### ISSUE TITLE
Add sample project for reference for Spring Metrics and Prometheus

### ISSUE THREAD

**Issue by checketts** [micrometer-metrics/micrometer#1]
I've created an initial sample project here https://github.com/checketts/spring-metrics-sample

Currently it doesn't do anything besides run. 

Metrics I want to express:

* Requests
* Annotations on endpoints
* Caches
* Database
* Executors (with `@Scheduled` usage too)
* Logback
* Demonstrate manual adding counters, gauges, and timers.

Also I want to include a sample Prometheus and Grafana config with explanations for the various useful metrics.

**Comment by jkschneider** [comment]
Would like to hear what you want to see monitored on Executors. Good thinking to tie instrumentation to `@Scheduled` in some way. Could be tricky though, as many `@Scheduled` methods are relatively long lived and would benefit from `LongTaskTimer`. Others, a simple `Timer`. How to distinguish between them?

**Comment by jkschneider** [comment]
For Logback, are you looking for a counter of messages at each log level?

**Comment by checketts** [comment]
If @Timer works with @Scheduled it think it will be sufficient. Just want to be sure to test/document it. 

For logback the counter at each level is perfect. I'm using it right now and it is very useful. So I just want to help streamline the config/setup

**Comment by jkschneider** [comment]
Logback support provided by `LogbackMetrics` binder in e2d873abd70c05ab4d6e5e9697dbe952f446fcb1.

**Comment by checketts** [comment]
With #7 fixes I'm able to see metrics and Logback is reporting. Now I'll revisit the sample project and  try to add the metrics I mentioned above.

**Comment by checketts** [comment]
I added `@Scheduled` and `@Timed` in the sample project, but wasn't able to get any metrics from them.

Is `@EnableAspectJProxy` required? (My @Scheduled code is being run)

**Comment by jkschneider** [comment]
I'll do another release, as things have shuffled around a bit related to @Scheduled

**Comment by jkschneider** [comment]
There has been more evolution on the default Prometheus case as well. `@EnablePrometheusMetrics` takes the place of `@EnableMetrics` + `@EnablePrometheusScraping` + registering the Prometheus meter registry. Have a placeholder for tag normalization that I haven't implemented yet in `PrometheusTagFormatter`.

**Comment by checketts** [comment]
> I'll do another release

Is the released code available in maven? I've just been running `./gradlew pTML` and referencing my local maven repo for now. I'm fine sticking with that since it let's me tweak it and send PRs when i find stuff

**Comment by jkschneider** [comment]
I have been publishing these pre-releases to jcenter and maven central. Since you are using `./gradlew pTML`, I suppose the issue remains, so I can dig into that.

BTW, [this](https://blog.jetbrains.com/idea/2016/10/intellij-idea-2016-3-eap-gradle-composite-builds-and-android-studio-2-2/) is even better than `./gradlew pTML` if you are using IntelliJ.

**Comment by jkschneider** [comment]
@checketts Pushed some changes to the sample project and tested it with the latest head.

**Comment by jkschneider** [comment]
There is a basic `PrometheusSample` in the spring-legacy project.

**Comment by checketts** [comment]
Yeah! I meant to call out how awesome the samples are and to close this.

Thanks!
