### ISSUE TITLE
Stackdriver: Monitor other resources type for k8s horizontal auto-scaling 

### ISSUE THREAD

**Issue by panthony** [micrometer-metrics/micrometer#1003]
Hi,

I have a spring boot application running in kubernetes with custom metrics published to stack driver for its horizontal auto scaling.

I'm interested in using the actuator+micrometrics to gather & handles them.

Do you plan to make the resource more configurable?

For my case here what is needed:

```java
        final Map<String, String> resourceLabels = new HashMap<>();

        // https://cloud.google.com/kubernetes-engine/docs/tutorials/custom-metrics-autoscaling#exporting_metrics_from_the_application

        resourceLabels.put("pod_id", config.podId);

        // must be set to empty string
        resourceLabels.put("container_name", "");

        // can be set to any value (unused)
        resourceLabels.put("namespace_id", "");
        resourceLabels.put("instance_id", "");

        resourceLabels.put("project_id", config.projectId);
        resourceLabels.put("cluster_name", config.clusterName);
        resourceLabels.put("zone", config.zone);

        return MonitoredResource.newBuilder()
            .setType("gke_container")
            .putAllLabels(resourceLabels)
            .build();
```

Maybe the StackdriverConfig could allows to configure the `type` and additional labels for the resource.

```java
public interface StackdriverConfig extends StepRegistryConfig {
    @Override
    default String prefix() {
        return "stackdriver";
    }

   default String resourceType() {
     //
   }

   default Map<String, String> resourceLabels() {
      // 
   }

    default String projectId() {
        String v = get(prefix() + ".projectId");
        if (v == null)
            throw new MissingRequiredConfigurationException("projectId must be set to report metrics to Stackdriver");
        return v;
    }
}

```

I'd be happy to provide a PR if you think it would be accepted.

**Comment by panthony** [comment]
@jkschneider  Here you have the list of labels per resource type: https://cloud.google.com/monitoring/api/resources#tag_gce_instance

>  I think we should create a builder class inside of StackdriverConfig that allows you to quickly build a StackdriverConfig instance for GKE

I'm actually using the metadata API to resolve everything (project.id included) from the `pod_id`, but using the tags & `resourceLabelKeys` approach I fails to see how it would be used.

Also,

In your exemple you are using `.` as separator (ex: `namespace.id` instead of `namespace_id`), does that mean that the StackDriver adapter should translate magically `.` to `_` to match the expected label name?

Does `.` has a special meaning in tag's name? I'm not that familiar with micrometer yet.

**Comment by jkschneider** [comment]
> In your exemple you are using . as separator (ex: namespace.id instead of namespace_id), does that mean that the StackDriver adapter should translate magically . to _ to match the expected label name?

Yes it does. Micrometer has a notion of `NamingConvention`s that are defined and customizable on a per-registry basis. Even though you may be exporting your metrics to Stackdriver right now, by using dot separated names for metric names and tag keys, your metrics are portable now to other monitoring systems that don't follow Stackdriver's opinions.

**Comment by tomwscott** [comment]
According to the [current](https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource) docs for Stackdriver Monitoring only these resource types support custom metrics:

- [aws_ec2_instance](https://cloud.google.com/monitoring/api/resources#tag_aws_ec2_instance)
- [dataflow_job](https://cloud.google.com/monitoring/api/resources#tag_dataflow_job)
- [gce_instance](https://cloud.google.com/monitoring/api/resources#tag_gce_instance)
- [gke_container](https://cloud.google.com/monitoring/api/resources#tag_gke_container)
- [generic_node](https://cloud.google.com/monitoring/api/resources#tag_generic_node)
- [generic_task](https://cloud.google.com/monitoring/api/resources#tag_generic_task)
- [global](https://cloud.google.com/monitoring/api/resources#tag_global)
- [k8s_cluster](https://cloud.google.com/monitoring/api/resources#tag_k8s_cluster)
- [k8s_container](https://cloud.google.com/monitoring/api/resources#tag_k8s_container)
- [k8s_node](https://cloud.google.com/monitoring/api/resources#tag_k8s_node)
- [k8s_pod](https://cloud.google.com/monitoring/api/resources#tag_k8s_pod)

_Each_ of these resource types has different requirements for the labels provided. Currently only the projectId is added as a label which is only valid for the `global` resource type. The documentation even recommends _not_ to use `global`

> Use this resource when no other resource type is suitable. For most use cases, generic_node or generic_task are better choices than global.

Configuring the registry for any other resource type results in errors buried in Stackdriver logs that look like: 
```
i.g.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: The set of resource labels is incomplete. Missing labels: (location namespace node_id).: timeSeries[0]
```
This could also be contributing a contributing factor for #1001 as the `MetricServiceClient` fails silently and just writes a log to Stackdriver. 

Updating the `StackdriverMeterRegistry` where it creates the `MonitoredResource` to include the required labels for each resource type will allow for metrics to be associated with these other resource types.

https://github.com/micrometer-metrics/micrometer/blob/6d615c4af01dcc8bf9e9b4d64c5bce7aba23b444/implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java#L338-L341

@jkschneider - if you're able to provide some guidance about pulling metadata from the Google Cloud compute metadata client I'd be happy to attempt a PR

**Comment by deanorderly** [comment]
I am integrating micrometer into the webpieces platform.

While doing that, I am using webpieces along with a project we built on webpieces in Google Cloud. 
 We are using stackdriver as the backend and this is the only post that came up when I searched for the error I ran into ...

"INVALID_ARGUMENT: One or more TimeSeries could not be written: The set of resource labels is incomplete. Missing labels: (cluster_name container_name instance_id namespace_id pod_id zone)."

and as tomwscott  points out, the resource type does not have the right labels set making the dimensional stuff not usable.  is there a fix/patch for this?

**Comment by HugoTigre** [comment]
with version 1.4.0 I was able to change the `resource type` to `gke_container` and pass it the respective resource labels that stackdriver needs, this works, this works just by overriding the new methods in `StepRegistryConfig`.

@deanorderly regarding this error

```
"INVALID_ARGUMENT: One or more TimeSeries could not be written: The set of resource labels is incomplete. Missing labels: (cluster_name container_name instance_id namespace_id pod_id zone)."
```

You need to fill out the necessary `resource labels` according to the `resource type`, this seems to be only possible in version 1.4.0.

My problem is that google's HPA has specific requirements on the metrics name, see [here](https://cloud.google.com/kubernetes-engine/docs/tutorials/custom-metrics-autoscaling#exporting_metrics_from_the_applicatio), basically they need a prefix of `custom.googleapis.com/` followed by a simple name, like `something_metrics_or_other`. And the way micrometer is exporting metrics, at least in Spring Boot, doesn't seem to follow this convention, they are all `custom/something/or/other`

I couldn't find a way to work around this.

**Comment by deanorderly** [comment]
@HugoTigre sorry, I didn't update....we got ours working and we use this class..

https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java

Does springboot NOT use that class?  That class is hardcoded to

            StringBuilder metricType = new StringBuilder("custom.googleapis.com/").append(getConventionName(id));

on line 427.

our issue now is we WANT like opencensus and other providers to override the very first thing in the path (we thought that was changing custom.googleapis.com but are not sure yet). See when searching for metrices, we want to type in 'servername' first so the auto complete works in google metrics.  CURRENTLY, we get metrics from ALL our servers which is pretty annoying not to mention the autocomplete box is finitely small making it hard to see what you are completing.

hmm, I wonder if I can hack and put a plugin to override their css so I can actually widen their autocomplete pulldown which would be very very nice.

we are using a snapshot of 1.4 as it wasn't released when we switched.  still haven't had time to check if it's released.

**Comment by HugoTigre** [comment]
`I wonder if I can hack and put a plugin to override their css`

lol, I have the same problem you have now idea how many times I've complained about this :)

Spring boot uses that, there is no problem with the `prefix` and there might not be a problem with the name metric also, for ex, for a metric in stackdriver that looks like this `custom/jvm/memory/used` in the `hpa.yml` config it should look like `custom|jvm|memory|used`. They have this on they documentation, but not in the documentation I was reading so I missed it.

In any case I still don't have it working to confirm that this was the only problem, but I should have news tomorrow and update here.

Regarding your issue, I guess that micrometer could provide a way to easily manipulate the prefix, or (don't know how you are create the `timeseries`) but defining every metric by `hand` you can always manipulate the name (not sure if this is the case)

**Comment by deanorderly** [comment]
yeah, we are trying to do what OpenCensus did like this (BUT replace the opencensus with each microservice name) as seen here

![image](https://user-images.githubusercontent.com/60440987/78187495-bd813a00-742b-11ea-8fe6-966b4975bd82.png)

**Comment by deanorderly** [comment]
lol, now I need to find a plugin that overrides very specific css as I just edited google's css in dev tools to get this so I can read crap...

![image](https://user-images.githubusercontent.com/60440987/78187780-4a2bf800-742c-11ea-9d9f-7f3b4779965e.png)

**Comment by HugoTigre** [comment]
i finally got it working, I had to problems in the end.

1. the metric `custom/jvm/memory/used` in `hpa` needs to be `custom.googleapis.com|jvm|memory|used` which is weird according to the official documentation 

2. we use `Workload Identity` for authentication in K8s, so we needed to change the original `custom metrics adapter` and map the k8s service account with a google service account.

I couldn't find anything about this in the documentation, especially how the metric is named in hpa.

**Comment by dantheperson** [comment]
@HugoTigre can you supply more details exactly how you provided the necessary labels for the other resource types?

I can't see any methods at all on StepRegistryConfig, let alone methods that allow me to supply extra labels.

**Comment by dantheperson** [comment]
nevermind... found it in StackdriverConfig rather than StepRegistryConfig

**Comment by shakuzen** [comment]
Closing this as it is possible to configure the resource labels since #1818 added that configuration. It would be good if we added such generic labels for users when available. Then we could map them to resource labels for Stackdriver as appropriate with less config required from users, and it would be consistently available across meter registries. However, getting the metadata seems challenging in a lot of cases since it isn't available in environment variables for containers out-of-the-box in generic kubernetes clusters. If there are ideas how we can do this in a generic way, please do open an issue and let's explore that.
