### ISSUE TITLE
Provide statsd support over tcp

### ISSUE THREAD

**Issue by JoshuaOliphant** [micrometer-metrics/micrometer#1009]
We are using Veneur https://github.com/stripe/veneur to ship statsd metrics, which supports both tcp and udp. It seems that micrometer only supports udp, and it would be nice if it also supported tcp.

**Comment by psycho-ir** [comment]
Hi, 

I just opened #1026 to address it.

**Comment by michaelmcfadyen** [comment]
Can this issue be closed?

**Comment by psycho-ir** [comment]
I believe so.

**Comment by izeye** [comment]
@michaelmcfadyen @psycho-ir Thanks! Closing as this has been resolved via #1026.
