### ISSUE TITLE
Revisit: Metrics getting cleared after export to InfluxDB

### ISSUE THREAD

**Issue by willmpls** [micrometer-metrics/micrometer#1013]
@jkschneider I wanted to revisit your comments in #755 and clarify your comment on InfluxDB's lack of rate functionality.  InfluxDB natively supports calculating rates from ever increasing counters via `non_negative_derivative` as documented here:

https://docs.influxdata.com/influxdb/v1.7/query_language/functions#non-negative-derivative

When exporting metrics to InfluxDB, I can't imagine a scenario where we would ever want to reset counter values, so wanted to get your thoughts.

The changes made in #265 for Prometheus are indeed what we'd like to see when exporting to InfluxDB so that the raw, non-reset counter data is stored directly in InfluxDB.

**Comment by marcingrzejszczak** [comment]
There was no interest in this issue since 2018. Let's close it for now and if there will be new interest, please comment on this closed issue and we will consider reopening it.
