### ISSUE TITLE
DefaultGauge WeakReference causes unit test to be flaky 

### ISSUE THREAD

**Issue by jlisam** [micrometer-metrics/micrometer#1014]
Hello 👋 ,

We currently have a project using micrometer version 1.0.6 and we ran into some flakiness in a test while using `SimpleMeterRegistry`. 

```java
 testSubscribingToMetrics FAILED
    org.junit.ComparisonFailure: expected:<[300.0]> but was:<[NaN]>
```

After further investigation, we believe it's because the weak object reference is gc'd so by the time it gets to  https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultGauge.java#L39, it's null and we end up getting a `NaN` as a result. 

```java
    @Override
    public double value() {
        T obj = ref.get(); // new WeakReference<>(obj);
        return obj != null ? value.applyAsDouble(ref.get()) : Double.NaN;
    }
```

Would it be possible to change the `SimpleMeterRegistry` to use a `Gauge` that does not use  `WeakReference` to objects? I am asking mainly for testing purposes. I am happy to work on a PR but wanted to check here first in case someone is already working on that or there are other plans for this. 

Thank you so much 🙇

**Comment by checketts** [comment]
The weak reference makes users have to intentionally keep references to objects that would get garbage collected otherwise (so metrics don't cause memory leaks). Keep in mind the `SimpleMeterRegistry` is useful outside of testing and is the base for alternative (home grown) metric registries, so it wouldn't be a good idea to make it a 'toy' registry.

Were you able to solve the reference collecting in your example? Perhaps documenting how to ensure the object it referenced an additional way would be useful?

Alternatively, you could subclass `SimpleMeterRegistry#newGauge` to create a different type of Gauge that doesn't use WeakReferences.

**Comment by jlisam** [comment]
> The weak reference makes users have to intentionally keep references to objects that would get garbage collected otherwise (so metrics don't cause memory leaks). Keep in mind the SimpleMeterRegistry is useful outside of testing and is the base for alternative (home grown) metric registries, so it wouldn't be a good idea to make it a 'toy' registry.

That makes sense. Perhaps we do need a "testing" registry. 

> Were you able to solve the reference collecting in your example? 

Yes! We were able to solve the reference issue by making sure that the object was referenced until the end of the test. 

> Perhaps documenting how to ensure the object it referenced an additional way would be useful?

That's a good idea. I can create a PR updating the micrometer documentation if you are open to it 😄 .

> Alternatively, you could subclass and override SimpleMeterRegistry#newGauge to create a different type of Gauge that doesn't use WeakReferences.

👍 good idea.

**Comment by checketts** [comment]
PRs are always welcome. Check out the docs repo: https://github.com/micrometer-metrics/micrometer-docs for those changes

**Comment by jkschneider** [comment]
@jlisam There are also strong reference gauges in Micrometer 1.1. You have to use the `Gauge.builder` fluent interface to create them.

**Comment by jlisam** [comment]
Thank you @checketts , @jkschneider !

**Comment by tkruse** [comment]
Hi, I ran into this as well. It would be nice if SimpleMeterRegistry javadoc warned about this. Currently it says: `A minimal meter registry implementation primarily used for tests.`, which is a bit ironic, given that it is not useful for others to be used for test assertions.

**Comment by jonatan-ivanov** [comment]
@tkruse All of the registries work like that so the javadoc of `MeterRegistry` mentions it.
Also, the docs site: https://micrometer.io/docs/concepts#_gauges

Please feel free to let us know/file a PR if you have improvement ideas.
