### ISSUE TITLE
Allow disabling of webserver

### ISSUE THREAD

**Issue by robertlemmen** [micrometer-metrics/micrometer#1015]
I am using micrometer in spring-boot with an influx exporter, so the web server isn't really necessary. I was hoping I could turn it off with e.g. spring.main.web-environment, but that does no loner seem to be the case once I include micrometer. please make it possible to turn this off

**Comment by izeye** [comment]
@robertlemmen Thanks for the report but I failed to see how an Influx meter registry and a web server are related. Could you help me understand this issue by providing a sample project to reproduce it?

**Comment by izeye** [comment]
@robertlemmen Thanks for the feedback! Closing as based on your response, it doesn't seem to be relevant to Micrometer. You'd better ask it with a sample on StackOverflow with the "spring-boot" tag. Also you might be interested in [the release notes for Spring Boot 2.1](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes).
