### ISSUE TITLE
Exception thrown by MicrometerCollector for a meter with a duplicate name does not include the name in its message

### ISSUE THREAD

**Issue by wilkinsona** [micrometer-metrics/micrometer#1016]
A typical message reads something like this:

> Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter containing tag keys [class, exception, method]. The meter you are attempting to register has keys [exception, method, outcome, status, uri].

Prompted by https://github.com/spring-projects/spring-boot/issues/15184, it would be helpful if the message included the name of the meter, rather than having to figure out what the name is likely to be based on the tag keys.

**Comment by izeye** [comment]
@wilkinsona Thanks for the suggestion! I created #1017 for it.
