### ISSUE TITLE
possible documentation err?

### ISSUE THREAD

**Issue by frko** [micrometer-metrics/micrometer#103]
![image](https://user-images.githubusercontent.com/1576993/29766356-c35d6800-8bde-11e7-9bb9-fdb3c1094d74.png)
the `server.request` tag is confusing me a bit, is the name indeed correct or perhaps some copy-paste thing?

**Comment by jkschneider** [comment]
The tag is correct, but perhaps we could come up with a less confusing example? In this case, `server.requests` is the tag value for the tag `id`. The example supposes that a single thread pool is being used for a variety of tasks, one of which is to handle server requests.

The example is incorrect for another reason though, which is that these metrics should be gauges and not counters. I'll change it to something more sensible.

Thanks for pointing it out!

**Comment by frko** [comment]
Very nice and quick response @jkschneider , thank you for the cooperation, really like it.

**Comment by jkschneider** [comment]
The sample has been corrected in the latest doc update.
