### ISSUE TITLE
@TimedSet annotation ignored

### ISSUE THREAD

**Issue by bratwurzt** [micrometer-metrics/micrometer#1032]
I wanted to use multiple @Timed annotations and found @TimedSet, but found no aspect for it. After some unsuccessful searching I came here. Not sure if it's a bug, though.

**Comment by jkschneider** [comment]
What would the purpose of this be?

**Comment by bratwurzt** [comment]
Sorry for late reply - I misunderstood how filters work and went about it the wrong way. You can close this, as it seems totally unnecessary to have multiple annotations of @Timed type.
