### ISSUE TITLE
Rates for counters could be configurable

### ISSUE THREAD

**Issue by slomo** [micrometer-metrics/micrometer#1034]
I am porting an existing system from drop wizard to micrometer with the graphite reporter. Creating a counter (via `meterRegistry.counter("name")`)  will always result in multiple metrics report to graphite (`name.counter`, `name.mean_rate`, `name.m5_rate`, `name.m10_rate`, `name.m15_rate`). While this probably is a reasonable default for most use cases, it might make no sense for others.

In my case I am using the counters to sum up a physical property that is observed for my system (eg the absolute weight of material, that has passed a certain electronic scale sensor). The rate is completely meaningless for me in this concrete example. It might not be the best metric to watch, but I have existing data some years back and would like to be able to keep the same data. It happens that I have a few hundreds of these properties, that I have to monitor. This results in an increase preasure on my graphite server.

Hence my question would be: Would an option to disable these additional metrics be possible? So instead of always relying on `com.codahale.metrics.Meter`, I would like to have an option to switch to a plain `com.codahale.metrics.Counter`.

https://github.com/micrometer-metrics/micrometer/blob/8b1273849004b19965db4f4865a6921fd4663ed2/micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardMeterRegistry.java#L59

I would totally understand, if that is out of scope for the project. My current work around is to use `AtomicLongs` instead and hooking up Gauges to them. Which requires me in some places to do wired stuff to keep references to those longs.

**Comment by jkschneider** [comment]
You should be able to use strong reference gauges now, for which there is a convenience method:

```
Gauge.builder("absolute.weight", () -> absoluteWeight()).register(registry);
``` 

Or

```
Gauge.builder("absolute.weight"), new WeightMeasurer(), measurer -> measurer.weight())
   .strongReference()
   .register(registry);
````

I don't think we want to encourage cumulative count monitoring through the `Counter` API, however, since this is in most cases a serious anti-pattern (counts get reset on instance restart, are a function of both the rapidity of increment and duration of instance life of which the latter is typically irrelevant).

**Comment by jkschneider** [comment]
Since I think this satisfies your need conveniently enough, I close this. Feel free to reopen if it doesn't!
