### ISSUE TITLE
Spring Boot application only reports metrics for 200 OK responses

### ISSUE THREAD

**Issue by fiunchinho** [micrometer-metrics/micrometer#104]
I have a Spring Boot application using micrometer to expose metrics to Prometheus. Even though I force some 404 errors by hitting non existing URL's, only 200 OK responses are being exposed

```
# HELP http_server_requests_duration_seconds  
# TYPE http_server_requests_duration_seconds summary
http_server_requests_duration_seconds_count{exception="None",method="GET",status="200",uri="/",} 4.0
http_server_requests_duration_seconds_sum{exception="None",method="GET",status="200",uri="/",} 0.018537225
http_server_requests_duration_seconds_count{exception="None",method="GET",status="200",uri="/hello",} 4.0
http_server_requests_duration_seconds_sum{exception="None",method="GET",status="200",uri="/hello",} 0.007250141
```

How can I get metrics for all HTTP status codes?

**Comment by fiunchinho** [comment]
If I define an endpoint that only returns 404, then I get it for that particular URL, but not for the non existing url's

```
    @RequestMapping("/404")
    public ResponseEntity not_found() {
        return new ResponseEntity(HttpStatus.NOT_FOUND);
    }
```

**Comment by checketts** [comment]
The metrics are being recorded via an interceptor, meaning the request needs to make it that far to trigger a metric. If you want to record metrics on all requests, I recommend creating a filter.

I believe Micrometer should offer a filter for this purpose too, but it doesn't currently.

**Comment by jkschneider** [comment]
This is what I'm getting from `PrometheusSample` when I hit a non-existent API endpoint:

![image](https://user-images.githubusercontent.com/1697736/29779445-32903c72-8bd8-11e7-97e9-60aee60e91cf.png)

@checketts the `HandlerInterceptorAdapter` does appear to be called for 404s. What am I doing differently?

**Comment by checketts** [comment]
@jkschneider Do you have a `@RequestMapper` for `/error`?

**Comment by fiunchinho** [comment]
What is PrometheusSample` @jkschneider?

**Comment by jkschneider** [comment]
I did not explicitly provide a `@RequestMapper`. Must be something Boot adds?

**Comment by jkschneider** [comment]
Can recreate it from a simple app generated by start.spring.io with dependencies:

```groovy
dependencies {
    compile("org.springframework.boot:spring-boot-starter-web:1.5.6.RELEASE")
    compile 'io.micrometer:micrometer-spring-legacy:0.10.0.RELEASE'
    compile 'io.micrometer:micrometer-prometheus-starter:0.10.0.RELEASE'
}
```

**Comment by jkschneider** [comment]
Verified the behavior is correct in 0.11.0 snapshots.
