### ISSUE TITLE
meter only root logger log4j2

### ISSUE THREAD

**Issue by z0mb1ek** [micrometer-metrics/micrometer#1042]
Hi. I see in Log4j2Metrics that you add only ROOT logger. Why? Can I meter my loggers too?

**Comment by izeye** [comment]
@z0mb1ek Looking at the code, I can see the filter being added on the root logger, so I expect it will meter all loggers. Do you mean it meters only the root logger or you want to have per-logger meters?

**Comment by z0mb1ek** [comment]
@izeye thx for reply. Yes, I tested it and it meters ONLY root logger :( I want to meter all my loggers together and my be it would be useful to configure what logger to meter.

**Comment by izeye** [comment]
@z0mb1ek Looking at [its test](
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/logging/Log4j2MetricsTest.java#L53), it seems to work for other loggers. Could you provide a sample project to reproduce it?

**Comment by z0mb1ek** [comment]
@izeye its about configuration of log4j2
For example:
```  Loggers:

      Root:
        level: info
        AppenderRef:
          - ref: Console_Appender

      Logger:
        - name: com.skipz
          additivity: false
          level: debug
          AppenderRef:
            - ref: Console_Appender
```
in this logs from com.skipz package will not meter.

**Comment by izeye** [comment]
@z0mb1ek Thanks for sharing a sample configuration! The test uses [a logger named its own class name](
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/logging/Log4j2MetricsTest.java#L37). I’m not sure whether the `additivity` configuration could affect here somehow. I can see your logger levels are different, so could you confirm the application logged something at debug level with the non-root logger?

**Comment by z0mb1ek** [comment]
@izeye yes. Or it can be kafka client with error level only for example, because it writes very much logs.

**Comment by izeye** [comment]
@z0mb1ek I confirmed it's working with a sample: https://github.com/izeye/sample-micrometer-spring-boot/tree/log4j2

The only remaining difference I noticed is the `additivity` flag. I'll try to check this later but if you could provide a sample to reproduce this on GitHub, it'd be appreciated.

**Comment by z0mb1ek** [comment]
@izeye can you show me log4j2 config in this project? Looking at the code this log to root too

**Comment by izeye** [comment]
@z0mb1ek It's using the Spring Boot default configuration and there's [a sample logging with a non-root logger](https://github.com/izeye/sample-micrometer-spring-boot/blob/log4j2/src/main/java/com/izeye/sample/web/SampleController.java#L30). You can check it's working by seeing the Spring Boot Actuator metrics endpoint.

**Comment by z0mb1ek** [comment]
@izeye its by default ROOT!!!! I PR to you my config

**Comment by z0mb1ek** [comment]
now if you comment
```
#    Logger:
#    - name: com.izeye.sample.web
#      additivity: false
#      level: info
#      AppenderRef:
#      - ref: Console_Appender
```
it will work

**Comment by izeye** [comment]
@z0mb1ek I'm confused with the "ROOT" in the context. Do you use "ROOT" to mean an appender attached to the root logger, not the root logger?

**Comment by z0mb1ek** [comment]
@izeye I test it more, you was right, its about additivity flag.

**Comment by izeye** [comment]
@z0mb1ek Thanks. I reproduced it and created #1045 to try to resolve it.
