### ISSUE TITLE
Expose a meter id that contains both normal and convention names and tags

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#105]
From @trustin on Slack initially:

> It seems like some `Meter` implementations' `getName()` return the convention name while some other do not. e.g. `registry.counter(String, String...)` vs `registry.more().counter(...)`

Furthermore:

> You can get the complete list of meters using getMeters(). If we call .getName() on all meters in it, you'll find inconsistency. Function tracking counters and ordinary counters have different naming style for example.

**Comment by checketts** [comment]
Looks great! Thanks!
