### ISSUE TITLE
Prometheus Exposition Formats (Timestamp)

### ISSUE THREAD

**Issue by tuc48831** [micrometer-metrics/micrometer#1051]
This is more of a question, is there any way that the Prometheus Meter Registry can support Promtheus Exposition Formats (https://prometheus.io/docs/instrumenting/exposition_formats/)? We have a use case where we want to have the timestamp on the end of the metric.

Right now it looks like the registry only ever creates samples inside of the meters without capturing the timestamp (it uses the overloaded constructor to recall the other sample() constructor with a null long where the timestamp would be), and I don't see a way to capture the timestamp as a configurable setting or anything. I looked into extending the Meter registry to override the methods but a bunch of the meter have package level visibility so it feels like I'd basically need to redundantly remake everything.

Any help would be greatly appreciated!

**Comment by jkschneider** [comment]
Since Micrometer uses the Prometheus java client under the hood, is it possible to do this with the simpleclient?

**Comment by tuc48831** [comment]
As far as I can tell, it looks like the simple client's Sample constructor inside collector is now overloaded and supports having timestamps and not having timestamps: https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/Collector.java#L82 (sorry if I misunderstood the question, I'm a new software developer). I couldn't think of a good way to extend/override anything to make this as easy as it feels like it should be but maybe I just haven't been creative enough yet.

**Comment by jkschneider** [comment]
Thanks. Can you elaborate on the situations that you confront that you'd like timestamps for?

**Comment by tuc48831** [comment]
From what my co-worker explained to me, we were experiencing a problem with staleness in the event that one of a restart/outage. In order to help us with the staleness issue, we came to the conclusion timestamps would be a good solution. From https://prometheus.io/docs/prometheus/latest/querying/basics/ : "Staleness will not be marked for time series that have timestamps included in their scrapes. Only the 5 minute threshold will be applied in that case."

**Comment by jkschneider** [comment]
@tuc48831 Thanks for the response. This is such an idiosyncrasy of Prometheus that we couldn't surface "to timestamp or not to timestamp" on meter creation in a general way. So I think we need to either configure a Prometheus registry to always include timestamps or always not include timestamps. Would always including timestamps have a deleterious effect in some other way?

**Comment by mweirauch** [comment]
From everything I read, a user supplied timestamp really is indicating the "when" this value occurred. (In Prometheus terms, that timestamp will be used as the "scrape time" which is attached to the metric before it is written to the metrics store in opposite to the current timestamp being as the scrape time when no timestamp is given.)

I am just trying to understand the problem before introducing timestamps which are considered a niche usecase from what I grasp.

How does/did the staleness issue materialize in your case?

**Comment by jkschneider** [comment]
> before introducing timestamps which are considered a niche usecase from what I grasp.

It's my intuition as well that this is niche, which has me worried about an always on/off switch.

**Comment by tuc48831** [comment]
We ended up just writing a static timestamp onto the end of every line after we generate the prometheus scrape because we actually end up forwarding that to a different location so this isn't really needed anymore.

**Comment by gangakrishh** [comment]
@jkschneider we've scenario .. we are pulling the metrics from cloudwatch and want to push to Promtheus using spring-boot/micrometer, so cloudwatch metrics provides the timestamps want to push metrics as it is including timestamps..

**Comment by kingbabingge** [comment]
I have the same problem，we are pulling the metrics from one software and want to push to prometheus using spring-boot/micrometer，the software provides the timestamps ，and we want micrometer transmit it.

**Comment by shakuzen** [comment]
Please create a new issue explaining your use case if you think there's a change to make in Micrometer. Micrometer doesn't ingest metrics from backends, so I don't understand how it is involved. Timestamps in the Prometheus scrape are generally discouraged, as mentioned in previous comments. It's a shame their [documentation](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details) gives no explanation. The OpenMetrics specification (standardization of the Prometheus exposition format) provides some [commentary on timestamps](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exposing-timestamps). I also found there is a [CloudWatch Exporter](https://github.com/prometheus/cloudwatch_exporter) provided by Prometheus.

**Comment by gangakrishh** [comment]
@shakuzen thanks for responding. [CloudWatch](https://github.com/prometheus/cloudwatch_exporter) not efficient one makes lot of calls since it uses GetMetricStatistics api insteadof GetMetricData.  lot of calls means lot of money have to pay to aws..
