### ISSUE TITLE
Description and unit of "executor.queued" is wrong

### ISSUE THREAD

**Issue by janssk1** [micrometer-metrics/micrometer#1060]
"executor.queued" 's description says it is a gauge of threads. But actually, it repesents tasks waiting for execution. Quite confusing.

Current code: in ExecutorServiceMetrics
Gauge.builder("executor.queued", tp, tpRef -> tpRef.getQueue().size())
                .tags(tags)
                .description("The approximate number of threads that are queued for execution")
                .baseUnit("threads")
                .register(registry);

**Comment by izeye** [comment]
@janssk1 Thanks for the report! I think you're right. It seems like a copy/paste error. I created #1061 to resolve it.
