### ISSUE TITLE
Metric names are changed in Prometheus

### ISSUE THREAD

**Issue by crmky** [micrometer-metrics/micrometer#1063]
I didn't aware the baseUnit is part of the metric name in Prometheus (PrometheusNamingConvention).

Now with the change of "baseUnit" by
https://github.com/micrometer-metrics/micrometer/commit/cf4a94cb96d25a5aae0084b738c5b7a525ce7782#diff-abb051f108aaf982e8a930524c212f65, several metric names are changed in Prometheus.

This is an incompatible change, but I didn't see this behavior is mentioned in anywhere. Do we want to keep this behavior, or remove base unit from Prometheus metric name?

**Comment by jkschneider** [comment]
Sorry for any trouble this caused. I think the lacking units was an error of omission previously, and adding the base unit as a suffix in Prometheus does seem to be the most idiomatic for Prometheus. A `MeterFilter` could be used to strip units if you need, or the naming convention can be overridden if necessary.

Any other thoughts?

**Comment by crmky** [comment]
I'm ok with that if you think that's the right direction for Micrometer.

My major concern is most people only consider metric name (as well as tags) as the contract, so they are free to modify other fields (description and etc). They just don't aware change baseUnit will change metric name in other MeterRegistry.

Maybe you can consider to improve document for that, especially for this one: https://micrometer.io/docs/concepts#_naming_meters

**Comment by jkschneider** [comment]
I understand your concern. The naming section of the doc does kind of highlight how Prometheus is different. The example shows that the base unit of "seconds" is suffixed to the name.

**Comment by bbzg** [comment]
I ran into this today after upgrading Spring Boot version. Kind of jarring to go from green to red in the alerts section. Kind of... bad?

**Comment by jkschneider** [comment]
@bbzg Sorry to cause you trouble. I'm not sure what we could really do differently. The lack of base unit was an error of omission and I think it's correct for base units to be suffixed on the Prometheus naming convention given what's idiomatic there. We try to keep metric names stable across minor releases at least.
