### ISSUE TITLE
Cloudwatch registry publish CallBack

### ISSUE THREAD

**Issue by alexvuta** [micrometer-metrics/micrometer#1066]
Hello,

I am working on implementation of micrometer with springboot and cloudwatch registry.
The scope is to push metrics to cloudwatch from a AWS Lambda.
The MetterRegistry method close, is asynchronous so the lambda context will be killed when the job was finished before all metrics are pushed to cloudwatch.

My 'quick and dirty" solution was:
```
/**
	 * Recursive function that wait until MeterRegistry thread is closed ( prevent
	 * metrics to be lost)
	 * 
	 * @param meterRegistry
	 * @return
	 */
	private static MeterRegistry waitMeterRegistry(MeterRegistry meterRegistry) {
		try {
			Thread.sleep(2000);
			if (meterRegistry.isClosed()) {
				logger.info("MeterRegistry closed succesfully!");
				return meterRegistry;

			} else {
				logger.info("Wait 2 seconds for MeteRregistry to close...");
				return waitMeterRegistry(meterRegistry);
			}
		} catch (Exception e) {
			logger.error(
					"Unable to wait MeterRegistry clean closing! Some metrics data will be lost because the application will stop running before pushing the metrics");
		}
		return meterRegistry;

	}
```

The CloudWatchMetterRegistry bean from implementation consume the callback inside his own method: 
```
 private void sendMetricData(List<MetricDatum> metricData) {
        PutMetricDataRequest putMetricDataRequest = new PutMetricDataRequest()
                .withNamespace(config.namespace())
                .withMetricData(metricData);
        amazonCloudWatchAsync.putMetricDataAsync(putMetricDataRequest, new AsyncHandler<PutMetricDataRequest, PutMetricDataResult>() {
            @Override
            public void onError(Exception exception) {
                logger.error("Error sending metric data.", exception);
            }

            @Override
            public void onSuccess(PutMetricDataRequest request, PutMetricDataResult result) {
                logger.debug("published metric with namespace:{}", request.getNamespace());
            }
        });
    }
``` 
So the question is: 
**How can I access the callback for recover the push result inside my Lambda function, to be able to make a clean exit at the end of execution** ?

Thanks!

**Comment by alexvuta** [comment]
Perfect!
Thanks, you are very reactive 👍

**Comment by alexvuta** [comment]
I am coming back with a little fix.
Before closing thread please call shudown method on AmazonCloudWatchAsync to avoid stacktraces from AmazonClientException.

Thanks!

**Comment by jkschneider** [comment]
@alexvuta Open to more discussion on this, but it feels wrong to me to call `AmazonCloudWatchAsync#shutdown` on `CloudWatchMeterRegistry#close` because you supplied the started AWS client in the constructor. Feels like the lifecycle of this client is the responsibility of the piece of code that injected it in the first place?

**Comment by alexvuta** [comment]
@jkschneider I agree with you. Sorry for the confusion 👍 After  5591728 fix will be ok because the thread will wait until the push is finished.
