### ISSUE TITLE
Static initializers of the Tags class are not null-safe

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#1078]
It seems that some of the methods in the `Tags` class are null-safe (e.g.: `and(...)`) and some of them are not (`of(...)`). The practical reason behind this is the fact that I bumped into a library which is using some of these methods with null parameters (https://github.com/codecentric/chaos-monkey-spring-boot) which will result in NPE.

This is my proposed change, I would be happy to submit it as a PR: https://github.com/jonatan-ivanov/micrometer/commit/06c76aa15e078e32e9aaa692b5e3b883c10d7fc0

**Comment by jkschneider** [comment]
I agree, consistency makes sense here.
