### ISSUE TITLE
micrometer-registry-statsd exports unrecognized time-unit `ms` to datadog

### ISSUE THREAD

**Issue by rreimann** [micrometer-metrics/micrometer#1083]
It seems that the statsd registry with flavor `datadog` exports unit `ms` instead of `millisecond` for timers which is not recognized by datadog: https://docs.datadoghq.com/developers/metrics/#units

The wrong `ms` unit is derived from [FlavorStatsdLineBuilder.java#L34](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/FlavorStatsdLineBuilder.java#L34) and could be overridden to `millisecond` in [DatadogStatsdLineBuilder.java](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/DatadogStatsdLineBuilder.java)

Opposed to micrometer-registry-statsd the micrometer-registry-datadog is aware of the units recognized by datadog - cf. [DatadogMetricMetadata.java#L30](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMetricMetadata.java#L30)

**Comment by jkschneider** [comment]
I'm not sure there is a way for us to ship base units on dogstatsd lines.

**Comment by rreimann** [comment]
Feel free to close the issue if there's no way to provide units via dogstatsd.
