### ISSUE TITLE
Add Description to metrics

### ISSUE THREAD

**Issue by Chase22** [micrometer-metrics/micrometer#1088]
In Prometheus you can print a descriptive comment with each metric. At the moment this is generated by micrometer and only supports very basic information for the metric.

It would be helpful if we could support custom description for metrics.

I opened this as an issue to discuss the possibilities of publishing those descriptions in other systems, since i'm only familiar with prometheus

**Comment by Chase22** [comment]
Reading the docs can often help. I just realized that the Metric builder already supports adding descriptions to metrics

**Comment by jkschneider** [comment]
@Chase22 No problem ;). I just want to add that if you are dissatisfied with the description provided by an automatically-instrumented metric (either in a `MeterBinder` or one provided by a framework like Spring Boot) you can alter the description text with a `MeterFilter`.
