### ISSUE TITLE
GKQuantiles insertAsNewMaximum 

### ISSUE THREAD

**Issue by shichaoyuan** [micrometer-metrics/micrometer#109]
https://github.com/micrometer-metrics/micrometer/blob/5ba0b887171c4496c576fbb2a2cb79a42a9c18c8/micrometer-core/src/main/java/io/micrometer/core/instrument/stats/quantile/GKQuantiles.java#L212

if (item == maximum) {
...
}

I don't think it necessary to deal with this situation.

**Comment by jkschneider** [comment]
Fixed in 1.0.0-rc.3 when Histogram/Quantile implementations were replaced by HdrHistogram.
