### ISSUE TITLE
Please add formatter and import order settings 

### ISSUE THREAD

**Issue by OleksiiBondar** [micrometer-metrics/micrometer#1090]
Please add code style formatter and import order settings to the repo so that every contributor will use the same settings. 
After this is done, we could also bring spotless plugin (https://github.com/diffplug/spotless) and appropriate step in build process to validate/apply consistent formatting to all java-files.

**Comment by mweirauch** [comment]
To my knowledge, spotless only supports the Eclipse formatter. This would mean trying to export the IDEA settings to Eclipse and then dumping them into SCM. Same goes for the import ordering.

**Comment by jonatan-ivanov** [comment]
+1

Also, according to @jkschneider, the project is using IntelliJ defaults right now.

**Comment by OleksiiBondar** [comment]
@jonatan-ivanov Not all contributors are using Intelij. And it's already misformatted in multiple places. 
It's definitilly has low priority but a good improvement going forward.
If not, who want to volunteer to keep formatting whole repo on some schedule basis (i.e. once a month)?

**Comment by jonatan-ivanov** [comment]
@OleksiiBondar I completely agree with you, that was my observation too. :)
I think adding formatter rules would be very beneficial here.

**Comment by jkschneider** [comment]
Agreed it would be beneficial to have as rules, especially for PRs we merge without noticing import ordering issues.

**Comment by izeye** [comment]
This seems to have been superseded by applying Spring Java Format.

**Comment by shakuzen** [comment]
Superseded by #3156
