### ISSUE TITLE
Micrometer not working with wavefront proxy

### ISSUE THREAD

**Issue by nyivan** [micrometer-metrics/micrometer#1092]
Hello, Since some time I struggle when trying to use the micrometer wavefront registry in proxy mode.
It is just not working with the latest Wavefront API. A colleague of mine(who is a part of the Wavefront team) opened a pull request which is fixing the issue. Can you please take a look at the [pull request](https://github.com/micrometer-metrics/micrometer/pull/905) and give us some feedback on when/if it can be accepted? 

Thanks!

**Comment by nyivan** [comment]
Hello, Is there any news regarding this issue?

**Comment by nyivan** [comment]
Thanks for the information! Do you have some rough estimate on when 1.2.0 will be released?

**Comment by shakuzen** [comment]
@nyivan the pull request has been merged. You can try out snapshots and let us know if it has resolved the issue. We're working on the plans for 1.2.0 and will be updating a tentative date for it on the milestone soon.
I'll close this issue assuming the mentioned pull request fixed it. If that is not the case, let us know the details and we'll reopen this issue.
