### ISSUE TITLE
0 value send to influx-DB for unchanged counter

### ISSUE THREAD

**Issue by Simulant87** [micrometer-metrics/micrometer#1093]
I am using micrometer-registry-influx, version: '1.0.6'.

When I create a counter and incremnt it the value is successfully send to Influx-DB
meterRegistry.counter("counter_name").increment();

Values for "counter_name"

no | time                  | metric_type | value
-- | ---------------- | ------------ | -------
1 |12/21/2018 2:20:00 PM |counter |1
2 |12/21/2018 2:21:00 PM |counter |0
3 |12/21/2018 2:22:00 PM |counter |0
4 |12/21/2018 2:23:00 PM |counter |0
5 |12/21/2018 2:24:00 PM |counter  |0

Afterwards for every reporting "step" a zero value is logged into the Influx-DB, even when the counter was not incremented.

For a DistributionSummary it is even worse, because all the 0 values are listed in my dashboard and for my usecase 0 is also a valid value.

Why are the zero values written to Influx-DB and isn't this a huge waste of transfered and stored data without any meaning?

I also tried with micrometer-registry-influx, version: '1.1.1', same result.

The same question is here on Stackoverflow: https://stackoverflow.com/questions/53177649/micrometer-sending-metrics-zero-spring-boot

Adjusting the "step" size does not really solve the problem. Especially when I have one counter that should be report frequently to get fast insights and another counter is just used occasionally but both are reported with the same step size.

**Comment by jkschneider** [comment]
> Why are the zero values written to Influx-DB and isn't this a huge waste of transfered and stored data without any meaning?

A zero value in this case means no additional samples were seen in this interval. Not sending anything at all could suggest that the application was not able to deliver a value at all to the monitoring system. So I don't believe sending a zero is a waste.

I'm interested in your feedback on this idea, but I've often seen this conversation go a certain way:

X: I don't want to ship 0 values for counts (sums, maxes, etc.)
Me: Why?
X: It takes up space for no reason
Me: How much space would have been consumed if exactly one event happened per interval? (Answer: the same amount of space that all of these zeroes plus any non-zero values take)
X: But this counter (timer, summary, etc.) is bursty.
Me: I worry first about a capacity plan that relies on a certain periodic shape in your traffic. Failing this, you could use `MeterRegistry.remove` when the counter goes un-utilized.

If we get all the way to the end of this conversation, and `MeterRegistry.remove` seems like what you want, I can understand that it is inconvenient. After all, you need to keep track of things that go unused and call remove on them after some time. I think we need a configurable expiry mechanism on meters that just lets them track their own internal state and after reporting zeroes for so many intervals just remove themselves. Seems to me that this would be the best compromise.

**Comment by jkschneider** [comment]
Thanks @Simulant87. Closing in favor of #1114

**Comment by 66-24** [comment]
So if we dont report unchanged metrics how does one distinguish between "app not sending metrics say because reporting thread died" vs "app not sending unchanged data" ?
