### ISSUE TITLE
Add support for ExceptionMetric

### ISSUE THREAD

**Issue by OleksiiBondar** [micrometer-metrics/micrometer#1097]
There is a need to be able to capture exceptions (i.e. business logic exceptions while processing/validating input). 
As a owner of such repo that throws various technical and business exception I want to have an ability to report them to the registry (influx, datadog, newRelic, etc) for future analysis, monitoring, alerting, historical trends, etc.
As a workaround, we could probably utilize Counter metric, but usage is very limited and concept becomes misleading. 
We could express Exception metric with:
 - exception stacktrace;
 - error severity (ERROR, WARN, INFO, etc;
 - unique transaction identifier as tag (to correlate with data in logs).

P.S. Not sure whether it can be well generalized across various registries, but in Datadog exceptions can be expressed as Event with some specific capabilities (dashboards, alerts, etc).
https://docs.datadoghq.com/monitors/monitor_types/event/
https://github.com/DataDog/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/Event.java

**Comment by checketts** [comment]
I could see a utility helper class could be helpful. However only the exception type could be of interest (unless you would like to include some example usecases that clarify needs)

Usage example without helper:
```
try {
  //my code that throws an exception
} catch (Exception e) {
  meterRegistry.counter("exception_counter", Tags.of("type", e.getClass())).increment();
  //rethrow exception
}
```

Potential API
```
meterRegistry.more().exceptionCounter(() -> {
  //my code that throws an exception
})
```

Unfortunately I don't foresee this being useful except in the outer-most layer of an application, like in the case of a `@ControllerAdvice` with a common `@ExceptionHandler` that would create an counter of uncaught exceptions, and even then I think the current counter approach works fine without needing an additional helper.

I recall discussing the usefulness of a Micrometer abstraction over events. Does that exist yet @jkschneider ?

**Comment by bisoldi** [comment]
+1 In my application, specific exceptions can warrant simply replacing a degraded instance, the need for a larger instance, a bug in the code, etc.

**Comment by OleksiiBondar** [comment]
As it was mentioned before, yes - we could workaround it by utilizing existing Counter and Timer metrics (that's what's already happening for certain applications where people want to keep track of exceptions), but this is very misleading - as a developer I might not need to count or express them with time. Worth to mention, that capabilities of such approach are limited - not many useful information can be derived/harvested just by tagging exception name, unless you have hierarchy of exceptions per failure/use case.

The way we are expressing exceptions in our current project might not be very generic and definitely specific to certain Datadog features. This is not a silver bullet, but I want to bring it here so that we can have discussions whether it can be generalized across other registries supported by Micrometer.

In Datadog there is a specific entity that represents activity - https://github.com/DataDog/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/Event.java.
We've utilized this capability to represent Exception metrics. Datadog out-of-the-box has number of features that allow to slice and dice stream of events in various representations - 
https://docs.datadoghq.com/graphing/event_stream/
For example, here is how we utilized it:
1. All exceptions/events are visualized on the DD dashboard using Event Stream panel;
![image](https://user-images.githubusercontent.com/4628962/50506444-de3f3080-0a2d-11e9-894e-a1f87ad18ef4.png)
2. Events also used  as real-time alerting mechanism - events marked with specific flag/tag that are actionable for oncall person reported to PagerDuty/Slack/Email for future analysis/investigation;
Datadog allows to achieve this with https://docs.datadoghq.com/monitors/monitor_types/event/.
3. Event can be expressed/customized per specific app - for our use case we've decided that event should contain error title, root cause exception stack trace, unique transaction identifier (to ease locate error in logs) and specific tags to determine environment, host, application name, etc.
4. After events delivered to Datadog they can be visualized and queried under various angles - count, distribution over the time, search by specific tags, exceptions, etc.

Again, it might not address all needs, but idea here is to share specific use-cases that people are trying to address and come up with some generic mechanism to address these needs.

**Comment by jkschneider** [comment]
I'll also throw out a variant of @checketts suggestion, where the helper is down on the `Tags` class instead so it can be used on any meter type without requiring an `exceptionCounter`, `exceptionTimer`, `exceptionSummary`, etc.

Usage example without helper:

try {
  //my code that throws an exception
} catch (Exception e) {
  registry.counter("exception.counter", Tags.of("type", e.getClass())).increment();
  //rethrow exception
}

Potential API

```
registry.counter("exception.counter", Tags.exception(e)); // (1)
registry.counter("exception.counter", Tags.concat(Tags.exception(e), "status", "NOT_OK") // 2
registry.counter("exception.counter", Tags.exception(e, "exception.name")); // 3
```

1. Add a tag with key `exception` where value is the exception class simple name.
2. Add an exception tag along with some other tag.
3. Add a tag with a customizable key where value is the exception class simple name.

Now this doesn't take care of the boilerplate of the try block and rethrowing the exception, but perhaps other libraries with functional try logic might be already well suited. Consider one well-known example (vavr):

```
Try.of(() -> { /* something potentially fatal */ })
      .onFailure(t -> registry.counter("exception.counter", Tags.exception(e)).increment())
      .get(); // 1
```

1. Only call `get()` if you care about the return value of the `of` block.

**Comment by marcingrzejszczak** [comment]
Can we accept Jon's answer as the correct one?
