### ISSUE TITLE
Incorrect MeterFilter documentation

### ISSUE THREAD

**Issue by bisoldi** [micrometer-metrics/micrometer#1099]
The Concepts documentation for MeterFilter shows a convenience method `acceptNameStartsWith`, however MeterFilter contains no such method.

https://micrometer.io/docs/concepts#_convenience_methods
> acceptNameStartsWith(String) - Accept every meter with a matching prefix.

I found this because I was looking for a way to specify common tags on a per Meter basis, rather than for the entire Registry.  Other than knowing the Meter.Id, which doesn't seem easily done because the Id is created internally and can't be created externally, I don't see a way to accept a Meter by name and then set tags.

If it helps, I cross-posted this question on SO.

https://stackoverflow.com/questions/53925641/micrometer-common-tags-for-specific-metrics

Does anyone have a good solution for this, other than creating a separate MeterRegistry?

**Comment by izeye** [comment]
@bisoldi Thanks for the report! For the inconsistency part I created #1100 to align with doc.

For the question part it seems to be resolved in StackOverflow.
