### ISSUE TITLE
dynatrace limits uploads to 15k

### ISSUE THREAD

**Issue by pjfanning** [micrometer-metrics/micrometer#1104]
I suggest that we can support a dynatrace.maxMessageSize property.

https://github.com/kontainers/micrometer-registry-dynatrace/commit/48e27c7d428812f773978854b93692dc34319408 has an implementation where if the limit is reached, the upload data is split over multiple messages.

**Comment by jkschneider** [comment]
Does dynatrace blow up if the 15k limit is exceeded?

**Comment by pjfanning** [comment]
Dynatrace rejects the message if it exceeds 15k.

**Comment by jkschneider** [comment]
Good to know. Is there any value then in making the max size configurable?

**Comment by pjfanning** [comment]
In https://github.com/kontainers/micrometer-registry-dynatrace/commit/48e27c7d428812f773978854b93692dc34319408 - I split the message into mutiple messages so that none exceeds the maxMessageSize.

**Comment by pjfanning** [comment]
I guess we could hardcode 15k. I can put together an MR in the coming days.
