### ISSUE TITLE
OkHttp deduce dynamic tags from headers

### ISSUE THREAD

**Issue by nyilmaz** [micrometer-metrics/micrometer#1106]
`OkHttpMetricsEventListener` is supplied to OkHttp client via constructor and unfortunately there is no way of customisation of tags apart from url mapping in some request context. 

Would you consider to add another way of customised tags like getting from some special header `X-Micrometer-OkHttp-Tags-{tag name}` and its value from header value (we can discuss further how it should be done)? I can send a pr if you wish.

ping @bjartek

**Comment by jkschneider** [comment]
Open to ideas on this, but at first blush it seems like allowing callers to influence tags based on a header opens up a form of DOS-style attack on your monitoring system, one in which a malicious caller simply keeps sending in unique header values causing more and more unique time series to be shipped.

**Comment by nyilmaz** [comment]
@jkschneider Well, tag resolving would be based on request headers, not response actually. What will be added as tags, is under developers' control. 

However, from security point of view, one drawback would be sending unnecessary headers with possibility to give further information about the system.

**Comment by jkschneider** [comment]
@nyilmaz You're right of course, I wasn't thinking clearly 🤦‍♂️. What would be ideal is if OkHttp allowed for tags or metadata to be hung on requests for the purpose of telemetry and not just for metrics, but for distributed tracing and logging as well. Do you think this is a feature request we should take to them?

**Comment by nyilmaz** [comment]
Very nice point @jkschneider ! It seems okhttp already have `Request.tags` property [for this purpose](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Request.java#L299)

All we should do is use tags on request imho 😄 .

**Comment by jkschneider** [comment]
@nyilmaz Perfect! Let's do that.

**Comment by bjartek** [comment]
Could we use this for mapping to an url pattern aswell? 

Should tags override generated labels on a metric?
