### ISSUE TITLE
Kafka Consumer Metrics report invalid number to InfluxDB

### ISSUE THREAD

**Issue by hgnoyke** [micrometer-metrics/micrometer#1120]
With Micrometer 1.1.1 and InfluxDB we still see errors with Kafka Consumer Metrics when no messages have yet been consumed.

Error message is like this:
`failed to send metrics to influx: 
{"error":"partial write:
unable to parse 'kafka_consumer_commit_latency_max,client_id=consumer-1,[custom tags],metric_type=gauge value=-∞ 1546517069666': invalid number
unable to parse 'kafka_consumer_fetch_throttle_time_max,client_id=consumer-3,[custom tags],metric_type=gauge value=-∞ 1546517069669': invalid number
... continues for metrics prefixed "kafka_consumer_"`

The root cause seems to be that from the Kafka MBean -Infinity is returned (org.apache.kafka.common.metrics.stats.Avg divides by zero) and io.micrometer.core.instrument.internal.DefaultGauge can not cope with it. That's what I got from debugging.

Could be related to https://github.com/micrometer-metrics/micrometer/issues/983 (raised a comment earlier there for 1.1.0, but seemed to address another issue of finding the right MBean + methods).

For the time being, I filtered Kafka Consumer Metrics with a Meterfilter:
`.meterFilter(MeterFilter.denyNameStartsWith("kafka.consumer"))`

Thanks for looking into this!

**Comment by ccellist** [comment]
Thanks for the fix. Any update on when this fix will make it to the next release?

**Comment by izeye** [comment]
@ccellist This should be included [since Micrometer 1.1.2](https://github.com/micrometer-metrics/micrometer/pull/1122). If that's not the case, please create a new issue with a sample project reproducing it.
