### ISSUE TITLE
how can I send metrics to cloudwatch and elastic in springboot2? Is there any docs? help!!

### ISSUE THREAD

**Issue by TsingLiang** [micrometer-metrics/micrometer#1121]

**Comment by izeye** [comment]
For the Micrometer's documentation there's [documentation for Elasticsearch](https://micrometer.io/docs/registry/elastic) but [no one for CloudWatch](https://github.com/micrometer-metrics/micrometer-docs/issues/49) yet.

For Spring Boot auto-configuration documentation, there's [documentation for Elasticsearch](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-export-elastic) but I [couldn't find one for CloudWatch](https://spring.io/projects/spring-cloud-aws). If you want to see documentation on Spring Boot auto-configuration for CloudWatch, you'd better raise an issue on [its issue tracker](https://github.com/spring-cloud/spring-cloud-aws/issues). Or you can reference [its source](https://github.com/spring-cloud/spring-cloud-aws/tree/master/spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/metrics).
