### ISSUE TITLE
Elastic: Failed to send metrics when using KafkaConsumerMetrics in 1.1 with default settings

### ISSUE THREAD

**Issue by fkoehler** [micrometer-metrics/micrometer#1134]
For mm 1.1.1 with Kafka 2.1:

I have bound the KafakConsumer metrics like so:

```
new KafkaConsumerMetrics().bindTo(globalRegistry)
```

Also I have added the ElasticMeterRegistry to the globalRegistry.
Now I get the following error when micromter tries to send the metrics to my local elastic:

```
failed to send metrics to elastic: {"took":11,"errors":true,"item
.....
,"status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"json_parse_exception","reason":"Non-standard token '-Infinity': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@273c3274; line: 1, column: 242]"}}}},
```

So it looks like some of the metrics is "-Infinity" which elastic won't accept.

Any ideas on how to start fixing this? I would be willing to help.

**Comment by fkoehler** [comment]
Looks like this is related to #1123

**Comment by izeye** [comment]
@fkoehler Thanks for the report! I think you can fix it by replacing `!value.isNaN()` with `Double.isFinite(value)` in the following two places:

- https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java#L183
- https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java#L194

**Comment by fkoehler** [comment]
Please see my PR with the fixes
