### ISSUE TITLE
PrometheusConfig descriptions config has no effect

### ISSUE THREAD

**Issue by pjfanning** [micrometer-metrics/micrometer#1140]
The PrometheusMeterRegistry uses the prometheus TextFormat class to create the scraped data and this always add the metric descriptions.

Should we remove this config setting?

https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusConfig.java#L42

**Comment by jkschneider** [comment]
While Prometheus always sends some description text, we use this config property to blank the description provided by Micrometer effectively to reduce the payload size. See [this](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/MicrometerCollector.java#L64).
