### ISSUE TITLE
add deviceId to PrometheusConfig

### ISSUE THREAD

**Issue by pjfanning** [micrometer-metrics/micrometer#1141]
There is an equivalent setting in DynatraceConfig and I think that is useful. It adds a tag to all metrics with the given deviceId. If set in the Prometheus Registry, the scrape method could automatically append the deviceId tag.

**Comment by jkschneider** [comment]
@pjfanning You can easily do this with a common tag for Prometheus. `deviceId` is a specific required field of dynatrace that has no corollated requirement in Prometheus. Several other variants of this exist in other monitoring systems, e.g. `host`. I think they are all conceptually just tags.

**Comment by pjfanning** [comment]
@jkschneider I can understand that when I create a custom metric, I can add my own host/deviceId tag. I still think it would be useful for the metrics in DefaultExports (JVM, GC metrics, etc.) to be able to get a host/deviceId tag when the prometheus data is exported.

In a previous job, the prometheus exporter that we used there automatically added some tags like the host which I thought was very useful.

**Comment by checketts** [comment]
@pjfanning  When @jkschneider  mentioned 'common tags', he was referring to the [common tags](https://micrometer.io/docs/concepts#_common_tags) concept.

That will allow you to set what the deviceId is that is relevant for your use case. For example a Kubernetes deployment would care about a podId while a raw AWS deploy might care about something different.
