### ISSUE TITLE
Tomcat ThreadPool metrics reporting NaN values

### ISSUE THREAD

**Issue by jvalloire** [micrometer-metrics/micrometer#1145]
Using Spring Boot 2.1.1 (with embedded Tomcat 9.0.13), Tomcat ThreadPool metrics report only *NaN* values.

Indeed, there is now a subtype `subType=SocketProperties` to ThreadPool type in JMX:

![image](https://user-images.githubusercontent.com/3441395/50975880-e0ee5b00-14ee-11e9-8498-f6f5b2f9a566.png)

As a consequence, 2 `objectNames` are found when trying to register metrics for ThreadPool here: https://github.com/micrometer-metrics/micrometer/blob/92b331cea76367c5c1690ea252a095e3cd4de0e7/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java#L225
For example:
- `Tomcat:type=ThreadPool,name="http-nio-8888",subType=SocketProperties`
- `Tomcat:type=ThreadPool,name="http-nio-8888"`

After registration, it keeps only one gauge that try to use the 1st objectName to get the metrics value and that results in a `AttributeNotFoundException`:
```
javax.management.AttributeNotFoundException:  Cannot find attribute maxThreads for org.apache.tomcat.util.net.SocketProperties
```
when evaluating the function here https://github.com/micrometer-metrics/micrometer/blob/92b331cea76367c5c1690ea252a095e3cd4de0e7/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java#L133

An issue related to this new subType was already tackled in Tomcat Manager: 
https://bz.apache.org/bugzilla/show_bug.cgi?id=62918
The fix was to filter out subtype mbeans: https://github.com/apache/tomcat85/commit/8c27e0e332d8dac8563193db333f865daeeca95b

Can we expect the same type of fix for Micrometer `TomcatMetrics` ?

**Comment by izeye** [comment]
@jvalloire Thanks for the report! But I couldn't reproduce it locally as `ObjectName` objects' ordering is different to me as follows:

```
Tomcat:type=ThreadPool,name="http-nio-8080"
Tomcat:type=ThreadPool,name="http-nio-8080",subType=SocketProperties
```

Although I failed to reproduce it, it seems to make sense to exclude the invalid `ObjectName` object. I created #1148 to try to resolve it.

**Comment by mweirauch** [comment]
I had seen it once, but couldn't reproduce since then. I am on:
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by jvalloire** [comment]
I reproduce it using:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

I've seen the issue on Spring Boot 2.1.1 with Tomcat 9.0.13 but I think it can be reproduced with Spring Boot 1.5.x, as long as it uses Tomcat > v8.5.35.

As @izeye mentionned, the order in which `ObjectName` objects are returned could explain you can't reproduce it.

**Comment by SimoneFalzone** [comment]
Despite [commit 1148](https://github.com/micrometer-metrics/micrometer/pull/1148) the problem still exists, because the query still returns all objects with the same name and subtype, because after "name=*,* there is also an asterisk wich should be removed.

**Comment by SimoneFalzone** [comment]
The problem exists again due to [commit](https://github.com/micrometer-metrics/micrometer/pull/1755/commits/f7ba40e02dde20149cb49aee15ce05d959b6a99d), because the query still returns all objects with the same name and subtype, because after "name" there is also an asterisk.
