### ISSUE TITLE
Metrics are sent twice on shutdown (CloudWatch)

### ISSUE THREAD

**Issue by alexvuta** [micrometer-metrics/micrometer#1154]
Hello,

After  [this fix](https://github.com/micrometer-metrics/micrometer/commit/55917287feaf067361df66f816b0cea3938f535b) (thanks to @jkschneider) I was able to test forced shutdown of a Spring Boot  Application.
The problem is that the last increment of the metric is pushed twice.
For testing I had used a shecduled task that increment a counter each 10 seconds, with a step of 10 seconds.

Console logs at shutdown: 
![spring logs](https://user-images.githubusercontent.com/11159607/51101555-59009d80-17db-11e9-978c-62c10e52dd8b.PNG)

As we can see the last increment was 63, and the total is 1844.

Grafana screen:
![grafana-screen](https://user-images.githubusercontent.com/11159607/51101559-61f16f00-17db-11e9-9fa7-e4458f13762b.PNG)

The total received was 1907 . 
The last counter value after an increment of 63 was 1844, 1907 - 63 is equal to exactly 1844.

Environment:
micrometer-core 1.1.0
micrometer-registry-cloudwatch  1.1.0
aws-java-sdk-cloudwatch #1066 
spring-boot 2.1.0.RELEASE
Java 1.8

**Comment by marcingrzejszczak** [comment]
Is it still a problem after almost 5 years?
