### ISSUE TITLE
Incorrect time conversions in FunctionTimer via JmxReporter

### ISSUE THREAD

**Issue by C-B-B** [micrometer-metrics/micrometer#1161]
I've played with the FunctionTimer today, to measure the duration of an operation that affects multiple records. When exposing the metrics to JMX and reading through the jconsole, I've noticed that the values were a million time lower than what I would see when using a standard Timer (and operating on a single record at a time).
Looking into the code, I can see that we're converting from the base time unit (nanoseconds) to the registry time unit (milliseconds) in two places within the same call stack, resulting in the one million factor difference (in DropwizardFunctionTimer.Snapshot.getMean() as well as JmxReporter.JmxTimer.getMean())

[JmxReporter.JmxTimer](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-jmx/src/main/java/com/codahale/metrics/jmx/JmxReporter.java#L421):
```
        this.durationFactor = 1.0 / durationUnit.toNanos(1);
```
```
        public double getMean() {
            return metric.getSnapshot().getMean() * durationFactor;
        }
```
[DropwizardFunctionTimer.Snapshot](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/dropwizard/DropwizardFunctionTimer.java#L82)
```
        public double getMean() {
            double count = count();
            return count == 0 ? 0 : totalTime(baseTimeUnit()) / count;
        }
```
```
        public double totalTime(TimeUnit unit) {
            T obj2 = ref.get();
            if (obj2 == null)
                return lastTime;
            return (lastTime = TimeUtils.convert(totalTimeFunction.applyAsDouble(obj2),
                totalTimeFunctionUnit,
                unit));
        }
```

Should the conversion in DropwizardFunctionTimer be removed? Can it?

Bit new to the group - let me know if I'm not following the right process.

Many thanks in advance,
CBB

**Comment by checketts** [comment]
@C-B-B Are you supplying the correct TimeUnit where you create your function timer?

Or are you saying the unit is correct in the non-JMX representation, but the JMX one is off?

**Comment by C-B-B** [comment]
@checketts, thanks for your reply.

Indeed I was careful to provide the right time unit (capturing time with System.nanoTime() and specifying Time Unit.NANOSECONDS. Also tried with milliseconds for both and got the same result - I think the issue is agnostic to that parameter).

As you suggest, when using the Micrometer LoggingMetricsRegistry the data is correct - but the issue is visible when using the JmxReporter, or also Dropwizard's ConsoleReporter. I believe the former uses the mean() implementation from the FuntionTimer interface whereas the latters use the DropwizardFunctionTimer Snapshot implementation.
Makes sense? Would the latter need to change?
Many thanks

**Comment by izeye** [comment]
@C-B-B Thanks for the report! I reproduced this with [a sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/micrometer-gh-1161).

Looking at `JmxReporter.JmxTimer`, it seems to expect nanoseconds for timer snapshot mean but `DropwizardFunctionTimer` provides a value with its base time unit. I created #1222 to fix this and confirmed that it fixes the sample locally.

**Comment by C-B-B** [comment]
That's great stuff, thanks a lot!
