### ISSUE TITLE
Multiple @Timed

### ISSUE THREAD

**Issue by qjex** [micrometer-metrics/micrometer#1164]
I want to use multiple `@Timed` annotation, but TimedAspect doesn't support this case.
I need this because I have custom timers in MetricRegistry, each of those can return average execution time of method in time window  
```java
    @Timed(MeterName.PROCESSING_AVG_TIME_1M)
    @Timed(MeterName.PROCESSING_AVG_TIME_15M)
    @Timed(MeterName.PROCESSING_AVG_TIME_5M)
    public void m() {}
```

**Comment by checketts** [comment]
A single timer can calculate all 3 averages. Here is an example with prometheus:

```
increase(processing_time[5m]) / increase(http_server_requests_seconds_count[5m])
```

Just switch out the `5m` for `1m` or `15m` if you want different time periods.

What backend are you using the requires this approach?

**Comment by qjex** [comment]
I actually use my own backend that uses dropwizzard metricRegistry and Timer

**Comment by checketts** [comment]
For your usecase you would probably be better off just using imperative timers and not annotations.

```
public void m() {
  multiTimer(() -> {
    //your code
  })
}

public void multiTimer(Runnable r) {
  registry.timer(MeterName.PROCESSING_AVG_TIME_1M).record(() -> {
    registry.timer(MeterName.PROCESSING_AVG_TIME_15M).record(() -> {
      registry.timer(MeterName.PROCESSING_AVG_TIME_5M).record(() -> {
        r.run()
      })
    })
  })
}
```

**Comment by izeye** [comment]
https://github.com/micrometer-metrics/micrometer/pull/2585 seems to have been opened for this.

**Comment by jonatan-ivanov** [comment]
@PasternakDominik Thanks for your use-case.
Would `@Observed` solve your use-case since it will create a `Timer` and a `LongTaskTimer` by default?
So if you do this:
```java
@Observed(name = "echo")
String echo(String message) {...}
```

You will get a `Timer` named "echo" and a `LongTaskTimer` named "echo.active".
