### ISSUE TITLE
InfluxMeterRegistry sends tags with empty values which influx then rejects

### ISSUE THREAD

**Issue by sean-brandt** [micrometer-metrics/micrometer#1167]
InfluxMeterRegistry simply collects up all tags for a given meter/metric and joins them together. Influx doesn't allow for tags with empty/null values and as such returns an error failing to parse the line.

```
    private String influxLineProtocol(Meter.Id id, String metricType, Stream<Field> fields) {
        String tags = getConventionTags(id).stream()
                .map(t -> "," + t.getKey() + "=" + t.getValue())
                .collect(joining(""));
```

I've run into the issue due to the project reactor integration where it defines an 'exception' tag with a default value of "" - somewhere along the line that "" becomes a null ( though either way influx would have an issue ). 

I believe that the reason for the pre-defined tag from the reactor perspective is due to prometheus requiring all the meters/metrics to have the same tags.

Given the above, I'd imagine that the most 'correct' fix would be to filter out the tags with empty/null values prior to mapping them. 

Thoughts? I need to see about both a very short term fix, as well as obviously hoping that a fix would be integrated here in the somewhat near future.

**Comment by mweirauch** [comment]
Shouldn't reactor produce an 'exception=NONE' tag like the MVC and Jersey servlet metric implementations? Just thinking loud here.

**Comment by sean-brandt** [comment]
Possibly. Though I'd argue that at least in Influx's case it doesn't matter. 'NONE', to me, is a work around for a system that doesn't metrics that have the same 'name' but different tags. (like prometheus). 

Why store data that is meaningless ( in that exception=NONE is the effectively the same as just not having the exception tag at all )?

**Comment by izeye** [comment]
Given that there's no restriction on empty values for tag values in Micrometer and InfluxDB rejects empty tag values, the suggestion seems reasonable to me.

**Comment by carhartl** [comment]
> Influx doesn't allow for tags with empty/null values and as such returns an error failing to parse the line.

Aaaah, I think the same is happening with the CloudWatchMeterRegistry. Collecting metrics from Reactor sequences, `reactor.flow.duration` never shows up in CloudWatch...
