### ISSUE TITLE
Adopt Spring Boot and Cloud naming convention for starter modules

### ISSUE THREAD

**Issue by wilkinsona** [micrometer-metrics/micrometer#117]
Spring Boot and Cloud both use the pattern `<project>-starter-<tech>` for their starters, for example `spring-boot-starter-web` and `spring-cloud-starter-atlas`. Micrometer currently uses `<project>-<tech>-starter`, for example `micrometer-jmx-starter`. Could Micrometer switch so that it matches the Boot and Cloud convention, for example `micrometer-starter-jmx`?

**Comment by jkschneider** [comment]
Sad oversight on my part. It might be best to just drop the `starter` bit altogether now that code has been shifted into each of them. They used to just be zero-byte jars that provided a collection of dependencies, but no longer.

**Comment by wilkinsona** [comment]
>  It might be best to just drop the starter bit altogether now that code has been shifted into each of them

Sounds reasonable to me

**Comment by jkschneider** [comment]
In the end, we renamed these modules to `micrometer-registry-prometheus`, etc.
