### ISSUE TITLE
Add support for Tinylog

### ISSUE THREAD

**Issue by re-thc** [micrometer-metrics/micrometer#1171]
Hi, [Tinylog ](https://github.com/pmwmedia/tinylog) is a very fast and efficient logging framework. Can a binder be added similar to logback / log4j2? Thanks!

**Comment by pmwmedia** [comment]
tinylog 2 has no filters but supports multiple bindings for consuming log entries at runtime. To do this, only the [LoggingProvider](https://github.com/pmwmedia/tinylog/blob/v2.0/tinylog-api/src/main/java/org/tinylog/provider/LoggingProvider.java) interface has to be implemented, and to be provided as a service that can be loader by the [ServiceLoader](https://docs.oracle.com/javase/9/docs/api/java/util/ServiceLoader.html).

**Comment by jkschneider** [comment]
@hc-codersatlas Are you affiliated with the tinylog project at all? Could we add optional-dependency instrumentation in tinylog itself? Otherwise, another binder here is fine by me.

**Comment by hc-codersatlas** [comment]
@pmwmedia is the owner.

**Comment by marcingrzejszczak** [comment]
If there's any interest in this still please create an issue in Tinylog and mention us there, thank you!
