### ISSUE TITLE
Support for Prometheus-like collector in the Micrometer API

### ISSUE THREAD

**Issue by nahguam** [micrometer-metrics/micrometer#1180]
We have use cases where there are no objects to pre-bind metrics to at registration time. To use the Micrometer API we would have to build a lot of boilerplate to pre-scrape the information on a schedule so we can sync the metrics with Micrometer, constantly registering and removing metrics as object are born and die. 

Currently we use the Prometheus APIs `Collector` directly to achieve this. At measurement time we programmatically scrape metrics from the live objects and any objects that have died since the previous measurement will have no metric reported this time around. Do you plan to add support for similar functionality to Micrometer?

**Comment by izeye** [comment]
This sounds like a duplicate of #1114.

**Comment by nahguam** [comment]
It's not a duplicate (scrape vs expiration) but it would be a way of handling our use cases.

**Comment by checketts** [comment]
It is a duplicate of #807 

Migration from Prometheus `Collector`s is the exact usecase it was  addressing. So check out `MultiGauge`. The semantics aren't identical, since collectors execute on demand when the Prometheus endpoint is called, but with a `MultiGauge` I believe you need to schedule a thread to update your gauge yourself.  I haven't used it yet in any of my code, (just reviewed the PR when it came up)

**Comment by nahguam** [comment]
Great. Thanks for the pointers all!

**Comment by shakuzen** [comment]
@nahguam let us know if the `MultiGauge` works for your use case. It sounds like it should. We can discuss further on Slack also, if you would like.

**Comment by nahguam** [comment]
@shakuzen It seems to be doing the job. The only thing I'm not keen on is that all combinations of `MultiGauge.Row#of` leave me with compiler warnings due to the omission of the generic in the return type.

**Comment by nahguam** [comment]
@shakuzen Just pushed out to our lab environment. Looks good! Code is nice and simple.

**Comment by shakuzen** [comment]
@nahguam Thank you for the follow-up. I'm glad it is working well for you.

**Comment by mweirauch** [comment]
Just out of curiosity (and I think I asked about this in another issue as well), wouldn't there be a need for this collector style for counters and distribution-summaries/timers as well?
