### ISSUE TITLE
Units not being sent to datadog for Timer metrics

### ISSUE THREAD

**Issue by nickmbailey** [micrometer-metrics/micrometer#1181]
Right now Timer metrics report their base unit as "seconds". The datadog registry maintains a whitelist of units that datadog supports and that includes "second" (not pluralized). Since "seconds" isn't in the whitelist, no units get sent for Timer metrics.

I would guess we just want a mapping from micrometer units to datadog units.

**Comment by shakuzen** [comment]
Thank you for reporting this. For anyone's reference, here is Datadog's documentation on the supported units: https://docs.datadoghq.com/developers/metrics/#units

**Comment by shakuzen** [comment]
@nickmbailey I looked into this a bit and realized that we do handle the units conversion for Datadog in the `DatadogMeterRegistry`. Can you share more information about your setup so we can figure out where the problem lies? How are you sending data to Datadog? What version of Micrometer are you using? Which metrics are losing units?

I have made some changes so the unit conversion is better tested in d729fa95b958d919dd8f13d35c1aa2d74049af0b

**Comment by nickmbailey** [comment]
Right the issue is that datadog only recognizes the unit "second" (with no 's' on the end). For timer metrics, micrometer reports the unit as "seconds" (with an 's' on the end). This won't be recognized by datadog.

**Comment by shakuzen** [comment]
@nickmbailey the tests I added in d729fa95b958d919dd8f13d35c1aa2d74049af0b prove that the units are mapped to the singular form when using the DatadogMeterRegistry. You can check the [DatadogMetricMetadata](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMetricMetadata.java) class for the implementation that does that. So I need more information about your setup to reproduce the problem you're seeing. Perhaps you aren't using the DatadogMeterRegistry and instead are using StatsD to send metrics to DataDog?

**Comment by nickmbailey** [comment]
Ok I did some more digging and it turns out this was user error. I didn't have an application key configured so metadata wasn't being written at all. The confusing part was datadog has at least a little built in support for memory metrics so heap size metrics appeared with units even though micrometer was never sending them.

I'd say maybe configuration logging on startup might be good to add to help future users. Are the docs from the website hosted in this repo? (https://micrometer.io/docs/registry/datadog) Updating those might be a good idea too, which I'd be happy to take a stab at.

Sorry for the wild goose chase.

**Comment by shakuzen** [comment]
Docs are over in this repo: https://github.com/micrometer-metrics/micrometer-docs

A pull request would be much appreciated. I'm glad you were able to figure out the issue in the end, and sorry it wasn't easier to figure out. Let me know what changes would help.

**Comment by nickmbailey** [comment]
Added a PR to add some startup logging if application key isn't configured.
