### ISSUE TITLE
`CompositeCounter#increment(double amount)` always increment by 1

### ISSUE THREAD

**Issue by yskopets** [micrometer-metrics/micrometer#119]
Behaviour of `CompositeCounter#increment(double amount)` is incorrect.

Expected behaviour:
`CompositeCounter#increment(2)` would increment the counter by `2`

Actual behaviour:
`CompositeCounter#increment(2)` increments the counter by `1`

The issue is reproducible on `0.11.0.RELEASE`

**Comment by jkschneider** [comment]
Thanks for the report @yskopets.
