### ISSUE TITLE
WebMvcMetricsFilter does not record a 500 response status for any downstream IOExceptions

### ISSUE THREAD

**Issue by kbobrien** [micrometer-metrics/micrometer#1190]
We have a scenario where an`IOException` is thrown when write the response to the client in our Spring Boot app (1.4.7-RELEASE with Micrometer legacy support lib), which will result in a 500 error as the API status code (see attached stack trace).  The `IOException` does not get caught by the catch block in the `WebMvcMetricsFilter` since it's not a `NestedServletException` so the 500 isn't counted in our APIs metrics.  

The 500 does get counted in the `tomcat_global_error_total` metric, but at that stage we have lost the API method and URI tags so it is impossible to know which APIs are causing the increase in 500s in a service.

While I know our setup is using a very old version of Spring Boot, looking at the latest codebases I'm pretty sure the same issue will still happen. 

All traffic to an API should be recorded by the timer regardless of the status code or result, so an alternative implementation would be to set an initial status code of 500 and use a `finally` instead of a `catch` block to record the metric. The metric would always be recorded then and something else downstream from the `WebMvcMetricsFilter` would change the status code of the Response object appropriately. 

[micrometer_ioexception.txt](https://github.com/micrometer-metrics/micrometer/files/2803886/micrometer_ioexception.txt)

**Comment by izeye** [comment]
@kbobrien Thanks for the report! I created https://github.com/spring-projects/spring-boot/pull/16014 to try to resolve this.
