### ISSUE TITLE
Strip invalid characters from events for New Relic naming convention

### ISSUE THREAD

**Issue by mustafashabib** [micrometer-metrics/micrometer#1192]
The [NewRelicNamingConvention](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicNamingConvention.java)

 uses [camelCase](https://github.com/micrometer-metrics/micrometer/blob/531d46b13601ecf79e772f451fd13250548091cb/micrometer-core/src/main/java/io/micrometer/core/instrument/config/NamingConvention.java#L73)

But the [NR docs naming syntax](https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/insights-custom-data-requirements-limits#general) specify that you can only use alphanumeric, `_`, and `:`.

Anything outside that set of chars should get replaced with an `_` IMO.

**Comment by shakuzen** [comment]
Resolved via #1193
