### ISSUE TITLE
Question - persist registry state across process restarts?

### ISSUE THREAD

**Issue by benemon** [micrometer-metrics/micrometer#1211]
Is it possible to persist the registry state to disk?

Use case: I'm using Micrometer as part of a stack that consumes metrics payloads from a message broker, and translates them into Prometheus metrics for visualisation in Grafana. If I restart the Micrometer element of the stack, the registry state (i.e. all registered instruments) is lost.

**Comment by checketts** [comment]
How would persisting the registry to disk solve this? That would just show stale data. Instead you can solve this in grafana. 

Under the graph `Display` tab, select `Null Value`: `Connected`. See http://docs.grafana.org/features/panels/graph/#display-styles

**Comment by benemon** [comment]
So, the reason being is that If I have a set of Counters or Guages, then the restart obviously wipes the state of that counter. I don’t miss any data during the restart because of the message broker behaviour - so when the Micrometer process comes back up I can just continue consuming and incrementing the Counter (or whatever). 

Bearing in mind that my process is effectively a metrics proxy rather than a primary source, my thought was that if the registry state could be persisted, I could avoid the instruments being reset to zero, and skewing the Grafana visualisations to misleading values. 

If I can compensate for this in Grafana then it’s less of an issue - I didn’t realise you could do manipulate the display in this way.

**Comment by marcingrzejszczak** [comment]
There was no interest in this feature since 2019. Let's close it for now, and if there's any interest still please comment on the issue and we'll consider re-opening it.
