### ISSUE TITLE
StatsD TCP connection does not recover

### ISSUE THREAD

**Issue by benzaita** [micrometer-metrics/micrometer#1212]
Version 1.2.0

When the TCP connection (e.g. to Telegraf) drops the [Netty TCP client](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java#L218) does not recover it.

See [this](http://tterm.blogspot.com/2014/03/netty-tcp-client-with-reconnect-handling.html) for a possible solution.

**Comment by izeye** [comment]
@benzaita Thanks for the report! I created #1251 to try to resolve this.

**Comment by shakuzen** [comment]
@benzaita could you try with the latest `1.4.0-SNAPSHOT` version to confirm this is working as expected now?
