### ISSUE TITLE
Support New Relic APM

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#122]

**Comment by jkschneider** [comment]
https://docs.newrelic.com/docs/agents/manage-apm-agents/agent-data/collect-custom-metrics?

**Comment by jkschneider** [comment]
Reference to publishing rest api [here](https://github.com/Terracotta-OSS/terracotta-newrelic-plugin#terracotta-new-relic-plugin).

**Comment by maximusfloydus** [comment]
To get more out of the data pushed to New Relic, I would want it sent to New Relic Insights.

https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/insert-custom-events-new-relic-apm-agents (via Java APM)

https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/insert-custom-events-insights-api (via Insights API)

The APM custom metrics will work, but they cannot be queries like data put into Insights.  I find the benefits of the custom metrics limiting because of this.

**Comment by jkschneider** [comment]
@maximusfloydus I'm pretty confused about the agent's interface for custom events heading to insights. If you've got some experience in this, I'd love to have a chat with you.

**Comment by jkschneider** [comment]
The second link you sent is new to me. It appears using that API that we can bypass interaction with the agent altogether, which is really attractive to me (i.e. if you want to bootstrap your app with the agent, by all means do so, but you aren't required to).

I guess what I'd like to know: is there any prior art on how, for example, a timer is structured using the insights API, or is this totally greenfield and I'm just picking a structure that makes sense?

If there isn't an established standard, I can imagine a timer shipping something like this:

```json
[
{
   "eventType": "http.server.requests", <-- corresponds to the meter name

   // one for each meter tag
   "response": "200",
   "method": "GET",
   "uri", "/api/people/{id}",

   // one for each statistic emanating from a timer
   statistic: "TotalTime",
   value: 0.01      // seconds as a base unit?
},
{
   "eventType": "http.server.requests", <-- corresponds to the meter name

   // one for each meter tag
   "response": "200",
   "method": "GET",
   "uri", "/api/people/{id}",

   // one for each statistic emanating from a timer
   statistic: "Count",
   value: 1 
}
]
```

**Comment by jkschneider** [comment]
NRQL has a `rate` function, so I think we'll ship cumulative values.

**Comment by jkschneider** [comment]
Insights is far more capable than custom dashboards.

![image](https://user-images.githubusercontent.com/1697736/33110169-986b894a-cf0b-11e7-83c3-6c6173487f66.png)

**Comment by jkschneider** [comment]
Example of timer instrumentation in Insights API with new Micrometer implementation:

![image](https://user-images.githubusercontent.com/1697736/33356169-a92faf5c-d480-11e7-9375-bb1790bc77ce.png)

**Comment by jkschneider** [comment]
Would love you to take it for a spin with the latest snapshot @maximusfloydus and see if this makes sense. You'll need at a minimum:

```
newrelic.accountId=YOURACCOUNTID
newrelic.apiKey=INSIGHTSAPIKEY
```

You can find your account id under Account Settings -> API Keys and your _insights_ API key (not the other one) under Account Settings -> API Keys -> Insights API Key
