### ISSUE TITLE
Any plan to add jsr 305 support for null check

### ISSUE THREAD

**Issue by linux-china** [micrometer-metrics/micrometer#123]
Now Spring 5 & Spring Boot 2 both add jsr305 support for null check, could micrometer add this feature. It will be easy to use io.micrometer.core.instrument.Metrics with null check, such as Metrics.counter("xxx.request") will be Nonnull, and it is friendly to Kotlin language and IDE. 

```
  <groupId>com.google.code.findbugs</groupId>
  <artifactId>jsr305</artifactId>
  <version>3.0.2</version>
```

**Comment by jkschneider** [comment]
I'll have to check with the team. I'm pretty sure last time I heard a talk on this that `com.google.code.findbugs:jsr305` breaks the module system in JDK 9 because `Nonnull` is in `javax.annotation`, leading to a split package scenario with the core JDK.

**Comment by linux-china** [comment]
@jkschneider you are right.   jsr305 will break module system in JDK.  I think that Spring 5 has the same problem to implement null check in JDK 9.  How did they fix this problem?  it's so complicated.

**Comment by checketts** [comment]
Interestingly at https://docs.spring.io/spring-framework/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/core.html#null-safety it states: `It is not necessary nor recommanded to have JSR 305 dependency in user project classpath.`

So perhaps we can just use the annotation and leave them as a provided or optional dependency?

**Comment by jkschneider** [comment]
I'll need to probe a bit deeper. It looks like Spring added a `Nonnull`-like annotation that just applies JSR305 `Nonnull` as a meta-annotation. I can't remember the details around this, but I think the runtime allows meta-annotations missing from the classpath to slip by without blowing up? If this is true, then the trick is to use it indirectly, effectively enabling the behavior in the presence of JSR305 and disabling it otherwise.

**Comment by jkschneider** [comment]
At any rate, disappointing half-solution from the Java team: https://stackoverflow.com/a/37911663/1113486

**Comment by jkschneider** [comment]
> It is not necessary nor recommanded to have JSR 305 dependency in user project classpath.

@checketts I guess not recommended because even with the decision to remove the annotations module from the module path by default, the split package problem still means you can only one of JSR305 _or_ the core annotations module (think `@PostConstruct`) at a time.

**Comment by zhaoxi1988** [comment]
I do not agree that we use google findbugs. Java Code Conventions & Spring 5 is more elegant.

[Spring Framework 5](https://docs.spring.io/spring-framework/docs/5.0.2.RELEASE/kdoc-api/spring-framework/org.springframework.lang/index.html)

**Comment by shakuzen** [comment]
@zhaoxi1988 I'm not sure what your feedback is. Micrometer uses null-related annotations in its own package like Spring Framework: https://www.javadoc.io/doc/io.micrometer/micrometer-core/1.5.5/io/micrometer/core/lang/package-summary.html

**Comment by zhaoxi2000** [comment]
> 

How it is working progress between spring 5 and java 9?

**Comment by zhaoxi2000** [comment]
> How it is working progress between spring 5 and java 9?

**Comment by shakuzen** [comment]
@zhaoxi2000 would you open a new GitHub issue if you are facing an issue with Micrometer's nullability annotations and Java 9? You can reference this issue so the conversation here is linked, but it will be better to triage in a new issue since this one is resolved.
