### ISSUE TITLE
Improve Metrics Actuator endpoint in Boot 2

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#124]
In Boot 2 M4, the endpoint looks a little funky:

http://localhost:8080/application/metrics/process.uptime

```
{
  "processUptime.": [
    {
      "statistic": "Value",
      "value": 1.0619075E13
    }
  ]
}
```

We could use some improvement here, perhaps something like:

http://localhost:8080/application/metrics/process.uptime

```
{
  "process.uptime": [
    {
      "statistic": "Value",
      "value": 1.0619075E13
    }
  ],
  "tags": [
    {
      "key": "host",
      "values": [
        {
          "value": "instance1",
          "_links": {
            "instance1": "http://localhost:8080/application/metrics/process.uptime.*host.instance1"
          }
        },
        {
          "value": "instance2",
          "_links": {
            "instance1": "http://localhost:8080/application/metrics/process.uptime.*host.instance2"
          }
        }
      ]
    }
  ],
  "_links" : {
    "self": {
      "href": "http://localhost:8080/application/metrics/process.uptime"
    }
  }
}
```

**Comment by joshiste** [comment]
Imho it would be useful if to query multiple metrics with a single request...

**Comment by jkschneider** [comment]
@joshiste Can you elaborate on the use case?

**Comment by joshiste** [comment]
just to reduce the needed requests to query multiple metrics. 
I'm a maintainer of Spring Boot Admin and for Boot 1.x we have a single page which shows multiple metrics (jvm-memory, datasources, http.sessions, uptime, ...).

**Comment by jkschneider** [comment]
Will be fixed with https://github.com/spring-projects/spring-boot/pull/10519.
