### ISSUE TITLE
Add Automatic-Module-Name to all manifest files

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1242]
While we haven't modularized Micrometer itself, we can still set a stable automatic module name for each of our produced artifacts and declare it in the manifest file. This will ensure the Micrometer artifacts' module names can be reliably used by those who are modularizing their applications and using Micrometer.

There seem to be two formulas folks are using to pick their module names. Without an Automatic-Module-Name specified or an actual module-info file, the JAR file name will be used to make an automatic module by converting hyphens `-` to dots `.`. Some choose to make this their declared automatic module name (e.g. `spring.beans`); others choose to add in their group ID in front of this (e.g. `org.junit.jupiter.api`).

Note: If there are users on the module path depending on our JAR name-derived automatic module name, we would break them by choosing something else - they would have to change the name when upgrading to the version we declare something else explicitly to be our module name.

See https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers

**Comment by JonathanGiles** [comment]
It would be great get this introduced in some form to lessen the warnings seen when building projects in JDK9+, e.g. 

```
[WARNING] *************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [micrometer-core-1.2.0.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] *************************************************************************************************************************************************
```

**Comment by shakuzen** [comment]
Seems we have a decision to make regarding what our automatic-module-names specifically are. I'm seeing 3 likely options:

* short project names e.g. `micrometer.core`, `micrometer.registry.whatever`
* reverse-DNS style based on artifact names `io.micrometer.core` / `io.micrometer.registry.whatever`
* reverse-DNS style based on root package name `io.micrometer.core` / `io.micrometer.whatever` (unlike previous option, no `registry` in there)

I'm leaning towards one of the latter two, even though it would differ from the implicit automatic-module-names now.

**Comment by JonathanGiles** [comment]
I would go with first or second personally, and probably the first is best IMHO.

**Comment by shakuzen** [comment]
I have gone with the short project names which will match the filename-based automatic modules. This should not break any existing users of our automatic modules.
