### ISSUE TITLE
failed to send metrics to datadog: Payload too big

### ISSUE THREAD

**Issue by adrianboimvaser** [micrometer-metrics/micrometer#1250]
I'm getting that error from `io.micrometer.datadog.DatadogMeterRegistry`. Is there any way to configure the rate at which metrics are sent to Datadog so this doesn't happens?

**Comment by izeye** [comment]
@adrianboimvaser You can set batch size (default: 10,000) on its configuration, `DatadogConfig`. If you're using Spring Boot, you can achieve it by setting the following property:

```
management.metrics.export.datadog.batch-size=10000 # Number of measurements per request to use for this backend. If more measurements are found, then multiple requests will be made.
```

**Comment by adrianboimvaser** [comment]
Thank you @izeye !

**Comment by subrasel** [comment]
We are using micrometer 1.0.3 and even after setting the batch size to 5000 and reducing the step time to 30seconds we are getting this error. Any suggestions.
