### ISSUE TITLE
@Timed annotation's extraTags property doesn't work with Prometheus backend

### ISSUE THREAD

**Issue by stevebakh** [micrometer-metrics/micrometer#1253]
The prometheus backend requires that all meters with the same name have the same set of tag keys. This means that the `extraTags` property of the `@Timed` annotation will never work unless all instances of the annotation used in the codebase have the same tag names supplied. 

It feels like this case should be handled by the code, or at the very least, the exception that's thrown from the Micrometer Prometheus registry should be logged; at the moment, the `TimedAspect` does some pokemon exception handling but just swallows the exception and doesn't log it. I had to run the code in debug mode with a break point to discover why my metric was disappearing from the prometheus output.

### Steps to reproduce
1. Write a Spring Boot application
2. Create the `TimedAspect` bean
3. Apply the annotation `@Timed` to method **one** (note, no extra tags!)
4. Apply the annotation `@Timed(extraTags = {"type", "foo"})` to method **two**
5. Run the application, invoking method one and then method two
6. Check prometheus output and see that there's no timed metric for method two.

The exception that is swallowed:

```
Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'method_timed_seconds' containing tag keys [class, exception, method]. The meter you are attempting to register has keys [class, exception, method, type].
```

There are two possible workarounds:
Ensure that all instances of the `@Timed` annotation in your codebase have the same tag keys, i.e. if you want to add a `type` tag, you will need to add it to all instances of `@Timed`.

Alternatively, you can force all timed metrics to automatically have the type tag, without explicitly adding it to all instances of the annotation (eugh). To do this, we can call the `TimedAspect` constructor that takes a function to use the proceeding join point to get the value of the extraTags value to set them where they exist, but make sure there's always a reference to the desired tag name.

Example:

```java
return new TimedAspect(registry, pjp -> {
    Method method = ((MethodSignature) pjp.getSignature()).getMethod();
    Timed timed = method.getAnnotation(Timed.class);
    String typeTagValue = Tags.of(timed.extraTags()).stream()
            .filter(tag -> tag.getKey().equals("type"))
            .findFirst()
            .map(Tag::getValue)
            .orElse("");

    return Tags.of("class", pjp.getStaticPart().getSignature().getDeclaringTypeName(),
            "method", pjp.getStaticPart().getSignature().getName(),
            "type", typeTagValue);
});
```

^ 😢

**Comment by michaelmcfadyen** [comment]
You can set the name of each meter created by `@Timed` by passing in the name to the annotation ie
`@Timed("my.metric.name")`

If you do not pass in a metric name, by default all meters created by the annotation will be `method.timed`.

**Comment by stevebakh** [comment]
Hi Michael,

I'm aware of that, but in the case where we want to maintain the name pattern (which describes the type), then defining `extraTags` in the `@Timed` annotation is broken and the error is swallowed/not logged. I think that as a minimum, it should be made obvious that any metric with the same name must have the same set of tags. This could be as simple as not swallowing exception without logging them.

```java

            try {
                sample.stop(Timer.builder(metricName)
                        .description(timed.description().isEmpty() ? null : timed.description())
                        .tags(timed.extraTags())
                        .tags(EXCEPTION_TAG, exceptionClass)
                        .tags(tagsBasedOnJoinPoint.apply(pjp))
                        .publishPercentileHistogram(timed.histogram())
                        .publishPercentiles(timed.percentiles().length == 0 ? null : timed.percentiles())
                        .register(registry));
            } catch (Exception e) {
                // ignoring on purpose . <--- why?
            }

```

**Comment by stephenharper82** [comment]
Is anyone going to pick this up? We've found the same issue to when trying to adopt the same naming  pattern.

**Comment by jkschneider** [comment]
We're adding a new configuration for Micrometer 1.6.0 that allows you to register a listener on `MeterRegistry` to detect these sorts of registration problems both in `@Timed` and anywhere else and do whatever you'd like with them, including logging.

See #2068.
