### ISSUE TITLE
AsyncCache support (caffeine 2.7)

### ISSUE THREAD

**Issue by ben-manes** [micrometer-metrics/micrometer#1254]
Micrometer provides convenient bindings for `Cache`, `LoadingCache`, and `AsyncLoadingCache`. `AsyncCache` was recently split off from `AsyncLoadingCache` based on integrations where the mapping function isn't provided up front (e.g. Akka's http cache) or for those who need to capture non-key parameters in the given lambda. These behaviors were supported by `AsyncLoadingCache` but a little clunky.

I believe all that is required is changing `CaffeineCacheMetrics` from
```java
public static <C extends AsyncLoadingCache> C monitor(...) {}
```
to
```java
public static <C extends AsyncCache> C monitor(...) {}
```

Due to the library maintaining strict semver, it should be safe to upgrade the required version clients use.

**Comment by izeye** [comment]
@ben-manes Thanks for the suggestion! I created #1255 to try to resolve this as suggested.

**Comment by shakuzen** [comment]
We'll want to note in our 1.2.0 release notes that Caffeine 2.7 or later is now required for the Caffeine caching metrics support.
