### ISSUE TITLE
After `ControllerMetrics` was refactored into `WebMvcMetrics`, method `#tagWithException(ex)` is no longer accessible to client code

### ISSUE THREAD

**Issue by yskopets** [micrometer-metrics/micrometer#126]
Issue:
* `User Manual for Prometheus` (http://micrometer.io/docs/prometheus), section `6.2.1. Web MVC and Annotation-Based WebFlux`, provides instructions how to configure `@ExceptionHandler` to make use of `WebMvcMetrics.tagWithException(ex)` 
* However, method `#tagWithException(ex)` is now `package-private` and not accessible to client code

Expected:
* Either documentation or source code get updated to be in sync

**Comment by jkschneider** [comment]
Thanks, it is intended to be public!

**Comment by jkschneider** [comment]
Opened PR against Boot 2 as well: https://github.com/spring-projects/spring-boot/pull/10318
