### ISSUE TITLE
NPE in TimedAspect (JdkDynamicAopProxy)

### ISSUE THREAD

**Issue by CrystalWhiteOwl** [micrometer-metrics/micrometer#1262]
In TimedAspect method.getAnnotation(Timed.class) returns null if proxy was created by JdkDynamicAopProxy. To avoid this, you have to annotate method in the interface and specify all the parameters there. This is explained by the fact that such proxies are accessed via the interface, and not through the implementation in which the annotation is located.

**Comment by izeye** [comment]
@CrystalWhiteOwl Thanks for the report! I created #1264 to try to resolve this.

**Comment by izeye** [comment]
> To avoid this, you have to annotate method in the interface and specify all the parameters there.

`@Timed`-annotated method in interface doesn't seem to work with the current implementation. #1264 doesn't, either. #1264 makes `@Timed`-annotated method in class implementing interface work.

**Comment by CrystalWhiteOwl** [comment]
> @Timed-annotated method in interface doesn't seem to work with the current implementation.
I meant that in the current implementation, you need to annotate the method in the implementation to indicate the need to create a proxy, and to annotate the method in the interface, you need to transfer the annotation parameters

**Comment by izeye** [comment]
With the current implementation, if we want to time a method in a class implementing an interface, we need to add `@Timed` to both methods to work. With #1264, we need to add `@Timed` only to the method on the class.

On pointcut for annotated method in interface, I'm not sure there's a way to achieve it.

**Comment by CrystalWhiteOwl** [comment]
> With #1264, we need to add @Timed only to the method on the class.

Great, this is the behavior I expect from such annotations.
For my annotation, I used AspectUtils.getAnnotation, but I'm not sure that there is an opportunity to apply it here. Although the meaning is the same. I’m not so familiar with pointcuts, so there’s nothing to offer.

**Comment by izeye** [comment]
@CrystalWhiteOwl Thanks for clarifying the scope of this issue! Hope #1264 to resolve your problem.

**Comment by CrystalWhiteOwl** [comment]
Thanks for the prompt solution of the problem.
