### ISSUE TITLE
@Timed annotation on classes

### ISSUE THREAD

**Issue by sabouri** [micrometer-metrics/micrometer#1278]
The @Timed annotation's target includes ElementType.TYPE, but when a class is annotated with @Timed, no new metrics are registered.

Is the @Timed annotation supposed to support classes?

**Comment by sabouri** [comment]
Please see:
https://github.com/micrometer-metrics/micrometer/pull/1279

**Comment by plum117** [comment]
Hi, can we expect a fix?

**Comment by mukeshjitsingh** [comment]
Has there been any updates on this? Any other alternative to have all the methods timed by annotating the class?

**Comment by shakuzen** [comment]
Duplicate of #493
