### ISSUE TITLE
CacheMeterBinder - cache.gets is set twice

### ISSUE THREAD

**Issue by samanthacatania** [micrometer-metrics/micrometer#1280]
The metric cache.gets is configured twice in CacheMeterBinder; once on line 62 and is linked to the misses and then on line 72 and linked to the hits. Is this intentional please?

**Comment by izeye** [comment]
@samanthacatania Assuming that you're referring `CacheMeterBinder` (not `CacheMeterBuilder`), as you've noticed, one for misses and another for hits. Any problem with it?

**Comment by samanthacatania** [comment]
@izeye You're correct I meant CacheMeterBinder. When loading the value from actuator only the hits seem to be returned.

http://localhost:8090/actuator/metrics/cache.gets
`{
  "name": "cache.gets",
  "description": "The number of times cache lookup methods have returned a cached value.",
  "measurements": [
    {
      "statistic": "COUNT",
      "value": 3.0
    }
  ],
  "availableTags": [
    {
      "tag": "result",
      "values": [
        "hit",
        "miss"
      ]
    },
    {
      "tag": "appointments",
      "values": [
        "cache"
      ]
    },
    {
      "tag": "cache",
      "values": [
        "appointments"
      ]
    },
    {
      "tag": "name",
      "values": [
        "appointments"
      ]
    },
    {
      "tag": "cacheManager",
      "values": [
        "cacheManager"
      ]
    }
  ]
}`

**Comment by izeye** [comment]
@samanthacatania `http://localhost:8090/actuator/metrics/cache.gets` gives you a merged result based on the meter name `cache.gets`.

If you want to see "hit" or "miss" result specifically, you can drill down to it by specifying tag(s) as follows:

- `http://localhost:8090/actuator/metrics/cache.gets?tag=result:hit`
- `http://localhost:8090/actuator/metrics/cache.gets?tag=result:miss`

See [the "Metrics endpoint" section in the Spring Boot reference](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-endpoint) for more details.

Closing as this is a question on Spring Boot Actuator metrics endpoint.

If you have an additional question, it'd be better to ask it on StackOverflow with tags like `spring-boot`, `spring-boot-actuator`, and `micrometer`.

**Comment by samanthacatania** [comment]
@izeye Thanks for clarifying, it is appreciated.
