### ISSUE TITLE
GraphiteReporter cant handle DNS updates

### ISSUE THREAD

**Issue by terozio** [micrometer-metrics/micrometer#1281]
This seems to be similar as https://github.com/micrometer-metrics/micrometer/issues/1252

Using micrometer-core-1.1.2 with spring boot.

Graphite metric sending fails to notice DNS changes. First noticed in AWS environment with a recreated Network Load Balancer but the same behaviour can be reproduced locally:

1. add entry to /etc/hosts (i.e. graphite.local 127.0.0.1)
2. start local carbon server
3. point application and a bash script that sends metrics with NC to graphite.local and start them
4. verify metrics are coming in from both sources to the local carbon server
5. edit /etc/hosts and change graphite.local to point to some random IP
6. check local carbon and notice that metrics from the bash script are not coming in anymore, but application metrics still flow in

**Comment by shakuzen** [comment]
See https://github.com/dropwizard/metrics/issues/606 for the upstream issue that made the desired behavior here possible.
