### ISSUE TITLE
Uri (UNKNOWN)  is incorrect when okhttp call ends with timeout

### ISSUE THREAD

**Issue by play-io** [micrometer-metrics/micrometer#1285]
When okhttp's call ends due to timeout error then published metric looks like this
`GET - UKNOWN - IO_ERROR` (pattern: `{{method}} - {{uri}} - {{status}}`)

That's enough if I call just one uri - so I know what uri cases the problem. However this information has no sense when I have more than uri to call.

For example:
- I am calling 2 endpoints:
 1.`GET example.com/xxx`
 2.` GET example.com/yyy`

- Assuming that some calls ended correctly and on failed due to timeout then in Prometheus it looks like:

`GET /xxx 200`
`GET /yyy 200`
`GET UNKNOWN IO_ERROR`

And i have no guess which one timedout.

Is there sense keeping it as it's or PR is welcomed?

**Comment by shakuzen** [comment]
It sounds like a pull request would be welcomed for this and would be in line with what I believe the behavior is for say Spring's WebClient or RestTemplate's tagging. We just want to avoid known high cardinality tag values.
