### ISSUE TITLE
Add support for popular cache libraries

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#129]
As part of the move to micrometer, Spring Boot no longer provides stats for the cache libraries that we support.

That abstraction was provided by [CacheStatisticProvider implementations](https://github.com/spring-projects/spring-boot/tree/1.5.x/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/cache). We also have a [sample in Spring Boot](https://github.com/spring-projects/spring-boot/tree/d89ff8cb2816add96f63a21028c3e857be68f10f/spring-boot-samples/spring-boot-sample-cache) that shows how those metrics can be used.

Right now, `master` doesn't show any metric at all for those.

**Comment by jkschneider** [comment]
Thanks @snicoll. We'll work this in before Boot 2 M5, along with any other gaps from our previous instrumentation.

**Comment by jkschneider** [comment]
Answer this question when done: https://groups.google.com/forum/#!msg/dropwizard-user/eeWrDhhLjdI/KQ1iL27XAQAJ

**Comment by jkschneider** [comment]
Looks to me that Infinispan's metrics are wholly covered by the JCache instrumentation, so not going to do anything special there.

**Comment by snicoll** [comment]
I am not following. We used to support a bunch of cache providers and I don't understand the link with Jcache. 

Can you please reconsider or clarify why you closed this?

**Comment by spencergibb** [comment]
I think the only one missing was infinispan

**Comment by jkschneider** [comment]
@snicoll I added support for Ehcache, JCache, and Hazelcast. We already supported Guava and Caffeine. Looking at the Spring Boot 1.5.X line, the only specifically supported cache outside of these was Infinispan, but we only tracked size and hit ratio. Micrometer's new support for JCache does a little better by tracking hits/misses, cache puts, removals, and evictions.

**Comment by snicoll** [comment]
Sorry. We usually close issues with a commit. Closing it with a comment made me think you actually did nothing.
