### ISSUE TITLE
Custom meters' fields are written incorrectly with InfluxMeterRegistry

### ISSUE THREAD

**Issue by zeratul021** [micrometer-metrics/micrometer#1296]
We have some custom meters with custom measurement that we use along with regular counters, gauges, etc.
We noticed an issue how the values appear in the InfluxDB. Instead of value=23 we see **v_al_ue=23**.

Quick debugging brought us to this implementation in InfluxMeterRegistry.writeMeter():
```

        Stream.Builder<Field> fields = Stream.builder();
        for (Measurement measurement : m.measure()) {
            String fieldKey = measurement.getStatistic().toString()
                    .replaceAll("(.)(\\p{Upper})", "$1_$2").toLowerCase();
            fields.add(new Field(fieldKey, measurement.getValue()));
        }

        return Stream.of(influxLineProtocol(m.getId(), "unknown", fields.build()));
```
1. I think instead of *measurement.getStatistic().toString()* we could use something different, e.g. *measurement.getStatistic().getTagValueRepresentation()*.
I can see the regexp later on is heavily opposed (not sure why, no doc around) to upper case letters and Statistic is an enum -> it's gonna always end up bad. We could at least call toLowerCase before replace, not after.
**Anyway, I would greatly appreciate explanation what & why it's happening here**.
2. instead of **"unknown"** type why not use actual type we pass to the Meter and it's Id upon registration?
3. A bit unrelated, but having extended our own InfluxMeterRegistry, the package-private method such *register()* would be really useful to be protected, similar to *newMeter()*. Javadoc mentions "Register a custom meter type".

**Comment by shakuzen** [comment]
> We noticed an issue how the values appear in the InfluxDB. Instead of value=23 we see **v_al_ue=23**.

Thank you for reporting this. It definitely looks like a bug to me. Let's focus this issue on that. Could you open other concerns as separate issues or [join us on Slack](http://slack.micrometer.io) to chat about them?

**Comment by zeratul021** [comment]
@shakuzen will create issue for 2. point and open discussion when free on the 3rd one.
