### ISSUE TITLE
Make LoggingMeterRegistry.Printer configurable

### ISSUE THREAD

**Issue by laxika** [micrometer-metrics/micrometer#1314]
I see no reason why `io.micrometer.core.instrument.logging.LoggingMeterRegistry.Printer` is not configurable by `io.micrometer.core.instrument.logging.LoggingMeterRegistry.Builder`.

I would like to provide my own Printer implementation when printing.

I'm happy to do a PR if you think that this is a good idea as well.

**Comment by shakuzen** [comment]
It could maybe be configurable, but it is intentionally an implementation detail right now, I think. What are you looking to customize by providing your own Printer implementation?

**Comment by laxika** [comment]
I know it's intentional. I would like to print out the actual count for a counter and not just the rate. Also I would like to edit the message format.

**Comment by shakuzen** [comment]
Thanks for the details. A pull request would be welcome.

**Comment by laxika** [comment]
I created a PR for this one. Not exactly what I have originally planned but I think it's even better.

https://github.com/micrometer-metrics/micrometer/pull/1336

The Printer was very tightly coupled to the Registry and I don't want to make any huge changes on that.
