### ISSUE TITLE
Server requests metrics are accumulated to uri=/error in the case of errors

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#132]
![image](https://user-images.githubusercontent.com/1697736/30617384-6c4f7e52-9d5b-11e7-8c59-6ba98d10be27.png)

**Comment by fortu-nato** [comment]
This is a problem for our team as well so it would be nice to have a fix.

**Comment by jkschneider** [comment]
This was fixed when we changed from using a `HandlerInterceptor` to a `MetricsFilter` in 1.0.0-rc.3
