### ISSUE TITLE
Make document type configurable in ElasticMeterRegistry

### ISSUE THREAD

**Issue by malex211** [micrometer-metrics/micrometer#1326]
Currently the document type of the metrics is hardcoded to be `doc` in `ElasticMeterRegistry`. It would be nice (in our case even necessary) to make type configurable.

**Comment by shakuzen** [comment]
Is this necessary for any reason other than supporting Elasticsearch 7? See #1408 where we made sure we handle differences for Elasticsearch 7 related to this.

**Comment by shakuzen** [comment]
Superseded by #1891
