### ISSUE TITLE
Transformation of Meter to Influx line protocol has always 'unknown' metric_type

### ISSUE THREAD

**Issue by zeratul021** [micrometer-metrics/micrometer#1327]
Fork from issue #1296.

Transformation of Meter to Influx line protocol adds Tag *metric_type* with hardcoded value **unknown**.
I think it should respect the registered type from **Meter.getId().getType()**.

```
        Stream.Builder<Field> fields = Stream.builder();
        for (Measurement measurement : m.measure()) {
            String fieldKey = measurement.getStatistic().toString()
                    .replaceAll("(.)(\\p{Upper})", "$1_$2").toLowerCase();
            fields.add(new Field(fieldKey, measurement.getValue()));
        }

        return Stream.of(influxLineProtocol(m.getId(), "unknown", fields.build()));
```
I'd propose following:

1. use *Meter.getId().getType().toLowerCase()* directly in *influxLineProtocol()*, drop the String metricType parameter

or in case this would cause an internal API change

2. use *Meter.getId().getType().toLowerCase()* in *writeMeter()* method instead of **unknown**

**Comment by zeratul021** [comment]
@shakuzen - waiting for triage - do you think this can fit in 1.1.4 milestone?

**Comment by shakuzen** [comment]
I wasn't sure why one would want to make a custom `Meter` with a type of a first-class meter instead of just using the first-class meter, but I suppose there are cases for those types with semantics that differ from Micrometer's implementation. So this change seems reasonable to me.

**Comment by shakuzen** [comment]
Though changing the value of the `metric_type` tag in a point release for custom meters would be a breaking change for people relying on the current value. This makes me lean towards pushing this change out to the 1.2.0 feature release.

**Comment by zeratul021** [comment]
> I suppose there are cases for those types with semantics that differ from Micrometer's implementation. So this change seems reasonable to me.

Exactly our use-cases. 

Meter type is an enum so if I'm forced to choose between _other_ and anything more specific, I'll lean towards the latter.

> Though changing the value of the metric_type tag in a point release for custom meters would be a breaking change for people relying on the current value.

You are right. I was thinking of that too.
Maybe we could add a new field **metricType** to _Meter_ that would be used translated to **metric_type**  with default value set to current **unknown**. That way it would be backwards compatible.

**Comment by izeye** [comment]
I created #1446 to try to resolve this as @zeratul021 suggested.
