### ISSUE TITLE
[Stackdriver] A maximum of 200 TimeSeries can be written in a single request

### ISSUE THREAD

**Issue by cbismuth** [micrometer-metrics/micrometer#1340]
Micrometer 1.1.3
Spring Boot 2.1.3.RELEASE

Hi,

We're encountering this quotas-related error below, should this be handled by Micrometer or by ourselves?

Thanks,
Christophe

Error message:

```
2019-03-28 14:53:01.000  WARN 11949 --- [stackdriver-metrics-publisher] i.m.s.StackdriverMeterRegistry           : failed to send metrics to stackdriver: INVALID_ARGUMENT: Field timeSeries had an invalid value: A maximum of 200 TimeSeries can be written in a single request.
```

Code sample:

```java
    @KafkaListener(topics = {
        "${kolsquare.ingest.kafka.topic.post.batch.name}",
        "${kolsquare.ingest.kafka.topic.post.stream.name}"
    })
    public void listen(final List<String> payloads) {
        try {
            Metrics.summary("ingest.loader.listener.size.summary").record(payloads.size());

            final List<Post> posts = resolvePosts(payloads);
            postRepository.updatePosts(posts);

            final Set<User> users = resolveUsers(posts);
            userRepository.updateUsers(users);

            Metrics.counter("ingest.loader.listener.success.counter").increment();
        } catch (final Exception e) {
            LOGGER.error(e.getMessage(), e);

            Metrics.counter("ingest.loader.listener.failure.counter").increment();

            throw e;
        } finally {
            Metrics.counter("ingest.loader.listener.total.counter").increment();
        }
    }
```

References:
* https://cloud.google.com/monitoring/quotas

**Comment by cbismuth** [comment]
I'll try to override the default batch size which is 10 000.

```java
@Component
class StackdriverProperties extends StepRegistryProperties {

    private final String projectId;

    StackdriverProperties(@Value("${kolsquare.ingest.google.projectId}") final String projectId) {
        this.projectId = projectId;
    }

    String getProjectId() {
        return projectId;
    }

    @Override
    public Integer getBatchSize() {
        return 200;
    }
}
```

**Comment by cbismuth** [comment]
After debugging, the `i.m.s.StackdriverMeterRegistry#publish` API finely gets a batch size value of `200`, but we still have the warning in logs and no metric pushed in Stackdriver.

**Comment by cbismuth** [comment]
Finally got to make it work with a batch size value of `199`, this may be related with the `i.m.c.i.u.MeterPartition#partition` API with max value excluded or not.

Maybe a `StackdriverProperties` class should be provided with Micrometer to override the default batch size with a value of `199`, I can open a PR if you want.

**Comment by shakuzen** [comment]
Thank you for reporting this issue, and sorry for the inconvenience.

> Maybe a `StackdriverProperties` class should be provided with Micrometer to override the default batch size with a value of `199`, I can open a PR if you want.

Changing the default is probably also a good idea, but since the Stackdriver API cannot accept more than 200 time series in a request, we should not try to send more than that, even if a user configures that. New Relic has a similar limitation; see
https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java#L110

A pull request would be welcome. I've marked this for inclusion in the upcoming 1.1.4 release.

**Comment by cbismuth** [comment]
Thank you for the pointer @shakuzen, I'll open a PR tomorrow.

**Comment by cbismuth** [comment]
I've opened a PR #1347.

**Comment by cbismuth** [comment]
Version 1.1.4 solves this issue, thanks @shakuzen for this quick release :+1:
