### ISSUE TITLE
Metric names are changed in CloudWatch

### ISSUE THREAD

**Issue by danieljamesscott** [micrometer-metrics/micrometer#1346]
I've noticed that commit https://github.com/micrometer-metrics/micrometer/commit/b7bbea3d6935aaf794d538cf5f6da5155c9bb93f caused a change to the metric names published to CloudWatch. e.g. 1.0.5 sends

```MetricName: jvm.memory.used,Dimensions: [{Name: area,Value: heap}, {Name: statistic,Value: value}]```

But 1.1.3 sends

```MetricName: jvm.memory.used.value,Dimensions: [{Name: area,Value: heap}]```

Was this a deliberate change? And are the names supposed to remain consistent going 
forwards?

I saw this issue related to promethius:

https://github.com/micrometer-metrics/micrometer/issues/1063

But I don't see any other issues related to this.

**Comment by izeye** [comment]
As Micrometer 1.0.x line has reached its EOL and there were no issues related to the change since then, this seems okay to be closed now.

**Comment by marcingrzejszczak** [comment]
Boot 3.1 is the latest supported OSS version. Is this still a problem now?
