### ISSUE TITLE
Memory leak in JvmGcMetrics.bindTo

### ISSUE THREAD

**Issue by blaszczyk** [micrometer-metrics/micrometer#1349]
`JvmGcMetrics.bindTo` registers a listener in the Jvm Gc system:
`((NotificationEmitter) mbean).addNotificationListener((notification, ref) -> {...})`
without the possibility to ever remove it. In an application server environment like tomcat, when undeploying an application that includes micrometer, this prevents the applications classloader together with its whole metaspace from being garbage collected.

**Comment by izeye** [comment]
@blaszczyk Thanks for the report! I created https://github.com/micrometer-metrics/micrometer/pull/1352 to try to resolve this.

**Comment by blaszczyk** [comment]
Thank you for fixing this so quickly. One last question: Will the removal of the listeners be triggered automatically, in particular when using micrometer with spring-boot-actuator, or are there actions required in the client code?

**Comment by izeye** [comment]
@blaszczyk I'd expect the Spring framework invokes its `close()` on context close.
