### ISSUE TITLE
Big increase in p99 latency after migrating to 1.1.3

### ISSUE THREAD

**Issue by Imaskar** [micrometer-metrics/micrometer#1358]
### Setup
A microservice on Java 8, Spring 1.5, Tomcat 8, Micrometer 1.0.5. Two registries are configured for Micrometer: New Relic and Prometheus. 

### Problem
After upgrading from `1.0.5` to `1.1.{0,3,4-SNAPSHOT}` we see a big increase in p99 latency our endpoints, while the average latency stayed the same. Also we see a big latency increase on Prometheus scraping endpoint.

Old p50: 4 ms
Old p99: 25 ms
New p50: 5ms
New p99: 170ms

### Story
First, we had a problem that NewRelic registry was silently stopping pushing metrics. Despite I see in `1.0.5` code, that there is a try/catch in an event loop, we decided to try to upgrade to `1.1.x` branch. It also had this ticket #1228 which we thought might be related to our problem. But when we upgraded to 1.1.3 branch we saw 2 problems:

1. Some metrics were counted twice, which is being addressed in #1282 
2. p99 latency of some of our endpoints went up 10 times, while the average stayed the same.

Then we thought that the two issues might be connected and the latency is caused by doing twice the work needed. Spring Boot [pull request by `izeye`](https://github.com/spring-projects/spring-boot/pull/16221) has a fix for it, but we needed it in `micrometer-spring-legacy`. I made a custom version of micrometer with these changes. 1st problem was gone, we confirmed it on QA (but we couldn't check the latency). Then we pushed it to prod, but the latency issue stayed the same. It means that problems 1 and 2 are not related, which hints that something might be wrong in Prometheus registry.

![withMicro105](https://user-images.githubusercontent.com/7257720/55474007-65450b80-5610-11e9-9c2a-d02b259f29fe.png)

![withMicro113custom](https://user-images.githubusercontent.com/7257720/55474018-6c6c1980-5610-11e9-96df-3c8b5686a6e3.png)

**Comment by mpasha96** [comment]
Faced similar issue in version ` 1.3.1`. Almost 15x latency increase on Prometheus scraping endpoint.  ~130ms latency on version ` 1.3.1` and ~8ms latency on `1.0.6`.

Setup: Java 8, Spring Boot 1.5

**Version 1.0.6**
![version-1 0 6](https://user-images.githubusercontent.com/24952399/86454724-1a490500-bd39-11ea-9bec-0af265569c1c.png)


**Version 1.3.1**
![version1 3 1](https://user-images.githubusercontent.com/24952399/86454704-13ba8d80-bd39-11ea-8269-c507beab61fd.png)

**Comment by shakuzen** [comment]
We're going to need more information if we hope to track this down. The issue is quite old now, so please try with the latest version and if there is still an issue to investigate, please open a new issue with a minimal sample project including steps to reproduce.
