### ISSUE TITLE
Docs: Add CloudWatch to the list of supported backends, document

### ISSUE THREAD

**Issue by holyjak** [micrometer-metrics/micrometer#1393]
Since there is https://github.com/micrometer-metrics/micrometer/tree/master/implementations/micrometer-registry-cloudwatch, CloudWatch should be mentioned at https://micrometer.io/docs just as InfluxDB & others and preferably link to a page with some documentation (such as the required IAM permissions to be able to use it).

Regarding IAM: perhaps only `cloudwatch:PutMetricData` needed?

Thank you!!!

**Comment by izeye** [comment]
Duplicate of https://github.com/micrometer-metrics/micrometer-docs/issues/49

**Comment by izeye** [comment]
@holyjak Thanks for the report but there's already an issue for it.

> Regarding IAM: perhaps only `cloudwatch:PutMetricData` needed?

In regards to this specific question I'm not a CloudWatch user but the permission seems sufficient for Micrometer to work just by guessing based on its name.

**Comment by mateuszmrozewski** [comment]
`cloudwatch:PutMetricData` is enough from the IAM permissions side
