### ISSUE TITLE
HibernateMetricsAutoConfiguration not included in spring.factories

### ISSUE THREAD

**Issue by mwesolowski** [micrometer-metrics/micrometer#1394]
Shouldn't io.micrometer.spring.autoconfigure.orm.jpa.HibernateMetricsAutoConfiguration be included in micrometer-spring-legacy/src/main/resources/META-INF/spring.factories?

**Comment by izeye** [comment]
@mwesolowski Thanks for the report! You're right. It seems missed somehow. I created https://github.com/micrometer-metrics/micrometer/pull/1395 to resolve it.
