### ISSUE TITLE
Log CloudWatch metric data when publishing fails

### ISSUE THREAD

**Issue by danieljamesscott** [micrometer-metrics/micrometer#1396]
When a failure occurs while sending to cloudwatch, I can see the exception in the logs:

https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java#L116

It would be useful to log the `metricData`, or possibly `putMetricDataRequest`. Would you accept a PR which does this?

**Comment by izeye** [comment]
@danieljamesscott Thanks for the suggestion! Sounds reasonable to me. FYI we already have error request logging for Elasticsearch. See https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java#L171

**Comment by danieljamesscott** [comment]
So would you want to only log it on debug? I would think that it would be OK to log it in the error log line?

**Comment by izeye** [comment]
@danieljamesscott I think it should be debug for consistency. If you think error fits better, you'd better open a separate issue for it as the change should be done across all meter registries consistently.

**Comment by danieljamesscott** [comment]
My PR logs request/response data when there is an error sending to the registries

**Comment by izeye** [comment]
@danieljamesscott Thanks for creating the PR but I expected to create a separate issue for discussion if you want to change the existing log level. I don't have a strong opinion on it but looking at https://github.com/micrometer-metrics/micrometer/pull/1289#issuecomment-479363103, @shakuzen seems to have an opinion on this, so I thought it'd be better to discuss it in a dedicated issue before acting on it.

**Comment by danieljamesscott** [comment]
Yep, understood. But logging on debug is useless for me because it's inconsistently reproducible - I can't run with debug logging enabled all the time. I'm using an extended `CloudWatchMeterRegistry` containing the required logging - so the problem is solved for me.

**Comment by shakuzen** [comment]
> But logging on debug is useless for me because it's inconsistently reproducible - I can't run with debug logging enabled all the time.

You should be able to configure your logging system to log DEBUG level for a specific logger (often corresponding to a single class), rather than all logging. Would that work for your purposes? Configuring the logging system as needed seems preferable to a custom MeterRegistry implementation.

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer/pull/4773 to try to resolve this.
