### ISSUE TITLE
micrometer-spring-legacy lacks support for the cloudwatch registry

### ISSUE THREAD

**Issue by holyjak** [micrometer-metrics/micrometer#1399]
The [io.micrometer.spring.autoconfigure.export](https://github.com/micrometer-metrics/micrometer/tree/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export) provides Spring integration for all supported systems but not for CloudWatch. For CloudWatch, [this line from Spring 1.5 docs is a lie](https://micrometer.io/docs/ref/spring/1.5):

> Spring Boot auto-configures a composite meter registry and adds a registry to the composite for each of the supported implementations that it finds on the classpath. Having a dependency on micrometer-registry-{system} in your runtime classpath is enough for Spring Boot to configure the registry. 

Please add it :-)

(I will likely send a PR to fix this.)

**Comment by izeye** [comment]
@holyjak Thanks for the suggestion but an auto-configuration for the CloudWatch lives in the Spring Cloud AWS repo. See https://github.com/spring-cloud/spring-cloud-aws/tree/master/spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/metrics

See also https://github.com/spring-projects/spring-boot/pull/11276 for background.

**Comment by holyjak** [comment]
Thanks a lot, @izeye ! But I see that `spring-cloud-aws-autoconfigure` includes it only from version 2.0.x so I guess my only option is to copy, paste, and adjust the packages from the 2.0.0 version...

**Comment by izeye** [comment]
@holyjak Sorry, I missed the fact that you want to use `micrometer-spring-legacy`.

`micrometer-spring-legacy` is just a module to provide Spring Boot 2.x integration for Spring Boot 1.x with the best effort by backporting changes from the Spring Boot 2.x repo. So based on the decision from Spring Boot, I think the only option for you is what you've mentioned above.

**Comment by holyjak** [comment]
@zverbatim Yes, I did - see https://gist.github.com/holyjak/70115d2c0fe3a2f0f856a678342ba61a

**Comment by zverbatim** [comment]
@holyjak thank you very much! It was helpful.
