### ISSUE TITLE
Support: Write to 2 different databases

### ISSUE THREAD

**Issue by Feralus** [micrometer-metrics/micrometer#140]
Is it possible to export the metrics to 2 or more different databases?
I have an multi tenancy application and want to export metrics to different influxdb-databases.

Is this somehow possible?

**Comment by jkschneider** [comment]
Yes, you can use a `CompositeMeterRegistry` and add two different Influx registries to it.

```
CompositeMeterRegistry composite = new CompositeMeterRegistry();
composite.add(new InfluxMeterRegistry(config1));
composite.add(new InfluxMeterRegistry(config2));

composite.counter("my.counter")...;
```
