### ISSUE TITLE
Issue when creating Elasticsearch Index

### ISSUE THREAD

**Issue by kevcodez** [micrometer-metrics/micrometer#1408]
Using Spring Boot with actuator and micrometer-registry-elastic.

Versions:

* Spring Boot 2.1.4.RELEASE
* Micrometer registry elastic 1.1.4
* Elasticsearch 7.0

I am getting the following exception ONCE when submitting the metrics to Elasticsearch:

```
failed to add metrics template to elastic: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [_default_ : {_all={enabled=false}, properties={name={type=keyword}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {_all={enabled=false}, properties={name={type=keyword}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [_default_ : {_all={enabled=false}, properties={name={type=keyword}}}]"}},"status":400}

```

I am getting data into the index, not sure if anything is missing due to the previous error.

**Comment by shakuzen** [comment]
I am guessing it is an issue with the index template containing something no longer supported in Elasticsearch 7.0. If metrics are still saved successfully, that's good there's no effective impact, but certainly we'll want to update things to avoid the warning. A pull request from anyone would be appreciated, keeping compatibility with previous versions of Elasticsearch also.

**Comment by pete-woods** [comment]
Some insight from looking into a related project (Zipkin), this is how they are handling the different versions of ElasticSearch:

https://github.com/apache/incubator-zipkin/blob/bf9350eceef8d4b58fb0c7e63ad83e277de4db00/zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/VersionSpecificTemplates.java

You can see the diff here:
https://github.com/apache/incubator-zipkin/pull/2398/files

**Comment by pete-woods** [comment]
I see, significantly:
- `if (templates.version() >= 7) builder.addQueryParameter("include_type_name", "true");` on the URL
- In the payload: `"\"_default_\": { \"_all\": {\"enabled\": false} },\n"` for < 5 and not at all for 5+
- Also for >=7 `Colons are no longer allowed in index names`

**Comment by izeye** [comment]
I created #1428 to try to resolve this.
