### ISSUE TITLE
PrometheusTimer - Avoid overflow

### ISSUE THREAD

**Issue by nhmarujo** [micrometer-metrics/micrometer#1410]
There is a high risk of overflow on timers for **Prometheus**. The majority of the monitoring systems are not prone to this, because they follow a rate normalized approach, while for **Prometheus** it needs to keep the cumulative value of the durations measured.

For **Prometheus** a timer holds internally a **long** that accumulates the durations in **nanoseconds**. The maximum value of a long is **9.223.372.036.854.775.807**, which means that it will hold up to **292.47 years**, given the base unit is **nanoseconds**.
Assuming some long durations at a relatively high frequency, it is really easy to reach that **292.47 years** threshold and overflow.

That said, I think it would be beneficial to assume lower precision specifically for **PrometheusTimer** (at **millisecond** level, which is enough for most applications), thus being able to greatly increase the overflow limit (would still be able to hold up to **292471208.68 years**, which is a huge improvement).

**Comment by adoelger** [comment]
Is there are solution or workaround for this problem available?

**Comment by shakuzen** [comment]
> Assuming some long durations at a relatively high frequency, it is really easy to reach that **292.47 years** threshold and overflow.

Most often Timers will be measuring execution occurring within the application. Do you mean using a Timer to record durations from something other than real-time execution in the application? Or that you're measuring some execution(s) with continuous high concurrency per application instance (thousands of executions per second) over a long uptime? If the length of execution is long and it is more interesting to get metrics on active executions, maybe you want a LongTaskTimer instead.

> Is there are solution or workaround for this problem available?

I suppose right now you could extend the PrometheusMeterRegistry and provide your own PrometheusTimer implementation that does something like suggested in the issue description.

**Comment by jkschneider** [comment]
This is roughly:

```
292 * 365 * 24 * 60 * 60 * 1000 = 9,208,512,000,000 ms
```

Assuming that a service is running at 1,000 RPS with 100ms response times (that's one hell of a thread pool for that long of a response time), it still takes:

```
90,208,512 / 60 / 60 / 24 = 1,065 days to overflow
```

I just can't imagine a timer used how it's supposed to be used overflowing like this. What is being measured?

**Comment by jkschneider** [comment]
I wouldn't favor losing nanosecond precision on account of this edge case, but if there is a good case that can be made for timers overflowing, I could imagine supporting downscaling the resolution of the internal counter to milliseconds as it approaches max long.

**Comment by adoelger** [comment]
My use case is the following:
We have an asynchronous event processing application. Events are ingested into Azure EventHub (similar to Apache Kafka) the event processor reads from the EventHub and process the data. I want to measure the time between ingest into the EventHub and the final processing. Up to 2.000 events are processed per second. If ingested events can be processed in-time (around 2-3 seconds from ingested to processed) everything is fine. But if over some period of time more events are ingested then could be processed the overall processing time could go up to multiple hours. Counting 2.000 events per seconds with a duration of multiple hours lead to an overflow.

My current solution is to use a DistributionSummary and report processing time in seconds.

**Comment by jkschneider** [comment]
@adoelger This sounds like the perfect application of a `LongTaskTimer`.
