### ISSUE TITLE
Using a `MeterFilter` to modify the SLAs of an existing timer is not intuitive

### ISSUE THREAD

**Issue by fitzoh** [micrometer-metrics/micrometer#1414]
`Timer.Builder::sla` takes a `Duration...`, which is self-explanatory.

If you need to create/modify SLA boundaries for that `Timer`, (I think) you need to use a `MeterFilter` to create a new `DistributionStatisticConfig` and merge it with the existing one.

`DistributionStatisticConfig.Builder::sla` takes a `long...`, and the Javadoc provides no guidance on the units.  Only by reading the `Timer.Builder::sla` source did I discover that the long values were meant to be nanoseconds.  I understand that `Timer`s aren't the only object that use a distribution configuration, but there should still be an easier way to figure out how to update them.

Possible remedies:

* update the `DistributionStatisticConfig.Builder::sla` to mention the unit for timers
* include a `DistributionStatisticConfig.Builder::sla` overload which takes a `Duration...`, with a warning in the Javadoc that this should only be used for `Timer`s.

(In case you're curious why I ran into this scenario, I'm attempting to instrument an existing Dropwizard/Jetty based application with Micrometer and was attempting to set up distribution statistics for a `MetricsApplicationEventListener`/`MetricsRequestEventListener`)

**Comment by jkschneider** [comment]
There is already a `Timer.builder::sla` method which takes a `Duration`. Is this what you're looking for? https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/Timer.java#L379

**Comment by fitzoh** [comment]
Bleh, I put the wrong class in the `Possible remedies` section...

In a `MeterFilter` you only have access to a `DistributionStatisticConfig`, which doesn't have a clean way to set times via `Durations`

**Comment by shakuzen** [comment]
Fixing the JavaDoc to mention the implicit units (when it is time) is definitely welcome. Whether we make another method or not, we will be keeping that existing one for backwards compatibility in at least maintenance versions for a the foreseeable future.
