### ISSUE TITLE
Design limitation on FlavorStatsdLineBuilder 

### ISSUE THREAD

**Issue by jlerbsc** [micrometer-metrics/micrometer#1417]
FlavorStatsdLineBuilder class defines the method 

    abstract String line(String amount, @Nullable Statistic stat, String type); .

The default visibility of this method limits the extension or the use of adapter to accomodate to a specific design.

**Comment by shakuzen** [comment]
I'm curious what is the use case? Are you using some system that ingests a StatsD format we don't currently support? Those classes are in an internal package, so I assume they weren't intended to be extended by users, but it is something we can consider changing.

**Comment by jlerbsc** [comment]
I'm closing this issue because unfortunately I've forgotten the context of this request.
