### ISSUE TITLE
API suggestion: Separate definition of tag keys and values

### ISSUE THREAD

**Issue by epkugelmass** [micrometer-metrics/micrometer#1422]
Hello! I'd like to offer a suggestion for enhancing the Micrometer API, inspired by one of the aspects of the Prometheus Java API.

Today, most Micrometer entry points for defining and registering a Meter look like this: `Metrics.counter(String name, String... keysAndValues)`. To obtain a Meter, clients must always provide the Meter name as well as any tag keys and values. In my view, this unnecessarily couples definition of a Meter archetype (where the tag values are not yet bound) with individual Meter instances. The effect of this pattern is especially clear when archetypes are bound to classes while instances are bound to objects.

For example, consider a Lollipop. 

```
class Lollipop {

private final String flavor;

Lollipop(String flavor) { this.flavor = flavor; }

void lick() {

   # other stuff
}

}
```

Now we'd like to instrument the Lollipops by counting the number of licks by flavor.

```
class Lollipop {

private final String flavor;
private final Counter counter;

Lollipop(String flavor) { 
  this.flavor = flavor;
  this.counter = Metrics.counter("lollipop_licks", "flavor", flavor);
}

void lick() {
   counter.increment();
   # other stuff
}

}
```

You might instead what to clearly separate the definition of the keys (same across all Lollipops) and values (can vary by Lollipop). This is purely to aid human readability, as I don't assume that this helps Meter creation/registration/lookup in any way.

```
class Lollipop {

static final CounterFactory COUNTER_FACTORY = 
     Metrics.counter("lollipop_licks", Keys.of("flavor"));

private final String flavor;
private final Counter counter;

Lollipop(String flavor) { 
  this.flavor = flavor;
  this.counter = COUNTER_ARCHETYPE.bind(flavor);
}

void lick() {
   counter.increment();
   # other stuff
}

}
```

This mimics the pattern preferred by Prometheus, where (unbound) Meters are stored in static final fields and then bound to label values when needed. https://github.com/prometheus/client_java#registering-metrics

For complicated Meter declarations, this pattern can make it much easier to read and understand the (unbound) Meter definition while also moving the definition complexity out of the instance-object logic. My colleagues and I are considering whether to adopt Prometheus (API) or Micrometer for a project. While the promise of a metrics facade is appealing, we see the current Meter definition API as a notable shortcoming in Micrometer today.

**Comment by epkugelmass** [comment]
I thought about this again overnight. While it would be nice if the Micrometer API supported this style, it's really not crucial because it doesn't impact what's required of any of the backend SPI providers (Prometheus integration, etc.).
If a user cares about building Meters in this way they're free to work on top of the existing Micrometer API with no impact on compatibility (compat story is akin to interface default methods).

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2019. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
