### ISSUE TITLE
Kibana Visualization Help

### ISSUE THREAD

**Issue by sabareeshkkanan** [micrometer-metrics/micrometer#1426]
Finally our metrics are in elastic search but trying to look for tutorials or sample documentation on creating visualizations based on metric shipped by micrometer. Google didnt help much. As because metrics are in 2 different entries there is no obvious way to do this in Kibana. I understand this may not be right place to ask but I thought people here might have come across the same issue. 
For example if I am trying make one visualization lets say gauge that shows committed to used i cant figure out how to do this 

May 17th 2019,   13:52:46.395 | jvm_memory_committed | 190,840,832
May 17th 2019,   13:52:46.395 | jvm_memory_max | 122,912,768
May 17th 2019,   13:52:46.395 | jvm_memory_used | 6,025,728

**Comment by shakuzen** [comment]
I am not aware of any pre-built Kibana dashboards out there for visualizing Micrometer metrics in Elasticsearch, but if someone makes one, feel free to share it here.

**Comment by shakuzen** [comment]
Here is a collection of Kibana visualizations and dashboards recently published by some users that may be useful to other Micrometer users with Elasticsearch and Kibana: https://github.com/acroquest/micrometer-kibana-dashboard

**Comment by sabareeshkkanan** [comment]
@zerglingone
