### ISSUE TITLE
Integration test against supported Elasticsearch versions

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1429]
Let's set up some integration tests (probably with testcontainers) so we can ensure via CI that this works with all the versions we say? https://www.testcontainers.org/modules/elasticsearch/

_Originally posted by @shakuzen in https://github.com/micrometer-metrics/micrometer/pull/1428#issuecomment-493867872_

**Comment by mweirauch** [comment]
I assume one would spin up the testcontainers from within the Java code when running the tests. This implies that every contributor would require a working docker setup. I wouldn't mind. Just thinking loud. (Is this a "contribution-stopper"?)
One way out would be to only run these tests on CI with opt-in when building locally.

**Comment by pukkaone** [comment]
While testcontainers requires Docker, https://github.com/allegro/embedded-elasticsearch is a library that allows Java integration tests to start Elasticsearch in a separate process.

**Comment by izeye** [comment]
@mweirauch Thanks for the feedback! I think we can use similar to [`SkippableContainer` from Spring Boot](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-test-support/src/main/java/org/springframework/boot/testsupport/testcontainers/SkippableContainer.java) for the concern.

@pukkaone Thanks for the suggestion! I think using Testcontainers means broader than this issue. I think we can also use it for integration tests on other metrics backends later.

I'm looking through Testcontainers. When I have something reviewable, I'll create a PR for this.

**Comment by izeye** [comment]
I created #1434 to try to resolve this.

**Comment by shakuzen** [comment]
It took a while but we finally got this setup and can ensure compatibility going forward. Thanks for the work on this @izeye
