### ISSUE TITLE
How to enable  ExcecutorServiceMetrics in SpringBoot 2 ?

### ISSUE THREAD

**Issue by sureshnaik-git** [micrometer-metrics/micrometer#1430]
How can we enable ExecutorServiceMetrics listed here ? 
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java

I am quite new to micrometer, just trying to understand, if any properties would enable this metrics, or we have to create a new auto-configuration for this metrics. Looks like SpringBoot2 doesn't provide auto-configuration by default. 

I did try following config , but that didn't help:
```
management.metrics.enable.executor= true
```
I am basically trying to collect ThreadPoolTaskExcecutor(bean: applicationTaskExecutor) metrics auto-configured by SpringBoot.

Any help is appreciated. 

Thanks,
Suresh

**Comment by shakuzen** [comment]
If Spring Boot doesn't offer auto-configuration of metrics for an executor it makes, you can request they add that, if it is generally useful.
