### ISSUE TITLE
Declarative Annotation Based API for Counters 

### ISSUE THREAD

**Issue by alimate** [micrometer-metrics/micrometer#1435]
Synopsis
--------
Although using `Timer` and `DistributionSummary` we can publish a count of events in addition to other measurements, sometimes it just makes sense to use a plain `Counter`. 

For timers, in order to keep track of how long a particular task is running, we have two options:
 1. Manually starting and stopping the `Timer`.
 2. Declarative time tracking using the `@Timed`.

These two options are complementary to each other. That is, the declarative approach is there to abstract the cross-cutting concern in a nice and familiar enterprise-ish way but we still have the option to manually manage the `Timer`s when we can't use the declarative API.

_For plain `Counter`s, there is no such declarative approach._ 

Recurring Pattern
-------------------
It's a recurring theme to keep track of:
 - A total number of attempts for a particular task.
 - A number of successful attempts.
 - A Number of failed attempts.

For example. when I receive a job submission request, I increment the `job.submission.attempts` by one. If I managed to successfully submit the job, the `job.submission.successful` would be incremented by one. Otherwise, I'd increment the `job.submission.failed` metric.

Suggestion
------------
Alongside the current `Counter` API, we can provide a declarative API to manage counters. For example, we can offer an annotation, e.g. `@Counted`, as the entry point to such API:
```java
/**
 * We expose the following metrics for the methods annotated with this annotation:
 * <ul>
 *     <li>{@code metric.initialSuffix} to represent the number of times the method is executed</li>
 *     <li>{@code metric.succeedSuffix} to represent the number of successful executions.</li>
 *     <li>{@code metric.failedSuffix} to represent the number of failed executions.</li>
 * </ul>
 */
@Inherited
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface Counted {

    /**
     * Determines the basic metric name, e.g. {@code job.submission}.
     * 
     * @return The prefix for all metrics.
     */
    String metric();

    /**
     * Determines the suffix for total attempts.
     * 
     * @return The total attempts suffix.
     */
    String initialSuffix() default "attempts";

    /**
     * Determines the suffix for successful attempts.
     * 
     * @return The successful attempts suffix.
     */
    String succeedSuffix() default "succeed";

    /**
     * Determines the suffix for failed attempts.
     *
     * @return The failed attempts suffix.
     */
    String failedSuffix() default "failed";
}
```

Then we can implement the counting logic using an aspect much like the `TimedAspect`:
```java
@Aspect
public class CountedAspect {

    private static final String EXCEPTION_TAG_NAME = "exception";
    
    private final MeterRegistry meterRegistry;

    public CountedAspect(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;
    }
    
    @Around("@annotation(counted)")
    public Object interceptAndCount(ProceedingJoinPoint pjp, Counted counted) throws Throwable {
        try {
            Counter.builder(initialName(counted)).register(meterRegistry).increment();
            Object result = pjp.proceed();
            Counter.builder(successfulName(counted)).register(meterRegistry).increment();
            
            return result;
        } catch (Throwable e) {
            Counter.builder(failedName(counted))
                .tag(EXCEPTION_TAG_NAME, e.getClass().getSimpleName())
                .register(meterRegistry).increment();
                
            throw e;
        }
    }
    
    private String initialName(Counted counted) {
        return String.format("%s.%s", counted.metric(), counted.initialSuffix());
    }

    private String successfulName(Counted counted) {
        return String.format("%s.%s", counted.metric(), counted.succeedSuffix());
    }

    private String failedName(Counted counted) {
        return String.format("%s.%s", counted.metric(), counted.failedSuffix());
    }
}
```

If you guys are OK with the idea, I'm more than happy to provide a PR.

Cheers 🍻

**Comment by checketts** [comment]
I like this proposal, but would recommend simplifying the suffix idea to use tags instead.  The common usecase I think this helps address is in counting the failure rate.

By default you don't need to track the attempted (aka started) count either. I could see supporting that feature, but disable it by default.

**Comment by alimate** [comment]
@checketts I agree, Using tags would simplify the API.
So, by default, we would just count the failed attempts. If the client has opt-in, we can calculate the total attempts, too.
