### ISSUE TITLE
TomcatMetrics incorrectly assumes that embedded Tomcat's JMX domain will always be Tomcat

### ISSUE THREAD

**Issue by wilkinsona** [micrometer-metrics/micrometer#1438]
There's an assumption in `TomcatMetrics` that the JMX domain used by embedded Tomcat will always be `Tomcat`. This assumption does not hold true as the name of the domain is configurable. In Spring Boot, the name is suffixed by an instance ID if the ID is greater than zero. This is to allow multiple embedded Tomcat web servers to exist and register MBeans at the same time. When this happens and the domain becomes, for example, `Tomcat-1`, MBean-based metrics are lost.

This problem is somewhat related to https://github.com/micrometer-metrics/micrometer/issues/1433 as it could be avoid if the metrics were not reliant upon MBean registration. A shorter term solution would be to make `jmxDomain` on `TomcatMetrics` configurable.

**Comment by izeye** [comment]
@wilkinsona Thanks for the issue! I created #1439 to try to resolve this as you suggested.

**Comment by wilkinsona** [comment]
Thanks, @izeye. FWIW, the proposed changes look good to me.
