### ISSUE TITLE
Duplicate dimensions when common tags are present in Spring Boot.

### ISSUE THREAD

**Issue by fortu-nato** [micrometer-metrics/micrometer#144]
On a Spring Boot (`1.5.2.RELEASE`) project we are using `micrometer-spring-legacy` and `micrometer-registry-prometheus` with version `1.0.0-rc.1`.

We are using a `MeterRegistryConfigurer` to register common tags, as the docs says we should. The metrics reported through the `/prometheus` endpoint contain duplicate dimensions of those tags. 
So if the configurer does something like 'registry.config().commonTags("a", "b", "c", "d")' then we can see entries like this: `jvm_memory_used_bytes{a="b",a="b",area="nonheap",c="d",c="d",id="Code Cache",} 1.3220416E7`.
We are not creating other registries ourselves.

From what I've researched I can see that the common tags are being added to the MeterId on creation in `AbstractMeterRegistry.createId(...)` when called by `Timer.Builder.register(MeterRegistry registry)` and then added again in `AbstractMeterRegistry.registerMeterIfNecessary(...)` when creating the `idWithCommonTags`.

**Comment by jkschneider** [comment]
Good catch, thanks!

**Comment by antonysychov** [comment]
is there a way to handle this in current release 0.12.0.RELEASE ? can I exclude some springboot autoconfiguration ?

**Comment by checketts** [comment]
Why not upgrade to `rc4`? It isn't less stable than `0.12.0.RELEASE`.

**Comment by antonysychov** [comment]
just because it's not backward compatible with 0.12.0.RELEASE

**Comment by antonysychov** [comment]
but ok, I'll try to use rc4
