### ISSUE TITLE
Meta-annotation support for @Timed in Spring Boot.

### ISSUE THREAD

**Issue by fortu-nato** [micrometer-metrics/micrometer#145]
It would be nice to be able to define a new annotation annotated with `@Timed` and with some parameters preset, for example `@Timed(quantiles = {0.5, 0.75, 0.9, 0.99})
public @interface TimedController {
}
`
so that this new one could be used in all our controllers without having to specify on each one the parameters that are common.
Or is there a way to do this already (Define the common parameters of the metric for all controllers)?

**Comment by jkschneider** [comment]
Related to #146.
