### ISSUE TITLE
HazelcastCacheMetrics latency values reported as nanos where they are retrieved as millis

### ISSUE THREAD

**Issue by wneild** [micrometer-metrics/micrometer#1454]
HazelcastCacheMetrics latency values are reported as nanos where Hazelcast (versions >= 3.9) stats report them as milliseconds.

e.g. 
```
cache -> cache.getLocalMapStats().getTotalGetLatency(), TimeUnit.NANOSECONDS)
```
Simply need to correct the TimeUnit to milliseconds but this will break for anyone using an old version of Hazelcast.

**Comment by shakuzen** [comment]
Do you mean that Hazelcast changed the units it returns for these stats, in a non-backwards compatible way? If so, could you link to something from Hazelcast that mentions this change?
Or do you mean that the units were always milliseconds and the code in Micrometer has always been wrong?

**Comment by wneild** [comment]
@shakuzen I'm not entirely clear what the case was before 3.9 but the best reference I could find is that they changed the code off of this pull request and comment explicitly describes a change from nanos to millis being reported https://github.com/hazelcast/hazelcast/pull/10930#issuecomment-315681738. They haven't documented it as a breaking change as far as I can tell even though IMO it looks like it should merit it.

**Comment by izeye** [comment]
If I read the reference PR correctly, it seems to change its internal time resolution from milliseconds to nanoseconds. Hence, there seems to be no change on getters for latencies which `HazelcastCacheMetrics` depends on. They seem to be in milliseconds from the beginning.

I created #1456 to resolve it.
