### ISSUE TITLE
Support JUnit Platform metrics

### ISSUE THREAD

**Issue by sormuras** [micrometer-metrics/micrometer#1455]
The JUnit "5" Platform exposes live test run related events via calling following methods on registered [TestExecutionListener](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/TestExecutionListener.html)s:

![image](https://user-images.githubusercontent.com/2319838/59489329-25a56600-8e82-11e9-946d-72579f7d852c.png)

A `MicrometerTestExecutionListener` could transform those events into _interesting_ metrics:
- live updates of [started|...|finished] container/test events (*2)
- average duration of test executions
- ...

What do you think of implementing and providing such a feature?

(*1) For some more details, see https://junit.org/junit5/docs/current/user-guide/#launcher-api-listeners-custom
(*2) The [`SummaryGeneratingListener`](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/listeners/SummaryGeneratingListener.html) collects data from test run and displays the following summary after a run:
```
Test run finished after 20622 ms
[        12 containers found      ]
[         0 containers skipped    ]
[        12 containers started    ]
[         0 containers aborted    ]
[        12 containers successful ]
[         0 containers failed     ]
[        20 tests found           ]
[         0 tests skipped         ]
[        20 tests started         ]
[         0 tests aborted         ]
[        20 tests successful      ]
[         0 tests failed          ]
```

**Comment by checketts** [comment]
I like this idea. It would be good for the listener to be configurable for a given registry since some we would need to configure where the metrics are being pushed to when the run finishes and also avoid pushing metrics when not in a CI environment.

**Comment by shakuzen** [comment]
This sounds interesting. I think I understand how we could implement a listener to instrument the metrics. My question is about the best way to handle configuration of the MeterRegistry to be used for test execution. I'm imagining most users would want to configure that in their build configuration, like they do other test-related configuration.

**Comment by sormuras** [comment]
Cool to see you like the idea.

FYI - JUnit Platform 1.7 will ship with JFR-based listener. See https://github.com/junit-team/junit5/issues/2272 and the associated PR for details.

**Comment by shakuzen** [comment]
Neat about the JFR-based listener. That doesn't have the same configuration concerns since JFR is built-in to the JRE. Do you have any pointers about anything else that requires some configuration to pass to a Listener? I think we'd want the user to be able to configure a `MeterRegistry` to pass to the listener we make.

**Comment by sormuras** [comment]
Erm, no idea at all ... but anything that's required to get metrics showing up somewhere.

I wanted to point to the `junit-platform.properties` file as a common source of simple configuration, but a listener that is created via the ServiceLoader SPI doesn't get handed over an instance of it at runtime. Test engines and Jupiter extension do get access to those configuration parameters: https://junit.org/junit5/docs/current/user-guide/#running-tests-config-params -- will discuss it with the @junit-team tomorrow.

**Comment by jkschneider** [comment]
I'd like to point out here that in addition to timing individual test executions, we might also look to measure _saturation_ of the parallelization mechanism (e.g. experimental `junit.jupiter.execution.parallel.enabled`).

`LongTaskTimer` is the unfortunately misnamed construct that really is well suited to measure pool saturation and things of this sort. Active parallel test executions vs. the configured max. Highlight areas where additional parallelization may help, or in fact where parallelization is hurting. For example, when increasing parallelization level, does the P90 active task duration increase to the point where we _contention_ for underlying resources is dragging test performance down?

Just a thought.

**Comment by jkschneider** [comment]
>  will discuss it with the @junit-team tomorrow.

@sormuras Any configuration ideas that arose from this?

**Comment by sormuras** [comment]
No, nothing yet. Will keep you updated.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
