### ISSUE TITLE
Support OpenJ9 GC policies

### ISSUE THREAD

**Issue by jschmied** [micrometer-metrics/micrometer#1458]
OpenJ9 (Java11b04) uses different names for GC:
nursery-allocate/nursery-survivor/tenured-SOA/tenured-LOA

Not sure how this fits into the Old/New GcGenerationAge.

https://www.eclipse.org/openj9/docs/gc/

**Comment by jschmied** [comment]
I did a rough implementation of JvmGcMetrics for OpenJ9.
[JvmGcMetrics.java.txt](https://github.com/micrometer-metrics/micrometer/files/3301460/JvmGcMetrics.java.txt)

**Comment by izeye** [comment]
@jschmied Thanks for the suggestion!

I have no experience on Eclipse OpenJ9 but just based on the doc you shared, "nursery area" seems to belong to "young generation" and "tenured area" seems to belong to "old generation". I think it'd be better to map them to the current corresponding concepts if possible rather than creating a dedicated implementation for it.

**Comment by jschmied** [comment]
Hmm, the behavior is different. 
- there are two old pools (small/large)
- there is no "ConcurrentPhase"
Even if we map both GC to same counter/gauges, we have to switch between implementations. This could be done by the memory-pool names. Maybe we can have a shared set of counter/gauges and if a gc has special values the can create them additionally.

**Comment by izeye** [comment]
@jschmied I didn't look into `JvmGcMetrics` in details but there are similar discrepancies among various garbage collectors in Oracle's JVM and I expect it covers them, so it might be possible to fit Eclipse OpenJ9 into it somehow.

**Comment by jschmied** [comment]
"jvm.gc.max.data.size" gives back -1 others work

**Comment by PascalSchumacher** [comment]
It would be great if at least "jvm.gc.live.data.size.bytes" was added.

**Comment by DanHeidinga** [comment]
I'm excited to see the interest in support OpenJ9 in micrometer.  As part of the OpenJ9 developer community, I can help out with this.
