### ISSUE TITLE
More flexible configuration of WebMvcMetrics through properties.

### ISSUE THREAD

**Issue by fortu-nato** [micrometer-metrics/micrometer#146]
I think it would be really nice to configure for example quantiles or histograms in my configuration file rather than have to provide them in all controllers through the use of `@Timed`.
Are there any plans of doing this?

**Comment by jkschneider** [comment]
There is a programmatic, and kind of unwieldy way of doing this in 1.0.0-rc.3:

```
registry.config()
    .meterFilter(new MeterFilter() {
        @Override
        public HistogramConfig configure(HistogramConfig config) {
            return HistogramConfig.builder()
                .publishPercentiles(0.95) // adds 95% to all timers and summaries
                .build()
                .merge(config);
        }
    });
```

There was a lot of machinery to put in place before we can go all the way to properties, but the goal in 1.0.0-rc.4 will be something like this:

```
spring.metrics.filter.guava.*:
   publishPercentiles: 0.95, 0.99
   publishPercentilesHistogram: true
   # plus all the other config options on `HistogramConfig`  

spring.metrics.filter.jvm.*:
   enabled: false         # turn off jvm metrics
```
