### ISSUE TITLE
Run tests on OpenJ9

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1462]
In addition to HotSpot, we try to support OpenJ9 where applicable and feasible. We, however, don't run our test suite on an OpenJ9 JVM to proactively catch issues and ensure compatibility.
We should consider adding an OpenJ9 build.

**Comment by marcingrzejszczak** [comment]
Is this still something we want to do @shakuzen ?

**Comment by shakuzen** [comment]
We claim to support JVM metrics on OpenJ9, so yes, it would generally be good that we actually run tests on OpenJ9. I think it will require creating a custom container image to run tests on or otherwise use different images than the convenience images offered by CircleCI since they rejected the request to add OpenJ9 variants: https://github.com/CircleCI-Public/cimg-openjdk/issues/78
