### ISSUE TITLE
Support Dynatrace custom device group name property.

### ISSUE THREAD

**Issue by s425267** [micrometer-metrics/micrometer#1464]
I see the custom metrics being reported from spring application to dynatrace under the name which I mentioned as device id `management.metrics.export.dynatrace.device-id=@project.artifactId@` but it is under some random custom device group name.

![image](https://user-images.githubusercontent.com/47148956/59772778-6d5d3080-927a-11e9-8dd1-7bbf48d4965e.png)

Can we add a property in DynatraceConfig class to set the group name like `management.metrics.export.dynatrace.group=mycustomgroup`?

I am cool with issuing a PR.

**Comment by checketts** [comment]
Sounds like a good idea. I'm happy to review a PR for it.
