### ISSUE TITLE
Graphite registry - escape dots in tags

### ISSUE THREAD

**Issue by pawel2401** [micrometer-metrics/micrometer#1465]
Hello,
The graphite-registry is not escaping dots in tags - when dot is present in tag name/value it will be treated as next tag value, e.g.
Tag<tagName.subName, tagValue.subValue> will be treated as <tagName, subName, tagValue, subValue>

One of the possible solutions is to escape the dots, for example by replacing them with underscore will fix the issue.
/Regards,
Pawel

**Comment by checketts** [comment]
Are there any other characters that are problematic? Like spaces?

**Comment by pawel2401** [comment]
From graphite doc:

> Graphite understands messages with this format:
>metric_path value timestamp\n
>metric_path is the metric namespace that you want to populate.
>value is the value that you want to assign to the metric at this time.
>timestamp is the number of seconds since unix epoch time.

It is parsing the metrics basing on space split, so I think that spaces should be escaped as well.

**Comment by izeye** [comment]
I created #1498 to try to resolve this and improve Graphite name sanitization in general.

**Comment by msmsimondean** [comment]
@checketts would it be possible to sanitize `?` question marks too?   Spring Boot puts question marks in metric names in some situations.  Here's an example: 

`httpClientRequests.clientName.some.host.name.method.POST.status.200.uri._path?key__clientKey_.count`

If it helps, here are the characters that HostedGraphite (as an example of a hosted Graphite provider) allow in a Graphite metric path: 

` a-zA-Z0-9:\._$%#=\-\[\] `

**Comment by msmsimondean** [comment]
In the example above, the question mark comes from a URI that's embedded in the metric path via a tag.

**Comment by checketts** [comment]
@msmsimondean Could you add that info to @izeye 's PR: https://github.com/micrometer-metrics/micrometer/pull/1498/files#diff-6bc8bb17eeb45b5274912aaa910ac3d7R37 ?

**Comment by shevyf** [comment]
> If it helps, here are the characters that HostedGraphite (as an example of a hosted Graphite provider) allow in a Graphite metric path:
> 
> `a-zA-Z0-9:\._$%#=\-\[\]`

For information, that's a slightly larger list of characters than normal Graphite allows (HG uses different storage). Vanilla Graphite doesn't allow the colon character either, as Whisper stores metrics as files so it would have issues in any OS that prohibits colons in file names (e.g. Windows). The backslashes shown there are just escape characters, for the same reason.
