### ISSUE TITLE
Duplicate Counter increments for same log event

### ISSUE THREAD

**Issue by dn5678** [micrometer-metrics/micrometer#1466]
io.micrometer:micrometer-core:1.1.4

I am trying to track down an issue where the log event counters are over x100 bigger than expected. 

I noticed that in Log4JMetrics, there is a bindTo(MeterRegistry registry) method that is registering the same metricsMeter object to the same root LoggerConfig for every logger created (which is over 100). 

Then, on a single log event, CompositeFilter will loop over these entries and will cause the counter to be incremented on the same filter multiple times. 

The net result is that the counter is being incremented multiple times (x100+) for the same log event. 

Is this a bug, or a configuration issue?

**Comment by izeye** [comment]
@dn5678 Thanks for the report but I couldn't reproduce it with [a sample using the latest version (1.1.5) of Micrometer](https://github.com/izeye/sample-micrometer-spring-boot/tree/log4j2). Could you please provide a sample reproducing it? It's okay to modify mine linked above if you prefer.

**Comment by dn5678** [comment]
Thanks. I loaded a sample project to https://github.com/dn5678/micrometer_1466

Put a break point at Log4j2Metrics.java:159: infoCounter.increment(); then start the app (MainApplication). 

You should see that it is being called multiple times for the same log event.

**Comment by izeye** [comment]
@dn5678 Thanks for the sample! I could reproduce it by changing additivity for the root logger in my sample to false. I initially assumed that additivity for the root logger won't be false, so I'm not sure for what the use case is. Could you please explain why you set additivity for the root logger to false?

**Comment by izeye** [comment]
I created #1470 to try to resolve this as regardless of the validity of the use case, the current behavior doesn't seem to be right.

**Comment by dn5678** [comment]
@izeye I don't know why it is set to false either. I will remove that setting and see if it resolves the problem. Thanks!
