### ISSUE TITLE
Support collectd (input to Graphite, Riemann, etc.)

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#147]

**Comment by jkschneider** [comment]
https://asylum.madhouse-project.org/blog/2014/12/09/monitoring-setup/

**Comment by jkschneider** [comment]
Direct-to-API docs for SignalFX: https://developers.signalfx.com/docs/metric-data-overview

**Comment by jkschneider** [comment]
SignalFX support has moved to #336

**Comment by jkschneider** [comment]
https://github.com/dropwizard/metrics/blob/5.0-development/metrics-collectd/src/main/java/io/dropwizard/metrics5/collectd/CollectdReporter.java

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2018. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
