### ISSUE TITLE
micrometer keep tracking counters and publish 0 values

### ISSUE THREAD

**Issue by bilelkhalsi** [micrometer-metrics/micrometer#1471]
Hello,
I'm using micrometer counter within spring batch jobs. I noticed that micrometer continue to track counter and send 0 values after the job finish.
This behavior creates a huge number of elastic-search documents (1go every day).

**Comment by checketts** [comment]
It sounds like you are experiencing a 'cardinality explosion'. Metrics are best for tracking aggregates of events. Logging is where individual details should be exposed.

A good rule of thumb when adding a tag to a metric is to keep the expected values for that tag 10 values with 100 being a red flag.

The nature of counters are intended to be a monotonic (only increasing number) so you can run queries to find rates of increase, etc.

**Comment by bilelkhalsi** [comment]
@checketts thank you so much.

Concretely, i have some spring-batch jobs. And i need to report the number of items/rows treated by each job. So i configured a listener that looks like this one:
`
@Component
public class MyItemWriterListener implements ItemWriteListener<Domain> {
    private final MeterRegistry meterRegistry;

    @Autowired
    MyItemWriterListener(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;
    }

    @Override
    public void afterWrite(List<? extends Domain> items) {
        Counter counter = Counter.
                builder("domain.insert")
                .tags("Job1")
                .register(meterRegistry);
        counter.increment(items.size());
    }
//...
}

`

**Comment by shakuzen** [comment]
> i tried to remove the counter at the end of the job but this didn't work.

Could you share this portion of the code? The counter should not continue to be reported if it has been removed.

**Comment by bilelkhalsi** [comment]
```
@PreDestroy() 
public void preDestroy() {
meterRegistry.remove(meterRegistry.find("domain.insert").counter());

}
```

**Comment by checketts** [comment]
That is strange that removing after the increment call didn't work. The `@PreDestroy` probably needs to include the tags too in the `find` call.

**Comment by markostijak** [comment]
Hi. I also have a question regarding this. Is there any way to prevent sending zero values, and that it is not using the remove method?

**Comment by shakuzen** [comment]
@markostijak could you open a separate issue describing your situation in more detail (which registry? what's the problem? what's the expectation?) so we can keep better track of things? You can also come chat with us on Slack.

**Comment by jhsenjaliya** [comment]
@shakuzen , was there any issue opened for this? I am observing the same behavior, this must be known issue, probably missing the right config.

**Comment by shakuzen** [comment]
> was there any issue opened for this?

I don't know to what exactly "this" is referring here. It's possible there is another issue covering it. You can search existing issues. If one doesn't exist, you can open one with all the appropriate details for us to investigate/fix.

If you are referring to the original issue raised here, we need a minimal sample/test case reproducing this to explain the behavior or fix any unintentional behavior. If that's something you can provide, we can reopen the issue and look into it more. Please check with the latest versions to ensure things haven't been fixed recently.

**Comment by tharenaaron06** [comment]
> Hello, I'm using micrometer counter within spring batch jobs. I noticed that micrometer continue to track counter and send 0 values after the job finish. This behavior creates a huge number of elastic-search documents (1go every day).

Can you please let me know , how you resolved this issue? thanks in Advance! @bilelkhalsi

**Comment by tharenaaron06** [comment]
I have a question regarding the behavior of Micrometer counters and their interaction with Elasticsearch.

After calling counter.increment(), how can I ensure that the data has been published to Elasticsearch before removing the counter? If I remove the counter immediately after the increment call, will the incremented data still be published?  if not how to publish the incremented data and then remove the counter ? please help 

@shakuzen  @checketts

**Comment by izeye** [comment]
@tharenaaron06 `ElasticMeterRegistry` is a `StepMeterRegistry`, so after a step (`ElasticConfig.step()`), it's been published or it's being published. Waiting two or more steps would guarantee that it's been published.

I'm not sure if there's a better way for it.

**Comment by shakuzen** [comment]
> If I remove the counter immediately after the increment call, will the incremented data still be published?

@tharenaaron06 Generally no. It sounds like you may be looking for a meter expiration feature - see #1114. That said, incrementing a counter and immediately wanting to remove it (after publishing) sounds like a mostly unexpected way to use metrics, so it may be interesting to understand your use case better. Metrics publishing is not guaranteed, so if recording of every event resulting in incrementing a counter is business critical, we generally suggest you don't use metrics for it. That would be more the domain of a data store supporting transactions.

It's easier for us to lose track of discussion on a closed issue, so if you could share more about your use case on #1114 or in a new issue if you think it's a different use case, that will probably be best.
