### ISSUE TITLE
micrometer-registry-influx timeout block main Application

### ISSUE THREAD

**Issue by noxymon** [micrometer-metrics/micrometer#1472]
Hi, i found strange behavior on micrometer registry influx when connection timeout is occurred. it causes stuck in main application.

is there any trick for this issue ?

**Comment by michaelmcfadyen** [comment]
what version on micrometer-registry-influx are you using?

**Comment by michaelmcfadyen** [comment]
From a quick look over the influx registry code any connection issues should not block the main thread. When the influx registry is initialised a separate single thread is configured via a ScheduledExecutorService which will periodically attempt to send the metrics to your influx instance. I can't see any code which is run on the main thread which communicates to influx. 

Personally, I've started up spring boot apps with micrometer configured but no influx host to talk to resulting in micrometer failing to connect to influx. However, this has not caused the application to stop working. 

It would be great if you could provide a sample project or some code that reproduces this issue.

**Comment by izeye** [comment]
I also tried to reproduce this but failed to do so with [this sample](https://github.com/izeye/sample-micrometer/tree/micrometer-gh-1472).

**Comment by noxymon** [comment]
so, i'm using kafka consumer with micrometer library. based on [this issue](https://stackoverflow.com/questions/50687794/spring-boot-kafkalistener-stops-consuming-messages-after-running-some-time) 

it seem's the symptom of the message stopped not caused by micrometer.
