### ISSUE TITLE
Spring boot failed to start after updating to 1.2.0, has to stay with 1.1.5

### ISSUE THREAD

**Issue by DevCeN** [micrometer-metrics/micrometer#1483]
Getting error:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 1 of constructor in io.micrometer.spring.autoconfigure.cache.CacheMetricsRegistrarConfiguration required a bean of type 'io.micrometer.spring.cache.CacheMeterBinderProvider' that could not be found.
    - Bean method 'caffeineCacheMeterBinderProvider' not loaded because @ConditionalOnClass did not find required class 'com.github.benmanes.caffeine.cache.Cache'
    - Bean method 'ehCache2CacheMeterBinderProvider' not loaded because @ConditionalOnClass did not find required class 'net.sf.ehcache.Ehcache'
    - Bean method 'hazelcastCacheMeterBinderProvider' not loaded because @ConditionalOnClass did not find required classes 'com.hazelcast.spring.cache.HazelcastCache', 'com.hazelcast.core.Hazelcast'
    - Bean method 'jCacheCacheMeterBinderProvider' not loaded because @ConditionalOnClass did not find required class 'javax.cache.CacheManager'

Action:
Consider revisiting the conditions above or defining a bean of type 'io.micrometer.spring.cache.CacheMeterBinderProvider' in your configuration.
```

**Comment by izeye** [comment]
@DevCeN Thanks for the report but I couldn't reproduce the failure with [a sample which is using Caffeine](https://github.com/izeye/sample-micrometer-spring-boot/tree/cache). Could you please provide more information to reproduce the failure? A sample to reproduce it would be ideal if possible.

**Comment by DevCeN** [comment]
Thank you @izeye , can't really provide a minimal project right now. In the meantime, not sure if thats related but I am still on Spring Boot 1.5 instead of 2.1.

**Comment by izeye** [comment]
@DevCeN Thanks for the feedback! I missed the package (`io.micrometer.spring.autoconfigure.cache`) of `CacheMetricsRegistrarConfiguration`. However, I still failed to reproduce it with [a sample using Spring Boot 1.5.x](https://github.com/izeye/sample-micrometer-spring-boot/tree/1.5.x-cache). The auto-configuration for cache metrics in Spring Boot 1.5.x has been added since Micrometer 1.2.0 via #1355, so it might affect to it somehow.

**Comment by DevCeN** [comment]
Thanks again @izeye . I finally have time to look at my code again and I can reproduce it using your sample code. So I noticed that I actually do not have the com.github.ben-manes.caffeine:caffeine dependency in my gradle build. If you comment that out you can reproduce the error. Then if you change micrometerVersion to 1.1.5, you won't get it.

It might have been me not adding caffeine as a dependency before in 1.1.5?

**Comment by izeye** [comment]
@DevCeN Thanks for the info 👍 I can see what went wrong now.

When I was porting the auto-configuration for cache metrics from Spring Boot 2.x to 1.5.x in #1355, I missed the semantic change on `@ConditionalOnBean` against multiple beans ("or" in 1.5.x vs. "and" in 2.x).

I created #1484 to resolve it.
