### ISSUE TITLE
[Stackdriver] Allow to set custom MonitoredResource

### ISSUE THREAD

**Issue by YashchenkoN** [micrometer-metrics/micrometer#1489]
Currently, StackdriverMeterRegistry has hardcoded MonitoredResource with type "global" and label "project_id".

There is no possibility to set different resource type other than "global" and put more labels.
Please enhance the code to allow customization of MonitoredResource

**Comment by IRus** [comment]
> and put more labels

Does it differ from contributing [common tags](https://micrometer.io/docs/concepts#_common_tags)?

> There is no possibility to set different resource type other than "global" 

Should it be part of StackdriverConfig? @shakuzen

**Comment by shakuzen** [comment]
> Should it be part of StackdriverConfig? @shakuzen

Yes, I think a configuration option there with a default of "global" for backwards compatibility would make most sense.

**Comment by YashchenkoN** [comment]
Hi @shakuzen,
Please review #1524
