### ISSUE TITLE
Gauges do not send units to CloudWatch

### ISSUE THREAD

**Issue by danieljamesscott** [micrometer-metrics/micrometer#1494]
It looks like guages do not send units to cloudformation:

https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java#L159

Would it be possible to pull the baseunit from the gauge and call the overloaded `metricDatum` message with the units?

**Comment by izeye** [comment]
@danieljamesscott Thanks for the suggestion! I created #1523 to try to resolve it generally.
