### ISSUE TITLE
Jetty metrics springboot

### ISSUE THREAD

**Issue by itsgauravsaxena** [micrometer-metrics/micrometer#1495]
I am trying to include jetty metrics in my springboot 2.0.3.Release configuration so as I can see it my prometheus output. I am somehow not able to do it using JettyStatisticsMetrics. Any idea or example I can refer to?

**Comment by shakuzen** [comment]
Hopefully you closing the issue means that you figured it out. Auto-configuration support for `JettyStatisticsMetrics` was added to Spring Boot in 2.1.0. Support for 2.0.x has ended, by the way, so I would suggest upgrading to the latest 2.1.x version of Spring Boot which should have the auto-configuration you're looking for.
