### ISSUE TITLE
Micrometer's `CompositeMeter`s invalidate all the optimisations that are happening inside native instrumentation libraries

### ISSUE THREAD

**Issue by yskopets** [micrometer-metrics/micrometer#150]
### Issue

At the moment, all `CompositeMeter`s inflict synchronization on every meter update, e.g.
* on every `Counter` [increment](https://github.com/micrometer-metrics/micrometer/blob/e81f194fe6d2daba3c81242e22a63c1c7e0f50c4/micrometer-core/src/main/java/io/micrometer/core/instrument/composite/CompositeCounter.java#L44)
* on every `Timer` [recording](https://github.com/micrometer-metrics/micrometer/blob/e81f194fe6d2daba3c81242e22a63c1c7e0f50c4/micrometer-core/src/main/java/io/micrometer/core/instrument/composite/CompositeTimer.java#L42)
* on every value [observed](https://github.com/micrometer-metrics/micrometer/blob/e81f194fe6d2daba3c81242e22a63c1c7e0f50c4/micrometer-core/src/main/java/io/micrometer/core/instrument/composite/CompositeDistributionSummary.java#L45) by a `DistributionSummary`

Such behaviour contrasts with the one of native instrumentation libraries - `Prometheus`, `Dropwizard`, etc - who try to avoid synchronization as much as possible (by using `LongAdder` or `DoubleAdder`, for example).   

Besides that, `CompositeMeter`s are used by default and there can be even a few of them in a row (one coming from `Spring Context`, another from `globalRegistry`).

### Expected behaviour

`Micrometer` should not change performance characteristics of the native instrumentation library

### Affected versions

v1.0.0-rc.2

**Comment by jkschneider** [comment]
Good point @yskopets. Luckily shouldn't be too difficult to fix.
