### ISSUE TITLE
Incorrect Kafka "last-heartbeat-seconds-ago"/"last-heartbeat" time unit

### ISSUE THREAD

**Issue by pertu** [micrometer-metrics/micrometer#1509]
In `KafkaConsumerMetrics` there is `last-heartbeat` metric attached to `last-heartbeat-seconds-ago` JMX metric.

Original `last-heartbeat-seconds-ago` is in seconds, and `KafkaConsumerMetrics` additionally "converts" it from `MILLISECONDS` to `SECONDS`.
Result: 1 second real value is `0.001` in micrometer gauge.

**Comment by izeye** [comment]
@pertu Thanks for the report! I created #1521 to resolve this and fix other wrong time units.
