### ISSUE TITLE
micrometer-spring-legacy fails with NoClassDefFoundErrororg/springframework/boot/actuate/endpoint/AbstractEndpoint

### ISSUE THREAD

**Issue by trustin** [micrometer-metrics/micrometer#151]
Spring boot 1.5.7.RELEASE and Micrometer 1.0.0-rc.2

I see the following exception when I try to use Prometheus without Spring actuator in my Spring boot application test which is run by JUnit `@RunWith(SpringRunner.class)`:

```
java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/AbstractEndpoint
```

Looking from a debugger, it seems like Spring tries to instantiate `PrometheusScrapeEndpointConfiguration`, which I never enabled. i.e. Unlike the documentation, the scraper endpoint is always enabled even if there's no spring-boot-actuator JAR in the class path.

My `application-*.yml` contains no `endpoints` section and it worked just fine with Micrometer 0.10.0. All I did was just removing `@EnablePrometheusMetrics` which is not necessary anymore in 1.0.0-rc.2.

What's the way to work around this issue when it's not an option to add spring-boot-actuator to my dependencies?

**Comment by mweirauch** [comment]
actuator was a compile time dep in 0.10.0.RELEASE ... optional since 0.11.0.RELEASE
Wrap the endpoint creation in a conditional configuration in case actuator is present?

**Comment by trustin** [comment]
@mweirauch wrote:
> actuator was a compile time dep in 0.10.0.RELEASE ... optional since 0.11.0.RELEASE
Yes, but I excluded actuator and spring web from the transitive dependencies explicitly.

> Wrap the endpoint creation in a conditional configuration in case actuator is present?
I guess this is not a workaround but a suggestion for a fix which requires a modification in Micrometer source code, right?

**Comment by mweirauch** [comment]
If I didn't fail miserably in testing, uncommenting the following line should do:
https://github.com/micrometer-metrics/micrometer/blob/20f234bfe54476fa3c78a9747f765d45baa04eb3/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/prometheus/PrometheusExportConfiguration.java#L99

**Comment by checketts** [comment]
Seems like if Actuator isn't present then we would need to create a `/prometheus` endpoint somehow (or at the least, log out an error so the user knows they aren't completely configured via `@ConditionalOnMissingClass`)

Otherwise there will be no way to scape the Prometheus metrics.

**Comment by mweirauch** [comment]
Yap, thought about the same. Just want to mention an esotheric(?) case:
Given some people can't scrape their instances, but would like to go the push-model-way - e.g. using the simpleclient_pushgateway - and they can't/don't wan't to use actuator, they'd be annoyed by the warning. The warning should not be emmitted in case the endpoint is disabled via configuration.
So mixing the `@ConditionalOnMissingClass` with `@ConditionalOnProperty`. Sounds ok?

**Comment by jkschneider** [comment]
@checketts In the absence of actuator, you can do something like this, but it is ugly:

```java
@RestController
class PrometheusScrapeController {
    private PrometheusMeterRegistry prometheusRegistry;

    public PrometheusScrapeController(MeterRegistry reg) {
        if (reg instanceof CompositeMeterRegistry) {
            prometheusRegistry = ((CompositeMeterRegistry) reg).getRegistries().stream()
                    .filter(PrometheusMeterRegistry.class::isInstance)
                    .map(PrometheusMeterRegistry.class::cast)
                    .findAny().orElse(null);
        }
        else if(reg instanceof PrometheusMeterRegistry) {
            prometheusRegistry = (PrometheusMeterRegistry) reg;
        }
    }

    @GetMapping("/prometheus")
    public void prometheus(HttpServletResponse response) throws IOException {
        if(prometheusRegistry != null) {
            response.setHeader(HttpHeaders.CONTENT_TYPE, TextFormat.CONTENT_TYPE_004);
            response.getWriter().write(prometheusRegistry.scrape());
        }
        else {
            response.setStatus(404);
        }
    }
}
```

**Comment by jkschneider** [comment]
It also occurs to me that we need to think about management security. In Boot 2 the general purpose metrics endpoint is no longer enabled by default as it is deemed to expose sensitive data about the application. The same should be true I suppose of the Prometheus endpoint.

The Prometheus config `scrape_config` does offer a variety of authentication options as well. We need to document the relationship of these options and the authentication options of actuator endpoints as well.

**Comment by jkschneider** [comment]
@wilkinsona What do you think about the Prometheus scrape endpoint sans Actuator? Should we be providing a `@RestController` that they can wire manually in the absence of Actuator? Or do you think that "if you want the out of the box scrape experience for Prometheus you need Actuator"?

**Comment by wilkinsona** [comment]
The latter is consistent with what we’ve done in the past and is my preferred option. Feels like there needs to be a condition in place to switch off the scrape endpoint in the absence of the Actuator.

**Comment by jkschneider** [comment]
@wilkinsona The switch to not configure the scrape endpoint in the absence of Actuator was added in cf0f19d. I agree with your opinion, so this issue is complete.
