### ISSUE TITLE
Uri tag replaced with REDIRECTION when 304 response

### ISSUE THREAD

**Issue by mardoz** [micrometer-metrics/micrometer#1510]
We have an S3 bucket sitting behind a spring-cloud-gateway service and our client makes use of the If-Modified-Since header so that it doesn't have re-download assets from S3 it already has.

Whenever S3 returns a 304 (Not Modified) to indicate that the client should use the cached asset the uri tag gets replaced with "REDIRECTION" in our spring-cloud-gateway metrics which means that unfortunately we lose metrics for which assets clients are attempting to download.

I understand that this retagging occurs to prevent the creation of too many metrics but is there any way we can enable or retrieve this information?

**Comment by izeye** [comment]
@mardoz Do you mean the metrics from [`GatewayMetricsFilter`](https://github.com/spring-cloud/spring-cloud-gateway/blob/master/spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/GatewayMetricsFilter.java)?

**Comment by mardoz** [comment]
My understanding of the Spring Cloud Gateway code isn't the best but that does look like the relevant place.

It looks like SCG is correctly filling the URI but then Micrometer is rewriting the URI because the response code is 304, hence me raising it here and not in the SCG project.

**Comment by izeye** [comment]
@mardoz Thanks for the feedback! Could you please provide the metric name and tags you're seeing?

**Comment by mardoz** [comment]
Sure, here's the Prometheus metric where we see this:
```
http_server_requests_seconds_count{exception="None",instance="i-xxxxxxxxxxxx",job="edge",method="GET",status="304",uri="REDIRECTION"}
```

**Comment by izeye** [comment]
@mardoz Thanks! I'm not familiar with Spring Cloud Gateway but I took an opportunity to create a sample and reproduced what you're seeing. It's the default behavior of `WebFluxTagsProvider` (`DefaultWebFluxTagsProvider`) which Spring Boot provides unless there's a `HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE` attribute. If you want to change the behavior, you need to provide your own `WebFluxTagsProvider` bean. Please see [this sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/micrometer-gh-1510) for an example.

**Comment by mardoz** [comment]
Thanks. I can't see exactly how that works but I'll give it a go.

**Comment by shakuzen** [comment]
@mardoz as @izeye mentioned, the logic for this is in Spring Boot's `DefaultWebFluxTagsProvider`. If you think it makes sense in the general case for 304s to record the actual URI template, you could open an issue in the Spring Boot repository requesting that change.
