### ISSUE TITLE
Human-readable output for SimpleMeterRegistry

### ISSUE THREAD

**Issue by artjock** [micrometer-metrics/micrometer#1527]
When doing first steps with micrometer it's not that straight forward to understand what is going on. It would simplify the learning curve massively if you can just output metrics you've collected in a human-readable form like Dropwizard is doing:

```
-- Gauges ----------------------------------------------------------------------
testLatencyHistogram.le.100
             value = 30.0
testLatencyHistogram.le.12
             value = 4.0
testLatencyHistogram.le.200
             value = 50.0
testLatencyHistogram.le.24
             value = 9.0
testLatencyHistogram.le.50
             value = 15.0
testLatencyPercentile.phi.0.9
             value = 150.994432
testLatencyPercentile.phi.0.97
             value = 150.994432

-- Timers ----------------------------------------------------------------------
testLatency
             count = 50
         mean rate = 11.59 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 0.00 calls/second
               min = 0.02 milliseconds
               max = 156.63 milliseconds
              mean = 83.62 milliseconds
            stddev = 47.23 milliseconds
            median = 90.30 milliseconds
              75% <= 124.76 milliseconds
              95% <= 148.10 milliseconds
              98% <= 148.20 milliseconds
              99% <= 156.63 milliseconds
            99.9% <= 156.63 milliseconds
```

I know you can [hook up](https://micrometer.io/docs/guide/consoleReporter) dropwizard registry, which is convenient for those, who are familiar with dropwizard metrics, but why bother if you can just override `SimpleMeterRegistry`'s `toString` method (or add another method) and print all the metrics in a human-readable form. So far I came up with something like:

```
Gauge test.latency.histogram [tag(le=12)] value=4.0
Gauge test.latency.histogram [tag(le=24)] value=9.0
Gauge test.latency.histogram [tag(le=50)] value=15.0
Gauge test.latency.histogram [tag(le=100)] value=30.0
Gauge test.latency.histogram [tag(le=200)] value=50.0
Timer test.latency []
	count=50, total=4189.092825, mean=83.7818565, max=156.630944
	percentileValues:
		90.0%: 150.994432
		97.0%: 150.994432
	histogramCounts:
		12.0: 4.0
		24.0: 9.0
		50.0: 15.0
		100.0: 30.0
		200.0: 50.0
Gauge test.latency.percentile [tag(phi=0.9)] value=150.994432
Gauge test.latency.percentile [tag(phi=0.97)] value=150.994432
```

But it can be further improved, by properly rounding and indenting numbers, adding units and adding mode to deduplicate technical gauges.

There is also `LoggingMeterRegistry`, but as far as understand it is designed to save metrics to logs, so one line – one meter, also you need to lunch it and it will output metrics regularly, which is inconvenient for my use cases.

Two main use cases I can see:

1. Learning micrometer, doing first steps, playing with metrics and output when you need it.
1. Instrument some local test project, where you want to benchmark different approaches and output human-readable stats.

The implementation I have in mind is to override `toString` method for `SimpleMeterRegistry`.

Let me know, what do you think, maybe I'm missing something and it already exists. If you like an idea – I can submit a merge request pretty soon.

**Comment by checketts** [comment]
Sounds good. What does the current SimpleMeterRegistry`'s `toString` return right now?

**Comment by artjock** [comment]
It's the default `Object`'s implementation, at least for version 1.2.0:

```
public String toString() {
    return getClass().getName() + "@" + Integer.toHexString(hashCode());
}
```

**Comment by checketts** [comment]
That could really be improved. Go for it and we can iterate on the output format in the PR.

**Comment by shakuzen** [comment]
Just a note that `SimpleMeterRegistry` is mostly for testing purposes, but I can see how it could be nice for initial debugging with Micrometer, and even debugging in tests, perhaps.

**Comment by jkschneider** [comment]
@artjock I think this is now what `LoggingMeterRegistry` is for. Please let me know if there's anything this doesn't cover.
