### ISSUE TITLE
Posting Gauge metrics once per call

### ISSUE THREAD

**Issue by jiwonys** [micrometer-metrics/micrometer#1530]
I know that by default, there is a 1 min interval at which the metrics are posted to the database.
I wanted to see if I could make it post just once per call instead of repeating every minute.
I also wanted to carry out multiple different calls with different values which will be posted according to different endpoints.

What I tried to do was 
for(String key:keys) {
        	produceAllMetrics(key);
        	produceIssueMetrics(key);
        }
				kairos.getRegistry().close();

This turns out to be a disappointment, because I can not open closed registries, and autowire in springboot does not let me instantiate objects.

Does anyone have a way around this?

Thank you

**Comment by shakuzen** [comment]
@jiwonys I see you've closed the issue. Were you able to figure out what you wanted to know?

> I wanted to see if I could make it post just once per call instead of repeating every minute.

Once per call of what?

> I also wanted to carry out multiple different calls with different values which will be posted according to different endpoints.

I'm not understanding what you want to do here. Could you elaborate on this?

> I can not open closed registries

Generally registries are only closed on application shutdown.
