### ISSUE TITLE
Composite meters should ignore Noop children when reporting their value

### ISSUE THREAD

**Issue by sfitts** [micrometer-metrics/micrometer#1537]
The current implementation of the composite meters is to report their value from the first child.  However, if that child is a no-op (because the associated registry denied the meter) then the value reported will be 0.  Since it isn't possible for no-op children to have a meaningful value it would seem to make sense to ignore them when reporting the value of a composite and instead report a value from the first non-noop child.

**Comment by izeye** [comment]
This seems to be a duplicate of #1441.

**Comment by sfitts** [comment]
So it is - sorry -- my search-fu needs improving.
