### ISSUE TITLE
Spring boot Embbeded Tomcat with multiple deployments

### ISSUE THREAD

**Issue by koekj** [micrometer-metrics/micrometer#1538]
When using multiple war files, the TomcatMetrics is only registring the Servlet from the "main" container. This is caused by the fact that the notificationlistener is  removed from the mbean server which is triggered when a new object is registered. 

To my opinion the registration of the listener should be removed, so that when servlets are created manually or when multiple war files are deployed the servlets are registered to be measured by using the mbean listener.

E.g. the following code should be removed from the TomcatMetrics (bold), resulting that servlets are always registered.
 ```
     NotificationListener notificationListener = new NotificationListener() {
            @Override
            public void handleNotification(Notification notification, Object handback) {
                MBeanServerNotification mBeanServerNotification = (MBeanServerNotification) notification;
                ObjectName objectName = mBeanServerNotification.getMBeanName();
                
                perObject.accept(objectName, Tags.concat(tags, nameTag(objectName)));
                **try {
                    mBeanServer.removeNotificationListener(MBeanServerDelegate.DELEGATE_NAME, this);
                } catch (InstanceNotFoundException | ListenerNotFoundException ex) {
                    throw new RuntimeException(ex);
                }**
            }
        };

```
Problems occured when using the hipshoot library to wrap Bloomreach Onehippo into a spring boot application.

**Comment by shakuzen** [comment]
I'll need more time to dig into this and understand your situation, how it differs from the more typical setup, and how changes might affect both.
In the meantime, as a workaround, you can use a custom implementation of `TomcatMetrics` in your applications.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2019. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
