### ISSUE TITLE
Histogram returns 0s at percentiles

### ISSUE THREAD

**Issue by edudar** [micrometer-metrics/micrometer#1539]
Metric monitoring and analysis systems, we use Datadog and an internal system, allow aggregations of a given metric by some dimensions like hostname. Aggregating client-side percentiles between servers is not something very useful but taking one server at a time it should have the same `max`, `min` and `avg` or so I thought. I ran a few tests, looked through HistogramSnapshot and this assumption confirms. This is a test on one server so latency values have very low deviation but `min`, `avg`, and `max` are identical and form one line on the first chart. Multiple lines are different percentiles: 0.5, 0.75, 0.95, 0.99 and 0.999.

![Screen Shot 2019-08-02 at 2 08 54 PM](https://user-images.githubusercontent.com/584181/62403073-beca3200-b53f-11e9-94eb-6ec277609cdb.png)

At some point, however, I noticed that my production latency values are about half of what they are supposed to be. Looking deeper into the individual host stats here's what I came by. Notice that `min` values are all 0s except for a few spikes. As a result, averages now `max + min / 2` where `min = 0`.

![Screen Shot 2019-08-02 at 2 13 57 PM](https://user-images.githubusercontent.com/584181/62403144-34360280-b540-11e9-9397-be87ee2804d5.png)

That was unexpected so I traced to the point where values diverge. Noticed that they trace identically and then `min` somehow drops to 0 and a general observation is that it drops after 20-30 minutes after service start.

![Screen Shot 2019-08-02 at 2 14 52 PM](https://user-images.githubusercontent.com/584181/62403211-9a228a00-b540-11e9-884e-d20144c0c810.png)

I confirmed that both systems we have do show similar charts and so values are reported through statsd. Here's distribution summary config I have:
```
expiry: 10s
bufferLength: 3
minimumExpectedValue: 1000ns
maximumExpectedValue: 1s
percentilePrecision: 2
```

Not sure how is that possible that min and max split for what is supposed to be a single data point (one metric, one host, 10-second interval) and whether it's a bug in or am I missing something.

**Comment by shakuzen** [comment]
Since you are using StatsD to send metrics to DataDog, the aggregation for max/min/avg is not done by Micrometer. Micrometer is sending individual measurements to StatsD.
