### ISSUE TITLE
Make `HierarchicalNameMapper` customizable for Etsy-flavored Statsd

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#156]
Also we may want to provide a generator for a `HierarchicalNameMapper` that turns a defined set of tags into a prefix in the generated metric name. In this way, we accomplish name prefixing on Etsy-flavored StatsD while still maintaining the prefix components as tags for maximum portability to other monitoring systems.

cc / @seonmila

**Comment by dheld-expedia** [comment]
Yes, please!!!
