### ISSUE TITLE
Logging dependencies

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1566]
> that we forward to the correct logging implementation based on the provided registry?

I don't think we're clear on what logging dependencies we have where, and I'd like to clear that up first. @izeye brought this up in https://github.com/micrometer-metrics/micrometer/pull/1475#issuecomment-506583936. I'll make an issue and link it here.

_Originally posted by @shakuzen in https://github.com/micrometer-metrics/micrometer/pull/1532#issuecomment-515289099_

**Comment by shakuzen** [comment]
Here's my archaeology dig on logging throughout the project. Some related early history: #473

---

A search in my IDE on the `1.1.x` branch shows that the following registry implementations already declare a direct dependency on SLF4J in `build.gradle`:

* AppOptics
* Azure
* CloudWatch
* Datadog
* Dynatrace
* Influx
* New Relic
* SignalFX
* Wavefront

---

A number of registry implementations were found to use slf4j classes but not declare a dependency on it. See #1567, #1568, #1569, #1570, #1571.

* Elastic
* Ganglia
* Humio
* Kairos
* Stackdriver

---

micrometer-core uses slf4j in several places although I believe the original intent was to make it not depend on slf4j.

```
micrometer.micrometer-core.main
-- io.micrometer.core.instrument.binder.hystrix
   * MicrometerMetricsPublisherCommand.java
-- io.micrometer.core.instrument.binder.jvm
   * JvmGcMetrics.java
-- io.micrometer.core.instrument.binder.logging
   * LogbackMetrics.java
-- io.micrometer.core.instrument.logging
   * LoggingMeterRegistry.java
-- io.micrometer.core.instrument.push
   * PushMeterRegistry.java
```

`MicrometerMetricsPublisherCommand` will only be used in applications using Hystrix, which has a dependency on slf4j.
`LogbackMetrics` will only be used in applications with Logback which depends on slf4j.
`LoggingMeterRegistry` checks for the presence of slf4j and falls back to `System.out::println` if not available.
`JvmGcMetrics` slf4j usage looks problematic on classpaths without slf4j.
`PushMeterRegistry` slf4j usage effectively makes all implementations require a dependency on slf4j, even though we can't enforce that. All implementations in the main repository are fine except if `LoggingMeterRegistry` threw an error at runtime to cause logging in `PushMeterRegistry`. However, custom implementations of `PushMeterRegistry` or `StepMeterRegistry` would need to be aware of this slf4j dependency.

---

Here is the analysis of the remaining modules.

The Atlas registry's dependency `spectator-reg-atlas` depends on slf4j, so it gets that transitively.

The Graphite registry transitively depends on slf4j via its Dropwizard `metrics-graphite` dependency.

The JMX registry transitively depends on slf4j via its Dropwizard `metrics-jmx` dependency.

The Prometheus registry implementation has no dependency or usage of slf4j or any other logging.

The StatsD registry implementation has no dependency or usage of slf4j. It shades all of its dependencies besides micrometer-core.

micrometer-spring-legacy's only usage is an auto-configuration for LogbackMetrics, but this is guarded by a `ConditionalOnClass`.

micrometer-jersey has no usage of logging.

**Comment by checketts** [comment]
Great analysis! The `PushMeterRegistry` finding seems like the most important to address. I couldn't tell if there were any plans to address that finding (or others), or just making sure we knew about it.

**Comment by shakuzen** [comment]
> The `PushMeterRegistry` finding seems like the most important to address. I couldn't tell if there were any plans to address that finding (or others), or just making sure we knew about it.

I wanted to figure out the complete current state in this issue and decide a direction. @izeye has a pull request open for `PushMeterRegistry` specifically: #1475. As I [commented there](https://github.com/micrometer-metrics/micrometer/pull/1475#discussion_r320550216), the direction is that we will introduce delegating logging that removes the dependency on slf4j.

With that decided, I think we can close this issue and follow up in linked issues. Let me know if anyone has any feedback.
