### ISSUE TITLE
`ExecutorServiceMetrics.monitor` doesn't get common tags applied in `MeterRegistryConfigurer`

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#158]
We need to move up the application of `MeterRegistryConfigurer`s to _before_ a registry is injectable elsewhere to ensure that common tags are uniformly applied.

cc / @mweirauch

**Comment by jkschneider** [comment]
What about uses of the static global composite? How do we ensure that they get common tags?

**Comment by checketts** [comment]
Prometheus has a `clear()` method you could use to reset and re-register metrics

**Comment by jkschneider** [comment]
> What about uses of the static global composite? How do we ensure that they get common tags?

The global composite starts devoid of any registries. As long as Spring doesn’t add any of your configured registries to the global composite until it’s done evaluating all the `MeterRegistryConfigurer`s, there won't be a problem. This is the behavior today.

The metrics generated by interacting with the global registry prior to Spring finishing startup don't go anywhere until startup is done.
