### ISSUE TITLE
DiskSpaceMetrics don't work with Dynatrace

### ISSUE THREAD

**Issue by alternate11** [micrometer-metrics/micrometer#1590]
DiskSpaceMetrics don't work with Dynatrace.

Error from the log:
`2019-09-16 17:05:07,586 ERROR [dynatrace-metrics-publisher] [DynatraceMeterRegistry] failed to send metrics to dynatrace: {"error":{"code":400,"message":"Could not map JSON at 'series[42].dimensions' near line 1 column 6292"}}`

Any ideas?

**Comment by checketts** [comment]
Are you saying if you disable the `DiskSpaceMetrics` that you don't receive this error? Can you capture the JSON being sent and include that in this issue?

**Comment by alternate11** [comment]
Exactly, if I disable DiskSpaceMetrics (and only this one) the errors goes away.
Currently I get the following message in Dynatrace:
> Your custom metrics quota of 100 metrics has been reached. 

I'm not sure if this quote is per day or in general, I haven't quite figured out yet how to make Micrometer visible in Dynatrace.

**Comment by alternate11** [comment]
Error:
> {"error":{"code":400,"message":"Could not map JSON at 'series[42].dimensions' near line 1 column 6255"}}

JSON:
`{"type":"java","series":[{"timeseriesId":"custom:jvm.gc.max.data.size","dataPoints":[[1568761781575,5726797824]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:jvm.memory.used","dataPoints":[[1568761781611,66525152]],"dimensions":{"area":"heap","appStack":"unknown","appId":"tst-server1","id":"PS Old Gen"}},{"timeseriesId":"custom:jvm.buffer.memory.used","dataPoints":[[1568761781612,32]],"dimensions":{"appStack":"unknown","appId":"tst-server1","id":"direct"}},{"timeseriesId":"custom:system.cpu.count","dataPoints":[[1568761781612,8]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:overflowPoolSizeHistogram.sum","dataPoints":[[1568761781612,0]]},{"timeseriesId":"custom:overflowPoolSizeHistogram.count","dataPoints":[[1568761781612,0]]},{"timeseriesId":"custom:overflowPoolSizeHistogram.avg","dataPoints":[[1568761781612,0]]},{"timeseriesId":"custom:overflowPoolSizeHistogram.max","dataPoints":[[1568761781612,0]]},{"timeseriesId":"custom:jvm.threads.states","dataPoints":[[1568761781613,0]],"dimensions":{"appStack":"unknown","appId":"tst-server1","state":"blocked"}},{"timeseriesId":"custom:jvm.threads.states","dataPoints":[[1568761781618,0]],"dimensions":{"appStack":"unknown","appId":"tst-server1","state":"new"}},{"timeseriesId":"custom:jvm.memory.used","dataPoints":[[1568761781619,77459896]],"dimensions":{"area":"nonheap","appStack":"unknown","appId":"tst-server1","id":"Metaspace"}},{"timeseriesId":"custom:jvm.buffer.memory.used","dataPoints":[[1568761781619,0]],"dimensions":{"appStack":"unknown","appId":"tst-server1","id":"mapped"}},{"timeseriesId":"custom:jvm.memory.max","dataPoints":[[1568761781620,1073741824]],"dimensions":{"area":"nonheap","appStack":"unknown","appId":"tst-server1","id":"Compressed Class Space"}},{"timeseriesId":"custom:jvm.threads.daemon","dataPoints":[[1568761781620,62]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:system.cpu.usage","dataPoints":[[1568761781620,0.29939]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:jvm.gc.memory.allocated","dataPoints":[[1568761781621,3482563304]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:jvm.memory.committed","dataPoints":[[1568761781621,30932992]],"dimensions":{"area":"nonheap","appStack":"unknown","appId":"tst-server1","id":"Code Cache"}},{"timeseriesId":"custom:jvm.threads.states","dataPoints":[[1568761781622,16]],"dimensions":{"appStack":"unknown","appId":"tst-server1","state":"runnable"}},{"timeseriesId":"custom:jvm.memory.committed","dataPoints":[[1568761781623,138412032]],"dimensions":{"area":"heap","appStack":"unknown","appId":"tst-server1","id":"PS Survivor Space"}},{"timeseriesId":"custom:overallConnectionAcquireMillis.sum","dataPoints":[[1568761781623,0]]},{"timeseriesId":"custom:overallConnectionAcquireMillis.count","dataPoints":[[1568761781623,0]]},{"timeseriesId":"custom:overallConnectionAcquireMillis.avg","dataPoints":[[1568761781623,0]]},{"timeseriesId":"custom:overallConnectionAcquireMillis.max","dataPoints":[[1568761781623,6]]},{"timeseriesId":"custom:jvm.threads.live","dataPoints":[[1568761781624,114]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:jvm.threads.peak","dataPoints":[[1568761781624,114]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:jvm.memory.used","dataPoints":[[1568761781624,9169904]],"dimensions":{"area":"nonheap","appStack":"unknown","appId":"tst-server1","id":"Compressed Class Space"}},{"timeseriesId":"custom:concurrentConnectionsHistogram.sum","dataPoints":[[1568761781624,0]]},{"timeseriesId":"custom:concurrentConnectionsHistogram.count","dataPoints":[[1568761781624,0]]},{"timeseriesId":"custom:concurrentConnectionsHistogram.avg","dataPoints":[[1568761781624,0]]},{"timeseriesId":"custom:concurrentConnectionsHistogram.max","dataPoints":[[1568761781624,0.000001]]},{"timeseriesId":"custom:jvm.threads.states","dataPoints":[[1568761781624,43]],"dimensions":{"appStack":"unknown","appId":"tst-server1","state":"waiting"}},{"timeseriesId":"custom:process.uptime","dataPoints":[[1568761781625,83806]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:jvm.gc.pause.sum","dataPoints":[[1568761781625,29]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Metadata GC Threshold","action":"end of minor GC"}},{"timeseriesId":"custom:jvm.gc.pause.count","dataPoints":[[1568761781625,2]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Metadata GC Threshold","action":"end of minor GC"}},{"timeseriesId":"custom:jvm.gc.pause.avg","dataPoints":[[1568761781625,14.5]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Metadata GC Threshold","action":"end of minor GC"}},{"timeseriesId":"custom:jvm.gc.pause.max","dataPoints":[[1568761781625,16]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Metadata GC Threshold","action":"end of minor GC"}},{"timeseriesId":"custom:jvm.memory.committed","dataPoints":[[1568761781626,2575302656]],"dimensions":{"area":"heap","appStack":"unknown","appId":"tst-server1","id":"PS Eden Space"}},{"timeseriesId":"custom:jvm.gc.pause.sum","dataPoints":[[1568761781626,438]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Metadata GC Threshold","action":"end of major GC"}},{"timeseriesId":"custom:jvm.gc.pause.count","dataPoints":[[1568761781626,2]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Metadata GC Threshold","action":"end of major GC"}},{"timeseriesId":"custom:jvm.gc.pause.avg","dataPoints":[[1568761781626,219]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Metadata GC Threshold","action":"end of major GC"}},{"timeseriesId":"custom:jvm.gc.pause.max","dataPoints":[[1568761781626,317]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Metadata GC Threshold","action":"end of major GC"}},{"timeseriesId":"custom:process.cpu.usage","dataPoints":[[1568761781626,0.091898]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:disk.free","dataPoints":[[1568761781650,111489384448]],"dimensions":{"path":"C:\TEST\DEV\TST\branches\8.1.1.04\Workspace201909M1\server","appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:maxPoolSizeHistogram.sum","dataPoints":[[1568761781663,0]]},{"timeseriesId":"custom:maxPoolSizeHistogram.count","dataPoints":[[1568761781663,0]]},{"timeseriesId":"custom:maxPoolSizeHistogram.avg","dataPoints":[[1568761781663,0]]},{"timeseriesId":"custom:maxPoolSizeHistogram.max","dataPoints":[[1568761781663,0.0001]]},{"timeseriesId":"custom:jvm.classes.loaded","dataPoints":[[1568761781663,12675]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:jvm.memory.committed","dataPoints":[[1568761781663,716177408]],"dimensions":{"area":"heap","appStack":"unknown","appId":"tst-server1","id":"PS Old Gen"}},{"timeseriesId":"custom:jvm.threads.states","dataPoints":[[1568761781663,55]],"dimensions":{"appStack":"unknown","appId":"tst-server1","state":"timed-waiting"}},{"timeseriesId":"custom:jvm.classes.unloaded","dataPoints":[[1568761781663,0]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:retryAttemptsHistogram.sum","dataPoints":[[1568761781663,0]]},{"timeseriesId":"custom:retryAttemptsHistogram.count","dataPoints":[[1568761781663,0]]},{"timeseriesId":"custom:retryAttemptsHistogram.avg","dataPoints":[[1568761781663,0]]},{"timeseriesId":"custom:retryAttemptsHistogram.max","dataPoints":[[1568761781663,0]]},{"timeseriesId":"custom:jvm.memory.committed","dataPoints":[[1568761781664,85196800]],"dimensions":{"area":"nonheap","appStack":"unknown","appId":"tst-server1","id":"Metaspace"}},{"timeseriesId":"custom:jvm.gc.live.data.size","dataPoints":[[1568761781664,66525152]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:jvm.buffer.count","dataPoints":[[1568761781664,2]],"dimensions":{"appStack":"unknown","appId":"tst-server1","id":"direct"}},{"timeseriesId":"custom:jvm.memory.max","dataPoints":[[1568761781664,251658240]],"dimensions":{"area":"nonheap","appStack":"unknown","appId":"tst-server1","id":"Code Cache"}},{"timeseriesId":"custom:jvm.memory.max","dataPoints":[[1568761781664,138412032]],"dimensions":{"area":"heap","appStack":"unknown","appId":"tst-server1","id":"PS Survivor Space"}},{"timeseriesId":"custom:jvm.buffer.total.capacity","dataPoints":[[1568761781664,32]],"dimensions":{"appStack":"unknown","appId":"tst-server1","id":"direct"}},{"timeseriesId":"custom:connectionAcquireMillis.sum","dataPoints":[[1568761781664,0]]},{"timeseriesId":"custom:connectionAcquireMillis.count","dataPoints":[[1568761781664,0]]},{"timeseriesId":"custom:connectionAcquireMillis.avg","dataPoints":[[1568761781664,0]]},{"timeseriesId":"custom:connectionAcquireMillis.max","dataPoints":[[1568761781664,5]]},{"timeseriesId":"custom:jvm.buffer.count","dataPoints":[[1568761781665,0]],"dimensions":{"appStack":"unknown","appId":"tst-server1","id":"mapped"}},{"timeseriesId":"custom:concurrentConnectionRequestsHistogram.sum","dataPoints":[[1568761781665,0]]},{"timeseriesId":"custom:concurrentConnectionRequestsHistogram.count","dataPoints":[[1568761781665,0]]},{"timeseriesId":"custom:concurrentConnectionRequestsHistogram.avg","dataPoints":[[1568761781665,0]]},{"timeseriesId":"custom:concurrentConnectionRequestsHistogram.max","dataPoints":[[1568761781665,0.000001]]},{"timeseriesId":"custom:jvm.buffer.total.capacity","dataPoints":[[1568761781665,0]],"dimensions":{"appStack":"unknown","appId":"tst-server1","id":"mapped"}},{"timeseriesId":"custom:jvm.memory.max","dataPoints":[[1568761781665,2583691264]],"dimensions":{"area":"heap","appStack":"unknown","appId":"tst-server1","id":"PS Eden Space"}},{"timeseriesId":"custom:jvm.gc.pause.sum","dataPoints":[[1568761781665,26]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Allocation Failure","action":"end of minor GC"}},{"timeseriesId":"custom:jvm.gc.pause.count","dataPoints":[[1568761781665,1]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Allocation Failure","action":"end of minor GC"}},{"timeseriesId":"custom:jvm.gc.pause.avg","dataPoints":[[1568761781665,26]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Allocation Failure","action":"end of minor GC"}},{"timeseriesId":"custom:jvm.gc.pause.max","dataPoints":[[1568761781665,26]],"dimensions":{"appStack":"unknown","appId":"tst-server1","cause":"Allocation Failure","action":"end of minor GC"}},{"timeseriesId":"custom:jvm.memory.used","dataPoints":[[1568761781666,30749696]],"dimensions":{"area":"nonheap","appStack":"unknown","appId":"tst-server1","id":"Code Cache"}},{"timeseriesId":"custom:jvm.threads.states","dataPoints":[[1568761781666,0]],"dimensions":{"appStack":"unknown","appId":"tst-server1","state":"terminated"}},{"timeseriesId":"custom:disk.total","dataPoints":[[1568761781666,510817320960]],"dimensions":{"path":"C:\TEST\DEV\TST\branches\8.1.1.04\Workspace201909M1\server","appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:jvm.memory.committed","dataPoints":[[1568761781670,11272192]],"dimensions":{"area":"nonheap","appStack":"unknown","appId":"tst-server1","id":"Compressed Class Space"}},{"timeseriesId":"custom:jvm.memory.used","dataPoints":[[1568761781670,0]],"dimensions":{"area":"heap","appStack":"unknown","appId":"tst-server1","id":"PS Survivor Space"}},{"timeseriesId":"custom:process.start.time","dataPoints":[[1568761781670,1568761697878]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}},{"timeseriesId":"custom:jvm.memory.max","dataPoints":[[1568761781670,5726797824]],"dimensions":{"area":"heap","appStack":"unknown","appId":"tst-server1","id":"PS Old Gen"}},{"timeseriesId":"custom:connectionLeaseMillis.sum","dataPoints":[[1568761781670,0]]},{"timeseriesId":"custom:connectionLeaseMillis.count","dataPoints":[[1568761781670,0]]},{"timeseriesId":"custom:connectionLeaseMillis.avg","dataPoints":[[1568761781670,0]]},{"timeseriesId":"custom:connectionLeaseMillis.max","dataPoints":[[1568761781670,193]]},{"timeseriesId":"custom:jvm.memory.max","dataPoints":[[1568761781671,-1]],"dimensions":{"area":"nonheap","appStack":"unknown","appId":"tst-server1","id":"Metaspace"}},{"timeseriesId":"custom:jvm.memory.used","dataPoints":[[1568761781671,1048623696]],"dimensions":{"area":"heap","appStack":"unknown","appId":"tst-server1","id":"PS Eden Space"}},{"timeseriesId":"custom:jvm.gc.memory.promoted","dataPoints":[[1568761781671,53148592]],"dimensions":{"appStack":"unknown","appId":"tst-server1"}}]}`

**Comment by izeye** [comment]
@alternate11 Thanks for the report and sharing the request JSON! I found broken parts from the request JSON, for example as follows:

```
      "dimensions": {
        "path": "C:\TEST\DEV\TST\branches\8.1.1.04\Workspace201909M1\server",
        "appStack": "unknown",
        "appId": "tst-server1"
      }
```

I created #1593 to fix this.
