### ISSUE TITLE
Missing connectionCount metric in TomcatMetrics

### ISSUE THREAD

**Issue by rafal-dudek** [micrometer-metrics/micrometer#1598]
We have recently found that Micrometer does not expose 'connectionCount' metrics for Tomcat, as a part of the PR: https://github.com/micrometer-metrics/micrometer/pull/1595 we also spotted that there is no effective test for metrics derived from 'mBeanServer' (in contrast to Manager object) since invalid metrics name would result in zero value rather than exception during initialization.

**Comment by shakuzen** [comment]
> we also spotted that there is no effective test for metrics derived from 'mBeanServer' (in contrast to Manager object) since invalid metrics name would result in zero value rather than exception during initialization.

Could you open a separate issue for this, please? That way we don't lose track of that. A pull request would also be greatly appreciated.

**Comment by shakuzen** [comment]
This is resolved by #2248
