### ISSUE TITLE
micrometer-registry-cloudwatch2 is missing from the BOM

### ISSUE THREAD

**Issue by philwebb** [micrometer-metrics/micrometer#1605]
Originally raised by @dreis2211 [here](https://github.com/spring-projects/spring-boot/pull/18367), it appears that the `micrometer-registry-cloudwatch2` has not been included in the published BOM.

**Comment by philwebb** [comment]
Sorry, ignore me. There is no micrometer BOM yet.

**Comment by shakuzen** [comment]
A Micrometer BOM was added as part of #469 which is part of the upcoming 1.3 release.
