### ISSUE TITLE
Idea: Kotlin extension for easier setup of registries

### ISSUE THREAD

**Issue by JotBePunkt** [micrometer-metrics/micrometer#1607]
I am currenly working on the integration of micrometer metrics in ktor. While doing so I had the idea of a Kotlin DSL to configure the specific registries. 

Here is an idea how I thought about the installation of an AppOptics specific metrics plugin in Ktor:

```
application.install(MicrometerMetricsAppOptics) {
  registry {
    config {
      apiToken = "test"
   }
   clock = Clock.SYSTEM
   }
}
```

this is much easier to read then the traditional way by implementing the configuration interface:
```
application.install(MicrometerMetricsAppOptics) {
  registry = AppOpticsMeterRegistry(object : AppOpticsConfig {
    override fun get(key: String) = null
    override fun apiToken() = "test"
    override fun batchSize() = 5
    override fun hostTag() = "test" 
  }, Clock.SYSTEM)
}
```

I think this DSL would fit better in this project so others project can also use it an not only ktor (or projects based on ktor). 

I would have one additional gradle module per implementation (maybe also one for micrometer-core) so that there is no dependency on kotlin runtime libraries if you just want the Java version. 

What are your thoughts about that?

**Comment by JotBePunkt** [comment]
see full code example here: https://github.com/JotBePunkt/ktor/pull/2

**Comment by shakuzen** [comment]
This sounds like it would be useful for Micrometer users building apps in Kotlin. I'm generally in favor of the idea as long as it doesn't force any Kotlin dependencies on non-Kotlin users. I'll take a closer look into this later as I'm busy with the 1.3 release now.

**Comment by JotBePunkt** [comment]
Continuing to Atlas which is the next in the alphabet, it looks like the actual pattern how to configure MeterRegistries by implementing the *Config Interface originates from the spectator project (see [AtlasConfig](https://github.com/Netflix/spectator/blob/a45c15ee59be2e6c4b3deff2ff4dba1a04397792/spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java) ) which is used in Micrometer directly to configure the [AtlasMeterRegistry](https://github.com/Netflix/spectator/blob/a45c15ee59be2e6c4b3deff2ff4dba1a04397792/spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java).

My interpretation of this design desison is that it is optimized to integrate with a configuration database (or even System.properties) so you usually would only implement the `get(String key)` method. But the more intuitive way is a POJO based configuration (Like in [Spring Boot](https://github.com/spring-projects/spring-boot/blob/aef92b9295f62d008faa9ab79905a474bf3496f3/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/export/atlas/AtlasPropertiesConfigAdapter.java)

To combine both features I suggest a pattern like this (that would be Java only, so also Java users would profit from it):
```java
// original interface for backwards compatibility
interface FooConfig {
     String get(String key);
     default String someConfigValue() {
        String v = get(prefix + "someConfigValue");
        return v != null ? v : "defaultValue";
     }
}
// maybe not use the "Impl" postfix but another package
class FooConfigImpl implements FooConfig {
  private String someConfigValue = super.configValue() // returns the default value from the interface
  // getters/setters
 public String someConfigValue() { 
    return someConfigValue;
 }

  public String get(String key) {
    return null; // to force the default methods return the default values
  }
}
```
This would enable users to configure Registries by just instanciating a Pojo ans setting the necessary values. By using fluent setters, the instantiation (even in Java) would be as easy as this:

```java
FooMeterRegistry registry = new FooMeterRegistry(new FooConfig()
                           .setConfigValue("one"),
                           .setOtherConfig("two"), Clock.System)
```
if we had an addional Kotlin wrapper providing named parameters and a default values for clock it would look like this in Kotlin:
```kotlin
val registry = FooMeterRegistry(FooConfig(
                            configValue = "one",
                            otherConfig = "two"))
```

Both ways much shorter and more expressive then the current. 

To enable the Kotlin support without forcing Java users to have a general dependency there would be two modules:

`micrometer-registry-foo`: (as it is currenly, only dependencies to Java libs)
`micormeter-registry-foo-kotlin`: (having a dependency to micrometer-registry-foo and a dependency to the Kotlin runtime lib)

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2019. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
