### ISSUE TITLE
Incorrect metrics format on /prometheus

### ISSUE THREAD

**Issue by jrcdsf** [micrometer-metrics/micrometer#1611]
We have been using micrometer-registry-prometheus and micrometer-spring-legacy (both version 1.2.1) to expose resilience4j (1.0.0) metrics on /prometheus but somehow the format of the metrics looks weird as shown below:

"# HELP tomcat_sessions_alive_max_seconds  \n# TYPE tomcat_sessions_alive_max_seconds gauge\ntomcat_sessions_alive_max_seconds 0.0\n# HELP apiSession_connections_max  \n# TYPE apiSession_connections_max gauge\napiSession_connections_max 5.0\n# HELP dataSource2_connections_min  \n# TYPE dataSource2_connections_min gauge\ndataSource2_connections_min 5.0\n# HELP dataSource2_connections_active  \n# TYPE dataSource2_connections_active gauge\ndataSource2_connections_active 0.0\n# HELP dataSource_connections_active  \n# TYPE dataSource_connections_active gauge\ndataSource_connections_active 0.0\n# HELP jvm_classes_unloaded_classes_total  \n# TYPE jvm_classes_unloaded_classes_total counter\njvm_classes_unloaded_classes_total 0.0\n# HELP tomcat_global_request_seconds  \n# TYPE tomcat_global_request_seconds summary\ntomcat_global_request_seconds_count{name=\"http-nio-8012\",} 0.0\ntomcat_global_request_seconds_sum{name=\"http-nio-8012\",} 0.0\n# HELP tomcat_sessions_expired_sessions_total  \n# TYPE tomcat_sessions_expired_sessions_total counter\ntomcat_sessions_expired_sessions_total 0.0\n# HELP jvm_buffer_total_capacity_bytes  \n# TYPE jvm_buffer_total_capacity_bytes gauge\njvm_buffer_total_capacity_bytes{id=\"direct\",} 81920.0\njvm_buffer_total_capacity_bytes{id=\"mapped\",} 0.0\n# HELP tomcat_global_sent_bytes_total  \n# TYPE tomcat_global_sent_bytes_total counter\ntomcat_global_sent_bytes_total{name=\"http-nio-8012\",} 0.0\n# HELP process_start_time_seconds  \n# TYPE process_start_time_seconds gauge\nprocess_start_time_seconds 1.569850224007E9\n# HELP tomcat_global_request_max_seconds  \n# TYPE tomcat_global_request_max_seconds gauge\ntomcat_global_request_max_seconds{name=\"http-nio-8012\",} 0.0\n# HELP system_load_average_1m  \n# TYPE system_load_average_1m gauge\nsystem_load_average_1m 1.1\n# HELP tomcat_sessions_rejected_sessions_total  \n# TYPE tomcat_sessions_rejected_sessions_total counter\ntomcat_sessions_rejected_sessions_total 0.0\n# HELP jvm_gc_live_data_size_bytes  \n# TYPE jvm_gc_live_data_size_bytes gauge\njvm_gc_live_data_size_bytes 5.089136E7\n# HELP jvm_memory_max_bytes  \n# TYPE jvm_memory_max_bytes gauge\njvm_memory_max_bytes{area=\"heap\",id=\"PS Survivor Space\",} 3.6175872E7\njvm_memory_max_bytes{area=\"heap\",id=\"PS Old Gen\",} 2.779774976E9\njvm_memory_max_bytes{area=\"heap\",id=\"PS Eden Space\",} 1.31596288E9\njvm_memory_max_bytes{area=\"nonheap\",id=\"Metaspace\",} -1.0\njvm_memory_max_bytes{area=\"nonheap\",id=\"Code Cache\",} 2.5165824E8\njvm_memory_max_bytes{area=\"nonheap\",id=\"Compressed Class Space\",} 1.073741824E9\n# HELP dataSource_connections_max  \n# TYPE dataSource_connections_max gauge\ndataSource_connections_max 5.0\n# HELP log4j2_events_total  \n# TYPE log4j2_events_total counter\nlog4j2_events_total{level=\"warn\",} 6.0\nlog4j2_events_total{level=\"debug\",} 0.0\nlog4j2_events_total{level=\"error\",} 0.0\nlog4j2_events_total{level=\"trace\",} 0.0\nlog4j2_events_total{level=\"fatal\",} 0.0\nlog4j2_events_total{level=\"info\",} 13.0\n# HELP jvm_gc_pause_seconds  \n# TYPE jvm_gc_pause_seconds summary\njvm_gc_pause_seconds_count{action=\"end of major GC\",cause=\"Metadata GC Threshold\",} 1.0\njvm_gc_pause_seconds_sum{action=\"end of major GC\",cause=\"Metadata GC Threshold\",} 0.18\njvm_gc_pause_seconds_count{action=\"end of minor GC\",cause=\"Metadata GC Threshold\",} 1.0\njvm_gc_pause_seconds_sum{action=\"end of minor GC\",cause=\"Metadata GC Threshold\",} 0.015\njvm_gc_pause_seconds_count{action=\"end of minor GC\",cause=\"Allocation Failure\",} 4.0\njvm_gc_pause_seconds_sum{action=\"end of minor GC\",cause=\"Allocation Failure\",} 0.108\n# HELP jvm_gc_pause_seconds_max  \n# TYPE jvm_gc_pause_seconds_max gauge\njvm_gc_pause_seconds_max{action=\"end of major GC\",cause=\"Metadata GC Threshold\",} 0.18\njvm_gc_pause_seconds_max{action=\"end of minor GC\",cause=\"Metadata GC Threshold\",} 0.015\njvm_gc_pause_seconds_max{action=\"end of minor GC\",cause=\"Allocation Failure\",} 0.037\n# HELP process_uptime_seconds  \n# TYPE process_uptime_seconds gauge\nprocess_uptime_seconds 172.088\n# HELP jvm_buffer_count_buffers  \n# TYPE jvm_buffer_count_buffers gauge\njvm_buffer_count_buffers{id=\"direct\",} 10.0\njvm_buffer_count_buffers{id=\"mapped\",} 0.0\n# HELP process_cpu_usage  \n# TYPE process_cpu_usage gauge\nprocess_cpu_usage 0.0037601052829479226\n# HELP process_files_max_files  \n# TYPE process_files_max_files gauge\nprocess_files_max_files 1048576.0\n# HELP jvm_buffer_memory_used_bytes  \n# TYPE jvm_buffer_memory_used_bytes gauge\njvm_buffer_memory_used_bytes{id=\"direct\",} 81920.0\njvm_buffer_memory_used_bytes{id=\"mapped\",} 0.0\n# HELP system_cpu_usage  \n# TYPE system_cpu_usage gauge\nsystem_cpu_usage 0.12220342169580747\n# HELP jvm_gc_max_data_size_bytes  \n# TYPE jvm_gc_max_data_size_bytes gauge\njvm_gc_max_data_size_bytes 2.779774976E9\n# HELP jvm_gc_memory_promoted_bytes_total  \n# TYPE jvm_gc_memory_promoted_bytes_total counter\njvm_gc_memory_promoted_bytes_total 2.5833992E7\n# HELP jvm_memory_used_bytes  \n# TYPE jvm_memory_used_bytes gauge\njvm_memory_used_bytes{area=\"heap\",id=\"PS Survivor Space\",} 2.5925608E7\njvm_memory_used_bytes{area=\"heap\",id=\"PS Old Gen\",} 5.0915936E7\njvm_memory_used_bytes{area=\"heap\",id=\"PS Eden Space\",} 4.343792E7\njvm_memory_used_bytes{area=\"nonheap\",id=\"Metaspace\",} 7.721416E7\njvm_memory_used_bytes{area=\"nonheap\",id=\"Code Cache\",} 2.7113856E7\njvm_memory_used_bytes{area=\"nonheap\",id=\"Compressed Class Space\",} 9577168.0\n# HELP jvm_threads_daemon_threads  \n# TYPE jvm_threads_daemon_threads gauge\njvm_threads_daemon_threads 60.0\n# HELP tomcat_sessions_active_max_sessions  \n# TYPE tomcat_sessions_active_max_sessions gauge\ntomcat_sessions_active_max_sessions 0.0\n# HELP jvm_memory_committed_bytes  \n# TYPE jvm_memory_committed_bytes gauge\njvm_memory_committed_bytes{area=\"heap\",id=\"PS Survivor Space\",} 3.6175872E7\njvm_memory_committed_bytes{area=\"heap\",id=\"PS Old Gen\",} 2.52182528E8\njvm_memory_committed_bytes{area=\"heap\",id=\"PS Eden Space\",} 8.8604672E8\njvm_memory_committed_bytes{area=\"nonheap\",id=\"Metaspace\",} 7.8905344E7\njvm_memory_committed_bytes{area=\"nonheap\",id=\"Code Cache\",} 2.8049408E7\njvm_memory_committed_bytes{area=\"nonheap\",id=\"Compressed Class Space\",} 9961472.0\n# HELP apiSession_connections_min  \n# TYPE apiSession_connections_min gauge\napiSession_connections_min 5.0\n# HELP jvm_threads_peak_threads  \n# TYPE jvm_threads_peak_threads gauge\njvm_threads_peak_threads 71.0\n# HELP tomcat_threads_current_threads  \n# TYPE tomcat_threads_current_threads gauge\ntomcat_threads_current_threads{name=\"http-nio-8012\",} 10.0\n# HELP tomcat_global_received_bytes_total  \n# TYPE tomcat_global_received_bytes_total counter\ntomcat_global_received_bytes_total{name=\"http-nio-8012\",} 0.0\n# HELP jvm_threads_states_threads  \n# TYPE jvm_threads_states_threads gauge\njvm_threads_states_threads{state=\"runnable\",} 11.0\njvm_threads_states_threads{state=\"blocked\",} 0.0\njvm_threads_states_threads{state=\"waiting\",} 30.0\njvm_threads_states_threads{state=\"timed-waiting\",} 26.0\njvm_threads_states_threads{state=\"new\",} 0.0\njvm_threads_states_threads{state=\"terminated\",} 0.0\n# HELP dataSource2_connections_max  \n# TYPE dataSource2_connections_max gauge\ndataSource2_connections_max 5.0\n# HELP jvm_gc_memory_allocated_bytes_total  \n# TYPE jvm_gc_memory_allocated_bytes_total counter\njvm_gc_memory_allocated_bytes_total 3.153132488E9\n# HELP jvm_threads_live_threads  \n# TYPE jvm_threads_live_threads gauge\njvm_threads_live_threads 67.0\n# HELP tomcat_global_error_total  \n# TYPE tomcat_global_error_total counter\ntomcat_global_error_total{name=\"http-nio-8012\",} 0.0\n# HELP process_files_open_files  \n# TYPE process_files_open_files gauge\nprocess_files_open_files 71.0\n# HELP dataSource_connections_min  \n# TYPE dataSource_connections_min gauge\ndataSource_connections_min 5.0\n# HELP apiSession_connections_active  \n# TYPE apiSession_connections_active gauge\napiSession_connections_active 0.0\n# HELP tomcat_threads_busy_threads  \n# TYPE tomcat_threads_busy_threads gauge\ntomcat_threads_busy_threads{name=\"http-nio-8012\",} 0.0\n# HELP tomcat_threads_config_max_threads  \n# TYPE tomcat_threads_config_max_threads gauge\ntomcat_threads_config_max_threads{name=\"http-nio-8012\",} 200.0\n# HELP system_cpu_count  \n# TYPE system_cpu_count gauge\nsystem_cpu_count 8.0\n# HELP tomcat_sessions_active_current_sessions  \n# TYPE tomcat_sessions_active_current_sessions gauge\ntomcat_sessions_active_current_sessions 0.0\n# HELP resilience4j_circuitbreaker_calls Total number of calls by kind\n# TYPE resilience4j_circuitbreaker_calls histogram\n# HELP resilience4j_circuitbreaker_state The state of the circuit breaker:\n# TYPE resilience4j_circuitbreaker_state gauge\n# HELP resilience4j_circuitbreaker_buffered_calls The number of buffered calls\n# TYPE resilience4j_circuitbreaker_buffered_calls gauge\n# HELP resilience4j_circuitbreaker_failure_rate The failure rate\n# TYPE resilience4j_circuitbreaker_failure_rate gauge\n# HELP resilience4j_circuitbreaker_slow_call_rate The slow call rate\n# TYPE resilience4j_circuitbreaker_slow_call_rate gauge\n# HELP jvm_classes_loaded_classes  \n# TYPE jvm_classes_loaded_classes gauge\njvm_classes_loaded_classes 14014.0\n# HELP tomcat_sessions_created_sessions_total  \n# TYPE tomcat_sessions_created_sessions_total counter\ntomcat_sessions_created_sessions_total 0.0\n"

I did copy the text from the browser, it looks like a big double quoted string. Content type looks right, text/plain; version=0.0.4;charset=utf-8
Even if I remove the resilience4j exporters I still have this strange double quoted string with JVM and others metrics.
Our application uses Spring Boot 1.5
Any clues ?
Thanks.

**Comment by jrcdsf** [comment]
![Captura de tela de 2019-09-30 10-34-00](https://user-images.githubusercontent.com/3901128/65884492-53e67d00-e36f-11e9-9a50-6e4a44b0443b.png)

**Comment by izeye** [comment]
@jrcdsf Thanks for the report but I couldn't reproduce the problem with [a sample (Spring Boot 1.5.22.RELEASE, Micrometer 1.2.1)](https://github.com/izeye/sample-micrometer-spring-boot/tree/1.5.x). Could you provide a sample to reproduce it?

**Comment by checketts** [comment]
How are you service the Prometheus metrics on the url `/prometheus`? Are you creating you own `@RequestMapping` and service the metrics as a string, or are you configuring actuator to do that?

Perhaps that config would lend some hints.

**Comment by jrcdsf** [comment]
> How are you serving the Prometheus metrics on the url `/prometheus`? Are you creating your own `@RequestMapping` and serving the metrics as a string, or are you configuring actuator to do that?
> 
> Perhaps that config would lend some hints.

We are using actuator, I forgot to mention that, sorry about it.

Thanks.

**Comment by jrcdsf** [comment]
Here is our pom.xml:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.10.RELEASE</version>
    </parent>

    <groupId>mycompany</groupId>
    <artifactId>marketplace-search</artifactId>
    <version>2.0.0-SNAPSHOT</version>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>

        <spring-boot.version>1.5.4.RELEASE</spring-boot.version>

        <mycompany-service-search.version>1.1.122+20190702.52</mycompany-service-search.version>
        <mycompany-service-recommendation.version>1.0.64</mycompany-service-recommendation.version>

        <mycompany-wsv3-breakdown.version>1.0.88+20190826.54</mycompany-wsv3-breakdown.version>
        <mycompany-commons.version>1.21</mycompany-commons.version>
        <mycompany.messaging.version>1.0.26</mycompany.messaging.version>
        <mycompany-data-alfred-client-api.version>201905301527929</mycompany-data-alfred-client-api.version>

        <HikariCP.version>2.6.1</HikariCP.version>
        <pgjdbc.version>42.2.2</pgjdbc.version>

        <aws.version>1.11.184</aws.version>
        <gson.version>2.7</gson.version>
        <javaee-api.version>7.0</javaee-api.version>
        <commons-io.version>2.4</commons-io.version>
        <commons-lang3.version>3.5</commons-lang3.version>
        <jackson.version>2.9.5</jackson.version>
        <tomcat.version>8.5.28</tomcat.version>

        
        <log4j2.version>2.11.0</log4j2.version>
        <slf4j.version>1.7.25</slf4j.version>
        <disruptor.version>3.3.6</disruptor.version>

        <service-home.version>0.0.1+96.2018-06-21.17-38-13</service-home.version>
        <content-search-model.version>1.0.0+20190924.155</content-search-model.version>
        <content-search-catalog-items-model.version>1.0.0+20190924.113</content-search-catalog-items-model.version>
        <cache2k.version>1.0.2.Final</cache2k.version>
        <spring.cloud.hystrix>1.4.5.RELEASE</spring.cloud.hystrix>
        <logstash-layout.version>0.11</logstash-layout.version>
        <mycompany.service.merchant.version>1.0.180</mycompany.service.merchant.version>
        <java-jwt.version>3.3.0</java-jwt.version>
        <org.json.version>20180813</org.json.version>
        <resilience4j.version>1.0.0</resilience4j.version>
        <micrometer.version>1.2.1</micrometer.version>
        <assertj.version>3.13.2</assertj.version>
        <jayway.version>1.7.0</jayway.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
            <version>${java-jwt.version}</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${org.json.version}</version>
        </dependency>

        <dependency>
            <groupId>com.vlkan.log4j2</groupId>
            <artifactId>log4j2-logstash-layout</artifactId>
            <version>${logstash-layout.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix</artifactId>
            <version>${spring.cloud.hystrix}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.netflix.archaius</groupId>
                    <artifactId>archaius-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.netflix.archaius</groupId>
            <artifactId>archaius-core</artifactId>
            <version>0.7.6</version>
        </dependency>

        <dependency>
            <groupId>com.netflix.hystrix</groupId>
            <artifactId>hystrix-javanica</artifactId>
            <version>1.5.12</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.lmax</groupId>
            <artifactId>disruptor</artifactId>
            <version>${disruptor.version}</version>
        </dependency>

        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-service-recommendation-model</artifactId>
            <version>${mycompany-service-recommendation.version}</version>
        </dependency>

        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-wsv3-breakdown-credentials</artifactId>
            <version>${mycompany-wsv3-breakdown.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>unirest-java</artifactId>
                    <groupId>com.mashape.unirest</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>mycompany-service-payment-client</artifactId>
                    <groupId>mycompany</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>mycompany-service-payment-model</artifactId>
                    <groupId>mycompany</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-wsv3-breakdown-dao-impl</artifactId>
            <version>${mycompany-wsv3-breakdown.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>lucene-core</artifactId>
                    <groupId>org.apache.lucene</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>lucene-analyzers-common</artifactId>
                    <groupId>org.apache.lucene</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-wsv3-breakdown-model</artifactId>
            <version>${mycompany-wsv3-breakdown.version}</version>
        </dependency>

        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-messaging-core</artifactId>
            <version>${mycompany.messaging.version}</version>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-messaging-model</artifactId>
            <version>${mycompany.messaging.version}</version>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-messaging-api</artifactId>
            <version>${mycompany.messaging.version}</version>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-messaging-aws</artifactId>
            <version>${mycompany.messaging.version}</version>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-service-merchant-model</artifactId>
            <version>${mycompany.service.merchant.version}</version>
        </dependency>

        
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>service-content-merchant-search-model</artifactId>
            <version>${content-search-model.version}</version>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>service-content-catalog-items-search-model</artifactId>
            <version>${content-search-catalog-items-model.version}</version>
        </dependency>

        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-geohash</artifactId>
            <version>1.0.1</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-support</artifactId>
        </dependency>

        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>${javaee-api.version}</version>
        </dependency>

        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>${pgjdbc.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.cache2k</groupId>
            <artifactId>cache2k-api</artifactId>
            <version>${cache2k.version}</version>
        </dependency>

        <dependency>
            <groupId>org.cache2k</groupId>
            <artifactId>cache2k-core</artifactId>
            <version>${cache2k.version}</version>
        </dependency>


        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-library</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-service-region-client</artifactId>
            <version>2.1.50</version>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-service-region-model</artifactId>
            <version>2.1.50</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>1.4.4</version>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-service-location-client</artifactId>
            <version>1.1.40</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-email</artifactId>
                    <groupId>org.apache.commons</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>ehcache-core</artifactId>
                    <groupId>net.sf.ehcache</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-core</artifactId>
            <version>1.11.125</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sts</artifactId>
            <version>1.11.125</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.0</version>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>service-home-model</artifactId>
            <version>${service-home.version}</version>
        </dependency>

        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-service-search-model</artifactId>
            <version>${mycompany-service-search.version}</version>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>mycompany-service-search-core</artifactId>
            <version>${mycompany-service-search.version}</version>
        </dependency>
        <dependency>
            <groupId>com.newrelic.agent.java</groupId>
            <artifactId>newrelic-api</artifactId>
            <version>3.43.0</version>
        </dependency>
        <dependency>
            <groupId>mycompany</groupId>
            <artifactId>service-account-model</artifactId>
            <version>0.0.1+112.2018-04-24.14-34-43</version>
        </dependency>
        <dependency>
            <groupId>mycompany.data.alfred</groupId>
            <artifactId>client-api</artifactId>
            <version>${mycompany-data-alfred-client-api.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-core</artifactId>
            <version>${micrometer.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-spring-legacy</artifactId>
            <version>${micrometer.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <version>${micrometer.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-circuitbreaker</artifactId>
            <version>${resilience4j.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-bulkhead</artifactId>
            <version>${resilience4j.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-all</artifactId>
            <version>${resilience4j.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-timelimiter</artifactId>
            <version>${resilience4j.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-micrometer</artifactId>
            <version>${resilience4j.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-prometheus</artifactId>
            <version>${resilience4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <version>${jayway.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}-${project.version}</finalName>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>fabric8-maven-plugin</artifactId>
                <version>3.5.31</version>
                <configuration>
                    <mode>kubernetes</mode>
                    <images>
                        <image>
                            <name>mycompany/marketplace-search</name>
                            <alias>marketplace-search</alias>
                            <build>
                                <dockerFileDir>${project.basedir}/src/main/docker</dockerFileDir>
                                <assembly>
                                    <descriptorRef>artifact</descriptorRef>
                                </assembly>
                            </build>
                        </image>
                    </images>
                </configuration>
                <executions>
                    <execution>
                        <id>fabric8</id>
                        <goals>
                            <goal>resource</goal>
                            <goal>build</goal>
                            <goal>helm</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <scm>
        <developerConnection>scm:git:git@bitbucket.org:mycompany/marketplace-search.git</developerConnection>
        <url>https://bitbucket.org/mycompany/marketplace-search</url>
        <tag>HEAD</tag>
    </scm>

    <repositories>
        <repository>
            <id>nexus-mycompany</id>
            <url>https://nexus.dc.mycompany.com.br/repository/public</url>
        </repository>
    </repositories>

</project>

**Comment by checketts** [comment]
What about the config to make the actuator use that url?

**Comment by jrcdsf** [comment]
Unfortunately I am unable to reproduce the issue by creating a new project with same configs, thanks for your assistance!

Regards, 
JR.
