### ISSUE TITLE
Add more general metrics 

### ISSUE THREAD

**Issue by VinkDong** [micrometer-metrics/micrometer#162]
Could you add more metrics in Prometheus, such as GC, threads, Cpu etc without extra coding?

**Comment by checketts** [comment]
Those are present already see: http://micrometer.io/docs/prometheus#_jvm_and_system_monitoring

**Comment by VinkDong** [comment]
@checketts Thanks a lot, Does it means if I want GC metrics I must add a line 
```
new JvmGcMetrics().bindTo(registry);
```
in the program ?

**Comment by checketts** [comment]
Correct. I believe Spring will autoconfigure those for you if you have the correct dep. But you can do it manually too.

**Comment by jkschneider** [comment]
@VinkDong If this is a Spring app, you can add a bean for it, like so:

```
@Bean
public JvmGcMetrics gcMetrics() { return new JvmGcMetrics(); }
```

Spring is autoconfiguring some binders and not others. `JvmGcMetrics` is _not_ automatically configured. See `MeterBindersConfiguration` in both `micrometer-spring-legacy` and Boot 2 master branch.

**Comment by VinkDong** [comment]
@jkschneider @checketts  Thank you very much, I got it
