### ISSUE TITLE
Lost Counter increments when registering Counters from multiple threads using CompositeMetricsRegistry with Prometheus

### ISSUE THREAD

**Issue by mcekovic** [micrometer-metrics/micrometer#1622]
There is an issue in the Micrometer 1.3.0 (also checked from 1.1.4 onward, but did no check earlier versions) that manifests in the lost Counter increments when registering Counters from multiple threads using CompositeMetricsRegistry with Prometheus.

Here is the minimal example code:

```
package test.micrometer;

import java.util.concurrent.*;

import org.junit.jupiter.api.*;

import io.micrometer.core.instrument.*;
import io.micrometer.core.instrument.composite.*;
import io.micrometer.prometheus.*;

import static org.assertj.core.api.Assertions.*;

class MicrometerCounterRegistrationTest {

	private MeterRegistry meterRegistry = createMeterRegistry();

	private static MeterRegistry createMeterRegistry() {
		CompositeMeterRegistry meterRegistry = new CompositeMeterRegistry();
		meterRegistry.add(new PrometheusMeterRegistry(PrometheusConfig.DEFAULT));
		return meterRegistry;
	}

	@Test
	void testTaggedCounterConcurrently() throws InterruptedException {
		int count = 10000;
		int tagCount = 100;
		var executor = Executors.newFixedThreadPool(10);
		for (int i = 0; i < count; i++) {
			int tagValue = i % tagCount;
			executor.execute(() ->
				createCounter(tagValue).increment()
			);
		}
		executor.shutdown();
		executor.awaitTermination(1L, TimeUnit.DAYS);
		for (int i = 0; i < tagCount; i++)
			assertThat(createCounter(i).count()).isEqualTo(count / tagCount);
	}

	private Counter createCounter(int tagValue) {
		return Counter.builder("test.counter").tag("test.tag", String.valueOf(tagValue)).register(meterRegistry);
	}
}
```

Running the above test couple of times will provoke the issue at least once.
The issue seems to **not** manifest using PrometheusMetricsRegistry directly, **nor** also seems to manifest when using SimpleMetricsRegistry inside the CompositeMeterRegistry.
The sample code runs with JDK 11, JUnit 5, AssertJ and Micrometer (Core and Prometheus) as only dependencies, though issue manifests with JDK 8 too.
Pre-registering Counters in the main thread eliminates the issue.

**Comment by izeye** [comment]
@mcekovic Thanks for the report and the test! I could reproduce this locally with your test, even with `SimpleMeterRegistry`.

There seems to be a race condition between `MeterRegistry.meterMap.plus()` and `CompositeMeter.add()` via meter-added event listener in `MeterRegistry.getOrCreateMeter()`. Hence, an empty `AbstractCompositeMeter.children` could happen while incrementing its children in `CompositeCounter`. I created #1628 to resolve it.
