### ISSUE TITLE
dimensional datamodel and drilling in

### ISSUE THREAD

**Issue by bijukunjummen** [micrometer-metrics/micrometer#163]
Just wanted to see if some of the documentation can be changed for newbies like me - I see the mention of dimensional data-model and ability to drill in based on dimensions, in the home page but no details around what it means. It will be great if some of the documentation of micrometer can cover this in some form

Something along these lines will be great - https://prometheus.io/docs/concepts/data_model/

**Comment by jkschneider** [comment]
Thanks @bijukunjummen. Currently going through a doc reorganization that I hope will help out. See https://github.com/micrometer-metrics/micrometer-docs/issues/6.
