### ISSUE TITLE
Add ability to customize InstrumentedQueuedThreadPool

### ISSUE THREAD

**Issue by IgorPerikov** [micrometer-metrics/micrometer#1639]
Right now [InstrumentedQueuedThreadPool](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPool.java) can be constructed with default underlying values only by implicitly calling no-arg `QueuedThreadPool` constructor, which looks like this:
```java
public QueuedThreadPool()
{
    this(200);
}
```
While I assume default logic might be useful in some cases, having an opportunity to tweak it is something I would really like to have (I have finely tuned threadpool in production). 

If team is fine with this proposal I can provide a PR, which will add bunch of overloaded constructors.

**Comment by IgorPerikov** [comment]
@shakuzen @izeye sorry, if my summon is incorrect - you seemed to be the most active and recent contributors to the micrometer. Would you mind commenting on the issue?

**Comment by izeye** [comment]
@IgorPerikov Thanks for opening an issue. I can see that `InstrumentedQueuedThreadPool` is not fully customizable although there are some setters from `QueuedThreadPool`. To make `InstrumentedQueuedThreadPool` fully customizable, your suggestion seems to make sense. However, I'm not sure that `InstrumentedQueuedThreadPool` has much value as using `JettyServerThreadPoolMetrics` directly seems to be sufficient to me as follows:

```java
        QueuedThreadPool threadPool = new InstrumentedQueuedThreadPool(registry, tags);
```

vs.

```java
        QueuedThreadPool threadPool = new QueuedThreadPool();
        new JettyServerThreadPoolMetrics(threadPool, tags).bindTo(registry);
```

If there's not much benefit from `InstrumentedQueuedThreadPool`, it might be better to deprecate it and encourage to use `JettyServerThreadPoolMetrics` directly.

Could you confirm that using `JettyServerThreadPoolMetrics` directly works for your use case?

**Comment by IgorPerikov** [comment]
`InstrumentedQueuedThreadPool` makes a lot of sense to me because of the following reasons:

1) It would be nice not to care about how exactly I should bind metrics to registry. It's additional code, which can be hidden by underlying abstraction and will remove extra burden from user code.
2) With `InstrumentedQueuedThreadPool` I am able to pass it directly to `org.eclipse.jetty.server.Server`, which on my project is being constructed via spring xml configuration. 

> Could you confirm that using JettyServerThreadPoolMetrics directly works for your use case

So according to the 2nd reason it doesn't really work in my case. I can make it work via defining `QueuedThreadPool` as standalone bean, create `@PostConstruct` block somewhere and bind them, but it will require a lot of boilerplate code just to bind metrics. Also it feels to be not very spring-ish way for me. 

For that reason my current workaround is custom successor, which makes same binding and supports customizing

**Comment by izeye** [comment]
@IgorPerikov Thanks for the quick feedback! My opinion was just based on the amount of code, and I didn't expect `InstrumentedQueuedThreadPool` to be created via XML configuration. Anyway, if `InstrumentedQueuedThreadPool` is still useful, your suggestion seems to be valid to me as I already mentioned in the previous comment. However, I'm not a regular Jetty user, so it'd be better to hear some opinions from a Jetty user.

**Comment by IgorPerikov** [comment]
So I can start working on providing support for this?

**Comment by izeye** [comment]
@IgorPerikov Sorry if I wasn't clear, but I meant that we'd be better to wait for some opinions with the following sentence:

> However, I'm not a regular Jetty user, so it'd be better to hear some opinions from a Jetty user.

Although it sounds reasonable to me, I don't want you to waste time due to my faulty opinion in any case.

**Comment by IgorPerikov** [comment]
Oh, right, sure. Do you know anyone in your team with relevant experience who can help with assessing what we have discussed here?

**Comment by shakuzen** [comment]
I'm also not a Jetty user, but adding a couple of constructors to `InstrumentedQueuedThreadPool` sounds reasonable. Delegation instead of extension seems like it would avoid potential explosion of constructors needed, but I guess that won't play well with XML configuration. If the number of constructors gets to be too many, perhaps we should consider a builder pattern. Feel free to send over the pull request and we can continue review on that. Thank you for bringing this to our attention and offering to contribute a solution @IgorPerikov

**Comment by IgorPerikov** [comment]
Cool, will start work on that soon, then

> Delegation instead of extension seems like it would avoid potential explosion of constructors needed, but I guess that won't play well with XML configuration.

It would not play well also because there are too many methods in QueuedThreadPool that need to be implemented (via simple delegation). Constructors won't bloat the code that much
