### ISSUE TITLE
non-cumulative histogram

### ISSUE THREAD

**Issue by dtanner** [micrometer-metrics/micrometer#1640]
I'm new to histograms, and my use case is to create a response time heatmap with non-cumulative counts in each bucket range.  I'm using the InfluxMeterRegistry but not sure that matters for this question.

Is there a way to do this in micrometer today?  I think what I want is a non-cumulative distribution summary / histogram.   If that's not built yet, what are your thoughts on adding the feature?  I don't know how fixed the concept of cumulation is in the existing interfaces and implementations.  Thanks.

**Comment by checketts** [comment]
You can create your own histogram equivalent using counters. Then if you were using a step-based registry (which resets everytime it publishes) it would reset the count in a non-cumulative fashion. 

I haven't used the built in histogram much, so I don't have a good answer for it though.

**Comment by tom-mi** [comment]
That would also be nice to have for Datadog, as there seems to be no proper way to graph a cumulative histogram in Datadog.

**Comment by jkschneider** [comment]
@tom-mi Just to clarify, there are kind of two forms of "cumulative" possible for histograms:

1. Bucket counts are cumulative over time
2. Bucket counts are cumulative from one bucket to the next. 

An illustration of the second point is this:

![image](https://user-images.githubusercontent.com/1697736/81132849-c8912380-8f1d-11ea-887e-cc83c43ef92c.png)

Which one are you wanting?

**Comment by tom-mi** [comment]
@jkschneider I'm referring to the second one.
