### ISSUE TITLE
gague-Dynamic registration of multiple metrics error

### ISSUE THREAD

**Issue by pangxljc** [micrometer-metrics/micrometer#1649]
problem:I hope to generate Gauge by passing parameters.For example(name,tags,description...),The effect I hope to achieve is to provide a common unified interface for dynamic registration of gauge metrics.
The problem I am having is that after I call the doRegister method with a different PromMetricsEntity Object, I find that the two metrics registered affect each other and change synchronously. I want every gauge metrics to manage its own values separately. I have read the relevant documentation, but still have not solved my doubts. Is my use the wrong way? Do you have any good suggestions?

The following is my code case and implementation effect (emmn... although I don't want to achieve this effect)

```
@Component
public class GaugeMetricsSampler extends PrometheusMetricsSampler {
@Autowired
    private PrometheusMeterRegistry registry;
    private Gauge searchGauge;
    private AtomicInteger atomicInteger = new AtomicInteger();
    public GaugeMetricsSampler(){ }

    @Override
    public void doRegister(PromMetricsEntity promMetricsEntity) throws Exception {
        doInit(promMetricsEntity);
        if (StringUtils.isNotEmpty(getMetricsName())) {
            if (getMetricsTags() != null && 0 != getMetricsTags().length) {
                Gauge.builder(getMetricsName(),atomicInteger,AtomicInteger::get)
                        .tags(getMetricsTags())
                        .description(getMetricsDescription())
                        .register(getRegistry());
            } else {
                Gauge.builder(getMetricsName(),atomicInteger,AtomicInteger::get)
                        .description(getMetricsDescription())
                        .register(getRegistry());
            }
            operate();
        }
    }

private void operate() {
        atomicInteger.addAndGet((int) getMetricsRegisterNum());
    }
}
```

【Code running result】
```
# HELP test1 lalalalalalalad
# TYPE test1 gauge
test1{product="testpro",source="web",} 25.0
# HELP test2 lalalalalalalad
# TYPE test2 gauge
test2{product="testpro",source="web",} 25.0
```

test1 and test2 are two different gauge metrics, but when I pass in 'name=test1', I not only changed the value of test1 metrics, but also changed the value of test2, which made me very annoyed.

**Comment by checketts** [comment]
Your problem is that they are both sharing the same underlying `AtomicInteger`. You need to create a map of `AtomicInteger`s and have each gauge reference its specific one.

**Comment by pangxljc** [comment]
> Your problem is that they are both sharing the same underlying `AtomicInteger`. You need to create a map of `AtomicInteger`s and have each gauge reference its specific one.

As of now, I have not thought of an elegant solution to this problem.
How to make each gauge use a different AtomicInteger?
I'm sorry to bother you
