### ISSUE TITLE
Multiple `http_server_requests_duration_seconds_count` for /prometheus endpoint

### ISSUE THREAD

**Issue by eivinhb** [micrometer-metrics/micrometer#165]
Running SpringBoot 2 M5 with `micrometer-registry-prometheus 1.0.0-rc.2` the prometheus metrics report multiple metrics for MCV endpoints to prometheus. The problem is that prometheus seems some what arbitrary to which metric it actually indexes, so it doesn't always read the correct value.

Example dump from /prometheus
```
http_server_requests_duration_seconds_count{exception="None",method="GET",status="200",uri="/api/soknad/{id}/info",} 2362.0
http_server_requests_duration_seconds_count{exception="None",method="GET",status="200",uri="/api/soknad/{id}/info",} 0.0
http_server_requests_duration_seconds_count{exception="None",method="GET",status="200",uri="/api/soknad/{id}/info",} 0.0
http_server_requests_duration_seconds_count{exception="None",method="GET",status="200",uri="/api/soknad/{id}/info",} 0.0
http_server_requests_duration_seconds_count{exception="None",method="GET",status="200",uri="/api/soknad/{id}/info",} 0.0
```

If I debug, I can see that `PrometheusScrapeEndpoint` (running SimpleClient 0.0.26) has mulitiple values in its collectorRegistry. But I am not sure whether this is a Micrometer, Prometheus or Spring boot issue.

Let me know if I should report this elsewhere, and I will.

**Comment by jkschneider** [comment]
New meter creation wasn't properly synchronized in `MeterRegistry`. So this happened when multiple threads hit the same new metric at around the same time.

**Comment by jkschneider** [comment]
Originally regressed in #134
