### ISSUE TITLE
Getting datapoint timestemp error after integrating with dynatrace monitoring system

### ISSUE THREAD

**Issue by Sandesh-Jayaprakash** [micrometer-metrics/micrometer#1656]
I am using spring boot **2.0.2.RELEASE** and micro meter **1.1.3**  
After adding     
compile(group: 'io.micrometer', name: 'micrometer-registry-dynatrace', version: '1.1.3') i thought spring boot will autoconfigure .But it was configuring simple meter registry. 

So i manually created DynatraceMeterRegistry bean now application is publishing metrics  and getting an error,

**i.m.dynatrace.DynatraceMeterRegistry     : failed to send metrics to dynatrace: {"error":{"code":400,"message":"Constraints violated.","constraintViolations":[{"path":"series[0].datapoints[0]","message":"Data point timestamp is lower than creation timestamp of the timeseries configuration.Creation timestamp is: 1571683714497","parameterLocation":"PAYLOAD_BODY","location":null}]}}**

Here is the code snippet,

`@Configuration
public class DyntraceCustomConfig {

    @Autowired
    private DynatraceConfig config;
	

    @Bean
    public MeterRegistry meterRegistry() throws Exception {
        return new DynatraceMeterRegistry(config, new Clock() {
            @Override
            public long wallTime() {
                return 0;
            }

            @Override
            public long monotonicTime() {
                return 0;
            }
        });
    }

    @Bean
    public DynatraceConfig dynatraceConfig() throws Exception {
        return new DynatraceConfig() {
            public String apiToken() {
                return "some_token"; // using valid token
            }

            @Override
            public String uri() {
                return "url";// using valid url 
            }

            @Override
            public String deviceId() {
                return "custom";
            }

            @Override
            @Nullable
            public String get(String k) {
                return null;
            }
        };
    }

}
`

Am doing the right way?

**Comment by checketts** [comment]
I'm not familiar with Dynatrace myself, but the `wallTime` and `monotonicTime` hard coded to `0` seem suspicious.

**Comment by Sandesh-Jayaprakash** [comment]
This issue got fixed after changing the code ,
    @Bean
    public MeterRegistry meterRegistry() throws Exception {
        return new DynatraceMeterRegistry(config, Clock.SYSTEM); // Clock.SYSTEM did the work
    }

**Comment by izeye** [comment]
> I am using spring boot **2.0.2.RELEASE** and micro meter **1.1.3**  
> After adding     
> compile(group: 'io.micrometer', name: 'micrometer-registry-dynatrace', version: '1.1.3') i thought spring boot will autoconfigure .But it was configuring simple meter registry.

@Sandesh-Jayaprakash [Auto-configuration for Dynatrace has been added since Spring Boot 2.1.0](https://github.com/spring-projects/spring-boot/blob/d254c6271253c57383e351998ffdd97b2d385c99/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/export/dynatrace/DynatraceMetricsExportAutoConfiguration.java#L43).

> So i manually created DynatraceMeterRegistry bean now application is publishing metrics  and getting an error,

You was using a broken `Clock` implementation as @checketts pointed out and you also figured out. For consistency, you'd better to use the auto-configured `Clock` like [this](https://github.com/izeye/sample-micrometer-spring-boot/blob/15dacdf2a6e0ba89448cb9fe8b78b9a87e8f1fe6/src/main/java/com/izeye/sample/config/MetricsConfig.java#L56).
