### ISSUE TITLE
Provide additional metrics in ExecutorServiceMetrics

### ISSUE THREAD

**Issue by skabashnyuk** [micrometer-metrics/micrometer#1665]
It would be nice if we code provides some additional metrics related to ThreadFactory and RejectedExecutionHandler. It could be:
For ThreadFactory
-  **thread.factory.created** - "The approximate number of threads that create with thread factory"
- **thread.factory.terminated** - "The approximate number of threads that is finished execution"
- **thread.factory.running** -  "The approximate number of threads that are started executing, but not terminated"

For RejectedExecutionHandler
- **executor.rejected** - "The number of tasks that were not accepted for execution"

I thought about this place https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java#L178, where we can wrap and inject ThreadFactory and RejectedExecutionHandler into user's ThreadPoolExecutor.

**Comment by skabashnyuk** [comment]
Possible implementation
https://github.com/eclipse/che/blob/observability/core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/CountedThreadFactory.java

https://github.com/eclipse/che/blob/observability/core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/CountedRejectedExecutionHandler.java

**Comment by asarkar** [comment]
It'll also be very useful to have the thread pool core size and max size as shown below.
```
Gauge.builder("executor.corePool.size", tpe, ThreadPoolExecutor::getCorePoolSize)
  .tags(tags)
  .description("The core number of threads in the pool")
  .baseUnit("threads")
  .register(registry);

Gauge.builder("executor.maxPool.size", tpe, ThreadPoolExecutor::getMaximumPoolSize)
  .tags(tags)
  .description("The maximum number of threads in the pool")
  .baseUnit("threads")
  .register(registry);
```

**Comment by shakuzen** [comment]
@skabashnyuk Thanks for the request and references. Sorry for the delay in getting to this. The links to the possible implementation unfortunately give a 404 error now.

I was looking into this, but I think I need some clarification on the request.

Currently we have a counter `executor.completed` which seems to be equivalent to the requested `thread.factory.terminated`.
https://github.com/micrometer-metrics/micrometer/blob/fc8cec7afe7c57795b1367ae5087571f0d7a4cf2/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java#L291-L295

We also have a gauge `executor.active` that seems to be equivalent to the requested `thread.factory.running`
https://github.com/micrometer-metrics/micrometer/blob/fc8cec7afe7c57795b1367ae5087571f0d7a4cf2/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java#L297-L301

I don't see a current equivalent for the requested `thread.factory.created` but I'm wondering what's the motivation behind this.

Given the above, do we need any new metrics for those? Let me know what you think.

I can see the usefulness in a counter for the rejected tasks. Indeed a `RejectedExecutionHandler` seems the best route to go.

**Comment by skabashnyuk** [comment]
@shakuzen this is a correct link to the code

- https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/CountedThreadFactory.java
- https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-observability/src/test/java/org/eclipse/che/commons/observability/CountedThreadFactoryTest.java
- https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-observability/src/main/java/org/eclipse/che/commons/observability/CountedRejectedExecutionHandler.java
- https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-observability/src/test/java/org/eclipse/che/commons/observability/CountedRejectedExecutionHandlerTest.java

>Currently we have a counter executor.completed which seems to be equivalent to the requested thread.factory.terminated.

I think they aren't equivalent. Because `executor.*` - it's about tasks and `thread.factory` - about threads. 

>We also have a gauge executor.active that seems to be equivalent to the requested thread.factory.running

Not sure about use cases, however, I think that might be situation when the thread is running but not active, depends on ThreadExecutor. I believe dedicated `CountedThreadFactory` might be useful if users want to concentrate only on threads and when they use only `ThreadFactory` but not executors.

**Comment by skabashnyuk** [comment]
@shakuzen wdyt about my last comment https://github.com/micrometer-metrics/micrometer/issues/1665#issuecomment-621156418 does it make sense for you?
