### ISSUE TITLE
StringCache statistic is not available

### ISSUE THREAD

**Issue by skabashnyuk** [micrometer-metrics/micrometer#1666]
I was not able to see values that have to be provided by this part of the code
https://github.com/micrometer-metrics/micrometer/blob/b280f32c0f5d9989a5c56e87426b36dce53d0b1b/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java#L153-L165

I assume the reason for that is that there is no name in the object 
<img width="1203" alt="Знімок екрана  о 12 15 55" src="https://user-images.githubusercontent.com/1614429/67563702-85a9f400-f721-11e9-8fd0-899833e60124.png">
and this code is looking something with name
https://github.com/micrometer-metrics/micrometer/blob/b280f32c0f5d9989a5c56e87426b36dce53d0b1b/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java#L226

**Comment by izeye** [comment]
@skabashnyuk Thanks for the report! Your analysis seems to be correct. I created https://github.com/micrometer-metrics/micrometer/pull/1689 to try to resolve this.

**Comment by skabashnyuk** [comment]
Can this fix be ported to 1.3.x?

**Comment by shakuzen** [comment]
Thank you for the report and analysis @skabashnyuk. This should be fixed in the latest snapshots (in a couple minutes from now) thanks to @izeye's pull request.

> Can this fix be ported to 1.3.x?

Yes, it will be merged forward into 1.3.x and will be in the next patch release.
