### ISSUE TITLE
Lower down okhtttp requirements

### ISSUE THREAD

**Issue by skabashnyuk** [micrometer-metrics/micrometer#1667]
Question:
would it be possible to lower down the required version of okhtttp from 3.12 to 3.9? For me, it's also related https://github.com/fabric8io/kubernetes-client version that is kind of problematic to upgrade.
This code https://github.com/micrometer-metrics/micrometer/blob/b280f32c0f5d9989a5c56e87426b36dce53d0b1b/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java#L102 was introduced in 3.12 only.

**Comment by izeye** [comment]
@skabashnyuk Thanks for raising an issue!

`Request.tag(Class)` has been added in [`okhttp` 3.11.0](https://square.github.io/okhttp/changelog_3x/#version-3110), and Micrometer branches are compiled with the following `okhttp` versions:

- Micrometer 1.0.x (EOL): `okhttp` 3.9.1
- Micrometer 1.1.x: `okhttp` 3.11.0
- Micrometer 1.3.x: `okhttp` 3.14.4

I created #1673 to try to resolve this. We might need to add the minimum version (3.11.0) for `okhttp` in its Javadoc when removing the reflection.
