### ISSUE TITLE
Using @Timed wrapped in a custom annotation.

### ISSUE THREAD

**Issue by Santhosh7792** [micrometer-metrics/micrometer#1677]
```java
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Timed
Public @interface MyCustomAnnotation{
@AliasFor(annotation = Timed.class , attribute = "value")
String value();
}
```

I have used `@MyCustomAnnotation` on the methods that need to measure the time taken by the method.

The `@Timed` annotation present inside the custom annotation is not getting invoked.

Any clues or suggestions would be extremely helpful.

**Comment by marcingrzejszczak** [comment]
Is it still a problem with the latest versions?
