### ISSUE TITLE
Initialize `jvm.gc.max.data.size` to correct value before any GC events

### ISSUE THREAD

**Issue by danieljamesscott** [micrometer-metrics/micrometer#1678]
We are using `jvm.gc.max.data.size` as part of a calculation to trigger an alarm when the heap used by the JVM increases above a threshold. The initial value of the ``jvm.gc.max.data.size` metric is 0:

https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java#L93

This causes a problem during startup, because we get a NaN (divide by zero) until a GC has run. Is it possible to set this to the correct value immediately? Without having to wait for a GC?

**Comment by shakuzen** [comment]
> as part of a calculation to trigger an alarm when the heap used by the JVM increases above a threshold.

Could you not use the `jvm.memory.max` metric instead, filtering by the tag for the old gen memory pool?

**Comment by danieljamesscott** [comment]
Yes, it's possible to do that. However, we don't send that metric by default. We'd have to add `JvmMemoryMetrics` (Which adds a fair bit of cost, in CloudWatch). It would be cleaner for us to use only the GC metrics.

**Comment by checketts** [comment]
> Which adds a fair bit of cost, in CloudWatch

How does it add cost? By adding additional metrics that you don't want CloudWatch to charge for? The solution in that case would be to add `JvmMemoryMetrics` and add a `MeterFilter` that mutes all the metrics you don't want CloudWatch to track. That will give you more flexibility in the long run too without worrying about swamping CloudWatch and causing surprise expenses.

**Comment by danieljamesscott** [comment]
Yes, by sending additional CW metrics which we don't (necessarily) want. Yes, we could filter out the metrics we don't want, but we've already got a very complicated setup with filters and registries sending to different destinations. I think that initialising the value to 0 is incorrect and so it is best if we fix it (I can submit a PR? If so, then please let me know if anyone has any opinions on the approach).

**Comment by shakuzen** [comment]
Resolved by 8b2893e and #1695
