### ISSUE TITLE
Fix flakiness of TomcatMetricsTest#mbeansAvailableAfterBinder

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1687]
See this failed build for instance: https://circleci.com/gh/micrometer-metrics/micrometer/4726

This is the assertion that is failing:
https://github.com/micrometer-metrics/micrometer/blob/9019656579f2b253a1fc3f060ff3f0e497c497ba/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetricsTest.java#L217

I think this is happening because the assertion is in a race with Tomcat completely finishing serving the request made from the HttpClient.

**Comment by izeye** [comment]
@shakuzen I created https://github.com/micrometer-metrics/micrometer/pull/1688 to try to resolve this.
