### ISSUE TITLE
Micrometer expose process_starttime_seconds in nanoseconds instead of seconds

### ISSUE THREAD

**Issue by danielmenezesbr** [micrometer-metrics/micrometer#169]
**Issue**
`Micrometer` expose process_starttime_seconds in `nanoseconds` instead of `seconds`

**Steps to reproduce**
When I access prometheus endpoint starttime is:

`# HELP process_starttime_seconds The starttime of the Java virtual machine`
`# TYPE process_starttime_seconds gauge`
process_starttime_seconds 1.508362615301**E9**

Notice that value is in scientific notation (E9). When it value saved into backend, the value will be 1508362615.301 seconds.

**Affected versions**
v1.0.0-rc.2

**Comment by danielmenezesbr** [comment]
Prometheus client java for reference: https://github.com/prometheus/client_java/blob/ce76a494acd4f4077f01b6cea40e4329b0d54fac/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java#L72

**Comment by mweirauch** [comment]
The `UptimeMetrics` register the Management Beans provided value with the correct TimeUnit (milliseconds) into micrometers `MeterRegistry`. For the Prometheus integration the value is scaled to seconds.
What is wrong with `1508362615` seconds and `301` milliseconds?
http://www.convert-unix-time.com/?t=1508362615

**Comment by jkschneider** [comment]
Agree with @mweirauch. It seems to be reporting the correct value. Prometheus' `StandardExport` also scales this value to seconds.

**Comment by danielmenezesbr** [comment]
Excuse me for my confusion.

When I looked at the @boeboe dashboard[1], I thought that start time had another meaning. However, the meaning was clear with @mweirauch explanation.

The value of the metric is correct. Apparently there is a problem in dashboard presentation (the dashboard should format the start time value as http://www.convert-unix-time.com/?t=1508362615), but that's another story.

[1] https://grafana.com/api/dashboards/3308/images/2093/image

**Comment by mweirauch** [comment]
Btw, Grafana 4.6.0 will provide a means of showing dates based on timestamps (ms). (Automatically adding the date when crossing the day boundary.)

![bildschirmfoto vom 2017-10-24 19-24-59](https://user-images.githubusercontent.com/1134031/31958134-1834b11e-b8f1-11e7-99e0-da443d3d2799.png)

**Comment by danielmenezesbr** [comment]
Grafana 4.6.0 was released:
https://github.com/grafana/grafana/releases/tag/v4.6.0

**Comment by danielmenezesbr** [comment]
@mweirauch How did you set up your grafana dashboard to show "start time"?

When I tried to configure, my dashboard displays a date of 1970.

My timestamp is 1508424790.

Convert-unix-time show it (http://www.convert-unix-time.com/?t=1508424790):
![image](https://user-images.githubusercontent.com/5949657/32242216-5645d0b0-be59-11e7-8b62-fbba7495d272.png)

My dashboard configuration (metric):
![image](https://user-images.githubusercontent.com/5949657/32242314-9284f5d8-be59-11e7-8a2e-57a2e4917853.png)

My dashboard configuration (option):
![image](https://user-images.githubusercontent.com/5949657/32242457-fdb42248-be59-11e7-8552-f79470873814.png)

I'm using grafana 4.6.0-stable.

**Comment by boeboe** [comment]
@danielmenezesbr 

You need to convert to milliseconds:

`process_start_time_seconds * 1000`

**Comment by boeboe** [comment]
@danielmenezesbr I have updated the dashboard available on grafana.com to reflect the new changes based on Grafana 4.6.0.

**Comment by danielmenezesbr** [comment]
@boeboe Thanks!
