### ISSUE TITLE
Calling the /prometheus interface under large data volume to get the indicator data will be stuck.

### ISSUE THREAD

**Issue by pangxljc** [micrometer-metrics/micrometer#1692]
We are a search interface that accesses the prometheus service. When we find that the prometheus interface is used to obtain the indicator data in the way of large data volume on the online environment, there will be 1s or so of the card, which will cause us all during this time. The search request timed out.

We only go to the search interface response to go to the custom indicator registration

When calling prometheus to get indicator data, will the main thread hang?

**Comment by checketts** [comment]
> When calling Prometheus to get indicator data, will the main thread hang?

It sounds like you are using a gauge to get the 'indicator data'. Is that correct? So, yes, gauges are called in the same thread as the Prometheus collection. All gauge calls need to be very fast (ALL gauges completing in 100ms is a good rule of thumb).

Here is an example where I iterate on `HealthIndicators` to make the expensive/slow calls periodically on a separate thread so the metric collection is fast: https://github.com/checketts/micrometer-springone-2019/blob/master/src/main/kotlin/com/github/checketts/micrometerspringone2019/HealthIndicatorBinder.kt  You could modify that to suit your slow gauge calls.

**Comment by pangxljc** [comment]
> > 调用Prometheus以获得指标数据时，主线程是否会挂起？
> 
> 听起来您正在使用量规来获取“指标数据”。那是对的吗？因此，是的，在与Prometheus集合相同的线程中调用了仪表。所有仪表的调用都必须非常快（在100ms内完成所有仪表是一个很好的经验法则）。
> 
> 这是一个示例，我反复在`HealthIndicators`一个单独的线程上进行周期性的昂贵/慢速调用，因此度量标准收集很快：[https](https://github.com/checketts/micrometer-springone-2019/blob/master/src/main/kotlin/com/github/checketts/micrometerspringone2019/HealthIndicatorBinder.kt)：[//github.com/checketts/micrometer-springone-2019/blob/master/src/main /kotlin/com/github/checketts/micrometerspringone2019/HealthIndicatorBinder.kt](https://github.com/checketts/micrometer-springone-2019/blob/master/src/main/kotlin/com/github/checketts/micrometerspringone2019/HealthIndicatorBinder.kt) 您可以对其进行修改以适合您的慢速调用。

We currently only use Counter and Summary. We have 4000+ normal threads for each single machine. Each thread will write about 7 indicator data during processing. The qps per second is about 150, and there is no problem in writing the indicator data to the normal thread.
We found that once the prometheus interface exposed by the actuator is called, it will cause some of the main threads to get stuck, which will cause our normal thread to time out. Therefore, is the reading of indicator data and write indicators mutually exclusive under large data volume? Does reading and writing have the existence of a lock? I looked at it as if there was no lock. Has this been verified by a large amount of data?

**Comment by shakuzen** [comment]
@pangxljc How is your Prometheus endpoint created?

**Comment by pangxljc** [comment]
> @pangxljc How is your Prometheus endpoint created?

Our custom metrics (a combination of name and tags) has 10000+, so we want to parse the search request to dynamically add the metrics name and tags. But we don't want to maintain 10000+ instances locally.
We see code and comments. If you pass the same name and tags when register, it will return an existing Meter (existing Meter). So every time we write the indicator, we will perform the register operation, get the returned instance, and then go to the indicator operation.
I use it like this.

```
@Component
public class CounterMetricsSampler{
    @Autowired
    private PrometheusMeterRegistry registry;
    private Counter searchCounter;

    public statis void doRegister(PromMetricsEntity promMetricsEntity) {
        if (StringUtils.isNotEmpty(promMetricsEntity.getMetricsName())) {
            searchCounter = Counter.builder(promMetricsEntity.getMetricsName())
                        .tags(promMetricsEntity.getMetricsTags())
                        .description(promMetricsEntity.getMetricsDescription())
                        .register(registry);
            incr(promMetricsEntity.getMetricsRegisterNum());
        }
    }
    
    public void incr(double num) {
        searchCounter.increment(num);
    }
}

@Controller
@RequestMapping(path = "/api/metrics")
public class metricsController{

     @RequestMapping(path = "hah")
     public @ResponseBody Object searchMetrics(HttpServletRequest request,
                              @RequestParam(name = "name", defaultValue = "") String name,
                              @RequestParam(name = "tags", defaultValue = "") HashMap tags,
                              @RequestParam(name = "num", defaultValue = "") double num,) {

                PromMetricsEntity promMetrics = new PromMetricsEntity();
                promMetrics.setName(name);
                promMetrics.setTags(tags);
                promMetrics.setRegisterNum(num);
                promMetrics.setDescription("This is a counter metrics");
                CounterMetricsSampler.doRegister(promMetrics);
                return promMetrics;
}
```

Of course, this is just a simplification of the code, we have done a lot of other processing, but the core idea is this. We can't register our metrics when the program starts, because that's too much.

Looking forward to your reply

**Comment by marcingrzejszczak** [comment]
Is this still a problem with the latest versions?
