### ISSUE TITLE
No metric to indicate a FORCED Open Hystrix circuit breaker

### ISSUE THREAD

**Issue by tzehuai** [micrometer-metrics/micrometer#1694]
The metric to indicate open circuit breakers, `hystrix.circuit.breaker.open` does not pick up a **forced** open circuit when setting `hystrix.command.HystrixCommandKey.circuitBreaker.forceOpen` to `true`. The number of short-circuited events (hystrix.execution.total{event="short_circuited"}) increases but `hystrix.circuit.breaker.open` still remain 0.

Or is there an alternative way to obtain the forced open circuit breaker state?

Thanks!

**Comment by shakuzen** [comment]
The `hystrix.circuit.breaker.open` gauge is using the `isOpen` method of the `HystrixCircuitBreaker` class.

https://github.com/micrometer-metrics/micrometer/blob/c43733ff36d7fa19f5eabb908053d969d6515249/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherCommand.java#L71

Looking at the implementation, it looks like it should be considering forced open circuits.

https://github.com/Netflix/Hystrix/blob/3cb21589895e9f8f87cfcdbc9d96d9f63d48b848/hystrix-core/src/main/java/com/netflix/hystrix/HystrixCircuitBreaker.java#L226-L235

Perhaps @checketts has more insight on this.

**Comment by tzehuai** [comment]
Hi @shakuzen @checketts, thanks a lot for your responses. 

I tried to force open hystrix circuits with `hystrix.command.default.circuitBreaker.forceOpen=true`, and this is what I am getting from Prometheus:

![image](https://user-images.githubusercontent.com/57402993/69121686-e84f9f00-0ad7-11ea-9278-84f9302428ca.png)

The top graph is plotting `hystrix_circuit_breaker_open` and the bottom graph is the total short circuited events. Notice that the open circuit breaker metric stays at 0 even when number of short-circuited events are increasing.

**Comment by shakuzen** [comment]
I previously linked the latest code from the `master` branch of Hystrix. However, that is not the latest released version of the code. This is:

https://github.com/Netflix/Hystrix/blob/809104c8751be0065a8269df3677965f3092e6b9/hystrix-core/src/main/java/com/netflix/hystrix/HystrixCircuitBreaker.java#L180-L211

It looks like the above implementation does not consider when the command is force closed. I am not sure what we can do without changes in Hystrix. If we had access to the `HystrixCommand` itself, the `isCircuitBreakerOpen` method seems to return what is expected.

**Comment by marcingrzejszczak** [comment]
Since Hystrix is a deprecated project, shouldn't we deprecate and schedule Hystrix support for removal?
