### ISSUE TITLE
Support Hazelcast 4

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1697]
The [Hazelcast 4 BETA-1 has been released](https://hazelcast.com/blog/hazelcast-imdg-4-0-beta/), and our current support fails to even compile against it. See #1696. We will need to consider how to best support Hazelcast 3/4 going forward.

**Comment by mesutcelik** [comment]
Hi @shakuzen , 
Hazelcast 3.12.x will be actively maintained for some period of time so feel free to keep it in your current minor release. You can upgrade to Hazelcast 4 in your next minor release(1.4) with a release notes entry pointing to [Migration Points](https://docs.hazelcast.org/docs/latest/manual/html-single/#upgrading-to-4-0-from-prior-versions-3-x)

Hazelcast 4 upgrade PR has already been sent so feel free to review it.
https://github.com/micrometer-metrics/micrometer/pull/1868

**Comment by shakuzen** [comment]
I've marked this for the 1.5 milestone so we can hopefully figure out what the best solution is for this by then. I'm afraid we've run out of time to include this in the 1.4 release, but since it looks like we have some help on this, we will hopefully get it sorted for 1.5 soon.

**Comment by leszko** [comment]
Hi @checketts @shakuzen,

We provided two solutions for this issue: #1868 and #1952, could you please check and give your thoughts?
