### ISSUE TITLE
process_starttime_seconds (Prometheus metric name)

### ISSUE THREAD

**Issue by danielmenezesbr** [micrometer-metrics/micrometer#170]
According to [Prometheus documentation](https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics), the metric name to collect process start time is `process_start_time_seconds`. Micrometer exposes it metric with the name `process_starttime_seconds`.

**Comment by danielmenezesbr** [comment]
Prometheus client java for reference: https://github.com/prometheus/client_java/blob/ce76a494acd4f4077f01b6cea40e4329b0d54fac/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java#L72

**Comment by mweirauch** [comment]
I knew this would crop up some day or the other. The motivation was to have a "one-word"-thingy as with "uptime".
In some sense, the micrometer Prometheus integration is a client implementation, on the other hand micrometer itself is a system on it's own exposing metric names as it sees fit for itself. The Prometheus integration is just one of the many integrations for the supported metric backends.
So changing the name just to fit Prometheus' client recommendations will change the metric name for any other backend integration mircometer supports.
Personally I am unbiased on the one or the other naming. "start_time" is likely the better english.

**Comment by jkschneider** [comment]
Few should be reliant on the Micrometer name yet, and `process.start.time` is reasonable in the naming convention independent form. So I'd support changing it to follow the existing name Prom users are accustomed to.

@mweirauch correctly points out that we aren't bound to follow Prometheus names for particular pieces of instrumentation where they don't make sense generally, but I don't think this is one of those cases.
