### ISSUE TITLE
LoggingMeterRegistry logs throughput, but this is not exported to influxdb

### ISSUE THREAD

**Issue by celiovasconcelos** [micrometer-metrics/micrometer#1703]
```
LoggingMeterRegistry     : http.server.requests{exception=None,method=GET,outcome=SUCCESS,status=200,uri=/public/teste} throughput=0.05/s mean=0.010075761s max=2.274716358s
```
In the influxdb I only see *count*, *sum*, *mean* and *upper* in the **http.server.requests*.* (metric type histogram)

* micrometer-registry-influx version 1.1.7
* spring-boot version 2.1.9.RELEASE

This is not smart to calculate rate server-side based on reporting interval.

So, the question is:

Is there a possibility to export client-side rate-aggregated (like requests per second) metrics to influxdb?

Thank you.

**Comment by checketts** [comment]
I'm not familiar with influxdb, but the `LoggingMeterRegistry` is a `StepMeterRegistry` so that is why it has those rate type based metrics. 

Promtheus uses those counts to be able to calculate rates dynamically. I would assume that influxdb can as well.

**Comment by jkschneider** [comment]
@celiovasconcelos In InfluxDB, `count` is the measure of throughput, and it's already shipped as a rate.
