### ISSUE TITLE
Add Jetty connector metrics

### ISSUE THREAD

**Issue by tomakehurst** [micrometer-metrics/micrometer#1704]
It's often useful to see how Jetty's connectors are performing, in terms of connection counts and inbound/outbound traffic throughput.

So I'd like to propose adding a meter binder for these metrics. I'm happy to contribute a PR for this (I have some tested code already available).

**Comment by checketts** [comment]
Sounds like a good idea. Are you able to gather these metrics via the JMX Beans or is there a better mechanism?

**Comment by tomakehurst** [comment]
Anyway, I'll put a PR your way shortly if you're happy with that.

**Comment by shakuzen** [comment]
> Anyway, I'll put a PR your way shortly if you're happy with that.

Yes please. Thank you.

**Comment by tomakehurst** [comment]
https://github.com/micrometer-metrics/micrometer/pull/1715 - ready to roll now that the Tomcat test fix is merged.

**Comment by jkschneider** [comment]
Resolved with #1715
