### ISSUE TITLE
Add TimeGauge example to documentation

### ISSUE THREAD

**Issue by zeelshah90** [micrometer-metrics/micrometer#1705]
I am trying to use timeGauge to send time in milliseconds to datadog:

`AtomicDouble avgProcessingTimeValue = new AtomicDouble(0);
avgProcessingTimeValue.set(averageProcessingTime); `

`TimeGauge g = meterRegistry.more().timeGauge("test.processing.avg.time", Collections.emptyList(), atomicDouble,TimeUnit.MILLISECONDS, AtomicDouble::get);`

But this will not add unit to datadog dashboard it will still be as Mega/Giga/Tera. So looks like there is some problem here.

**Comment by checketts** [comment]
I'm not too familiar with the `timeGauge`, but I have used the `timer`. Do you have the totals that were used to calculate the average?

**Comment by zeelshah90** [comment]
```
    // Metric to calculate max and average processing time per batch
    private void calculateProcessingTime() {
        final long endTime = System.currentTimeMillis();

        long maxProcessingTime = 0;
        long sumOfProcessingTime = 0;
        int keyCounter = 0;

        // get init time for each key
        for(K key: keysToFlush.keySet()){
            try {
                // get initTime from key context
                long initTime = stateStore.getInitTime(key);

                // calculate individual key processing time
                long currentProcessingTime = endTime - initTime;

                log.info("CURRENT-PROCESSING-TIME: " + currentProcessingTime);

                sumOfProcessingTime += currentProcessingTime;
                maxProcessingTime = Math.max(maxProcessingTime, currentProcessingTime);
                keyCounter++;

            } catch(Exception e) {
                log.error("could not fetch initTime for key - " + key.toString() + " , exception - " +
                        ExceptionUtils.getStackTrace(e));
            }
        }

        if(keyCounter != 0) {
            final double averageProcessingTime = sumOfProcessingTime/keyCounter;
//            AtomicDouble atomicDouble =meterRegistry.gauge(METER_NAME.concat(".average.processing.time.per.key"), avgProcessingTimeValue);
//            atomicDouble.set(averageProcessingTime);
            avgProcessingTimeValue.set(averageProcessingTime);
            TimeGauge g = meterRegistry.more().timeGauge("test.processing.avg.time", Collections.emptyList(), avgProcessingTimeValue,TimeUnit.MILLISECONDS, AtomicDouble::get);

        }

        AtomicLong atomicLong = meterRegistry.gauge(METER_NAME.concat(".max.processing.time.per.key"), maxProcessingTimeValue);
        atomicLong.set(maxProcessingTime);
    }
```

This is the whole method essentially i get init time for a given key from the state store and subtract it from currentMillis to get the processing time and then find avg and max for the given keys. Not sure if this is what you were asking?

**Comment by checketts** [comment]
This can just be simplified into recording the measurements in a timer:

```
    // Metric to calculate max and average processing time per batch
    private void calculateProcessingTime() {
        final long endTime = System.currentTimeMillis();

        // get init time for each key
        for(K key: keysToFlush.keySet()){
            try {
                // get initTime from key context
                long initTime = stateStore.getInitTime(key);
                meterRegistry.timer("test.processing.avg.time").record(endTime - initTime)
            } catch(Exception e) {
                log.error("could not fetch initTime for key - " + key.toString() + " , exception - " +
                        ExceptionUtils.getStackTrace(e));
            }
        }
    }
```

A `timer` tracks both the total duration and total counts (which can be used to create an average easily). It also include a MAX based on a rolling window (1 minute by default)

**Comment by zeelshah90** [comment]
Ok i tried the following:

`meterRegistry.timer("test.processing.avg.time").record(currentProcessingTime, TimeUnit.SECONDS);`

But still shows as M/G/T no unit for time. I wonder if there is some config in the dashboard itself which i cannot find.

**Comment by checketts** [comment]
Sorry I don't have any DataDog experience to be able to help with that. Good luck! Please report your success to help others.

**Comment by zeelshah90** [comment]
thanks for the help but yea if i get it to work i will surely put that here.

**Comment by izeye** [comment]
> But still shows as M/G/T no unit for time. I wonder if there is some config in the dashboard itself which i cannot find.

@zeelshah90 I'm not a Datadog user, but it seems to work for me with [a sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/datadog):

<img width="841" alt="Screen Shot 2019-12-09 at 1 10 58 PM" src="https://user-images.githubusercontent.com/1059363/70406948-c49fc900-1a85-11ea-9865-a732d2959db8.png">
