### ISSUE TITLE
Thread metrics should be whole numbers, not decimals

### ISSUE THREAD

**Issue by asarkar** [micrometer-metrics/micrometer#1706]
[ExecutorServiceMetrics](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java) creates gauges with double values causing merics like pool size and number of tasks being exported as a double. This doesn't make sense and creates problems with averages over time.

**Comment by checketts** [comment]
All metrics are doubles. See https://stackoverflow.com/questions/58068832/why-is-a-counter-a-double-and-not-a-long

Feel free to add specific details of your usecase, and specifics for your averages problem overtime. Are you referring to potential loss of precision?

**Comment by asarkar** [comment]
Perhaps the following screenshot from Grafana would make the problem clearer.
![Screen Shot 2019-11-15 at 4 49 12 PM](https://user-images.githubusercontent.com/1302775/68984990-3ad34780-07c8-11ea-8ef1-cc268391d239.png)

**Comment by checketts** [comment]
![image](https://user-images.githubusercontent.com/416063/69076532-eced5800-09f0-11ea-822c-976b39aa2528.png)

That is a Grafana behavior. The values were reported at their whole values (1.0, 2.0, etc). The avg is computed by Grafana based on the window size you are displaying.

**Comment by asarkar** [comment]
It seems it's possible to cast the values to whole numbers on Grafana as shown below. I'll close this ticket.
![Screen Shot 2019-11-18 at 5 23 21 PM](https://user-images.githubusercontent.com/1302775/69108019-39a05580-0a28-11ea-8746-b919ecb2060e.png)
