### ISSUE TITLE
Counters not idempotent / state & lifecycle unclear

### ISSUE THREAD

**Issue by dylanraithel** [micrometer-metrics/micrometer#1713]
Counters (and presumably other metering classes) don't appear to be idempotent. A single instance of a Counter class, registered to a DataDogRegistry doesn't produce consistent results when calling count() or measure(). The below example is from a scala sbt console and is a verbatim output, in order.

```scala> counter
res74: io.micrometer.core.instrument.Counter = io.micrometer.core.instrument.step.StepCounter@34cb4a37

scala> counter.count()
res75: Double = 0.0

scala> counter.increment(10)

scala> counter.count()
res77: Double = 0.0

scala> counter.measure()
res78: Iterable[io.micrometer.core.instrument.Measurement] = [Measurement{statistic='COUNT', value=0.0}]

scala> counter.increment(10)

scala> counter.measure()
res80: Iterable[io.micrometer.core.instrument.Measurement] = [Measurement{statistic='COUNT', value=20.0}]

scala> counter.count()
res81: Double = 20.0

scala> counter.count()
res82: Double = 0.0
```

What's the lifecycle of the state of this object supposed to look like? Should the count values ever reset on their own? I'd really like to use this library and not go back to Dropwizard metrics if I don't have to

**Comment by Solutron** [comment]
Here's another example:

```res98: Iterable[io.micrometer.core.instrument.Measurement] = [Measurement{statistic='COUNT', value=0.0}]

scala> counter.increment(10)

scala> counter.increment(10)

scala> counter.increment(10)

scala> counter.increment(10)

scala> counter.increment(10)

scala> counter.increment(10)

scala> counter.increment(10)

scala> counter.increment(10)

scala> counter.count()
res107: Double = 0.0

scala> counter.measure()
res108: Iterable[io.micrometer.core.instrument.Measurement] = [Measurement{statistic='COUNT', value=0.0}]

scala> counter.measure()
res109: Iterable[io.micrometer.core.instrument.Measurement] = [Measurement{statistic='COUNT', value=0.0}]

scala> counter.count()
res110: Double = 0.0

scala> counter.increment()

scala> counter.measure()
res112: Iterable[io.micrometer.core.instrument.Measurement] = [Measurement{statistic='COUNT', value=101.0}]

scala> counter.count()
res113: Double = 101.0```

**Comment by Solutron** [comment]
It seems the call to a parameter-less `increment` method resolves the missing counted values with the state of the object. This doesn't make much sense to me :D

**Comment by checketts** [comment]
That is bizarre behavior and not at all what I would expect (especially based on my understanding of how it is implemented). 

Increment take a `double` is it possible the Scala `10` isn't calling the method correctly? How does it behave if you use `10.0`?

**Comment by Solutron** [comment]
It behaves the same, but I do eventually see the metrics in DataDog, so are the values in the Counter instance(s) just being reset after the library purges data to DataDog?

```scala> counter.count
res156: Double = 0.0

scala> counter.increment(10.0)

scala> counter.count
res158: Double = 0.0

scala> counter.measure()
res159: Iterable[io.micrometer.core.instrument.Measurement] = [Measurement{statistic='COUNT', value=10.0}]

scala> counter.count
res160: Double = 10.0

```

**Comment by shakuzen** [comment]
This, I believe, is due to timing and because the Step* implementations will return the value (count) for the **previous** interval. I'll open a separate issue to add some unit tests that demonstrate this for Step* metrics, as it has confused others and it would be nice to have something to point people to that also verifies the behavior. For now you can check the TCK test for counter increments.

https://github.com/micrometer-metrics/micrometer/blob/49162a881c4c80976980d6ea0ef45d2d59c4ca14/micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepDouble.java#L58-L64

https://github.com/micrometer-metrics/micrometer/blob/49162a881c4c80976980d6ea0ef45d2d59c4ca14/micrometer-test/src/main/java/io/micrometer/core/tck/CounterTest.java#L36-L49
