### ISSUE TITLE
Endpoint path with slash

### ISSUE THREAD

**Issue by banterCZ** [micrometer-metrics/micrometer#1719]
[In documentation](https://micrometer.io/docs/ref/spring/1.5) there is specified:

 > If you’d like the endpoint to be wired to a different endpoint, add a property:
> `endpoints.prometheus.id=micrometheus`

But when I set `endpoints.prometheus.id=/monitoring/prometheus` I get 
```
Binding to target io.micrometer.spring.export.prometheus.PrometheusScrapeEndpoint@39876e1f failed:

    Property: endpoints.prometheus.id
    Value: /monitoring/prometheus
    Reason: Property 'id' threw exception; nested exception is java.lang.IllegalArgumentException: Id must only contains letters, numbers and '_'
```

Other actuators respect _path_ property (thanks to [this fix](https://github.com/spring-projects/spring-boot/issues/5105)), e.g.

```
endpoints.health.id=health
endpoints.health.path=/monitoring/health
```

Micrometer endpoint is not possible to configure via path variable.

Using _Spring Boot_ **1.5.22** and _micrometer-spring-legacy_ **1.3.1** with _micrometer-registry-prometheus_.

**Comment by checketts** [comment]
I could be wrong, but I have some bad news @banterCZ . Since SpringBoot 1.5.x is end of life the `micrometer-spring-legacy` module has been deleted. 

Your best bet would be to subclass the `PrometheusScrapeEndpoint` and set the URL manually.

**Comment by banterCZ** [comment]
Well, I am not happy that I have to use that old version. Anyway, is `endpoints.prometheus.path` supported with **Spring Boot 2**?

**Comment by checketts** [comment]
They are slightly different with Spring Boot 2. See: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-customizing-management-server-context-path

To my knowledge they work correctly. I think the new one is: `management.endpoints.web.path-mapping.prometheus`

**Comment by shakuzen** [comment]
We can probably fix this in a patch release, but yes, going forward from the next feature release, micrometer-spring-legacy will no longer be published. So it is of course better to be on a supported version of Spring Boot.

**Comment by shakuzen** [comment]
Configuring the path with `endpoints.prometheus.path` should work in 1.1.9 and 1.3.2 micrometer-spring-legacy snapshots now.

**Comment by banterCZ** [comment]
Thanks a lot! I approve that it is working in 1.3.2-SNAPSHOT
