### ISSUE TITLE
Doc in section 3.1.2 describes wrong example

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#173]
The section 3.1.2 "Tag Naming" describes the following example: 

> Suppose we are trying to measure the number of threads in a thread pool and the number of rows in a database table.

But the sample shows something entirely different (number of HTTP requests on a given API)

**Comment by jkschneider** [comment]
Thanks. Fixed in my local edits for the micrometer docs that will roll out shortly.
