### ISSUE TITLE
1.3.2 release for registry jars

### ISSUE THREAD

**Issue by pjfanning** [micrometer-metrics/micrometer#1734]
Would it be possible to release 1.3.2 versions of jars like micrometer-registry-prometheus? Up until now, the norm appears to have been that all the main micrometer jars get released together.

http://repo1.maven.org/maven2/io/micrometer/micrometer-core/
http://repo1.maven.org/maven2/io/micrometer/micrometer-registry-prometheus/

**Comment by shakuzen** [comment]
Sorry about the inconvenience and thank you for reporting this. It looks like the sync between Bintray and Maven Central did not sync everything, even though logs show it was successfully synced. I'm re-running the syncing now and I'll verify things show up in Maven Central.

**Comment by shakuzen** [comment]
I've opened https://issues.sonatype.org/browse/OSSRH-53585. Releasing from the staging repository seems to have failed midway through leaving things in a partially released state.

**Comment by shakuzen** [comment]
Everything has been sync'd properly for 1.3.2 now and is available in Maven Central. Sorry again for the inconvenience and thank you for bringing it to our attention. Let us know if anything is still not as expected.
