### ISSUE TITLE
Signalfx tag name sanitization is incomplete

### ISSUE THREAD

**Issue by kjurasovic-dexcom** [micrometer-metrics/micrometer#1746]
Recently we started using SignalFx for our application monitoring.
We integrated to their endpoint using spring Boot 2.2 and micrometer SignalFx integration. 

Integration works well except in one case.

In our application we have Kafka consumers. 
Micrometer and Spring Boot expose all metrics to actuator endpoint and SignalFx. 
The problem is SignalFx rejects all Kafka related metrics.
After few days of research with SignalFx we determined that metrics are rejected because they contain tag with with a dot (.). Specifically tag "client.id".

According to SignalFx documentation tag name must be:
1) UTF-8 string, maximum length 128 characters (512 bytes)
2) Must start with an uppercase or lowercase letter. The rest of the name can contain letters, numbers, underscores (_) and hyphens (-)
3) Must not start with the underscore character (_)
4) Must not start with the prefix sf_, except for dimensions defined by SignalFx such as sf_hires
5) Must not start with any of these prefixes: aws_, gcp_, or azure_.

I've checked class SignalFxNamingConvention and it seems micrometer only enforces rules 1, part 1 of 2, 3, 4 but not 5 and "the rest of the name" rules.

At the moment we created our custom filter that sanitizes on missing rules. 
Would it be possible to add missing rules to SignalFx module?

SignalFx naming convention can be found here [link](https://developers.signalfx.com/metrics/data_ingest_overview.html#_criteria_for_metric_and_dimension_names_and_values).

We are currently using version "io.micrometer:micrometer-registry-signalfx:1.1.4".
I've check the master branch and it has the same issue.

**Comment by izeye** [comment]
@kjurasovic-dexcom Thanks for the report! I created #1748 to resolve this.

**Comment by shakuzen** [comment]
Thanks for the report @kjurasovic-dexcom and sorry for the inconvenience. We'll get this fixed for the next patch release. Once we have a fixed merged, if you could test the snapshots without your current workaround, we'd appreciate the confirmation of the fix.

By the way, Spring Boot 2.2 should manage the version of all Micrometer dependencies for you. Is there any reason you're explicitly using version 1.1.4 instead of the version managed by Spring Boot?

**Comment by kjurasovic-dexcom** [comment]
Thanks for the fix @shakuzen, @izeye. That was quick.
Sure we can test the fix when its ready.

Regarding version 1.1.4. We know about spring dependency management. This was some fix from before what was not removed yet. Will be in some future release.
