### ISSUE TITLE
Tomcat servlet metrics is not available anymore

### ISSUE THREAD

**Issue by crmky** [micrometer-metrics/micrometer#1754]
Seems this is a regression caused by https://github.com/micrometer-metrics/micrometer/commit/680f8103436f460a86be840150ed975dc45d7d4d.

The ObjectName format is something similar to:

```
Tomcat:j2eeType=Servlet,WebModule=//localhost/,name=default,J2EEApplication=none,J2EEServer=none
```

If query by `Tomcat:j2eeType=Servlet,name=*`, it returns nothing. I guess you probably want to modify the code from:

```
Set<ObjectName> objectNames = this.mBeanServer.queryNames(new ObjectName(getJmxDomain() + ":" + key + "=" + value + ",name=*"), null);
```

to:

```
Set<ObjectName> objectNames = this.mBeanServer.queryNames(new ObjectName(getJmxDomain() + ":" + key + "=" + value + ",name=*,*"), null);
```

**Comment by izeye** [comment]
@crmky Thanks for the report and sorry for the inconvenience. It seems that you're right. I created #1755 to try to fix it.

**Comment by shakuzen** [comment]
Thanks for the report @crmky and thank you for the quick pull request @izeye. I'm wondering why our tests didn't catch this before. Or was the NotificationListener still working even when the immediate registration failed due to the query always returning nothing?

**Comment by izeye** [comment]
@shakuzen There seems to be missing coverage which has been added in #1755.

**Comment by shakuzen** [comment]
> There seems to be missing coverage which has been added in #1755.

I see. It was only an issue for the Servlet metrics. Thank you for improving the coverage!
