### ISSUE TITLE
Avoid sending empty timer or summary values

### ISSUE THREAD

**Issue by nilswieber** [micrometer-metrics/micrometer#1762]
I'm using the ElasticMeterRegistry to send different metrics like request count and duration for the available endpoints. A larger number of endpoints can exist in my use case.

The problem is, that the ElasticMeterRegistry keeps sending entries for timers, where the count is 0, which isn't useful for my use case. But it takes a lot of space to store these "empty" values.

Is there any way to prevent sending of such "empty" entries and if not, could you provide a way to disable it.
Maybe a feature for filtering metrics to publish would be beneficial.

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/81420934-b205ea80-911e-11ea-9415-fb4fd60f7343.png)

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
