### ISSUE TITLE
AWS CloudWatch registry should be more customisable 

### ISSUE THREAD

**Issue by smougenot** [micrometer-metrics/micrometer#1763]
AWS CloudWatch metrics can become a mess because of its 'minimal' management of dimensions in custom metrics
see #303
or https://github.com/micrometer-metrics/micrometer/issues/457#issuecomment-477389592

## Goal
`CloudWatchMeterRegistry` should provide some customisable tools 
* for mapping `Meter` to `MetricDatum` (refers to the `Batch` inner class)
* for filtering (cost efficiency) the Meter that will be esported.

I'll work on a PR for those
Might be a way to add some possibilities for the use cases I related above.

**Comment by jkschneider** [comment]
@smougenot I think this kind of customization of the `MetricDatum` is fairly easily achieved by customizing the `CloudWatchAsyncClient` itself without any more complexity required in Micrometer's configuration?

```java
CloudWatchConfig config = ...

CloudWatchAsyncClient filteringClient = new CloudWatchAsyncClient() {
    private final CloudWatchAsyncClient delegate = CloudWatchAsyncClient.create();

    @Override
    public String serviceName() {
        return delegate.serviceName();
    }

    @Override
    public void close() {
        delegate.close();
    }

    @Override
    public CompletableFuture<PutMetricDataResponse> putMetricData(PutMetricDataRequest putMetricDataRequest) {
        return delegate.putMetricData(PutMetricDataRequest.builder()
                .namespace(config.namespace())
                .metricData(putMetricDataRequest.metricData().stream()
                        .filter(datum -> !datum.metricName().contains(".avg"))
                        .collect(Collectors.toList())
                )
                .build());
    }
};

CloudWatchMeterRegistry cloudwatchRegistry = new CloudWatchMeterRegistry(config, Clock.SYSTEM, filteringClient);
```

**Comment by jkschneider** [comment]
I'll close this for now under the assumption that there is a workable solution available, but happy to have more discussion on this if anybody would like.
