### ISSUE TITLE
Support for including HOST_GROUP in Dynatrace configuration 

### ISSUE THREAD

**Issue by anandr781** [micrometer-metrics/micrometer#1765]
I looked at the [issue](https://github.com/micrometer-metrics/micrometer/issues/1464) which details how to include device group . Can we supply HOST_GROUP value in this . Can you please clarify.

**Comment by shakuzen** [comment]
Could you reference some Dynatrace documentation so it is more clear what is meant by "HOST_GROUP value" here?

**Comment by anandr781** [comment]
Can you see this link : https://www.dynatrace.com/support/help/how-to-use-dynatrace/hosts/configuration/organize-your-environment-using-host-groups/

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
