### ISSUE TITLE
Avoid registering unnecessary listeners in TomcatMetrics

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1771]
Providing a clean up method is a good idea, but I wonder if we are also registering listeners for things that will never be notified. If we can eliminate that, it would help with memory usage, even in the case where there aren't multiple contexts. We can tackle that in a separate change, though.

_Originally posted by @shakuzen in https://github.com/micrometer-metrics/micrometer/pull/1760#issuecomment-570128659_

Related to #1424

**Comment by shakuzen** [comment]
> @shakuzen I thought about it, but I didn't do it intentionally as it is a breaking change. Is it okay to remove it on master?

@izeye I haven't looked at this closely yet, but I was judging from https://github.com/micrometer-metrics/micrometer/issues/1424#issue-444679628 that we may be registering more listeners than necessary. What would it break if we only registered the necessary ones? I'm not sure on what basis we make the distinction yet though.

> I debugged with eclipse and see the following behaviour:
> registerMetricsEventually will be called 2x (for "type", "StringCache" and "j2eeType", "Servlet") but on redeploy, the listener, which removes itself with `mBeanServer.removeNotificationListener` is only called for the "j2eeType", "Servlet" filter.

**Comment by izeye** [comment]
@shakuzen Sorry. I misread your comment as removing all clean-up listeners. Looking at the referenced comment, if it's always the case, clean-up listener for "StringCache" seems to be removable as you mentioned.
