### ISSUE TITLE
BaseTimeUnit in InfluxMeterRegistry

### ISSUE THREAD

**Issue by kratostaine** [micrometer-metrics/micrometer#1781]
The `InfluxMeterRegistry` class has the `getBaseTimeUnit()` implementation hardcoded to millis and is not configurable. Any particular reason for the same? Can it be made configurable?

```
    @Override
    protected final TimeUnit getBaseTimeUnit() {
        return TimeUnit.MILLISECONDS;
    }
```

https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxMeterRegistry.java#L239

**Comment by shakuzen** [comment]
Each MeterRegistry specifies a time unit that makes sense for the metrics backend it supports. For example, Prometheus expects time values to be in seconds, so it uses that. I don't know why milliseconds was chosen for Influx specifically (maybe @jkschneider remembers), but it provides consistency in reporting metrics, regardless of the unit used when recording values. Could you explain your use case for why you would want it to be configurable? If different apps are sending metrics with time values in different units, that seems more problematic, which making this configurable opens up as a possibility.

**Comment by kratostaine** [comment]
Thank you for the kind response @shakuzen. Well, Micrometer provides Timer recording in nanoseconds, and Influx provides the precision up to nanoseconds as well. I had a use-case of having the Timer values saved in Influx in millis precision, so that I can have better precision with my recorded timer values. But with the Micrometer's Influx implementation, it always gets saved in microseconds as it's hardcoded. I was wondering if there was a specific reasoning behind not making it configurable? Would having a default value set as `TimeUnit.MILLISECONDS` but opening up the possibility of having it configurable via the `InfluxConfig` interface be okay?

**Comment by shakuzen** [comment]
> Well, Micrometer provides Timer recording in nanoseconds, and Influx provides the precision up to nanoseconds as well. I had a use-case of having the Timer values saved in Influx in millis precision, so that I can have better precision with my recorded timer values. But with the Micrometer's Influx implementation, it always gets saved in microseconds as it's hardcoded.

It will send decimal values in milliseconds. For example, a timer with a maximum recorded value of 179 nanoseconds will send the max as `0.000179`.

**Comment by shakuzen** [comment]
> I was wondering if there was a specific reasoning behind not making it configurable? Would having a default value set as `TimeUnit.MILLISECONDS` but opening up the possibility of having it configurable via the `InfluxConfig` interface be okay?

We don't expose base time unit as a configuration option in any meter registry implementations currently. This has the benefit of not letting you easily get in the situation where different applications are reporting in different time units, which would be a pain to troubleshoot.
As mentioned in my previous response, precision is not lost since we are not rounding to whole milliseconds. Let us know if there's any other concern regarding this.
