### ISSUE TITLE
elasticsearch: how to specify a cluster for export

### ISSUE THREAD

**Issue by ajay-aggarwal** [micrometer-metrics/micrometer#1783]
We would like to export metrics to an elasticsearch cluster. This cluster has multiple nodes for HA and scalability. How can I specify a list of cluster nodes in Elasticsearch Config?  If I understood correctly `management.metrics.export.elastic.host` only accepts single host.

**Comment by shakuzen** [comment]
In light of this question, `host` may not have been the best naming for the property. It accepts a URL, which could be backed by a load balancer to balance traffic across Elasticsearch nodes in a cluster.

**Comment by marcingrzejszczak** [comment]
What could be the name of the metric? `addresses` ?
