### ISSUE TITLE
micrometer-core apparently distributes pcollections without proper attribution

### ISSUE THREAD

**Issue by tazle** [micrometer-metrics/micrometer#1785]
While looking inside the micrometer-core JAR at https://repo1.maven.org/maven2/io/micrometer/micrometer-core/1.3.1/micrometer-core-1.3.1.jar I noticed that it apparently includes pcollections from https://github.com/hrldcpr/pcollections without including the copyright notice from https://github.com/hrldcpr/pcollections/blob/master/LICENSE in the distribution.

**Comment by adriancole** [comment]
as #1786 is similar (though this one is more about shaded MIT licensed stuff vs the other which is a combination of ASL and otherwise), probably we should check to see what other pivotal/spring projects do.. possibly in a separate issue, or by renaming this to specifically the shade/repackaging aspect.

**Comment by adriancole** [comment]
This one is interesting. I think what's being requested here goes a bit beyond the norm, for example even beyond what's required by the ASF. For example, ASF only concerns itself with source distributions, not binary ones. There are many projects who shade in friendly licensed software as a part of the build without citing that.

As each of these type of requests is expensive to parse and could seem onorous to comply with, can you give a bit more color to the legal implication you think we have, yet ASF projects do not?

**Comment by adriancole** [comment]
ps thanks to @trustin for naming the demon here "Binary modification & redistribution" :D

if we end up covering this somehow, this would be the classification to file things like shade under.

**Comment by tazle** [comment]
> For example, ASF only concerns itself with source distributions, not binary ones.

Section 4a of Apache License 2.0 does not make any distinction between source and object forms of the work, recipients of either must be given a copy of the license.

Back to the matter at hand:
When it comes to other projects, spring-core includes the license text of its repackaged-in dependencies in its own license file.

Ee4j projects (typically) only include the copyright statements of its vendored-in dependencies in a separate notice file, and also include that in their binary distributions, but I'm not quite sure if that is sufficient in case of e.g. MIT license, where the requirement is specifically to include the complete copyright statement and license text with all copies of the software. I haven't yet gotten around to creating any tickets there, though.

**Comment by adriancole** [comment]
If you are interested in doing this, my unsolicited 2p would be to do a github search of anyone using shade or tools like it. You'll probably find most of the top projects use this and do not cite the act of binary modification as they do source. In cases where they do, you may find that they are acting randomly and not necessarily out of any specific consultation. You'll end up trying to convince probably hundreds of project leads to take a specific course which may make sense with your interpretation, but not actually required. As you mentioned you aren't an expert, and that could lead to judgemental errors.

If you want to take this on more specifically, I might suggest talking to someone who fosters the MIT license, and ask them. Or ask the authors of shade and tools that do binary modifications for the implications of that.

Putting a random implementation might well be what we do here, but seriously I wouldn't consider this particular topic black and white.

**Comment by adriancole** [comment]
since this is the only case where there's literally a different license in use I personally advocate eliminating the question vs the road taken so far. #1791 should remove the dependency and any questions about MIT.

I'm hoping there remains no objections to this, but if there are, hope whoever does takes effort to address the remaining license question etc which only exists while we use a vendored MIT thing.

**Comment by adriancole** [comment]
https://github.com/micrometer-metrics/micrometer/pull/1795 obviates this entirely
