### ISSUE TITLE
micrometer-core contains modified code from Guava, Jettison and Commons-lang without proper copyright attribution

### ISSUE THREAD

**Issue by tazle** [micrometer-metrics/micrometer#1786]
According to several comments in micrometer-core, it contains modified source code from Guava, Jettison and Commons-lang:
```
$ git grep -C1 'Modified'
micrometer-core/src/main/java/io/micrometer/core/instrument/util/AbstractPartition.java- *
micrometer-core/src/main/java/io/micrometer/core/instrument/util/AbstractPartition.java: * Modified from {@link com.google.common.collect.Lists#partition(List, int)}.
micrometer-core/src/main/java/io/micrometer/core/instrument/util/AbstractPartition.java- *
--
micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringEscapeUtils.java-    /**
micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringEscapeUtils.java:     * Modified from the quote method in:
micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringEscapeUtils.java-     * https://github.com/codehaus/jettison/blob/master/src/main/java/org/codehaus/jettison/json/JSONObject.java
--
micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringUtils.java-     *
micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringUtils.java:     * Modified from {@link org.apache.commons.lang.StringUtils#isBlank(String)}.
micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringUtils.java-     *
```

I could not find appropriate copyright attribution in the micrometer-core distribution, or in the project documentation.

**Comment by tazle** [comment]
Note that in case of https://github.com/codehaus/jettison/blob/master/src/main/java/org/codehaus/jettison/json/JSONObject.java, looking at the copyright statement there, and the code itself, it seems likely that the code is actually a derivative work of https://github.com/stleary/JSON-java/blob/master/JSONObject.java which is notoriously *not* licensed under the permissive Apache 2.0 license, but rather the JSON.org license, which forbids using the software for Evil.

**Comment by adriancole** [comment]
Experience from working in ASF space has that you are required to retain the copyright notice (NOTICE), if a project has one. The advisory copyright line in headers is a bit mushier. I've certainly seen projects do different things here, from nothing, to duplicating the header just to retain an old one, to always including a NOTICE file anytime ASL is used, to a combination of all the above.

The practice here, noting the source of ASL licensed work, is fairly common and not isolated to micrometer, and there are different styles used based on project governance and often self-imposed strictness levels. While definitely, I've seen folks passionate about particular approaches, I've also seen passion about different ways.

Regardless of decision made on where and whether to add "copyright the guava authors" in addition to the other citations, you did catch a nice one on the JSON thing which is absolutely something to address.

my 2p

**Comment by adriancole** [comment]
I think the abstractpartition code over-cites and also over-engineers the problem. For example, there's no need to handle negatives etc when factoring list sizes. I'll raise a PR to yank the code backfilling tests for edge cases.

**Comment by adriancole** [comment]
looking closer, all these things cited are trivial. there's no reason I can't think of to buff them out vs add more ceremony around them

**Comment by adriancole** [comment]
opened #1788 #1789 #1790 which I think should close this one out when they are done

**Comment by shakuzen** [comment]
> I could not find appropriate copyright attribution

To be clear, you mean that the copyright line from the original file is not present in our source? For example, for Guava's `Lists` class it is `Copyright (C) 2007 The Guava Authors`?

**Comment by tazle** [comment]
I guess something like "Copyright (C) 2007 The Guava Authors, modifications 20xx copyright Pivotal", if you want to go that route. But of course that's logistically problematic, since it only applies to a small fragment of the complete work. An alternative might be to just mention in the documentation that """
Micrometer contains modified source code from the Guava and Commons-lang, distributed under the Apache 2.0 license. The following copyrights apply to the modified source code:
- Copyright (C) 2007 The Guava Authors
- whatever the Commons-lang NOTICE file contains
"""

but then it's not clear where the modified 3rd part ysource code is in your codebase, in case you e.g. want to get rid of because you want to start distributing Micrometer under some other license.

Then again, I would not consider myself an expert on these matters, and if I was trying to do something similar on my employer's codebase, I would definitely seek to consult an expert.

**Comment by tazle** [comment]
Getting rid of the modified 3rd party code should certainly solve the problem for future Micrometer releases.

**Comment by adriancole** [comment]
thanks for the feedback and the context. We'll try to sort a pragmatic way
out that addresses attribution, but doesn't cause a lot of drag on the
project.

**Comment by adriancole** [comment]
fyi I'm planning to raise a PR similar to this, having studied various projects, finding almost no commonality :P Eventhough we aren't ASF, at least there is some documentation around it, so unless someone screams will copy approach of this https://github.com/openzipkin/brave/pull/1056

**Comment by adriancole** [comment]
this outta do it. appreciate the heads up about this stuff https://github.com/micrometer-metrics/micrometer/pull/1803
