### ISSUE TITLE
Get rid of StringUtils.isBlank/isNotBlank for just checking empty

### ISSUE THREAD

**Issue by codefromthecrypt** [micrometer-metrics/micrometer#1789]
As similarly discussed extensively in https://github.com/google/guava/issues/352, developers for years have propagated checking if something is apache commons variant of blank when probably, just empty or trimming would have sufficed. I think it if far easier to just stop using isBlank when all you really need to do is see if something is empty.

The current impact is that because we chose to cite apache commons like so...

```
public final class StringUtils {

    /**
     * Check if the String is null or has only whitespaces.
     *
     * Modified from {@link org.apache.commons.lang.StringUtils#isBlank(String)}.
     *
```

we ended up with an issue concerned with this #1786. If you look at the implementation it is an obvious loop over a string, which I think deserves no such citation in the first place. In any case, this is overused and I believe can just be swapped out with null || empty in almost all cases.

**Comment by adriancole** [comment]
FWIW I think when we use words like "Modified from X" it probably will raise antibodies with folks concerned about IP. Probably in some cases, we should just use "Like X" when something is similar or an obvious implementation with no viable alternative when using java standard libraries.

**Comment by jkschneider** [comment]
No objection to this, but please be careful about the various call sites. `HttpSender.Request.Builder` as well as uses in Dynatrace and Influx registries really do need to check for blank strings where we don't really need the trimmed variant of the string in the end (it's just a conditional switch).

**Comment by adriancole** [comment]
thanks for the tripline, warning, Jon.

Code creating strings with various whitespace only seems something to pin down. Can you recall why we expect not just ascii (spaces, tabs, cr/lf), but all unicode blank characters in any of these? I can't seem to find at least in the http sender builder where the original act happened, ex where the bug occurred where checkBlank was the solution. Just my experience, but last ten years of doing clients and senders (including jclouds), we've never needed to guard randomly on client requests. Seems something we can couple to the call sites. ex if somehow dynatrace and influx are creating empty payloads with odd unicode characters, put a utility there and tests to prove it.

thoughts?

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
