### ISSUE TITLE
Remove core dependency on pcollections?

### ISSUE THREAD

**Issue by adriancole** [micrometer-metrics/micrometer#1791]
I was auditing how pcollections is used, as we were asked to cite it due to the side effects of shading in #1785.

I read through the benefits claimed by pcollections, notably how it allows lazy chaining without copying all values. However, in auditing use of the types in the core module, I notice collections are not folded.. all uses I could find were adding or removing single elements. It may have been more sophisticated in a version before, but currently, I'd question why we can't use SDK libraries instead of pcollections, especially considering all the ops happen under locks anyway. 

Adding a single element to a collection under a lock vs swapping references each time seems something we can prove out with benchmarks, and I'd prefer the simpler less dependencies way out vs using a third party library which isn't (as I perceive) being played to its strengths anyway.

**Comment by adriancole** [comment]
spiked this https://github.com/micrometer-metrics/micrometer/pull/1794

**Comment by shakuzen** [comment]
The history is that pcollections was introduced as part of the solution to https://github.com/micrometer-metrics/micrometer/issues/585. Also linked there is a commit that added a metrics registration benchmark that we could probably use to ensure there is no performance degradation in any alternate implementation. The only other concern I can think of is that the new implementation does not introduce any (new) concurrency problems.
@jkschneider are there any other motivations for using pcollections that should be considered?
