### ISSUE TITLE
StepTimer#max should always return maximum value for the last step

### ISSUE THREAD

**Issue by crankydillo** [micrometer-metrics/micrometer#1796]
My team currently has a custom `StepMeterRegistry` and needs to push `Timer#max` to our metric gathering backend.   If I add a delay in publish, which of course can happen due to thread scheduling, I get some weird results.  I know in my case, I could take a snapshot before the sleep; however, that won’t help me if publish altogether fires much later than the step’s duration.

```
public static void main(String[] args) {
    class MyReg extends StepMeterRegistry {
            public MyReg(final Clock clock) {
                super(new StepRegistryConfig() {
                    @Override
                    public String prefix() {
                        return null;
                    }
                    @Override
                    public String get(final String key) {
                        return null;
                    }
                    @Override
                    public Duration step() {
                        return Duration.ofMillis(2_500);
                    }
                }, clock);
            }
            @Override
            protected void publish() {
                System.out.println("publishing!");
                try {
                    Thread.sleep(1500);
                } catch (Exception e) {
                }
                this.getMeters().forEach(meter -> {
                    if (meter instanceof Timer) {
                        Timer t = (Timer) meter;
                        System.out.println(t.mean(TimeUnit.SECONDS));
                        System.out.println(t.count());
                        System.out.println(t.max(TimeUnit.SECONDS));
                        Arrays.stream(t.takeSnapshot().percentileValues()).forEach(p -> {
                            System.out.println(p.percentile() + " - " + p.value(TimeUnit.SECONDS));
                        });
                    }
                });
            }
            @Override
            protected TimeUnit getBaseTimeUnit() {
                return TimeUnit.MILLISECONDS;
            }
        }
        MyReg reg = new MyReg(Clock.SYSTEM);
        reg.config()
            .meterFilter(new MeterFilter() {
                @Override
                public DistributionStatisticConfig configure(final Meter.Id id, final DistributionStatisticConfig config) {
                    return DistributionStatisticConfig.builder()
                        .bufferLength(1)
                        .build()
                        .merge(config);
                }
            });
        reg.start();
        Timer timer = Timer.builder("sams").register(reg);
        Thread.sleep(3_000);
        timer.record(Duration.ofSeconds(25));
        timer.record(Duration.ofSeconds(75));
        Thread.sleep(3_000);
        timer.record(Duration.ofSeconds(25));
        Thread.sleep(3_000);
        timer.record(Duration.ofSeconds(5));
        timer.record(Duration.ofSeconds(10));
        Thread.sleep(3_000);
}
```

I get the following results:
```
publishing!
0.0
0
75.0
publishing!
25.0
1
25.0
publishing!
0.0
0
0.0
publishing!
7.5
2
0.0
```
The max shouldn't be 75 if the count was 0 (first publish), nor should the average be 7.5 if the max is 0 (last publish).

My proposal is that `TimeWindowMax` should not be used for `PushMeterRegistry#newTimer`.  Instead, we should use a `Timer` that records `max` in something like a `StepLong`, which will always display the previous steps maximum value.

[Original slack discussion](https://micrometer-metrics.slack.com/archives/C662HUJC9/p1578668216044200?thread_ts=1578590819.023800&cid=C662HUJC9)

**Comment by crankydillo** [comment]
Of course, [the move to `TimerMaxWindow`](https://github.com/micrometer-metrics/micrometer/commit/0b13da44c4d862ae5d68fd19eb4944991935fecb) is concerning as the previous code appears to be what we want:)

**Comment by shakuzen** [comment]
I think it makes sense to align the max with the count and total. This will be a significant change for users paying close attention to max, though, so I've marked this to include a prominent note in the release notes. We will want to update any documentation accordingly.

This will reverse the change in #317 but only for `StepMeterRegistry`.

Copying for posterity a comment from Slack about max and percentiles by @jkschneider 

> view the calculation of a percentile and a max as independent things with different windows upon which they are operating
