### ISSUE TITLE
Support "collection" tag in "mongodb.driver.commands" metric

### ISSUE THREAD

**Issue by netme** [micrometer-metrics/micrometer#1799]
Currently, `mongodb.driver.commands` metric exposes the following tags:
- command
- cluster.id
- server.address
- status

https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandListener.java#L62

It would be great to make it more verbose and additionally expose MongoDB collection names.

**Comment by chrgue** [comment]
We were very happy when we found out there is a way to get such metrics.

But for services which are interacting with more then one collection the "collection" tag seams to be mandatory to generate useful insights.

**Comment by netme** [comment]
Thanks, @chrgue for taking a look at this ticket 

I have tried to mock a possible solution:

```java
public class MongoMetricsCommandListener implements CommandListener {

    private final ConcurrentHashMap<Integer, String> collectionsCache;
    
    // ... 

    @Override
    public void commandStarted(final CommandStartedEvent event) {
        extractCommandName(event)
                .ifPresent(it -> collectionsCache.put(event.getRequestId(), it));
    }

    @Override
    public void commandSucceeded(final CommandSucceededEvent event) {
        timeCommand(event, getCollectionNameOrUnknown(event), "SUCCESS", event.getElapsedTime(TimeUnit.NANOSECONDS));
    }

    @Override
    public void commandFailed(final CommandFailedEvent event) {
        timeCommand(event, getCollectionNameOrUnknown(event), "FAILED", event.getElapsedTime(TimeUnit.NANOSECONDS));
    }
    // ...
}
```

MongoDB driver does expose the collection name, however, it is only available in `commandStarted`. We can try to use some cache to get this data accessible in both `commandSucceeded` and `commandFailed`. What do you think about this approach?
