### ISSUE TITLE
Release 1.3.3 not properly synced in Maven Central

### ISSUE THREAD

**Issue by jakubjanecek** [micrometer-metrics/micrometer#1811]
Hello,
I think the latest release `1.3.3` is not properly synced into Maven Central. Even though the files seem to be there https://repo1.maven.org/maven2/io/micrometer/micrometer-registry-statsd/1.3.3/ I always get `404` when I try to download them. Probably the same problem as in #1734. Could you please try to refresh it again?

Thank you.

**Comment by shakuzen** [comment]
Sorry for the inconvenience. We're awaiting final resolution of https://issues.sonatype.org/browse/OSSRH-54535

**Comment by shakuzen** [comment]
Both 1.1.10 and 1.3.3 should be downloadable now. Let us know if you have any issues with that still.
