### ISSUE TITLE
CloudWatchMeterRegistry sends tags with empty values which CloudWatch then rejects

### ISSUE THREAD

**Issue by carhartl** [micrometer-metrics/micrometer#1813]
Project reactor integration for instance defines an `exception` tag with a default value of "", for when collecting metrics for arbitrary sequences (`reactor.flow.duration`).

Similar to #1167

With the following workaround I can get the metrics to show up in CloudWatch:

```java
@Configuration
public class MetricsConfig {
  @Bean
  MeterRegistryCustomizer<CloudWatchMeterRegistry> sanitizeReactorTags() {
    return registry ->
        registry
            .config()
            .meterFilter(
                MeterFilter.replaceTagValues("exception", tag -> tag.isBlank() ? "None" : tag));
  }
}
```
^ I chose to turn the blank tag into "None", similar to how the Spring request latency metrics look like, but the tag could just as well be removed I guess.

**Comment by shakuzen** [comment]
Thanks for reporting this. Have you also reported it to the Reactor team? They might want to consider following suit with similar metrics that use an exception tag.

**Comment by shakuzen** [comment]
Here is the relevant section of the [CloudWatch documentation on Dimensions](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Dimension.html):

> Length Constraints: Minimum length of 1. Maximum length of 255.

**Comment by carhartl** [comment]
Hi @shakuzen 

>Have you also reported it to the Reactor team?

I thought of that, but wasn't sure were this issue belongs. Judging from #1167 it seemed like it needs to be taken care of in Micrometer.

If we're going to fix it here, I might find the time to create a PR, would that be ok?

**Comment by shakuzen** [comment]
We'll want to fix the general case here regardless of anything that changes or not in Reactor. But the fix here will drop the non-conforming dimension. If the implementation changes to use `None` for the value, then it will properly make it to CloudWatch.

> If we're going to fix it here, I might find the time to create a PR, would that be ok?

Sounds good. I'll look forward to your pull request. Let me know if you don't have the time or interest in the PR anymore and I'll take care of it instead.
