### ISSUE TITLE
Metric "cpu.load.average" unfortunate naming

### ISSUE THREAD

**Issue by mweirauch** [micrometer-metrics/micrometer#182]
Everybody mistakes this as the CPU load average, when it basically is the system load average. Rightly so the metric is coming from the better named `OperatingSystemMXBean::getSystemLoadAverage`.

There is a nice post by Brendan Gregg detailing some archeological digging on when that metric became something like "system load average": http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html
The post mentions, that for other OSes the value might really mean only "cpu load average", though.

Is the naming on purpose or hasn't any deeper thought put on it?
Also, should it be made clear it's the "1m" load average? (at least on my Linux based system)

**Comment by jkschneider** [comment]
Nothing but ignorance of the deeper meaning on my part :). Let's rename it!

**Comment by checketts** [comment]
So `os.load.average1m` ?

**Comment by mweirauch** [comment]
I had thought of `system.load.average.1m`.
