### ISSUE TITLE
Evaluate Circllhist as an HdrHistogram replacement

### ISSUE THREAD

**Issue by trustin** [micrometer-metrics/micrometer#1821]
https://arxiv.org/abs/2001.06561

> The circllhist histogram is a fast and memory efficient data structure for summarizing large numbers of latency measurements. It is particularly suited for applications in IT infrastructure monitoring, and provides nano-second data insertion, full mergeability, accurate approximation of quantiles with a-priori bounds on the relative error.
> Open-source implementations are available for C/lua/python/Go/Java/JavaScript.

**Comment by adriancole** [comment]
relates to #1599 as currently there's a hard dependency on HdrHistogram. Not sure if the aim here is to replace or make possible.

Interesting paper. I haven't yet found the java impl, though. I have found others which are BSD licensed, not sure if/how they are distributed cc @postwait https://github.com/circonus-labs/libcircllhist

**Comment by postwait** [comment]
https://github.com/circonus-labs/metrics-circonus/blob/master/metrics-circonus/src/main/java/com/circonus/metrics/HistImpl.java

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
