### ISSUE TITLE
MetricsTurboFilter increments stats when is<LEVEL>Enabled() is called.

### ISSUE THREAD

**Issue by bcrownw** [micrometer-metrics/micrometer#183]
For isDebugEnabled, isErrorEnabled, etc are called, the decide filter is invoked with null parameters for format, params, and t.

This causes inflated count stats, and in some cases phantom counts when one of those actions does not actually generate a log message.

**Comment by checketts** [comment]
Perhaps an `appender` is a better solution. I've been using my own appender with good success for a while now. I'll create a PR to share it.

**Comment by jkschneider** [comment]
@bcrownw Good catch, thanks!
