### ISSUE TITLE
MeterFilter.accept(Meter.Id id) states in Javadoc that the id parameter is passed after the transformations, but in reality, the pre-mapped id is used.

### ISSUE THREAD

**Issue by dlemaigl** [micrometer-metrics/micrometer#1834]
The MeterFilter.accept method states that the id will be passed after the transformations of the mapper filter are applied.

[MeterFilter](https://github.com/micrometer-metrics/micrometer/blob/05e66eba7c00aaab207ea139ccb5d2674547a113/micrometer-core/src/main/java/io/micrometer/core/instrument/config/MeterFilter.java#L394)
```java
/**
     * @param id Id with {@link MeterFilter#map} transformations applied.
     * @return After all transformations, should a real meter be registered for this id, or should it be no-op'd.
     */
    default MeterFilterReply accept(Meter.Id id) {
        return MeterFilterReply.NEUTRAL;
    }
```

But in the MeterRegistry, we can see that te originalId is passed instead. This causes that the accept or deny filters don't take on account the previous mapper filters.

[MeterRegistry](https://github.com/micrometer-metrics/micrometer/blob/05e66eba7c00aaab207ea139ccb5d2674547a113/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L581)

```java
private Meter getOrCreateMeter(@Nullable DistributionStatisticConfig config,
                                   BiFunction<Id, /*Nullable Generic*/ DistributionStatisticConfig, ? extends Meter> builder,
                                   Id originalId, Id mappedId, Function<Meter.Id, ? extends Meter> noopBuilder) {
        Meter m = meterMap.get(mappedId);

        if (m == null) {
            if (isClosed()) {
                return noopBuilder.apply(mappedId);
            }

            synchronized (meterMapLock) {
                m = meterMap.get(mappedId);

                if (m == null) {
                    if (!accept(originalId)) { // <-- this should be mappedId instead
                        //noinspection unchecked
                        return noopBuilder.apply(mappedId);
                    }
```

If you want i can make a PR to change it.

**Comment by dlemaigl** [comment]
I have created a test where you can see this issue in action.

 [https://github.com/dlemaigl/Micrometer-issue-test-1834](https://github.com/dlemaigl/Micrometer-issue-test-1834)

**Comment by dlemaigl** [comment]
Created PR to fix it -> #1847

**Comment by jkschneider** [comment]
Thanks again @dlemaigl!

**Comment by jkschneider** [comment]
Backported to 1.1.x with 0c057fc1c22e6db3e3454e28d2463ddf34cc05b5
