### ISSUE TITLE
Disable aggregations

### ISSUE THREAD

**Issue by kvaidas** [micrometer-metrics/micrometer#1838]
It seems that the metric aggregations posted (tested on ElasticSearch and CloudWatch) are kind of redundant since it's possible to do aggregations without having them stored separately. This would save space - in case of ElasticSearch. Or in the case of CloudWatch, it could cut the cost by 75% by only having 1/4 of the metrics.

**Comment by GregoryOrciuch** [comment]
I'm looking forward that too. In my app there is no point of sending out the avg/min/max, while all those can be calculated directly in CloudWatch.

@kvaidas did you find a way to maybe disable those aggregated ones? or blacklist them.

**Comment by shakuzen** [comment]
> It seems that the metric aggregations posted (tested on ElasticSearch and CloudWatch) are kind of redundant since it's possible to do aggregations without having them stored separately. This would save space - in case of ElasticSearch. Or in the case of CloudWatch, it could cut the cost by 75% by only having 1/4 of the metrics.

Could you be more specific? Averages probably shouldn't be shipped at all anyways, but removing that will have to be a 2.0 change. I suppose we could make a configuration option to not ship them in the meantime. Anything other than average you're looking to change? For which meter types? For which registries? We would need to verify such aggregations can be easily done in the backend.

> I'm looking forward that too. In my app there is no point of sending out the avg/min/max, while all those can be calculated directly in CloudWatch.

We don't ship a min, as far as I know. Average, I agree - see above. As for max, I don't see how you can calculate that in CloudWatch - we don't ship individual metric recordings so how would you know after the fact what the max value was for any time period?

**Comment by GregoryOrciuch** [comment]
@shakuzen alright, so with details here we are:
1. My app using spring-boot+spring-actuator+micrometer + cloudwatch-registry. All is like default from pom.xml. 
2. Looks like only custom metrics via Gauge or Couter do not pass to cloudwatch the min/max/avg/sum . They only appear as .value or .counter which is fine

3. However the preconfigured metrics like 'http.client.requests." or "http.server.requets."  are sending to CloudWatch avg/sum/min/max and count. My thinking is that only 'count' is needed in CloudWatch (app is sending-out all every 5min). So if I know that I can let cloudwatch to calculcate min/max/avg/sum by it's own based on the 'count' metric.

4. Also all "@Timed" annotated rest methods metrics are sending out all the avg and the stuff. 

5.  I tried MetricFilter with Deny on ".avg" etc but it didnt work and it still sending out all of them.
ref. https://stackoverflow.com/a/54097060

[
![Screenshot from 2020-04-14 10-13-29](https://user-images.githubusercontent.com/1514985/79201616-a5041d00-7e38-11ea-991f-7075e88a4904.png)
](url)

**Comment by shakuzen** [comment]
> * However the preconfigured metrics like 'http.client.requests." or "http.server.requets."  are sending to CloudWatch avg/sum/max and count. My thinking is that only 'count' is needed in CloudWatch (app is sending-out all every 5min). So if I know that I can let cloudwatch to calculcate min/max/avg/sum by it's own based on the 'count' metric.
> 
> * Also all "@timed" annotated rest methods metrics are sending out all the avg and the stuff.

Yes, Timer meters will typically ship count/sum/avg/max depending on the specific registry. The `count` is the number of recorded events. The `sum` is the sum of total time recorded. The `max` is a time-windowed maximum latency recorded. This is explained [in the Micrometer documentation for Timers](https://micrometer.io/docs/concepts#_timers). So if you only have a `count`, you only have a Counter for the number of recorded events (e.g. HTTP server requests). You lose all information about how long requests took that is contained in the `sum` and `max`. You would not be able to derive this in CloudWatch only given a `count`.

>     5\. I tried MetricFilter with Deny on ".avg" etc but it didnt work and it still sending out all of them.
>         ref. https://stackoverflow.com/a/54097060

`MeterFilter` is for filtering `Meter`s. Depending on the registry implementation, a `Meter` is converted to one or more time series that are published to the metrics backend. You cannot filter out individual time series from a Meter using a `MeterFilter`.

**Comment by GregoryOrciuch** [comment]
@shakuzen thanks for explanation. However still, I dont know how I can achive the goal, while goal is to not have a avg/sum/max (whatever my choice is) in CloudWatch. App is quite simple and having 300+ metric points almost by default. I've been asked to figure out how to resign from at least part of them, and still looking for a way to blacklist unwanted metrics (like the avg)

**Comment by jkschneider** [comment]
@kvaidas / @GregoryOrciuch for the reasons @shakuzen mentions, you can't derive max from count. But if you _really_ only want count, you can accomplish this sort of filtering by customizing the `CloudWatchAsyncClient` to filter out unwanted `MetricDatum`.

```java
CloudWatchAsyncClient filteringClient = new CloudWatchAsyncClient() {
    private final CloudWatchAsyncClient delegate = CloudWatchAsyncClient.create();

    @Override
    public String serviceName() {
        return delegate.serviceName();
    }

    @Override
    public void close() {
        delegate.close();
    }

    @Override
    public CompletableFuture<PutMetricDataResponse> putMetricData(PutMetricDataRequest putMetricDataRequest) {
        return delegate.putMetricData(PutMetricDataRequest.builder()
                .namespace(config.namespace())
                .metricData(putMetricDataRequest.metricData().stream()
                        .filter(datum -> !datum.metricName().contains(".avg"))
                        .collect(Collectors.toList())
                )
                .build());
    }
};

CloudWatchMeterRegistry cloudwatchRegistry = new CloudWatchMeterRegistry(key -> null, Clock.SYSTEM, filteringClient);
```

**Comment by shakuzen** [comment]
> App is quite simple and having 300+ metric points almost by default. I've been asked to figure out how to resign from at least part of them, and still looking for a way to blacklist unwanted metrics (like the avg)

You could also disable the Spring Boot auto-configuration and only register the meters you want.

**Comment by wuetherich** [comment]
in micrometer what is the default time period for a timer and how do i change it?
