### ISSUE TITLE
Support application/host prefixes

### ISSUE THREAD

**Issue by dheld-expedia** [micrometer-metrics/micrometer#184]
In our environment, we have hundreds of applications which log to the same back-end.  Thus, we need to namespace our metrics by application and server.  Ideally, we could make these a fixed prefix of the metric names, rather than a tag, which comes after the metric name.  So, for instance, instead of:

`jvmMemoryCommitted.area.heap.id.Par_Eden_Space.statistic.value`

we would have:

`my-app.my-host.jvmMemoryCommitted.area.heap.id.Par_Eden_Space.statistic.value`

**Comment by spencergibb** [comment]
Isn't that exactly what tags are for, so everything shares the same metric name, but it could be filtered by a tag? Can you explain why tags don't work in your case?

**Comment by dheld-expedia** [comment]
Because our back-end is Graphite (based), and tags flatten after the metric name.  So the above becomes:

`jvmMemoryCommitted.my-app.my-host.area.heap.id.Par_Eden_Space.statistic.value`

Unfortunately, we have a lot of infrastructure which requires the app and host to be a prefix to aggregate properly, so the position of elements is quite important.

**Comment by jkschneider** [comment]
@dheld-expedia Tags flatten after the metric name _by default_. But you are free to replace `HierarchicalNameMapper` with whatever scheme you desire (see the `GraphiteMeterRegistry` constructor that takes an instance of `HierarchicalNameMapper` or if you are in a Spring environment, you just need to declare a `@Bean` of type `HierarchicalNameMapper`).

Your particular implementation can add a prefix and then just delegate to the DEFAULT mapper to do the rest.
