### ISSUE TITLE
AWS SDK needs upgrade to v2.10.56 to prevent use of stale IP

### ISSUE THREAD

**Issue by tomerzel87** [micrometer-metrics/micrometer#1840]
Got a note from AWS:

One or more applications in your AWS account has a dependency on asynchronous features of AWS SDK for Java V2. In versions below 2.10.56 of the AWS SDK for Java V2, the asynchronous clients (e.g. S3AsyncClient, SqsAsyncClient) resolve and cache the IP address of AWS Services once per channel pool, and the resolved IP is then used for all future connections to the host name until the client is closed. As a result, applications that use long-lived asynchronous SDK clients could use stale IP addresses to AWS services that can result in exceptions, and potentially not use the breadth of load balancing that the service provides, causing increased overall latency.

What Do I Need to Do?
Please upgrade your application dependency to AWS Java V2 SDK 2.10.56 [1].

The latest release of micrometer (1.3.3) uses AWS SDK 2.9.9

**Comment by shakuzen** [comment]
I'm assuming you're using the CloudWatch registry which has a dependency on the AWS SDK. You should be able to override the version of the dependency in your application.

**Comment by jkschneider** [comment]
To add further @tomerzel87, dependencies on third party dependencies are updated to their latest forms every minor release but kept stable over patch releases. So you can expect 1.4.x will have AWS 2.10.x or whatever the latest version of the AWS SDK is at that time. In the meantime, as @shakuzen notes, you can absolutely include a later version of the AWS SDK in your application, and allow version conflict resolution in either Maven or Gradle to select your more recent SDK version.

**Comment by shakuzen** [comment]
Closing this per notes about using dependency management in your build tool to use a later version and also Micrometer 1.4.0 has been released which builds with version 2.10.88 of the AWS SDK.
