### ISSUE TITLE
Shaded dependencies missing in snapshots

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1843]
micrometer-registry-statsd 1.4.0-snapshot with spring boot 2.2.0.RELEASE, 2.2.4.RELEASE release will  throw java.lang.NoClassDefFoundError: io/micrometer/shaded/reactor/core/publisher/FluxSink
FluxSink class was part of the micrometer-registry-statsd 1.3.0 jar.

_Originally posted by @uchandroth in https://github.com/micrometer-metrics/micrometer/issues/1676#issuecomment-582821986_

---

Looks like the shaded classes are not included in the produced JAR artifact anymore. Possibly related to build changes made recently in `master`.

**Comment by shakuzen** [comment]
Any ideas on this one @anuraaga? I'll try taking a look later but I figured you might be faster than me.

**Comment by anuraaga** [comment]
Yeah I'm sure it's related to my changes, let me take a look tomorrow.

First thing I do will be understanding why we have these two magic lines here

https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-statsd/build.gradle#L32
