### ISSUE TITLE
MeterFilter applied twice to KafkaConsumerMetrics

### ISSUE THREAD

**Issue by fukuang** [micrometer-metrics/micrometer#1850]
I have a `MeterFilter` which adds a `prefix` to all my metrics.
It will be applied twice to kafka consumer metrics.

Using `kafka.consumer.fetch.latency.avg` as an example:

In [KafkaConsumerMetrics.bindTo](https://github.com/micrometer-metrics/micrometer/blob/b546524ad6eda81d857f6ce392530f1e0aea4ac4/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java#L108), [registerTimeGaugeForObject](https://github.com/micrometer-metrics/micrometer/blob/b546524ad6eda81d857f6ce392530f1e0aea4ac4/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java#L219) is invoked.

Inside it, a TimeGauge [registers](https://github.com/micrometer-metrics/micrometer/blob/b546524ad6eda81d857f6ce392530f1e0aea4ac4/micrometer-core/src/main/java/io/micrometer/core/instrument/TimeGauge.java#L117) itself to reigstry.

At where the id is mapped by [getMappedId(id)](https://github.com/micrometer-metrics/micrometer/blob/b546524ad6eda81d857f6ce392530f1e0aea4ac4/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L528) as `prefix.kafka.consumer.fetch.latency.avg`

The meter with mapped id will eventually be returned to [`KafkaConsumerMetrics`](https://github.com/micrometer-metrics/micrometer/blob/b546524ad6eda81d857f6ce392530f1e0aea4ac4/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java#L142).

It's used for [addUnregistrationListener](https://github.com/micrometer-metrics/micrometer/blob/b546524ad6eda81d857f6ce392530f1e0aea4ac4/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java#L267) to [remove](https://github.com/micrometer-metrics/micrometer/blob/b546524ad6eda81d857f6ce392530f1e0aea4ac4/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java#L301) meter with the mapped id `prefix.kafka.consumer.fetch.latency.avg`.

In `MeterRegistry.remove` the `getMappedId` is [invoked again](https://github.com/micrometer-metrics/micrometer/blob/b546524ad6eda81d857f6ce392530f1e0aea4ac4/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L626). The result id is now `prefix.prefix.kafka.consumer.fetch.latency.avg`. So no one is removed and two metrics left in registry.

This is triggered at least in Kafka Fetcher, when [`fetchThrottleTimeSensor.add`](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/internals/Fetcher.java#L1373) is invoked for the 2nd time. (by [JmxReporter](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/metrics/JmxReporter.java#L162))

**Comment by shakuzen** [comment]
Thank you for the analysis on this. This generically is an issue with removing meters when there is a non-idempotent `MeterFilter` registered. The following unit test fails:

```java
@Test
void removeMetersAffectedByPrefixingMeterFilter() {
    registry.config().meterFilter(new MeterFilter() {
        @Override
        public Meter.Id map(Meter.Id id) {
            return id.withName("prefix." + id.getName());
        }
    });

    Counter counter = registry.counter("name");
    assertThat(registry.find("prefix.name").counter()).isSameAs(counter);
    assertThat(registry.remove(counter)).isSameAs(counter); // fails here
    assertThat(registry.find("prefix.name").counter()).isNull();
}
```
