### ISSUE TITLE
Support Shenandoah GC in JvmGcMetrics

### ISSUE THREAD

**Issue by IRus** [micrometer-metrics/micrometer#1861]
Micrometer: 1.3.5
JDK: 11.0.6

Right now all metrics exported from `JvmGcMetrics` are 0.

**Comment by asad-awadia** [comment]
And/Or metronome from openj9

**Comment by shakuzen** [comment]
@asad-awadia Could you open a separate issue for that? I did not know OpenJ9 had its own garbage collector.

**Comment by asad-awadia** [comment]
@shakuzen https://github.com/micrometer-metrics/micrometer/issues/1458 I think there is already an issue? Didn't want to make duplicates
