### ISSUE TITLE
Multiple Counter increments for single log4j2 event

### ISSUE THREAD

**Issue by cbarreholm** [micrometer-metrics/micrometer#1862]
### Issue ###
Log4j2Metrics is causing the logging events to be counted multiple times when the same LoggerConfig is shared by multiple Logger:s available at autoconfiguration time. It appears to be triggered for those loggers that are initialized in a class annotated with @Configuration. 

### Reproduce ###
I have created a sample project that demonstrates the issue in detail.
https://bitbucket.org/ingby/micrometer-log4j2-duplicates

### Relations ###
This ticket is related to issue #1466.

### Micrometer Version ###
The sample runs:
Micrometer 1.3.1
```
$ mvn dependency:tree|grep micrometer
[INFO] ---------------< com.ingby:micrometer-log4j2-duplicates >---------------
[INFO] Building micrometer-log4j2-duplicates 1.0.0-SNAPSHOT
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ micrometer-log4j2-duplicates ---
[INFO] com.ingby:micrometer-log4j2-duplicates:jar:1.0.0-SNAPSHOT
[INFO] +- io.micrometer:micrometer-registry-prometheus:jar:1.3.1:compile
[INFO] |  +- io.micrometer:micrometer-core:jar:1.3.1:compile
```

### Troubleshooting and Mitigation ###
Run a debugger and set a breakpoint in `Log4j2Metrics` method `bindTo` to detect which LoggerConfig:s that filters are added to multiple times. Those Logger:s are likely initialized in a @Configuration class. Note that all loggers falling under that configuration will be incorrect, not only the ones found in breakpoint. 

Declaring dedicated logger configs for those specific classes should limit the impact on other loggers, which would otherwise have fallen under the same config.

**Comment by cbarreholm** [comment]
I have created a branch in the demo project to show how one could work around the issue by not specifying an appenderRef and implicitly setting additivity `true`. The later will filter out the logger from Log4j2Metrics.bindTo, avoiding the bug.
https://bitbucket.org/ingby/micrometer-log4j2-duplicates/branch/config-workaround

**Comment by RJayz** [comment]
I have also encountered this issue, and have submitted this pull request for it:
https://github.com/micrometer-metrics/micrometer/pull/1842
