### ISSUE TITLE
Deploy task fails with Gradle 6.2.1 on statsd artifact

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1872]
Since upgrading the build to use Gradle 6.2.1 in #1857 the deploy job is failing, specifically for the statsd artifact, with the following error. For instance, see https://circleci.com/gh/micrometer-metrics/micrometer/5525

```
Execution failed for task ':artifactoryDeploy'.
> java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Artifact micrometer-registry-statsd-1.4.0-SNAPSHOT.jar wasn't produced by this build.
```

This leads me to believe it has to do with the shadow plugin we are using with the statsd module.

**Comment by shakuzen** [comment]
@anuraaga if you have any bandwidth and interest on taking a look at this one, it would be appreciated. No problem if not - we can rollback the Gradle version upgrade at least until we get out the upcoming 1.4 release and work on fixing this in time for the 1.5 release.

**Comment by anuraaga** [comment]
Sorry about this I'll take a look tomorrow. Indeed I was worried about
deploy tasks which I can't actually run locally. Hoping I'll find a good
pointer in the logs.

**Comment by izeye** [comment]
@anuraaga For your information, a similar failure can be reproduced with the following command:

```
$ ./gradlew clean pTML
...
> Task :micrometer-registry-statsd:publishNebulaPublicationToMavenLocal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':micrometer-registry-statsd:publishNebulaPublicationToMavenLocal'.
> Failed to publish publication 'nebula' to repository 'mavenLocal'
   > Artifact micrometer-registry-statsd-1.4.0-SNAPSHOT.jar wasn't produced by this build.
...
$
```

**Comment by anuraaga** [comment]
@izeye Thanks for the tip! Made it easy to debug :)

**Comment by shakuzen** [comment]
Thank you both for the work on this.
