### ISSUE TITLE
Add metrics for OkHttp ConnectionPool

### ISSUE THREAD

**Issue by benhubert** [micrometer-metrics/micrometer#1875]
Hi! I think it would be helpful to have metrics for OkHttp's [ConnectionPool](https://square.github.io/okhttp/3.x/okhttp/okhttp3/ConnectionPool.html) usage.

I already implemented this for us and created a PR. I'm uncertain about some implementation details, see my comments in the PR for details.

**Comment by jkschneider** [comment]
@benhubert Would you like to open a PR with this implementation? Seems like you've got it working...

**Comment by benhubert** [comment]
Well, that was my intention, but seems that I forgot to open the PR. Thanks for your hint.
Now it's ready for review: https://github.com/micrometer-metrics/micrometer/pull/2066
