### ISSUE TITLE
Caffeine binder uses Gauge/TimeGauge for cumulative measures.

### ISSUE THREAD

**Issue by john-karp** [micrometer-metrics/micrometer#1880]
A couple of the metrics exposed by Caffeine are cumulative, so they should be wrapped accordingly, instead of using Gauge/TimeGauge.

* `cache.eviction.weight`/`evictionWeight()` should use FunctionCounter instead of Gauge.
* `cache.load.duration`/`totalLoadTime()` should use FunctionTimer instead of TimeGauge.

When the binder was first merged, FunctionCounter/FunctionTimer weren't yet available:
https://github.com/micrometer-metrics/micrometer/pull/78#issuecomment-321640355

**Comment by jkschneider** [comment]
@john-karp Changed `cache.eviction.weight` to use a `FunctionCounter` as you suggested (thanks for the reminder!). Unfortunately, there isn't anything we can do for `cache.load.duration`.

Caffeine offers the _throughput_ side of a presumptive `FunctionTimer` divided between successes and failures, but the duration is not split between successes and failures. So there is no way we can determine how much of the total duration to attribute to each.

**Comment by john-karp** [comment]
@jkschneider Yes, current definition of `cache.load.duration` includes both successes and failures, and as you point out, the Caffeine stats API doesn't have any way of separating them. So we're stuck on that part, short of a change to Caffeine.

However, that doesn't mean we can't use FunctionTimer to address the cumulative-ness:
```java
            FunctionTimer.builder("cache.load.duration", cache,
                    c -> c.stats().loadCount(),
                    c -> c.stats().totalLoadTime(), TimeUnit.NANOSECONDS)
                    .tags(getTagsWithCacheName())
                    .description("Cache loads, including both successes and failures")
                    .register(registry);
```

Caffeine docs:
`loadCount()`
> Returns the total number of times that Cache lookup methods attempted to load new values. This includes both successful load operations, as well as those that threw exceptions. This is defined as loadSuccessCount + loadFailureCount.

`totalLoadTime()`:
> Returns the total number of nanoseconds the cache has spent loading new values. This can be used to calculate the miss penalty. This value is increased every time loadSuccessCount or loadFailureCount is incremented.
