### ISSUE TITLE
MicrometerCollector does not work with CollectorRegistry filteredMetricFamilySamples(Set<String> includedNames)

### ISSUE THREAD

**Issue by wilkinsona** [micrometer-metrics/micrometer#1883]
When a `MicrometerCollector` is registered with `CollectorRegistry` with auto-describe enabled, `collect()` is called on the collector to get the collector's names. It returns an empty list which subsequently prevents the collector's samples from being included when calling `CollectorRegistry.filteredMetricsFamilySamples(Set<String> includedNames)`.

This behaviour became apparent while triaging a [Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/20371). Please see the issue for some further background and the use case for filtering while scraping [rather than at the meter registry](https://github.com/micrometer-metrics/micrometer/issues/1758#issuecomment-570483982).

**Comment by izeye** [comment]
@wilkinsona Thanks for the issue! I created https://github.com/micrometer-metrics/micrometer/pull/1885 to try to resolve this.
