### ISSUE TITLE
How to create metrics to HTTP requests that use CloseableHttpAsyncClient

### ISSUE THREAD

**Issue by candresrv** [micrometer-metrics/micrometer#1886]
Hi there, I see there is a Micrometer implementation to track the time that http requests take using MicrometerHttpRequestExecutor, but in my project I'm executing these requests using CloseableHttpAsyncClient:

i.e. :  myCloseableHttpAsyncClient.execute(req, cxt, callback);

Where:

- req is an HttpUriRequest obj
- cxt is a HttpClientContext obj

Is there any way to use Micrometer under this implementation? 

Thanks!

**Comment by jkschneider** [comment]
@candresrv Hopefully the method provided below will work for you with the new `MicrometerHttpClientInterceptor`. Please try out the 1.4.0 snapshot if you get a chance, as this release will be coming out soon.

```
CloseableHttpAsyncClient asyncClient() {
    MicrometerHttpClientInterceptor interceptor = new MicrometerHttpClientInterceptor(registry,
            request -> request.getRequestLine().getUri(),
            Tags.empty(),
            true);

    return HttpAsyncClients.custom()
            .addInterceptorFirst(interceptor.getRequestInterceptor())
            .addInterceptorLast(interceptor.getResponseInterceptor())
            .build();
}
```
