### ISSUE TITLE
How gauge gets data from hashmap?

### ISSUE THREAD

**Issue by Bobi-zhou** [micrometer-metrics/micrometer#1895]
I defined a hashmap<String,Integer> in my service,and data can be added to this hashmap by a api interface,but I don't kown what data will be added，for example ：
someone put：
ABC-->2
ACD-->3

another put:

BAC-->4
AASFFF->1
ACF-->1

I want to use gauge to collect this hashmap and output like this logic:

such as :
   the gauge name is: test
   the tag name is：t 

The tag value is the second character of the key of this hashmap，the guage value is sum of the hashmap value group by the tag value

so the prometheus metrics will out put:

test{t="B"} 2
test{t="C"} 4  //3+1
test{t="A"} 5 //4+1

how to define this gauge？

**Comment by izeye** [comment]
I'm not sure if there's any better way for it except just iterating the map and building gauges periodically or at a scrape time.

**Comment by poznachowski** [comment]
Haven't used it, but it may seem that `MultiGauge` could serve your purpose. Unfortunately, it's not documented well. Take a look here: https://github.com/micrometer-metrics/micrometer/issues/807

**Comment by jkschneider** [comment]
There's a book on Micrometer (plus other SRE topics) coming out soon. The Micrometer chapter of that book contains much more detail than in the current docs and this chapter will replace the Micrometer docs that currently exists. Here is the `MultiGauge` snippet:

![image](https://user-images.githubusercontent.com/1697736/76907663-2ccc2b00-687d-11ea-8514-7ac9d8c789e4.png)
