### ISSUE TITLE
InfluxNamingConventions should allow the tag value "time"

### ISSUE THREAD

**Issue by sfitts** [micrometer-metrics/micrometer#1902]
When attempting to write a tag with the value "time", you get an exception from `InfluxNamingConventions.tagValue`.  This is too restrictive.  The current version (1.7) of Influx allows the use of `time` as a tag value, just not as a tag key.  See https://docs.influxdata.com/influxdb/v1.7/query_language/spec/#keywords.

**Comment by izeye** [comment]
@sfitts Thanks for the report!

Looking at the inline comments, it seems to be there accidentally. I created https://github.com/micrometer-metrics/micrometer/pull/1903 to try to resolve this.

**Comment by shakuzen** [comment]
@sfitts Thank you for reporting this and sorry for the inconvenience. @izeye's fix for this will be included in the upcoming 1.1.11 release (and merged forward for the next 1.3.x and 1.4.0 release).
