### ISSUE TITLE
Remove configuring Elasticsearch index type

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1906]
As a note for future planning, once we no longer support Elasticsearch versions less than 7, we should remove this configuration option.

Based on Elasticsearch's published EOL schedule, it looks like that will be sometime around the end of this year: https://www.elastic.co/support/eol

> Elasticsearch | EOL date | Maintained until
> -- | -- | --
> 6.8.x | 2020-11-20 | 8.0.0

_Originally posted by @shakuzen in https://github.com/micrometer-metrics/micrometer/issues/1891#issuecomment-597086693_

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer/pull/2361 to try to resolve this.
