### ISSUE TITLE
Metrics not written to Stackdriver when using resource type other than global

### ISSUE THREAD

**Issue by deanorderly** [micrometer-metrics/micrometer#1907]
Please read Tom's post on down to my post in the previous reported bug which was support more resource types and while we can set another one, all writing of metrics then fails to GCP.

According to the [current](https://cloud.google.com/monitoring/custom-metrics/creating-metrics#which-resource) docs for Stackdriver Monitoring only these resource types support custom metrics:

- [aws_ec2_instance](https://cloud.google.com/monitoring/api/resources#tag_aws_ec2_instance)
- [dataflow_job](https://cloud.google.com/monitoring/api/resources#tag_dataflow_job)
- [gce_instance](https://cloud.google.com/monitoring/api/resources#tag_gce_instance)
- [gke_container](https://cloud.google.com/monitoring/api/resources#tag_gke_container)
- [generic_node](https://cloud.google.com/monitoring/api/resources#tag_generic_node)
- [generic_task](https://cloud.google.com/monitoring/api/resources#tag_generic_task)
- [global](https://cloud.google.com/monitoring/api/resources#tag_global)
- [k8s_cluster](https://cloud.google.com/monitoring/api/resources#tag_k8s_cluster)
- [k8s_container](https://cloud.google.com/monitoring/api/resources#tag_k8s_container)
- [k8s_node](https://cloud.google.com/monitoring/api/resources#tag_k8s_node)
- [k8s_pod](https://cloud.google.com/monitoring/api/resources#tag_k8s_pod)

_Each_ of these resource types has different requirements for the labels provided. Currently only the projectId is added as a label which is only valid for the `global` resource type. The documentation even recommends _not_ to use `global`

> Use this resource when no other resource type is suitable. For most use cases, generic_node or generic_task are better choices than global.

Configuring the registry for any other resource type results in errors buried in Stackdriver logs that look like: 
```
i.g.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: The set of resource labels is incomplete. Missing labels: (location namespace node_id).: timeSeries[0]
```
This could also be contributing a contributing factor for #1001 as the `MetricServiceClient` fails silently and just writes a log to Stackdriver. 

Updating the `StackdriverMeterRegistry` where it creates the `MonitoredResource` to include the required labels for each resource type will allow for metrics to be associated with these other resource types.

https://github.com/micrometer-metrics/micrometer/blob/6d615c4af01dcc8bf9e9b4d64c5bce7aba23b444/implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver/StackdriverMeterRegistry.java#L338-L341

@jkschneider - if you're able to provide some guidance about pulling metadata from the Google Cloud compute metadata client I'd be happy to attempt a PR

_Originally posted by @tomwscott in https://github.com/micrometer-metrics/micrometer/issues/1003#issuecomment-556118415_

**Comment by deanorderly** [comment]
oh shoot, I found out there is a change on master like this but it's not released in 1.3.6

                    .setResource(MonitoredResource.newBuilder()
                            .setType(config.resourceType())
                            .putLabels("project_id", config.projectId())
                            .putAllLabels(config.resourceLabels())
                            .build())

:(. 

When does this go out and get released?

**Comment by deanorderly** [comment]
hmm, digging further, I see this landed on Mar. 7th on master but I the 1.3.6-SNAPSHOT does not contain this fix from Mar. 16th....how is that possible.  I have the line in my gradle

    compile group: 'io.micrometer', name: 'micrometer-registry-stackdriver', version: '1.3.6-SNAPSHOT'
    compile group: 'io.micrometer', name: 'micrometer-core', version: '1.3.6-SNAPSHOT'

along with the maven repo from
https://repo.spring.io/libs-snapshot

not quite sure how to get the fix and test it out.

**Comment by deanorderly** [comment]
Finally found out that 1.4.0-SNAPSHOT does have the fix BUT for some reason, no metrics show up.  Only global can be used for some reason.  Does anyone have a working config?  Mine was this from cloudrun which doesn't seem to work....

	private static class OurGoogleConfig implements StackdriverConfig {
		@Override
		public String projectId() {
			return "ourproject-id";
		}
		@Override
		public String get(String key) {
			return null;
		}
		@Override
		public String resourceType() {
			return "generic_task";
		}

		@Override
		public Map<String, String> resourceLabels() {
			Map<String, String> map = new HashMap<>();
			map.put("namespace", "staging_tx");
			map.put("job", "nothing");
			map.put("task_id", "fillWithInstanceId");
			map.put("location", "fillWithZone");
			return map;
		}
	};

**Comment by Alos** [comment]
I too have the same issue. I upgraded to `1.4.0-SNAPSHOT` and the error is gone, no metrics can be found tho.

**Comment by shakuzen** [comment]
Thank you for trying out snapshots and reporting this issue. We'll have to figure out why metrics are failing to be written. Could you try to turn on more logging? I will also try to investigate after finishing the 1.4 release.

**Comment by deanorderly** [comment]
Sorry, circling back.  We got it working.  Ok, you MUST fill with zone, MUST fill with UUID.random().toString for your instance id (task_id).  you MUST fill the job with 'revision_name'

The reason is there is a conflict on reporting to the same location in the same minute from different instances.  

this fixes it EXCEPT we ran into one more issue in that is hurting us bad(at least in google's monitoring set).  This is hard coded string and it's very important to set it to the cluster_name for each cluster or you end up with ALL your server metrics for ALL servers in the completion window which is very frustrating...

new StringBuilder("custom.googleapis.com/").append(getConventionName(id));

Can we move that "custom.googleapis.com/" into the configuration object default method of metricPrefix() or something like that?

(I guess it's a separate issue but it's a very quick change, should we do a pull request or can someone slam that into master so we can get a snapshot friday or monday?)

It's much appreciated.

We are going to be adding micrometer to the platform 
https://github.com/deanhiller/webpieces

thanks,
Dean

**Comment by deanorderly** [comment]
For completeness, in cloud run, this is what we do now

			String projectId = MetadataConfig.getProjectId();
			String service = System.getenv("K_SERVICE");
			String revisionName = System.getenv("K_REVISION");
			String config = System.getenv("K_CONFIGURATION");
			String zone = MetadataConfig.getZone();

			String instanceId = UUID.randomUUID().toString();
			Map<String, String> map = new HashMap<>();
			map.put("namespace", service);
			map.put("job", instanceId);
			map.put("task_id", revisionName);
			map.put("location", zone);

and that map is passed back in our config object like so...

	private static class OurGoogleConfig implements StackdriverConfig {

		private String projectId;
		private Map<String, String> resourceLabels;

		public OurGoogleConfig(String projectId, Map<String, String> resourceLabels) {
			this.projectId = projectId;
			this.resourceLabels = resourceLabels;
		}

		@Override
		public String projectId() {
			return projectId;
		}
		@Override
		public String get(String key) {
			return null;
		}
		@Override
		public String resourceType() {
			return "generic_task";
		}

		@Override
		public Map<String, String> resourceLabels() {
			//they call this EVERY time, so save on memory by only passing the same
			//map every time instead of re-creating it...
			return resourceLabels;
		}
	};

**Comment by deanorderly** [comment]
you can add these to your documentation though we do need a 

     public String metricPrefix() default: "custom.googleapis.com/" in the config next like I mention above.

**Comment by Alos** [comment]
Adding these values to the map did not work. It appears that when running in GKE it these caused issues like:

```INVALID_ARGUMENT: One or more TimeSeries could not be written: Unrecognized resource label: namespace: timeSeries[0-73]```

**Comment by deanorderly** [comment]
@Alos you are missing this...

	@Override
	public String resourceType() {
		return "generic_task";
	}

namespace only works if your resourceType is generic_task.  There are others you can choose as well(not many and not one for cloud run yet).

**Comment by Alos** [comment]
Oh! That works! I can now see some of the metrics! Thanks!

**Comment by deanorderly** [comment]
One more thing @Alos .  you will also want to override the prefix with the name of your cloud run service as I allude to above(of course, need the override in first)!!!  if you don't early on, it's hard to change later and metrics of ALL your services will be displayed which is really really annoying especially when deploying a new server with very little metrics.

It's very hard to move metrics later as the whole team learns the locations and switching them is a huge tax on a team so do it early on.

**Comment by shakuzen** [comment]
Glad you both got this working. @deanorderly could you open a separate issue (or pull request) about making what you need more configurable? Thanks.
