### ISSUE TITLE
Swallowing exceptions flag to turn that off?

### ISSUE THREAD

**Issue by deanorderly** [micrometer-metrics/micrometer#1910]
Swallowing exceptions(and just logging and not monitoring it) is generally not a good practice since stuff gets unnnoticed.  In fact, if using a ThreadPool, throw it into the thread and my applications DefaultUncaughtExceptionHandler will be called and I can deal and monitor failures in the system.

by swallowing it, things can go unnoticced.  I am wondering if we could at least have a flag to log or throw exception depending on the exception.

I realize that you may perhaps have a requirement that if you fail in adding a metric, you don't want to impact the business logic of the system.  In my case, we prefer that.  We want everything working 100% and if it doesn't, we want it to impact so we get operations on it ASAP to solve.  visibility is more important than hiding.  We found the more hiding went on, the more we had unknown errors and bugs happening impacting our systems.  We solved this with the "FAIL FAST" mantra and converted all developers to always throw up the stack 'except' in very special circumstances.

ie. a flag so we can get back to fail fast would be great!!!

thanks,
Dean

**Comment by checketts** [comment]
Can you add some context and or sample code where you see exceptions being swallowed? I'm not aware of timers swallowing exceptions.

Perhaps you are seeing that with Gauges?

**Comment by deanorderly** [comment]
Sorry for the delay.  From what I can tell, it's every minute when metric updates are tried and we have this line such that if you throw into ExecutorService, I am pretty sure all those standard libs call into the exceptionhandler if you did something like what webpieces does...

		Thread.setDefaultUncaughtExceptionHandler(new WebpiecesExceptionHandler());

so that the handler is notified of something being wrong.

specifically, I am using the google stackdriver meter registery and if you get stuff wrong, google throws exceptions.

**Comment by deanorderly** [comment]
oh, and sorry for the delay on this.  I have been slammed.

**Comment by deanorderly** [comment]
try {
                CreateTimeSeriesRequest request = CreateTimeSeriesRequest.newBuilder()
                        .setName("projects/" + config.projectId())
                        .addAllTimeSeries(partition)
                        .build();

                logger.trace("publishing batch to Stackdriver:{}{}", System.lineSeparator(), request);

                client.createTimeSeries(request);
                logger.debug("successfully sent {} TimeSeries to Stackdriver", partition.size());
            } catch (ApiException e) {
                logger.warn("failed to send metrics to Stackdriver", e);
            }

exception swallowed.,

**Comment by deanorderly** [comment]
try {
            publish();
        } catch (Throwable e) {
            logger.warn("Unexpected exception thrown while publishing metrics for " + this.getClass().getSimpleName(), e);
        }

swallowed

**Comment by checketts** [comment]
Both these cases are Micrometer's internals sending metrics to external services, right? The term here isn't `swallowing` but rather that it is recovering from the exception so it can continue processing. 

> Error swallowing is the practice of catching an error or exception, and then continuing without logging, processing, or reporting the error to other parts of the software. 

(See https://en.wikipedia.org/wiki/Error_hiding) Not trying to be pedantic, just want to clarify so we are talking about the same thing.

If the code just rethrew the exception, Micrometer's processigng would break.

Perhaps you want a way to register some sort of error listener?

**Comment by deanorderly** [comment]
@checketts uh, on terminology, sure!  You guys are using ScheduledExecutorService, correct?  you can throw back to it's threadpool  and it will invoke the error listener I put above.  It will not break or cause the thread to die.  Only Timer.java does that (it was written wrong and dies if you throw into it).

Unless I am misremembering.  I wanted to re-test that but I am slammed right now.  we are trying to help out in covid in a few ways including covid19.orderlyhealth.com and scrambling to help health care companies.

ps. I believe ExecutorService does the same thing.  (ie. the pattern is already in place but people don't seem to be using it and instead add error listeners to their apis which seems kind of weird when there is already a standard).

**Comment by jkschneider** [comment]
> you can throw back to it's threadpool and it will invoke the error listener I put above.

If this is true, I can certainly imagine rethrowing exceptions from publish failures. Would want to see what happens in frameworks, etc.

**Comment by tomilchik** [comment]
This thread looks old - but it is the best match to a very similar io.micrometer behavior that I'm seeing.
Using io.micrometer:micrometer-tracing:1.0.2 with Java 17 / SpB3.

Code throws at some point (missing JDK (font library).

1) with tracing disabled:
* exception is caught by code and logged with full stack trace (as expected) including the missing library name - i.e. all detaisl needed for troubleshootiing.
2) with tracing enabled
* io.micrometer logs an exception "cannot invoke io.micrometer.tracing.CurrentTraceContext$Scope.close() because the return value of io.micrometer.tracing.handler.TracingObservationHandler$TracingContext.getScope() is null"
* stack trace does not include any other root cause - all of the stack looks to be in tracing space
* the _partial_ (very abbreviated) stack trace of the applicaiton exception is added to the span Logs and is only visible in Jaeger UI.

Whatever terminology might be used to describe this (I see above that "swallowing" did not go down well; a non-existent term "exception redirection" might work) - this is quite different from what Sleuth/Zipkin used to do - which is very side-car/observer not interfering with exception propagation.

Is there anything I can do in my code (configuration, etc.) to change the current behavior?

**Comment by jonatan-ivanov** [comment]
@tomilchik I think those are unrelated and the NPE was fixed: https://github.com/micrometer-metrics/tracing/issues/179 (should be released on Monday). Could you please try the latest snapshot to check if the issue still persists? If so, could you please open an issue for [Micrometer Tracing](https://github.com/micrometer-metrics/tracing/issues/new)?
