### ISSUE TITLE
Memory pressure binder

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#1911]
The meter binder provides methods to access measurements of low pool memory and heavy GC overhead as described in [TeamCity's Memory Monitor](https://www.jetbrains.com/help/teamcity/teamcity-memory-monitor.html).

It determines the percent of time spent in GC by computing a moving sum of the times of individual GC events (excluding concurrent phase GC events) divided by the moving interval. Sums are retained in a ring buffer whose elements expire at this predetermined interval.

To determine the accuracy of this method of determining GC overhead, the results emitted from the monitor were compared against JProfiler's notion of percent time spent in GC, and they were converged on roughly the same value, as seen below:

![image](https://user-images.githubusercontent.com/1697736/73699355-91f30500-46b1-11ea-8835-b5059442ac61.png)

**Comment by checketts** [comment]
Very cool! Thanks for this addition!

**Comment by shakuzen** [comment]
I've polished in 5f4b201e4e864d05b69b0f1b376c1e14fcec2894 renaming the one metric to `jvm.memory.usage.after.gc` to more closely align with the existing JVM memory metric names. Also that it is heap memory is already expressed via the tag on it.
