### ISSUE TITLE
404 Metrics end up with 'NOT_FOUND' uri tag

### ISSUE THREAD

**Issue by codemedian** [micrometer-metrics/micrometer#1912]
Hi everyone,

I'm using this module quite heavily and I believe there is an issue with URL mapping for 404/301 errors. In my dashboards I have a request errors widget, and all my 404 errors show up with `NOT_FOUND` as the URI.

Been digging around the code a little and either I'm misunderstanding how this bit works, or it's wrong.

Looking at the `time` method in OkHttpMetricsEventListener.java 
```java
    private void time(CallState state) {
        Request request = state.request;
        boolean requestAvailable = request != null;

        String uri = state.response != null && (state.response.code() == 404 || state.response.code() == 301)
                ? "NOT_FOUND" : urlMapper.apply(request);

        Tags requestTags = requestAvailable ? getRequestTags(request) : Tags.empty();

        Iterable<Tag> tags = Tags.concat(extraTags, Tags.of(
            "method", requestAvailable ? request.method() : "UNKNOWN",
            "uri", requestAvailable ? uri : "UNKNOWN",
            "status", getStatusMessage(state.response, state.exception),
            "host", requestAvailable ? request.url().host() : "UNKNOWN"
        )).and(requestTags);

        Timer.builder(this.requestsMetricName)
            .tags(tags)
            .description("Timer of OkHttp operation")
            .register(registry)
            .record(registry.config().clock().monotonicTime() - state.startTime, TimeUnit.NANOSECONDS);
    }
```
It appears to me that the uri is always set to `NOT_FOUND` for 404 and 301 errors, regardless of whether the request was available (I think that indicates timeout) or not. The change was made in #1401 and has been in for a while though.

**Comment by jkschneider** [comment]
@codemedian Indeed mapping 404 and 301 to `NOT_FOUND` is an important anti-DOS preventative for your monitoring system. Without it a malicious user could generate a large number of unroutable paths, overhwelming your monitoring system with unique tag values.

This said, I do think we should permit customization. In c630cde, a new `tag` method was added that allows you to provide a set of request/response context-specific tags. For backwards compatibility, I think it's best that we maintain the `NOT_FOUND` behavior on `uri`, but with the new method you can add another tag key like `real.uri` that preserves the original route if you'd like:

```
OkHttpClient client = new OkHttpClient.Builder()
                .eventListener(OkHttpMetricsEventListener.builder(registry, "okhttp.requests")
                        .tag((req, res) -> Tag.of("real.uri", req.url().encodedPath()))
                        .build())
                .build();
```

**Comment by igorng** [comment]
Hello,
This is a great feature! I was about to ask the ability to extend OkHttpMetricsEventListener, or at least a way to add context specific tags, as I wanted to have dimension like Exception and stuff (same dimensions as spring boot default on web clients ). 
When will this feature be released?

**Comment by shakuzen** [comment]
> When will this feature be released?

This is marked for the [1.5.0 milestone](https://github.com/micrometer-metrics/micrometer/milestone/57), which has a tentative release date listed in the milestone page.
