### ISSUE TITLE
V1.4.0 was pushed to repo.spring.io

### ISSUE THREAD

**Issue by delta50** [micrometer-metrics/micrometer#1923]
There seems to be a V1.4.0 of micrometer-registry-prometheus on the spring maven repo. It was pushed up a couple days ago. Since there is no V1.4.0 tagged release, I feel like this might have been a mistake. https://repo.spring.io/snapshot/io/micrometer/micrometer-registry-prometheus/

**Comment by shakuzen** [comment]
There may have been an issue before that got cleared up, but I'm not seeing one anymore. Could you confirm if there's still an issue @delta50 ?

**Comment by delta50** [comment]
Yes, there is still an artifact in the spring repo for version 1.4.0
[https://repo.spring.io/snapshot/io/micrometer/micrometer-registry-prometheus/1.4.0-SNAPSHOT/](https://repo.spring.io/snapshot/io/micrometer/micrometer-registry-prometheus/1.4.0-SNAPSHOT/)

**Comment by shakuzen** [comment]
That's a snapshot version in the snapshot repository. That is to be expected.
