### ISSUE TITLE
Running out of memory over time, how to unregister metrics?

### ISSUE THREAD

**Issue by deanorderly** [micrometer-metrics/micrometer#1929]
We attach metrics to each socket that comes in so we create a new guage for to measure backpressure for each socket individually.  As we create these and sockets come and go, we don't seem to be able to unregister the metrics for that socket that is no longer there.  This eats up memory.

ps. I love this project!  way better and easier than opencensus which is what we started with!!!

**Comment by shakuzen** [comment]
`MeterRegistry` defines a `remove` method that you can use to remove meters that have been registered.
