### ISSUE TITLE
Add configuration option to `SimpleMeterRegistry` to govern whether it is step-based or not

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#193]
cc / @jvalkeal
cc / @checketts

**Comment by jvalkeal** [comment]
Yeah, this would be a good thing as it then gives user a choice for one way or the other. I assume this is the impl how boot exposes its metrics via actuators. In a perfect world you could define what specific metrics are step based or not, but I'm not sure how feasible it'd be to implement a feature like that. If you need to query metrics from boot to export those to your legacy monitoring system, then it'd be beneficial to choose it per metric.

**Comment by jkschneider** [comment]
@jvalkeal We support quite a few "legacy" monitoring systems and are not afraid of adding others. I don't want there to be any reason to scrape boot to export to a monitoring system. Let me know if you see obvious gaps in implementations.

**Comment by jkschneider** [comment]
@jvalkeal We'll make cumulative mode the default. Be aware:

1. Still not safe to scrape the actuator endpoint (and shouldn't be necessary)
2. I'd still like to hear a concrete case where a counter should always be in cumulative mode, irrespective of the monitoring system. There may be such a need that I just can't imagine. I have a history of changing my mind on this -- re: objected to a `TimeGauge` for quite a while.

**Comment by checketts** [comment]
Thanks @jkschneider at the very least it makes the unit tests simpler. The RestTemplate config one was giving me grief (worked when ran alone, but failed when ran with others)

**Comment by jkschneider** [comment]
Yep, I agree. The unit test requirements were a bad surprise I think.

**Comment by jvalkeal** [comment]
I'm referencing to case I used with cumulative `errorCount`. Need to point to old hyperic docs [hyperic alert](http://pubs.vmware.com/vfabricHyperic50/index.jsp?topic=/com.vmware.vfabric.hyperic.5.0/ui-Alert.New.html)

Metrics were imported to hyperic via agents and pulled from apps(or other systems) using various ways(http, jmx, etc). That doc mentions `Fire upon change in metric value` which is my case was backed by a real increasing counter. In this case metrics were collected in intervals(1 min, 5min, etc). If you pull out something from an app(assume boot actuator metrics), singe increasing counter value would get lost after 10 seconds. You could only alert based on changing value if you magically pull metric within that 10 second window as after that rate is zero again.

It was always a case by case whether you wanted to create some alerts/actions by a counter or a rate. Sometimes raw counter was better, sometimes rate was a better choice. It's always what end user wants to use, not something we force feed without giving any options to customise how things work.
