### ISSUE TITLE
Migration from Dropwizard Metrics to Micrometer

### ISSUE THREAD

**Issue by JUGI4U** [micrometer-metrics/micrometer#1935]
Hello, 
I have to migrate our application metrcis system from Dropwizard to Micrometer.
Although I have read through many articles, I still don't know exactly how to replace these methods:

com.codahale.metrics.Meter.getMeanRate / getOneMinuteRate / getFiveMinuteRate / getFifteenMinuteRate
and
com.codahale.metrics.Snapshot.getMedian / get95thPercentile / getStdDev

We need these values because we've made extensive use of Dropwizard's ScheduledReporter.

Any help is very appreciated! Thanks.

**Comment by checketts** [comment]
Can you please add more details around what you need those methods for?

Many modern metrics systems like Prometheus make those types of information available via queries in the metrics backend, instead of pre-calculating those numbers. (So they don't even exit in Micrometer).

What is your intended backend? Micrometer can be a facade in front of Dropwizard metrics, so you could begin using Micrometer and keep reporting with Dropwizard.

**Comment by JUGI4U** [comment]
We use Dropwizards CSV and JMX reporter. 
CSV files are used by various internal development tools as data source for further processing.
So we need to keep these files as they are, their structure and contents.
These files are kind of metrics backend for us. It's just another target to publish data to.
Maybe we will later add some other metrics backend(s) like Prometheus too, but for now this is not planned.

I actually used the Dropwizard integration io.micrometer.core.instrument.dropwizard and it worked fine. There was a DropwizardMeterRegistry that kept all of our Dropwizard metrics and CSV files were written like before.
But to be clean in my code, I wanted completely migrate to Micrometer and remove all Dropwizard stuff.

**Comment by checketts** [comment]
If you are relying on Dropwizard CSV/JMX you can keep those. Micrometer doesn't provide a way to generate those (or rather you could re-invent it with s `SimpleMeterRegistry`, but I wouldn't recommend it)

Micrometer provides a `CompositeMeterRegistry` that you can wire in your DropWizard integration to so you could investigate Prometheus or other alternatives, without having to remove any Dropwizard integrations until you have a replacement.

**Comment by JUGI4U** [comment]
Yes as I said, the Dropwizard integration worked fine. 
Metrics.globalRegistry kept a nested DropwizardMeterRegistry that held all metrics I had configured, also JMX integration and CSV creation worked as before in DW standalone version.

But there's one thing I don't completely understand.
If I have registered meters to a registry that is part of a composite registry, are these meters or their values also published to other metrics backends?
As far as I understood, this holds for meters registered at the highest level, e.g. Metrics.globalRegistry.
But what about meters registered at a lower level, e.g in a nested registry?

**Comment by checketts** [comment]
Meters registered at a lower level(ie directly against a child registry) won't automatically appear in other registries. You want to go through the composite registry to ensure meters are registered in all children registries.

**Comment by mychaow** [comment]
I think support com.codahale.metrics.Meter.getMeanRate / getOneMinuteRate / getFiveMinuteRate / getFifteenMinuteRate is more flexible.

If the backend metrics system does not support them, we could push data to them. If they do support, the user do not need to use Meter. But now, the user have to calculate them by themselves.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
