### ISSUE TITLE
OkHttpMetricsEventListener leaks memory when used with OkHttpClient caching

### ISSUE THREAD

**Issue by ahatzz11** [micrometer-metrics/micrometer#1937]
I have recently been using Retrofit to make API calls, and two of the features we have are request metrics and caching requests. For Caching we use [okhttp3.Cache](https://github.com/square/okhttp/blob/okhttp_3.14.x/okhttp/src/main/java/okhttp3/Cache.java). Since we heavily use Spring Boot 2.x, micrometer was an easy choice for metrics and implementation was easy with the `OkHttpMetricsEventListener`. 

## The Problem

Over time we have seen instances of our applications run out of memory and die / stop responding. We narrowed this down to the combination of metrics and caching when making API calls. 

## The Cause

The `OkHttpMetricsEventListener` maintains a map of all `Call`s, and it seems that calls are removed in two ways:

1. Call ends in Failure - which happens if an IOException is thrown
2. The response headers are read

When caching is used, neither of these conditions happen - there is no error thrown, and the response headers aren't read because a network call is never made.

We tracked this down to `OkHttpMetricsEventListener` not implementing the `EventListener.callEnd()` method, which is what would get called when a cache hit happens in OkHttp. Because this isn't implemented, the `Call`s end up living in the `callState` map and don't become eligible for garbage collection. Over time this fills up the available memory and the JVM dies.

## The Solution

Implementing the `callEnd()` method in the `OkHttpMetricsEventListener` to remove the `Call` from the `callState` map for requests that don't fall into one of the scenarios listed above.

Fixed by #1938 

### JVM Heap size

![image](https://user-images.githubusercontent.com/6256032/77476453-9fdb2180-6de8-11ea-8043-dcb9af08eef7.png)
before fix: **yellow** | after fix: **green**

![image](https://user-images.githubusercontent.com/6256032/77476416-8d60e800-6de8-11ea-85b5-cf0ab531e140.png)
before fix: **yellow** | after fix: **green**

### Response Times

![image](https://user-images.githubusercontent.com/6256032/77475058-335f2300-6de6-11ea-8d43-a42732dcad9d.png)
before fix: **yellow** | after fix: **green**

### Heap Analysis

![image](https://user-images.githubusercontent.com/6256032/77474534-4ae9dc00-6de5-11ea-94e7-fc6158709c81.png)

![image](https://user-images.githubusercontent.com/6256032/77474557-550bda80-6de5-11ea-8279-da58e378b95d.png)

**Comment by shakuzen** [comment]
Thank you for the detailed bug report, analysis, and pull request. Sorry for the trouble with the memory leak. We'll get your patch merged and released soon.

**Comment by shakuzen** [comment]
For the release notes: this fix will only work with okhttp 3.14.2 and newer versions - users affected by this bug should check the version of okhttp they're using when upgrading Micrometer to get this fix. See https://github.com/micrometer-metrics/micrometer/pull/1938#discussion_r397598389 for details.
