### ISSUE TITLE
Make step registries use `StepClock`

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#198]
Stumbled upon by @nebhale.

**Comment by nebhale** [comment]
Is the plan that you will wrap the `Clock` that is passed into the constructor so that the external callers don't need to do the wrapping themselves?

**Comment by jkschneider** [comment]
I think that sounds right.

**Comment by jkschneider** [comment]
Turns out this isn't even needed. Deleted `StepClock` entirely.
