### ISSUE TITLE
DistributionSummary computing wrong percentiles

### ISSUE THREAD

**Issue by azelenkovas** [micrometer-metrics/micrometer#1997]
Hello

I'm trying to get percentiles for a metric and I'm getting weird results. I understand that percentiles are computed differently depending on implementation, but these are way off. For instance, the max value of the distribution is 9 but the 90th percentile and above are reporting 15. How are these percentiles being calculated? Thanks.

The test:

```
import io.micrometer.core.instrument.DistributionSummary;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.distribution.HistogramSnapshot;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.util.*;
import java.util.stream.IntStream;

import static com.google.common.math.Quantiles.percentiles;
import static org.junit.Assert.assertEquals;

public class DistributionSummaryTest {

    @Test
    public void distributionSummaryTest() {
        MeterRegistry meterRegistry = new SimpleMeterRegistry();
        DistributionSummary distributionSummary =
                DistributionSummary.builder("name_size")
                        .percentilePrecision(0)
                        .distributionStatisticBufferLength(1000)
                        .distributionStatisticExpiry(Duration.ofHours(1))
                        .publishPercentiles(0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99, 1.0)
                        .register(meterRegistry);

        List<Integer> values = new ArrayList<>();
        IntStream.range(1,10).forEach(n -> IntStream.range(0, 100).forEach(m -> values.add(n)));
        values.stream().forEach(n -> distributionSummary.record(n));

        HistogramSnapshot snapshot = distributionSummary.takeSnapshot();
        System.out.println("MEAN: " + snapshot.mean());
        System.out.println("MAX: " + snapshot.max());
        System.out.println("COUNT: " + snapshot.count());
        System.out.println("TOTAL: " + snapshot.total());

        Map<Integer, Double> guavaPercentiles = percentiles().indexes(10, 25, 50, 75, 90, 95, 99, 100).compute(values);

        Map<Integer, Double> micrometerPercentiles = new TreeMap<>();

        Arrays.stream(snapshot.percentileValues()).forEach(p -> {
            micrometerPercentiles.put(Integer.valueOf((int) (p.percentile() * 100)), p.value());
        });

        System.out.println("GUAVA PERCENTILES: " + guavaPercentiles);
        System.out.println("MICROMETER PERCENTILES: " + micrometerPercentiles);

        assertEquals(guavaPercentiles, micrometerPercentiles);
    }
}
```

The result:
MEAN: 5.0
MAX: 9.0
COUNT: 900
TOTAL: 4500.0
GUAVA PERCENTILES: {10=1.0, 25=3.0, 50=5.0, 75=7.0, 90=9.0, 95=9.0, 99=9.0, 100=9.0}
MICROMETER PERCENTILES: {10=1.0, 25=3.0, 50=7.0, 75=7.0, 90=15.0, 95=15.0, 99=15.0, 100=15.0}

java.lang.AssertionError: expected:<{10=1.0, 25=3.0, 50=5.0, 75=7.0, 90=9.0, 95=9.0, 99=9.0, 100=9.0}> but was:<{10=1.0, 25=3.0, 50=7.0, 75=7.0, 90=15.0, 95=15.0, 99=15.0, 100=15.0}>
Expected :{10=1.0, 25=3.0, 50=5.0, 75=7.0, 90=9.0, 95=9.0, 99=9.0, 100=9.0}
Actual   :{10=1.0, 25=3.0, 50=7.0, 75=7.0, 90=15.0, 95=15.0, 99=15.0, 100=15.0}

**Comment by jkschneider** [comment]
@azelenkovas Under the covers, Micrometer uses [HdrHistogram](http://hdrhistogram.org/) to compute percentiles. HdrHistogram gives us the opportunity tradeoff computational complexity for accuracy. In your code sample, by setting percentile precision down to 0, you've effectively chosen the most computationally cheap approximation and in the process sort of crippled accuracy. 

By default Micrometer uses a precision of 1, which yields this result (closer to but still computationally cheaper than Guava, which I think is computing the _true_ percentile?)

```
MEAN: 5.0
MAX: 9.0
COUNT: 900
TOTAL: 4500.0
GUAVA PERCENTILES: {10=1.0, 25=3.0, 50=5.0, 75=7.0, 90=9.0, 95=9.0, 99=9.0, 100=9.0}
MICROMETER PERCENTILES: {10=1.0, 25=3.0625, 50=5.1875, 75=7.1875, 90=9.4375, 95=9.4375, 99=9.4375, 100=9.4375}
```

Bumping it up to 2 gets you even closer:

```
MEAN: 5.0
MAX: 9.0
COUNT: 900
TOTAL: 4500.0
GUAVA PERCENTILES: {10=1.0, 25=3.0, 50=5.0, 75=7.0, 90=9.0, 95=9.0, 99=9.0, 100=9.0}
MICROMETER PERCENTILES: {10=1.0, 25=3.0078125, 50=5.0234375, 75=7.0234375, 90=9.0546875, 95=9.0546875, 99=9.0546875, 100=9.0546875}
```

There is a [bit in the docs](http://micrometer.io/docs/concepts#_memory_footprint_estimation_2) at least about memory footprint estimation for percentile approximations. We've put a _lot_ of thought into this tradeoff and hopefully have arrived at a reasonable place?
