### ISSUE TITLE
Incorrect sanitization of colons for datadogstatsd

### ISSUE THREAD

**Issue by klevy-toast** [micrometer-metrics/micrometer#1998]
It appears that this fix (https://github.com/micrometer-metrics/micrometer/issues/739 & https://github.com/micrometer-metrics/micrometer/commit/f18b6e03522318b136817b76154b493b28ae810a) removes _all_ colons from metric names _and_ tags. Datadog does actually support colons in metric tags, just not at the beginning or end -- see https://docs.datadoghq.com/tagging/

```
Tags must start with a letter and after that may contain the characters listed below:

    Alphanumerics
    Underscores
    Minuses
    Colons
    Periods
    Slashes

Other special characters are converted to underscores.

Note: A tag cannot end with a colon, for example tag:
```

We were able to rollback to version 1.0.5 in order to preserve our proper tagging names, and the metrics went through without issue.

**Comment by shakuzen** [comment]
That documentation unfortunately doesn't make very clear where it is talking about tag keys versus tag values, but I believe your request is to not sanitize colons (`:`) in tag values unless they are at the end of the tag value. Is that correct?

**Comment by klevy-toast** [comment]
A colon should also be sanitized at the beginning of the tag value (must start with a letter). Everything else is correct. Thank you!

**Comment by shakuzen** [comment]
Please try the latest snapshots containing this fix. It'll be in the upcoming 1.1.13, 1.3.8, 1.4.2, and 1.5.0.

**Comment by klevy-toast** [comment]
Thanks!
