### ISSUE TITLE
Change "sla" configuration options to "serviceLevelObjectives"

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#2001]
Service Level Agreement" is more formally the agreement between an engineering organization and the business. Service Level Objectives are set more conservatively than the SLA to provide some wiggle room while still satisfying the business requirement. SLOs are the threshold we intend to measure against, then.

**Comment by snicoll** [comment]
So we have an object with the `sla` term as well as a configuration namespace. What would be the recommendation? `serviceLevelObjectives` is quite mouthful and we don't do multiple words for groups.

**Comment by snicoll** [comment]
Thanks for the feedback Tommy. I've created an issue on our side to figure out what to do with the deprecation.
