### ISSUE TITLE
Improvements to LongTaskTimer (max, percentiles, histograms)

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#2005]
Currently a `LongTaskTimer` just ships two statistics: active task count and total duration of all active tasks. So when there is more than on active task, you can get an average of the durations of all active tasks, but there is no way to tell that one has been running for a really long time and others just started.

This improves `LongTaskTimer` to include:

- **max**. The longest active task duration
- **percentiles**. Specified on `LongTaskTimer.Builder` like you would for `Timer.Builder`.
- **histogram/serviceLevelObjectives**. Specified on `LongTaskTimer.Builder` like you would for `Timer.Builder`.

`LongTaskTimer.Builder` will start with a minimum expected value of 2 minutes and maximum expected value of 2 hours, both configurable as for `Timer.

**Comment by mattiasflodin** [comment]
IMO this PR should not have been accepted without javadoc on the newly added interface methods. I just upgraded and am unsure how to implement them, and the interface documentation gives no guidance. It wasn't until I came to this issue that I found a description of what max() should do.

**Comment by jkschneider** [comment]
@mattiasflodin Can you point out where the missing Javadoc is so it can be corrected?

![image](https://user-images.githubusercontent.com/1697736/81701741-6c0b9800-9438-11ea-9ef7-c583a95567d5.png)

**Comment by mattiasflodin** [comment]
I apologize for the noise. I realized after making this comment that IntelliJ had served me an auto-decompiled class file that doesn't contain the javadoc. Went here and deleted my comment but after updating the page I found you had already responded.

**Comment by jkschneider** [comment]
@mattiasflodin No worries! I do tend to be a bit sloppy about Javadocs from time to time as @izeye well knows ;)
