### ISSUE TITLE
Registry configuration validation

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#2011]
## Background

The need for stronger type-aware validation was raised in a discussion with @ebullient with respect to Quarkus' build-time validation of configuration.

Previously, there was an inconsistent set of validations happening across some registries and not others, primarily resulting in a `MissingRequiredConfigurationException` (unchecked) at constructor time.

Here we introduce stronger validation of registry configuration interfaces. A new incubating API exists in `io.micrometer.core.instrument.config.validate` to address this concern. Some high level details:

* `MeterRegistryConfig` now has a `Validated<?> validate()` method with a default implemenation that does no validation.
* `PushMeterRegistryConfig`, from which many other registry implementations extend validates all the properties common to push-based registries.
* `Validated` is a "sealed" class of sorts with specializations for `Valid`, `Invalid`, `None`, and `Either`. It contains many convenience methods for generating an initial valid or invalid signal, mapping them, flat mapping them, etc. Some examples included below.
* `MissingRequiredConfigurationException` has been deprecated in favor of the new `Validated` API.

Every Micrometer-provided registry implementation now performs validation at constructor time.

### Throwing a `ValidationException` when the configuration isn't valid

```java
DatadogConfig config = System::getProperty;
config.requireValid();
```

`requireValid()` is shorthand for `validate().orThrow()`.

### Retrieving a list of invalid configuration _without_ throwing any exceptions

```java
config.validate() // is an Iterable<Validated<?>>
```

There is a shorthand for retrieving just failures:

```java
List<Invalid<?>> failures = config.validate().failures();
```

`Invalid` has information about the type of problem, the property, the value it tested, a message describing the problem, and sometimes a `Throwable` that caused the invalidation.

Sometimes, you may wish to filter on a specific subset of invalid properties (such as those that were malformed as opposed to missing when doing build-time verification of properties where secrets aren't expected to be provided until runtime):

```java
config.validate().failures().stream()
  .filter(invalid -> !invalid.getReason().equals(InvalidReason.MISSING))
  ...
```

### A push based registry checking for a valid URI

```java
default String uri() {
   return getUrlString(this, "uri").orElse("http://localhost:8080/api/v1/datapoints");
 }
```

`getUrlString` is defined on `PropertyValidator` which contains many such methods. It returns a `Validated` object which has an `orElse` to retrieve either the valid value or some default.

```java
@Override
default Validated<?> validate() {
    return checkAll(this,
            c -> StepRegistryConfig.validate(c),
            checkRequired("uri", KairosConfig::uri)
    );
}
```

### A required secret

```java
default String apiToken() {
    return getSecret(this, "apiToken").required().get();
}
```

```java
@Override
default Validated<?> validate() {
    return checkAll(this,
            ...
            checkRequired("apiToken", AppOpticsConfig::apiToken),
    );
}
```

### A registry which has a numeric property which cannot be greater than some value

```java
@Override
default int batchSize() {
    return Math.min(getInteger(this, "batchSize").orElse(DEFAULT_BATCH_SIZE), MAX_BATCH_SIZE);
}
```

```java
@Override
default Validated<?> validate() {
    return checkAll(this,
            ...
            check("batchSize", AppOpticsConfig::batchSize)
                    .andThen(v -> v.invalidateWhen(b -> b > MAX_BATCH_SIZE, "cannot be greater than " + MAX_BATCH_SIZE))
    );
}
```

**Comment by snicoll** [comment]
@jkschneider unfortunately this is breaking the Spring Boot build. We are working on releasing RC1 next week and our plate is already quite full to have to deal with such last-minute change in behaviour, in particular so close from the release.

Is this really necessary in 1.5?

**Comment by shakuzen** [comment]
Reverting this for now so Boot's build can successfully run. See also #2013 for challenges adapting to these changes.
