### ISSUE TITLE
New configuration validation messages are misleading for values that must not be null

### ISSUE THREAD

**Issue by wilkinsona** [micrometer-metrics/micrometer#2013]
Looking at the latest 1.5 snapshots, I think that the new configuration validation messages are a bit misleading. For example, if I don't provide an API key or account ID for New Relic, the failure message is the following:

```
io.micrometer.core.instrument.config.validate.ValidationException: Multiple validation failures:
newrelic.apiKey='null' is required when publishing to Insights API
newrelic.accountId='null' is required when publishing to Insights API
```

This reads to me like both `newrelic.apiKey` and `newrelic.accountId` are required to be `null` if I want to publish to the Insights API.

**Comment by wilkinsona** [comment]
I was hoping to work around this in Boot's failure analyser for Micrometer configuration problems. Unfortunately, the various messages used to describe invalid configuration aren't written in a consistent manner so it's proving difficult.

For example, I can use the property, value, and message for the above to produce a message like this:

```
newrelic.apiKey was 'null' but is required when publishing to Insights API
```

Doing similar for an integer property does not work:

```
example.property was 'abc' but not an integer
```

In the case of a `null` value for a required property, the message describes the constraint (the property is required) whereas for an integer property the message describes the problem (the value was not an integer).

**Comment by jkschneider** [comment]
> This reads to me like both newrelic.apiKey and newrelic.accountId are required to be null if I want to publish to the Insights API.

Perhaps this can be improved. It's meaning to say `newrelic.apiKey` which is _currently null_ needs to not be null to publish.

**Comment by jkschneider** [comment]
All messages have been changed to be a complete sentence that reads in the _positive_ about what a value should be. No messages now say what a value _shouldn't_ be. For example:

```
example.property was 'abc' but must be an integer
```
