### ISSUE TITLE
JvmMemoryMetrics and others are not using strong references

### ISSUE THREAD

**Issue by ivenhov** [micrometer-metrics/micrometer#2014]
Hi
I was a little bit surprised to see that JvmMemotyMetrics does not use strong references
`
            Gauge.builder("jvm.buffer.count", bufferPoolBean, BufferPoolMXBean::getCount)
                    .tags(tagsWithId)
                    .description("An estimate of the number of buffers in the pool")
                    .baseUnit(BaseUnits.BUFFERS)
                    .register(registry);
`
[https://github.com/micrometer-metrics/micrometer/blob/0dc111d1f6d3aa288dda24ac0912cbb483f1da1e/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryMetrics.java](url)

Similar code is in JvmGcMetrics.

From what I understood references to created Gauges has to be kept with strong references somewhere to prevent them from GC. Yet, somehow Jvm memory reporting works OK for me :)

Clearly I'm missing something but if I understand it right DefaultGauge uses weak reference in its
constructor.
`
this.ref = new WeakReference<>(obj);
`

What am I missing?

Mu conclusions are based on doc:
`
https://micrometer.io/docs/concepts
`
9.3. Why is my Gauge reporting NaN or disappearing?

Regards
Daniel

**Comment by shakuzen** [comment]
As long as a strong reference is maintained somewhere, the object will not be garbage collected. It doesn't mean the MeterBinder itself needs to maintain a strong reference to it. We expect a reference to the MXBean to be maintained by the Java platform as that's where we're getting it from.

**Comment by ivenhov** [comment]
I've just realised this as I was editing my original question. 
I missed that and the docs is mentioning 'state object' not Gauge.
Thank you very much for your clarification.
