### ISSUE TITLE
Gauge metric publishing

### ISSUE THREAD

**Issue by v-yzakapko** [micrometer-metrics/micrometer#2017]
Hi all!

I used micrometer in project to publish gauge metrics to Prometheus. In version 1.1.3 metrics was publishing like : 
\#  HELP %name%  
\#  TYPE %name% gauge
%name%{%tags%,} %value%

but when we a version was changed to 1.3.6 metrics started looking like:

\#  HELP%project-name%%name%  
\#  TYPE%project-name%%name% gauge
%project-name%%name%{%tags%,} %value%

%project-name% - should not be in the output. So, my question is it possible to delete %project-name% from the output? Could somebody support me?

**Comment by shakuzen** [comment]
Could you please provide a sample project that shows this behavior difference when using the two versions? I'm not aware of a change that would make that happen.

**Comment by v-yzakapko** [comment]
Sorry, we found the reason, it was in our project.
