### ISSUE TITLE
Unbind KafkaClientMetrics in close()

### ISSUE THREAD

**Issue by garyrussell** [micrometer-metrics/micrometer#2018]
Consider keeping a reference to the registry from `bindTo()` and unbind (`remove()`) meters in `close()`.

For example, if a user creates a `KafkaClientMetrics` with a tag containing the `client-id` property of the client, recycling the client could cause a memory leak because the `client-id` may change from one instance to another.

While generally long-lived, typically, clients may come and go within a running application.

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer/pull/2424 to try to resolve this.
