### ISSUE TITLE
reactor-core version conflict between micrometer-registry-statsd and Spring Boot 1.5

### ISSUE THREAD

**Issue by pukkaone** [micrometer-metrics/micrometer#202]
## How to reproduce

- micrometer-registry-statsd 1.0.0-rc.3
- micrometer-spring-legacy 1.0.0-rc.3
- Spring Boot 1.5.8.RELEASE

Given a Spring Boot application defined by this pom.xml:

    <project
        xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
      <modelVersion>4.0.0</modelVersion>

      <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.8.RELEASE</version>
        <relativePath/> 
      </parent>

      <groupId>com.example</groupId>
      <artifactId>bug</artifactId>
      <version>0.0.1-SNAPSHOT</version>
      <packaging>jar</packaging>

      <name>bug</name>
      <description>Demo project for Spring Boot</description>

      <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <java.version>1.8</java.version>
        <micrometer.version>1.0.0-rc.3</micrometer.version>
      </properties>

      <dependencies>
        <dependency>
          <groupId>io.micrometer</groupId>
          <artifactId>micrometer-registry-statsd</artifactId>
          <version>${micrometer.version}</version>
        </dependency>
        <dependency>
          <groupId>io.micrometer</groupId>
          <artifactId>micrometer-spring-legacy</artifactId>
          <version>${micrometer.version}</version>
        </dependency>

        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-test</artifactId>
          <scope>test</scope>
        </dependency>
      </dependencies>

      <build>
        <plugins>
          <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>

    </project>

The application fails on start up with:

    java.lang.ClassNotFoundException: reactor.core.Disposable

## Cause

micrometer-registry-statsd depends on reactor-core [3.1.0.RELEASE](https://github.com/micrometer-metrics/micrometer/blob/v1.0.0-rc.3/implementations/micrometer-registry-statsd/build.gradle#L5) but Spring Boot 1.5.8 defines a dependency on reactor-core [2.0.8.RELEASE](https://github.com/spring-projects/spring-boot/blob/v1.5.8.RELEASE/spring-boot-dependencies/pom.xml#L143) and this is the version used.

## Work around

Set the Reactor version to use by adding this property to the properties in Spring Boot application pom.xml:

    <reactor.version>3.1.0.RELEASE</reactor.version>

but the consequence is any code depending on the other version will break.

## Possible resolution

Add a description of the work around to the documentation at http://micrometer.io/docs/ref/spring/1.5

**Comment by jkschneider** [comment]
Thanks. I checked with our resident reactor expert, and upgrading to 3.1.0 should cause no problem in Boot 1.5.

Updated the docs in https://github.com/micrometer-metrics/micrometer-docs/commit/b59f53f4af36cfef68360c0828b276e398316de5 to indicate the need to force up the version of Reactor in Boot 1.5.x when using StatsD.

**Comment by jkschneider** [comment]
The updated doc section is at http://micrometer.io/docs/ref/spring/1.5#_statsd

**Comment by foolin** [comment]
If use gradle, springboot 1.5  customize a managed version can solve this problem：
`ext['reactor.version'] = '3.1.0.RELEASE'`

docs: https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/html/howto-build.html#howto-customize-dependency-versions


Such as this:
```
dependencies {
    //compile ...
}

ext['reactor.version'] = '3.1.0.RELEASE'

```

**Comment by jkschneider** [comment]
@foolin We shade reactor in `micrometer-registry-statsd` now, so this shouldn't be necessary.
