### ISSUE TITLE
QUESTION: Force publishing metrics before application shut-down

### ISSUE THREAD

**Issue by tsiq-dhruv** [micrometer-metrics/micrometer#2021]
I am developing an application which publishes gauges via the `StatsdMeterRegistry`. This application uses version 1.1.0 of the `micrometer-registry-statsd` artefact. This application is short-lived. It sets a couple of gauges, and exits immediately.

The problem is that, because the gauge values are not published immediately when they are set, and because the application is short-lived, they don't get published in a majority of cases.

Is there a way to force all remaining metrics to be published before the application shuts down?

**Comment by jkschneider** [comment]
@tsiq-dhruv Yes, if you call `close()` on `StatsdMeterRegistry` it polls gauges one last time and pushes them.

**Comment by tsiq-dhruv** [comment]
@jkschneider unfortunately this doesn't seem to work for me. I added `registry.close()` as the very final call of my application, but the metrics still don't get published.

**Comment by tsiq-dhruv** [comment]
@jkschneider unfortunately calling `registry.close()` at the end of the application didn't reliably solve the problem. My application runs on a timer every few minutes, and I only see the metrics from a subset of the runs.
