### ISSUE TITLE
[feature] add a logicmonitor integration

### ISSUE THREAD

**Issue by benmccann** [micrometer-metrics/micrometer#2040]
It would be great if there were a `micrometer-registry-logicmonitor`

**Comment by jkschneider** [comment]
@benmccann Could you help us understand this product a little? Looking through their REST API docs, I don't see an obvious place for us to post custom metrics data?

**Comment by benmccann** [comment]
I need to choose a monitoring solution and was interested in testing out LogicMonitor as a contender because it got good reviews online, but after looking at their docs I'm not sure I'm as interested :stuck_out_tongue_closed_eyes:

Thanks for taking a look!
