### ISSUE TITLE
Add "host" tag to JettyClientMetrics.

### ISSUE THREAD

**Issue by dragneelfps** [micrometer-metrics/micrometer#2054]
Having bult in support for "host" tag found in other metric clients such as OkHttp3 will be very helpful.

P.S- I can work on this if it is approved.

**Comment by dragneelfps** [comment]
Adding onto this, can we a set of pre-defined tags for diffirenet http client micrometer implementations, so that we have a clear, unamibigous taglist.

**Comment by jkschneider** [comment]
@dragneelfps Yes, this seems like a good improvement that we'd happily take a PR for.

**Comment by dennysfredericci** [comment]
Hi @dragneelfps 😊 

Thank you for your suggestion, I just create a PR to add the host.
