### ISSUE TITLE
The following method did not exist: void io.micrometer.prometheus.PrometheusConfig.requireValid()

### ISSUE THREAD

**Issue by Comrada** [micrometer-metrics/micrometer#2059]
Hi,

I'm using micrometer 1.5.0 with spring boot 2.2.6, but without web/actuator.
I took a usage example from your [documentation](https://micrometer.io/docs/registry/prometheus) and adapted it to run inside Spring.
Config:
```java
@Configuration
public class MetricsConfig {
    @Bean
    public PrometheusMeterRegistry getMeterRegistry() {
        final var registry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
        registry.config().commonTags("application", "app_name");
        new ClassLoaderMetrics().bindTo(registry);
        new JvmMemoryMetrics().bindTo(registry);
        new JvmGcMetrics().bindTo(registry);
        new ProcessorMetrics().bindTo(registry);
        new JvmThreadMetrics().bindTo(registry);
        new UptimeMetrics().bindTo(registry);
        return registry;
    }
}
```
Service:
```java
@Service
public class Micrometer {
    private final PrometheusMeterRegistry registry;

    public Micrometer(final PrometheusMeterRegistry registry) {
        this.registry = registry;
    }

    @PostConstruct
    public void start() {
        try {
            HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);
            server.createContext("/prometheus", httpExchange -> {
                String response = registry.scrape();
                httpExchange.sendResponseHeaders(200, response.getBytes().length);
                try (OutputStream os = httpExchange.getResponseBody()) {
                    os.write(response.getBytes());
                }
            });

            new Thread(server::start).start();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
```
Immediately after starting, I get an error:
```
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.micrometer.prometheus.PrometheusMeterRegistry.<init>(PrometheusMeterRegistry.java:64)

The following method did not exist:

    'void io.micrometer.prometheus.PrometheusConfig.requireValid()'
```
But the same configuration works fine with Micrometer up to version 1.4.2
I opened the `PrometheusMeterRegistry` class and saw that in version 1.5.0 the constructor has a call to the nonexistent method `config.requireValid()`. In version 1.4.2. there is no such.

Am I doing something wrong or is this a bug in the latest release?
Thanks in advance

**Comment by Comrada** [comment]
In the next [thread](https://github.com/micrometer-metrics/micrometer/issues/2061) it turned out that the problem is in different versions of `micrometer-registry-prometheus` and `micrometer-core`. As a temporary solution, it may be the inclusion of a module `micrometer-core` with the same version.

**Comment by jkschneider** [comment]
Copied from the other thread:

> @Comrada The old version isn't actually depended on by `micrometer-registry-prometheus`, it's the annoying behavior of the `io.spring.dependency-management` plugin which is forcing down the version of `micrometer-core` to the version _it_ expects unless there is a first-level dependency on it with a different version.

> The Spring team continues to try to make Gradle behave like Maven, and this the consequence...
