### ISSUE TITLE
Backport ExecutorServiceMetrics meter name customization

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2070]
@shakuzen Mentioned it in https://github.com/line/armeria/pull/2689 too but would it be possible to merge this into 1.3 as well? Currently, we're in dependency hell not that different from the ABI break in the other issue.

- Want to support users that use any supported LTS version of micrometer, currently 1.3 and 1.5
- Want to be able to interop with Reactor

Seems like a reasonable desire for an infra library like micrometer to not lock us out of these :) But currently we have to pick Reactor + 1.5 (taking this fix) or 1.3 and no Reactor (or continue to use our forked `ExecutorServiceMetrics`)

_Originally posted by @anuraaga in https://github.com/micrometer-metrics/micrometer/issues/1919#issuecomment-625699782_

**Comment by anuraaga** [comment]
Thanks :)
