### ISSUE TITLE
how to get @Timerd(longtask=true) value?

### ISSUE THREAD

**Issue by taomingyaojing** [micrometer-metrics/micrometer#2091]
hello,sorry,need help,
    I want to use the time-consuming indicators for monitoring, and then do some time-consuming calculations and timeout control on the project. How can I get the data monitored by @timed?

**Comment by jkschneider** [comment]
I'm not clear what you're asking. Could you please ask this on slack.micrometer.io? Alternatively StackOverflow, but the response there might be a bit longer in coming.

**Comment by taomingyaojing** [comment]
Sorry, I did n’t describe clearly, I will put this question in the discussion area, but I also want to elaborate on the problem: I want to use @Timed to count time in my own application (Springboot), and then I hope to use this statistical Time, the timeout control of the transaction, or the time-consuming calculation of the transaction, and then output in the log. So I want to get the time of the current transaction, but I don't know what method I use to get it.
