### ISSUE TITLE
Micrometer registry memory usage

### ISSUE THREAD

**Issue by asad-awadia** [micrometer-metrics/micrometer#2093]
I had a question regarding the registry. What are the memory implications of having a registry that is getting metrics relatively frequently?

It holds all of them in memory right? 

Are they flushed when the registry is scraped - what if there is no scrape? do they grow unbounded? 

Are they dropped after a certain time? 

Does it impact my RSS and in a limited memory container environment?

Or is it so low it's not worth worrying about - I think each sample is ~1.5 bytes or something?

**Comment by jkschneider** [comment]
@asad-awadia For most registries the cost should be fixed, provided that you do a good job of making sure tag cardinality is unbounded. Yes, the meters are held in memory, but statistics are just accumulated to them. So for a timer, for example, the memory cost is the same whether you have 1 request/second or 1 million requests/second.

**Comment by asad-awadia** [comment]
@jkschneider tag cardinality is unbounded? did you mean bounded?

>This is what makes metrics different than other forms of observability like tracing or logs, which grow in cost proportionally to traffic.

Is there somewhere I can read more on this?

**Comment by jkschneider** [comment]
Sorry, I meant bounded.

**Comment by jkschneider** [comment]
> Is there somewhere I can read more on this?

Can you elaborate on what more you'd like to know?

**Comment by asad-awadia** [comment]
@jkschneider 

How metrics memory cost stay the same regardless of traffic - I am having trouble wrapping my head around how 1m req/sec and 1 req/sec both lead to the same memory usage for metrics

**Comment by jkschneider** [comment]
@asad-awadia A meter with a particular name and set of tags is long-lived, you just keep accumulating to its internal `LongAdder`/`DoubleAdder`-type data structures. The number goes up, but new meters aren't getting allocated for each request.

It might work better to continue this conversation on slack.micrometer.io.
