### ISSUE TITLE
Memory leak with Kafka metrics

### ISSUE THREAD

**Issue by alevohin** [micrometer-metrics/micrometer#2096]
Hi there,

Version 1.3.6 (used by Springboot 2.2.6).
`KafkaConsumerMetrics` has collection `notificationListenerCleanUpRunnables` which contains `Runnable`s to remove registered `NotificationListeners` from `MBeanServer`. The only place where `notificationListenerCleanUpRunnables` are executed is `close` method.

During consumer rebalancing (by default once per 5 minutes) new Kafka Consumer is created, new MBean is registered in `MBeanServer`. So a new list of metrics for the consumer is created and one more `NotificationListener` is added to `MBeanServer` in `KafkaConsumerMetrics` but the previous listener still exists. As a result, we have memory leak for previously registered `NotificationListener`s. You could see example on the screenshot:
![KafkaConsumerMetrics](https://user-images.githubusercontent.com/1502358/81945810-3537ac80-9607-11ea-9cfe-f58cdb92e6d9.png)

**Comment by izeye** [comment]
@alevohin Sorry for the trouble, and thanks for the issue. I created #2124 to try to resolve this.

**Comment by shakuzen** [comment]
@alevohin thanks for reporting this and sorry about the issue. Would you try with the latest snapshots containing the fix from @izeye to see if that resolves it for you?

**Comment by jonatan-ivanov** [comment]
Should be but @alevohin haven't confirmed the fix.
1.2.0 is not supported, could you please upgrade to the latest one and see if you still have the issue?

**Comment by shakuzen** [comment]
> Hi Is this resolved? I am using micrometer version 1.2.0
> and still facing the same issue.

The fix is not included in 1.2.0 since this was fixed after 1.2.0 was released. As @jonatan-ivanov stated, please upgrade to [a supported version](https://github.com/micrometer-metrics/micrometer#long-term-support-versions), which should include the fix.
