### ISSUE TITLE
Expose per-region statistics for Hibernate L2 cache

### ISSUE THREAD

**Issue by kennymacleod** [micrometer-metrics/micrometer#2097]
As of Micrometer 1.5, the `HibernateMetrics` binder exposes L2 cache statistics from the `org.hibernate.stat.Statistics` interface. This is useful, but it would be better if this were done on a per-cache-region basis, giving us more fine-grained per-entity and per-collection information.

This can be done by using `getSecondLevelCacheRegionNames` and `getSecondLevelCacheStatistics`, giving you a `SecondLevelCacheStatistics` object.

As well as providing the same hit/miss/put stats you get from the higher-level `Statistics` interface, you also get cache size and memory usage stats. These can then be tagged with the region name.

**Comment by jkschneider** [comment]
Nice! Let's do this.

**Comment by kennymacleod** [comment]
I'll try and get PR up soon

**Comment by shakuzen** [comment]
I'm not familiar with L2 cache regions. Are these static or dynamic? Will we know at binding time what all the regions are, or could they change?

**Comment by kennymacleod** [comment]
Good question, @shakuzen. My assumption was that once the `SessionFactory` is up and running, the set of regions is immutable. I just had a rummage through the Hibernate 5.2 codebase, and this does indeed seem to be the case. While the set of regions is mutable (for addition only) in the `Statistics` implementation class, this only occurs in the `SessionFactoryImpl` constructor. After that, there's no way to change them.

**Comment by shakuzen** [comment]
Looks like the method `getSecondLevelCacheStatistics` has been deprecated since Hibernate 5.3. I have switched to the recommended non-deprecated replacement `getDomainDataRegionStatistics`  in e6ae7bac8d272b1d4d5fc4d545acfa5ae29c23fc and things appear to work well.
