### ISSUE TITLE
Deadlock on DatadogStatsdLineBuilder

### ISSUE THREAD

**Issue by brunopalos** [micrometer-metrics/micrometer#2100]
Hi there!

We are seeing deadlocks on `DatadogStatsdLineBuilder`. This is affecting 1.4.1 but it seems the issue is also on master. The bellow `synchronised` blocks can originate a deadlock:

https://github.com/micrometer-metrics/micrometer/blob/629b1b54deebb205c15d683644a6f4e2da7992e7/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/DatadogStatsdLineBuilder.java#L54

https://github.com/micrometer-metrics/micrometer/blob/629b1b54deebb205c15d683644a6f4e2da7992e7/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/DatadogStatsdLineBuilder.java#L82

The following snippet explain the potential problem:

```
   public static void main(String[] args) {
        final Object conventionTagsLock = new Object();
        final ConcurrentMap<String, String> tags = new ConcurrentHashMap<>();
        ExecutorService executorService = Executors.newFixedThreadPool(3);
        for (int i = 0; i < 10; i++) {
            executorService.submit(() -> {
                synchronized (conventionTagsLock) {
                    tags.clear();
                }
            });
            executorService.submit(() -> {
                String randomKey = UUID.randomUUID().toString();
                tags.computeIfAbsent(randomKey, s -> {
                    synchronized (conventionTagsLock) {
                        return "value";
                    }
                });
            });
        }
    }
```

Thank you

**Comment by brunopalos** [comment]
micrometer 1.3.5 is not affected by this.

**Comment by izeye** [comment]
@brunopalos Thanks for the issue!

I created #2102 to try to resolve this.
