### ISSUE TITLE
Jetty Integration

### ISSUE THREAD

**Issue by cemo** [micrometer-metrics/micrometer#2109]
What is the proper way to use `TimedHandler` and others such as `JettyConnectionMetrics` with Spring Boot? I checked both documentation but could not find it.

**Comment by jkschneider** [comment]
@cemo There is no reason to use `TimedHandler` with Spring Boot generally. Spring's WebMvc and Webflux metrics publish a `http.server.requests` metric that does everything `TimedHandler` can do.

In general, any `MeterBinder` that Spring doesn't autoconfigure you can configure by just adding it as an `@Bean`. So create an `@Bean JettyConnectionMetrics` and Spring will plug it in to whatever registry implementations it is managing.

**Comment by cemo** [comment]
@jkschneider thank you so much. I will go in the way you suggest.
