### ISSUE TITLE
NPE in `MongoMetricsConnectionPoolListener`

### ISSUE THREAD

**Issue by Stephan202** [micrometer-metrics/micrometer#2117]
Today we observed the following on a shutdown thread:
```
java.lang.NullPointerException: null
    at io.micrometer.core.instrument.binder.mongodb.MongoMetricsConnectionPoolListener.lambda$registerGauge$0(MongoMetricsConnectionPoolListener.java:122)
    at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:54)
    ...
```

Looking at the code, what seems to have happened is the following:
1. [`#connectionPoolOpened`](https://github.com/micrometer-metrics/micrometer/blob/0dc111d1f6d3aa288dda24ac0912cbb483f1da1e/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java#L59) registers gauges for some server ID. This adds an entry to each of the four `ConcurrentHashMap`s and the gauges have a callback function which [unconditionally](https://github.com/micrometer-metrics/micrometer/blob/0dc111d1f6d3aa288dda24ac0912cbb483f1da1e/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java#L122) assumes that the server ID is a key in these maps.
2. At some point [`#connectionPoolClosed`](https://github.com/micrometer-metrics/micrometer/blob/0dc111d1f6d3aa288dda24ac0912cbb483f1da1e/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java#L71) is called. This removes the server ID entry from each of the maps.
3. At this point the gauges are still registered, and the next time they are read out an NPE results.

**Comment by Stephan202** [comment]
Looking closer at [`#connectionPoolClosed`](https://github.com/micrometer-metrics/micrometer/blob/0dc111d1f6d3aa288dda24ac0912cbb483f1da1e/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java#L71), the meters _should_ have been deregistered before the server ID entry is removed from each of the maps. Maybe a race condition? :thinking:

**Comment by izeye** [comment]
@Stephan202 Thanks for the issue!

It seems that there is a possible window between unregistering gauges and collecting values from gauges. I created https://github.com/micrometer-metrics/micrometer/pull/2118 to try to resolve this.

**Comment by Stephan202** [comment]
Tnx for the quick turnaround. Fix LGTM :)
