### ISSUE TITLE
java.lang.NoClassDefFoundError: org/LatencyUtils/IntervalEstimator in Springboot 2.3.0

### ISSUE THREAD

**Issue by yuanpli** [micrometer-metrics/micrometer#2122]
See https://github.com/spring-projects/spring-boot/issues/21538

**Comment by shakuzen** [comment]
Have you seen the comment from @izeye https://github.com/spring-projects/spring-boot/issues/21538#issuecomment-632639800? This is most likely the issue. Please take a look.
