### ISSUE TITLE
minimumExpectedValue(Double) and maximumExpectedValue(Double) are missing at 1.3.x's DistributionSummary.Builder

### ISSUE THREAD

**Issue by imasahiro** [micrometer-metrics/micrometer#2123]
I'm using a library compiled with micrometer-1.5.1 and an application which uses micrometer-1.3.9. At 1.5.x, `DistributionSummary.Builder.minimumExpectedValue(@Nullable Double min)` (or `maximumExpectedValue(Double)`) is introduced (https://github.com/micrometer-metrics/micrometer/commit/3da05bbb8a66371f6e01ecb5963497e2b4850147#diff-6102e7c5a5c207819b80fe916d46a509R275) but since the APIs are not backported to 1.3.x, it causes NoSuchMethodError at runtime.
[Here](https://github.com/line/armeria/blob/armeria-0.99.5/core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java#L98-L99) is a pointer to the location which throws NoSuchMethodError 
```
java.lang.NoSuchMethodError: io.micrometer.core.instrument.DistributionSummary$Builder.maximumExpectedValue(Ljava/lang/Double;)Lio/micrometer/core/instrument/DistributionSummary$Builder;
0 = {StackTraceElement@22772} "com.linecorp.armeria.common.metric.MoreMeters.newDistributionSummary(MoreMeters.java:98)"
```

Like https://github.com/micrometer-metrics/micrometer/issues/2002, do we have a chance to backport the commit or introduce APIs to 1.3.x to bridge compatibility?

**Comment by minwoox** [comment]
https://github.com/line/armeria/pull/2742
This is the related PR.
Perhaps can we add `DistributionSummary.maximumExpectedValue(Double)` and `DistributionSummary.minimumExpectedValue(Double)`to 1.3?

**Comment by anuraaga** [comment]
I think I missed this in the previous issue since unlike that one where it was also API breaking our build (we were setting into a local variable), here it is only ABI breaking at runtime but otherwise has the same concept and so should add the methods so libraries can support latest patch of all LTS versions.

**Comment by shakuzen** [comment]
Please try with the latest 1.5.2-SNAPSHOT and 1.3.10-SNAPSHOT versions to make sure there are no remaining issues before we release these.
