### ISSUE TITLE
Is there a way to report newrelic errors via micrometer registry?

### ISSUE THREAD

**Issue by srikarn** [micrometer-metrics/micrometer#2125]
We currently use NewRelic APM agent to publish metrics. along with regular metrics, we heavily make use of the error analysis supported by NewRelic.

We currently report errors like so

`NewRelic.noticeError(exception, mapOfErrorAttributes);`

https://newrelic.github.io/java-agent-api/javadoc/index.html?com/newrelic/api/agent/NewRelic.html

is there a way to report errors via micrometer registry?

**Comment by jkschneider** [comment]
@srikarn Can you help us understand how this is viewed on the backend? Would something like an error counter do the same thing effectively?

```java
registry.counter("errors", Tags.of("exception", exception.getClass().getName(), ...));
```
(where the ... is `mapOfErrorAttributes` turned into tag key-value pairs)

**Comment by srikarn** [comment]
New relic has error analysis feature that charts out errors over time and top 5 errors e.t.c
https://docs.newrelic.com/docs/apm/applications-menu/error-analytics/introduction-error-analytics

**Comment by shakuzen** [comment]
Thanks for the link to the New Relic documentation.

We don't currently map anything from Micrometer to any special notion of New Relic errors.

You can tag any metrics you're making with information from exceptions, as Jon pointed out. This is usually already done with HTTP server/client metrics instrumentation, for example.
From reading the linked documentation, I didn't see any way to do this, but if New Relic's error analytics could also work with metrics reported to New Relic, I think you'd have what you want already. I suppose you can do similar analysis on those metrics yourself already, just without the error analysis UI pre-built.

Without a change on New Relic error analytics side to derive from metrics, this sounds similar to the request to support events (#581) or exception events (#1097).
