### ISSUE TITLE
StatsDCounter won't report at all if never incremented

### ISSUE THREAD

**Issue by DRSains** [micrometer-metrics/micrometer#2131]
Currently the code for StatsD counter does ignore increment = 0:

```
public void increment(double amount) {
        if (!shutdown && amount > 0) {
            count.add(amount);
            subscriber.onNext(lineBuilder.count((long) amount));
        }
    }
```

if a counter is created, but never incremented, it will never be reported as 0. This a problem for the many users of datadog. In fact it won't allow you to create a dashaboards or alerts for metrics that have never been reported. The use case were this is a big issue is when creating error alerts: one wants to create an alert in case an error counter suddenly goes > threshold, but datadog would only allow it after the first error.

I would be very useful to have a setting or a property somewhere to report even 0 values for counters.

**Comment by jkschneider** [comment]
Thanks for the nice detailed explanation of the datadog experience. I would hate for you to ever have to zero increment a counter to solve a usability issue on one monitoring system.

What do you think about, for the dogstatsd flavor, we just always ship a zero on counter registration?

**Comment by DRSains** [comment]
The fact not to report 0 has been like that for a very long time, so maybe the most sensible thing is not to change this behaviour, but leave a configuration setting to enable the bahaviour I requested. I'd be happy with that.

**Comment by jkschneider** [comment]
@DRSains Personally I think shipping a zero early brings this closer in line to what would happen if you published a counter directly to API via `DatadogMeterRegistry`. I don't think there are any compatibility concerns. 

So if the behavior is sensible, adding additional configuration options is purely API bloat.

Any downsides you can think of?

**Comment by DRSains** [comment]
Personally I see no downsides! Thanks

**Comment by DRSains** [comment]
Also careful, I am talking about the StatsD registry, not the DatadogRegistry. This is the datadog flavour statsd registry and not the datadog api. I know it is confusing, but there are 2 ways of accessing this, I'd prefer the DD Api directly, but the setup I use is not my choice.

**Comment by jkschneider** [comment]
> Also careful, I am talking about the StatsD registry, not the DatadogRegistry. 

@DRSains No worries, you were clear about this. I just propose that in `StatsdMeterRegistry`, when a counter is registered and we are using the dogstatsd flavor, that we just immediately ship a zero.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
