### ISSUE TITLE
StatsdMeterRegistry sends multiple duplicated count measurements

### ISSUE THREAD

**Issue by chengzp** [micrometer-metrics/micrometer#2138]
Micrometer version: 1.5.1

As time progresses, `StatsdMeterRegistry` seems to be creating more and more udp connections. A single counter increment is then sent to all those connections, leading to duplicate counts. For example, in one particular case, the ngrep for a specific counter increment shows 7 identical messages (the message contents are omitted):
```
U 172.30.23.125:40280 -> 172.31.23.196:8125 #12277
U 172.30.23.125:55138 -> 172.31.23.196:8125 #12278
U 172.30.23.125:50911 -> 172.31.19.45:8125 #12279
U 172.30.23.125:58785 -> 172.31.25.42:8125 #12280
U 172.30.23.125:46418 -> 172.31.25.42:8125 #12281
U 172.30.23.125:45846 -> 172.31.24.89:8125 #12282
U 172.30.23.125:47359 -> 172.31.24.89:8125 #12283
```
(The `172.31.*.*` IP addresses are what our statsd server's hostname resolves to.)

We also saw this:
```
$ jcmd 168 GC.class_histogram | grep StatsdMeterRegistry
1036:            13            208  io.micrometer.statsd.StatsdMeterRegistry$$Lambda$152/0x00000001002e8040
1105:             7            168  io.micrometer.statsd.StatsdMeterRegistry$$Lambda$113/0x0000000100250440
1316:             7            112  io.micrometer.statsd.StatsdMeterRegistry$$Lambda$122/0x0000000100255c40
1334:             1            104  io.micrometer.statsd.StatsdMeterRegistry
2583:             1             24  <redacted>.StatsdMeterRegistryFactory$build$config$1
2696:             1             24  io.micrometer.statsd.StatsdMeterRegistry$$Lambda$112/0x0000000100250040
2989:             1             16  <redacted>.StatsdMeterRegistryFactory
3368:             1             16  io.micrometer.statsd.StatsdMeterRegistry$$Lambda$110/0x0000000100229c40
3369:             1             16  io.micrometer.statsd.StatsdMeterRegistry$$Lambda$164/0x00000001002ea840
3370:             1             16  io.micrometer.statsd.StatsdMeterRegistry$$Lambda$201/0x000000010032e840
3371:             1             16  io.micrometer.statsd.StatsdMeterRegistry$$Lambda$77/0x0000000100213c40
```
The 7 occurrences of `Lambda$113`/`Lambda$122` is suspiciously equal to the number of duplicate udp connections. (It also shows that the issue is not multiple `StatsdMeterRegistry` being created.)

The issue is not easily reproducible. Only after a long time and with enough metric traffic does it seem to reproduce. Let me know if there is anything more I can do to help with the diagnosis.

I am not positive, but it might be related to this change: https://github.com/micrometer-metrics/micrometer/commit/2bf645d6c4a2fad6e2dcf57bc90fb779bce32645

**Comment by shakuzen** [comment]
Sorry for the trouble and thanks for the detailed report of the issue. Were you using this prior to 1.5.1 without issue?

**Comment by chengzp** [comment]
The project is relatively new, so I don't have good data other than for 1.5.1. We tried downgrading to 1.4.1, but it seems like the opposite happens now, where no metrics are sent at all after a while (this might be the issue https://github.com/micrometer-metrics/micrometer/commit/2bf645d6c4a2fad6e2dcf57bc90fb779bce32645 was intended to solve).

**Comment by chengzp** [comment]
I looked at the code a bit more. Should [this line](https://github.com/micrometer-metrics/micrometer/blob/v1.5.1/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java#L273) and [this line](https://github.com/micrometer-metrics/micrometer/blob/v1.5.1/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java#L281) use [`update()`](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/Disposable.java#L59-L67) instead of [`replace()`](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/Disposable.java#L69-L77), so the previous disposable is cleaned up properly?

**Comment by jkschneider** [comment]
Looks like you found the issue @chengzp! Would you like to PR this?

**Comment by chengzp** [comment]
Sure! I'll give it a try.

**Comment by chengzp** [comment]
@shakuzen @jkschneider: the PR is created. Please take a look. 

Is there anything I need to do to get it into 1.5.2?

**Comment by shakuzen** [comment]
I don't have a problem with the fix, but I would ideally like to add a test that reproduces this scenario. I'm having a little trouble understanding when the client being replaced would still be able to send metrics, as it should only be replaced when the previous one disconnected (`doOnDisconnected` callback is called).
