### ISSUE TITLE
NewRelic - Configure HTTP Proxy

### ISSUE THREAD

**Issue by jaecktec** [micrometer-metrics/micrometer#2145]
There is currently no possible way to create a NewRelicMeterRegistry with a custom http-sender. 

We have to run our service within a dmz and all outgoing http requests have to be tunneled through a http proxy.

The constructor to adjust the HttpSender is currently private thus can't be used. Is there a different way how to configure a HttpProxy?

**Comment by jaecktec** [comment]
can we by any chance make this constructor public? That would make it possible to set the proxy settings

**Comment by jkschneider** [comment]
I think it is possible today when sending through the api client provider:

```java
        NewRelicConfig config = key -> null;
        NewRelicMeterRegistry.builder(config)
                .clientProvider(new NewRelicInsightsApiClientProvider(config, httpSender))
                .build();
```

**Comment by jaecktec** [comment]
ah thanks, for some reason I thought the Builder is package only too (Builder is, builder is not)
