### ISSUE TITLE
Lost metrics when Dynatrace is dow 

### ISSUE THREAD

**Issue by fsaldivars** [micrometer-metrics/micrometer#2146]
Currently, our project is using:
`micrometer-core 1.5.1`
`micrometer-registry-dynatrace 1.5.1`
 When a metric is triggered by Micrometer we've seen some issues. The most common is a DT host down, another is API-token not provided.

There is a configuration that allows to Micrometer to react on unsuccess call and allow to resent metrics in batch or another mechanism?

**Comment by jkschneider** [comment]
> API-token not provided

You mean you didn't configure an API token to the registry? I suppose this wouldn't ever work?

**Comment by jkschneider** [comment]
You could fix the periodically down DT host by providing a custom `HttpSender` and using something like [Resilience4J retries](https://resilience4j.readme.io/docs/retry) for the request. Normally I wouldn't bother much with a dropped metrics payload or two. If this is happening with enough frequency to raise an issue on this, it feels like an alarmingly bad reliability for the DT service itself, and I'd suggest you raise this with DT support.

**Comment by fsaldivars** [comment]
Right the problem is coming up on periodically scale down DT we lost metrics and there is no way to recover it, our vendor is working to provide a solution. but it is good to have Reslience4J retries as one option.
