### ISSUE TITLE
Question: Registries implementing AutoCloseable

### ISSUE THREAD

**Issue by AarjavP** [micrometer-metrics/micrometer#2147]
I see that the `MeterRegistry` has a close method with same semantics as `AutoCloseable`'s `close` method but it is not implementing it. Just wondering why this is the case.
Was this decision made for backwards compatibility or to avoid some interaction with code quality plugins? or is it somehow bad practice and causes unintentional behavior?

**Comment by jkschneider** [comment]
> to avoid void some interaction with code quality plugins.

Exactly. And IDEs sometimes suggest to close AutoCloseable resources in the block in which they are created as well.
