### ISSUE TITLE
Percentile metrics zeroed after while

### ISSUE THREAD

**Issue by kgonia** [micrometer-metrics/micrometer#2150]
Hi, 

I'm using timer to measure time of task. I also configured timer to use percentiles. After few calls everything is fine but after while all percentile metrics are zeroed. Is it expected behavior? 

My configuration:
Spring boot app with TimedAspect, Timer is configured using @Timed annotation. I'm using prometheus endpoint for viewing metrics.

`@Timed(value = "my_task",
            extraTags = {"action", "calculating_something"},
            percentiles = {0.1, 0.25, 0.5, 0.75, 0.95, 0.99})`

Counter and sum works fine. This is how metrics looks like after while:

`my_task_seconds{action="calculating_something",class="my.package.service",exception="none",method="getSomething",quantile="0.1",} 0.0
my_task_seconds{action="calculating_something",class="my.package.service",exception="none",method="getSomething",quantile="0.25",} 0.0
my_task_seconds{action="calculating_something",class="my.package.service",exception="none",method="getSomething",quantile="0.5",} 0.0
my_task_seconds{action="calculating_something",class="my.package.service",exception="none",method="getSomething",quantile="0.75",} 0.0
my_task_seconds{action="calculating_something",class="my.package.service",exception="none",method="getSomething",quantile="0.95",} 0.0
my_task_seconds{action="calculating_something",class="my.package.service",exception="none",method="getSomething",quantile="0.99",} 0.0
my_task_seconds_count{action="calculating_something",class="my.package.service",exception="none",method="getSomething",} 46.0
my_task_seconds_sum{action="calculating_something",class="my.package.service",exception="none",method="getSomething",} 117.038815208`

**Comment by izeye** [comment]
@kgonia The implementation for percentiles is time-windowed, so it seems to work as expected.

Please see the "NOTE" in [the "10. Timers" section in the Micrometer reference docs](http://micrometer.io/docs/concepts#_timers). It's about max, but it also applies to percentiles. I created https://github.com/micrometer-metrics/micrometer-docs/pull/135 to make it explicit.
