### ISSUE TITLE
TimedAspect，@Timed  Only arbitrary methods in another bean. If called from within the bean, it will not work 

### ISSUE THREAD

**Issue by panqingcui** [micrometer-metrics/micrometer#2152]
###  question

TimedAspect，@Timed  Only arbitrary methods in another bean. If called from within the bean, it will not work 

### code

```
@Configuration
@Slf4j
public class TimedConfiguration {
    @Bean
    public TimedAspect timedAspect(MeterRegistry registry) {
        log.info("--------------------->timed aspect init success!");
        return new TimedAspect(registry);
    }
}

@Service
public class TestService {
    
    @Timed
    public boolean getUser() {
        return get();
    }
    @Timed
    public boolean get() {
        return true;
    }

}

@RestController
@RequestMapping("/tool")
public class ToolController {
 
    private final TestService testService;

    public ToolController( TestService testService) {
     
        this.testService = testService;
    }

    @RequestMapping(method = RequestMethod.GET, produces = "application/json")
    public CommonResult getTool() {
        return CommonResult.success(testService.getUser());
    }
```

### metrics
not get() method metrics
![QQ图片20200615165432](https://user-images.githubusercontent.com/10126345/84638386-80f0b500-af29-11ea-94d7-134e669e160b.png)

**Comment by shakuzen** [comment]
If I remember correctly, that's a limitation of Spring AOP / AspectJ and I don't think we can do anything about that in Micrometer's implementation. Only method calls via proxied Spring beans will have the aspect applied to them. See [the Understanding AOP Proxies documentation](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#aop-understanding-aop-proxies). Specifically:

> However, once the call has finally reached the target object (the `SimplePojo`, reference in this case), any method calls that it may make on itself, such as `this.bar()` or `this.foo()`, are going to be invoked against the this reference, and not the proxy. This has important implications. It means that self-invocation is not going to result in the advice associated with a method invocation getting a chance to execute.

There might be a way with some aspect weaving configuration to get even those method calls proxied, but I'm not sure of specifics.

**Comment by panqingcui** [comment]
Thank you for your reply
