### ISSUE TITLE
Influx string escaping

### ISSUE THREAD

**Issue by themoritz** [micrometer-metrics/micrometer#2154]
It looks like the Influx backend doesn't do any escaping of e.g. tag values. As an example, using `JvmMemoryMetrics()` tries to send the following line to influx:

```
jvm.memory.max,area=heap,id=G1 Eden Space,metric_type=gauge value=-1 1592264154913
```

whereas the properly escaped value for the `id` tag would be `G1\ Eden\ Space` (see [Influx docs](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/#special-characters)).

**Comment by izeye** [comment]
@themoritz Thanks for the report, but I couldn't reproduce it with [this sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/influx), and escaping seems to work as follows:

```
jvm_memory_max,area=heap,id=G1\ Eden\ Space,metric_type=gauge
```

You might be using an old version. If that's the case, please try the latest version. If not, a simple sample to reproduce it would be helpful.

**Comment by themoritz** [comment]
Ok while building a reproducing example I was able to narrow the problem down a bit: It only occurs when I'm using `NamingConvention.dot`, like [here](https://github.com/themoritz/micrometer-escaping-repro/blob/e93bb7181952589d862889caba0988c0dda45afb/src/main/kotlin/micrometer/escaping/repro/App.kt#L28).

**Comment by izeye** [comment]
@themoritz Thanks for the quick feedback.

Escaping usually happens in `NamingConvention`, so replacing its dedicated one will lose the ability.

See https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxNamingConvention.java

**Comment by izeye** [comment]
@themoritz For your information, if you want to stick with the dot notation for some reason while keeping the escaping, you can use `InfluxNamingConvention(NamingConvention.dot)` instead.

**Comment by shakuzen** [comment]
Thanks for the support @izeye. With that information, I believe that makes things clear and there is no change to be made in Micrometer. Let us know if that's not the case and we can reopen this @themoritz

**Comment by themoritz** [comment]
Can confirm that using `InfluxNamingConvention(NamingConvention.dot)` solves my issue, thanks a lot @izeye!
