### ISSUE TITLE
MetricsDSLContext discards the user's ExecuteListeners

### ISSUE THREAD

**Issue by ben-manes** [micrometer-metrics/micrometer#2157]
The mutations of the jOOQ configuration replaces, rather than amends, the user supplied ExecuteListeners. The `derive(ExecuteListeners)` and `set(ExecuteListeners)` should build a combined array when setting.

https://github.com/micrometer-metrics/micrometer/blob/06e895f2a8eced07eae69c449ab74f969a7b6a2b/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/MetricsDSLContext.java#L83-L87

https://github.com/micrometer-metrics/micrometer/blob/06e895f2a8eced07eae69c449ab74f969a7b6a2b/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/MetricsDSLContext.java#L97-L101

**Comment by izeye** [comment]
@ben-manes Thanks for the issue!

I created https://github.com/micrometer-metrics/micrometer/pull/2158 to try to resolve this.
