### ISSUE TITLE
HibernateMetrics and HibernateQueryMetrics should check whether or not caches are enabled

### ISSUE THREAD

**Issue by schlangz** [micrometer-metrics/micrometer#2162]
HibernateMetrics and HibernateQueryMetrics should check whether or not caches are enabled.

Since query cache and 2nd level cache (also controls natural id cache) can be disabled it would be great if the metrics would check the settings before registering "dead" meters:

`    Properties props = sessionFactory.getProperties();`
`    this.isSecondLevelCacheEnabled = ConfigurationHelper.getBoolean( AvailableSettings.USE_SECOND_LEVEL_CACHE, props );`
`    this.isQueryCacheEnabled = ConfigurationHelper.getBoolean( AvailableSettings.USE_QUERY_CACHE, props );`

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
