### ISSUE TITLE
Sending Metrics to Datadog Agent running on swarm?

### ISSUE THREAD

**Issue by aworrell-terazo** [micrometer-metrics/micrometer#2178]
management.metrics.export.statsd.enabled=true
management.metrics.export.statsd.flavor=datadog
management.metrics.export.statsd.port=8125
management.metrics.export.statsd.host=datadog-agent
management.metrics.tags.application=${spring.application.name}

This is the configuartion we are trying to get working, datadog-agent is a swarm agent running on the same swarm as the service with this configuration is running in. Is there something we are doing wrong here? We changed the host to be a host agent and that worked fine. Is it possible to send metrics to a swarm agent? 

thank you

**Comment by shakuzen** [comment]
I'm not very familiar with docker swarm and running the datadog agent on it, but if the hostname is resolvable from the application and there are no other networking issues, the application should be able to send the statsd lines to it.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
