### ISSUE TITLE
Setting minimum-expected-value from java application propertiese 

### ISSUE THREAD

**Issue by mostafaHamdy-git** [micrometer-metrics/micrometer#2179]
I am facing issues regarding the number of buckets being generated for my **http.server.requests**.
I found that we can control number of buckets by using **minimum-expected-value** and **maximum-expected-value**.
So my question is simple, these are my configuration in my properties file, what is the time unit that i should be using.

`management.metrics.distribution.minimum-expected-value.http.server.requests`
I know it can be done from code but setting it in properties file is easier, i have looked around but i was not able to find examples for it

**Comment by izeye** [comment]
@mostafaHamdy-git This seems to be a Spring Boot question. You can find the details of the properties in the "[10.A.14. Actuator properties](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator-properties)" section as follows:


Key | Default Value | Description
-- | -- | --
management.metrics.distribution.maximum-expected-value.* |   | Maximum value that meter IDs starting with the specified name are expected to observe. The longest match wins. Values can be specified as a long or as a Duration value (for timer meters, defaulting to ms if no unit specified).
management.metrics.distribution.minimum-expected-value.* |   | Minimum value that meter IDs starting with the specified name are expected to observe. The longest match wins. Values can be specified as a long or as a Duration value (for timer meters, defaulting to ms if no unit specified).

As you can see, their default duration units are milliseconds. For the details of Spring Boot duration unit support, see the "[Converting durations](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-conversion-duration)" section.
