### ISSUE TITLE
Upgrade to netty 4.1.51, reactor-netty 0.9.10, and reactor 3.3.8

### ISSUE THREAD

**Issue by iam-nagarajan** [micrometer-metrics/micrometer#2188]
I am using micrometer-registry-statsd version 1.3.10 and it has the following critical vulnerability on netty package.
https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Anetty&cpe_product=cpe%3A%2F%3Anetty%3Anetty&cpe_version=cpe%3A%2F%3Anetty%3Anetty%3A4.1.34

Since it is a shaded artifact, I couldn't exclude and upgrade netty to latest version.

Please upgrade netty version and publish a latest artifact on 1.3.x. 
I am not sure about whether there are issues with latest version 1.5.x

**Comment by shakuzen** [comment]
As noted on Slack:
> There is no usage of the netty server component or HTTP in Micrometer's StatsD module, so none of those CVEs are applicable.

That said, we can still upgrade the patch version for the next patch release of 1.3.x.
