### ISSUE TITLE
Adding container tag，for example pod_name

### ISSUE THREAD

**Issue by CoderLan0668** [micrometer-metrics/micrometer#2191]
Using Spring Boot Actuator and Prometheus in K8S, the metrics has't any lebel about the container or pod, we usually filter or aggregate there metrics by container or pod. How can i acheive this goal?

**Comment by checketts** [comment]
Container and pod labels should be provided via service discovery/relabelling with Prometheus and Kubernetes, not via Micrometer

**Comment by jkschneider** [comment]
If you would like to do it programmatically, can accomplish it with the fabric8 K8S client:

![image](https://user-images.githubusercontent.com/1697736/87594036-35a10200-c6a1-11ea-8ac8-0bf55b084401.png)
