### ISSUE TITLE
CommonObjectPool metrics

### ISSUE THREAD

**Issue by CoderLan0668** [micrometer-metrics/micrometer#2194]
Do any one know why the CommonObjectPool metrics not in the latest release version? But the class `CommonsObjectPool2Metrics`  had already been merged into the branch Matser.

**Comment by CoderLan0668** [comment]
as #1712   The CommonObjectPool metrics will publish in 1.6.0， so when？

**Comment by shakuzen** [comment]
We are about to release 1.6.0 today. You can usually check the [milestone page](https://github.com/micrometer-metrics/micrometer/milestones) to check tentative release dates.
