### ISSUE TITLE
Micrometer support for Dependency Tracking 

### ISSUE THREAD

**Issue by msalemcode** [micrometer-metrics/micrometer#2201]
I am new for micrometer. I am trying to convert my Java Spring from using Application Insight Telemetry client to user  `io.micrometer.azuremonitor` In Telemetry I can establish dependency tracking 

`DependencyTrackingTelemetryModule depModule = new DependencyTrackingTelemetryModule();
    depModule.Initialize(TelemetryConfiguration.Active);`

My goal is to when I submit a Rest Call to get the duration and counter for all the subsystem that call will use. I can not find any example doing more than hello world.

**Comment by shakuzen** [comment]
Could you provide a link to some documentation describing the feature? I'm not familiar with it. It is possible that it is something outside the current scope of Micrometer.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
