### ISSUE TITLE
Http_Request metrics is not available

### ISSUE THREAD

**Issue by vasantharajankuduva** [micrometer-metrics/micrometer#2206]
When we implement Micrometer via Spring boot actuator, it is providing metrics with data for Http requests as well.
But when we use micormeter core jar for non spring boot application. We are not able to get Http requests metrics data.

Do we need to do any extra steps for the latter scenario?

**Comment by shakuzen** [comment]
Yes, something needs to do the instrumentation of whatever framework/library you are using for an HTTP server/client. Spring Boot is what does that when Spring is the framework. You can check the (auto-)configuration code Spring Boot provides to see if you can perhaps reuse some of that code outside of a Spring Boot application. Otherwise, you could try with the `TimedAspect` and `@Timed` annotations.

**Comment by SubhamSinghal** [comment]
Can we add filter in micrometer to collect http metrics?

**Comment by vasantharajankuduva** [comment]
> Yes, something needs to do the instrumentation of whatever framework/library you are using for an HTTP server/client. Spring Boot is what does that when Spring is the framework. You can check the (auto-)configuration code Spring Boot provides to see if you can perhaps reuse some of that code outside of a Spring Boot application. Otherwise, you could try with the `TimedAspect` and `@Timed` annotations.

Can you provide us some example on this? Or why is it not available as out of the box from Micrometer?

**Comment by shakuzen** [comment]
> @shakuzen Can we add servlet filter in micrometer to collect http metrics?

Possibly. Usually frameworks on top of servlet have more context than the servlet layer does when instrumenting, so it's better to instrument the higher-level frameworks. If there's a use case for this (building applications using servlets directly with no framework), feel free to open an enhancement request and we can consider it. Having something like this would make double instrumentation likely to occur which is generally something we would like to avoid.

> Can you provide us some example on this? Or why is it not available as out of the box from Micrometer?

The official support for Micrometer with Spring framework components resides in Spring Boot, so we don't have an official example of using Micrometer without Spring Boot in a Spring app. Something unofficial may exist, though. We have limited resources and need to focus our efforts in regards to what we support. Out of the box support for Micrometer in Spring apps requires something like an auto-configuration mechanism, which is a core feature of Spring Boot. Even if we provided instrumentation of Spring framework components in Micrometer itself, you would have to configure them in each of your applications without auto-configuration.

**Comment by shakuzen** [comment]
My previous answer was largely assuming the non-Spring Boot applications mentioned are still Spring applications. If that's not the case, much of the answer remains the same in that there needs to be some support for offering out-of-the-box metrics with Micrometer, which generally means some kind of auto-configuration mechanism. If you'd like to discuss specifics of your situation more, Slack is probably a better medium for this than this GitHub issue. Feel free to reach out on the [Micrometer Slack](https://slack.micrometer.io)

**Comment by SubhamSinghal** [comment]
> > @shakuzen Can we add servlet filter in micrometer to collect http metrics?
> 
> Possibly. Usually frameworks on top of servlet have more context than the servlet layer does when instrumenting, so it's better to instrument the higher-level frameworks. If there's a use case for this (building applications using servlets directly with no framework), feel free to open an enhancement request and we can consider it. Having something like this would make double instrumentation likely to occur which is generally something we would like to avoid.
> 
> > Can you provide us some example on this? Or why is it not available as out of the box from Micrometer?
> 
> The official support for Micrometer with Spring framework components resides in Spring Boot, so we don't have an official example of using Micrometer without Spring Boot in a Spring app. Something unofficial may exist, though. We have limited resources and need to focus our efforts in regards to what we support. Out of the box support for Micrometer in Spring apps requires something like an auto-configuration mechanism, which is a core feature of Spring Boot. Even if we provided instrumentation of Spring framework components in Micrometer itself, you would have to configure them in each of your applications without auto-configuration.

Created a new issue for this. https://github.com/micrometer-metrics/micrometer/issues/2213
