### ISSUE TITLE
Multiple registered custom metrics in Dynatrace by one Timer

### ISSUE THREAD

**Issue by boyan-velinov** [micrometer-metrics/micrometer#2216]
Hi,

When we register one Timer in DynatraceMeterRegistry, the result is multiple custom metrics in Dynatrace.
For example:
Registered one timer with name: `my.timer`
Custom metrics in Dynatrace: `my.timer.max`,  `my.timer.avg`, `my.timer.sum` and `my.timer.count`

I believe these values are related to Dynatrace `aggregationType` on custom metric level:
https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v1/custom-metrics/put-custom-metric/

Is there a way to restrict registering all derivates custom metrics? For, example I want to use only `my.timer.avg` without others.
This will minimize our Dynatrace custom metrics quota consumption.

Thanks!
Boyan

**Comment by obarcelonap** [comment]
Hi, I am afraid that's not posible for the moment.
The expansion of the Meter interface into multiple metrics in the monitoring system is a regular pattern in all the meter registries. Hence, I agree it would be a nice feature not only for Dynatrace but for all the vendors.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
