### ISSUE TITLE
NaN or question mark "?" as value of mean field in InfluxLine protocol

### ISSUE THREAD

**Issue by admoca60** [micrometer-metrics/micrometer#2226]
Dear all

I have a system with InfluxMeterRegistry configured as default MeterRegistry.

Sometimes, I could see some strange values for some fields in TomcatMetrics, but I suspect that this is not strictly related to any MeterBinder but the core for StepMeterRegistry model.

In my example, we can see how any specific Tomcat metric for influx has the following behaviour:

```
tomcat.global.request,tagkey1=value1,tagkey2=value2 sum=955,count=23,mean=? 1596267900005000000
```

Other times, in other custom metrics, I can see the "NaN" randomly as "mean" field. For example:

```
grpc.server,tagkey1=value1,tagkey2=value2 rpc.completed.responseTime.sum=290.577193,rpc.completed.responseTime.count=9,rpc.completed.responseTime.mean=NaN,rpc.completed.responseTime.upper=48.271632 1596352020000000000
```

Note: I cannot reproduce them easily

**Comment by izeye** [comment]
@admoca60 Thanks for the issue!

This seems to be similar to #1932, but for `InfluxMeterRegistry`. I created https://github.com/micrometer-metrics/micrometer/pull/2227 to try to resolve this.
