### ISSUE TITLE
StatsD + Custom fields 

### ISSUE THREAD

**Issue by TheHydGuy** [micrometer-metrics/micrometer#2233]
Hello All,

I have an springboot application that sends metrics using STATSD protocol to telegraf. Now I have a requirement where I have to send custom fields as part of the metrics.

Is there a way I can send the custom metrics?

show field keys from http_server_requests
name: http_server_requests
fieldKey fieldType
-------- ---------
count    integer
lower    float
mean     float
stddev   float
sum      float
upper    float

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
