### ISSUE TITLE
spring data jpa rest apis are broken when micrometer dependencies are added for springboot 1.5.x

### ISSUE THREAD

**Issue by elue** [micrometer-metrics/micrometer#224]
Micrometer version : 1.0.0-rc3
Spring boot version: 1.5.8
         <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-influx</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-spring-legacy</artifactId>
        </dependency>
These 2 dependencies are preventing the spring-data-jpa rest endpoints to get exposed.

**Comment by checketts** [comment]
I'm not familiar with those specific endpoints. Are you referring to actuator endpoints? What error are you seeing?

**Comment by elue** [comment]
There are no errors, the endpoint is simply not available, when the micrometer dependencies are removed, its Ok.

**Comment by jkschneider** [comment]
Thanks, I can reproduce with a fork of the Spring Data REST API sample. https://github.com/jkschneider/gs-accessing-data-rest/commit/0eabe74566eacfee57213d432d116185dfe6be59
