### ISSUE TITLE
[micrometer-registry-statsd 1.3.x] Upgrade to latest patch versions in netty 4.1.x and reactor-netty

### ISSUE THREAD

**Issue by iam-nagarajan** [micrometer-metrics/micrometer#2240]
micrometer-registry-statsd latest 1.3.x i.e 1.3.12 still uses netty 4.1.34 and it reports some critical vulnerabilities.

As discussed in #2188 , can we upgrade these to latest patch versions in next 1.3.x patch release?

**Comment by izeye** [comment]
@iam-nagarajan Thanks for the issue!

Looking at #2188 and d7300e963a6cd67192857c78951da9e4e0f0564f, the upgrades seem to have applied only to dynamic versions. `micrometer-registry-statsd` is using fixed versions, so its locked dependencies haven't been updated.

Looking at https://github.com/micrometer-metrics/micrometer/issues/2188#issuecomment-657520288, it seems to have intended to upgrade them to the latest patch versions, but its title and commit reference to the latest versions.

I created https://github.com/micrometer-metrics/micrometer/pull/2245 to try to resolve this. Note that the PR upgrades them to the latest patch versions, but I didn't revert the previous change as it applied only to non-production code.

**Comment by shakuzen** [comment]
A heads up that I'm going to revert this upgrade. It has reintroduced a bug as described in #2293. Backporting the changes from 1.5.x to 1.3.x would present more risk and change in a patch release than downgrading this shaded dependency. I apologize for the inconvenience of having to deal with security scanners giving false positives, but I have to give priority to issues with real negative impact.
