### ISSUE TITLE
Return fixed (fake) values in prometheus export for e.g. simple manual testing of alerts

### ISSUE THREAD

**Issue by bjung82** [micrometer-metrics/micrometer#2243]
Hi,

micrometer works really good :-) But it would event be better, if there would be
a simple way to fiddle around with metrics values right before export ;-)

I think about implementing a feature in our application to set value x for metric y to z for a certain time t
(e.g. 5 Minutes). This way, we could verify our whole monitoring/alerting stack is working e.g. for a new
alert rule. It seems all metrics are directly passed to some prometheus client libraries by micrometer. This prometheus lib produces the file provided by /metrics. But there is no simple place to hook into this mechanism and change some values before
writing the file out in the servlet.

Any idea anyone? :-)

Regards
Benjaming

**Comment by checketts** [comment]
You could create an endpoint that returns a hardcoded value and point Prometheus to it. (You could make it fancy by having your endpoint pull the metrics out of Micrometer and massaging them, but if you just want to hard code a response, that isn't needed)

I'm not sure there would be any benefit to adding this feature to Micrometer itself.

**Comment by bjung82** [comment]
The idea is to test scraping/alerting in a real system. I don't want to trick prometheus into scraping another endpoint like /metrics2 for this case, I want to use the infrastructure already in place. /metrics should simply return a fixed value for a single metric, and the other metrics are working normal (return real values). If this would be possible, I could test alerting in a very simple way, without (temporarily) changing any prometheus/alertmanager configs.

It would be nice to have a simply way for this in micrometer itself, because this way such a feature could be used for all kind of export formats.

**Comment by bjung82** [comment]
I have opened a PR in the prometheus-client project that will handle this case.
There will be a new parameter "ValueFilter" on the prometheus "TextFormat".

https://github.com/prometheus/client_java/pull/628

You can think about providing this functionality in the Micrometer wrapper, too.
Otherwise one has to simply override io.micrometer.prometheus.PrometheusMeterRegistry.scrape(Writer)
which is public anyway.

If you don't plan to provide/wrap the Value filter (if the PR above is accepted) you can close this issue.

BTW: Micrometer is awesome :-)
