### ISSUE TITLE
Upgrade google-cloud-monitoring to 2.x

### ISSUE THREAD

**Issue by loicmathieu** [micrometer-metrics/micrometer#2249]
Upgrade google-cloud-monitoring dependency to the 2.x version line.

I have a cloud library where I use the Google Cloud library BOM and starting with the 9.x version of the library BOM it includes a 2.x version of the google-cloud-monitoring.
This causes the dependency being upgraded in a version not compatible with micrometer-registry-stackdriver.

**Comment by shakuzen** [comment]
We'll need to consider our options here - e.g. if we can support both in one module or should make a new module for the 2.x SDK.

**Comment by pebo** [comment]
Are the google-cloud-monitoring 2.x+ versions supported by micrometer-registry-stackdriver or does it only work with the 1.x versions?

**Comment by shakuzen** [comment]
There were breaking changes in 2.0.0 that caused us to pin to 1.x in #2235. Interestingly, I tried upgrading locally and did not see that failure just now.
@loicmathieu would you (or anyone else) be able to check if things work for you with the latest version of the Google Cloud library BOM and Micrometer? If so, it seems there aren't any changes required on our side.

**Comment by shakuzen** [comment]
As far as my testing could tell, things are working with the latest version of google-cloud-monitoring 2.x now without changes in Micrometer. I tried with google-cloud-monitoring 2.3.3 and with the libraries-bom 20.6.0 (which manages google-cloud-monitoring to 2.3.0). I have upgraded the version we compile against in main to the latest, which will be published as 1.8.0-SNAPSHOT.

> Are the google-cloud-monitoring 2.x+ versions supported by micrometer-registry-stackdriver or does it only work with the 1.x versions?

@pebo As far as I can tell, it works with the latest 2.x version. Please let us know if you run into any issues.

Closed by #2660

**Comment by pebo** [comment]
> As far as my testing could tell, things are working with the latest version of google-cloud-monitoring 2.x now without changes in Micrometer. I tried with google-cloud-monitoring 2.3.3 and with the libraries-bom 20.6.0 (which manages google-cloud-monitoring to 2.3.0). I have upgraded the version we compile against in main to the latest, which will be published as 1.8.0-SNAPSHOT.
> 
> > Are the google-cloud-monitoring 2.x+ versions supported by micrometer-registry-stackdriver or does it only work with the 1.x versions?
> 
> @pebo As far as I can tell, it works with the latest 2.x version. Please let us know if you run into any issues.
> 
> Closed by #2660

I tested micrometer-registry-stackdriver 1.7.0 with google-cloud-monitoring 2.3.3 without any problems 👍  The [breaking changes in google-cloud-monitoring  2.x](https://github.com/googleapis/java-monitoring/blob/master/CHANGELOG.md#200-2020-08-10) doesn't seem to affect micrometer-registry-stackdriver as far as I can tell.

**Comment by shakuzen** [comment]
Thank you for trying it out and reporting back to us. I've [updated our documentation](https://github.com/micrometer-metrics/micrometer-docs/issues/178) to add a note that the Micrometer Stackdriver registry can be used with google-cloud-monitoring versions 1.x and 2.x.

**Comment by loicmathieu** [comment]
Thanks all for testing it! That's good news ;)
