### ISSUE TITLE
Prometheus calculates strange percentile values

### ISSUE THREAD

**Issue by DepraTb** [micrometer-metrics/micrometer#2254]
Spring-based application, Spring Boot version '2.0.3.RELEASE', so io.micrometer:micrometer-core version '1.0.5'

I use DistributionSummary for recording some simple values to Prometheus:
```
DistributionSummary summary = DistributionSummary
    .builder(metricName)
    .tags(someTags)
    .publishPercentiles(0.5, 0.75, 0.95, 0.98, 0.99, 0.999)
    .register(meterRegistry);
```
```
summary.record(someValue);
```
After I record value '2' and have metrics:
```
summary_metric{unimportantTags, quantile="0.5",} 2.0
summary_metric{unimportantTags, quantile="0.75",} 2.0
summary_metric{unimportantTags, quantile="0.95",} 2.0
summary_metric{unimportantTags, quantile="0.98",} 2.0
summary_metric{unimportantTags, quantile="0.99",} 2.0
summary_metric{unimportantTags, quantile="0.999",} 2.0
summary_metric_count{unimportantTags,} 1.0
summary_metric_sum{unimportantTags,} 2.0
summary_metric_max{unimportantTags} 2
```
Looks good, but after that I record value '418':
```
summary_metric{unimportantTags, quantile="0.5",} 2.0
summary_metric{unimportantTags, quantile="0.75",} 431.875
summary_metric{unimportantTags, quantile="0.95",} 431.875
summary_metric{unimportantTags, quantile="0.98",} 431.875
summary_metric{unimportantTags, quantile="0.99",} 431.875
summary_metric{unimportantTags, quantile="0.999",} 431.875
summary_metric_count{unimportantTags,} 2.0
summary_metric_sum{unimportantTags,} 420.0
summary_metric_max{unimportantTags,} 418.0
```
Why does the P75 (or higher) percentile have a strange value 431.875? Why these percentiles greater than max value?

The result won't change much if I record the greater values sequence:
419,427,419,426,22,419,429,22,421,22,422,419,425,22,419,22,23,419,22,418,429,418,419,419,22, etc.
Some percentiles still will be greater than max and have strange values.

Updating Spring Boot to the latest version (2.3.3.RELEASE) and correspondingly updating the io.micrometer:micrometer-core version to the latest version (1.5.4) doesn't resolve this issue.

Could you please help me with understanding this behavior? In my opinion, this looks like a bug, because I think there is no formula by which percentiles are calculated this way.

**Comment by DepraTb** [comment]
I cloned this repo and locally wrote some test:
```
MockClock clock = new MockClock();
MeterRegistry registry = new SimpleMeterRegistry(new SimpleConfig() {
    @Override
    public String get(String key) {
        return null;
    }

    @Override
    public CountingMode mode() {
        return CountingMode.STEP;
    }
}, clock);

DistributionSummary summary = DistributionSummary.builder("test")
                                                 .publishPercentiles(0.5, 0.75, 0.95, 0.98, 0.99, 0.999)
                                                 .register(registry);
```

and was playing with some recording values.

For example, I recorded three times the value 418, I expected that all percentiles will be equal to this value, but I got:
`[(416.0 at 50.0%), (416.0 at 75.0%), (416.0 at 95.0%), (416.0 at 98.0%), (416.0 at 99.0%), (416.0 at 99.9%)]`

Ok, I decided to diversify recording values and use this approach:
```
for (int i = 0; i < 1000; i++) {
    summary.record(i);
}
```
And I got this result:
`[(511.9375 at 50.0%), (767.9375 at 75.0%), (959.9375 at 95.0%), (991.9375 at 98.0%), (991.9375 at 99.0%), (1023.9375 at 99.9%)]`

Not only is the P100 percentile(max value is 999) less than the P99.9 percentile, so also P98 and P99 percentiles are equal to each other, which cannot be with such amount of records.

It looks like an attempt to give not an exact value, but to fit the nearest value.

**Comment by jkschneider** [comment]
@DepraTb Micrometer performs a percentile _approximation_ that converges with more and more values. To calculate true percentiles requires _every sample that was ever seen_ which consumes an increasing amount of memory with more samples.

**Comment by DepraTb** [comment]
I resolved my problem with not accurate numbers in this way:
```
DistributionSummary summary = DistributionSummary
    .builder(metricName)
    .tags(someTags)
    .publishPercentiles(0.5, 0.75, 0.95, 0.98, 0.99, 0.999)
    .percentilePrecision(precision) // <-- here
    .register(meterRegistry);
```
Setting percentilePrecision value works and makes percentiles calculations more accurate. The value should be between 0 and 5. The higher the degrees of precision, the more accurate the approximation is, but it will require more memory and time.
