### ISSUE TITLE
jvm.gc.memory.allocated confusion

### ISSUE THREAD

**Issue by wind57** [micrometer-metrics/micrometer#2259]
I do not know if this was already tackled, but I have a few miss-understandings with `jvm.gc.memory.allocated`.

 - First [is the description of the property](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java#L118):

> Incremented for an increase in the size of the young generation memory pool after one GC to before the next

I read it probably 100 times, on 3 different days (I kid you not), I am _still_ not sure what it is supposed to present. After looking at [how it is computed](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java#L177), it seems like it just generates the total amount of bytes that were allocated via the _young space_.

So, if I have an Eden of `100 MB` and if everything from Eden is cleared on the GC cycle (i.e. : `final long youngAfter = after.get(youngGenPoolName).getUsed()` is zero -> this is why a young GC exists to begin with), then the value of: `jvm.gc.memory.allocated` should be increased with `~100MB` at each cycle. I say `~` because there could be a trigger for a  Full GC (that in turn will trigger a young GC), and at that point Eden might contain less than `100MB`.

So, in general, as far as I read the code : this value will increase, constantly. 

And second, why not have a description that is easier to grasp? May be:

> total amount of memory allocated via the Eden Space (or young space).

I also have to rant about `jvm.gc.memory.allocated` itself; in case there are humongous allocations. Those will not be captured by this metric, but the fact that the metric does not have _young_ in its name might cause confusion, so may be include it? I know that the description has it, but do people _actually_ read it? Just my 0.02$.

Thank you.

**Comment by jkschneider** [comment]
Getting late here, but I can tackle the easy part of this question:

> this value will increase, constantly.

It is a `Counter`, and that is exactly what counters do. Generally, we view counters as rates in a monitoring system, and that's what you're looking for in this case: what is the size of new allocations happening in an interval.

I could be convinced of a description update.

> in case there are humongous allocations. Those will not be captured by this metric

Humongous allocations are visible in GC metrics, where "humongous" allocation is one of many possible causes.

**Comment by wind57** [comment]
thank you for the humongous reference - I did look at the code and saw that now, much appreciated. 

So, I guess, if you would take a description update into account - I would be entirely satisfied. 

Thank you for your time.

**Comment by izeye** [comment]
For your information, the description has been updated in 6d3fec0a3acaa2c3f17effcf71fcb8b04149ad5d as follows:

> Incremented for an increase in the size of the (young) heap memory pool after one GC to before the next

The main question has been answered, so this issue seems to have been resolved unless the description needs to be refined more.

**Comment by jonatan-ivanov** [comment]
@wind57 I'm closing this, please let us know if this needs to be further improved.
