### ISSUE TITLE
Upgrade build to JDK 15

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2261]
[JDK 15](https://openjdk.java.net/projects/jdk/15/) is now GA. Let's upgrade the version of the JDK we're using to build Micrometer.

**Comment by izeye** [comment]
For your information, `cimg/openjdk:15.0` is available now.

See https://github.com/CircleCI-Public/cimg-openjdk/pull/62

**Comment by shakuzen** [comment]
Thanks for helping get the build image we needed, Johnny.
