### ISSUE TITLE
1.1.18 release missing micrometer-registry-prometheus POM file

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2265]
The 1.1.18 release is missing the pom files for the micrometer-registry-prometheus artifact
https://repo1.maven.org/maven2/io/micrometer/micrometer-registry-prometheus/1.1.18/

_Originally posted by @empirephoenix in https://github.com/micrometer-metrics/micrometer/pull/2197#issuecomment-694321687_

**Comment by shakuzen** [comment]
@empirephoenix thank you for reporting this. I'm looking into it.

**Comment by shakuzen** [comment]
The missing POM files have been uploaded to Bintray and another sync to Maven Central has been done - hopefully the POM will show up in Central soon. If not, I'll continue to work on this in the morning.

**Comment by shakuzen** [comment]
The POM file is available from Central now.

**Comment by empirephoenix** [comment]
Thank you 👍
