### ISSUE TITLE
Adding AWS specific dimensions when running in an AWS cloud environment using the CloudWatch metrics registry

### ISSUE THREAD

**Issue by ddewaele** [micrometer-metrics/micrometer#2268]
A question on the micrometer.io integration in spring boot / cloud. 

We are running Spring Boot microservices in an ECS Fargate Cluster. I have setup micrometer with cloudwatch integration (using micrometer-registry-cloudwatch2) and I see the spring boot metrics popping up in Cloudwatch, but I was expecting to see ECS Fargate dimensions like clustername, task arn, service name...... 

(as described here https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v3.html). 

Am I missing some configuration to expose these additional dimensions ? (I assume that this can be provided by spring cloud but don't know if such an integration has already been done).
_

**Comment by shakuzen** [comment]
If you have a way to get that information, you can configure common tags with that. I agree it would be better if that were done automatically - there's a bit of a question of who should do that where. I think there are a lot of different environments within AWS with different metadata. It could be a daunting task to manage something like that on the Micrometer side. I'm wondering if the CloudWatch SDK can/should add those dimensions itself. We are using the CloudWatch SDK to publish the metrics, after all.

**Comment by mpatnode** [comment]
@ddewaele DId you (or anyone else) figure out an easy way to do this?

**Comment by jonatan-ivanov** [comment]
@mpatnode You can add common tags: https://micrometer.io/docs/concepts#_common_tags in Boot there is a property for this so you can get them easily from environment variables if you want.

I would open an issue for the CloudWatch SDK to add these tags.
(Maybe Spring Cloud AWS could do that too but I would start with the CloudWatch SDK)

**Comment by shakuzen** [comment]
As mentioned in my previous comment, I don't think it is sustainable for us to maintain tagging AWS environment-specific metadata in Micrometer itself. If it were added to the AWS SDK itself, it would be available to everyone and should be more maintainable in an AWS-specific project maintained by AWS. I would encourage users that want this to open an issue with the CloudWatch SDK team.

As @jonatan-ivanov mentioned, you can always configure common tags yourself with some code if you want this metadata in the meantime.

**Comment by mpatnode** [comment]
> @mpatnode You can add common tags: https://micrometer.io/docs/concepts#_common_tags

Thanks!  Found that myself and it did exactly what I wanted.   That's the solution AFAIC.
