### ISSUE TITLE
Log count but don't update stats for Timer

### ISSUE THREAD

**Issue by krasnyt** [micrometer-metrics/micrometer#2269]
Hi, I am using `Timer` for recording delays of market data ticks from a remote exchange. Some market data contain the creation timestamp at the exchange and some don't in which case I am assigning the current timestamp at my side in the system. This effectively means a delay of 0. 
Recording such value into a timer does increment the count but it also affects the statistics such as `mean`. 

Is there a way to do the `count` increment without updating the stats? I don't want to lose the information that an event came (`count`) but also I don't want to affect the stats by the artificial 0 delay (`mean`).

Thank you.

**Comment by shakuzen** [comment]
Could you explain more what is your goal or desired result? The `mean` is the `totalTime` / `count`, so it makes sense for it to be affected by events that took 0 time. That said, I doubt the `mean` will be particularly meaningful as a representation of these delays unless the delays are close to a normal distribution (bell curve). If you still want to be able to track the mean without zero time events, you could use a Counter for zero time events and only record non-zero events with the Timer.

**Comment by krasnyt** [comment]
My goal is to see two metrics:
1) the average delay (but only where I actually have the delay)
2) the number of total events received

But thanks to your answer I realised that what I want doesn't make sense. As you said, it has to be separate, one metric for the delay and another separate metric for the count. 

Thank you, closing.
