### ISSUE TITLE
Inconsistencies between Executor, ExecutorService and ScheduledExecutorService metric naming

### ISSUE THREAD

**Issue by slovdahl** [micrometer-metrics/micrometer#2274]
There are currently some inconsistencies in the naming between timed `Executor`s, `ExecutorService`s and `ScheduledExecutorService`s. The actual timings of tasks run in the thread pools are called `executor.execution` if the monitored type is an `Executor`, but if it's  an `ExecutoService` or `ScheduledExecutorService` it's only called `executor` (disregarding any prefixes). This subtle difference feels counter-intuitive, and makes graphing and alerting harder because both types need to be taken into account.

I know that changing these would be a breaking change, so I'm mainly opening this issue to gauge interest in the change at all, in case this is something that could be considered for a future Micrometer 2.0 version.

From Micrometer 1.5.5:

```java
public TimedExecutor(MeterRegistry registry, Executor delegate, String executorName, String metricPrefix, Iterable<Tag> tags) {
    this.registry = registry;
    this.delegate = delegate;
    Tags finalTags = Tags.concat(tags, "name", executorName);
    this.executionTimer = registry.timer(metricPrefix + "executor.execution", finalTags);
    this.idleTimer = registry.timer(metricPrefix + "executor.idle", finalTags);
}

...

public TimedExecutorService(MeterRegistry registry, ExecutorService delegate, String executorServiceName,
                            String metricPrefix, Iterable<Tag> tags) {
    this.registry = registry;
    this.delegate = delegate;
    Tags finalTags = Tags.concat(tags, "name", executorServiceName);
    this.executionTimer = registry.timer(metricPrefix + "executor", finalTags);
    this.idleTimer = registry.timer(metricPrefix + "executor.idle", finalTags);
}

...

public TimedScheduledExecutorService(MeterRegistry registry, ScheduledExecutorService delegate,
                                     String executorServiceName, String metricPrefix,
                                     Iterable<Tag> tags) {
    this.registry = registry;
    this.delegate = delegate;
    Tags finalTags = Tags.concat(tags, "name", executorServiceName);
    this.executionTimer = registry.timer(metricPrefix + "executor", finalTags);
    this.idleTimer = registry.timer(metricPrefix + "executor.idle", finalTags);
    this.scheduledOnce = registry.counter(metricPrefix + "executor.scheduled.once", finalTags);
    this.scheduledRepetitively = registry.counter(metricPrefix + "executor.scheduled.repetitively", finalTags);
}
```

**Comment by marcingrzejszczak** [comment]
We're not planning to do a Micrometer 2.0 any time soon. Is there anything else we could to help you out?

**Comment by marcingrzejszczak** [comment]
I see. Ok, let's close this one for now then since we're not planning to change things at this point. If anyone else would think that we should change our decision please comment on the closed issue.
