### ISSUE TITLE
Log level for micrometer influx registry

### ISSUE THREAD

**Issue by elue** [micrometer-metrics/micrometer#229]
`2017-11-16 12:01:47.722  INFO 25786 --- [spectator-spring-metrics-publisher-0] io.micrometer.influx.InfluxRegistry      : successfully sent 42 metrics to influx`

I would rather log this at 'DEBUG' level. 

Micrometer version: 0.12.0.RELEASE with spring boot 1.5.8

**Comment by jkschneider** [comment]
INFO level is consistent with passthru instrumentations like Spectator, so I think we'll keep it as is. Appreciate the feedback, though.

Feel free to suppress in your logs with: `logging.level.io.micrometer.influx: WARN` in your application.yml.

**Comment by elue** [comment]
Ok, Yes I have done that.
