### ISSUE TITLE
Disable system.out metrics while calling actuator/prometheus

### ISSUE THREAD

**Issue by moshere** [micrometer-metrics/micrometer#2294]
Hi,
I'm using micrometer with Spring boot for prometheus.
Everything is ok, however every time I'm calling actuator/prometheus application dumps all the metrics to stdout.
Is there any way to disable this dump to stdout. It's spamming my logs and make it unreadable.

Thank you
Moshe

**Comment by checketts** [comment]
The `actuator/prometheus` doesn't do that by default. Have you added a `LoggingMeterRegistry` or some other thing that logs our response values to the console?

**Comment by moshere-fb** [comment]
Hi,
We're using only `MeterRegistry` to add gauge metric.
We're not using `LoggingMeterRegistry`

**Comment by checketts** [comment]
@moshere In that case I'm not certain why that is happening. Do you have some sort of debug logging enabled? Perhaps posting details of what is being logged could give a hint.

**Comment by moshere-fb** [comment]
Here is an example of what we're getting:
```
jvm_buffer_count_buffers{id="direct",} 2.0
jvm_buffer_count_buffers{id="mapped",} 0.0

# HELP jvm_gc_pause_seconds Time spent in GC pause
# TYPE jvm_gc_pause_seconds summary
jvm_gc_pause_seconds_count{action="end of major GC",cause="Metadata GC Threshold",} 1.0
jvm_gc_pause_seconds_sum{action="end of major GC",cause="Metadata GC Threshold",} 0.036
jvm_gc_pause_seconds_count{action="end of minor GC",cause="Metadata GC Threshold",} 1.0
jvm_gc_pause_seconds_sum{action="end of minor GC",cause="Metadata GC Threshold",} 0.011
# HELP jvm_gc_pause_seconds_max Time spent in GC pause
# TYPE jvm_gc_pause_seconds_max gauge
jvm_gc_pause_seconds_max{action="end of major GC",cause="Metadata GC Threshold",} 0.036
jvm_gc_pause_seconds_max{action="end of minor GC",cause="Metadata GC Threshold",} 0.011
```

We're running regular spring boot with no special debugging flags

**Comment by shakuzen** [comment]
Could you please provide a minimal sample application that reproduces this behavior? I have never seen the described behavior in apps I have run.

**Comment by shakuzen** [comment]
I'm closing this for now, we can reopen it once we have a minimal sample project that reproduces the described issue.

**Comment by mirceade** [comment]
NVM, my bad. Was actually having logbook log the actual contents of the prometheus plugin endpoint when it was invoked. So not something to do with micrometer per-se, sorry for that.
