### ISSUE TITLE
Micrometer - @Counted and @Timed

### ISSUE THREAD

**Issue by patpatpat123** [micrometer-metrics/micrometer#2299]
Hello Micrometer,

First of all, big thanks for this amazing project.

Small question regarding Java and the use of Micrometer.
We have been using the annotations @Counted and @Timed.

We are very happy about those two annotations. They are doing the job very well, and we can see the metrics related to the method with those annotations, i.e. the count of a method invoked, the timed elapsed for a method execution. All in a very clear annotation way. Really cool.

It is trivial count is not time, but why count and time are different things and represented by two different annotations?
I was just wondering the design choice behind the two.

Because technically, a time is also a count. For instance, if I say "It took me 2 minutes and 12 seconds to eat this orange". Technically, if I annotate @Timed, I would have expected 2 minutes and 12 seconds, but also a count of 1, since the action did happen, and the action happened taking 2 minutes and 12 seconds. Why would a @Counted be needed in addition in order to get the count? 

Overall, this is just a simple question, a @Timed event is by definition also a count of this event happening. Why differentiate the annotations? Is it possible @Timed can offer the information?

Thank you

**Comment by checketts** [comment]
The way you described how you believe `@Timed` should work is accurate and to my understanding is exactly how it currently is working. 

Could you try to create a minimal project that reproduces the behavior you are seeing?

**Comment by shakuzen** [comment]
> Why would a @counted be needed in addition in order to get the count?

It isn't need in addition. Micrometer `Timer`s include a count. You would use one or the other.

> a @timed event is by definition also a count of this event happening. Why differentiate the annotations? Is it possible @timed can offer the information?

Not all things can be easily timed, so sometimes we can only count them with a Counter. In the case of the annotations, I agree that an annotated method can always be timed, but sometimes the extra metrics about timing are not interesting for some reason and only the count is. If the timing information is interesting, then only using `@Timed` provide metrics on timing and count.

[Timers always report a count](https://micrometer.io/docs/concepts#_timers). See also the [note in the documentation for `Counters`](https://micrometer.io/docs/concepts#_counters):

> Never count something you can time with a `Timer` or summarize with a `DistributionSummary`! Both `Timer` and `DistributionSummary` always publish a count of events in addition to other measurements.

**Comment by patpatpat123** [comment]
This is a very clear explanation @shakuzen
Many thanks
