### ISSUE TITLE
CloudWatch Registry should split batches also by byte size to prevent RequestEntityTooLarge

### ISSUE THREAD

**Issue by holyjak** [micrometer-metrics/micrometer#2302]
I am getting this error hen using cloudwatch registry:

> AmazonCloudWatchException: Request size 47947 exceeded 40960 bytes (Service: AmazonCloudWatch; Status Code: 413; Error Code: RequestEntityTooLarge

I can decrease the batch size to try to prevent it but it would be better if the registry itself took the smaller of (batch size records, records with total size below 40960)

The 40kB limit is mentioned here: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudwatch/AmazonCloudWatchClient.html#putMetricData-com.amazonaws.services.cloudwatch.model.PutMetricDataRequest-

**Comment by shakuzen** [comment]
We can also consider gzip compressing the metrics payload. At a max of 20 metrics per payload, I'm surprised you're reaching the limit as is.

**Comment by holyjak** [comment]
Yes, gzip sounds good too.

Long stack traces I guess :-)

**Comment by holyjak** [comment]
Sory, my bad, I guess I mixed up logs and metrics. Sorry!
