### ISSUE TITLE
Support ZGC in JvmGcMetrics

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2305]
Similar to #1861 for ZGC.

**Comment by crohit** [comment]
Hi @shakuzen  - sorry to bug on this old post with this question, but I recently upgraded to zgc for a repo at work and am wondering what are the metrics available for zgc. 

```
action:end_of_gc_pause,cause:proactive
action:end_of_gc_pause,cause:warmup
```

These are the only ones I see. Are there more metrics I should be seeing? Including any other `causes` and `actions`?

**Comment by shakuzen** [comment]
> Are there more metrics I should be seeing? Including any other `causes` and `actions`?

Not until more actions and causes happen in your application after `JvmGcMetrics` is bound to a registry. The metrics are dynamically registered in response to GC notifications. Until GC events happen in your application, there won't be any metrics recorded for them. We do not register metrics for GC events until they happen. You could, for example, force a GC in your application (with e.g. `System.gc()` or JMX or `jconsole`) and see GC metrics recorded in response to that. Does that make sense and clear up what's happening?

**Comment by crohit** [comment]
> > Are there more metrics I should be seeing? Including any other `causes` and `actions`?
> 
> Not until more actions and causes happen in your application after `JvmGcMetrics` is bound to a registry. The metrics are dynamically registered in response to GC notifications. Until GC events happen in your application, there won't be any metrics recorded for them. We do not register metrics for GC events until they happen. You could, for example, force a GC in your application (with e.g. `System.gc()` or JMX or `jconsole`) and see GC metrics recorded in response to that. Does that make sense and clear up what's happening?

Ah yeah that clears up- Let me go back and look into this. Are there other notifications which are emitted on GC that I know I should look out for when a GC is run?

**Comment by shakuzen** [comment]
> Are there other notifications which are emitted on GC that I know I should look out for when a GC is run?

We don't keep an exhaustive list because it is up to what the garbage collector has implemented, which can change between versions of the JVM. Unfortunately, I'm not aware of good documentation on this from each collector either.
