### ISSUE TITLE
Add method tagKeys(Collection<String> keys) to Search

### ISSUE THREAD

**Issue by Styopa1769** [micrometer-metrics/micrometer#2310]
There is a method in [https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/search/Search.java](url):
```java
 /**
   * Meter contains a tag with the matching keys.
   *
   * @param tagKeys The tag keys to match.
   * @return This search.
   */
  public Search tagKeys(String... tagKeys) {
      requiredTagKeys.addAll(Arrays.asList(tagKeys));
      return this;
  }
```
I think that there may occur double work, because i (may be not only me) want to pass to this method List or another Collection.
So, i have to convert Collection/Iterable to Array, then in method my array is converting to List again
Why there is not method like that:
```java
    public Search tagKeys(Collection<String> tagKeys) {
        requiredTagKeys.addAll(tagKeys);
        return this;
    }
```
?
I think that two methods with another parameter type are not a problem.

**Comment by izeye** [comment]
@Styopa1769 Thanks for the issue. I created https://github.com/micrometer-metrics/micrometer/pull/2349 to try to resolve this.
