### ISSUE TITLE
[Feature request] Add an ability to change / add prefix in MongoMetrics* classes

### ISSUE THREAD

**Issue by otlg** [micrometer-metrics/micrometer#2329]
Current implementation of MongoMetrics* either hard coded or private final definition for metrics prefix. 

It will be nice to get an ability to override or extend it. 

This can be useful if more than 1 MongoClientSettings is used.

**Comment by shakuzen** [comment]
See #2360 and #2437 which recently added tags providers to the mongo metrics. Rather than a meter name prefix, you could configure an additional tag like `client` with a client identifier for each of your different clients. Would that be sufficient for your needs?

**Comment by shakuzen** [comment]
Closing due to lack of feedback. As mentioned in the previous comment, you can add a tag now to distinguish different clients. For dimensional metrics, this is better than using a metric name prefix, which would result in different metric names for the same type of measurement.
