### ISSUE TITLE
CumulativeCounter imports Google AtomicDouble

### ISSUE THREAD

**Issue by philwebb** [micrometer-metrics/micrometer#234]
I think [this import](https://github.com/micrometer-metrics/micrometer/blob/afeb04598c03e1c204e57d4aa0895308f7366edf/micrometer-core/src/main/java/io/micrometer/core/instrument/simple/CumulativeCounter.java#L18) is probably wrong and it should be the JDK `AtomicDouble`.

**Comment by philwebb** [comment]
FWIW we also hit this a lot in Spring Boot and ended up setting a [checkstyle rule](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-parent/src/checkstyle/checkstyle.xml#L76) to prevent it.

**Comment by jkschneider** [comment]
Fixed with #238
