### ISSUE TITLE
Histogram buckets between 0 and 1 in DistributionSummary

### ISSUE THREAD

**Issue by ajain22** [micrometer-metrics/micrometer#2341]
I am using Micrometer core 1.1.9 version and trying to create histogram with 10 buckets between 0 and 1. But as per DistributionSummary config, I am not able to pass minimum expected value less than 1. Below is my config, 

```
DistributionStatisticConfig distStatCfg =
		            DistributionStatisticConfig.builder()
		                                       .percentilesHistogram(true)
		                                       .percentiles(buckets)
		                                       .percentilePrecision(2)
		                                       .minimumExpectedValue(1L)
		                                       .maximumExpectedValue(1L)
		                                       .build();
```

I need this to capture model scores that lies between 0 and 1.

**Comment by shakuzen** [comment]
1.1.9 is quite old and the 1.1.x line is no longer supported. It's a good idea to check with the latest version when opening an issue.

The way to handle this use case is explained in the documentation: see the section Distribution summaries → [Scaling and histograms](https://micrometer.io/docs/concepts#_scaling_and_histograms).
As explained there, we have a set of buckets that are not fully configurable.
Your configuration `.percentiles(buckets)` probably does not do what you're hoping; [see the JavaDoc](https://www.javadoc.io/static/io.micrometer/micrometer-core/1.6.5/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.Builder.html#percentiles(double...)).
You can use `serviceLevelObjectives` to effectively add buckets, though. While not ideal, this is a way to cover your use case currently. See an example:

```java
MeterRegistry registry = new SimpleMeterRegistry();
DistributionSummary summary = DistributionSummary.builder("my.summary")
        .publishPercentileHistogram()
        .maximumExpectedValue(100d)
        .scale(100)
        .serviceLevelObjectives(10, 20, 30, 40, 60, 90)
        .register(registry);

summary.record(0.15);
summary.record(0.55);
summary.record(0.9);

System.out.println(summary.takeSnapshot()); // HistogramSnapshot{count=3, total=160.0, mean=53.333333333333336, max=90.0, histogramCounts=[(0.0 at 10.0), (1.0 at 20.0), (1.0 at 30.0), (1.0 at 40.0), (2.0 at 60.0), (3.0 at 90.0)]}
```

Let us know if that's sufficient for your use case.

**Comment by shakuzen** [comment]
Closing due to lack of feedback. We can reopen if there is a change to be made based on any feedback.
