### ISSUE TITLE
Configurable _source.enabled  Elastic mapping property

### ISSUE THREAD

**Issue by jvmlet** [micrometer-metrics/micrometer#2357]
Would you  please make `_source.enabled` mapping property configurable (see [this ](https://stackoverflow.com/questions/57427480/spring-boot-with-micrometer-elasticsearch-registry-indexes-only-empty-documents)for reference ). 
It's easier to develop  Kibana dashboards and debug custom counters publishing with this  attribute turned on.
In production  it  will be turned off.
I'm talking about `TEMPLATE_BODY_AFTER_VERSION_7` field in  `ElasticMeterRegistry` class :

````java
private static final Function<String, String> TEMPLATE_BODY_AFTER_VERSION_7 = (indexPrefix) -> "{\n" +
            "  \"index_patterns\": [\"" + indexPrefix + "*\"],\n" +
            "  \"mappings\": {\n" +
            "    \"_source\": {\n" +
            "      \"enabled\": false\n" + // configurable 
            "    },\n" + TEMPLATE_PROPERTIES +
            "  }\n" +
            "}";
````

Thanks

**Comment by izeye** [comment]
@jvmlet Thanks for the issue. This seems to be a duplicate of https://github.com/micrometer-metrics/micrometer/issues/1629.

**Comment by jvmlet** [comment]
Closing in favor of #1629
