### ISSUE TITLE
[Question] Why not design sla,minimum and maximum ExpectedValue in @Timed annotation

### ISSUE THREAD

**Issue by liuhu** [micrometer-metrics/micrometer#2367]
In `@Timed` annotation,  why not design such as sla,minimumExpectedValue,maximumExpectedValue configurations interface about histogram. 
I used `TimedAspect` to process my service measurement.  And we have different measurement scenarios require different buckets.
Thanks.

**Comment by jkschneider** [comment]
The original reasoning was that you could simply enable advanced features like this through a `MeterFilter`, so there was no reason to overcomplicate the annotation.

**Comment by liuhu** [comment]
Yes, In Spring actuator autoconfigure we can use `MetricsProperties` config histogram buckets,  which will work with `PropertiesMeterFilter`  on `Timer` builder.  
But, I don't think that this is a good way. Because It separated the same configuration in two places. 
So I customized a new `Timed` annotation, `TimedAspect` and `WebMvcMetricsFilter` to support config histogram properties.

**Comment by liuhu** [comment]
> The original reasoning was that you could simply enable advanced features like this through a `MeterFilter`, so there was no reason to overcomplicate the annotation.

Yes, In Spring actuator autoconfigure we can use MetricsProperties config histogram buckets, which will work with PropertiesMeterFilter on Timer builder.
But, I don't think that this is a good way. Because It separated the same configuration in two places.
So I customized a new Timed annotation, TimedAspect and WebMvcMetricsFilter to support config histogram properties.
Thank you for your patient answer.
