### ISSUE TITLE
Timer.record() API with checked exception supplier

### ISSUE THREAD

**Issue by jvmlet** [micrometer-metrics/micrometer#2381]
Please provide API to record time with function callback that throws exception : 
```` java
private Object myFunctionIWantToMeasure() throws SomeException{
}
return Timer.builder("name")
  .tag("tagName", tagValue)
  .register(registry)
  .record(this::myFunctionIWantToMeasure);
````
instead of
````java
final Timer.Sample sample = Timer.start(registry);
                    final Timer timer =  Timer.builder("name")
                            .tag("tagName", tagValue)
                            .register(registry);
                    try {
                        return myFunctionIWantToMeasure();
                    } finally {
                        sample.stop(timer);
                    }
````

One also possible to provide tag name (`result` ? ) for `success` or `error` invocation result : 
````java
return Timer.builder("name")
  .tag("tagName", tagValue)
  .register(registry)
  .record(this::myFunctionIWantToMeasure,"result","success","error");
````

**Comment by shakuzen** [comment]
For the first part, I think the `recordCallable` method is what you are looking for. See [the documentation](https://micrometer.io/docs/concepts#_recording_blocks_of_code).

**Comment by jvmlet** [comment]
Thanks, but for the second part,  by `record(this::myFunctionIWantToMeasure,"result","success","error")` I meant that the tag with name `result` will be populated with value `success` or `error`, depending whether or not the  method has thrown exception.
It will require timer registration be postponed till method completes (exceptionally or not)

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
