### ISSUE TITLE
Expose Hystrix metrics on time taken by http requests

### ISSUE THREAD

**Issue by fiunchinho** [micrometer-metrics/micrometer#239]
I'm using Feign and Hystrix to make http calls to other services. I'd like to expose metrics on the time taken by those requests so I can graph the latency between services, having different projections for different HTTP status codes and paths.

**Comment by checketts** [comment]
Currently the Hystrix metrics only track success/fallback counts. We need to add in the timing metrics. 

See https://github.com/ahus1/prometheus-hystrix/blob/master/src/main/java/com/soundcloud/prometheus/hystrix/HystrixPrometheusMetricsPublisherCommand.java#L145

**Comment by jkschneider** [comment]
This all makes good sense to support, given that Spring Cloud has Feign as a supported path.
