### ISSUE TITLE
Prometheus  http_server_requests_seconds_bucket{le="+Inf"} value randomly incorrect during high load

### ISSUE THREAD

**Issue by jtorkkel** [micrometer-metrics/micrometer#2394]
Scrape Prometheus metrics from uservice running micrometer which is configured to collect also http_server histogram and quantiles.

Query for generating Grafana heatmap, template variable filtering removed from query:
sum(rate(http_server_requests_seconds_bucket{}[$range])) by (le)

Grafana heatmap dashboard shows randomly long response time for +Inf with count -0.033 following value 0.033 in next scrape. This cause glitches to metrics,

Detailed analysis indicates that max value never exceed 4s, but there is change in values between 30.0 and +Inf.
http_server_requests_seconds_bucket{le=~".Inf|30.0"}
http_server_requests_seconds_max

Detailed dumps from Prometheus raw metrics
le="+Inf" values
99060 @1609756122.131
102076 @1609756152.134  **# too low value, 1 smaller than 30.0**
105008 @1609756182.131
107932 @1609756212.131

le="30.0" values
99060 @1609756122.131
102077 @1609756152.134  **# correct value for 30s**
105008 @1609756182.131
107932 @1609756212.131

The issue happen only during high load which hint that generating +Inf value from largest bucket value is not "atomic". 

**Environment:**
scrape interval: 30s
Micrometer 1.5.9
Java 8 192
Linux

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
