### ISSUE TITLE
Blow up or warn when @Timed has no name on @Scheduled

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#24]

**Comment by checketts** [comment]
How does`@Timed` behave on non-`@Scheduled` methods? (IE if `SomeBean.doWork()` were annotated)

**Comment by jkschneider** [comment]
Right now, it's just used to instrument `@Scheduled`, and `@RequestMapping` (and the `@GetMapping` type variations). So it would do nothing.

Presumably we could add a pointcut to do something similar for an arbitrary method. For scheduled and request mappings, I'm trying to get the necessary changes in to spring framework 5.+ so that you don't need AOP at all.

**Comment by szpak** [comment]
It would be good to mention it in the documentation. I had spent some time before I found that issue trying to explain why my `@Timed`-annotated method with a non `@RestTemplate` remote server call doesn't generate any metrics...

**Comment by shakuzen** [comment]
I'm not sure what the full context was here and it is very old at this point. I will close this until we can resurface details about the issue we wanted to fix.
