### ISSUE TITLE
Use immutable map 

### ISSUE THREAD

**Issue by padilo** [micrometer-metrics/micrometer#241]
Checking the code I saw the following:

https://github.com/micrometer-metrics/micrometer/blob/afeb04598c03e1c204e57d4aa0895308f7366edf/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L653-L667

If I use a meter that has a dynamic tag for instance getting the counter as follows:

```
counter = registry.counter("my.metric.custom", "my-tag", tagValue);
```

That would end up using a lock to just check the counter already exists and created if not, if using its cache, or just create my own counter cache, which I think it shouldn't be necessary.

I don't know if there is way to use this kind of metrics that are a bit dynamic without ending in the contention it will give you a lock... If there isn't, I suggest to implement that Map using immutable maps, which will allow to use the double check and just locking in case the Map needs to be modified (reconstructed).

I can PR that you want.

**Comment by jkschneider** [comment]
@padilo Looks like your example was cut off. Meter ids are already immutable. Could you elaborate?

**Comment by padilo** [comment]
Yep, sorry. I rewrite the whole thing.

Yes, the problem is the `meterMap` attribute on the `MetricRegistry`, that isn't immutable and to register a new metric or even check if there is one to add it, it will end up on a synchronized block. Which may be fine if register is only use it once, but not if you have metrics that are not completely static or you need to rely on the list of Meter the `MetricRegistry` has.

Sorry If I don't explain it too well

**Comment by jkschneider** [comment]
@padilo There was an extensive look at the synchronization behavior in #227, and we concluded that this is the best we can do. I don't know what immutable map construct you have in mind, but if you even want to just sketch this out roughly, I'd be interested in looking at it.

@smaldini suggested that using an atomic guard with a `for ;;` might be better, but I haven't wrapped my mind around that pattern yet.
