### ISSUE TITLE
Description of process_start_time_seconds metric needs to be fixed in PushGateway as well as in the Prometheus client

### ISSUE THREAD

**Issue by vlaguduva** [micrometer-metrics/micrometer#2413]
As  per ["Writing libs from Prometheus website"](https://prometheus.io/docs/instrumenting/writing_clientlibs),  Help string of the metric "process_start_time_seconds" needs to be "Start time of the process since unix epoch in seconds." but Micrometer has "Start time of the process since unix epoch."; I understand that value kept in this metric is of unit milli seconds, nevertheless, the metric still named as seconds. Please change the help string as required. If required, please add additional metric process_start_time_milliseconds; This will also fix the long pending push gateway specific issue related to this very same metric.

**Comment by shakuzen** [comment]
My understanding of that document is not that the help string MUST be exactly as shown there. What problem does it cause you for the help string to not match that exactly?

> I understand that value kept in this metric is of unit milli seconds

The value is not reported in milliseconds; it is scaled to seconds because that is what Prometheus expects. Other registries may have different preferences. We don't specify the final unit in the description because it differs by meter registry.

> This will also fix the long pending push gateway specific issue related to this very same metric.

I don't know what issue this is referencing.

**Comment by shakuzen** [comment]
If you really wanted to change the description of that meter for the Prometheus registry, you could register a `MeterFilter` like the following on the PrometheusMeterRegistry (again note that you would not want to register this filter for other registries that do not use seconds as their base time unit):

```java
new MeterFilter() {
    @Override
    public Meter.Id map(Meter.Id id) {
        if (id.getName().equals("process.start.time")) {
            return new Meter.Id(id.getName(), Tags.of(id.getTagsAsIterable()), id.getBaseUnit(), "Start time of the process since unix epoch in seconds.", id.getType());
        }
        return id;
    }
}
```

Until there is some demonstrated problem to fix, I'm going to close this issue for now. Please let us know if I've missed something.

**Comment by vlaguduva** [comment]
Thanks for providing more information.

While the metric description is not pressing for the regular client, it is breaking push gateway for sure. 
Example log :
> >> Metric families 'name:\"process_start_time_seconds\" help:\"Start time of the process since unix epoch.\" and name:\"process_start_time_seconds\" help:\"Start time of the process since unix epoch in seconds.\"....have inconsistent help strings. The latter will have priority. This is bad. Fix your pushed metrics!"

Fixing the metric description will make metric as required by Prometheus + fixes the push gateway issue.

**Comment by shakuzen** [comment]
That's a shame that the push gateway is fussing about help strings. We can add the workaround to the [`PrometheusRenameFilter`](https://github.com/micrometer-metrics/micrometer/blob/d212d90cd8ec9097770d5056306e1f136ac0b1f3/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusRenameFilter.java) to make it a little easier to apply to your projects.

**Comment by shakuzen** [comment]
From my understanding of the [Prometheus Pushgateway docs](https://github.com/prometheus/pushgateway#about-metric-inconsistencies), the inconsistent help strings do not result in lost metrics; rather one of the help strings is chosen for that metric name.

> Inconsistent help strings are tolerated, though. The Pushgateway will pick a winning help string and log about it at info level.

I haven't tested myself, but this documentation seems to be at odds with you saying it results in an error. It should just be a log message and no error.

**Comment by mweirauch** [comment]
@vlaguduva what version of Prometheus PushGateway are you running? There've been numerous discussions about this and also metrics with different label sets being pushed to PG in their issue tracker. IIRC the Micrometer project also faced one issue. I can't find the exact bug report (yet), but I am pretty sure the issue was relaxed two/three years ago starting with the 0.5.x and 0.6.x releases.

**Comment by vlaguduva** [comment]
Thanks for looking into this issue further.

I have been using v0.80 and it returns 500 on inconsistent help strings.

Now I have updated to v1.3.1; it prints the same error with better wording; let you know if it causes problem.

**Comment by vlaguduva** [comment]
I could figure out the issue.
The issue is not with the inconsistent help strings, definitely nothing to do with Micrometer.
Metrics collected by Pushgateway grows over the time and a scrape call by prometheus times out and prometheus server starts reporting that pushgateway is down.
Non issue for Micrometer, sorry about that.

**Comment by shakuzen** [comment]
Thanks for the follow-up, and I'm glad you were able to get to the root cause of the issue.
