### ISSUE TITLE
Improve performance while initializing KafkaMetrics

### ISSUE THREAD

**Issue by kptfh** [micrometer-metrics/micrometer#2415]
This code in `KafkaMetrics` leads to quadratic complexity. 
```
metrics.forEach((name, metric) -> {
    for (Meter other : registryMetersByNames.getOrDefault(meterName, Collections.emptyList())) {
    }
}
```
Faced very poor performance while running  a lot of Kafka consumers and producers (over 400)

**Comment by jonatan-ivanov** [comment]
Fixed in https://github.com/micrometer-metrics/micrometer/pull/2416
