### ISSUE TITLE
micrometer create large number of objects, cause GC  !

### ISSUE THREAD

**Issue by darren-fu** [micrometer-metrics/micrometer#2423]
we use micometer to record performance metrics.
but we found micormeter will create too many objects in thsi process.
this is a jmap -histo output table, u will find a lot of micrometer objects.

``` shell
 num     #instances         #bytes  class name
----------------------------------------------
   1:       4741082      968442160  [C
   2:        788953      152126984  [B
   3:       4576102      109826448  io.micrometer.core.instrument.ImmutableTag
   4:       2291099       91643960  io.micrometer.core.instrument.Meter$Id
   5:       2284617       91384680  java.util.IdentityHashMap$ValueIterator
   6:       2377958       75750832  [Ljava.lang.String;
   7:        163382       66828760  [I
   8:       1140468       63866208  io.netty.channel.DefaultChannelHandlerContext
   9:       2495266       59886384  java.lang.String
  10:       1446974       57878960  io.netty.util.DefaultAttributeMap$DefaultAttribute
  11:       2287807       55440880  [Lio.micrometer.core.instrument.Tag;
  12:       2287807       54907368  io.micrometer.core.instrument.Tags
  13:        989755       39590200  io.netty.handler.codec.DefaultHeaders$HeaderEntry
  14:       2305090       36881440  java.lang.Integer
  15:       2251963       36031408  io.micrometer.core.instrument.MeterRegistry$$Lambda$255/765702264
  16:       2251963       36031408  io.micrometer.core.instrument.MeterRegistry$$Lambda$257/45703335
  17:        673322       34702584  [Ljava.lang.Object;
  18:        508264       32528896  io.netty.util.concurrent.ScheduledFutureTask
  19:        145615       19803640  io.netty.channel.epoll.EpollSocketChannel
  20:        685478       16451472  java.lang.Long

```
the code we useto record.
``` java
DistributionSummary.builder("api.call.performance")
                        .tags("path", req.getPath(),
                                "upstream.path", mappingPath,
                                "upstream.service", serviceName,
                                "status", statusCode)
                        .publishPercentileHistogram(false)
                        .sla(sla)
                        .register(Metrics.globalRegistry).record(cost);
```

has any one meet problem like this ?

**Comment by jonatan-ivanov** [comment]
Do any of your tags contain any high cardinality data? E.g.: Can the path contain a (resource) ID?
From the jmap output it seems so. Please see the docs why is this a misusage: https://micrometer.io/docs/concepts#_tag_values

Try to remove the path tag and see if the issue disappears. If so do not attach the full path tag: e.g.: do not attach `/users/5f2561d8-2e97-4703-b008-abab8f5dc8ac` but attach `/users` instead.

**Comment by darren-fu** [comment]
no,  we only have regular path like `/getUser`
i try to use prometheus_client api directly,and the GC count per minute is reduced.
![image](https://user-images.githubusercontent.com/8833871/106581689-2078bb80-657e-11eb-9f8f-e33436bd86ef.png)

-------
in micrometer, we will use `xxx.builder()` every time when we want to record some metrics.
In my opinion, i think it will create many  duplicate objects like `Tag,Tags, Meta.Id`， then GC happens more often.

**Comment by jonatan-ivanov** [comment]
Could you please do two things?
1. Could you please show us what is the prometheus output for this metric?
1. Could you please check if it is better if you remove the tags?

**Comment by darren-fu** [comment]
1. the metrics out put like this.
``` shell
gateway_api_performance_bucket{path="/fl_test/bbbb",upstream_path="/bbbb",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="10.0",} 1.0
gateway_api_performance_bucket{path="/fl_test/bbbb",upstream_path="/bbbb",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="50.0",} 1.0
gateway_api_performance_bucket{path="/fl_test/bbbb",upstream_path="/bbbb",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="100.0",} 1.0
gateway_api_performance_bucket{path="/fl_test/bbbb",upstream_path="/bbbb",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="500.0",} 1.0
gateway_api_performance_bucket{path="/fl_test/bbbb",upstream_path="/bbbb",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="1000.0",} 1.0
gateway_api_performance_bucket{path="/fl_test/bbbb",upstream_path="/bbbb",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="+Inf",} 1.0
gateway_api_performance_count{path="/fl_test/bbbb",upstream_path="/bbbb",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",} 1.0
gateway_api_performance_sum{path="/fl_test/bbbb",upstream_path="/bbbb",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",} 2.0
gateway_api_performance_bucket{path="/fl_test/cccc",upstream_path="/cccc",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="10.0",} 1.0
gateway_api_performance_bucket{path="/fl_test/cccc",upstream_path="/cccc",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="50.0",} 1.0
gateway_api_performance_bucket{path="/fl_test/cccc",upstream_path="/cccc",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="100.0",} 1.0
gateway_api_performance_bucket{path="/fl_test/cccc",upstream_path="/cccc",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="500.0",} 1.0
gateway_api_performance_bucket{path="/fl_test/cccc",upstream_path="/cccc",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="1000.0",} 1.0
gateway_api_performance_bucket{path="/fl_test/cccc",upstream_path="/cccc",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",le="+Inf",} 1.0
gateway_api_performance_count{path="/fl_test/cccc",upstream_path="/cccc",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",} 1.0
gateway_api_performance_sum{path="/fl_test/cccc",upstream_path="/cccc",upstream_service="fl_test",upstream_host="127.0.0.1:9090",status="200",downstream_service="mes",} 2.0

```
2. No, I didn't try that,because these tags are usesful to me, and we have exactly the same tags when we use prometheus_client API.

**Comment by checketts** [comment]
The `Metrics.globalRegistry` is a CompositeRegistry which in turn publishes to a PrometheusRegistry. So perhaps the double registry might have an impact? Is it possible you have a MeterFilter only on the PrometheusRegistry, so tags are normalized in one registry but not the other?

**Comment by darren-fu** [comment]
no `MeterFilter` defined in my project.
only have a `namingConvention` to remove the `_total ` suffix.

-----------------
code like this:
``` java
CompositeMeterRegistry compositeRegistry = Metrics.globalRegistry;
PrometheusMeterRegistry prometheusMeterRegistry = 
new PrometheusMeterRegistry(PrometheusConfig.DEFAULT,CollectorRegistry.defaultRegistry, Clock.SYSTEM);

compositeRegistry.add(prometheusMeterRegistry);

compositeRegistry.config().namingConvention(new SelfPrometheusNamingConvention());
prometheusMeterRegistry.config().namingConvention(new SelfPrometheusNamingConvention());

private static class SelfPrometheusNamingConvention extends PrometheusNamingConvention {
        @Override
        public String name(String name, Meter.Type type, @io.micrometer.core.lang.Nullable String baseUnit) {
            String nameAfterConvention = super.name(name, type, baseUnit);

            String end = "_total";
            if (nameAfterConvention.startsWith(GATE_WAY)
                    && nameAfterConvention.endsWith(end)) {
                return StringUtils.removeEnd(nameAfterConvention, end);
            }
            return nameAfterConvention;
        }
    }

```

**Comment by izeye** [comment]
@darren-fu Based on the attached heap dump, 2,291,099 `Meter`s seem to have been registered somehow. Is it an expected number of meters for you? If not, could you attach the full output from the Prometheus scrape endpoint to see what makes the cardinality explosion?

**Comment by darren-fu** [comment]
sorry, the full output of prometheus which contains data from our product env, I can‘t post it here.

-----
But the the number of meter is  2291099,and it's not necessary, because after CMS GC in old heap，most
data will be removed(over 1000M)， only 50M data left in old heap.

--------
So my point is, micrometer create many unnecessary and duplicate objects when we use the `Builder` api to create `Metric instrument` like `Count` or `Timer` .

**Comment by izeye** [comment]
@darren-fu Apologies for the confusion. I thought that a `Meter.Id` intance was created per a `Meter` instance somehow, but actually, `Meter.Id` instances could be created temporarily.

They seem to be expected to be garbage-collected shortly, so I'm not sure why they were not garbage-collected during young GCs prior to old GCs.

**Comment by izeye** [comment]
I tried to reproduce this with [a sample project](https://github.com/izeye/sample-micrometer-spring-boot/tree/micrometer-gh-2423) based on the attached code snippet above, but the number of `Meter.Id` instances didn't grow that much.

@darren-fu It would be helpful if you could share a minimal yet complete sample project that reproduces it and how to reproduce it with the sample project.

**Comment by darren-fu** [comment]
ok, i will try to reproduce this with a demo project, that will spend some time for this.

**Comment by shakuzen** [comment]
@darren-fu were you able to put together a sample project that we can run? We appreciate the time you've spent helping investigate this.

**Comment by shakuzen** [comment]
If you can provide a minimal sample project for us to investigate, we can reopen the issue. Closing for now due to lack of feedback.
