### ISSUE TITLE
Springboot with micrometer/prometheus: disabling and enabling some specific metrics at runtime

### ISSUE THREAD

**Issue by ltosetti75** [micrometer-metrics/micrometer#2446]
Hi, we know that it's possible to enable/disable micrometer metrics on a per-meter basis using properties, in particular setting management.metrics.enable.=true/false, but we would need something more dynamic (without deploy and restart of the springboot application). Our need would be to enable/disable some metrics on the fly, by reading a value set on an external database (for example, a table with a column for metric names and a column as a flag for "enable/disable"), and polling that table every minute, for example. So the scenario that we imagine is an external table where someone can update a record setting some metric's name to "enable" or "disable", and our SpringBoot module keeps updated with this table and consequently enable/disable the corresponding metrics. In your opinion, is this possible, and in case, which is the best approach to use for this kind of scenario?

I tried to make use of micrometer meterFilters like below, but, as described in some other posts, they work permanently, so after a deny call the metric is disabled forever:

meters.config().meterFilter(MeterFilter.denyNameStartsWith(metricName));

PS: I also read about spring cloud (config server) for externalization of properties that can be refreshed at runtime, maybe not the right solution, anyway I tried to explore it, but it doesn't work with springboot properties, it works only with custom properties on the external properties file. So if I try to overwrite a property like management.metrics.enable.mymetricname=true with management.metrics.enable.mymetricname=false and viceversa, and checking with a curl the prometheus endpoint after an http /refresh, it works only the first time.

Thanks in advance for every support or suggestion.

**Comment by jonatan-ivanov** [comment]
Closing this in favor of: https://stackoverflow.com/questions/66150801/springboot-with-micrometer-prometheus-disabling-and-enabling-some-specific-metr
