### ISSUE TITLE
Micrometer not publishing outbound metrics with multiple Rest Template beans

### ISSUE THREAD

**Issue by ramya257** [micrometer-metrics/micrometer#2457]
I want to know if there is any limitation in micrometer that it would measure RestTemplate metrics only with the bean name "restTemplate" or it can measure metrics across multiple rest templates beans registered using qualifier. Please suggest how to proceed.

**Comment by checketts** [comment]
Are your creating the RestTemplate yourself or via the RestTemplate builder? If not using the builder, are you binding it to a meter registry yourself?  Perhaps if you include some code samples we could offer more insight. 

But the short answer is there shouldn't be any limitation.

**Comment by shakuzen** [comment]
As @checketts said, as long as you are using the auto-configured `RestTemplateBuilder` that Spring Boot provides, you should have metrics for all `RestTemplate`, per the [Spring Boot documentation](https://docs.spring.io/spring-boot/docs/2.4.x/reference/htmlsingle/#production-ready-metrics-http-clients). Let us know if that does not clear up the issue.
