### ISSUE TITLE
TimedAspect work only with ElementType.METHOD

### ISSUE THREAD

**Issue by diablont** [micrometer-metrics/micrometer#2458]
Target of annotation @Timed ElementType.TYPE and also in TimedAspect.java i see comment: "AspectJ aspect for intercepting types or methods annotated with @Timed.", but single aspect in code is @Around("execution (@io.micrometer.core.annotation.Timed * *.*(..))").
I may be wrong, but I think need to add @within(@io.micrometer.core.annotation.Timed)

**Comment by jonatan-ivanov** [comment]
@diablont Thank you for spotting this. I agree, if the intention is to measure every method in a class annotated with `@Timed`, the current pointcut is not sufficient.

@shakuzen @jkschneider Do you remember the original intention here?
Is the `@Target` of the `Timed` annotation is wrong (btw `ANNOTATION_TYPE` is there too) or the pointcut in `TimedAspect` should be fixed?

**Comment by jonatan-ivanov** [comment]
Connected to #493

**Comment by shakuzen** [comment]
Duplicate of #493
