### ISSUE TITLE
Update Caffeine

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#2465]
Caffeine `3.0.0` has been released recently (https://search.maven.org/artifact/com.github.ben-manes.caffeine/caffeine) with some breaking changes, micrometer supports 2.x (https://github.com/micrometer-metrics/micrometer/commit/766fa07804c819a86c4cb7269e4cd752e8a99eee).

**Comment by ben-manes** [comment]
I believe the only change that impacts this project is `StatsCounter`. This can be made backwards compatible by retaining the deprecated `recordEviction()` method and removing the `@Override`. It should cross compile.

**Comment by izeye** [comment]
@ben-manes Thanks! I created https://github.com/micrometer-metrics/micrometer/pull/2476 to try to resolve this.

**Comment by jonatan-ivanov** [comment]
Fixed in #2478
