### ISSUE TITLE
Micrometer's `DistributionSummary` API doesn't allow to define fractional `minimumExpectedValue` and `maximumExpectedValue`, such as `0.25` and `0.75` 

### ISSUE THREAD

**Issue by yskopets** [micrometer-metrics/micrometer#248]
#### Issue

`Micrometer` 's `DistributionSummary` API doesn't allow to define fractional `minimumExpectedValue` and `maximumExpectedValue`, e.g. `0.25` and `0.75` 

E.g., consider a metric that represents a `ratio` ( i.e.,  `amount granted / amount requested`  ):
* all metric values fall into interval `[0, 1]`
* to limit the number of exported buckets, I'd like to be able to set `minimumExpectedValue == 0.1`

#### Observed behaviour

Current `DistributionSummary` API doesn't support such  a use case

#### Affected versions

v1.0.0-rc.4

**Comment by jkschneider** [comment]
Micrometer's preselected buckets are all integers from 1 to +Inf. Currently `minimumExpectedValue`/`maximumExpectedValue` serve to control the cardinality of the bucket set. 

If we attempt to detect that your min/max yields a small range and scale the preselected bucket domain to your summary's range, then we don't have another lever to control bucket cardinality.

I'm going to add what I hope is a _good enough_ solution to what I hope is a rare problem by allowing you to instead scale your summary's range by a fixed factor.

```
DistributionSummary.builder("my.ratio").scale(100).register(registry)
```

This way, `amount granted / amount requested` winds up in the range `[0, 100]` and we can set `maximumExpectedValue = 100`. Pair this with custom SLA boundaries if you care about particular ratios:

```
DistributionSummary.builder("my.ratio")
   .scale(100)
   .sla(70, 80, 90)
   .register(registry)
```

I realize that this changes the scale on your charts, but hopefully this is a good enough compromise!
