### ISSUE TITLE
Possibility to add returned value to tags in Timed and Counted aspects

### ISSUE THREAD

**Issue by uvalashchuk** [micrometer-metrics/micrometer#2481]
Thanks for the lib!

Currently we're using `TimedAspect` and `CountedAspect` to record method metrics and we're faced an problem when we need to filter metrics depending on what value method returned. 

In our case we want to record metrics from only method with `@Timed` which returned `true`. In our case we can't afford to throw an exception or inject `MeterRegistry` to our beans with business logic. With this enhancement we could add returned value to tags and utilize `MeterFilter` then.

I think it could be done in same manner as `tagsBasedOnJoinPoint` feature is done because it's not always needed to tag a metric with return value.
https://github.com/micrometer-metrics/micrometer/blob/7d8c0500a1f573d79b3cc056191c281394ab28ad/micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java#L115

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
