### ISSUE TITLE
node exporter support (?) with prometheus

### ISSUE THREAD

**Issue by naarani** [micrometer-metrics/micrometer#2488]
If an application could not expose metrics for some reason, Prometheus has the option to push data from the application to a Node Exporter, then Prometheus will pull data from the Node Exporter

Is this kind of management supported?

**Comment by checketts** [comment]
Could you post an example of how you would do that with the prometheus client? You can get the `CollectorRegistry` that Micrometer is wrapping and use it directly.

**Comment by mweirauch** [comment]
@naarani are you perhaps talking about the Prometheus PushGateway and Prometheus scraping that? The usecase you describe sounds exactly like that. If so, that's already possible with Micrometer.

**Comment by naarani** [comment]
yes, thank you.  Do you have some references for this configuration with Micrometer? thanks

**Comment by mweirauch** [comment]
You might want to have a look at the [Spring Boot docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-export-prometheus) or - if you are not using Spring Boot - at the [Spring Boot AutoConfiguration](https://github.com/spring-projects/spring-boot/blob/v2.3.9.RELEASE/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/export/prometheus/PrometheusMetricsExportAutoConfiguration.java) to get an idea of what needs to be done.

**Comment by shakuzen** [comment]
Closing as I believe this has been answered with https://github.com/micrometer-metrics/micrometer/issues/2488#issuecomment-793472542
