### ISSUE TITLE
Add `Timer.record(long count, long amount, TimeUnit unit)`

### ISSUE THREAD

**Issue by ars-java** [micrometer-metrics/micrometer#2490]
It will be good to have method `Timer.record(long count, long amount, TimeUnit unit)` to add custom value to internal `LongAdder`. For example, I have a process that writes lists of models (size `n`) to storage. Each write operation is atomic and I can't calculate time for single model, just for list. It's not good to call `Timer.record` `n` times. I just wanna one call `Timer.record(n, 5, SECONDS)`

The same for methods `record(Supplier)`, `record(Runnable)` and others. It will be reasonable to write code:
```
timer.record(n, () -> { ... });
```

**Comment by ars-java** [comment]
Any comments about this enhancement?

**Comment by jonatan-ivanov** [comment]
I'm not sure I understand the use-case. If you write n items to a storage with a single write operation, you want to measure that single operation. You don't know how much time would writing a single element take unless you write them one-by-one, right?

**Comment by ars-java** [comment]
Chunks of data can have not the same size. For example I can read them from Kafka, accumulate by time (or smth else) and then write to some storage as batch using single HTTP request. I wanna calculate total count of elementary documents (not chunks) and total time to write these documents. I wanna calculate total time and total count of documents (not chunks).

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
