### ISSUE TITLE
Add timer implementation (or method to `Timer`) that counts error cases too

### ISSUE THREAD

**Issue by ars-java** [micrometer-metrics/micrometer#2491]
For example, I have a process that can fail and I wanna record it's time and counts the number of fails. I need create 1 Timer and 1 Counter for each such case and duplicate such code:
```
try {
    timer.record(() -> {... })
} catch (e: Exception) {
    errorCounter.increment()
    throw e;
}
``` 
I think that it's a common case and it's good to have such standard implementation in the library. It's good to have default naming for such `errorCounter` too.

**Comment by shakuzen** [comment]
There isn't a need for a separate counter. Timers include a count, and a tag can be used to distinguish between successful and exceptional cases. You can see an example of the prototypical usage for this case in our implementation of the TimedAspect:

https://github.com/micrometer-metrics/micrometer/blob/996db4af032b4cc9f65f5793657bf9eb5c7ebb12/micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java#L100-L123

It would be good to include guidance on this in the documentation, which seems to currently be lacking.

I think the ask here is for the above handling to be applied by Micrometer when using the timer methods that take a Runnable or Callable. This sounds similar to the second part of #2381. I'm not sure how much of an opinion we want to have on the exception tagging or lack thereof. We can consider it, though. Perhaps we could take a strategy for tagging based on the exception and provide an implementation, but still leave it up to the user whether to use it or not.
