### ISSUE TITLE
Fails to build GraalVM executable with "Classes that should be initialized at run time"

### ISSUE THREAD

**Issue by dayman** [micrometer-metrics/micrometer#2492]
After adding micrometer-registry-statsd to dependencies graalvm fails with following
```
io.micrometer.shaded.io.netty.util.internal.PlatformDependent was unintentionally initialized at build time. To see why io.micrometer.shaded.io.netty.util.internal.PlatformDependent got initialized use --trace-class-initialization=io.micrometer.shaded.io.netty.util.internal.PlatformDependent

io.micrometer.shaded.io.netty.util.internal.PlatformDependent0 was unintentionally initialized at build time. To see why io.micrometer.shaded.io.netty.util.internal.PlatformDependent0 got initialized use --trace-class-initialization=io.micrometer.shaded.io.netty.util.internal.PlatformDependent0

```

**Comment by shakuzen** [comment]
This is likely a consequence of our shading netty and that not translating GraalVM substitutions or other configurations to the `io.micrometer.shaded` package. To be sure, though, could you try with the latest versions and if it is still an issue, provide a sample project with instructions to reproduce?

**Comment by shakuzen** [comment]
Were you able to make a sample to reproduce this, @dayman?

**Comment by shakuzen** [comment]
Closing for now. We can reopen if we have a way to reproduce (like a sample project) the issue.
