### ISSUE TITLE
Timer is missing Field dimension

### ISSUE THREAD

**Issue by bogdanTeut** [micrometer-metrics/micrometer#2496]
It would be very useful for Timer to support Fields (along with Tags). Probably my use case very specific to InfluxDB. But what happens currently is, publishing all the metadata for a metric as tags leads to a series explosion in InfluxDb. 
Having fields in Timer and publishing then together with other fields that are published(e.g. mean, max, etc) would fix the issue.

Anything like that in your backlog yet?

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
