### ISSUE TITLE
java.net.http.HttpClient metrics

### ISSUE THREAD

**Issue by Lhaaits** [micrometer-metrics/micrometer#2511]
I didn't find any open tickets about this, so I'm shooting in this issue.
I noticed when using the java 11 java.net.http.HttpClient, I don't see the http.client.request metrics appear in prometheus. Is this not supported yet? Or am I missing something? All other default metrics are visible, just not my calls with the HttpClient

I'm using micrometer-core 1.3.5

**Comment by shakuzen** [comment]
We haven't had any requests for it so far, so we don't have instrumentation for it currently. Also, with java.net.http.HttpClient being added in Java 11, while we support down to Java 8, we would either need to do a multi-release JAR or make a separate module that is Java 11 based to include instrumentation for it, I think. I'm not aware of built-in support in Gradle or a stable plugin for multi-release JARs, which would be better than a separate module for one instrumentation. If someone has a proposal, we can consider it. I worry about the complexity that might be added to the build to support multi-release JARs right now.

**Comment by Lhaaits** [comment]
That's fair. I didn't realize support was up to java 8.
I suppose as a workaround I can define my own similar timers:
`Timer.Sample sample = Timer.start();
            response = httpClient.send(request, HttpResponse.BodyHandlers.ofByteArray());
            sample.stop(Metrics.timer("http.client.request", "status", String.valueOf(response.statusCode()), "uri", uriTemplate, "method", request.method()));
`

**Comment by shakuzen** [comment]
> I didn't realize support was up to java 8.

It's not up to 8 in the sense that Micrometer consumers can use later versions of Java (we build/test with the latest GA version of Java). But we support down to 8.

Maybe I was overthinking it. Since we don't need to switch classes based on Java version, perhaps we can just define a Java 11 source set and include it in the produced JAR rather than a multi-release JAR. However, I'm not sure what the correct metadata is for the JAR if part of it requires 11 while the rest is 8.

**Comment by Lhaaits** [comment]
I see, so you mean it should be backwards compatible with java 8, which did not have the java.net.http.HttpClient, so you need a way to know if you should monitor this client, depending on the version, right?

**Comment by shakuzen** [comment]
Whether to monitor any client or not is up to a user's configuration or the framework they are using. We would only provide the instrumentation for HttpClient and users can use it if they're on Java 11+ and using the HttpClient. I'm marking this for consideration in Micrometer 2.x when we may revisit our minimum supported Java version for now. If there is significant demand for this instrumentation (please thumbs up the issue to indicate your interest), we can consider making a micrometer-java11 module or such to support it sooner.

**Comment by izeye** [comment]
This seems to have been resolved via https://github.com/micrometer-metrics/micrometer/pull/3358.

**Comment by gmariottiAtWolt** [comment]
Hi @shakuzen, would it be possible to share an example project on how to use the jdk11 release in Gradle? I tried to setup a simple Kotlin project with the below files but keep getting compilation errors and can't find anything online about it.

```
❯ ./gradlew compileKotlin

> Task :compileKotlin FAILED
e: /Users/gmariotti/empty-kotlin-project/src/main/kotlin/main.kt: (1, 45): Unresolved reference: jdk
e: /Users/gmariotti/empty-kotlin-project/src/main/kotlin/main.kt: (6, 18): Unresolved reference: MicrometerHttpClient

```

```kotlin
// build.gradle.kts
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.7.20"
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "17"
}

dependencies {
    implementation("io.micrometer:micrometer-core:1.10.2")
}
```

```kotlin
// main.kt
import io.micrometer.core.instrument.binder.jdk.MicrometerHttpClient
import io.micrometer.core.instrument.simple.SimpleMeterRegistry
import java.net.http.HttpClient

fun main() {
    val client = MicrometerHttpClient.instrumentationBuilder(HttpClient.newHttpClient(), SimpleMeterRegistry()).build()
}
```

**Comment by gmariottiAtWolt** [comment]
@shakuzen issue created, let me know if there's anything I can do to help out
