### ISSUE TITLE
Apache HttpClient 5.x support

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2513]
A new major version (5) of the Apache HttpClient is available. It uses different package names for classes, so our support for major version 4 will not work with it. The implementation should be similar, if not the same, just with different packages.

**Comment by ginkel** [comment]
@shakuzen Do you have any preferences regarding the implementation (code-copy vs. sharing code w/ the v4 implementation)? We are missing this feature and could possibly offer a contribution.

**Comment by shakuzen** [comment]
Thank you for the offer to help. I have not looked into it enough to know how much could potentially be reused between the two. Generally we want to avoid a bug being fixed in one but not the other because of duplicated code, but we also don't want to overly complicate the code for the sake of reducing duplication either. So it's hard to say without taking a closer look. If you don't mind, feel free to make a judgement call on it and propose something in a pull request, and we can more easily decide with something concrete.

**Comment by shakuzen** [comment]
Thank you for starting the work @tommyk-gears. We have merged a copy of the Apache HttpClient 4 support adapted for changes in Apache HC 5. I still believe having the instrumentation closer to the library would be a better experience for users (this issue would not have been needed because the instrumentation would presumably have been updated when the breaking changes were made from version 4). Unfortunately, no Apache HttpClient users have requested Micrometer support in the Apache HttpClient project that I'm aware of. The Micrometer team would be happy to advise and review any work to do such, but in the meantime, to unblock users of Apache HttpClient 5, we have made something available in Micrometer.

**Comment by flozano** [comment]
any chance to have this backported to a stable release? the current version of spring stack uses apache http client 5 and it becomes impossible to have  proper metrics for an apache-client-backed RestRemplate with spring 6

**Comment by jonatan-ivanov** [comment]
@flozano I don't think this should or will be backported but it will be released in 1.11.0 (planned release date: 2023-05-08).

**Comment by flozano** [comment]
I see. The 1.11.0 release seems to be coming pretty soon, so it is probably OK.

Thanks for considering it.
