### ISSUE TITLE
Weird count value for counters using micrometer-registry-statsd

### ISSUE THREAD

**Issue by ayeletmorris** [micrometer-metrics/micrometer#2530]
Hi, I'm using micrometer-registry-statsd and am using counters,  I use increment(), which if I understand correctly adds 1 each time that is being invoked.
My process is a dataflow that is reading some messages and counting the amount of incoming and outgoing messages, these numbers are integers.
From reading your documentation I understand that counters uses double to save the amount, I was wondering why? This seems to be classic integer/long value.
This causes a weird behaviour in my dataDog view, I want to see the amount of incoming and outgoing messages, to verify they align, but the number is something like 127.2345678921 and not 127 or 128 as I expect it to be (I definitely don't receive 1/2 a message).

I tried to define this metric as "counter" in dataDog metric summary as well, that didn't help as well.
Can someone please advise how I can see the correct and accurate amount (I don't want to ignore the reminder of the amount)?

**Comment by shakuzen** [comment]
>  I use increment(), which if I understand correctly adds 1 each time that is being invoked.

Correct.

> From reading your documentation I understand that counters uses double to save the amount, I was wondering why?

While you only want to increment by 1 in your use case, other users have use cases for incrementing by decimal amounts.

> Can someone please advise how I can see the correct and accurate amount (I don't want to ignore the reminder of the amount)?

We send each increment to dogstatsd as a count metric. Dogstatsd is handling shipping metrics to the Datadog backend beyond that. When I just tested now, I see it is by default setting the metadata to be a rate, which is probably what results in the decimal numbers. You could still ensure that the incoming and outgoing amount is the same by comparing the rate without having the specific amount, by the way. I was also able to switch when querying the metric from `as rate` to `as count` and I got the count at each interval.

We can look into it more if you can provide a sample and steps to reproduce the issue. Let us know and we can reopen.
