### ISSUE TITLE
Kafka Metrics with spring boot

### ISSUE THREAD

**Issue by rahulKumar-dev** [micrometer-metrics/micrometer#2534]
Hi,

In my Spring boot application (v 2.3.0) I am using 
```
<dependency>
     <groupId>org.apache.kafka</groupId>
     <artifactId>kafka-clients</artifactId>
     <version>2.7.0</version>
</dependency>
```

and not sure why but micrometer is unable to pick up the kafka-clients metrics.
upon some research i came across [this](https://github.com/luiztoscano/spring-boot-kmetrics/tree/master/spring-boot-autoconfigure-kmetrics/src/main/java/org/kmetrics) library which basically does the same thing as what the official micrometer library does [here](https://github.com/micrometer-metrics/micrometer/tree/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka).

Whats strange is when i use that external library, i am able to see the metrics on the Prometheus actuator endpoint. But what i am not able to understand is why micrometer is not able to scrape those.

Any idea what could be causing this?

**Comment by jonatan-ivanov** [comment]
`MeterBinder`s need to be registered. It seems Spring Boot does not auto-configure them. The library you linked has `@Component` on the `MeterBinder`s so Spring creates a bean  for them. Try to create beans for `KafkaClientMetrics`, `KafkaConsumerMetrics `, and `KafkaStreamsMetrics`. This could be a nice addition to the Spring Boot autoconfig.

**Comment by shakuzen** [comment]
This is more of a Spring Boot usage question. You can check the Spring Boot documentation to see [what metrics it supports configuring out-of-the-box](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-meter). It supports [Kafka metrics](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-kafka) if you are using Spring Kafka. If you are not using Spring Kafka, you can configure the Micrometer metrics for the generic kafka clients as @jonatan-ivanov explained.
