### ISSUE TITLE
Some of Kafka metrics display "NaN" in prometheus

### ISSUE THREAD

**Issue by CrocoRyan** [micrometer-metrics/micrometer#2538]
Hi all,

I'm trying to inspect metrics for my springboot(v1.5.3) kafka demo with micrometer (v1.6.5)+prometheus
The version of the kafka-client was specified as 2.2.0

Though error or warnings occurred during runtime, when I scrape the metrics, some of the values show NaN, and the metrics with NaN value vary as I refreshed the link.

Below is a fragment of the result:

![image](https://user-images.githubusercontent.com/29674755/112838793-0b2c9300-90d0-11eb-9dc7-0c46db4b83f2.png)

In my demo, the "consumer-2" did polled some messages, and many other metrics worked just fine.

I saw there's a fix on a similar problem at[#2312](https://github.com/micrometer-metrics/micrometer/pull/2312), but I've already implemented the version after this fix. 

I also debugged my demo, the program never hit either 
["Prometheus requires that all meters with the same name have the same set of tag keys."](https://github.com/micrometer-metrics/micrometer/blob/b46de6e39912692999918e31a804a14aa32554dc/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L488)
or
["Failed to bind meter"](https://github.com/micrometer-metrics/micrometer/blob/b46de6e39912692999918e31a804a14aa32554dc/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java#L196)
line, which are often found in the past issues on kafka metrics

**Comment by jonatan-ivanov** [comment]
Are you using `KafkaConsumerMetrics` or `KafkaClientMetrics`. The first one is deprecated and you might need tricks to enable it on JMX which I guess can cause the behavior you see.

Could you please try to bind `KafkaClientMetrics` and see if you still have the issue?

**Comment by CrocoRyan** [comment]
I'm binding KafkaClientMetrics to the registry. 
I checked the source code in Kafka last night, and found out the cause.
It's because Kafka changed its valuation rule when computing metrics with no samples to Double.NaN since ver. 2.2.0. In earlier versions those metrics would be assigned with -Inf or 0.
Thx for the reply anyway

**Comment by jonatan-ivanov** [comment]
Makes sense, thanks for the investigation.
