### ISSUE TITLE
[Feature request] Add a sample option?

### ISSUE THREAD

**Issue by jiming** [micrometer-metrics/micrometer#254]
Some time, the metrics could be very huge, maybe 10 percent or even less sample is good enough. Is it a good idea to support a sample option?

Thanks!
Jiming

**Comment by jkschneider** [comment]
Metrics always ship aggregated statistics, so the size of the data shipped to the backend does not grow with an increase in samples. While sampling is necessary for operational insight systems like distributed tracing, it is really bad to do this with metrics data.

From Gil Tene's explanation of why Dropwizard Timer sampling is so bad:

> The Timer's internal reservoir only keeps 1028 results. The way it chooses whether or not to place a sample in the set and which one to throw away is based on a priority number that is chosen based on a weighted random number (weighted to give more recent results a higher chance). But since they are aiming at swaying towards the past 5 *minutes*, they use a 1 second granularity in selecting the weight. That means all 10,000 result collected in the same [wall clock] second are all weighted the same, and have exactly the same change of making it into the data set

> When it comes to staying around in the data set for a whole second while others come in, it's not an even chance. There will be more sway towards more recent results, as they have to stand in front of the Russian roulette for fewer turns than the older ones in the same second. So when you come in for a sample every 1 second, the more recent part of that second has a higher chance of being represented than the earlier part of the second.

> Rather than trying to do deduce all these russian-roulette dependent probabilities from a sequence of 10,000 random events, it's pretty easy to do the" "outside" math: Assuming there is no coordination between when outliers happen in the second and when in that same second you would be sampling the histogram, and knowing that 10,000 results/sec are flowing in and out of a 1,028 entry buffer, the chance of any single measured result still being in that buffer when you sample is even: any result has a ~90% probability of not showing up anywhere in your samples. That obviously applies to outliers just as much as any other result.

> In your example of a system logging 10K operations/sec with the histogram being sampled every second, you'll be missing 9 out of each 10 actual outliers. You can have an outlier every second and think you have one roughly every 10. You can have a huge business affecting outlier happening every hour, and think that they are only occurring once a day.
