### ISSUE TITLE
Add a possibility to  append rows to the MultiGauge

### ISSUE THREAD

**Issue by Fetsivalen** [micrometer-metrics/micrometer#2546]
**Issue Type:** feature request

**Problem:** There is no way to register an additional row to the MultiGauge at runtime, or I don't fin one.

**Use case:** Currently, I'm trying to record the web socket session in my application (built on top of the Spring Cloud Gateway). To do this, I need to manage different sessions amount for the different routes. It will be much more convenient to add an ability to add new rows dynamically without complete row's list recreation.

But [here](https://github.com/micrometer-metrics/micrometer/blob/1a64dd311b9458004ca3c306b2ed020f0063c320/micrometer-core/src/main/java/io/micrometer/core/instrument/MultiGauge.java#L82-L85)  there is an ability to recreate all rows, and there is no ability to add one.

** Desired Solution:**  Add additional method which allows adding row without touching others.

For example with a signature like:
```
  public void register(Row<?> row, boolean overwrite) {
//logic here
}
```

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
