### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#2547]
This issue is about renaming the default branch (`master`) to `main` in our [repos](https://github.com/micrometer-metrics).
GitHub supports this, see their [guide](https://github.com/github/renaming).

Things need to be done after the rename:
- [ ] CircleCI config fix
- [ ] Documentation update
- [ ] Updating the guides (wiki, `.md` files, etc.)
- [ ] Communicating it (Slack)

**Comment by shakuzen** [comment]
I have done the rename now for this repo. I think the rest of the tasks were taken care of by #2579 except communicating it to committers.
