### ISSUE TITLE
PrometheusMeterRegistry: better use computeIfAbsent instead of compute (Thread-Safety)

### ISSUE THREAD

**Issue by bjung82** [micrometer-metrics/micrometer#2552]
https://github.com/micrometer-metrics/micrometer/blob/b229c12b82899870d5549b55ed2cfda456dd589a/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L475

Hi, 

in our software we have a lot of threads that are started in parallel, which register a lot of metrics
for the same metric family (only the tag values differ). In some cases the first thread suceeds, the next
few threads fail, and the remaining > 200 succeed again. There is an Exception raised: Collector already registered that provides name in io.prometheus.client.CollectorRegistry.register(Collector) because of this..

Using computeIfAbsent would provide an internal lock that should prevent this situation.

Regards
Benjamin

**Comment by marcingrzejszczak** [comment]
Can you please show some benchmarks that prove this statement?
