### ISSUE TITLE
Non-existent Enum 'Type.UNTYPED' causes NoSuchFieldError

### ISSUE THREAD

**Issue by mehmetcuneyit** [micrometer-metrics/micrometer#2555]
Hi, I'm using the latest versions of below packages, 
- package: io.micrometer.micrometer-registry-prometheus version: 1.6.5
- package: io.prometheus.simpleclient  version: 0.10.0

Error:
`java.lang.NoSuchFieldError: UNTYPED
        at io.micrometer.prometheus.MicrometerCollector.describe(MicrometerCollector.java:100)
        at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:98)
        at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50)
        at io.prometheus.client.Collector.register(Collector.java:175)
        at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$applyToCollector$16(PrometheusMeterRegistry.java:412)
`

- There is no such "UNTYPED" enum defined in the prometheus simple client package (0.10.0 github reference [Collector.java](https://github.com/prometheus/client_java/blob/eb4e694b00024043f948e407510f516dea58cbc7/simpleclient/src/main/java/io/prometheus/client/Collector.java) ) 

- Check [MicrometerCollector.java#L101](https://github.com/micrometer-metrics/micrometer/blob/1.6.x/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/MicrometerCollector.java#L101) and [MicrometerCollector.java#L105](https://github.com/micrometer-metrics/micrometer/blob/1.6.x/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/MicrometerCollector.java#L105)

**Comment by shakuzen** [comment]
It's unfortunate that the Prometheus Java client made this breaking change, but there's not much we can do to support versions before and after the breaking change in the same code. See #2418 and https://github.com/prometheus/client_java/releases/tag/parent-0.10.0

Micrometer 1.6.x and earlier will support the Prometheus Java client 0.9.x and earlier. Micrometer 1.7x will support the Prometheus Java client 0.10.x and later.

You can manage the version of the Prometheus client to `0.9.0` and it will work with Micrometer 1.6.x.

**Comment by mehmetcuneyit** [comment]
I see, thanks for the suggestion. I've encountered this issue while I was working with Spring Batch 4.3.2, and it is reproducible with a simple job configuration. Thus, the error blocks executing the jobs. 
I can confirm there is no issue with the Prometheus client 0.9.0 and Micrometer 1.6.x.
