### ISSUE TITLE
Build with Gradle 7.x

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2558]
See the release notes: https://docs.gradle.org/7.0/release-notes.html

**Comment by shakuzen** [comment]
I'm getting the following error even after upgrading the nohttp plugin to 0.0.6, which should work with Gradle 7.0.

```
> Task :micrometer-benchmarks-core:checkstyleNohttp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':micrometer-benchmarks-core:checkstyleNohttp'.
> Cannot add config_loc to checkstyle.configProperties. Please configure the configDirectory on the checkstyle task instead.
```

**Comment by shakuzen** [comment]
The issue in the previous comment has been separately reported to the nohttp project as https://github.com/spring-io/nohttp/issues/44

**Comment by shakuzen** [comment]
The issue with the nohttp plugin has been fixed and I have tested with snapshots. Unfortunately we are now blocked by a different issue - our license plugin. https://ge.spring.io/s/7ufbuslo6pv5a

> Some problems were found with the configuration of task ':micrometer-benchmarks-core:licenseJmh' (type 'License').
>   - Type 'License' property 'URI' is missing an input or output annotation.
>     
>     Reason: A property without annotation isn't considered during up-to-date checking.
>     
>     Possible solutions:
>       1. Add an input or output annotation.
>       2. Mark it as `@Internal`.
>     
>     Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.

**Comment by shakuzen** [comment]
The above mentioned issue with the license plugin looks to be https://github.com/hierynomus/license-gradle-plugin/issues/179 which was fixed but has never been released. Perhaps we'll need to use a different license plugin just to get on Gradle 7.

**Comment by jonatan-ivanov** [comment]
Reopening this since I went back to 6.9 so that we can release, see: https://github.com/micrometer-metrics/micrometer/issues/2601
