### ISSUE TITLE
Fail build if potentially missing types found in method signatures

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2559]
> Sorry this keeps coming up. You'd think I would remember. I tried looking into tools/build plugins we could use to catch this but I haven't found something so far. Checkstyle and [Forbidden APIs](https://github.com/policeman-tools/forbidden-apis) didn't seem to have the feature of disallowing a method parameter or return type that matches a package pattern.

You can do these kinds of checks with ArchUnit I believe.

_Originally posted by @ThomHurks in https://github.com/micrometer-metrics/micrometer/issues/2557#issuecomment-817525806_

Indeed it seems we can. I prototyped something like the following:
```java
ArchRule noSunManagementInMethodSignatures = methods()
        .should().notHaveRawReturnType(resideInAPackage("com.sun.management.."))
        .andShould().notHaveRawParameterTypes(DescribedPredicate.anyElementThat(resideInAPackage("com.sun.management..")));
```

Thanks for the suggestions @ThomHurks.

**Comment by ThomHurks** [comment]
Glad to help!
