### ISSUE TITLE
Count the JVM GC events that happen before subscribing to notifications

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2561]
I noticed as part of investigating and testing #2514 that GC events can happen before we subscribe to notifications and those will not be counted. This will result in less GC count/time as well as lower allocated/promoted bytes than actual. We have aggregate information about GCs up until binding in the `GarbageCollectorMXBean`s. Since that is aggregate info, we can't accurately record it in timer since we lack the individual timings. It would be questionable to record the average time, but I'm not sure it is worse than missing these GC events entirely. Over time, either way becomes inconsequential, but for short-lived applications, the metrics not including events before binding could be significant.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
