### ISSUE TITLE
Changing rateUnit in JMX

### ISSUE THREAD

**Issue by brianmartinil** [micrometer-metrics/micrometer#2566]
Is there a standard way to change the rate unit using the JMX registry?  I'm looking to switch from seconds to minutes due to a limitation in our analytics platform.

**Comment by jonatan-ivanov** [comment]
You can pass a `JmxReporter` to the [`JmxMeterRegistry`](https://github.com/micrometer-metrics/micrometer/blob/56fbc92bd041ea7015a7a648d16521758760ea63/implementations/micrometer-registry-jmx/src/main/java/io/micrometer/jmx/JmxMeterRegistry.java#L42-L43) and you can [configure](https://metrics.dropwizard.io/3.1.0/apidocs/com/codahale/metrics/JmxReporter.Builder.html) the `JmxReporter` to use the unit you want.

**Comment by jonatan-ivanov** [comment]
I'm closing the issue because of the answer above, please let me know if I misunderstood something or the solution does not work and I reopen the issue.
