### ISSUE TITLE
Broken site: https://micrometer.io/docs/guide/healthAsGauge

### ISSUE THREAD

**Issue by pgpbpadilla** [micrometer-metrics/micrometer#2580]
## Expected

Not a blank page

## Actual 

A blank page

## System configuration 

Tested on: 

- OS: MacOS
- Browser: Chrome, Safari and Firefox

### Browser Network tools

```
# Request

GET /docs/guide/healthAsGauge HTTP/1.1
Host: micrometer.io
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36

# Response Preview
You need to enable JavaScript to run this app.
```

**Comment by izeye** [comment]
@pgpbpadilla Thanks for the report. It has been removed in https://github.com/micrometer-metrics/micrometer-docs/pull/126 in favor of [the corresponding section in the Spring Boot reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-map-health-indicators-to-metrics).
