### ISSUE TITLE
Timer without aggregation on client side

### ISSUE THREAD

**Issue by littlehau** [micrometer-metrics/micrometer#2590]
I am trying to use CloudWatchMeterRegistry to record a series of time.
I notice those time data points are aggregated within a step and only reports max/avg/count/sum to cloudWatch

This prevent me from calculating 95% from AWS CloudWatch.
Is there anyway to keep all individual data points or immediate publish the data by micrometer?

**Comment by jonatan-ivanov** [comment]
You can configure Micrometer to report TP95 (or any set of TP values you need), wouldn't that work?

**Comment by littlehau** [comment]
Thanks for replaying @jonatan-ivanov.
I agree with the idea of pre-aggregation resulting in less calls made to CloudWatch.

However, I would like to explain my use case in detail.
1. I have a specific task triggered by users thru an endpoint. The task takes around 60 to 300 seconds, some outlier could go more than 1000 seconds(when service has some issues)
2. When task is completed I would like to report the time to CloudWatch by MicroMeter timer.
3. The number call is probably ~10k/day.
4. StepMeter duration is 60 seconds, which generating 1440 data points per day.

At end of the day, I would like to see the p95 for all 10k data point to understand the healthiness of my system. 
If p95 is 170 seconds, I would say it's fine. 95% of the time, users experience acceptable task processing time. 
if p95 suddenly jump to 400 seconds, there is something wrong with my service clusters.

With MicroMeter, metrics data ends up with the data distributed across 1440 data points.
At peak hour, count in Timer is around 20 per data point, which is not enough get reliable p95.
Besides, micro meter already pre-aggregated the result. I can't calc p95 accurately from cloudWatch.
Considering a Timer has three data recored, two task of 60 seconds got avenged with one task of 540 seconds becomes 220 seconds. This looks good from average. but might not look good from overall p95.

I like the concept that micro meter publish data to multiple registries seamlessly with simple config.
This is the only issue so far. 

Is this because CloudWatch does not support percentile estimation?
Do I suppose to use micro meter this way?
