### ISSUE TITLE
Go back to Gradle 6.9

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#2601]
It seems that the nebula plugins we are using (coming from) the spring-release plugin are not compatible with Gradle 7.x

**Comment by jonatan-ivanov** [comment]
Resolved in: https://github.com/micrometer-metrics/micrometer/commit/93056cb0374311032b42836fd77c54dbde44271d

**Comment by shakuzen** [comment]
We could manage the version of the nebula dependencies to versions compatible with Gradle 7 (assuming they exist), but that's going more in the direction of hacking at the problem and we do have releases coming up, so this is the better solution for now.
