### ISSUE TITLE
Percentiles reported to graphite keep last value if no new measurements reported

### ISSUE THREAD

**Issue by dimovelev** [micrometer-metrics/micrometer#2612]
We use micrometer indirectly in a spring boot application to measure certain percentiles for inbound http requests. We noticed that if the requests stop arriving the last percentile value is reported with each flush to graphite. That does look like a bug or misconfiguration on our side. Unfortunately, I could not find any configuration that could change that. For example, the metrics reported in graphite are response_times.requestA.p99 and response_times.requestA.count - p99 remains at the last value even if count does not change.

**Comment by shakuzen** [comment]
Those p99 etc time series are from the underlying Dropwizard Timer. Our Graphite registry tunnels Micrometer metrics through a Dropwizard `MetricRegistry` for reporting using the Dropwizard Graphite reporter. Micrometer-configured percentiles would be published like `my.timer.percentile;phi=0.9` and would expire based on the `DistributionStatsiticsConfig`.

By default, Dropwizard Timers use the [exponentially decaying reservoir](https://metrics.dropwizard.io/4.2.0/manual/core.html#exponentially-decaying-reservoirs). We could consider changing this, but it would be a breaking change.

**Comment by leehuwuj** [comment]
Hi @shakuzen , I tried config the `DistributionStatsiticsConfig` but it doesn't works.
```
MeterFilter meterFilter = new MeterFilter() {
                @Override
                public DistributionStatisticConfig configure(Meter.Id id, DistributionStatisticConfig config) {
                    if (id.getName().startsWith("....")) {
                        return DistributionStatisticConfig.builder()
                                .expiry(Duration.ofMinutes(1))
                                .percentiles(0.99, 0.95)
                                .build()
                                .merge(config);
                    }
                    return config;
                }
            };
```
Is there any solutions to fix this issue?

**Comment by marcingrzejszczak** [comment]
Is this still a problem with the latest versions?
