### ISSUE TITLE
NPE when Tag value is null 

### ISSUE THREAD

**Issue by liuhu** [micrometer-metrics/micrometer#2615]
The metrics with finite dynamic tag of value, for example：
``` java
Metrics.counter("rpc_total",  (Tags.of("uri", getUri()))).increment();
```
When getUri method return `null` value, micrometer will throw NPE:
 
![image](https://user-images.githubusercontent.com/1286384/119312082-78aa0980-bca4-11eb-8661-52a30bf3049a.png)

**This expcetion will affect the normal execution of the code, causes our services to be unavailable.**

This issue very easy to fixed it. We can verify Tag value must be not null.
But it just an example, i don't want to verify Tag value everywhere when to use micrometer. That means everybody must to know when we use micrometer the Tag value must be not `null`, although sometimes we are not sure if it is `null` or not.

My suggestion is, **Metrics logic do not interfere with existing processes as much as possible. We can use blank string replaces the `null` value.**

``` java
public ImmutableTag(String key, String value) {
        requireNonNull(key);
        this.key = key;
        this.value = Optional.ofNullable(value).orElse("");
    }
```

Original code：
``` java
public ImmutableTag(String key, String value) {
        requireNonNull(key);
        requireNonNull(value);
        this.key = key;
        this.value = value;
    }
```

**Comment by gqhao0521** [comment]
I also think the null validation here is not valid and will make the code worse

**Comment by marcingrzejszczak** [comment]
Changing this behaviour would be a breaking change which we don't want to do. You can do a `null` before you pass a value. You have an option to verify what should be the tag value if there's no value (should it be `null`, `none`, `empty` etc.). We'll close this issue for now, if you want to talk about this please comment on this issue.
