### ISSUE TITLE
Unable to enable Micrometer Tracing

### ISSUE THREAD

**Issue by abari000** [micrometer-metrics/micrometer#2616]
I modified log4j2.xml file to have the following 

```
 <Logger name="io.micrometer.datadog" level="DEBUG"
                additivity="false">
            <Appender-ref ref="Lambda" level="DEBUG" />
        </Logger>
```

but I don't want see any output. I need to see what data gets sent to datadog

**Comment by checketts** [comment]
If you are trying to see the data sent on https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMeterRegistry.java#L131 then you need to set a TRACE level, in your example you are setting a DEBUG level.
