### ISSUE TITLE
Micrometer sends 0 values to data dog

### ISSUE THREAD

**Issue by abari000** [micrometer-metrics/micrometer#2617]
I am using the following to create custom metrics:
```java
meterRegistry.counter(name, tagsArray).increment(1);
meterRegistry.timer(name, tagsArray).record(value, TimeUnit.MILLISECONDS);
```
From the logs I can see that metrics recorded with correct values (please see attached), but when they are sent to data dogs the values are 0s. This code is running as AAWS Lambda and sometime it works but most of the time it does not. The micrometer  has direct integration with data dog as the following:

```java
static DatadogConfig config = new DatadogConfig() {
        @Override
        public Duration step() {
            return Duration.ofSeconds(5);
        }

        @Override
        public String get(String key) {
            switch (key) {
                case "datadog.apiKey" :
                    return DDAPIKey.getSecret(apiKeyName);
                default:
                    logger.info("No value specified for key=" + key + " default configuration will be used");
                    return null;
            }
        }
    };

    public static MeterRegistry createRegistry () {
        MeterRegistry registry = new DatadogMeterRegistry(config, Clock.SYSTEM);
        return registry;
    }
```

[micrometer0values.log](https://github.com/micrometer-metrics/micrometer/files/6541940/micrometer0values.log)

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
