### ISSUE TITLE
Bind cache metrics from Spring's `CacheManager`

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#262]
See https://github.com/spring-projects/spring-boot/issues/11221#issuecomment-348669359

**Comment by jkschneider** [comment]
The plan is to add an event listener somewhere in or around `CacheManager` to detect when a new cache has been added to the manager. From there, we can use `Cache#getNativeCache()` to retrieve the underlying cache and bind the correct `MeterBinder`.

**Comment by jkschneider** [comment]
We won't be able to accomplish this in Boot 1.5.x and prior.

**Comment by snicoll** [comment]
@jkschneider unfortunately, I think we have to let this one go. `javax.cache.CacheManager` has no event support for a cache being added which is a blocker on its own. I am not sure the other implementations are any easier in that area.

In the meantime, I've added auto-configuration support for caches with a service that allows you to bind the caches that are created programmatically. That doesn't work for caches created on the fly, which is quite annoying.

**Comment by jkschneider** [comment]
Just a reason to upgrade to Boot 2 :)

**Comment by jkschneider** [comment]
This was accomplished in https://github.com/spring-projects/spring-boot/commit/0515ca0dd02fec54d438d45afbf95db1b5f41353#diff-8af53ca5a010486793f937636f38863d
