### ISSUE TITLE
Silently dropping negative durations gives bad developer experience

### ISSUE THREAD

**Issue by jonmcewen** [micrometer-metrics/micrometer#2620]
Having just lost a few hours debugging a missing metric, where the calling code mistakenly calculated a negative duration, I would suggest throwing an exception in the `else` case here: https://github.com/micrometer-metrics/micrometer/blob/67c41db552cac463e44cd45545e5a7b8f3513f1b/micrometer-core/src/main/java/io/micrometer/core/instrument/AbstractTimer.java#L169

**Comment by jonatan-ivanov** [comment]
I think a log entry would make more sense, we have a `WarnThenDebugLogger`, do you want to make the change?
Btw, how did you manage to measure a negative amount? Did you use `System.currentTimeMillis()`?

**Comment by jonmcewen** [comment]
Yes, after submitting I realised that it would be rather intrusive to throw an exception from a metrics library.  I'll have a look at the logger.

The negative value was a simple develop error: 
`duration = start - now`
hence my description as bad DX.  Functionally, dropping the negative is fine, as it is meaningless, but there was nothing to help the developer see their mistake.
Of course, if they had unit tested the metrics...

**Comment by jonmcewen** [comment]
@jonatan-ivanov I can't find a `WarnThenDebugLogger`, and when I try to `./gradlew pTML` I get a 401 on hystrix-core

**Comment by jonatan-ivanov** [comment]
Here's the class: [WarnThenDebugLogger](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/util/internal/logging/WarnThenDebugLogger.java)

Here's an usage example: https://github.com/micrometer-metrics/micrometer/blob/67c41db552cac463e44cd45545e5a7b8f3513f1b/micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultGauge.java#L38

Based on the gitter messages, I guess your build issue is resolved, right?
