### ISSUE TITLE
micrometer.io is down

### ISSUE THREAD

**Issue by gjemp** [micrometer-metrics/micrometer#2626]
Error 525 Ray ID: 65674fafbe72fe58 • 2021-05-28 11:58:28 UTC
SSL handshake failed

is displayed

**Comment by raindev** [comment]
And I see a slightly different Origin is Unreachable error returned by Cloudflare:

Error 523 Ray ID: 6568553e4ddd4168 • 2021-05-28 14:57:01 UTC

**Comment by shakuzen** [comment]
Sorry for the inconvenience. We're aware of the issues. Hopefully they'll be resolved soon.

**Comment by jonatan-ivanov** [comment]
Fyi: depending on what Cloudflare cached for you previously (location, user-agent, etc.), you might be able to use the docs site, e.g.: https://micrometer.io/ works for me but https://micrometer.io/docs/concepts does not.

You can read a 3 weeks old snapshot using the wayback machine: https://web.archive.org/web/20201229212659/https://micrometer.io/

**Comment by jonatan-ivanov** [comment]
The issue seems to be resolved, it was caused by a connectivity issue at the data center were the docs site is hosted.
