### ISSUE TITLE
How to add timestamp into metric data?

### ISSUE THREAD

**Issue by XiamenGeek** [micrometer-metrics/micrometer#2627]
I can't find the method on micrometer class to add timestamp into metric data. Like this, 

> http_requests_total{method="post",code="200"} 1027 1395066363000

Anybody know about this?
I have a situation need to precisely record the metric's timestamp when the issue happend. My business logic code will renew the metric per 1 minute. If I set prometheus scrape interval as 1 minute. Sometime, it may have a gap between scape timestamp and the real timestamp when the issue happen.

**Comment by checketts** [comment]
This isn't currently supported by micrometer. You'll need to use the Prometheus client directly (assuming it is supported by that client)

**Comment by XiamenGeek** [comment]
Oops...anyway, thanks @checketts for your reply.

**Comment by shakuzen** [comment]
Why do you want to add a timestamp to the metric data in the first place? Generally it is best practice with Prometheus to defer to the thing collecting the data to handle attaching a timestamp.

**Comment by shakuzen** [comment]
> I have a situation need to precisely record the metric's timestamp when the issue happend. My business logic code will renew the metric per 1 minute. If I set prometheus scrape interval as 1 minute. Sometime, it may have a gap between scape timestamp and the real timestamp when the issue happen.

If you could help me understand the use case more, we could consider if it makes sense to support this in some way. I don't think it would be portable across registry implementations, though, so @checketts suggestion to use the Prometheus client directly for this metric may be the best idea anyways.

**Comment by XiamenGeek** [comment]
@shakuzen I means the prometheus scrape timestamp is not engough precise, may be 3 seconds, or 10 seconds (etc, depends on how much I set the prometheus scrape interval granularity)  deviation with real timestamp when issue happened.  If I set with fine-grained scrape interval, it will increase the burden of prometheus server when have bundle of metrics. If I set with coarse-grainned scrape interval, the deviation will be greater.

**Comment by shakuzen** [comment]
To clarify, the trouble I'm having understanding is the nature of a metric you want with a specific timestamp when an incident happened. It doesn't sound like a prototypical use case for metrics, which are in general aggregate data. We have metrics for GC events, we don't keep track of a timestamp when GC events happened because we keep aggregate data of them only. Same thing for HTTP server/client timings - we don't keep a timestamp of any individual recording.
Trying to bring it back to your example (which I don't grasp in enough detail), what would you want to be the output when more than one "issue happens" in a step interval? There would then be multiple timestamps for that metric then, no?

**Comment by ebullient** [comment]
I think I would map this into the "can we support prometheus exemplars" category (as exemplar data is timestamped)

**Comment by shakuzen** [comment]
Exemplars might be what the original request is describing, but I'm not sure, which is the clarification I was trying to get. Prometheus allows (though as far as I understand, discourages) specifying the timestamp for a metric, which is the format in the original issue description. It is the `timestamp` in [this section](https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information) describing the Prometheus format:

```
metric_name [
  "{" label_name "=" `"` label_value `"` { "," label_name "=" `"` label_value `"` } [ "," ] "}"
] value [ timestamp ]
```

The [OpenMetrics specification](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#metric) is more explicit about its discouragement of explicit timestamps:

> MetricPoints SHOULD NOT have explicit timestamps.

With more words on it in the [Exposing Timestamps](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exposing-timestamps) section.

If [exemplars](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars) were what is wanted, I think you can only have 1 exemplar per MetricPoint, so my question about what if two "incidents" happen in a scrape interval would remain. This is why I feel like we still need clarity on the context and specifics of the use case.

**Comment by marcingrzejszczak** [comment]
We do support exemplars with Prometheus.
