### ISSUE TITLE
Native image support investigation

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2637]
The purpose of this task is to investigate and identify what the gaps are between Micrometer metrics available on the JVM vs running as a native image (i.e. GraalVM native images).

Most things already work and we are not aware of any outright failures. We have already added some code to guard against unavailable things in native images that throw exceptions, e.g. #1948.

The result of this investigation should be tasks in Micrometer and in native image tools like GraalVM.

**Comment by shakuzen** [comment]
### What's the diff
Not an exhaustive list, but from comparing one sample application on the JVM vs compiled as a GraalVM native image I found the following.

#### Missing
The GraalVM native image was missing the following metrics:
* FileDescriptorMetrics
* ProcessorMetrics
* JvmMemoryMetrics
* JvmGcMetrics

#### Needs attention
* Classloader metrics are present (though always have a 0 value). I don't think it makes sense to register classloader metrics when running as a native image.
* `jvm.*` prefix is on various metrics. Does it make sense to keep this for native images?
* JvmThreadMetrics mostly works already. Only the metrics about thread state are missing.

### Platform MBeans
All of the things mentioned above are based on JMX MBeans.
While the JVM platform MBeans cannot be used in native images, GraalVM provides substitutions that implement some of the functionality in them where it makes sense. See work like https://github.com/oracle/graal/pull/2547.

**Comment by shakuzen** [comment]
### Micrometer tasks
- [ ] FileDescriptorMetrics reflection config
- [ ] ProcessorMetrics reflection config

### GraalVM
* [BufferPoolMXBeans and MemoryPoolMXBeans are unsupported for now](https://github.com/oracle/graal/blob/89e4cfc7aeea69970b60c64cd075ceb2a104e864/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/management/ManagementSupport.java#L139-L144)

**Comment by shakuzen** [comment]
I think this investigation is done for now. We may find additional gaps to work on in the future. I have shared my findings with the GraalVM team on what we aren't able to fix with changes in Micrometer. If there are relevant updates to GraalVM, we can take advantage of that accordingly.

**Comment by Haarolean** [comment]
@shakuzen hi, considering https://github.com/oracle/graal/issues/4510 is implemented, is there anything else that has to be done on micrometer side to make this work? Currently I don't see the required metrics within native build.

**Comment by shakuzen** [comment]
@Haarolean could you please open a new issue with the details of what isn't working as you expect and include all the necessary information about versions you're using and preferably a minimal sample project that reproduces the issue?
