### ISSUE TITLE
JvmMemoryMetrics: Provide heap used percentages for backends like InfluxDB that do not support cross measurement division

### ISSUE THREAD

**Issue by adyang** [micrometer-metrics/micrometer#2641]
Context:
JvmMemoryMetrics provides the following measurments in InfluxDB:
jvm_memory_used
jvm_memory_max

However, some metrics backend such as InfluxDB is not able to support cross measurement division (see: https://github.com/influxdata/influxdb/issues/3552).

Desired Behaviour:
Be able to obtain percentages of metrics in different supported backends such as InfluxDB.

I have seen #2198 but the reason for closure was for the fact that summing can already be done (which is true), but does not address the fact that division across measurement is not possible.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
