### ISSUE TITLE
Logback metrics not working for lombok slf4j

### ISSUE THREAD

**Issue by lensener** [micrometer-metrics/micrometer#2657]
micrometer-registry-prometheus：1.1.7
I test in two project。
the different betweent the two project is LoggerContext
![image](https://user-images.githubusercontent.com/28326573/122527965-69716e00-d04e-11eb-81c0-aa3437a2e878.png)
![image](https://user-images.githubusercontent.com/28326573/122528046-7ee69800-d04e-11eb-81a1-51690a542c8a.png)

**Comment by checketts** [comment]
If you have 2 classes in the same project, one using Lombok and one using a manually created logger, do you still see one create metrics while the other doesn't?

If you have a sample project we can inspect, that will help.

**Comment by shakuzen** [comment]
Micrometer 1.1.x is not a supported line anymore. Please try with the latest version and if the issue persists, please share a minimal sample project so we can investigate. We want to make sure we're looking for the same problem you're running into, which should hopefully save us all time and get to a solution most efficiently.

**Comment by shakuzen** [comment]
Closing due to lack of feedback. If this is still an issue on the latest versions, we can reopen and investigate with a minimal sample project that reproduces the issue.
