### ISSUE TITLE
Prometheus scrapper fails with IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by feli6** [micrometer-metrics/micrometer#266]
When the children have fewer tags than the first Metric that created MicrometerCollector, the scraper fails with IndexOutOfBoundsException. In the other scenario, there is a possibility of ignoring new tags added by the children since only the tags of the first metric are considered when exporting. 

`java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:42)
	at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusScrapeEndpoint.scrape(PrometheusScrapeEndpoint.java:50)
`

**Comment by jkschneider** [comment]
Got a test to prove this now. Thanks

**Comment by jkschneider** [comment]
We have a better error message now, but this is fundamentally a constraint imposed by Prometheus. Prometheus does not allow you to register meters of the same name with different tag key sets.

**Comment by jkschneider** [comment]
For Boot 2: There is a required change to `MetricsFilterTest`

**Comment by feli6** [comment]
Thanks. How do you suggest fixing this for metrics that have variable set of tags? I am trying to export kafka stream metrics and they could have different tags for the same metric. May be adapting MicrometerCollector to keep the tags consistent with newly added/removed tags could help.

**Comment by jkschneider** [comment]
It's OK to have different tag _values_, just not varying tag _key_ sets. When you originally conceptualize a tag as sometimes present and sometimes not, consider making it always present and just fill in "none" or something like that for the value when it is not applicable. This is what we do for the `exception` tag on http request metrics.

If this doesn't seem satisfactory, I'd like to hear more about the structure of your kafka metrics specifically. Perhaps there is something we could do to shed light on how to tag those better?
