### ISSUE TITLE
Correct the classpath of your application so that it contains a single, compatible version of org.springframework.boot.actuate.autoconfigure.metrics.MetricsProperties

### ISSUE THREAD

**Issue by AnkitOpl** [micrometer-metrics/micrometer#2665]
**Describe the bug**
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.actuate.autoconfigure.metrics.data.RepositoryMetricsAutoConfiguration.metricsRepositoryMethodInvocationListener(RepositoryMetricsAutoConfiguration.java:68)

	The following method did not exist:

		org.springframework.boot.actuate.autoconfigure.metrics.MetricsProperties.getData()Lorg/springframework/boot/actuate/autoconfigure/metrics/MetricsProperties$Data;

The method's class, org.springframework.boot.actuate.autoconfigure.metrics.MetricsProperties, is available from the following locations:

    jar:file:/C:/Users/ankit.agrawal/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.4.1/spring-boot-actuator-autoconfigure-2.4.1.jar!/org/springframework/boot/actuate/autoconfigure/metrics/MetricsProperties.class
    jar:file:/C:/Users/ankit.agrawal/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.5.0/spring-boot-actuator-autoconfigure-2.5.0.jar!/org/springframework/boot/actuate/autoconfigure/metrics/MetricsProperties.class

The class hierarchy was loaded from the following locations:

    org.springframework.boot.actuate.autoconfigure.metrics.MetricsProperties: file:/C:/Users/ankit.agrawal/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.4.1/spring-boot-actuator-autoconfigure-2.4.1.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.boot.actuate.autoconfigure.metrics.MetricsProperties

**Environment**

 - Micrometer version [e.g. 1.7.1]
 - Micrometer registry [e.g. prometheus]
 - OS: [e.g. macOS]
 - Java version: [e.g. output of `java -version`]

**To Reproduce**
How to reproduce the bug:

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g. related issues.

**Comment by shakuzen** [comment]
As the error message explains, you have two versions of the `spring-boot-actuator-autoconfigure` JAR on your classpath. You should only have one and it should be the version that is consistent and compatible with the other versions of dependencies in your application. This is not a Micrometer issue.

**Comment by Hari-Nikesh-R** [comment]
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:161)

The following method did not exist:

    'void org.springframework.boot.builder.SpringApplicationBuilder.<init>(java.lang.Object[])'

The method's class, org.springframework.boot.builder.SpringApplicationBuilder, is available from the following locations:

    jar:file:/Users/harinikeshr/.m2/repository/org/springframework/boot/spring-boot/2.4.0/spring-boot-2.4.0.jar!/org/springframework/boot/builder/SpringApplicationBuilder.class

The class hierarchy was loaded from the following locations:

    org.springframework.boot.builder.SpringApplicationBuilder: file:/Users/harinikeshr/.m2/repository/org/springframework/boot/spring-boot/2.4.0/spring-boot-2.4.0.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.boot.builder.SpringApplicationBuilder

I was struck with this issue, while migrating spring boot version 1.5x to 2.4x

**Comment by jonatan-ivanov** [comment]
This is Micrometer's issue tracker, I don't see how the problem you described is related.
Also, you are trying to migrate _to_ a version that already reached its end of life.
