### ISSUE TITLE
Native image configuration not compatible with Java 11

### ISSUE THREAD

**Issue by zakkak** [micrometer-metrics/micrometer#2670]
**Describe the bug**

[micrometer-core-1.7.1.jar](https://repo1.maven.org/maven2/io/micrometer/micrometer-core/1.7.1/micrometer-core-1.7.1.jar) fails to compile without `--allow-incomplete-classpath`/`-H:+AllowIncompleteClasspath` when using GraalVM's `native-image` with JDK 11.

The reason is that [Micrometer adds `getCpuLoad()` to the reflection configuration](https://github.com/micrometer-metrics/micrometer/blob/5f7409eddd999177879abad18be0d7769f535179/micrometer-core/src/main/resources/META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json#L5), however  [`getCpuLoad()` is only available since JDK 14](https://docs.oracle.com/en/java/javase/16/docs/api/jdk.management/com/sun/management/OperatingSystemMXBean.html#getCpuLoad()) resulting in the following error when using GraalVM CE with Java 11:

```
Error: Error parsing reflection configuration in jar:file:/home/zakkak/code/tmp/micrometer-reproducer/reproducer/target/reproducer-1.0-SNAPSHOT.jar!/META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json:
Method com.sun.management.OperatingSystemMXBean.getCpuLoad() not found. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
```
source: https://github.com/quarkusio/quarkus/pull/18120

**Environment**

 - Micrometer version: 1.7.1
 - Micrometer registry: prometheus
 - OS: Ubuntu 20.04
 - Java version: 11

**To Reproduce**
How to reproduce the bug:

1. `https://github.com/zakkak/micrometer-native-image-reproducer.git`
2. cd micrometer-native-image-reproducer
3. mvn package
4. `native-image` -jar target/reproducer-1.0-SNAPSHOT.jar

Using `native-image` from GraalVM CE java11 21.1

**Comment by shakuzen** [comment]
Thanks for letting us know about the issue and sorry for the trouble in a patch release. I'm not really sure the best way to go about solving it though. As far as I can tell, GraalVM CE has a Java 16 release now. So how can we support both the Java 11 and Java 16 release with the same reflection configuration is something we'll need to figure out.

**Comment by shakuzen** [comment]
I've been informed we can simply add the `--allow-incomplete-classpath` arg to our existing native-image.properties file.

**Comment by gsmet** [comment]
@shakuzen using the `--allow-incomplete-classpath` option has numerous consequences and we don't support it in Quarkus.

I'm not sure exactly what a good solution could be (conditional reflection probably... @zakkak any chance you could bring that up with the Mandrel/GraalVM team?) but for now, given the Java 16 GraalVM is only preview, I would support Java 11.

And hopefully a solution could be found before 16 gets out of preview.

**Comment by gsmet** [comment]
@zakkak I let you follow up on this in the GraalVM/Mandrel world?

**Comment by shakuzen** [comment]
I tested the changes with the reproducer, but please do try out snapshots and let us know if there is any problem. Snapshots should be available in about 5 minutes for all our upcoming patch releases (e.g. 1.7.2-SNAPSHOT).
I've also reached out to the GraalVM team about a long-term solution for supporting GraalVM for Java 11 and Java 17 (what I presume will end up as a non-experimental release due to being an LTS release).

**Comment by zakkak** [comment]
> @zakkak I let you follow up on this in the GraalVM/Mandrel world?

Sure! @gsmet 

@gradinac already suggested the following on Slack:
> one approach is to create a Feature that will register the method for reflection using org.graalvm.nativeimage.hosted.RuntimeReflection only when the image builder is running on a specific Java version

But I would personally prefer something less "complex".
One work around for now would be to register all methods for reflection using:
```
...
  {
    "name":"com.sun.management.OperatingSystemMXBean", "allPublicMethods": true,
  },
...
```

> I've also reached out to the GraalVM team about a long-term solution for supporting GraalVM for Java 11 and Java 17

@shakuzen did you do so on a public forum? If yes, could you please share the link to the discussion? Thanks

**Comment by shakuzen** [comment]
Also let us know how urgent a patch release with this fix is for you. Our next scheduled round of patch releases will probably be July 14, but we can do a round of patch releases sooner if you need it.

> did you do so on a public forum? If yes, could you please share the link to the discussion? Thanks

It was on a private slack channel.
