### ISSUE TITLE
Enabling `percentiles-histogram` disables time series metrics.

### ISSUE THREAD

**Issue by Albertoimpl** [micrometer-metrics/micrometer#2694]
**Describe the bug**
Enabling `percentiles-histogram` disables time-series metrics.
When doing it so, for example in `spring.cloud.gateway.requests`.
It starts sending `spring.cloud.gateway.requests.m` however, it stops publishing now `spring.cloud.gateway.requests.max`, breaking existing dashboards.
Debugging the published meters in `WavefrontMeterRegistry` with, and without the properties, we see how the `spring.cloud.gateway.requests` `Meter` changed to a `WavefrontHistogramImpl`, instead of adding a new one.

**Environment**
```
wavefront-spring-boot-starter:2.1.1
spring-boot:2.4.7
springCloudVersion:2020.0.3
```

**To Reproduce**
How to reproduce the bug:
```
spring.cloud.gateway.metrics.enabled: true
management.metrics.distribution.percentiles-histogram.spring.cloud.gateway.requests: true
```

This is true for every property `percentile-histogram` gets enabled for.

**Expected behavior**
Both histogram and time-series data get sent to the registry.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
