### ISSUE TITLE
Support dynatrace

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#272]
https://www.dynatrace.com/support/help/dynatrace-api/custom-devices-and-metrics/what-does-the-custom-network-devices-and-metrics-api-provide/

**Comment by jkschneider** [comment]
Also uses the API directly: https://github.com/Dynatrace/dynatrace-cli

**Comment by jkschneider** [comment]
Shows use of custom metrics: https://www.youtube.com/watch?v=nwK9T22uQac

**Comment by obarcelonap** [comment]
@jkschneider is this subject open for contribution?

**Comment by jkschneider** [comment]
@obarcelonap It sure is!

**Comment by obarcelonap** [comment]
Starting to look into the topic. Some interesting resources below.
Blog post:
https://www.dynatrace.com/news/blog/register-custom-network-devices-smartscape-topology/
Samples:
https://github.com/Dynatrace/dynatrace-api/tree/master/custom-device-metrics-F5-example
https://github.com/Dynatrace/dynatrace-api/tree/master/custom-device-metrics-Raspberry-example

**Comment by obarcelonap** [comment]
@jkschneider did some progress on this, mainly creating all the boiler plate and defining minimal configuration properties.
Branch here:
https://github.com/micrometer-metrics/micrometer/compare/master...obarcelonap:dynatrace-support
Next week I'll start to work in the meter registry, I'll keep you posted!

**Comment by jkschneider** [comment]
Looking good!

**Comment by grabnerandi** [comment]
Hi. Just got off a call with Josh Long who highlighted this project. I am the Dev Advocate from Dynatrace and happy to help with any questions you have around the APIs. Seems you already found the Timeseries API which is great to push data. Soon we will provide other options to pull data into Dynatrace if that is of interest.

**Comment by obarcelonap** [comment]
Hi guys, I've been working in the topic, the progress can be checked in the branch mentioned to comments above: https://github.com/micrometer-metrics/micrometer/compare/master...obarcelonap:dynatrace-support

I've implemented all the bolierplate code needed for the implementation and also part of the meter registry, which has the following behavior:
1. For each meter creates the custom metric using `https://{your-environment-id}.live.dynatrace.com/api/v1/timeseries/<metric_ID>`. The names of metrics created through the API are kept in an in-memory collection so this action would be only executed the first time the publish function is executed.
2. For each meter builds the json body (series) of the metrics to be pushed into the API. 
3. Finally it pushes all the series in one single call using `https://{your-environment-id}.live.dynatrace.com/api/v1/entity/infrastructure/custom/<device_ID>`

Implementation of the real HTTP calls is still missing I want to focus first in the internals of the meter.

I've doubts in how to map each meter exposed by micrometer into a custom metric of the API, regarding the following points:
* The unit of the custom metric is extracted from the base unit of the meter after some normalization (lowercase & pluralization). Is something similar as it is done in `DatadogMetricMetadata`, but still there I foresee dynatrace's units that might be not used by the implementation (eg. Information per time, ratio)
* I mapped the tags exposed in the meter as dimension of dynatrace API, might work for almost all the cases but I am not sure if I am missing something.

I attached a file with all the calls regarding custom metric creation that would be done after initialization of the spring boot 1 sample, all the request payloads without unit field will be treated as `Counter` as stated in the api docs.
[micrometer-dynatrace-custom-metric-calls.log](https://github.com/micrometer-metrics/micrometer/files/1852704/micrometer-dynatrace-custom-metric-calls.log)

@jkschneider @grabnerandi if you could take a look and give me feedback I'd apreciate it :)

**Comment by obarcelonap** [comment]
Actually that's already posible with the exposed properties. `url` property has precendence over `tenant`, therefore it would be posible to use url property even for a SaaS. 
You can check `io.micrometer.dynatrace.DynatraceConfig#uri()` for implementation details. 
But I agree that to keep it simple with `url` property is enough to cover both cases so I'll adapt the code to do so.

**Comment by obarcelonap** [comment]
Just created the pull request, I am planning to test during next week using Dynatrace SaaS to verify everything is working as expected.

**Comment by jkschneider** [comment]
@grabnerandi I'm fine working off of a trial account to test this, but if you could help connect me to somebody who could make that test account more permanent, I'd appreciate it.

**Comment by jkschneider** [comment]
@obarcelonap I haven't been able to create a custom chart in Dynatrace off of a custom metric. Have you?

**Comment by jkschneider** [comment]
Merged with a5272df8. Added types to every metrics payload, as that seems to be required. Did a little bit more work to polish tag keys and limit display name text to 256 characters per Dynatrace's requirement. Removed the Guava dependency.

This may require further work, but we can do any further work off of a new PR/master.

**Comment by grabnerandi** [comment]
I can help you with the trial extension. Please reach out to me via email. It is my firstname.lastname(at)dynatrace.com. I can then also show you how to pull/push metrics

**Comment by obarcelonap** [comment]
thank you @jkschneider! is my first "real" contribution to github, to be honest I am kind of proud :)
I loved the experience and I'd like to continue working on it.

What is missing is to expose all the available parameters (displayName, ipAddresses, listenPorts,..) of the custom device as configuration properties in order to push that data into Dynatrace too.

What you said "further work"... did you have something explicit in your mind?

**Comment by cjmckenna** [comment]
Is there documentation available on leveraging this integration?  I am currently trying to experiment with it but not having much luck.  I got the dependency loaded fine and set up the config for our SaaS server but nothing seems to actually be getting Dynatrace.

      <dependency>
         <groupId>io.micrometer</groupId>
         <artifactId>micrometer-registry-dynatrace</artifactId>
         <version>1.1.0-SNAPSHOT</version>
      </dependency>

management.metrics.export.dynatrace.enabled=true
management.metrics.export.dynatrace.apiToken=obfuscated
management.metrics.export.dynatrace.uri=https://obfuscated.live.dynatrace.com
management.metrics.export.dynatrace.deviceId=ServiceA
management.metrics.enable.jvm=true

**Comment by jkschneider** [comment]
@cjmckenna Yep, I haven't figured it out either. The Dynatrace API call says the metrics payload was received successfully but I don't see it show up. Not sure what we could be doing wrong: we're following the documented process and the API responds successfully.

Sent an email to @grabnerandi on this yesterday. Hopefully he can offer some direction!

**Comment by grabnerandi** [comment]
Hi. Sorry for the slow response to your email. I replied to you just now. There is a sample that one of our PMs put out to push custom metrics to Dynatrace: https://github.com/Dynatrace/dynatrace-api/tree/master/custom-device-metrics-F5-example. I just tested it and all the data shows up correctly in Dynatrace. Please have a look at the sample implementation. I am sure there is only a small thing missing on your end to make this work. Keep me posted. happy to help

**Comment by izeye** [comment]
The built request JSON body for custom metric values looks broken.

See https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceMeterRegistry.java#L229

**Comment by obarcelonap** [comment]
Hi guys, I fixed couple of things:
* Wrong json payload when posting custom metric values (thx @izeye).
* Missing "technologyType" in the same call, in the documentation says is mandatory.
Branch here: https://github.com/micrometer-metrics/micrometer/compare/master...obarcelonap:fix-dynatrace-support

But still without luck, the device appears in smartscape but I cannot create custom charts from the reported metrics.

**Comment by jkschneider** [comment]
@obarcelonap Could you go ahead and open a PR here to include your recent changes so we are all working off of the "closest-to-working" copy?

**Comment by obarcelonap** [comment]
Pull request created.
I've been in touch with @grabnerandi, let's see if we find out what are we missing.
