### ISSUE TITLE
jvm.memory.used

### ISSUE THREAD

**Issue by tonycody** [micrometer-metrics/micrometer#2725]
How do I get it from the code API ”jvm.memory.used”

![image](https://user-images.githubusercontent.com/6773121/127642451-2d60fa48-6d19-48fa-b337-bbabbfee6a0a.png)

**Comment by shakuzen** [comment]
I'm assuming you figured out how given you closed the issue. Since the `jvm.memory.used` meter is a Gauge, you can retrieve it programmatically like:

```java
double usedHeapBytes = registry.get("jvm.memory.used").tags("area", "heap").gauge().value();
```
