### ISSUE TITLE
Lock dependencies

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2742]
Before releasing the 1.8.0-M2 milestone we should lock dependencies so that the milestone release is reproducible from the git tag. The locks can be removed in a commit after the milestone release.

**Comment by jonatan-ivanov** [comment]
Fixed in https://github.com/micrometer-metrics/micrometer/commit/d84973349c542741cd9046f0e2441c0232c75712

**Comment by jonatan-ivanov** [comment]
Revert: https://github.com/micrometer-metrics/micrometer/commit/a17ab84d7e2a9153a0539c7097d43d9b4cdc8735
