### ISSUE TITLE
Support for Jersey 3 server

### ISSUE THREAD

**Issue by alexsatori** [micrometer-metrics/micrometer#2748]
Jersey 3 has moved to using Jakarta EE 9. Basically most things under javax.* moved to jakarta.*.
Any plans to support this in micrometer? Maybe micrometer-jersey3?

**Comment by shakuzen** [comment]
> Any plans to support this in micrometer?

Interest from users is a good first step to support potentially being added. A pull request is another good step which I see you've provided. Thank you for bringing this to our attention and for the pull request. We'll take a look at adding this.

**Comment by shakuzen** [comment]
Superseded  by #2766

**Comment by shakuzen** [comment]
The existing Jersey server instrumentation code has been updated to support Jersey 3 as well as Jersey 2 in #2766. Additionally, #2780 moves the jersey code into micrometer-core, so support for Jersey 2 and Jersey 3 will be maintained there going forward. No additional module needed. Users should update their imports to use the code in the micrometer-core module.
