### ISSUE TITLE
Move DiskSpaceMetrics to i.m.core.instrument.binder.system

### ISSUE THREAD

**Issue by wilkinsona** [micrometer-metrics/micrometer#2750]
**Please describe the feature request.**
`DiskSpaceMetrics` is currently packaged in `io.micrometer.core.instrument.binder.jvm` alongside various JVM-specific metrics classes such as `ClassLoaderMetrics`. I'd like to propose that `io.micrometer.core.instrument.binder.jvm.DiskSpacveMEtrics` is deprecated with a replacement being introduced in `io.micrometer.core.instrument.binder.system` alongside `FileDescriptorMetrics`. 

**Rationale**
Disk space metrics are not JVM-specific so I don't think `DiskSpaceMetrics` belongs in the `binder.jvm` package. Additionally, they're closely related to file descriptor metrics so I think it makes sense to package them alongside `FileDescriptorMetrics`.

**Additional context**
https://github.com/spring-projects/spring-boot/issues/27688

**Comment by wilkinsona** [comment]
Thanks, Tommy. Should the new class be `@since 1.8.0`? It’s currently 1.1.0.

**Comment by shakuzen** [comment]
Good catch. I've removed the `@Incubating` annotation on the new class and added a `@since 1.8.0` JavaDoc in cf7e540541cdaa4e32f0847c5d3d46585b1daddc
