### ISSUE TITLE
Upgrade Gradle to 7.2

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#2757]
It seems something is broken with 7.2 and certain JDK versions, see: https://github.com/micrometer-metrics/micrometer/pull/2755

**Comment by jonatan-ivanov** [comment]
@izeye Could you please try it with OpenJDK 11.0.12 (kill your gradle daemons)?
It seems it works for me on the latest version (no build cache):
- `main`: https://ge.micrometer.io/s/7xytebh2ec6eu
- `1.5.x`: https://ge.micrometer.io/s/adh5pvv4zfc5m

```
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
```

**Comment by izeye** [comment]
@jonatan-ivanov I'm not sure why, but I can't reproduce it even with OpenJDK 11.0.11. Have you ever experienced the exception before?

**Comment by jonatan-ivanov** [comment]
I have never seen it. If I need to guess, I would say that the gradle daemon messed up something. Usually if I see these kind of ("this is impossible") errors, I usually kill the daemons and delete the project's `.gradle` folder.
