### ISSUE TITLE
Support timing individual servlet filters

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#278]
**Purpose:** Monitor the impact that individual servlet filters have on overall latency.

cc / @twicksell
cc / @adriancole

Options we discussed:
1. BPP
2. AOP
3. Server-specific impl _a la_ `AbstractConfigurableWebServerFactory`

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/33790778-0eb1e3d6-dc38-11e7-9176-d038ff4ff6a6.png)

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2018. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
