### ISSUE TITLE
StackDriverRegistry does not report http requests in Google Cloud Monitoring

### ISSUE THREAD

**Issue by jayleenli** [micrometer-metrics/micrometer#2789]
I am not sure if this is a bug in StackDriverRegistry or if I am using the StackDriverRegistry incorrectly. Please correct me if it's the latter. 

HTTP request metrics do not show up in GC Monitoring but they do show up in Prometheus.
 
**Environment**
 - Micrometer version 1.7.3
 - Micrometer registry: prometheus and stackdriver
 - OS: macOS
 - Java version: 15

**To Reproduce**
How to reproduce the bug:
Took the Quarkus micrometer quickstart https://quarkus.io/guides/micrometer, and switched the Registry from Prometheus to StackDriverRegistry. It still publishes info to Prometheus.

Uploaded the project, but linking just the one file with most of the actual changes.
https://github.com/jayleenli/quarkus-micrometer-quickstart-stackdriver/blob/main/src/main/java/org/acme/micrometer/ExampleResource.java

**Expected behavior**
When you open the prometheus endpoint at localhost:8080/q/metrics, it shows information generated from http requests.

```
# HELP method_timed_seconds  
# TYPE method_timed_seconds summary
method_timed_seconds_count{class="org.acme.micrometer.ExampleResource",exception="none",method="checkIfPrime",} 2.0
method_timed_seconds_sum{class="org.acme.micrometer.ExampleResource",exception="none",method="checkIfPrime",} 0.003384136
# HELP method_timed_seconds_max  
# TYPE method_timed_seconds_max gauge
method_timed_seconds_max{class="org.acme.micrometer.ExampleResource",exception="none",method="checkIfPrime",} 0.003204394

...

# HELP http_server_requests_seconds  
# TYPE http_server_requests_seconds summary
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/example/prime/{number}",} 2.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/example/prime/{number}",} 0.306113721
http_server_requests_seconds_count{method="GET",outcome="CLIENT_ERROR",status="404",uri="NOT_FOUND",} 1.0
http_server_requests_seconds_sum{method="GET",outcome="CLIENT_ERROR",status="404",uri="NOT_FOUND",} 0.03581488
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/q/metrics",} 3.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/q/metrics",} 0.063061369
# HELP http_server_requests_seconds_max  
# TYPE http_server_requests_seconds_max gauge
http_server_requests_seconds_max{method="GET",outcome="SUCCESS",status="200",uri="/example/prime/{number}",} 0.301232062
http_server_requests_seconds_max{method="GET",outcome="CLIENT_ERROR",status="404",uri="NOT_FOUND",} 0.03581488
http_server_requests_seconds_max{method="GET",outcome="SUCCESS",status="200",uri="/q/metrics",} 0.052659256

```

However this request information is no where to be seen in GC Monitoring dashboard. It would be very beneficial for the use case I am trying to implement if there was a way to have these http requests graphed onto a metrics chart within GC Monitoring, thanks!

**Comment by jayleenli** [comment]
Adding some more information. So the http requests will go to the default MeterRegistry made in the ExampleResource constructor `ExampleResource(MeterRegistry registry)`. I am thinking that there is some sort of binding for http requests that could bind it for the StackDriver registry but I am unable to find it. What (if it exists) is the http request metric binder?

Or: Is there a way to construct a StackDriverRegistry using a MeterRegistry? Maybe I could import the meters from the constructor to the StackDriver one.

**Comment by shakuzen** [comment]
This sounds mostly like a Quarkus usage question. For metrics to be published to Stackdriver, you need to make sure you are providing the configuration necessary. However, you shouldn't need to make the `StackdriverMeterRegistry` yourself. See the part of the Quarkus Micrometer documentation that mentions using registries other than Prometheus: https://quarkus.io/guides/micrometer#using-other-registry-implementations
You can then use configuration properties to configure things like the project ID. See https://quarkiverse.github.io/quarkiverse-docs/quarkus-micrometer-registry/dev/micrometer-registry-stackdriver.html
You will also need to make sure you are either running in a Google Cloud environment that provides the Google credentials necessary, or if you are running elsewhere (such as your local dev machine), you can configure, for example, `GOOGLE_APPLICATION_CREDENTIALS` like mentioned in the Micrometer docs for Stackdriver: https://micrometer.io/docs/registry/stackdriver#_configuring
Hopefully that provides some direction.
