### ISSUE TITLE
DistributionSummary setting 0 as minimumExpectedValue and record decimal values

### ISSUE THREAD

**Issue by gdadon** [micrometer-metrics/micrometer#2790]
**Describe the bug**
Using DistributionSummary with 0 as minimumExpectedValue, then record a decimal value (i.e 0.625)
getting the following error
`io.micrometer.core.instrument.config.InvalidConfigurationException: Invalid distribution configuration: minimumExpectedValue (0.0) must be greater than 0`

 - Micrometer version: 1.7.1
 - Micrometer registry: MeterRegistry
 - OS: macOS
 - Java version: java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

**To Reproduce**
`

  @Test
  public void testDistributionSummaryWithDecimalValues() {
  
    MeterRegistry meterRegistry = new SimpleMeterRegistry();
    String metricName = "decimal.value.test";
  
    double amount = 0.06;
    DistributionSummary
            .builder(metricName)
            .publishPercentiles(0.99, 0.95, 0.5)
            .percentilePrecision(1)
            .publishPercentileHistogram()
            .minimumExpectedValue(0.0D)
            .maximumExpectedValue(100D)
            .register(meterRegistry)
            .record(amount);
  
    DistributionSummary summary = meterRegistry.summary(metricName);
    Assert.assertEquals(1, summary.count());
    Assert.assertEquals(amount, summary.totalAmount(), 0.0D);
  
  }

`

**Expected behavior**
Expected to record the amount

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
