### ISSUE TITLE
Sending of micrometer metrics failing with Error: "The dimensions of an already configured timeseries id cannot be changed" 

### ISSUE THREAD

**Issue by db-vmw** [micrometer-metrics/micrometer#2792]
**Describe the bug**
Dynatrace : Sending of micrometer metrics failing with Error: "The dimensions of an already configured timeseries id cannot be changed" in the spring boot application.

**Environment**
 - Micrometer version : 1.3.1
 - Micrometer registry : Dynatrace
 - OS: Mac OS, Ubuntu, Photon
 - Java version: 1.8

**To Reproduce**

- We have spring boot application and we are using micrometer to send tomcat and jvm metrics to Dynatrace instance.
- In the spring boot application are creating DynatraceMeterRegistry bean as configuration (using @Configuration).
- We do have created the Config class (@Configuration) by implementing DynatraceConfig which returns the following parameters: Dynatrace URI, API Token and Device ID.
- Sending of spring boot application metrics worked fine only on 1st time created configuration (on my dev environment, sending of metric is working fine).
- My spring boot application persists configuration parameters (dynatrace) to cassandra Db.
- But, the same spring boot application when connected to different cassandra DB instance OR runs on a different environment fails to send the metrics to Dynatrace (same dynatrace connection properties).
- The micrometer prints the following log : 

`[dynatrace-metrics-publisher] ERROR io.micrometer.dynatrace.DynatraceMeterRegistry.lambda$putCustomMetric$3 (245) - failed to create custom metric custom:http.server.mangle.requests.avg in dynatrace: {"error":{"code":400,"message":"The dimensions of an already configured timeseries id cannot be changed. Currently configured dimensions are: exception, cluster, method, host, uri, Source, outcome, status"}}`

- The above error seems to be hinting that the metrics are getting mapped to the same device ID at Dynatrace though configuration parameter for DynatraceMeterRegistry are different.

- While I'm running the spring boot application on different environment, I provide the same Dynatrace URI, API Token and a different unique device ID.
- I confirmed that, the DynatraceConfig is returning the different device Id that I have provided. 

Still wondering on why there is a failure in reporting the Spring boot application metrics to Dynatrace using micrometer.

NOTE: 
 if I point my spring boot application to use the cassandra DB which I had used for for testing for the 1st time, it works. I don't know on what correlation it is adding here.

Looking at the below code, looks like DynatraceMeterRegistry is consuming the device ID as the API endpoint. But, not sure what is the issue
```
DynatraceMeterRegistry.java

    @Override
    protected void publish() {
        String customDeviceMetricEndpoint = config.uri() + "/api/v1/entity/infrastructure/custom/" +
                config.deviceId() + "?api-token=" + config.apiToken();


```

**Expected behavior**
Dynatrace micrometer instance should be able to send the metrics of spring boot application as long as Device ID configuration parameter is different.

**Comment by jonatan-ivanov** [comment]
>Micrometer version : 1.3.1

The Micrometer version that you are using is not supported anymore, could you please upgrade to the latest?

>In the spring boot application are creating DynatraceMeterRegistry bean as configuration (using @configuration).

I don't think you need to, Spring Boot can autoconfigure the `DynatraceMeterRegistry` for you.

>The dimensions of an already configured timeseries id cannot be changed. Currently configured dimensions are: exception, cluster, method, host, uri, Source, outcome, status

To me this does not seem to be related to the deviceId, it seems that you are sending two metrics with the same name but different dimensions, e.g.:

```
name: abc123,
tags:
    - x: 42
    - y: aaa
```
vs.
```
name: abc123,
tags:
    - z: 123
```

Could you please confirm if this is the case?

**Comment by db-vmw** [comment]
Thanks @jonatan-ivanov 

> > Micrometer version : 1.3.1
> 
> The Micrometer version that you are using is not supported anymore, could you please upgrade to the latest?
> 
This may not be an easy option for us due to the spring boot version we are using currently. But we will upgrade the version of micrometer once we upgrade spring boot version.

> > The dimensions of an already configured timeseries id cannot be changed. Currently configured dimensions are: exception, cluster, method, host, uri, Source, outcome, status
> 
Is the Source set to Device ID we configure ?

> To me this does not seem to be related to the deviceId, it seems that you are sending two metrics with the same name but different dimensions, e.g.:
> 
> ```
> name: abc123,
> tags:
>     - x: 42
>     - y: aaa
> ```
> 
> vs.
> 
> ```
> name: abc123,
> tags:
>     - z: 123
> ```
> 
> Could you please confirm if this is the case?
Yeah I got it.
For some reason, Source dimension was missing.

**Comment by jonatan-ivanov** [comment]
Great to hear that the issue has been resolved! I'm closing this PR, please let me know if I misunderstood something and you want us to reopen it.

**Comment by db-vmw** [comment]
Hi @jonatan-ivanov , 
Is "Source" dimension added by micrometer? Can you please confirm this?

**Comment by jonatan-ivanov** [comment]
No, Micrometer does not add tags (dimensions) by default, you need to add them on your own. :)
If you don't find it i your own codebase, you can use a `MeterFilter` to remove it.
