### ISSUE TITLE
High CPU usage while using KafkaStreamsMetrics in micrometer 1.7.4

### ISSUE THREAD

**Issue by JorgenRingen** [micrometer-metrics/micrometer#2801]
**Describe the bug**
We run spring-boot + kafka-streams with micrometer and KafkaStreamsMetrics. Metrics are exposed by using `micrometer-registry-prometheus`

After upgrading from micrometer 1.7.3 to 1.7.4 we notice high cpu-usage. If we disable KafkaStreamsMetrics the high cpu usage disappear. Also, downgrading to 1.7.3 makes the high cpu usage disappear.

The cpu usage increases while calling `actuator/prometheus`. Our monitoring system polls this endpoint frequently and the CPU is therefore always high.

Have provided a small sample-app that reproduces the issue: https://github.com/JorgenRingen/micrometer_1_7_4_high_cpu_usage

**Environment**
Kubernetes and locally.
 - Micrometer version: 1.7.4
 - Micrometer registry: prometheus
 - OS: macOS, Linux
 - Java version: openjdk version "11.0.7"

**To Reproduce**
How to reproduce the bug:
https://github.com/JorgenRingen/micrometer_1_7_4_high_cpu_usage
Java-branch has a very basic spring-boot, kafka-streams, micrometer setup.

**Expected behavior**
While polling `localhost:8080/acutator/prometheus` the CPU usage is very high on 1.7.4. Expected behavior is that this should barely be noticeable.

**Additional context**
Slack thread: https://micrometer-metrics.slack.com/archives/C662HUJC9/p1632729969102400

**Comment by jonatan-ivanov** [comment]
@JorgenRingen I checked out your project but unfortunately I was not reproduce the issue, the Prometheus overhead I'm seeing is somewhere between 0 and 1%.

Also, the client fails shortly after I start the service:
```
2021-10-05 15:20:55.297 ERROR 7963 --- [-StreamThread-2] org.apache.kafka.streams.KafkaStreams    : stream-client [sample-app-4340437c-e603-4bed-b5c7-4845a9d78561] Encountered the following exception during processing and the registered exception handler opted to SHUTDOWN_CLIENT. The streams client is going to shut down now. 

org.apache.kafka.streams.errors.StreamsException: Could not create topic sample-app-foo-repartiton-1-repartition.
...
Caused by: org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.
```

Is it possibe to make the project a little more minimalistic? It still references config files I don't have: `file:/etc/config/sb-config.yaml` and in order to rule out language/sdk-related things it would be great to have a java reproducer. I'm not sure if all classes are also needed to repro this, that project contains rather a lot of code for such a simple reproducer.

Btw have you take a look at spring integration? It has nice Kafka support with a much simpler API.

**Comment by JorgenRingen** [comment]
@jonatan-ivanov : Yes, I linked to the java-branch on the sample project. It's very minimalistic and uses out-of-the-box spring integration: https://github.com/JorgenRingen/micrometer_1_7_4_high_cpu_usage/tree/java

**Comment by JorgenRingen** [comment]
Very interesting! I sent the sample-app to a couple of colleagues so they can test it as well. But I've replicated it on 2 different machines and in our k8s production environment, where the screenshots in slack-tread was taken from. The k8s-pods are not very powerful, so that's why the cpu-spikes are so high there.

I just ran in on my local machine: macOS 11.6 (Big Sur); 3,8 GHz Quad-Core Intel Core i5; 40 GB RAM and Java 17 `(Temurin 17 2021-09-14)` using VisualVM:

**Micrometer 1.7.4**:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/5677271/136919409-13538e27-fed4-400e-b2b0-1edeefa5fdd0.png">

Some runs with `curl -s localhost:8080/actuator/prometheus | wc -l` (stop-start app between each run): 
1. **5188**
2. 4515
3. 3950
4. 3945
5. **5188** (again)

It uses some time (about a minute) before it stabilizes on a number as you said. 
The diff between total number of metrics and non-kafka metrics is always **140**.

I don't know what causes this and the slow increase in number of metrics before it stabilizes. Might be some scheduled thing in kafka-streams that generates a lot of metrics.

**Micrometer 1.7.3**:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/5677271/136919484-298424d0-dbf3-425d-8494-c409ded7174e.png">
(last spike is shutdown)

Some runs with `curl -s localhost:8080/actuator/prometheus | wc -l` (stop-start app between each run): 
1. **5188** (same as 1.7.4)
2. **5188**
3. **5188**

Really interesting. Always same result on 1.7.3. Also had to wait quite a bit of time (1+ min) before it stabilizes on 5188.

The CPU trend is the same for 1.7.4 (25-30%) and 1.7.3 (1-2%) regardless of number of metrics. I would also add that the endpoint itself is extremely more responsive on 1.7.3 (~100ms ish) compared to 1.7.4 (~1sec ish)

> Could you please also check if you need all 5000+ metrics? You can filter them out using a MeterFilter.

Will definitely look into filtering out some of the metrics we don't use. We just use the default setup and kafka-streams provides a _lot_ of metrics by default.

> Could you please tell how frequently?

I'll try to figure it out, we use a datadog-agent in kubernetes which scrapes /prometheus and forwards the metrics to datadog: https://docs.datadoghq.com/integrations/prometheus/

**Comment by JorgenRingen** [comment]
Yes, as @ghmulti points out, it seems to be this change: https://github.com/micrometer-metrics/micrometer/commit/f78fcb00300ed67ffa250a8d8f9437c95b6d697d#diff-7056fc4a7f15d24878096caa96ae9852ac8c9b2afcf11609faead6b9123efbb0R197

Instead of retrieving the value of the metric directly, the metric-supplier is passed and by calling the metric-supplier all kafka-streams metrics are retrieved for each metric.

This means that this call is run for all kafka-streams metrics (4-5000): org.apache.kafka.streams.KafkaStreams#metrics

**Comment by jonatan-ivanov** [comment]
I investigated this further and if I replace the `Supplier` to an `AtomicReference` and update the `AtomicReference` with the scheduler in `KafkaMetrics` (60s by default):

```java
private ToDoubleFunction<AtomicReference<Map<MetricName, ? extends Metric>>> toMetricValue(MetricName metricName) {
    return metricsSupplier -> toDouble(this.metrics.get().get(metricName));
}
```

It seems it is fast again. The problem with this is the same, if you just updated the reference but Kafka will replace its `Metric` then you won't get updates (or you will get `NaN` if GC kicks in for a minute).

**Comment by jonatan-ivanov** [comment]
Great to hear!
Thanks everyone for reporting and investigating this!
