### ISSUE TITLE
Provide API for integration testing of application

### ISSUE THREAD

**Issue by everflux** [micrometer-metrics/micrometer#2803]
**Please describe the feature request.**
I would like to use something like the `SimpleMeterRegistry` in integration tests.
I need to reset the meters to initial values in order to have independent test cases without the need to recreate the whole registry and, with Spring Boot, the application context with `@DirtiesContext`.

**Rationale**
Currently the '`clear`' method removes all meters, subsequent tests fail since the application state is broken.
Running multiple request through `MockMVC` and validating the meters are correctly set are a valid use case to ensure correct tags and values, in my point of view.
To my knowledge:
There is no copy/clone method to remove-and-add meters to the registry.
There is no "`TestMeterRegistry`" that supports resetting the meters without the need to restart the application.
Providing a `TestMeterRegistry` that openes up the `register` method is not possible from outside of the micrometer package.

**Additional context**
There was an issue opened in unit testing context, so for single classes without running the whole application: https://github.com/micrometer-metrics/micrometer/issues/709
This issue describes the '`clear`' method to support testing https://github.com/micrometer-metrics/micrometer/issues/569 but I have no idea how that would help since afterwards the meters are removed.
I thought about re-adding meters using something like

```
toClone.forEach(m -> {
            var t = m.getId().getType();
            switch(t) {
                case COUNTER:
                    meterRegistry.register(
                        new Meter.Id(m.getId().getName(),
                            Tags.of(m.getId().getTags()),
                            m.getId().getBaseUnit(),
                            m.getId().getDescription(),
                            Meter.Type.COUNTER)
                    );
            }
        });
```
But this does not work since the `register` method is not accessible from outside, nor would it work with custom meters, I guess.
I checked the test cases for micrometer and noticed that they are in fact all quite simple unit tests in isolation and I could not get a story how more complex scenarios could be modeled.
For counters I used the following mitigation, but I think this is quite clumsy.

```
toClone.forEach(m -> {
  var t = m.getId().getType();
  switch(t) {
    case COUNTER:
        meterRegistry.counter(m.getId().getName(), m.getId().getTags());
        break;
```

**Comment by jonatan-ivanov** [comment]
@poznachowski Could you please try not holding a reference to the `Counter` in the ctor but do this in the `increment` method instead:
```java
Counter.builder(COUNTER_NAME)
        .register(meterRegistry)
        .increment();
```
and try with `clear`?

Right now your test results seem to be expected, Micrometer is doing what you are asking it to do.

**Comment by everflux** [comment]
I think there are valid scenarios for holding references. For example I have a situation with an enum map to look up the right counter depending on the outcome of a decision. 

Or even passing references to separate construction and usage of a meter.

**Comment by poznachowski** [comment]
@jonatan-ivanov that would work, but I don't see doing all the ceremony (having to call builder + register, passing meterRegistry everywhere) to increment a Counter as best practice. What's more, not looking at the internals, it may seem like a bug (building and registering same counter over again).

**Comment by poznachowski** [comment]
@jonatan-ivanov I know, but by just reading the code (not the docs) is not really intuitive.
Nevertheless, your proposed solution works. Thanks.
Is that the official recommendation?

**Comment by jonatan-ivanov** [comment]
It seems the issue is resolved, please let us know if you want us to reopen.
