### ISSUE TITLE
Micrometer 2.x Java baseline

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2809]
We currently have a Java 8 baseline. It will be at least a few years until we have another opportunity (major version release) to revisit the Java baseline version. The GA date for Micrometer 2.0 is expected to be late 2022.

Java 17 is already available and is currently the latest LTS version. In the time frame of a late 2022 release, Java 18 and 19 will have been released, but they are non-LTS versions. Our options for Micrometer 2.x Java baseline are:

* 17
* 11
* 8 (same as Micrometer 1.x)

What are the benefits of each?

### 8

We don't have to worry about a consumer not being able to upgrade due to a higher Java baseline if we don't change the Java baseline.

### 11

Looking at the list of JEPs included in releases since 8, there are some features that may be useful to Micrometer.

* (9) [Memory order modes](http://gee.cs.oswego.edu/dl/html/j9mm.html) ([JEP193](https://openjdk.java.net/jeps/193))
* (9) [JEP 264: Platform Logging API and Service](https://openjdk.java.net/jeps/264)
* (9) [JEP 277: Enhanced Deprecation](https://openjdk.java.net/jeps/277)
* (9) JPMS - modularize Micrometer for better encapsulation of internals
* (10) `var`
* (11) [JEP 321: HTTP Client](https://openjdk.java.net/jeps/321) - new default HTTP client for registries that use one and instrumentation for the JDK HTTP client

Note that support for Java 11 is expected to end before support for Java 8, according to most currently published material. See, for example, [adoptium's support page](https://adoptium.net/support.html), which states availability for updates until at least Oct 2024 for Java 11. In comparison, Java 8 is supported until at least May 2026. While it is stated as "at least", Oct 2024 would only give about 2 years of support from our GA date if we choose 11 as the baseline for our next major version. That's a significant concern given how long we expect to support major versions.

### 17

With 17, we would get the features in 11 in addition to the following. See the [full list of JEPs in 17 since 11](https://openjdk.java.net/projects/jdk/17/jeps-since-jdk-11). The Language features are probably where the direct benefit is for us.

* 394: Pattern Matching for instanceof (16)
* 395: Records (16)
* 409: Sealed Classes (17)
* 361: Switch Expressions (14)
* 378: Text Blocks (15)

## Other projects

For comparison, here is a sampling of what other JVM projects are publicly planning on doing with respect to Java baseline in their upcoming (or recent) major version releases.

* Netty 5: Java 11 https://github.com/netty/netty/pull/10650
* Spring 6: Java 17 ([blog](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6))
* Quarkus 2: Java 11
* Helidon 2: Java 11
* Micronaut 4: [Java 11 or 17](https://twitter.com/graemerocher/status/1481202824289693698)
* Reactor 4: https://github.com/reactor/reactor/issues/703
* Caffeine 3: Java 11
* Jakarta EE 10: Java 11 ([release plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee10/JakartaEE10ReleasePlan); [1Q2022 completion (proposed)](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee10/JakartaEE10#jakarta-ee-10-schedule))
* HikariCP 5: Java 11

## 1.x support

Regardless of what Java baseline we go with, for users that may need some time to upgrade to a new major version, they can continue to use Micrometer 1.x, which we will still support and even plan to do a couple minor releases from this point before 2.0 goes GA.

**Comment by wengertj** [comment]
I'll just add my 2 cents here:

Apart from my personal preference for JDK17 as baseline (which is irrelevant) there's one very compelling technical reason for JDK17 which is JFR.

Gunnar Morling has posted [a nice article](https://www.morling.dev/blog/rest-api-monitoring-with-custom-jdk-flight-recorder-events/) in which he describes how to monitor a JAX-RS Api with Custom JFR Events and expose them via [JFR Event-Streaming](https://openjdk.java.net/jeps/349)

I don't know very much about JFR (yet) but it looks like Micrometer could make use of it for some use-cases. One example that comes to mind is all the JVM-related metrics that currently are being queried via JMX.

**Comment by shakuzen** [comment]
While we would have liked to take the opportunity of a major version to raise the Java baseline for Micrometer, as such a low-level library that is depended on by frameworks and other libraries, and with observability being something that is important to make available as broadly as possible, we decided to not raise the Java baseline from 8 for Micrometer 2.x. Maybe in Micrometer 3.x it will be more feasible and beneficial to raise it, with the increased pace of Java LTS versions.

@wengertj JFR integration in some form has been on our radar as a topic to explore further, but we have not yet delivered anything on it yet. A separate module for it that has a higher baseline than other modules could make sense. We'll have to see.
