### ISSUE TITLE
Exemplars support for Prometheus Histogram

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#2812]
This issue belongs to https://github.com/micrometer-metrics/micrometer/issues/2672 (Support for Exemplars), see the details there.

**Comment by jonatan-ivanov** [comment]
@neiser I am (was? 😃), but we are always happy to see contributions so if you want to work on it, please feel free to do so.
I took a look at the Histogram support at the time I wrote support for Counters but it is a little more complicated case and I needed to focus on other things. We are planning to add this in the next minor release of Micrometer (1.9.0) so your timing is perfect.

**Comment by neiser** [comment]
@jonatan-ivanov Alright, then let me see if I can provide a PR in the coming days.

**Comment by neiser** [comment]
@jonatan-ivanov I've looked into the code and figured that I'd need to start at `PrometheusDistributionSummary#recordNonNegative` to trigger recording an exemplar for `count`/`amount`/`max` and all `histogram` buckets. I didn't quite get why `PrometheusDistributionSummary` manages its own `histogram`, while the base class `AbstractDistributionSummary` already has such a field (though configuration of it seems to be complex, in particular with the weirdly integrated case of `VictoriaMetrics` which also surprisingly appear in core module as `io.micrometer.core.instrument.distribution.FixedBoundaryVictoriaMetricsHistogram` (my impression was that micrometer tries to abstract away any particular backend system for metrics collection... which is kinda broken by this class IMHO).

Anyway, my question is now is: Should I attempt a refactoring which would make getting exemplars into histogram buckets easier? Or should I just hack a lot of stuff around the "prometheus" part of Micrometer to achieve whatever resolving this issue takes?

**Comment by fscellos** [comment]
Hello i did some test to integrate exemplars in histogram. 
For test i implemented it by define a custom TimeWindowFixedBoundaryHistogram (some private attributes (bucket) does not allow a direct inheritance from AbstractTimeWindowHistogram) and try to inspire from code of @jonatan-ivanov in its counter.

ReadMe is in french but you can take a look at : [github / micrometer-prometheus-examplar ](https://github.com/fscellos/micrometer-prometheus-examplar ). If you want to check it, i'll be happy to try to find an implementation with you.

It seems to work from a spring boot application (by defining PrometheusMeterRegistry Bean to override default actuator behaviour) but i always have a little problem....
Some span values are not correct (too low for my test application) and i suspect that my "exemplar-sampling" time is too low versus prometheus scraping.. 
I have to refine it to be sure that exemplars associated with a scraped metrics contains the full time of the span, and not a partial one...

**Comment by jonatan-ivanov** [comment]
@neiser If my memory serves me well, I wanted to extend `TimeWindowFixedBoundaryHistogram` as `PrometheusHistogram` and add exemplars support to it.

Micrometer "abstracts away backends" in the sense that a `MeterRegistry` implementation will define a couple of things:
1. The dimensionality (dimensional vs. hierarchical)
2. Push or Pull based
3. Client or Server side aggregation (e.g.: sending discrete samples, rates, cumulative values, etc.)
4. The "line"/"network" protocol
5. etc?

Some `MeterRegistry` implementations support multiple flavors of this, e.g.: `StatsdMeterRegistry` supports four flavors of line protocols (see `StatsdFlavor`) and three flavors of "network" protocols (TCP, UPD, UDS).

In case of Prometheus, there are multiple backends that support the Prometheus format and Prometheus itself supports multiple formats ("Prometheus Text" and OpenMetrics). VictoriaMetrics also supports the Prometheus format but they define their own histogram flavor, also this histogram flavor is reused in OpenTSDB. :)

So if you use an XyzMeterRegistry, that does not mean you need use the Xyz backend. It rather means that you need to use a backend that supports the XyZ format (e.g.: with the `StatsdMeterRegistry` you can use many backends).

Or in the other way: if you use Xyz as a backend you don't need to use XyzMeterRegistry but you can use a different one if that backend supports multiple standards (e.g.: if you use DataDog, you can use the `DatadogMeterRegistry`(HTTP API) or the `StatsdMeterRegistry` with the DataDog flavor since the backend supports multiple standards).

**Comment by neiser** [comment]
@fscellos @jonatan-ivanov Thank you for your answers. This helped me a bit. But I can't promise that I can make progress before next week. So if you find time over the weekend to work on this, please let me know so that we don't do the work twice!

**Comment by fscellos** [comment]
Hello. As target is to apply trace sampling, i will take a look to see if it is possible to include TraceFlags (cf https://www.w3.org/TR/trace-context/#sampled-flag) information to choose if a specific trace is eligible to be set as exemplars in bucket (or counter).

Because if you have client sampling (what can be done with Instrumentation sampling on client side), suppose 1%, we can't use 99 % of this traces as examplars as we're not be able to find them in storage backend (ie. in a prometheus instance, if you click on an exemplar, you won't find it in backend storage).

So we must only keep traces that have a sampled flag set to "01" (other with TraceFlags set to "00" won't be store)

**Comment by fscellos** [comment]
Note that previous remarks il also available for Counter.

**Comment by fscellos** [comment]
Hello. That's cool. But i always don't understand how you can manage sampling on trace as my PR on prometheus java client haven't be merge yet (https://github.com/prometheus/client_java/pull/766)

**Comment by jonatan-ivanov** [comment]
@fscellos Haven't we discussed this here: https://github.com/micrometer-metrics/micrometer/pull/3019#discussion_r809244950?

If the `SpanContextSupplier` returns `null` when the span is not sampled, your changes on the Prometheus client are not really needed for Micrometer to make this work. Also, they are completely transparent from Micrometer's perspective: we don't need any code change to integrate with them (we only need to change tests).

I tested this using Spring Cloud Sleuth ([`SleuthSpanContextSupplier`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/prometheus/prometheus/SleuthSpanContextSupplier.java)), please see the description of the PR to try it out: https://github.com/micrometer-metrics/micrometer/pull/3091#issue-1177411405.
Please let us know if it works for you.

**Comment by neiser** [comment]
@fscellos @jonatan-ivanov I've patched a [demo spring boot app](https://github.com/qaware/cloud-observability-grafana-spring-boot/tree/main/spring-boot-app) such that the actuator endpoint includes exemplars (note that when testing with curl, you need to use an Accept header to get openmetrics format). It required to explicitly pass the [exemplar sampler into the Prometheus registry](https://github.com/qaware/cloud-observability-grafana-spring-boot/blob/main/spring-boot-app/src/main/java/de/qaware/demo/cloudobservability/PrometheusExemplarSamplerConfiguration.java), assuming it's instrumented with the opentelemetry agent (see Dockerfile for details). 

Note that the demo uses micrometer with 1.9.0-SNAPSHOT, I hope the release will happen soon 🙂 

Thanks y'all for finishing this feature. Exemplars are really something I've always wished I had when debugging some nasty cloud bugs.

**Comment by jonatan-ivanov** [comment]
@neiser Please take a look at the description of the PR that belongs to this issue: https://github.com/micrometer-metrics/micrometer/pull/3091
It will tell you that this is only available in the OpenMetrics format and it will also show the header that you need to send. Your browser/curl does not send that header, Prometheus does.

In the samples (see the description of the PR) you will find a demo spring boot app (with the sampler bean), here's the boot PR to auto-configure it: https://github.com/spring-projects/spring-boot/pull/30472

`1.9.0-RC1` should be released in mid April, `1.9.0` should be in mid May, Boot 2.7.0 should be a week after that.

**Comment by neiser** [comment]
@jonatan-ivanov Thanks, I was aware of that `Accept` header, I just wanted to let @fscellos know about it (I've also updated my previous comment with a specific `curl` request). It has led to confusion in the past though, see [here for example](https://linuxczar.net/blog/2022/01/17/java-spring-boot-prometheus-exemplars/).

I agree that https://github.com/spring-projects/spring-boot/pull/30472 is the correct solution, however, as shown in my little Spring Boot Demo (see previous comment), you don't need to wait to have exemplars reported already now, if you're not using Spring Sleuth but OpenTelemetry agent instrumentation. Again, thanks for pushing this feature!

**Comment by neiser** [comment]
@fscellos Thanks for your detailed answer. I've applied a [little patch here](https://github.com/qaware/cloud-observability-grafana-spring-boot/commit/09417f6c8c1ad14e7365521d6fe8838a1cf54f36) which should respect the fact that not all traces are samples and thus not suitable for exemplars.

**Comment by fscellos** [comment]
@neiser : yes it should work like this.
