### ISSUE TITLE
Jvm is faked death (when micrometer collectting thead info in native)

### ISSUE THREAD

**Issue by fly7632785** [micrometer-metrics/micrometer#2832]
**Describe the bug**
Hello, we got a problem, our service is not responsed.  Need help, thank you.

After using micrometer for a period of time, service is not reponsing. 
http://xxxxx/actuator/prometheus   is not responsing, too.

![image](https://user-images.githubusercontent.com/10276266/137448312-dd0c610c-b877-48ca-99a5-90461eb4f2ee.png)
So, can't continue to collect data  

And our any request is not responsing,too. Cause our project system is not useful.

We dump javacore.txt to analysis, but not figure out anything useful.
Just find so many threads which are runnable and related to micrometer and promethues

![image](https://user-images.githubusercontent.com/10276266/137447356-16c63bd2-45cd-4d15-a948-10b78dae1493.png)

![image](https://user-images.githubusercontent.com/10276266/137446568-822dc90d-9a6b-4e25-a949-7bd5a592bfa9.png)

We try use jstat jstack to anylysis, but jstack -l xx  is  not responsing, too.
So we have to kill -3 xx and get javacore.txt to analysis.

This is javacore.txt，hope some people help, thank you in advance!
We are not so professional that we can't find the reason

[javacore.txt](https://gitee.com/jafir/blogs/raw/master/javacore.20211015.135751.1.0001.txt)

**Environment**
```
<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter-actuator</artifactId>-->
<!--            <version>2.5.5</version>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>io.micrometer</groupId>-->
<!--            <artifactId>micrometer-core</artifactId>-->
<!--            <version>1.6.9</version>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>io.micrometer</groupId>-->
<!--            <artifactId>micrometer-registry-prometheus</artifactId>-->
<!--            <version>1.6.9</version>-->
<!--        </dependency>-->
```

```
#management:
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#    tags:
#      application: ${spring.application.name}
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    prometheus:
#      enabled: true
#    metrics:
#      enabled: true
```

PS：Our project may use too many thread pools and theads, don't know if it's related.

**Comment by shakuzen** [comment]
> PS：Our project may use too many thread pools and theads, don't know if it's related.

Yes, I suspect the issue is the thread state metrics. As @checketts suggested, if you try with not binding `JvmThreadMetrics` it should help us narrow down the issue.
