### ISSUE TITLE
Using spring.metrics.filter.percentiles sets http_(client|server)_requests_duration_seconds_max to 0.0 in Spring Boot 1.5.9

### ISSUE THREAD

**Issue by robachmann** [micrometer-metrics/micrometer#284]
Given the following configuration:
```
> application.yml
spring.metrics.filter.percentiles: 0.1, 0.5, 0.95

> build.gradle
springBootVersion = '1.5.9.RELEASE'
compile 'io.micrometer:micrometer-spring-legacy:1.0.0-rc.5'
compile 'io.micrometer:micrometer-registry-prometheus:1.0.0-rc.5'
```
Produces the following Prometheus output:
```
http_server_requests_duration_seconds{app="micrometer-demo",exception="None",instance="0",method="GET",status="200",uri="/normal",quantile="0.1",} 0.079167487
http_server_requests_duration_seconds{app="micrometer-demo",exception="None",instance="0",method="GET",status="200",uri="/normal",quantile="0.5",} 0.191889407
http_server_requests_duration_seconds{app="micrometer-demo",exception="None",instance="0",method="GET",status="200",uri="/normal",quantile="0.95",} 0.381681663
http_server_requests_duration_seconds_count{app="micrometer-demo",exception="None",instance="0",method="GET",status="200",uri="/normal",} 2734.0
http_server_requests_duration_seconds_sum{app="micrometer-demo",exception="None",instance="0",method="GET",status="200",uri="/normal",} 565.975153166
http_server_requests_duration_seconds_max{app="micrometer-demo",exception="None",instance="0",method="GET",status="200",uri="/normal",} 0.0
```
as you can see, `http_server_requests_duration_seconds_max` is set to `0.0`. The same applies to `http_client_requests_duration_seconds_max`.

If I use this annotation, quantiles as well as `_max` is set: `@Timed(percentiles = {0.1, 0.5, 0.95})`

Unfortunately, in Spring Boot 2.0, the application property `spring.metrics.filter.percentiles` is not picked up but that's a different story. 

I would expect using `spring.metrics.filter.percentiles` not to set `http_(client|server)_requests_duration_seconds_max` to `0.0`. Otherwise, a property `spring.metrics.filter.max: true` would be nice to have. 

Thank you and best, 
Roman

**Comment by checketts** [comment]
Since Max is windowed, Max will show the max for a given window. Is it possible the window hasn't passed? If you watch the metric it should appear correct. 

Or alternatively if you haven't hit it for a long time perhaps max is going to zero to represent that it had no measurements?

**Comment by robachmann** [comment]
Strange, the value was set to 0.0 right after a redeployment in Cloud Foundry using Spring Boot 1.5.9 instead of 2.0 and setting the property: 
![image](https://user-images.githubusercontent.com/8127370/33801283-318cbc04-dd0b-11e7-97c3-75494eeb4ee6.png)

Let me investigate if I can reproduce it locally. Thank you :-)

**Comment by robachmann** [comment]
Ok, I can reproduce it locally: I'm pushing all metrics to a Prometheus Pushgateway once every minute using the following class:
```
// from: 'io.prometheus:simpleclient_pushgateway:0.1.0'
import io.prometheus.client.CollectorRegistry;
import io.prometheus.client.exporter.PushGateway;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

@Component
public class PrometheusPusher {

    @Autowired
    private CollectorRegistry collectorRegistry;

    @Scheduled(fixedRateString = "60000")
    public void sendMetricsToPushGateway() throws IOException {
        Map<String, String> prometheusLabels = new HashMap<>(); // some tags to identify the job, e.g. instance id
        String pushGatewayUrl = "localhost:9091";
        PushGateway pushGateway = new PushGateway(new URL(pushGatewayUrl));
        pushGateway.pushAdd(collectorRegistry, "spring_metrics", prometheusLabels);
    }
}
```
The received `http_client_requests_duration_seconds_max` is always `0`: 

![image](https://user-images.githubusercontent.com/8127370/33801407-6a0c7a34-dd0f-11e7-84a7-c72c9d50961a.png)

I use Jon's docker commands to run a Pushgateway locally: https://github.com/micrometer-metrics/micrometer/issues/243#issuecomment-347923401

**Comment by jkschneider** [comment]
Thanks @robachmann. We'll take a look.
