### ISSUE TITLE
Allow Cumulative counting in InfluxMeterRegistry

### ISSUE THREAD

**Issue by bentatham** [micrometer-metrics/micrometer#2842]
`InfluxMeterRegistry` today (v1.7.5) only allows step counting, meaning the aggregation of counters is done in the application. 

**Rationale**
When looking at counters and timers in grafana (or other visualizations), being able to look at differences in the counts over time is very helpful. Doing this for arbitrary time points is much easier with cumulative counters (although I suspect there is some serious philosophical debates at this). I think it should be up to the user to decide which counting mode to use.

**Additional context**
 
Implementation options:
1. Allow extending `InfluxMeterRegistry`, and its `Builder`, to we can override the creating of the meters (which effectively invalidates the extension of `StepMeterRegistry`)
1.  Don't extend `StepMeterRegistry`, and instead mimic what `SimpleMeterRegistry` does by making a configurable counting mode (STEP or CUMULATIVE)
1. Go even further and add configurable counting mode to `PushMeterRegistry` to benefit other registries to have similar behaviour.

I think option #2 makes the most sense for now.

**Comment by bentatham** [comment]
I apologize for my delay in replying. Clearly a contentios issue (as I assumed), and I don't mean to ruffle any feathers about it.

To summarize, I completely agree on the concept of using (visualizing, monitoring, etc) rates rather than absolute/cumulative counts. I think this is merely a discussion of _where_ the rate is calculated - in the application or in the influx backend when the metrics is being used (ie using [non_negative_derivative](https://docs.influxdata.com/influxdb/v1.8/query_language/functions/#non_negative_derivative) and in some cases [non_negative_difference](https://docs.influxdata.com/influxdb/v1.8/query_language/functions/#non_negative_derivative) (although that one has many of the problems you mentioned, depending on the use case). 

To me, the latter allows for greater flexibility in changing the time period of which are looking at the rate, etc. And is also far less susceptible to missing a spike or other anomaly in the data because you can never miss the increase (unless the application restarts before reporting), whereas if you report each step and then reset in the application, influx may never see the anomalous value.

I'll respond to some specific points as well, at the risk of repeating myself.

> Does cumulativeSum work for you?

Theoretically, yes, but you lose data if individual steps are not published due to varying issues, as mentioned  "There may be loss of publishes on network/backend issues".

> if all of your applications aren't configured consistently

I definitely agree on the consistency issue. And in general, out-of-box (opinionated) libraries that enforce that are good. But I think libraries should also be flexible to allow developers (and companies across their applications even) to make choices as they see fit. Convention over Configuration, but still Flexible.

> ...exact absolute counts of metrics should not be relied upon. Metrics are not published as part of the business transaction that they may be representing. There may be loss of publishes on network/backend issues and partial step intervals may be lost on shutdown or instance failure.

Isn't the same true for reporting step counters? And in my view even worse, because if one step value is not published, you could miss an entire spike in the data. Whereas is one report of a cumulative counter is dropped, you miss the exact time the step happened, but you never miss the step (other than a restart of the application).

**Comment by marcingrzejszczak** [comment]
@bentatham did @shakuzen answer your concerns? Can we close this?
