### ISSUE TITLE
Provide a Grafana dashboard for Spring Kafka Metrics

### ISSUE THREAD

**Issue by KoumiArt** [micrometer-metrics/micrometer#2855]

**Comment by shakuzen** [comment]
I assume you mean the metrics registered when using the `KafkaMetrics` class in Micrometer. This is not specific to Spring, and it registers the metrics provided by the Kafka clients. As such, we do not define what metrics there are and they can change across Kafka client versions. Therefore I think this is more appropriate as a request for the Kafka client team that controls the Kafka client metrics.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
