### ISSUE TITLE
OpenTelemetry Protocol (OTLP) MeterRegistry

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2864]
**Please describe the feature request.**
Use Micrometer to ship metrics in [OTLP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md) format for metrics.

**Rationale**
Some metrics backends and metrics intermediaries like proxies/collectors/daemons that may do some processing of metrics before ingestion will support OpenTelemetry Protocol format. If there is enough interest from users, we should support this use case.

**Additional context**
This can be separate from a MeterRegistry implementation that delegates to OpenTelemetry metrics API. By focusing on the publishing format, this makes it most similar to other `MeterRegistry` implementations.

While the rest of the OTel metrics efforts are not stable yet, the OTLP metrics format is marked stable, unblocking this work.

**Comment by sfc-gh-twicksell** [comment]
+1 to this issue, I have this exact problem of needing to interact with a proxy which supports OTLP.

**Comment by twicksell** [comment]
+1 to this issue, I have this exact problem of needing to interact with a proxy which supports OTLP.
