### ISSUE TITLE
LogbackMetrics: SubstituteLoggerFactory cannot be cast to class LoggerContext

### ISSUE THREAD

**Issue by hestad** [micrometer-metrics/micrometer#2868]
**Describe the bug**
https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/LogbackMetrics.java#L56

`this(tags, (LoggerContext) LoggerFactory.getILoggerFactory());`

`ILoggerFactory` has another implementation in addition to `LoggerContext`, namely `SubstituteLoggerFactory`. We are running our application tests in parallell where our application is setup once for each test. This includes a call to LogbackMetrics() via ktor's MicrometerMetrics. In some cases when LoggerFactory.getILoggerFactory() is called in parallell you receive a SubstituteLoggerFactory instead.

**Environment**
 - Micrometer version 1.7.5
 - Micrometer registry prometheus
 - OS: macOs and Ubuntu 20
 - Java version: 16 and 17

**To Reproduce**
Possible to checkout https://github.com/navikt/su-se-bakover and run `./gradlew test`
But a smaller case would be to setup a lot of parallell tests calling LogbackMetrics() 

**Expected behavior**
>java.lang.ClassCastException: class org.slf4j.helpers.SubstituteLoggerFactory cannot be cast to class ch.qos.logback.classic.LoggerContext (org.slf4j.helpers.SubstituteLoggerFactory and ch.qos.logback.classic.LoggerContext are in unnamed module of loader 'app')
        at io.micrometer.core.instrument.binder.logging.LogbackMetrics.<init>(LogbackMetrics.java:56)
        at io.micrometer.core.instrument.binder.logging.LogbackMetrics.<init>(LogbackMetrics.java:52)
        at no.nav.su.se.bakover.web.routes.NaisRoutesKt$installMetrics$1.invoke(NaisRoutes.kt:56)
        at no.nav.su.se.bakover.web.routes.NaisRoutesKt$installMetrics$1.invoke(NaisRoutes.kt:48)
        at io.ktor.metrics.micrometer.MicrometerMetrics$Feature.install(MicrometerMetrics.kt:213)
        at io.ktor.metrics.micrometer.MicrometerMetrics$Feature.install(MicrometerMetrics.kt:171)
        at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:68)
        at no.nav.su.se.bakover.web.routes.NaisRoutesKt.installMetrics(NaisRoutes.kt:48)

**Comment by shakuzen** [comment]
[This](https://stackoverflow.com/questions/21335805/logback-and-slf4j-programmatic-configuration) might be relevant. If you can get it to reproduce in a minimal sample, it would help in testing that it doesn't happen anymore after a fix.

**Comment by hestad** [comment]
jdoodle.com/ia/jPG

`import java.util.concurrent.CyclicBarrier;
public class MyClass {
    
    public static void main(String args[]) throws InterruptedException {
      int numberOfThreads = 10;
      final CyclicBarrier gate = new CyclicBarrier(numberOfThreads+1); // Waiting on mains thread gate.await() as well.
      for (int i = 0; i < numberOfThreads; i++) {
        new Thread(new Runnable()  {
          public void run() {
            try {
              gate.await();
            } catch(Exception e) {
              throw new RuntimeException(e);
            }
            new io.micrometer.core.instrument.binder.logging.LogbackMetrics();
          }
        }).start();
      }
      try {
        gate.await();
      } catch(Exception e) {
        throw new RuntimeException(e);
      }
    }
}`

**Comment by shakuzen** [comment]
@hestad Thank you for the isolated code. I've adapted it to a test in #3669 along with a "fix" that seems to resolve the issue.

**Comment by shakuzen** [comment]
@hestad Let us know if the latest snapshots containing the mentioned fix solve the problem for you or not.

**Comment by hestad** [comment]
Seems like it works both with and without the snapshot-patch, at least locally 😓 Let's see what the build server says: https://github.com/navikt/su-se-bakover/pull/1293

**Comment by shakuzen** [comment]
> Seems like it works both with and without the snapshot-patch, at least locally

If there is any static initialization of a LoggerFactory, then that avoids the issue. Perhaps your code has been changed since originally filing this issue such that it has that somewhere now? I had to make a new test class to reproduce the issue and avoid a static initialization from masking the issue.
