### ISSUE TITLE
Jdbc Registry Support

### ISSUE THREAD

**Issue by pxzxj** [micrometer-metrics/micrometer#2878]
**Please describe the feature request.**
Support saving metrics in common relational databases like MySQL、Oracle etc
**Rationale**
In some small projects, we try to save all data in the database to avoid installing other software

**Comment by checketts** [comment]
This is available using a SimpleMeterRegistry. Subclass it and override the report method (I think) and write to your DB

**Comment by pxzxj** [comment]
I know it can be achieved by creating a few tables ,extends MeterRegistry and override some methods，But if many projects need the jdbc registry (i'm not sure)，that shoud be implement in this offical repo

**Comment by shakuzen** [comment]
I'm not sure traditional relational databases are a good choice for efficiently storing and querying dimensional metrics (time series data). That said, if there were something that was a good fit over JDBC and it had enough interest from users, we could consider it. So far I don't think there's been much interest expressed in light of other options. If you wanted to publish a `MeterRegistry` implementation outside of this repository, you could start there and gather feedback from interested users.
