### ISSUE TITLE
Counters are incorrectly created as Gauges in Datadog

### ISSUE THREAD

**Issue by khelenek** [micrometer-metrics/micrometer#288]
To reproduce: 
Create a new metric, for example: Metrics.counter("datadog.test", "key", "value").increment(100)

In datadog, go to the metrics explorer. Search for "datadog.test" and confirm the new metric is of type Gauge.

**Comment by khelenek** [comment]
Looks like this might be a limitation of the DataDog API method for sending metrics. Perhaps we should highlight that in the docs? For many that is probably a deal breaker and the statsd route is the correct option. 
https://docs.datadoghq.com/metrictypes/

**Comment by checketts** [comment]
@khelenek What is the deal breaker you are referring to? 

#289 fixes the `count` problem you had noted.

**Comment by khelenek** [comment]
Sorry, I could absolutely be in the wrong here. I thought the docs suggested it just wasn't possible to  create anything but a Gauge using the API. Note that I didn't test using the agents/statsd approach which likely works fine. I'm happy to test your fix again though if you found a solution. Thanks again for your work on this.

**Comment by jkschneider** [comment]
I'm happy to report _more accurate_ metadata to Datadog, at least to the extent it is possible, but I do not understand the practical impact of mislabeling a particular metric. Seems like the display is the same, same functions available, etc. Can you elaborate on what might be a dealbreaker if we couldn't fix this perfectly?

**Comment by jkschneider** [comment]
Ah, I see there was an explanation on #289:

> Yeah it affects the usage, not just the categorization. For a gauge you can't do things like total count for the last hour/day/etc. It treats it more like a sampling of the data at that time.

**Comment by jkschneider** [comment]
Also to verify: base units are added to metadata correctly.

**Comment by jkschneider** [comment]
...and description text.

**Comment by jkschneider** [comment]
Boot 2 change: We added `DatadogConfig#descriptions()`

**Comment by jkschneider** [comment]
@khelenek For this to work, you'll have to set `spring.metrics.export.datadog.applicationKey` in addition to `spring.metrics.export.datadog.apiKey` (or a similar property binding to `DatadogConfig` if you aren't using Spring). Datadog doesn't allow us to adjust metric metadata without that additional key.
