### ISSUE TITLE
Conversion of Base Units with regards to the Prometheus Registry

### ISSUE THREAD

**Issue by Channyboy** [micrometer-metrics/micrometer#2911]
Hello,

I have the following:

```
        PrometheusMeterRegistry pmr = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
        
        Gauge.builder("myGauge1", () -> { return 4000;}).baseUnit("milliseconds").register(pmr);
        Gauge.builder("myGauge2", () -> { return 4000;}).baseUnit("ms").register(pmr);
        
        
        String output = pmr.scrape();
        System.out.println(output);
```
And the output is 
```
# HELP myGauge2_ms
# TYPE myGauge2_ms gauge
myGauge2_ms 4000.0
# HELP myGauge1_milliseconds
# TYPE myGauge1_milliseconds gauge
myGauge1_milliseconds 4000.0
```
The  Prometheus (and/or OpenMetrics) output is expected to be in base units. In this case it would be seconds.
Is there something I need to configure or is this a bug?

**Comment by checketts** [comment]
I'm not certain, but I think the `baseUnits` is a default label. Not certain that is does any conversion. In your gauge example, you are overridding the base unit so it is displaying it as the suffix.

**Comment by Channyboy** [comment]
Right with Prometheus/OpenMetrics the name should include the units as a suffix where applicable. But with Prometheus/OpenMetrics it should be converted to one of the base units (5th para at https://prometheus.io/docs/instrumenting/writing_exporters/#naming) and the Open Metrics doc at https://prometheus.io/docs/instrumenting/writing_exporters/#naming.

So for example, If I want to _gauge_ an  MXbean attribute that returns nanoseconds or milliseconds it should be formatted to be in the _seconds_ base unit in the final output. I didn't find any related issues so I'm not sure if I'm missing something :(

**Comment by flyletc** [comment]
hello 
I have a question. When I use Gauge, the value of the indicator has not changed.The value reported for the first time is recorded. 
I don't know where I made a mistake.
The test code:
```
@Component
public class GaugeTimer {

    @Autowired
    private MeterRegistry registry;

    @Scheduled(cron = "*/10 * * * * ?")
    public void incrementGauge(){
        int i = new Random().nextInt(100);
        Integer integer = new Integer(i);
        String metricName = "test_cpu_usage";
        Gauge.builder(metricName, integer, new ToDoubleFunction<Integer>() {
            @Override
            public double applyAsDouble(Integer value) {
                if (value == null) {
                    return 0;
                } else {
                    return value;
                }
            }
        }).description("test my metrics")
          .tags("name","cpu","devId","test01")
          .register(registry);
```
so sorry, are you experiencing similar problems and are there any solutions

**Comment by shakuzen** [comment]
@flyletc it's not related to this issue. See [this section of the documentation](https://micrometer.io/docs/concepts#_manually_incrementing_or_decrementing_a_gauge) and specifically the warning at the end:

> Attempting to construct a gauge with a primitive number or one of its `java.lang` object forms is always incorrect. These numbers are immutable. Thus, the gauge cannot ever be changed. Attempting to “re-register” the gauge with a different number does not work, as the registry maintains only one meter for each unique combination of name and tags.

You should use and maintain a reference to an `AtomicInteger` and update that. There is no need to register the gauge more than once.

**Comment by shakuzen** [comment]
@Channyboy Sorry for the delay in responding. If you want Micrometer to handle time conversion of gauge values, you need to use `TimeGauge` instead of `Gauge`. See a sample test case:

```java
@Test
void timeGauge() {
    AtomicInteger msTimeGauge = new AtomicInteger(4000);
    AtomicInteger usTimeGauge = new AtomicInteger(4000);
    TimeGauge.builder("my.gauge", msTimeGauge, TimeUnit.MILLISECONDS, AtomicInteger::get).register(registry);
    TimeGauge.builder("my.other.gauge" , usTimeGauge, TimeUnit.MICROSECONDS, AtomicInteger::get).register(registry);
    System.out.println(registry.scrape());
}
```

With output:

```
# HELP my_gauge_seconds  
# TYPE my_gauge_seconds gauge
my_gauge_seconds 4.0
# HELP my_other_gauge_seconds  
# TYPE my_other_gauge_seconds gauge
my_other_gauge_seconds 0.004
```

We should document this in the reference documentation. I've opened https://github.com/micrometer-metrics/micrometer-docs/issues/209 for that.

**Comment by Channyboy** [comment]
@shakuzen  I seemed to have missed the notifications too. Thanks for the information!
Is there some support for other units such as bytes, kilobytes, etc. 
I should've asked that in the issue by diversifying my examples :(

**Comment by checketts** [comment]
Actual conversion of units is a display concern. (See this article https://www.robustperception.io/who-wants-seconds)

Prometheus encourages using bytes and seconds, then Grafana handles the human readability of the units.

**Comment by shakuzen** [comment]
We don't do automatic conversion for units other than time, but you can specify the base unit of a meter, which will be used as the suffix in Prometheus. As @checketts mentions, Prometheus suggests standard units.
