### ISSUE TITLE
OkHttp Metric Enhancements

### ISSUE THREAD

**Issue by msmerc** [micrometer-metrics/micrometer#2914]
Hi,

Can I propose a couple of OkHttp enhancements:

1. Currently the URL mapper is not applied if the reply is HTTP 404 (or 301). This means that all 404 reposes fall in the same bucket. However it's not uncommon for a REST api to use 404 for a valid response e.g. "user not found", in which cases I'd expect these 404 metrics to be in the same bucket as "user was found".

I propose removing changing the return of getUriTag() to: `return state.response != null ? "NOT_FOUND" : urlMapper.apply(request);`

https://github.com/micrometer-metrics/micrometer/blob/67c41db552cac463e44cd45545e5a7b8f3513f1b/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java#L201

2. Currently the set of tags is very prescriptive. You will ALWAYS get tags for scheme, host (even if you set `includeHostTag=false`), port, method, status, url. This can cause a proliferation of prometheus metrics. It might be that some users don't wish to create quite so many metrics in their Prometheus instances.

Proposal: Either: create a `protected Iterable<Tag> generateContextTags(Request request, Response response)` so that users can subclass and provide their own tags.

Or: Refactor all the existing tags so that they are `contextSpecificTags`, and change the builder so that by default in includes a "standard" set of context specific tags which users can choose to add to or replace completely. This would certainly be neater but would requires some minor changes to the API, specifically contextSpecificTags should be `Function<CallState, Tag>` not `BiFunction<Request, Response, Tag>`. It shouldn't be too hard to do this and still maintain backwards compatibility (if required).

(There's a 20% chance I'd be able to submit these changes as a pull request - if you'd be open to it that is).

**Comment by marcingrzejszczak** [comment]
You can use the latest observation instrumentation and modify the way [observation convention](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/DefaultOkHttpObservationConvention.java) is applied
