### ISSUE TITLE
Spring Boot 2.6.x - Jvm Metrics Missing

### ISSUE THREAD

**Issue by headfox23** [micrometer-metrics/micrometer#2925]
**Describe the bug**
After an upgrade of spring boot to 2.6.1 we lost almost all metrics which were exposed with micrometer-registry-prometheus.
For example all jvm_xxx metrics are missing, all http_server_requests_seconds_bucket are missing which were configured with slo config.

**Environment**
 - Micrometer version 1.8.1
 - Micrometer registry for prometheus
 - OS: Ubuntu and other distros on cloudfoundry
 - Java version: 13

**To Reproduce**
How to reproduce the bug:
Take any application with spring boot 2.5.x with micrometer prometheus and upgrade it to spring boot 2.6.x

**Expected behavior**
All metrics which were exported before should still be available

**Additional context**
I dont know if this is a micrometer or spring-boot bug. Therefore i start here :)

**Comment by headfox23** [comment]
Details about versions:
```
 <properties>
        <java.version>11</java.version>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- region plugin versions-->
        <frontend-maven-plugin.version>1.12.0</frontend-maven-plugin.version>
        <maven-resources-plugin.version>3.2.0</maven-resources-plugin.version>
        <typescript-generator-maven-plugin.version>2.34.976</typescript-generator-maven-plugin.version>
        <jacoco-maven-plugin.version>0.8.7</jacoco-maven-plugin.version>
        <!-- endregion -->
        <!-- region main versions-->
        <spring-boot.version>2.6.1</spring-boot.version>
        <!-- endregion -->
    </properties>
...
   <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-sleuth</artifactId>
                <version>3.1.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.security.oauth.boot</groupId>
                <artifactId>spring-security-oauth2-autoconfigure</artifactId>
                <version>${spring-boot.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.security.oauth</groupId>
                <artifactId>spring-security-oauth2</artifactId>
                <version>2.5.1.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-registry-prometheus</artifactId>
                <version>1.8.1</version>
            </dependency>
         ...
        </dependencies>
    </dependencyManagement>
```

**Comment by checketts** [comment]
I suspect it is a spring boot bug. Can you create a sample project that should show the jvm metrics?

**Comment by shakuzen** [comment]
For what it's worth, I just tried a sample Spring Boot app with Spring Boot 2.6.1 and the prometheus registry, and I didn't notice any missing metrics in the `/actuator/prometheus` endpoint. So as @checketts mentioned, we're going to need a sample project to figure out what's wrong.

**Comment by checketts** [comment]
Some ideas that might be at play: if you are providing a PrometheusMeterRegistry instead of using the provided one or if you are using Spring cloud, since it could be initializing things very early in the lifecycle, causing unexpected behavior

**Comment by headfox23** [comment]
I'm currently looking into it.
The minimal project which I created expose the metrics correctly.
I now add dependencies one by one.
Seems to be somehow security related.

**Comment by headfox23** [comment]
Finally i found the issue.
It was caused by a custom WebSecurityConfigurerAdapter.
I refactored it and now the standard metrics are back.

I assume its more related to spring boot then micrometer...
But could not validate this in detail.

Thank you all for your quick response!

**Comment by TheImplementer** [comment]
@headfox23 I think I'm in a similar situation, what did you do to fix it? Thanks.

**Comment by headfox23** [comment]
@TheImplementer I removed security chains and figured out which caused this issue.
Then I refactored this and it worked somehow :)

**Comment by headfox23** [comment]
after the upgrade to spring boot 2.7.0 they disappeared again... :/

**Comment by shakuzen** [comment]
@headfox23 I would check your dependency management. In your previous snippet, you are hard-coding some versions, which you should generally avoid. Let Spring Boot manage the version of Micrometer dependencies unless you are intentionally using a different version. I have generated a project from https://start.spring.io with web, actuator, and prometheus dependencies. It has JVM metrics in the Prometheus endpoint. So we will need more information about your application or preferably, a minimal sample application that reproduces the issue you are seeing. Make sure you are using compatible version of dependencies - Spring Boot, Spring Cloud, Micrometer, etc.

**Comment by headfox23** [comment]
Since the "problem" changed a bit i can also open a new ticket...

**Comment by headfox23** [comment]
new ticket: https://github.com/micrometer-metrics/micrometer/issues/3207
