### ISSUE TITLE
Support "database" tag in "mongodb.driver.commands" metric

### ISSUE THREAD

**Issue by sshplendid** [micrometer-metrics/micrometer#2932]
It would be nice to support `database` tag.
[CommandStartedEvent](https://github.com/mongodb/mongo-java-driver/blob/master/driver-core/src/main/com/mongodb/event/CommandStartedEvent.java) already has database information.
And It will be useful to applications that has multiple mongodb connections (several databases)

Releated to https://github.com/micrometer-metrics/micrometer/issues/1799 , I think that it will be good to collect database name while collecting the collection name.

**Comment by jonatan-ivanov** [comment]
By database tag you mean the hostname:port?
We do have a `server.address` tag which provide this information.

**Comment by sshplendid** [comment]
@jonatan-ivanov Thanks for feedback!
I mean database name of mongodb connection, not hostname and port.

> #### database
> A physical container for collections. Each database gets its own set of files on the file system. A single MongoDB server typically has multiple databases
> https://docs.mongodb.com/manual/reference/glossary/#std-term-database

FYI, Mongo`CommandStartedEvent` already supports the database name.
https://github.com/mongodb/mongo-java-driver/blob/master/driver-core/src/main/com/mongodb/event/CommandStartedEvent.java#L30

**Comment by jonatan-ivanov** [comment]
Oh, right. Are you interest in creating a PR?

**Comment by sshplendid** [comment]
@jonatan-ivanov 
Sure. I’ll get it.
