### ISSUE TITLE
Support IoTDB Registry

### ISSUE THREAD

**Issue by jun0315** [micrometer-metrics/micrometer#2933]
Hi, friends from the community, I am an open source enthusiast from the Apache IoTDB community. At present, the IoTDB monitoring framework uses micrometer, but there is no official iotdb-registry. At present, we have implemented iotdb-registry ourselves (under preparation for review). We plan to submit an micrometer-registry-iotdb for the micrometer warehouse after optimizing the code. You are welcome to put forward various opinions.

Here are some references:

- https://iotdb.apache.org/
- https://github.com/apache/iotdb/tree/master/metrics
- https://github.com/apache/iotdb/pull/4634

**Comment by marcingrzejszczak** [comment]
We will be very happy to review the registry that is in your codebase. Can you point us to that registry so that we can perform the review?
