### ISSUE TITLE
Better support for Kibana

### ISSUE THREAD

**Issue by pbartoszek** [micrometer-metrics/micrometer#2936]
It seems to me that the way metrics are sent to Elasticsearch doesn't make it very convenient to query them in Kibana... It was already described in https://stackoverflow.com/questions/67149967/micrometer-elasticsearch-convert-json-name-to-key

The thing is that Kibana allows to search for metric name based on the field name appearing in ES document..
So having a counter named jvm_threads_daemon in micrometer should send it as

```
    {... "jvm_threads_daemon": "18", "type": "counter"} 
```
rather than
```
{... name:"jvm_threads_daemon", "type": "counter", "count":18} 
```
Of course it's a breaking change but it should be possible to configure it via flag for instance...

**Comment by jonatan-ivanov** [comment]
Could you please help us a little what would that look like?
I'm not sure I see why using the name as the key is it better: `name:jvm_threads_daemon` vs. `_exists_: jvm_threads_daemon`

**Comment by pbartoszek** [comment]
I guess ES is used with Kibana in a majority of cases... and you want to find a metric in kibana you can just start typing metric name. Example

![image](https://user-images.githubusercontent.com/8142131/148211385-99d0ac13-fa3a-4de6-8e47-5cada1b7079a.png)

but this only works for `_exists_: jvm_threads_daemon` case as far as I know

**Comment by shakuzen** [comment]
> In the case of `name:jvm_threads_daemon` no hints are provided by Kibana...

@pbartoszek I tried now with Kibana 8.3 and it does show values for the `name` field.
![image](https://user-images.githubusercontent.com/8924140/180020117-157d3f2b-8037-404a-9326-4ac4f3b69f3e.png)
![image](https://user-images.githubusercontent.com/8924140/180020238-fb244140-469e-4696-9238-777e31fa11e9.png)

In your example, you use a counter, which only has a count value. However, Timer and DistributionSummary have multiple values (count, sum, mean, max). Which would be the value for the field of the metric name? I don't know how the proposed format would work for these types.

**Comment by shakuzen** [comment]
I think with recent versions of Kibana, the usability is improved as shown in the screenshots in my previous comments. If I'm missing something, let us know and we can consider reopening this issue.
