### ISSUE TITLE
MetricsAutoConfiguration lacks import of CloudWatchExportConfiguration

### ISSUE THREAD

**Issue by osialr** [micrometer-metrics/micrometer#294]
Not sure if this is intentional, but `MetricsAutoConfiguration` is does not have an `@Import` of `CloudWatchExportConfiguration.class`.   

I had to manually import it in my spring app to get it picked up.

This is the code I'm referring to:
https://github.com/micrometer-metrics/micrometer/blob/b059c307a930295fa1e81b6e8a6bca580c4537a7/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/MetricsAutoConfiguration.java#L67-L75

**Comment by checketts** [comment]
Looks like an oversight.

**Comment by jkschneider** [comment]
We hadn't yet decided where to put this autoconfig. Ultimately, I think its going to go to `spring-cloud-aws`. The Spring team is fearful of having the AWS Java SDK underneath its managed dependencies (BOM), since Amazon releases a new patch release roughly every 2 weeks.

**Comment by osialr** [comment]
I completely understand. Putting it under Spring cloud sounds like a good approach. 

The aws sdk is a beast of a dependency tree and annoying to keep up to date.

**Comment by jkschneider** [comment]
Added to spring-cloud-aws in https://github.com/spring-cloud/spring-cloud-aws/commit/dc3f9aea70c4a00046a25fa59fd232742739138f.
