### ISSUE TITLE
micrometer-registry-elastic 1.8.1 fails to put data into elastic 7.16.2 with an error: only write ops with an op_type of create are allowed in data streams

### ISSUE THREAD

**Issue by yilativs** [micrometer-metrics/micrometer#2976]
**Describe the bug**
micrometer-registry-elastic 1.8.1 fails to put data into elastic 7.16.2 with an error: 
**only write ops with an op_type of create are allowed in data streams**

**Environment**

 - Micrometer version: 1.8.1
 - Micrometer registry : elastic
 - OS: linux
 - Java version: 11

**To Reproduce**
How to reproduce the bug:
setup spring boot 2.6.2 with micrometer and elastic registry
(if needed I can provide a link to a git hub repository reproducing the error)

**Expected behavior**
micrometer does not fail when sends metrics to elastic.

**Additional context**
Everything works fine with elastic 7.6.2 however when we tried to updated to 7.16.2 
an error show up with message:  only write ops with an op_type of create are allowed in data streams

**Comment by shakuzen** [comment]
As a first quick question before looking into this more, are you customizing the index name configuration (`ElasticConfig#index`) or using the default (`micrometer-metrics`)?

**Comment by yilativs** [comment]
I'm default from SpringBoot.

**Comment by shakuzen** [comment]
I made a sample app from start.spring.io using Spring Boot 2.6.2 and I started an elasticsearch container with:

```
docker run -p 127.0.0.1:9200:9200 -p 127.0.0.1:9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.16.2
```

I was able to publish metrics from the app to the elasticsearch container.
Could you provide a minimal sample app and steps to reproduce the issue you are seeing?

**Comment by yilativs** [comment]
I found the reason.
I was using management.metrics.export.elastic.index=**metrics**
but it was changed in 
https://github.com/micrometer-metrics/micrometer/pull/2288/commits/e5257abcb5e634cb1a1cffb951f6316fb394f1fb

I'm closing this issue, sorry for taking your time!
