### ISSUE TITLE
Add support for Azul Prime's (Zing) C4 (GPGC)

### ISSUE THREAD

**Issue by leelamv** [micrometer-metrics/micrometer#2982]
[Azul Prime](https://www.azul.com/products/prime/) which is based on OpenJDK consists of [C4 GC ](https://www.azul.com/products/components/pgc/). For monitoring the java heap, Azul prime supports standard MXbeans. However, names of those memory pools / memory managers and GC memory manages which are accessed thru MXBeans are different. 

This issue is created to make relevant changes to access pools/managers in Azul prime. Plan is to provide the changes from me.

**Comment by jonatan-ivanov** [comment]
Hi,

This is great to hear and it's an interesting addition to Micrometer.
My only concern is testing and troubleshooting this. Do you happen to know if we can get licenses to test the integration?

**Comment by leelamv** [comment]
[Azul Platform Prime Stream Builds ](https://www.azul.com/products/prime/stream-download/)are free for development, testing, and evaluation. I am trying to setup CircleCI to test using Azul prime builds on [docker hub](https://hub.docker.com/r/azul/prime).

**Comment by leelamv** [comment]
This was delayed for various reasons. I wouldn't be contributing to this but there would be other person working on this.

**Comment by jonatan-ivanov** [comment]
Ok, please let us know if you have questions/need help.

**Comment by andrew-krasny** [comment]
@jonatan-ivanov , @shakuzen , is there anything I can help with to accept the #3582? ;)
Thanks!
