### ISSUE TITLE
`PUT` count is always 0 for caffeine.

### ISSUE THREAD

**Issue by mangatmodi** [micrometer-metrics/micrometer#2993]
**Describe the bug**
I have raised the same issue here - https://github.com/ben-manes/caffeine/issues/660. The maintainer has confirmed that Caffeine doesn't support metrics on the `PUT` operation

**Environment**

 - Micrometer version: 1.8.2
 - Micrometer registry: Prometheus
 - OS: Linux
 - Java version: openjdk version "11.0.13"

**To Reproduce**
How to reproduce the bug:
1. Use Caffeine binder.
2. `PUT` data into caffeine.
3. `GET` some data
3. Metrics shows only `GET `.

**Expected behavior**
Either `PUT` should show some data, or we should comment that caffeine doesn't support `PUT` metrics

**Additional context**

**Comment by marcingrzejszczak** [comment]
Do I understand this correctly, that in the test below you would like after doing a `cache.put` to have the `putCount` return `1` and due to the fact that Caffeine doesn't store puts, and we redirect `putCount` to load count you feel confused?

```java
@Test
    void caffeineCacheMetricsStatisticsAreNotAwareOfPut() {
        LoadingCache<String, String> cache = Caffeine.newBuilder()
            .recordStats()
            .build(key -> "");

        CaffeineCacheMetrics<String, String, Cache<String, String>> metrics = new CaffeineCacheMetrics<>(cache,
            "testCache", expectedTag);

        MeterRegistry meterRegistry = new SimpleMeterRegistry();
        metrics.bindTo(meterRegistry);

        cache.put("foo", "bar");
        // assertThat(metrics.putCount()).isEqualTo(1); // This assertion would fail, put count is 0
        cache.get("foo");

        assertThat(metrics.hitCount()).isEqualTo(1); // for "foo"

        cache.get("baz"); // this triggers a load cause there's no "baz"
        assertThat(metrics.missCount()).isEqualTo(1); // missed "baz"
        assertThat(metrics.putCount()).isEqualTo(1); // the assertion passes cause put == load stat, there was 1 load
    }
```
