### ISSUE TITLE
Allow to set upper bound for tag values count of all meters (increase safety to use tags)

### ISSUE THREAD

**Issue by anschnapp** [micrometer-metrics/micrometer#2999]
**Please describe the feature request.**
Allowing for meters (like Counter) to set an upper tag value count limit per tag type.
Maybe only support this for small upper bounds numbers, so it could be easily be implemented by comparing with a fairly small in memory map of old values...

**Rationale**
I often have a situation where i use a meter like counter with one or multiple tags where the tag values are theoretically bounded and should have a low cardinality...

... but it's depends on some code which is not close related to the one where i'm using the meter.
I could review all sections (and normally i'm doing so) to check if cardinality is really low and bounded.
But the code is not close for change and for me it feels like it's not safe (enough) to use this kind of values as a tag because it could have severe performance issues if the tag value size is not bounded (any longer) and therefore could increase without limits.

I was thinking about customizing or decorate the meter, but then i thought this is a quite common issue which might be something to solve for everyone. For me this could make handling of tags more easy and most importantly more safe and stable.

**Comment by shakuzen** [comment]
If I'm understanding the behavior you want, this should already be achievable by configuring a `MeterFilter`. See [this section](https://micrometer.io/docs/concepts#_deny_or_accept_meters) of the documentation. We provide a convenience method `maximumAllowableTags`. This is used, for example, with the instrumentation of HTTP clients when tagging the URI if we can't know for certain we are tagging a templated URI (thus bounded in cardinality).
Does that fit what you're trying to do?

**Comment by anschnapp** [comment]
@shakuzen  thank you! that's exactly what i was looking for!
