### ISSUE TITLE
All RestTemplate requests are recorded twice, once with parameter substitution, once without

### ISSUE THREAD

**Issue by marcoschulte** [micrometer-metrics/micrometer#300]
All RestTemplate requests are recorded twice, e.g.

    http_client_requests_duration_seconds_count{clientName="localhost",method="GET",status="200",uri="api/user/{id}",} 1.0
    http_client_requests_duration_seconds_sum{clientName="localhost",method="GET",status="200",uri="api/user/{id}",} 26.363359379
    http_client_requests_duration_seconds_max{clientName="localhost",method="GET",status="200",uri="api/user/{id}",} 0.0
    http_client_requests_duration_seconds_count{clientName="localhost",method="GET",status="200",uri="api/user/1",} 1.0
    http_client_requests_duration_seconds_sum{clientName="localhost",method="GET",status="200",uri="api/user/1",} 27.81834886
    http_client_requests_duration_seconds_max{clientName="localhost",method="GET",status="200",uri="api/user/1",} 0.0

The reason for this is that the `MetricsClientHttpRequestInterceptor` gets registered twice. Once the inner of those two finishes, it clears the ThreadLocal where it stores the urlTemplate (`io.micrometer.spring.web.client.MetricsClientHttpRequestInterceptor:72`), so the outer interceptor does a fallback the the HttpRequest's uri (`io.micrometer.spring.web.client.RestTemplateExchangeTags:38`).

The interceptor gets registered twice with each RestTemplate because it is provided as a bean (`io.micrometer.spring.autoconfigure.web.client.RestTemplateMetricsConfiguration#metricsRestTemplateCustomizer`), therefore it is getting automatically applied by Spring's `RestTemplateBuilder`, and because a BeanPostProcessor is provided as a bean, which registers the Interceptor again (`io.micrometer.spring.autoconfigure.web.client.RestTemplateMetricsConfiguration.MetricsInterceptorPostProcessor#postProcessAfterInitialization`).

Solutions:

I don't understand what you had in mind with the BeanPostProcessor but in my opinion I would simply remove it. The only reason for it that I see is to automatically register the interceptor with RestTemplates that aren't created with the RestTemplateBuilder. But if someone does that, he might have good reason and explicitly does not want this to happen anyways.
If you have good reason to keep the PostProcessor, another solution might be to alter the logic that adds the interceptor twice. It could check beforehand, whether the interceptor is already added (`io.micrometer.spring.web.client.MetricsRestTemplateCustomizer#customize`).

**Comment by marcoschulte** [comment]
Btw., we temporarily fixed it with

```java
@Configuration
@EnableAspectJAutoProxy
public class FixMicrometerHttpMetricsConfiguration {

    @Bean
    public FixMetricsAdvice fixMetricsAdvice() {
        return new FixMetricsAdvice();
    }

    @Aspect
    public class FixMetricsAdvice {

        private static final String INTERCEPTOR_CLASS_NAME = "io.micrometer.spring.web.client.MetricsClientHttpRequestInterceptor";

        @Around("execution (void io.micrometer.spring.web.client.MetricsRestTemplateCustomizer.customize(org.springframework.web.client.RestTemplate))")
        public Object interceptRestTemplateCustomizer(ProceedingJoinPoint pjp) throws Throwable {
            Object[] args = pjp.getArgs();

            Assert.isInstanceOf(RestTemplate.class, args[0], "must be of type RestTemplate");
            RestTemplate restTemplate = (RestTemplate) args[0];

            Optional<ClientHttpRequestInterceptor> metricsInterceptor = restTemplate.getInterceptors().stream()
                    .filter(interceptor -> Objects.equals(interceptor.getClass().getName(), INTERCEPTOR_CLASS_NAME))
                    .findFirst();

            if (!metricsInterceptor.isPresent()) {
                pjp.proceed();
            }

            return null;
        }
    }
}
```

**Comment by jkschneider** [comment]
Thanks @marcoschulte. We'll take a look.

**Comment by jkschneider** [comment]
Thanks for the detailed analysis @marcoschulte. Removed the BPP in rc6. Boot's [docs](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-restclient.html) lead you to the conclusion that you should generally use `RestTemplateBuilder` anyway.
