### ISSUE TITLE
@Timed on @Scheduled Spring Beans don't register timing metrics

### ISSUE THREAD

**Issue by nickstolwijk** [micrometer-metrics/micrometer#301]
I tried to get the @Timed annotation to work on my @Scheduled beans, but it doesn't give any results.

I added spring-boot-starter-aop as a dependency and tried the following configuration:
```
@Configuration
@EnableScheduling
@EnableAspectJAutoProxy
public class Schedulers {

    @Scheduled(fixedDelay = 10_000)
    @Timed("execute.synchronize")
    public void executeSynchronize() {
        // Execute some tasks removed for brevity
    }
}
```

**Comment by mweirauch** [comment]
For the record:
* this is boot 2.0.0.M7

> mweirauch [13:57 Uhr] 
> @Nick Stolwijk the sb2 MetricsAutoConfiguration is missing the ScheduledMethodMetrics bean for being picked up by aspectj. you can auto-register it temporarily until a fix arrives in sb2. here's the code: https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/MetricsAutoConfiguration.java#L121

**Comment by jkschneider** [comment]
For now, we are making a manually configurable `TimedAspect` available in `micrometer-core` for use in Boot 2. We will revisit a general purpose application of `@Timed` via either AOP or a BPP in Boot 2.1. See #361.
