### ISSUE TITLE
@Timed on @JMSListener should register timing metrics

### ISSUE THREAD

**Issue by nickstolwijk** [micrometer-metrics/micrometer#302]
Using Spring JMS and Spring Boot 2 I want to be able to put the @Timed annotation on the methods with @JMSListener, so I can track how much messages I have processed and how long they took. (See the functionality for @Scheduled)

**Comment by jkschneider** [comment]
Dependent on https://jira.spring.io/browse/SPR-14683

**Comment by klr8** [comment]
@nickstolwijk,
What exactly is preventing you from putting the @Timed annotation no an @JmsListener annotated method? For me this seems to work fine in Spring Boot 2.1.9:
```
@JmsListener(destination = "myqueue")
@Timed(value = "message.process", extraTags = {"queue", "myqueue"})
public void processMsg(String messageText, Message message) {
```
And
```
@Configuration
@EnableAspectJAutoProxy
public class AutoTimingConfiguration {
  @Bean
  public TimedAspect timedAspect(MeterRegistry registry) {
    return new TimedAspect(registry);
  }
}
```

**Comment by marcingrzejszczak** [comment]
There was no feedback since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
