### ISSUE TITLE
Impedance mismatch between micrometer and CloudWatch

### ISSUE THREAD

**Issue by cykl** [micrometer-metrics/micrometer#303]
Unlike almost any other TSDB, CloudWatch suffer from a very severe limitation: it is not able to aggregate across dimension.

http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Dimension

> For metrics produced by certain AWS services, such as Amazon EC2, CloudWatch can aggregate data across dimensions. For example, search for metrics in the AWS/EC2 namespace but do not specify any dimensions, CloudWatch aggregates all data for the specified metric to create the statistic that you requested. **CloudWatch does not aggregate across dimensions for your custom metrics.** 

> CloudWatch treats each unique combination of dimensions as a separate metric, even if the metrics have the same metric name. **You can only retrieve statistics using combinations of dimensions that you specifically published.** When you retrieve statistics, specify the same values for the namespace, metric name, and dimension parameters that were used when the metrics were created. You can also specify the start and end times for CloudWatch to use for aggregation. 

This limitation leads to a serious impedance mismatch with micrometer:

  - To be able to get both service and instance level statistics you must publish two MetricDatum (the only difference being the drop of the instance dimension)
  - Most micrometer `MeterBinder`s define highly dimensional Meter that you won't be able to aggregate. CloudWatch also charges per active metrics (defined as "_a name, a namespace, and zero or more dimensions_"), leading to another trade-off between costs and level of details.

Another issue related to CloudWatch charging per `active metrics`, is that the current registry constantly push all registered meters even if they are not active. Servo used to stop pushing inactive metrics leading to substantial cost saving  (many counters tracking infrequent errors are mostly inactive) 
 
I had like to know your opinion about those issues and how people typically use the CloudWatch registry. 

---

I am migrating from Spectator + servo-aws and tried to recreate our current, unpleasant, setup:

 - Registry is configured to add `serviceId` & `instanceId` tags to all meters, meaning that we can get instance level stats but not service level stats.
 - To get service level stats, I duplicate meters and drop the `instanceId` dimension. I wrote [a prototype](https://gist.github.com/cykl/bd6463bb8f15fa486815547368c9c307) of a such approach.  Overriding `getMeters` is likely a not a good idea, but it was the easiest one.  
 - As CloudWatch is quite expensive, we decided to not duplicate every meters but only the ones that are while listed (ie. name prefixed by `"service."`). It work "fines" for user defined meters but also mean that I can't get service level stats from micrometer defined meters. Switching to a tag based approach might be more flexible.  
 - That's it.  I don't see how to overcome CloudWatch limitations. Highly dimensional metrics, like WebMvc, can be seen at instance level with the help of templated dashboards (Grafana). It's better than nothing but not what you want.

**Comment by jkschneider** [comment]
In 50e57ba1 I started working out an implementation for these concerns. It introduces a new aggregation concept to `CloudWatchMeterRegistry` that allows you to control how highly-dimensioned data is rolled up and whether to publish the detail as well:

Suppose you start with these metrics:

```
        registry.counter("http.requests", "method", "GET", "uri", "/api/foo", "host", "h1", "service", "myservice").increment();
        registry.counter("http.requests", "method", "GET", "uri", "/api/foo", "host", "h2", "service", "myservice").increment();
        registry.counter("http.requests", "method", "GET", "uri", "/api/bar", "host", "h3", "service", "myservice").increment();
        registry.counter("http.requests", "method", "POST", "uri", "/api/foo", "host", "h4", "service", "myservice").increment();
        registry.counter("my.counter", "host", "h1");
        registry.gauge("my.gauge", Tags.of("host", "h1"), registry, r -> r.getMeters().size());
```

Then:

```
CloudWatchMeterRegistry registry = ...
registry.aggregator(registry.find("http.requests").tagKeys("method"), true, "service");
```

Causes an aggregate to be published that rolls up the first 3 metrics, preserving the `method` tag (because it is common to all 3 meters matching the search terms), dropping uri and host because they is NOT the same on all 3 matching meters, and dropping service because you asked the rollup to drop that tag additionally. Because the second argument is `true`, all 3 detail metrics will still be published.

If you preferred that the detail metrics didn't ever contain "host", for example, then you could use `MeterFilter#ignoreTags` on the registry to ignore that tag generally.

Aggregates are always grouped up to but not including the name. So if a search term covers multiple names (e.g. `Search.search(registry).name(n -> n.startsWith("my.prefix"))` covers both a timer with `my.prefix.timer` and `my.prefix.counter`), then there will be an aggregate for each matching name.

**Comment by djgeary** [comment]
This unresolved issue https://github.com/blacklocus/metrics-cloudwatch/issues/10 I raised for the codahale/dropwizard metrics cloudwatch integration might be relevant here. It also has the idea of being able to configure how metrics are aggregated and sent to cloudwatch. 
The most flexible solution would be able to configure all permutations of the dimensions and specify which are actually sent to cloudwatch - so you have a range of options between the following:
1) Just send some aggregates ie drop some dimensions (reduces costs)
2) Send as is (highly dimensional but can't see aggregates in cloudwatch)
3) Send aggregates for different metric combination permutations AND detail as is - this could be costly but allows the creation of new 'metrics' in cloudwatch that effectively give the detail and aggregates cloudwatch doesn't give by itself. 

I think what is being proposed here covers all these scenarios?

**Comment by jkschneider** [comment]
> I think what is being proposed here covers all these scenarios?

@djgeary It does. The boundaries are still a little murky, but some combination of `MeterFilter#ignoreTags` for (1), the new aggregates concept for (2) and (3), and whitelisting with `MeterFilter#denyUnless` should handle all of it.

**Comment by jkschneider** [comment]
Too much to test for 1.0.0 going out today, but we'll follow with a minor release with this feature sometime in the near future.

**Comment by dibog** [comment]
I tried to use/eval micrometer-metrics for cloudwatch but couldn't find any documentation how to do that. Could you give me a pointer where I see how to use them in one simple standalone demo class?

**Comment by cykl** [comment]
Thanks @jkschneider. The API you described seems to cover my needs. I hope to give it a shoot by next week.

**Comment by nwoike** [comment]
@jkschneider Did the CloudWatch aggregate registry solution get scrapped or was there an alternative solution? I did find that Spring Boot Actuator now has a `WebMvcTagsProvider` that allows you to custom the `http.server.request` tags sent helping to reduce the dimensionality.

**Comment by tom-mi** [comment]
Are there any updates on this issue?
In my case I need the Cloudwatch metric for (Kafka Consumer) autoscaling, and that requires it to have a cardinality of 1. My hack is to drop all dimensions in a facade for the CloudWatch client, however that is not a perfect solution as the data is just not aggregated. Instead, CloudWatch receives multiple datapoints at the same timestamp. This does not allow to aggregate across dimensions in a proper way - it somehow does the job, but is quite fragile.
Another attempt to use a `MeterFilter` to drop the extra dimensions with `replaceTags` failed as well, as this seems to lead to data loss.

**Comment by marcingrzejszczak** [comment]
Can you elaborate on "Another attempt to use a MeterFilter to drop the extra dimensions with replaceTags failed as well, as this seems to lead to data loss." and explain in more details why it didn't work?

**Comment by tom-mi** [comment]
Uh-oh, this has been more than one year ago. IIRC using replaceTags to drop some tags caused issues, as afterwards multiple data points with the same tag combinations were present, and no (proper?) aggregation is done. I'm not 100% sure about this however, and unfortunately I did not find any more details on my experiments back then.
(We have changed our setup to generate custom aggregated kafka metrics via the endpoint registry instead of using the ones provided by micrometer to work around this issue)

**Comment by marcingrzejszczak** [comment]
Is there a chance for a reproducer? Because without it it's hard to do sth about this issue.

**Comment by izeye** [comment]
For your information, the [`cloudwatch-improvements`](https://github.com/micrometer-metrics/micrometer/tree/cloudwatch-improvements) branch seems to have been created for this [here](https://github.com/micrometer-metrics/micrometer/issues/303#issuecomment-366889634).
