### ISSUE TITLE
How disable RestTemplate monitoring

### ISSUE THREAD

**Issue by chendy560** [micrometer-metrics/micrometer#304]
There are many such codes in my system:
```java
    public void doSomething(String id) {
        URI uri = UriComponentsBuilder.fromHttpUrl("http://...").queryParam("id", id).build().encode().toUri();
        RequestEntity<Void> request = RequestEntity.get(uri).build();
        restTemplate.exchange(request, SomeThing.class);
        //...
    }
```
Each different id will bring a different URI, as well as a new tag. It will take up a lot of memory, so how disable it?

**Comment by spencergibb** [comment]
Why don't you use the rest template it URI templates?

**Comment by chendy560** [comment]
@spencergibb 
Sorry, I did not know it before😂
It works, thanks

**Comment by dougbacelar** [comment]
@spencergibb Code I am working on cannot be easily refactored. Is there a way to turn off metric gathering for a particular `RestTemplate` bean?

I am using the code below to customize the `RestTemplate`
``` java        
new MetricsRestTemplateCustomizer( meterRegistry, ( urlTemplate, request, response ) ->
  Arrays.asList(
      RestTemplateExchangeTags.method(request),
      RestTemplateExchangeTags.status(response),
      RestTemplateExchangeTags.clientName(request)
  ), 
  "myTestMetric"
)
.customize( restTemplate );
```
This creates a metric called `myTestMetric` and it does not record the URI, just like I wanted. However the automatically generated `http_client_requests_seconds_*` are still being recorded.

Each request would generate a new metric as the url is very complex.

**Comment by chandreshlko** [comment]
> I fixed my problem creating the following `@Bean`:
> 
> ```java
>     @Bean
>     RestTemplateExchangeTagsProvider restTemplateExchangeTagsProvider() {
> 
>         new RestTemplateExchangeTagsProvider() {
>             @Override
>             Iterable<Tag> getTags( String urlTemplate, HttpRequest request, ClientHttpResponse response ) {
> 
>                 Tag uriTag
> 
>                 if ( StringUtils.hasText( urlTemplate ) ) {
>                     uriTag = RestTemplateExchangeTags.uri( urlTemplate )
>                 } else if ( request.URI.path.startsWith( '/faulty-endpoint' ) ) {
>                     uriTag = RestTemplateExchangeTags.uri( request.URI.path )
>                 } else {
>                     uriTag = RestTemplateExchangeTags.uri( request )
>                 }
> 
>                 [ RestTemplateExchangeTags.method( request ),
>                   uriTag,
>                   RestTemplateExchangeTags.status( response ),
>                   RestTemplateExchangeTags.clientName( request ) ]
>             }
>         }
>     }
> ```
> 
> If the `URI.path` starts with `/faulty-endpoint`, it will tag the `URI.path` instead of the full `URI` with all parameters.
> 
> The above is simply a slightly modified version of the `DefaultRestTemplateExchangeTagsProvider`

I am calling a third party API for lagging the metrics 
the URI is like "/api/xxx/123" the last 3 digits are changes 
my requirement is to count the trigger for "/api/xxx" for this metrics 
I have other api call that i don't want to change I am using spring boot (RestTemplate) and the configuration is global
any suggestion how can i do  this.

**Comment by shakuzen** [comment]
@chandreshlko I'm not understanding exactly what you're trying to accomplish. It will probably be easier to figure this out through chat. Feel free to join us on Slack at https://slack.micrometer.io.

**Comment by faramarzaf** [comment]
@chandreshlko and @shakuzen I have the same problem, I am invoking rest API that has a path variable like this -> /api/{id}
but I don't want to log /{id} part because of the high request rate which leads to using more space. Is there any solution to exclude the specific path? I mean something like bulk metric for Rest controllers?

**Comment by bclozel** [comment]
@faramarzaf can you ask this question on StackOverflow? Please add to your question the relevant information like: which spring boot version you are using, how are you creating and using the rest template instance, show which metrics are collected.
