### ISSUE TITLE
How to add custom tags for all metrics?

### ISSUE THREAD

**Issue by kesavkolla** [micrometer-metrics/micrometer#3044]
I use AWS cloudwatch for collecting all my application metrics. Currently there is only one configuration which is namespace. I am running my application in autoscaling group and I would like to add dimensions like EC2 instance id, aws region etc... Is it possible to add some tags to all the metrics?

**Comment by jonatan-ivanov** [comment]
Yes, please see the docs: https://micrometer.io/docs/concepts#_common_tags
Also, these type of questions are better suited for StackOverflow/
