### ISSUE TITLE
Deadlock issue in TimeWindowLatencyHistogram

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#307]
As reported by @imasahiro.

https://gist.github.com/imasahiro/2e7f119d670bb957dde8dbd916cd352d

**Comment by jkschneider** [comment]
`PauseDetectorThread` can sit in an infinite loop at:

TimeCappedMovingAverageIntervalEstimator.determineNumberOfWindowPositionsOutsideOfTimeCap(TimeCappedMovingAverageIntervalEstimator.java:266

**Comment by jkschneider** [comment]
Doesn't appear that an infinite loop is possible in `TimeCappedMovingAverageIntervalEstimator`.

**Comment by jkschneider** [comment]
For rc6, we're going to put in a config that allows you to swap out a NOOP implementation until the underlying issue can be identified:

```
registry.config().pauseDetector(new NoPauseDetector());
```

The same mechanism allows us to control CPU consumption on a clock-drift based detector (CPU consumption is inversely proportional to the duration in the first argument:

```
registry.config().pauseDetector(new ClockDriftPauseDetector(Duration.ofMillis(100), Duration.ofMillis(100)));
```

**Comment by kaliatech** [comment]
Fwiw, I'm seeing constant CPU usage in the SimplePauseDetector threads, but _seemingly_ only when running on Linux/EC2. Not yet sure why.  CPU usage starts on first HTTP request (when timer gets created). Happens consistently 100% of the time. Would like to provide more info, but not yet sure how to debug further.  It's only noticeable by connecting remotely via visualvm and sampling. Looking forward to rc.6 release so I configure the noop pause detector.

**Comment by imasahiro** [comment]
FWIW, I just found that, it has many queued PauseNotification at `SimplePauseDetector#message` during deadlock (85,731 entries at this case). And each `PauseNotification` has weird pauseEndTimeNsec (`15142069549920191` == `1970-06-25T06:07:49.549Z`)

<img width="939" alt="2018-01-05 15 00 12" src="https://user-images.githubusercontent.com/73532/34597300-358c3a68-f229-11e7-8c79-f78f0ecd2c40.png">


Here is my env.
* CPU: Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
* OS: CentOS Linux 7.3.1611
* JDK: 1.8.0_121
```
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by jkschneider** [comment]
Looks like deadlock is possible in the base class in `MovingAverageIntervalEstimator#recordIntervalAndReturnWindowPosition`, as noted in the comment in that implementation.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2018. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
