### ISSUE TITLE
Timed annotation missing metric entries - Successful & Faulty request order

### ISSUE THREAD

**Issue by lschaertel** [micrometer-metrics/micrometer#3083]
**Describe the bug**
When using the `@Timed` annotation on any method inside of an `@RestController` there are inconsistencies/problems when processing successful and faulty timer metrics with the same metric value/name.

If the first generation of the metric entry is a successful request then any consecutive faulty call (Like a 404/422/...) will not generate another entry with the tags for an invalid, faulty request:
Successful call:
`custom_timed_value_test_seconds_count{class="com.package.test",exception="none",method="customTimedValueTest",} 1.0`
Faulty call:
- Will not generate any other entry

The other way around where an faulty request gets sent first, and then a successful one:
Faulty call:
`custom_timed_value_test_seconds_count{exception="MethodArgumentNotValidException",method="POST",outcome="CLIENT_ERROR",status="400",uri="/api/v2/test/custom/metric",} 1.0
`

Successful call will now generate an additional entry:
`custom_timed_value_test_seconds_count{exception="None",method="POST",outcome="SUCCESS",status="200",uri="/api/v2/test/custom/metric",} 1.0`

**Environment**
Java version: `openjdk-17.0.2`
Currently used dependency version: `io.micrometer:micrometer-core:1.8.3`
Used SpringBoot version: `org.springframework.boot:spring-boot:2.6.4`
OS: macOS and also same behaviour when deployed onKubernetes

**To Reproduce**
How to reproduce the bug:
Configuration class for Counted & Timed aspect:
```
@Configuration
public class MetricConfig {
    @Bean
    CountedAspect countedAspect(MeterRegistry registry) {
        return new CountedAspect(registry);
    }
    @Bean
    TimedAspect timedAspect(MeterRegistry registry) {
        return new TimedAspect(registry);
    }
}

```

Simple endpoint inside of an rest controller (Mandatory header to cause exceptions):
```
@Timed(value = "custom_timed_value_test")
@PostMapping(value = "/test/custom/metric", produces = MediaType.APPLICATION_JSON_VALUE)
public void customTimedValueTest(@RequestHeader("header") final String header) {
}

```

**Expected behavior**
To me, the expected behaviour should be, that no matter which order the entries are generated, the result should be the same and there should always be multiple entries - One for the successful calls & one for the invalid, faulty ones.

**Comment by shakuzen** [comment]
If you want to customize the Timer name of a specific controller endpoint, you should not be using the `TimedAspect`. Spring Boot has support for customizing controller timers without that. See the [Spring Boot documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.supported.timed-annotation). If you try using both the `TimedAspect` and Spring Boot's support, those methods get instrumented twice with the same name, so which will end up in Prometheus is a race condition. I suspect this is the root cause of the issue. Could you try without the aspects and see if the behavior is how you expect? We can look into this more if it's still an issue then.

**Comment by lschaertel** [comment]
Ok that actually fixed my issue thanks alot for the fast answer!

I'm also using custom metrics which I use without the annotation and I had issues with non-existing `CountedAspect` & `TimedAspect` beans when trying to increment any counter. But I just removed them again and Im not having this issue anymore.
