### ISSUE TITLE
MeterFilter.accept is ignored 

### ISSUE THREAD

**Issue by kle-pra** [micrometer-metrics/micrometer#3110]
Redirected from: https://github.com/spring-projects/spring-boot/issues/30496#event-6351044367

-  Spring Boot: `2.6.5` with `spring-boot-starter-actuator`
- ` micrometer-registry-prometheus`: `1.8.4` for exposing prometheus metrics

I think there is a bug with  `MeterFilter.accept.`

The following config ouputs all the metrics even though `MeterFilter.accept `is returning false (hardcoded).

```Java
   @Configuration
public class MetricConfiguration {

    private static final String IGNORED_TAGS[] = {"main-application-class"};


  @Bean
    MeterRegistryCustomizer<MeterRegistry> metricsCommonTags() {
        return registry -> registry.config()
           //   .meterFilter(ignoreTags(IGNORED_TAGS))
                .meterFilter(accept(t -> false));
    }
}
```
Meanwhile, ignoreTags, if commented in, is working fine (the config is working).

Bug seems to also be present in older versions (tried `1.7.5` and `1.5.4`)

**Comment by jonatan-ivanov** [comment]
Not `ACCEPT`ing something means being `NEUTRAL` about it.
Try denying it, please see the docs: https://micrometer.io/docs/concepts#_deny_or_accept_meters

Here's an example:
```java
public class FilterDemo {
    public static void main(String[] args) {
        PrometheusMeterRegistry registry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
//        registry.config().meterFilter(MeterFilter.accept(id -> false)); // this means being NEUTRAL
        registry.config().meterFilter(MeterFilter.deny(id -> true)); // this means DENY

        Counter.builder("test.counter")
                .register(registry)
                .increment();

        System.out.println(registry.scrape());
    }
}
```

If you still have an issue with this, could you please write a test case in `MeterFilterTest`.
If you think we should update the docs, could you please propose a change?

**Comment by kle-pra** [comment]
Thank you, I missed that `NEUTRAL` state behavior. 

It makes sense now, deny works as expected.
