### ISSUE TITLE
Support EMF LoggingMeterRegistry

### ISSUE THREAD

**Issue by chenqi0805** [micrometer-metrics/micrometer#3112]
**Please describe the feature request.**
We need a metric log output file that uses [Embedded Metrics Format](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html), e.g.

```
{
  "_aws": {
    "Timestamp": 1574109732004,
    "CloudWatchMetrics": [
      {
        "Dimensions": [["..."]],
         ...
      }
    ] 
  },
  "ClientId": "012345678910",
  ...
}
```

**Rationale**
Please help us understand the rationale (why) behind the enhancement request.

**Additional context**
Add any other context about the feature request here, e.g. related issues, prior art.

**Comment by jonatan-ivanov** [comment]
Micrometer supports CloudWatch, you don't need to log your metrics out in EMF if you just want to use CloudWatch. Would the CloudWatchMeterRegistry work for you?

**Comment by chenqi0805** [comment]
> Micrometer supports CloudWatch, you don't need to log your metrics out in EMF if you just want to use CloudWatch. Would the CloudWatchMeterRegistry work for you?

@jonatan-ivanov Thanks for the quick feedback! In our use case, stream processing is needed including filtering, update, transformation, and aggregation on the metrics before publishing to CloudWatch while CloudWatchMeterRegistry directly uses the cloudwatch client to publish data. Follow up questions:

1. How much efforts (estimation of days) it will take to build such an EMF logging meter?
2. As an alternative, is there any logging meter registry that output metrics to logs in a particular format?

**Comment by checketts** [comment]
@chenqi0805 I'm not aware of anyone actively working on an AWS EMF implementation. So there is no estimate available. Unless you were asking how hard it would be for you to contribute, the effort to extend an existing `SimpleMeterRegistry` probably wouldn't be too much.

As an alternative, instead of enhancing the existing logging registry, you could extend the `LoggingMeterRegistry` or `StepMeterRegistry` and hook into the `publish` method to write out any EMF specific data.

Sorry I can be more helpful.

**Comment by chenqi0805** [comment]
@checketts Thanks for the response!

>As an alternative, instead of enhancing the existing logging registry, you could extend the LoggingMeterRegistry or StepMeterRegistry and hook into the publish method to write out any EMF specific data.

This seems to be the right strategy for our usecase. I did a little diving, looks like we just need to override this part

https://github.com/micrometer-metrics/micrometer/blob/2a78239f99fc1a308def9817b422a92a3ff129c7/micrometer-core/src/main/java/io/micrometer/core/instrument/logging/LoggingMeterRegistry.java#L97-L143

with the usage of AWS EMF library: https://github.com/awslabs/aws-embedded-metrics-java which is being used in CloudWatchMeterRegistry. Since at this point EMFLoggingMeterRegistry is only valuable to our use case, I will not make contribution to the micrometer repo. But please feel free to let me know once it becomes valuable to others.

Also, is there any place we could use for questions during development on extending meter registry?

**Comment by jonatan-ivanov** [comment]
You can find us on SO and https://slack.micrometer.io/

**Comment by chenqi0805** [comment]
@jonatan-ivanov Thanks. I am OK to leave it up to you to open or close the issue. Just want to let you know that we will not directly contribute to the repo with EMFLoggingMeterRegistry for short term.

**Comment by juliocvergarah** [comment]
@chenqi0805 I need a Micrometer Compatible EMF Logger, do you have your implementation in a branch I could see ? Thanks.

**Comment by juliocvergarah** [comment]
I created an EMFCloudWatchMeter Registry based on the CloudWatchMeterRegistry. where I use the metricsLogger and a simple conversion from MetricsDatum in the Cloudwatch model to what the MetricsLogger requires. Why ? Cause the CloudWatchMeterRegistry already bridged all the conversions from Micrometer Meters to MetricDatum, which is really close to what the MetricsLogger requires. You just need to override the publish and the the sendMetricsData methods.
