### ISSUE TITLE
Retrofit method aware metrics.

### ISSUE THREAD

**Issue by kazuki-ma** [micrometer-metrics/micrometer#3113]
**Please describe the feature request.**

Support retrofit, widely used http RPC framework, metrics.

Basically, retrofit stands on OkHttp but OkHttpMetrics only measure host global metrics.

Retrofit aware metrics exporter can export metrics for each API path ignoring path parameter variation.

**Rationale**

Many cases, there are many types of APIs between caller and callee.

For example: `GET /api/v1/books` and `GET /api/v1/book/{book_id}`.

[OkHttpMetrics exporter](https://github.com/micrometer-metrics/micrometer/tree/2a78239f99fc1a308def9817b422a92a3ff129c7/micrometer-binders/src/main/java/io/micrometer/binder/okhttp3) CAN'T split those request in nature.

But retrofit aware exporter CAN measure metrics by each interface / path patterns.

**Additional context**
* Related: [OkHttpMetrics exporter](https://github.com/micrometer-metrics/micrometer/tree/2a78239f99fc1a308def9817b422a92a3ff129c7/micrometer-binders/src/main/java/io/micrometer/binder/okhttp3)

**Comment by kazuki-ma** [comment]
Planned Implementation Policies:

I'm not sure extending [OkHttpMetrics](https://github.com/micrometer-metrics/micrometer/tree/2a78239f99fc1a308def9817b422a92a3ff129c7/micrometer-binders/src/main/java/io/micrometer/binder/okhttp3) to measure Retrofit's metrics if it exist on class path.

Current plan is create completely new exporter like `RetrofitEventMetricsListener` etc.

**Comment by shakuzen** [comment]
It seems some users of Retrofit configure a `uriMapper` on the `OkHttpMetricsEventListener` that captures the templated path - see https://github.com/micrometer-metrics/micrometer/issues/771#issuecomment-456528336. This can be used already. Perhaps we could have a `uriMapper` implementation that does this more directly, that Retrofit users could configure. What do you think?

**Comment by marcingrzejszczak** [comment]
We have an example of that here https://github.com/micrometer-metrics/micrometer/blob/v1.12.1/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/okhttp3/RetrofitOkHttpObservationInterceptorTest.java and its base class
