### ISSUE TITLE
[bug] timer.max is less then 0.999 percentile

### ISSUE THREAD

**Issue by jiming** [micrometer-metrics/micrometer#312]
Hi,

I export the metrics, but notice that max is less than 0.999 percentile. Is it a bug or I made a mistake? Thanks!

```
sb.append(m.getId().getName()).append("_count{").append(tagSb).append("} ").append(m.count()).append('\n');
sb.append(m.getId().getName()).append("_totalTime{").append(tagSb).append("} ").append(m.totalTime(TimeUnit.MILLISECONDS)).append('\n');
sb.append(m.getId().getName()).append("_max{").append(tagSb).append("} ").append(m.max(TimeUnit.MILLISECONDS)).append('\n');
sb.append(m.getId().getName()).append("_999{").append(tagSb).append("} ").append(m.percentile(0.999, TimeUnit.MILLISECONDS)).append('\n');
sb.append(m.getId().getName()).append("_990{").append(tagSb).append("} ").append(m.percentile(0.990, TimeUnit.MILLISECONDS)).append('\n');
sb.append(m.getId().getName()).append("_950{").append(tagSb).append("} ").append(m.percentile(0.950, TimeUnit.MILLISECONDS)).append('\n');
sb.append(m.getId().getName()).append("_800{").append(tagSb).append("} ").append(m.percentile(0.800, TimeUnit.MILLISECONDS)).append('\n');
sb.append(m.getId().getName()).append("_500{").append(tagSb).append("} ").append(m.percentile(0.500, TimeUnit.MILLISECONDS)).append('\n');

```

The output is 

```
http_client_timer_count{host="miao.dangdang.com",} 29
http_client_timer_totalTime{host="miao.dangdang.com",} 42630.897426
http_client_timer_max{host="miao.dangdang.com",} 3810.931167
http_client_timer_999{host="miao.dangdang.com",} 3825.205247
http_client_timer_990{host="miao.dangdang.com",} 3825.205247
http_client_timer_950{host="miao.dangdang.com",} 3774.873599
http_client_timer_800{host="miao.dangdang.com",} 2785.017855
http_client_timer_500{host="miao.dangdang.com",} 1333.788671
```

**Comment by checketts** [comment]
The max is windowed (and configurable). As in it is the max seen in the last minute. The Percentile is an overall Percentile. 

This keeps the max useful even when the app has been tracking metrics for a long time

**Comment by checketts** [comment]
We should document this fact better

**Comment by jkschneider** [comment]
> We should document this fact better
Perhaps. I think it's largely going to be a moot point when we move to a ring buffer approach for max rather than a `StepDouble`. It will no longer be possible for it to be less than a high percentile.

**Comment by jkschneider** [comment]
After #317, it is still possible for a server-side percentile _approximation_ based on something like `histogram_quantile` to exceed the max in a given interval. This is for a couple reasons:

1. Since `histogram_quantile` et al are approximations, they of course have a non-zero error bound.
2. For some systems, like Prometheus, the approximation is based off a rate normalization that is decided at query time, which may be different than the ring-buffer expiry the app has chosen for rolling max computation in the app.

Example:

![image](https://user-images.githubusercontent.com/1697736/34329266-af482c96-e8be-11e7-9d65-29fa6797b52f.png)

Yellow is the approximation. Note the **true** P99 (in this case determined client-side) is always below max.

**Comment by jiming** [comment]
@jkschneider ,

Document it makes sense.

What about do a little trick? which is not accurate, but better than the case the max is less than 

```
max() {
    return Math.max(max(), percentile(0.99999, TimeUnit.MILLISECONDS);
}
```

Thanks!

**Comment by jiming** [comment]
BTW, can you please supply a windowed Percentile? Doesn't it useful too?

**Comment by jkschneider** [comment]
> What about do a little trick?

I guess I'm not explaining this well. Percentiles pre-aggregated by Micrometer in the application will always be less than or equal to the max, but percentile approximations generated by the monitoring system's query language may not. 

I really don't think you should concern yourself with this. We know that such approximations have a non-zero error bound. Recognizing that a high percentile approximation may drift above the true max is a natural consequence of this. Trying to force that not be the case is like refusing to acknowledge the reality of the data.

> can you please supply a windowed Percentile and make the window size customizable? 

The client-side percentile already is windowed in a ring buffer, governed by `histogramExpiry` and `histogramBufferLength` options on a `Timer`.

**Comment by jiming** [comment]
Thanks a lot!
