### ISSUE TITLE
system_cpu_usage is Nan when compiled in native

### ISSUE THREAD

**Issue by benoit-messager** [micrometer-metrics/micrometer#3121]
**Describe the bug**
When executing an application in native mode system_cpu_usage is Nan.

**Environment**

 - Micrometer version [1.8.4]
 - Quarkus version [2.7.5.Final]
 - Micrometer registry [prometheus]
 - Graalvm version [graalvm-ce-java11-22.0.0.2 / graalvm-ce-java17-22.0.0.2]
 - OS: [Docker image based on quarkus-micro-image:1.0]
 - Java version: [N.A. in native mode]

**To Reproduce**
How to reproduce the bug:
Generate a sample app with quarkus https://code.quarkus.io/ compile it to native and add micrometer ( https://quarkus.io/guides/micrometer)

**Expected behavior**
system_cpu_usage the current cpu usage value.

**Additional context**
Here's the original SO post with a suggestion from "ebullient"

**Comment by benoit-messager** [comment]
Oups, forgot the SO link : https://stackoverflow.com/questions/71830135/system-cpu-usage-is-nan-when-compiled-in-native

**Comment by shakuzen** [comment]
This used to work back when I added the reflection config for ProcessorMetrics, but it has broke at some point due a change in GraalVM. It looks to be fixed again in GraalVM 22.2 with https://github.com/oracle/graal/pull/4383 - I tried a 22.2 dev build and it is working without issue again. I'm not sure there is anything we can do in Micrometer to work around this. If someone has an idea, please share and we can consider it. For now, I'm closing as an external issue.
