### ISSUE TITLE
Histogram with values that are 0. 

### ISSUE THREAD

**Issue by mohnishkodnani** [micrometer-metrics/micrometer#3138]
**Please describe the feature request.**
We have a current integration with Prometheus Java Client, where we have a lot of histograms for our website. The website measures how many things were shown to the user and we are interested in how many 0 results were shown. In the current implementation, we can get this for free where we could look at le="0.0" bucket and get exactly the number of times exactly 0 things were shown. 
I would like to know if there is a way to get the same using micrometer. If I put the SLO has 1, then it will include both 0 and 1 things shown. 
I want to avoid creating a specific metrics for this case where currently the histogram gives this for free. 

**Rationale**
Please help us understand the rationale (why) behind the enhancement request.

**Additional context**
Add any other context about the feature request here, e.g. related issues, prior art.

**Comment by marcingrzejszczak** [comment]
Thank you for filing the issue. Is there a chance for you to write a failing test for this? Or a reproducer?
