### ISSUE TITLE
Move Timer max to a ring buffer implementation

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#317]
Currently `Timer#max` is step-based, so it reports the max from the last step interval. Many users are confused by how max is 0 for the first step (#284), and can appear less than a high percentile in a given interval (#312).

We should reimplement max as a decaying value (a fixed ring buffer) so that it:

1. Is always reported greater than a high percentile in a given interval.
2. Is non-zero on the first publishing interval if any sample has been observed.

**Comment by jkschneider** [comment]
Boot 2 changes:

* JMX now has a configuration interface.

**Comment by checketts** [comment]
Will this mean that `max` is no longer configurable for a given duration? 

I like the idea of reasoning that it would be the `max seen in the last 15 minutes` but that would conflict with point 1 above, since the high percentile would likely be longer than the relatively short `max`'s window.

**Comment by jkschneider** [comment]
> Will this mean that max is no longer configurable for a given duration?

My plan is to reuse two configuration options of a `Timer`, `histogramExpiry` and `histogramBufferLength`, to configure the max ring buffer as well. That ensures that client-side percentiles and max are aligned.

The slight difference here is that a sample will coexist in all the individual `AtomicLong`s in the ring buffer. So `max seen in the last 15 minutes` can be arrived at by selecting an expiry of 5 minutes and a buffer length of 3, an expiry of 3 minutes and a buffer length of 5, etc. This is precisely what we do for high percentile calculation as well (at least client side).

Also, the server-side percentile approximations in Atlas (and perhaps Wavefront depending on how the implementation settles?) will also be aligned with max since the histogram buckets on which they are based are non-cumulative over all time, but are governed by expiry and buffer length. But as I've mentioned in #312, this doesn't make much difference.
