### ISSUE TITLE
how to update micrometer dynatrace debug logging for non spring boot apps

### ISSUE THREAD

**Issue by Krithikavv** [micrometer-metrics/micrometer#3189]
need help to understand how I can add the debug logging for micrometer dynatrace. 

my applications are running with a specific sap format app files which are html files. its a form of sap ariba web app. 
http://www.aribaweb.org/Documentation/1_AribaWeb/AribaWeb.htm

working on integrating this with micrometer and dynatrace so wanted to check iwth debug logging whether it can print more info on what's exported details from such non spring boot apps. 
please advise

**Comment by shakuzen** [comment]
How to configure logging levels depends on the logging system you use - e.g. [logback](https://logback.qos.ch/manual/configuration.html), [log4j](https://logging.apache.org/log4j/2.x/manual/configuration.html). You will need to consult their documentation to see how to configure the log level. There's nothing specialized in Micrometer.

I'm not familiar with Ariba Web apps, and I don't know if they force a certain logging system. You'll need to check what logging system your application is using. Your question is not really specific to Micrometer, so I can't help much on specific steps to take. I can tell you we do log details of metrics published using the dynatrace registry at debug level. So as long as debug level logging is enabled, you should have that.

I hope that helps. Let us know if there's anything we can do to help from the Micrometer perspective.
