### ISSUE TITLE
Suspected memory leak

### ISSUE THREAD

**Issue by shiyanhui** [micrometer-metrics/micrometer#3191]
**Describe the bug**

Hi, recently we observed that our service would make major gc collection frequently after running for days. And we found that it may be related to memory leak of micrometer.

Here are three screenshots, the first is the datadog JVM heap runtime metrics, the second is the datadog thrown profiling, and the third is the heap histogram with command `jmap -histo:live`.

<img width="1727" alt="Screen Shot 2022-05-21 at 09 59 20" src="https://user-images.githubusercontent.com/7406269/169630164-bfbf5ca2-ba9e-4b14-a171-3423ba0d008b.png">

<img width="1117" alt="Screen Shot 2022-05-21 at 09 44 06" src="https://user-images.githubusercontent.com/7406269/169630177-6f3ff3fc-bf99-4967-b2a1-050b4604a14e.png">

<img width="1237" alt="Screen Shot 2022-05-21 at 09 27 27" src="https://user-images.githubusercontent.com/7406269/169630185-79466676-29d4-40c1-9b6a-9d66635c1bec.png">

All the thrown exceptions shown in the second screenshot point to [ResourceLeakDetector](https://github.com/netty/netty/blob/netty-4.1.65.Final/common/src/main/java/io/netty/util/ResourceLeakDetector.java#L616). We traced the code and suspected that some buffer objects it requested here [NettyOutbound.java](https://github.com/reactor/reactor-netty/blob/v0.9.20.RELEASE/src/main/java/reactor/netty/NettyOutbound.java#L307) may not be released. 

We are using an old version micrometer `1.5.14`, so is it known issue and fixed in later versions? If not, can you please help to give some advice? Thanks.

**Environment**

 - Micrometer version: 1.5.14
 - Micrometer registry: datadog
 - OS:  Ubuntu 18.04.1
 - Java version: openjdk version "11.0.15"

**To Reproduce**

The Old Gen Size grows slowly, so it will take days to reproduce this on our k8s. We didn't built a minimum app to reproduce it locally.

**Expected behavior**

Make sure that there are no memory leak for micrometer.

**Comment by checketts** [comment]
This sort of behavior is typically due to 'tag cardinality explosion'. See #3038

**Comment by shiyanhui** [comment]
Yeah, we do have metrics with multiple tags. Seems we likely find the root cause. Will fix it and see whether back to normal. Thanks!

**Comment by shiyanhui** [comment]
Another question is, it seems that only when we use Spring WebFlux this problem will appear. Not if we use Spring MVC. So is there any way to make micrometer not use `reactor` and `reactor-netty` ?

**Comment by jonatan-ivanov** [comment]
As @checketts mentioned above, this is probably caused by using high cardinality tags, the jmap output seems to agree with this, see the Tag and Meter.Id (Tag is part of the Id) on the output.
Using multiple tags is not an issue, using a tag that has high cardinality, is.

>Seems we likely find the root cause.

Can I ask what was it?

>it seems that only when we use Spring WebFlux this problem will appear. Not if we use Spring MVC.

This is pretty weird, are you sure you don't attack high cardinality tags in one case and not in the other?

>So is there any way to make micrometer not use reactor nor reactor-netty ?

I'm not sure I understand how would this help. Micrometer only using them for its StatsD registry and they are shadowed so _theoretically_ you should not notice it. Can you try using DataDog through the `DatadogMeterRegistry`? That one does not use reactor or reactor-netty.

**Comment by shakuzen** [comment]
> We are using an old version micrometer `1.5.14`, so is it known issue and fixed in later versions?

I can't think of a specific issue, but there have been various changes in the statsd module since that version, so trying with the latest version available to see if the issue remains is a good troubleshooting step.

**Comment by shiyanhui** [comment]
Problem solved, just want to sync the result here. It's caused by `high cardinality tags` in reactor netty. So this issue can be closed now, thanks!

**Comment by jonatan-ivanov** [comment]
@shiyanhui Were those tags attached by you or by rector/reactor-netty/netty?

**Comment by afosorio** [comment]
@jonatan-ivanov  Apparently only reactor-netty adds them, but I don't know how he solved it

**Comment by jonatan-ivanov** [comment]
Me neither, but I would report that issue to reactor-netty. Also, you can always, remove/modify add tags using a `MeterFilter`/`ObservationFilter`.

**Comment by afosorio** [comment]
@jonatan-ivanov Is it netty that generates high cardinality? Would deleting the library in the pom be enough?

**Comment by afosorio** [comment]
![image](https://github.com/user-attachments/assets/98fbda14-9f96-48bb-8b19-78626924b270)

@jonatan-ivanov I removed these tags but still, the memory consumption is very high

**Comment by jonatan-ivanov** [comment]
I think Netty is not instrumented (so it can't produce any high cardinality data) and you also said it's reactor-netty that does. :) Did you check it or just read [this comment](https://github.com/micrometer-metrics/micrometer/issues/3191#issuecomment-1140391436)? If it produces data, it means it is used so if you remove it from your dependencies your app might be broken but I don't know how reactor-netty is used in your app.

I'm not sure what you expect from the config changes you made above. They are not tags and have nothing to do with netty or reactor netty. I would report the issue to reactor-netty and in the meantime use a `MeterFilter`/`ObservationFilter` as I suggested above.
