### ISSUE TITLE
Support interval counters

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#32]
A counter that also keeps track of the time since last update (in the form of a gauge).

**Comment by checketts** [comment]
Would this be like:

`uptime 1000.0`

If the service has been up for 1000 seconds?

I seem to recall Prometheus preferring unix epoc style as in

`process_start_time` (https://github.com/prometheus/client_java/blob/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java#L80)

**Comment by jkschneider** [comment]
This is just a counter with an additional gauge that represents the time since the last counter increment. So if you had some sort of cancellable scheduled process, for example, and you wanted to alert if this process didn't complete at least once a day.

**Comment by jkschneider** [comment]
It may make sense to create an `IntervalTimer` as well to measure gaps between events.

**Comment by kevcodez** [comment]
I recently opened a [Stackoverflow Thread](https://stackoverflow.com/questions/49887716/spring-boot-2-metrics-last-invocation-of-timed-scheduled-job) and was linked here to share my use case.

I'd like to track scheduled jobs in my spring boot application.

There are multiple use-cases:

* See the timestamp of the latest invocation of a specific scheduled job
* See invocation timestamps of scheduled jobs historically
* See how long a scheduled job took

This could be combined to something like

```json
[
{"jobname": {
"invocations": [
{"took": 1, "start": "2018-08-17T18:00:00.001Z", "end": "2018-08-17T18:00:00.002Z"}
]
}
}]
```

I actually expected that behaviour when using `@Timed` on a `@Scheduled` method.

**Comment by checketts** [comment]
@kevcodez How would this be exported to different monitoring backends? I think it could only be consumed by a person (or a tracing backend)

Application observability falls into 3 categories: logging, tracing, and metrics. Micrometer is really focused around metrics.

I'm not trying to shutdown your request but metrics focuses on aggregation and scalability. What you are describing aligns quite well with tracing. Have you looked into using Zipkin? (We've done some dabbling to create timers that offered tracing at the same time, but that doesn't exist yet see #207 )

**Comment by marcingrzejszczak** [comment]
There was no issues on this topic since 2018. We have tracing, metrics and exemplars that can achieve similar goals. Let's close this issue for now and if there's any interest in this, please add your comment and we'll consider re-opening it.
