### ISSUE TITLE
Call register multi-times with the same name/tags

### ISSUE THREAD

**Issue by guy1699** [micrometer-metrics/micrometer#3203]
I'm trying to understand the concept, do I need to register the Timer (let's say) only once, and then call 
`timer.record(duration);`
for each process I measure?

I wonder because some tags can be given only on run time and so it will be impossible to register the timer with tags in the first place.
So is there anything bad with registering in each process?

```
public void time(TimerType timerType, Iterable<Tag> tags, Duration duration) {
    try {
      Timer timer = meterRegistry.timer("metricName", tags);
      timer.record(duration);
    } catch (Exception ex) {
      logException(ex);
    }
  }
```
Plus, I see that there is already a check if a metric is registered
https://github.com/micrometer-metrics/micrometer/blob/b617100e92f55584f3207a29c8e0338d73042b73/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L569

**Comment by jonatan-ivanov** [comment]
You can do both.

You can create a timer, keep a reference to it and then use it.
You can only do this if your tags are static, if your tags are dynamic you need to use a builder. If you create two timers with the same name and tags, Micrometer won't create a new timer, it will reuse the existing one (`registerMeterIfNecessary `).

I'm not sure what you are trying to do here but I would highly recommend not measuring elapsed time on your own (here's why: [How Not to Measure Elapsed Time](https://develotters.com/posts/how-not-to-measure-elapsed-time/)), you can use the convenience features of the `Timer` for these:

```java
timer.record(() -> dontCareAboutReturnValue());
timer.recordCallable(() -> returnValue());
```
and/or
```java
Timer.Sample sample = Timer.start(registry);
Response response = doStuff();
sample.stop(registry.timer("my.timer", "status", response.status()));
```

**Comment by guy1699** [comment]
Thanks Jonatan,
So can you elaborate a bit, on what happens on the `register` call, is there any I/O call?
Because I'm trying to understand what happens when a new instance of my app starts and does not know about previous timers being written.

**Comment by jonatan-ivanov** [comment]
Hey @guy1699,

Could you please move these question either to Slack or to StackOverflow (slack is faster)?
You can check the source code/debug your app, there should not be I/O calls on register, those happen on publish in a separate thread asynchronously.

**Comment by guy1699** [comment]
Thank you !
