### ISSUE TITLE
micrometer support on console apps java/non boot apps

### ISSUE THREAD

**Issue by Krithikavv** [micrometer-metrics/micrometer#3208]
does micrometer support exporting data from non boot apps with java like console base apps or so or pure native java apps.?

I have an app which is not boot apps, but general app which is java based web object apple framework apps.

I dont see the meter data getting propagated from app to wards dynatrace( have updated the config programmatically for this) Works with spring boot apps with same config with src/main/resources/application.yaml/json .  I tried to check the meter data which is getting prepared but not propagated. how could I start troubleshooting this ?

**Comment by jonatan-ivanov** [comment]
Micrometer is a Java library it does not depend or tied to Spring so it can work with any Java app. Please check the docs to see how to configure it: https://micrometer.io/docs/registry/dynatrace
