### ISSUE TITLE
Dynatrace test failures

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#3213]
I checked the failed tests locally and I think those are unrelated and are from `dynatrace-metric-utils` [releasing a new version recently that bumped the max line length](https://github.com/dynatrace-oss/dynatrace-metric-utils-java/releases/tag/v1.6.0) that's breaking a couple tests.

_Originally posted by @simondemartini in https://github.com/micrometer-metrics/micrometer/issues/3139#issuecomment-1150672416_

/cc @pirgeo
See, for example, https://app.circleci.com/pipelines/github/micrometer-metrics/micrometer/2811/workflows/4ef46ed7-6377-4b96-abd2-cb0cec0b4e75/jobs/15089

**Comment by pirgeo** [comment]
Thanks for fixing this :) I didn't realize that we were pointing to `latest.release` in the dependencies, sorry!

**Comment by shakuzen** [comment]
> I didn't realize that we were pointing to `latest.release` in the dependencies, sorry!

It's a bit of an unusual setup on our part. We do this without dependency locking in the `main` branch to automatically pick up new versions and catch things like this early so we don't have a sudden surprise right before a release when upgrading dependencies. It does lead to surprises sometimes and unrelated pull request builds failing, however. On maintenance branches, we use dependency locking so versions will not change between builds.
