### ISSUE TITLE
Enhance code logic in PrometheusNamingConvention

### ISSUE THREAD

**Issue by EricGao888** [micrometer-metrics/micrometer#3231]
**Please describe the feature request.**
* There are two `switch` statements in `PrometheusNamingConvention`, which might be combined as one.

https://github.com/micrometer-metrics/micrometer/blob/393de2ffd8140d4e665bc0851d22b8772ee4c4a0/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusNamingConvention.java#L56-L79

**Rationale**
* Current logic makes developers a little bit confused.

**Additional context**
* I'd like to submit a PR to fix this.

**Comment by marcingrzejszczak** [comment]
Thank you for filing the issue and sorry for the delay, please file a PR :)

**Comment by EricGao888** [comment]
> Thank you for filing the issue and sorry for the delay, please file a PR :)

done

**Comment by marcingrzejszczak** [comment]
Currently this introduces more problems than fixes things. Let's close it for now.
