### ISSUE TITLE
Is it possible to use the micrometer prometheus integration in a spring boot library project

### ISSUE THREAD

**Issue by sweller999** [micrometer-metrics/micrometer#3246]
**Please describe the feature request.**
I believe there is probably already a way to do this, but I would like to add custom prometheus metrics via micrometer to a springboot client library app which is itself imported by a springboot api (Both of which I have access to the code)

**Rationale**
The micrometer prometheus integration works great out of the box, but we have a client lib which wraps a non-spring http client to make calls to another of our apis, and as such isn't included in the http_client_request_* metrics. Since the client lib only exposes two methods, I'd rather find a way to annotate those methods with @Timed within the lib itself, my thinking being annotating the methods I call the lib in in my api app will also include the execution time of the method I make the call in, and not just the time of the client calls.

The lib already uses Spring Boot Autoconfigure and Spring Context (Those are currently the only spring dependencies in the project), so my hope is there is a way to import the micrometer prometheus integration lib, use the @Timed annotation on those two methods there, and then have those metrics be exposed on the /actuator/prometheus endpoint of my api app that I import the lib to.

 Is this possible, or is there a better way to accomplish what I'm trying to do?

**Comment by jonatan-ivanov** [comment]
This question is better suited for stackoverflow.

The first thing I would check if the HTTP client that you use under the hood has Micrometer support or not, e.g.: JDK's HttpURLConnection, Apache HC, okhttp, OpenFeign, etc. do have.

If you are using a HTTP Client under the hood which is not supported (please tell us which one in that case), you can instrument any component using Micrometer by injecting a `MeterRegistry` (i.e.: through ctor) and create `Meter`s (`Timer`, `Counter`, etc.) as things happen. So when you create this component as a Spring `@Bean` you can inject the registry that Spring Boot provides for you and your `Meter`s will use this registry to report their measurements.

**Comment by sweller999** [comment]
Hi @jonatan-ivanov. I'll give the solution you described a shot. For the record, the client I'm referring to is the apollo-graphql-client

**Comment by jonatan-ivanov** [comment]
Since you are using Spring Boot, you might want to take a look at [Spring for GraphQL](https://spring.io/projects/spring-graphql) which as far as I remember has Micrometer support.
