### ISSUE TITLE
CaffeineCacheMetrics constructor inconsistent with other implementations

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#325]
`CaffeineCacheMetrics` takes a cache, a list of tags and a name. All other implementations take a cache, a name and a list of tags. It would be nice to harmonize the constructors.

I can prepare a PR if that helps.

**Comment by spencergibb** [comment]
:+1:

**Comment by snicoll** [comment]
Fixed by https://github.com/micrometer-metrics/micrometer/commit/d477d064cdf5d1bcffdf1a71b02b536c26d5460b#diff-49c147dbcc19197cf6d257520cf3026d
