### ISSUE TITLE
maven-compiler-plugin:3.8.1:compile for parameter path: Cannot find 'path' in class org.apache.maven.plugin.compiler.DependencyCoordinat

### ISSUE THREAD

**Issue by AbhijitJadhav4u** [micrometer-metrics/micrometer#3252]
maven is complaining  after adding micrometer entries. If remove entries build is successful.

command : mvn clean install. or mvn clean package

POM.XML:-->
<maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>

 <maven.compiler.release>8</maven.compiler.release>
   <maven.compiler.source>1.8</maven.compiler.source>
  <maven.compiler.target>1.8</maven.compiler.target>

Java 8.
micronaut version 3.0.1

Error message:-
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project XYZ: Unable to parse configuration of mojo org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile for parameter path: Cannot find 'path' in class org.apache.maven.plugin.compiler.DependencyCoordinate -> [Help 1]

Added following entries micronaut project in pom:------>
<annotationProcessorPath>
              <path>
                <groupId>io.micronaut.micrometer</groupId>
                <artifactId>micronaut-micrometer-annotation</artifactId>
              </path>
            </annotationProcessorPath>

and 

<dependency>
  <groupId>io.micronaut.micrometer</groupId>
  <artifactId>micronaut-micrometer-core</artifactId>
  <version>${micronaut.version}</version>
</dependency>

<dependency>
  <groupId>io.micronaut.micrometer</groupId>
  <artifactId>micronaut-micrometer-registry-statsd</artifactId>
  <version>${micronaut.version}</version>
</dependency>

<dependency>
  <groupId>io.micronaut</groupId>
  <artifactId>micronaut-management</artifactId>
  <version>${micronaut.version}</version>
</dependency>

**Comment by shakuzen** [comment]
I'm not sure what would cause that issue, but those are Micronaut-specific dependencies for Micronaut's integration with Micrometer. Please check with Micronaut support channels first to troubleshoot the issue. If it turns out there is some change to be made in Micrometer, we can reopen this issue or use a new one to track that work. Closing this for now as it needs to be triaged elsewhere, I think.
