### ISSUE TITLE
Whether the time-series database TDengine is supported

### ISSUE THREAD

**Issue by worker24h** [micrometer-metrics/micrometer#3253]
**Support TDengine**
I wish `Micrometer` could support `TDengine`. `TDengine` is an excellent and open source timing database.

1.  https://github.com/taosdata/TDengine
2. https://tdengine.com/
3. [Writer TDengine vs Influxdb](https://tdengine.com/2022/02/23/4975.html)
4. [Reader TDengine vs Influxdb](https://tdengine.com/2022/02/24/5120.html)

**Additional context**
I can support a new PR

everyone, thanks

**Comment by shakuzen** [comment]
Thank you for opening this request. This looks like an interesting choice for a metrics backend. We have to consider the cost of supporting any new feature, especially a new registry. We would like to see how much interest there is from Micrometer users for this, and how straightforward support for TDengine as a Micrometer registry would be. It would be a good first step to incubate an implementation of a MeterRegistry that publishes to TDengine outside of this repository. You could make a GitHub repository with the implementation called something like tdengine-micrometer-registry. Once that has been vetted by enough users, we could consider whether it makes sense to maintain the implementation here. Another option could be for the taosdata org to host the repository if they are willing to maintain it. Depending on how much the API/SDK used to publish metrics changes, it may be easier to keep things in sync and compatible there.

What do you think? Would you be interested in hosting a separate GitHub repository to incubate this and get feedback from users?

**Comment by worker24h** [comment]
> Thank you for opening this request. This looks like an interesting choice for a metrics backend. We have to consider the cost of supporting any new feature, especially a new registry. We would like to see how much interest there is from Micrometer users for this, and how straightforward support for TDengine as a Micrometer registry would be. It would be a good first step to incubate an implementation of a MeterRegistry that publishes to TDengine outside of this repository. You could make a GitHub repository with the implementation called something like tdengine-micrometer-registry. Once that has been vetted by enough users, we could consider whether it makes sense to maintain the implementation here. Another option could be for the taosdata org to host the repository if they are willing to maintain it. Depending on how much the API/SDK used to publish metrics changes, it may be easier to keep things in sync and compatible there.
> 
> What do you think? Would you be interested in hosting a separate GitHub repository to incubate this and get feedback from users?

Thanks, I think creating an incubation GitHub repository is the best option. Let's do it ?

**Comment by shakuzen** [comment]
> Let's do it ?

To be clear, my feedback was that anyone could make a repository (on GitHub or elsewhere) outside of the micrometer org to host a MeterRegistry implementation for TDengine. If someone does end up doing that, feel free to link to it here so interested users can find it. Since we haven't seen additional interest here, we'll close this for now. If folks are interested or make their own registry implementation for this, let us know. Thanks.
