### ISSUE TITLE
Allow for property based configuration of Hystrix commandGroupKey tag key and Hystrix commandKey tag key 

### ISSUE THREAD

**Issue by jarheadjred** [micrometer-metrics/micrometer#329]
I'm looking into updating my organizations metrics library usage to take advantage of the spring legacy micrometer features. 

In looking at the hystrix related functionality it looks like I have a compatibility issue due to the fact that my organization uses the generic 'group' tag as a common tag in the configuration of the library. If I understand things correctly that tag will be overridden by the hardcoded tags added to hystrix metrics being published.

Should specific binder implementations that are adding tags, provide for user configuration based overrides of their tag keys in the event that they collide with either: other binder implementations use of tags, or library consumers common tagging conventions?

https://github.com/micrometer-metrics/micrometer/blob/50495033630d417ea278ad7b9053d4d8e728a1ac/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisherCommand.java#L78

**Comment by checketts** [comment]
`MeterFilters` allow some adjustments if users need to combine or change tags, but I'm not sure if that would help you.  Can you give a little more detail around how your organization uses `group`?

I suspect in this case the hystrix tags are just too generic and could be changed to `commandGroup` and `commandKey` to avoid conflicts.

**Comment by jarheadjred** [comment]
Yes, generically our organization tags all our metrics reporting out to DataDog with `group` set to the Organizational Unit responsible for the application producing the metric. We have hundreds of dashboards and screenboards already configured utilizing the group tag so a refactoring in my case isn't possible.

We tag our outgoing hystrix metrics with `hystrixcommand`, `hystrixgroup`, and `threadpool`. In a generic sense the exercise I'm currently going through is being able to take micrometer provided binders and configure them to match our existing tags. HystrixBinder is the first example I'm exploring.

`MeterFilter` looks like it could solve my problem, but will would be more maintenance for us. Maybe following a TagProvider pattern similar to `DefaultRestTemplateExchangeTagsProvider` seems like it would be a more focused and intentional way to have binders allow for library consumers to provide a non-default bean based override of their Tag sets.

**Comment by jkschneider** [comment]
If I understand correctly, we have the following:

1. What micrometer tags as `group`, you'd prefer `hystrixgroup`.
2. What micrometer tags as `key`, you'd prefer `hystrixcommand`.
3. What micrometer tags as `threadpool`, you also tag as `threadpool`.

If so, with the added filter:

```
@Bean MeterFilter renameHystrixGroup() { return MeterFilter.renameTag("hystrix", "group", "hystrixgroup"); }
@Bean MeterFilter renameHystrixCommand() { return MeterFilter.renameTag("hystrix", "key", "hystrixcommand"); }
```

**Comment by jarheadjred** [comment]
@jkschneider Thanks for the example! I had to walk away from this but the solution with the static builder for the MeterFilter is very clear and concise. That should work well for our organization, we'll be packaging the tag renaming filters and other org specific things in a starter so that will continue to keep the domain services simple.

I appreciate the extra information and reasoning around the `XXXTagsProvider` related concepts. After reading your rationale for a tag provider vs just renaming metrics from a metric binder I agree that what you've got in place provides the customization points needed.

I'll close the issue, thanks for the extra insight and example!
