### ISSUE TITLE
Filter SignalFX datapoints

### ISSUE THREAD

**Issue by johnowl** [micrometer-metrics/micrometer#3296]
We have a limited amount of datapoints that we can send to SingalFX, so it would be nice to have a way to filter out some datapoints. Is it possible to do that with MeterFilter? Partially, because some metrics can turn into one or more datapoints in signalFX, for instance:

```
 private fun addTimer(timer: Timer) =
        sequenceOf(
            addDatapoint(timer, COUNTER, statSuffixCount, timer.count()),
            addDatapoint(timer, COUNTER, statSuffixTotalTime, timer.totalTime(baseTimeUnit)),
            addDatapoint(timer, GAUGE, statSuffixAvg, timer.mean(baseTimeUnit)),
            addDatapoint(timer, GAUGE, statSuffixMax, timer.max(baseTimeUnit))
        )
```

In the example above a timer will be transformed into 4 datapoints. It would be nice to remove the totalTime, the mean and the Max datapoints for a specific metric because I'm only interested in the count for example.

**Comment by johnowl** [comment]
Here a proposed solution: https://gist.github.com/johnowl/b0f0417abc521f648e410e3577779a98

**Comment by shakuzen** [comment]
The MeterFilter can only transform or filter out entire meters, not individual time series that may be produced during publishing of that Meter to a backend, because the way a Meter translates to time series is dependent on a backend to some degree. If you have control of the instrumentation and you only care about the count, you could instrument with a Counter instead of a Timer. If you are using instrumentation provided by a third-party, this isn't an option.

We could try to come up with a generic way to configure the time series produced by Meters, but one currently doesn't exist.

**Comment by johnowl** [comment]
@shakuzen this example with the count I totally agree with you, in this case we can just use a counter. The main problem here is the limited amount of metrics that we can send, so, in many cases what happens is disabling only the max.

I like your idea of having a generic way to configure the times series produced by Meters.  In this scenario it would be helpful.

**Comment by shakuzen** [comment]
In the meantime, if you want to customize the data points published to SignalFX, one solution is to extend and customize the behavior of our `SignalFxMeterRegistry`.

**Comment by johnowl** [comment]
We are using a solution similar if what you proposed. I'll try to come up with something similar with what you said: "We could try to come up with a generic way to configure the time series produced by Meters, but one currently doesn't exist."

**Comment by johnowl** [comment]
Something like this?

https://github.com/micrometer-metrics/micrometer/compare/main...johnowl:micrometer:main

**Comment by marcingrzejszczak** [comment]
There was not a lot of interest in this issue, let's wait for more thumbs up or comments. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
