### ISSUE TITLE
Error starting spring container with missing `java.time.Clock`

### ISSUE THREAD

**Issue by cskinfill** [micrometer-metrics/micrometer#330]
I have an existing spring boot app that starts and runs (its our production service) that has an
```
    @Bean
    public Clock clock() {
        return Clock.systemUTC();
    }
```
within an `@Configuration` class.  This clock is injected into another non-micrometer related class.

When I add the `micrometer-spring-legacy` project to my app, and do nothing else, when I try to run the app using `mvn spring-boot:run`, I'm getting this error

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.my.service.ResponseLogFilter required a bean of type 'java.time.Clock' that could not be found.
```

If I include the `micrometer-core` lib it runs fine.  Its only when the `micrometer-spring-legacy` lib is included.  I _assume_ there's some autoconfig happening but didn't notice anything that would appear to change the `java.time.Clock` from being instantiated and added to the spring context.

**Comment by checketts** [comment]
What version of micrometer are you on? I fixed this on a previous version. The behavior from Spring is when a new bean with a same ID is declared, the other bean is overridden/removed. 

The fix is for the MicroMeter clock to have a bean ID of `microMeterClock` as you can see here: https://github.com/micrometer-metrics/micrometer/blob/eeacc1c84508e73722af773bbfe08992445364e6/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/prometheus/PrometheusExportConfiguration.java#L92

**Comment by cskinfill** [comment]
I'm using`0.12.0.RELEASE`

The code you reference above is for an instance of `io.micrometer.core.instrument.Clock` but I'm referring to an instance of `java.time.Clock` that seems to be missing.

Also, I wasn't using Prometheus, but was trying to use influxdb.  If that's any part of the problem too.

**Comment by jkschneider** [comment]
@cskinfill `0.12.0.RELEASE` is quite old now. Could you please try 1.0.0-rc.5? Or wait until tomorrow and we may have an rc6 out.

**Comment by checketts** [comment]
@cskinfill The Prometheus example was just to demonstrate the fix. Here is what the Influx code you are running is: https://github.com/micrometer-metrics/micrometer/blob/v0.12.0.RELEASE/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/influx/InfluxExportConfiguration.java#L115

Spring is only looking at the bean IDs, even though the types are different. In your logs you would see some text about the clock bean being overwritten.

An alternative solution if you don't want to upgrade to the RC would be to change the name of your `java.time.Clock`

```
    @Bean
    public Clock systemUtcClock() { // <--Not the method name will change the bean ID
        return Clock.systemUTC();
    }
```

**Comment by jkschneider** [comment]
@cskinfill I'm going to close this issue because it is no longer an issue in more recent releases, but feel free to drop us a note if you have any other questions.

**Comment by cskinfill** [comment]
I tried with `1.0.0-rc.5` and my app started up fine now.

Why was I thinking that spring would use both the type and the bean id when it decided if a dependency was available for injection?  🤔
