### ISSUE TITLE
Non-monotonic kafka metric reported as counter

### ISSUE THREAD

**Issue by jack-berg** [micrometer-metrics/micrometer#3300]
**Describe the bug**
[KafkaMetrics](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java#L252-L253) converts the metric `kafka.consumer.connection.count` to a counter despite the number of connections _not_ being monotonically increasing. 

This is causing issues in in the [opentelemetry micrometer shim](https://github.com/open-telemetry/opentelemetry-java/tree/main/micrometer1-shim), which relies counters being monotonically increasing for a proper translation to the opentelemetry data model. 

**Environment**
 - Micrometer version: latest
 - Micrometer registry: opentelemetry micrometer shim
 - OS: any
 - Java version: any

**To Reproduce**
Run the [KafkaClientMetricsIntegrationTest](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/kafka/KafkaClientMetricsIntegrationTest.java#L113) and observe that the printed meters should `kafka.consumer.connection.count` is a counter where it should probably be a gauge. 

**Expected behavior**
`kafka.consumer.connection.count` and other non-monotonically increasing kafka metrics should probably be gauges instead of counters. 

Originally discussed in CNCF slack [here](https://cloud-native.slack.com/archives/C024DRQ63UP/p1657828698290849).

**Comment by shakuzen** [comment]
Thank you for reporting the issue.
It looks like it would be correct for us to remove the OR conditional checking for names ending in `count` when deciding whether to make a counter or gauge since all the names ending in count appear to be an active count (gauge).
https://github.com/micrometer-metrics/micrometer/blob/b617100e92f55584f3207a29c8e0338d73042b73/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java#L252

**Comment by jack-berg** [comment]
> It looks like it would be correct for us to remove the OR conditional checking for names ending in count when deciding whether to make a counter or gauge

That does appear to be the case. I implemented something similar in opentelemetry recently and inspected the type of the `KafkaMetric`'s `org.apache.kafka.common.metrics.Measurable`, and defined a [mapping](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/kafka/kafka-clients/kafka-clients-common/library/src/main/java/io/opentelemetry/instrumentation/kafka/internal/KafkaMetricRegistry.java#L36-L50) from measurable implementation to corresponding instrument type. This seemed safer to me than relying on naming naming conventions.

**Comment by shakuzen** [comment]
That does sound like a safer way to do it. Thank you for sharing.
