### ISSUE TITLE
How to create custom bucket values of the Histogram type?

### ISSUE THREAD

**Issue by wang007** [micrometer-metrics/micrometer#3324]
Timer register = Timer.builder("passive_handled_duration_seconds")
                .tag("a", "1")
                .buckets(.02, .05, .1, .2, .5, 1, 2, 5)

**Comment by shakuzen** [comment]
You can add custom buckets to the histogram by defining `serviceLevelObjectives` - see [the JavaDoc](https://www.javadoc.io/doc/io.micrometer/micrometer-core/latest/io/micrometer/core/instrument/Timer.Builder.html#serviceLevelObjectives(java.time.Duration...)).
