### ISSUE TITLE
add prefix to GraphiteReporter

### ISSUE THREAD

**Issue by chicagozer** [micrometer-metrics/micrometer#333]
When sending stats to graphite, I would like to set a prefix in `GraphiteMeterRegistry` indicating my instance/host. Currently, all stats go to the top level of my graphite server.

```
 this.reporter = GraphiteReporter.forRegistry(getDropwizardRegistry())
                .prefixedWith(<myprefix>)
                .convertRatesTo(config.rateUnits())
                .convertDurationsTo(config.durationUnits())
                .build(sender);
```
I believe I can add this to GraphiteConfig if you would accept a pull request.

**Comment by checketts** [comment]
You'll want to use the `commonTags` registry option for this capability. That way the instance/host info will be included in all your metrics and remain portable should you decide to leverage a different metric backend later.

Then for your `GraphiteRegistry` you would (in theory) set the prefix logic on the `GraphiteNamingConvention`. Perhaps a PR for the `GraphiteNamingConvention` would be worthwhile. For now you could leave out `commonTags` and just sub-class the naming convention, adding in your prefix there.

**Comment by chicagozer** [comment]
Thanks!

**Comment by checketts** [comment]
@chicagozer Hmm, I don't love that you have to code around the CompositeMeterRegistry`.

Could it be simplified to something like this?

```
    @Bean
    public MeterRegistryConfigurer configurer() {
        return (MeterRegistry registry) -> {
            if(registry instanceof GraphiteMeterRegistry) {
                NamingConvention nc = new NamingConventionImpl(env.getProperty("spring.metrics.export.graphite.prefix")); 
                registry.config().namingConvention(nc);
            }
    }
```

That way the `GraphiteMeterRegistry` is the only one configured.

**Comment by jkschneider** [comment]
Seems like a good signal that we still need to do something about configuring children inside a composite.

**Comment by checketts** [comment]
That was my first reaction too, but then realized that `MeterRegistryConfigurer`s are probably registry specific. For example the `NamingConvention` with Graphite specific config wouldn't be wanted for the Prometheus one.

If anything, perhaps it means we should exclude the composite from `MeterRegistryConfigurer`, then the user wouldn't need to check against it and the bean would just be:

```
    @Bean
    public MeterRegistryConfigurer configurer() {
        return (MeterRegistry registry) -> {
            NamingConvention nc = new NamingConventionImpl(env.getProperty("spring.metrics.export.graphite.prefix")); 
            registry.config().namingConvention(nc);
    }
```

**Comment by jkschneider** [comment]
Can't do that though, because suppose you want to add a filter rule that disables a metric across all registries in a composite.

**Comment by checketts** [comment]
Don't `MeterRegistryConfigurer` apply to a meter registries? That would allow the configurer to add the filter to all registries without having to go via the composite.

**Comment by jkschneider** [comment]
> Also I agree that filtering the composite might not be a good idea.

Actually, I think it's a fine idea. We have a test for filtering (say disabling) some set of metrics from the composite and then adding more specific filtering down on child registries.
