### ISSUE TITLE
Where to find complete list of metric names?

### ISSUE THREAD

**Issue by Paxa** [micrometer-metrics/micrometer#3333]
Is there any documentation with complete list of metric names? For each instrumentation binder

**Comment by jonatan-ivanov** [comment]
Right now we don't have such documentation though this could change in the future with the introduction of the Observation API in the next version of Micrometer (check `DocumentedObservation` and [micrometer-docs-generator](https://github.com/micrometer-metrics/micrometer-docs-generator), both are work in progress).
