### ISSUE TITLE
system.cpu.usage missing with OpenJ9 0.33.0

### ISSUE THREAD

**Issue by BingTang70** [micrometer-metrics/micrometer#3349]
Hi,

There  is a recently changes in OpenJ9  the  method  `getSystemCpuLoad()` removed from `com.ibm.lang.management.OperatingSystemMXBean`  and  inherited from `com.sun.management.OperatingSystemMXBean`
this cause the  [ProcessorMetrics.java](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/system/ProcessorMetrics.java) stop working,  which can not return the metric **system.cpu.usage** 

The method `detectMethod `invoke `getDeclaredMethod()`   it does not return the inherite methods , if change to `getMethod `will resolve this issue. 

```
    @Nullable
    private Method detectMethod(String name) {
        requireNonNull(name);
        if (operatingSystemBeanClass == null) {
            return null;
        }
        try {
            // ensure the Bean we have is actually an instance of the interface
            operatingSystemBeanClass.cast(operatingSystemBean);
            return operatingSystemBeanClass.getDeclaredMethod(name);
        }
        catch (ClassCastException | NoSuchMethodException | SecurityException e) {
            return null;
        }
    }
```

Thanks 

Bing

**Comment by shakuzen** [comment]
Thanks for reporting the issue and sorry for the trouble. I don't think there was a good reason I used `getDeclaredMethod` instead of `getMethod` so we can fix that.
Linking to https://github.com/eclipse-openj9/openj9/issues/15685
