### ISSUE TITLE
PrometheusMeterRegistry not being processed 

### ISSUE THREAD

**Issue by NavyashriS** [micrometer-metrics/micrometer#3377]
I am trying to add prometheus dependency to my application. I added the dependency and ran the application but it was not coming up on dashboard. I found in logs that prometheusMeterRegistry is not eligible for getting processed by all BeanPostProcessors.
Can anyone tell how to solve this issue.

**Comment by checketts** [comment]
@NavyashriS Can you please include version and dependency details? Are you using Spring Cloud or have any unusual beans that might be triggering an early instantiation? This sounds similar to something that was resolved by the Spring Cloud team a while ago.
