### ISSUE TITLE
JmxConfig extends from DropwizardConfig

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#338]
Reporting a potential design issue unless I am missing something. Currently `JmxConfig` extends from `DropWizardConfig`. That doesn't sound sane to me.

**Comment by jkschneider** [comment]
That's intentional. We are using Dropwizard as a passthru to get metrics to JMX. Same is true of Graphite and Ganglia. Other systems sometimes use vendor-provided clients as a passthru, others are done manually.
