### ISSUE TITLE
Support "TimerContext" in the Timer interface

### ISSUE THREAD

**Issue by sunnychanwork** [micrometer-metrics/micrometer#339]
In DropWizard they have a style for timer usage like this:

TimerContext tc = Timer.start();
/*Do some work*/
tc.stop() (record the time) 

This style is useful for cases like timing a JTA transaction where a transaction is start at transaction object creation, and we stop timing when someone call commit() or rollback(). 

see https://docs.oracle.com/javaee/7/api/javax/transaction/Transaction.html

**Comment by jkschneider** [comment]
Thanks for the feedback @sunnychanwork
