### ISSUE TITLE
 Micrometer Steps skipped by Datadog Registry

### ISSUE THREAD

**Issue by zangetsu420** [micrometer-metrics/micrometer#3393]
**Describe the bug**
I'm logging every increment of the metric to have a real value of the metric that should be sent in given interval.
The metrics sent through DatadogMeter API do not match those logs and do not match our database records.
Metrics should be sent with 1m step, some steps are simply skipped and never sent. (At least thats how it looks in DD)

**Environment**
- io.micrometer:micrometer-registry-datadog:1.9.1

 - Micrometer version - 1.9.1
 - Micrometer registry - Datadog 1.9.1
 - Alpine - Alpine Linux v3.14
 - Java version  - 1.8.0_345

**To Reproduce**
No idea - we just tried to use the built in Spring integration with micrometer.

**Expected behavior**
Metrics are correctly sent to Datadog with 1m step.

**Additional context**
It's not a network issue, we checked that, there are no errors logged about failed sends. It looks like the scheduler is simply not invoking ever step.
**Looking for tips on what else to check or fix to make ingested metrics correct!!**

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.
