### ISSUE TITLE
AbstractTimeWindowHistogram produces wrong values after long period of inactivity

### ISSUE THREAD

**Issue by MalyginaEkaterina** [micrometer-metrics/micrometer#3395]
**Describe the bug**
After a long period of inactivity Timer percentile values become equal to 0.0.

**Environment**
 - Micrometer version: 1.8.3
 - Micrometer registry: prometheus
 - OS: Windows
 - Java version: 11.0.14

**To Reproduce**
1. Set expiry in DistributionStatisticConfig to 60 seconds.
2. Start the app, invoke the method with @Timed annotation.
3. Wait 150 seconds, invoke the method with @Timed annotation again.
4. Get prometheus metrics.

**Expected behavior**
Timer percentile values not equal to 0.0.

**Additional context**
The bug is very similar to https://github.com/micrometer-metrics/micrometer/issues/2647

`AbstractTimeWindowHistogram::lastRotateTimestampMillis` does increase by more than `durationBetweenRotatesMillis * ringBuffer.length` during one `rotate()`, so the `rotate()` called from `takeSnapshot()` will reset all buckets to zero even if called immediately after `recordDouble()`

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file. Thank you!
