### ISSUE TITLE
'java.lang.module.FindException: Unable to derive module descriptor' when using module path with micrometer-core 1.10.0-M5

### ISSUE THREAD

**Issue by moarychan** [micrometer-metrics/micrometer#3398]
**Describe the bug**
The compilation failure occurs in our CI pipeline when building using Java 11, here is a temp [URL ](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1840856&view=logs&j=c1fb1ddd-7688-52ac-4c5f-1467e51181f3&t=270374a4-721a-5366-7f60-bad5b1983827&l=17)to see the console log.

I can see the module name is correct in version 1.10.0-M3.
![image](https://user-images.githubusercontent.com/19926623/189333414-db85a325-98bf-45ef-8bf2-b6fef883be3e.png)

It works fine in our CI pipelines based on Java 8.

```console
[ERROR] Error occurred during initialization of boot layer
[ERROR] java.lang.module.FindException: Unable to derive module descriptor for D:\a\_work\1\.m2\repository\io\micrometer\micrometer-core\1.10.0-M3\micrometer-core-1.10.0-M3.jar
```

**Environment**

 - Micrometer version [1.10.0-M3]
 - OS: [windows server 2019]
 - Java version: [11.0.16.1, vendor: Eclipse Adoptium, runtime: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\11.0.16-101\x64]

**To Reproduce**
How to reproduce the bug:
Please follow this steps:
- Checkout this branch https://github.com/moarychan/azure-sdk-for-java/tree/moary/migrate-spring-data-cosmos-to-spring-dir
- Or sparse checkout below parts:
  ```console
  /*
  !/*/
  /eng
  **/*.xml
  /sdk/cosmos
  /sdk/formrecognizer
  /sdk/parents
  /sdk/spring  
  ```

- Run the below command in the root project:
  `mvn.cmd -f pom.xml  --batch-mode --fail-at-end --settings eng/settings.xml -Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Dgpg.skip -Dmaven.javadoc.skip=true -Dcodesnippet.skip=true -Dspotbugs.skip=true -Dcheckstyle.skip=true -Drevapi.skip=true -DtrimStackTrace=false -pl com.azure:azure-cosmos, -DAZURE_TEST_DEBUG=false -Dparallel-test-playback=true -Punit -T 1C verify`

**Expected behavior**
Normal use.

**Additional context**
N/A

**Comment by jonatan-ivanov** [comment]
Can you try what happens if you build against `M4`?
Can you build it locally? (I would also try wiping out micrometer from your maven cache.)

Are you sure this is caused by micrometer? And not something else, e.g.: your JVM crashed:
```
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

**Comment by moarychan** [comment]
Thanks for your update.

When using M4, the same error occurs, 
![image](https://user-images.githubusercontent.com/19926623/189790554-ce12f94d-513e-42f3-81dd-d3c640809de1.png)

I am not sure this is caused by micrometer, but this error message seems to have appeared before the JVM crashed.

Could you please help double-check this error message? Many thanks!

**Comment by saragluna** [comment]
I tried to run `java -p ~/.m2/repository/io/micrometer/micrometer-core/1.10.0-M3/micrometer-core-1.10.0-M3.jar --list-modules` for `micrometer-core` version `1.10.0-M3` and got the following error:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for /Users/xxx/.m2/repository/io/micrometer/micrometer-core/1.10.0-M3/micrometer-core-1.10.0-M3.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor not in module
```

**Comment by saragluna** [comment]
@jonatan-ivanov seems like the issue was caused by https://github.com/micrometer-metrics/micrometer/blob/f2977bcf864f8c16934978be2f0c3a43b6a50687/micrometer-core/src/main/resources/META-INF/services/io.micrometer.context.ThreadLocalAccessor#L1?

**Comment by moarychan** [comment]
I have seen the below information, does this indicate the JVM crashed with the micrometer module exception? 

![image](https://user-images.githubusercontent.com/19926623/189841939-efed849c-d79b-4882-a082-e60a18f32d32.png)

@jonatan-ivanov could you help give a workaround to fix this exception? Thanks! We are preparing to release a milestone version for Spring Boot 3 support.

**Comment by saragluna** [comment]
@shakuzen if the `micrometer-observation` already has this https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-observation/src/main/resources/META-INF/services/io.micrometer.context.ThreadLocalAccessor, can we remove it from the `micrometer-core`?

**Comment by shakuzen** [comment]
@saragluna indeed we shouldn't need it in both places. I think it was an oversight it ended up in both modules. Thank you for catching that. I have removed the service provider config file from micrometer-core now. I tried it locally and the `--list-modules` command works on the produced jar now.

Would you be able to try out the latest snapshot to let us know if things are working fine now?

Our next planned (pre-)release is the RC1 version for Micrometer 1.10 on October 10. Is that alright for you all or is this issue blocking a release you would like to do sooner than that? We can consider doing an unplanned release sooner if it is critical for you all.

**Comment by saragluna** [comment]
Thanks @shakuzen! We'll first test the snapshot version and let you know later whether we need a release.

**Comment by jonatan-ivanov** [comment]
@saragluna @moarychan Thank you for the details, please let us know if this is fixed on your side.
Also, fyi, we are adding a check to our build based on your feedback to detect things like this: https://github.com/micrometer-metrics/micrometer/pull/3411

It seems the newrelic registry still has issues, please let us know if you are building against it.

**Comment by moarychan** [comment]
Hi @jonatan-ivanov thanks for your support, I just passed the artifact building using the snapshot version,  we still need a release version for our pipeline side to finish lots of verification, please help to release a new version.

**Comment by shakuzen** [comment]
@moarychan Micrometer 1.10.0-M6 is now published to the milestones repository. Can you use that to verify things are fixed?

**Comment by moarychan** [comment]
Yes, thanks for your support.
