### ISSUE TITLE
Project version is not correct during release tag build

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#3408]
See for instance this CI build: https://app.circleci.com/pipelines/github/micrometer-metrics/micrometer/3319/workflows/fa0296a1-7e7b-468c-b491-19dd3efc0ee0/jobs/17823

Or this Gradle build scan: https://ge.micrometer.io/s/g7zutvuq7su3e

This was a build of the `v1.9.4` tag, but the version during the build job is determined as `1.10.0-SNAPSHOT`. During the actual deploy, it would end up as `1.9.4` due to the following having `-Prelease.useLastTag=true`.
https://github.com/micrometer-metrics/micrometer/blob/3b6b2a7b482f9d285185831791541c196d26ed8d/gradle/deploy.sh#L24

**Comment by marcingrzejszczak** [comment]
@jonatan-ivanov is this still a problem?

**Comment by jonatan-ivanov** [comment]
I think `-Prelease.useLastTag=true` does the trick for releases so it should not be an issue there. I _guess_ it could be that we print out the version number at the beginning of each build that might be modified after we print them out to the correct value?
