### ISSUE TITLE
Instrument Vert.x applications

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#343]
cc / @jfconavarrete

**Comment by vietj** [comment]
the vertx team is willing to support the micrometrics library and commit to its maintenance, is that something we can discuss to achieve synergy between the two projects ?

**Comment by jkschneider** [comment]
@vietj Sounds good. You can reach me in real time on slack.micrometer.io or jkschneider@gmail.com.

**Comment by izeye** [comment]
Closing as Micrometer support for Vert.x seems to exist in Vert.x repo now.

See https://github.com/vert-x3/vertx-micrometer-metrics
See also https://vertx.io/docs/vertx-micrometer-metrics/java/
