### ISSUE TITLE
Add `GraphiteConfig#tagAsPrefix`

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#348]
Prefixing as a thing is a very graphite-specific thing unfortunately, so maybe we could get on board with a `GraphiteConfig#prefix()`. On the other hand, we haven't done this historically because the prefix folks add to Graphite metrics tend to be something like application name which really is a _tag_ in a dimensional system. So our advice has been to add a common tag with (following this example) application name, and then override the naming convention to place that tag value in a prefix position in the name. By adding a common tag, the metric is instantly portable to more capable dimensional monitoring systems for which nobody really does prefixing.

That said, we get this request _a lot_ for Graphite users. So much so, that I think it's safe to say the majority of Graphite users want some sort of tag-like prefix on their metrics. So perhaps a `GraphiteConfig#tagAsPrefix(tagKey)` would be even better. Guide the user to adding a common tag that is portable, and imbue the default Graphite naming convention with a knowledge of how to turn the specified tag key into a prefix when it is present.

**Comment by michaelmcfadyen** [comment]
In the past I have used multiple elements combined as the Graphite prefix ie. `<app>.<hostname>`.
So could the `GraphiteConfig#tagAsPrefix(tagKey)` method definition support multiple tags and be `GraphiteConfig#tagAsPrefix(tagKeys...)`? You would have to derive the order of tags when building the prefix from the order they are passed in.

**Comment by jkschneider** [comment]
@michaelmcfadyen Sure, sounds like a good idea!

**Comment by jkschneider** [comment]
Fixed in 7f1e0f4
