### ISSUE TITLE
OkHttp timeout metrics

### ISSUE THREAD

**Issue by Paxa** [micrometer-metrics/micrometer#3483]
Is it possible to see metrics for timeouts & exceptions for OkHttpMetricsEventListener metrics? Or any other okhttp integration?

**Comment by jonatan-ivanov** [comment]
It is but at the moment I don't think it is possible using `OkHttpMetricsEventListener` alone.
I think there are three options:

1. We can explore the possibility of adding this information to `OkHttpMetricsEventListener`. Right now [it sets a `status` tag](https://github.com/micrometer-metrics/micrometer/blob/e904ffd9bca5c8079bde69eb89b27f171784ed88/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java#L217) based on the exception. Would you mind helping us debug into that method and checking what exception is there when you simulate a timeout? I.e.: we might be able to add an error tag that has the class name of the exception.

2. You can use `@Timed` which [does exactly this](https://github.com/micrometer-metrics/micrometer/blob/e904ffd9bca5c8079bde69eb89b27f171784ed88/micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java#L237), or you can add an extra `Timer` manually. The disadvantage of this is the cost of an extra `Timer` and inconvenience.

3. With 1.10 we are going to release the Observation API. OkHttp is instrumented and it [attaches the error](https://github.com/micrometer-metrics/micrometer/blob/e904ffd9bca5c8079bde69eb89b27f171784ed88/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpObservationInterceptor.java#L103): there are two advantages of this: 1. you can have logs, tracing, etc. on top of metrics and 2. if you don't like the data what Micrometer attaches (see [`DefaultMeterObservationHandler`](https://github.com/micrometer-metrics/micrometer/blob/e904ffd9bca5c8079bde69eb89b27f171784ed88/micrometer-core/src/main/java/io/micrometer/core/instrument/observation/DefaultMeterObservationHandler.java#L74)), you can write your own handler and attach whatever tags you want based on the exception.

**Comment by marcingrzejszczak** [comment]
There was no feedback since 2022. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
