### ISSUE TITLE
DistributionStatisticConfig object is mutable 

### ISSUE THREAD

**Issue by gopircr** [micrometer-metrics/micrometer#3489]
**Describe the bug**

Builder to create DistributionStatisticConfig object doesnt follow the standard [Builder design pattern ](https://blogs.oracle.com/javamagazine/post/exploring-joshua-blochs-builder-design-pattern-in-java) and hence the state of the config object can potentially  be modified after it is created. 

**Environment**

 - Micrometer version 1.9.5
 

**To Reproduce**

 ```
       DistributionStatisticConfig.Builder  b = DistributionStatisticConfig.builder()
                .bufferLength(1000)
                .maximumExpectedValue(300.0);
        
        DistributionStatisticConfig config = b.build();
        
        // prints 1000
        System.out.println(config.getBufferLength()); 

        //builder is reused to create more config objects
        b.bufferLength(400);

        //side effect of updating the builder. It prints 400
        System.out.println("again-"+config.getBufferLength()); 

```

**Expected behavior**

The standard builder pattern is used to create immutable objects and if the desired behavior is to allow mutability then builder name can be a misnomer and can cause confusion.   Its perhaps a common practice that builder itself can be reused to create more objects of the same type ( in this case its config object ).

**Comment by marcingrzejszczak** [comment]
What problem would this change actually fix?
