### ISSUE TITLE
Investigate a type-safe `MeterRegistryConfigurer`

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#349]
Avoids:

```
@Bean
public MeterRegistryConfigurer configurer(MeterRegistry registry) {
   if(registry instanceof GraphiteMeterRegistry) {
      // do something specific to Graphite
   }
}
```

In fact, the above doesn't even work for the composite case. You have to do a separate instanceof check for `CompositeMeterRegistry` and then recurse down its children. Ugly.

cc / @checketts

**Comment by checketts** [comment]
I thought when you have a composite meter registry all the child registries go through this path, so the composite can be completely ignored.

**Comment by jkschneider** [comment]
I don't think so? After all, Spring can only inject the `MeterRegistry` it has available to it, which is the composite. All the other registries are hidden under `MetricsExporter` which is essentially a `Supplier<MeterRegistry>`, just exists as a layer of type indirection so Spring knows which `MeterRegistry` to inject.

**Comment by checketts** [comment]
Ah I thought Micrometer was checking and essentially iterating over the `MetricsExporter`s

**Comment by checketts** [comment]
It appears that the only the `CompositeMeterRegistry` does this config.

https://github.com/micrometer-metrics/micrometer/blob/9ae63906cc78d44c444dbb43340b5b287d6b645e/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/MetricsAutoConfiguration.java#L104

Am I missing something else that is driving this config? I want to make sure I'm not missing something here so I don't play with a solution with a bad understanding.

**Comment by jkschneider** [comment]
The previous assumption was that if you are displacing the composite with another `@Bean MeterRegistry`, then there is really no point in `MeterRegistryConfigurer`, as you'd just configure it as you created it.

I'm expecting some feedback from the Boot team on exactly how they think it should work. Something about a `BeanFactoryPostProcessor`? As part of this, Phil is also keen to conditionally create a composite iff there is more than one registry implementation in play.
