### ISSUE TITLE
Prometheus histogram containing summary fails to be scraped by Opentelemetry collector

### ISSUE THREAD

**Issue by markfergy** [micrometer-metrics/micrometer#3494]
**Describe the bug**
The Opentelemetry collector drops the histogram metrics containing a summary as being invalid when scraped from the Prometheus endpoint (ie localhost/actuator/prometheus).

There is an explicit check in the Opentelemetry collector making sure a summary and histogram have the expected metrics data points. I assume this is based off how the metric types are documented by Prometheus https://prometheus.io/docs/concepts/metric_types/

There is no mention about a histogram containing a summary (They seem to be documented as separate metric types).

I found a comment in this file https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java

```
// Prometheus doesn't balk at a metric being BOTH a histogram and a
// summary
```

While the Prometheus server might not balk at this obviously other collectors are validating the data input and deem this to be invalid. 
 
**Environment**

 - Micrometer version [1.9.5]
 - Micrometer registry [prometheus]
 - OS: [Linux, Windows]
 - Java version: [11.0.16]

**To Reproduce**
How to reproduce the bug:

Create a timer publishing both  percentiles and percentile histogram
```
default Timer initTimer(MeterRegistry registry, String meterName, String... tags) {
        LOGGER.info("Creating a new timer with name {} and tags: {}", meterName, tags);
        return Timer.builder(meterName)
                .publishPercentiles(0.5, 0.9, 0.95, 0.99)
                .publishPercentileHistogram()
                .serviceLevelObjectives(Duration.ofMillis(200))
                .minimumExpectedValue(Duration.ofMillis(1))
                .maximumExpectedValue(Duration.ofSeconds(10))
                .tags(tags)
                .register(registry);

```

Output will be something like this (curl localhost/actuator/prometheus):

```
\# HELP curve_construction_latency_seconds  
\# TYPE curve_construction_latency_seconds histogram
curve_construction_latency_seconds{ric="RATES.USD.SWAP.LCH:MAQB",quantile="0.5",} 0.0
curve_construction_latency_seconds{ric="RATES.USD.SWAP.LCH:MAQB",quantile="0.9",} 0.0
curve_construction_latency_seconds{ric="RATES.USD.SWAP.LCH:MAQB",quantile="0.95",} 0.0
curve_construction_latency_seconds{ric="RATES.USD.SWAP.LCH:MAQB",quantile="0.99",} 0.0
curve_construction_latency_seconds_bucket{ric="RATES.USD.SWAP.LCH:MAQB",le="0.001",} 1.0
curve_construction_latency_seconds_bucket{ric="RATES.USD.SWAP.LCH:MAQB",le="0.001048576",} 1.0
curve_construction_latency_seconds_bucket{ric="RATES.USD.SWAP.LCH:MAQB",le="0.001398101",} 1.0
curve_construction_latency_seconds_bucket{ric="RATES.USD.SWAP.LCH:MAQB",le="0.001747626",} 1.0
curve_construction_latency_seconds_bucket{ric="RATES.USD.SWAP.LCH:MAQB",le="0.002097151",} 1.0
.......
curve_construction_latency_seconds_count{ric="RATES.USD.SWAP.LCH:MAQB",} 1.0
curve_construction_latency_seconds_sum{ric="RATES.USD.SWAP.LCH:MAQB",} 0.0
.......
```

**Expected behavior**
There should be a separate histogram and summary output.

```
\# HELP curve_construction_latency_seconds  
\# TYPE curve_construction_latency_seconds histogram
curve_construction_latency_seconds_bucket{ric="RATES.USD.SWAP.LCH:MAQB",le="0.001",} 1.0
curve_construction_latency_seconds_bucket{ric="RATES.USD.SWAP.LCH:MAQB",le="0.001048576",} 1.0
curve_construction_latency_seconds_bucket{ric="RATES.USD.SWAP.LCH:MAQB",le="0.001398101",} 1.0
curve_construction_latency_seconds_bucket{ric="RATES.USD.SWAP.LCH:MAQB",le="0.001747626",} 1.0
curve_construction_latency_seconds_bucket{ric="RATES.USD.SWAP.LCH:MAQB",le="0.002097151",} 1.0
.......
curve_construction_latency_seconds_count{ric="RATES.USD.SWAP.LCH:MAQB",} 1.0
curve_construction_latency_seconds_sum{ric="RATES.USD.SWAP.LCH:MAQB",} 0.0
.......

# HELP curve_construction_latency_seconds  
# TYPE curve_construction_latency_seconds summary
curve_construction_latency_seconds{ric="RATES.USD.SWAP.LCH:MAQB",quantile="0.5",} 0.0
curve_construction_latency_seconds{ric="RATES.USD.SWAP.LCH:MAQB",quantile="0.9",} 0.0
curve_construction_latency_seconds{ric="RATES.USD.SWAP.LCH:MAQB",quantile="0.95",} 0.0
curve_construction_latency_seconds{ric="RATES.USD.SWAP.LCH:MAQB",quantile="0.99",} 0.0
curve_construction_latency_seconds_count{ric="RATES.USD.SWAP.LCH:MAQB",} 1.0
curve_construction_latency_seconds_sum{ric="RATES.USD.SWAP.LCH:MAQB",} 0.0
```

**Additional context**
Note this is only a problem if you are publishing both  percentiles and percentile histogram at the same time.

**Comment by shakuzen** [comment]
> There should be a separate histogram and summary output.

I don't think having the same name with a different type is valid either, by the way. From [OpenMetrics](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#metricset):

> Each MetricFamily name MUST be unique.

Or from [Prometheus' documentation](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels):

> Every time series is uniquely identified by its _metric name_ and optional key-value pairs called _labels_.

**Comment by markfergy** [comment]
I guess you can say we came across the issue by mistake. A developer had enabled publishing of both percentiles and percentile histogram and then we saw the error in the Opentelemetry collector.

We are exposing Prometheus metrics in our applications and  using the Opentelemetry collector to scrape and then export them to Influxdb.

I am not that familiar with using histogram data to know whether you would want to publish the percentiles and percentile histogram at the same time.

**Comment by markfergy** [comment]
> I don't think having the same name with a different type is valid either, by the way. From [OpenMetrics](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#metricset):

Yes I agree based on the Open Metrics standard each Metric family name should be unique so publishing a separate summary and histogram with the same name would not be valid. 

You could say that when publishing both percentiles and percentile histogram combining them into a single type histogram could be a valid representation. Since each metric point component is grouped by suffix and label it is valid in that respect, however not from the definition of what a histogram is.

**Comment by markfergy** [comment]
Our use case would be to only publish a summary or histogram (without percentiles) so it is just a matter of being aware not to publish both at the same time.

That is the solution we will move forward with so this bug can be closed I think with not action required.

**Comment by shakuzen** [comment]
@markfergy thank you for the thoughts on this and giving us some insight into your use case. It's certainly not ideal that this can cause issues in some setups. We could perhaps log a warning, but it's not an issue when using Prometheus itself.
If the end goal is to store metrics in Influxdb, we do have a registry to publish directly from your application to Influx. If you want to publish to an OpenTelemetry collector in between, the OTLP registry is another option.

**Comment by shakuzen** [comment]
@droni1234 please be more specific about what your issue is. I copied a sample scrape output in Prometheus text format of a single Micrometer Timer that has publishPercentileHistogram enabled, and there were no errors from the linting tool. There were notices that there was no help text because I did not set a description, but help text is optional.

**Comment by droni1234** [comment]
Hey Shakuzen,

I have here an example of our metric that is produced, I redacted the names.

```
# HELP XXXXX_duration_seconds  
# TYPE XXXXX_duration_seconds histogram
XXXXX_duration_seconds{tag="A",quantile="0.5",} 0.0
XXXXX_duration_seconds{tag="A",quantile="0.95",} 0.0
XXXXX_duration_seconds{tag="A",quantile="0.99",} 0.0
XXXXX_duration_seconds_bucket{tag="A",le="0.001",} 0.0
XXXXX_duration_seconds_bucket{tag="A",le="0.001048576",} 0.0
XXXXX_duration_seconds_bucket{tag="A",le="0.001398101",} 0.0
XXXXX_duration_seconds_bucket{tag="A",le="0.001747626",} 0.0
XXXXX_duration_seconds_bucket{tag="A",le="0.002097151",} 0.0
XXXXX_duration_seconds_bucket{tag="A",le="0.002446676",} 0.0
XXXXX_duration_seconds_count{tag="A",} 0.0
XXXXX_duration_seconds_sum{tag="A",} 0.0
```

This gives the warning 
![image](https://github.com/micrometer-metrics/micrometer/assets/44118346/f32e1485-ad68-4c1e-a0c1-8c36d61e9717)

And looking at the prometheus doc, their example looks vastly different:
```
# A histogram, which has a pretty complex representation in the text format:
# HELP http_request_duration_seconds A histogram of the request duration.
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_bucket{le="0.05"} 24054
http_request_duration_seconds_bucket{le="0.1"} 33444
http_request_duration_seconds_bucket{le="0.2"} 100392
http_request_duration_seconds_bucket{le="0.5"} 129389
http_request_duration_seconds_bucket{le="1"} 133988
http_request_duration_seconds_bucket{le="+Inf"} 144320
http_request_duration_seconds_sum 53423
http_request_duration_seconds_count 144320

# Finally a summary, which has a complex representation, too:
# HELP rpc_duration_seconds A summary of the RPC duration in seconds.
# TYPE rpc_duration_seconds summary
rpc_duration_seconds{quantile="0.01"} 3102
rpc_duration_seconds{quantile="0.05"} 3272
rpc_duration_seconds{quantile="0.5"} 4773
rpc_duration_seconds{quantile="0.9"} 9001
rpc_duration_seconds{quantile="0.99"} 76656
rpc_duration_seconds_sum 1.7560473e+07
rpc_duration_seconds_count 2693
```

We use vertx 4.2.3
which contains vertx-micrometer-metrics
and we use micrometer-registry-prometheus 1.11.3

My question would be why we are not getting something similar to the prometheus docs and how I could potentially change this.

Kind Regards Phips

**Comment by jonatan-ivanov** [comment]
What do you mean by that it "looks vastly different", could you please be more specific about what your issue is?

- Is it the optional `HELP` text that you are missing?
- Is it that the bucket and/or quantile labels are not the same?
- Is it that the Summary and the Histogram has the same name? (I'm not sure why you have both, you can get quantiles from the Histogram using `histogram_quantile `)

Also, your output is different because you are doing a different thing, in order to get the same output:
1. Create a `Timer`, name it `http.request.duration`, enable histogram, and do not add any tags (the buckets will be different though).
1. Create another `Timer`, name it `rpc.duration`, add the percentiles you want, and do not add any tags.

I'm also curious what you mean by "wrongly formatted". Is that Prometheus is not able to parse the data or Prometheus is able to parse it it's just the linter who does not like it?

**Comment by shakuzen** [comment]
@droni1234 did you see the previous comments in this issue? In particular, https://github.com/micrometer-metrics/micrometer/issues/3494#issuecomment-1284894586. The example you provided has percentile histogram and client-side percentiles enabled for the same Timer, which is what's causing the problem you mention. Why are you doing that instead of calculating the percentiles server-side based on the histogram? If you want to enable histogram on one Timer and client-side percentiles on a different Timer, similar to your example from the Prometheus docs, that would also be fine.

**Comment by droni1234** [comment]
@shakuzen I am new to to this. Would you mind to explain where the difference is between publishPercentiles and publishPercentileHistogram?

If I understood correctly I could drop publishPercentiles and calculate them on server-side.
I think that a fitting query is actually already in use looking at our Prometheus query in Grafana.

```
quantile (
  0.90,
  XXXXXX:latency:response_time{filters......}
)
```

Kind Regards

**Comment by shakuzen** [comment]
@droni1234 see the Micrometer documentation. It has a section on [Histograms and Percentiles](https://micrometer.io/docs/concepts#_histograms_and_percentiles). The Prometheus function you would use with percentile histograms is [`histogram_quantile`](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile).
