### ISSUE TITLE
A puzzle about the meter publish model

### ISSUE THREAD

**Issue by uraurora** [micrometer-metrics/micrometer#3506]
**Please describe the feature request.**
As the title said, I have a question about the publish model, which combines the publisher and registry together. As a result, the MeterRegitstry has two roles here, and if I want to publish same meter with different client, I should create the meter twice. Perhaps I made a mistake on the way using it, but if not, please tell me the purpose of this framework.

**Rationale**
Base the producer-consumer model,  MeterRegistry should be the queue or registry center role, and a publish layer is needed.

**Additional context**
A picture blew  could show my opinion clearly

<img width="782" alt="image" src="https://user-images.githubusercontent.com/37466949/198247552-9416c308-775c-497a-b7e2-5b55d047bdab.png">

**Comment by jonatan-ivanov** [comment]
Have you taken a look at [CompositeMeterRegistry](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/composite/CompositeMeterRegistry.java)? :)

**Comment by uraurora** [comment]
I have taken a look at the details of `CompositeMeterRegistry`. It is more like component composition and enhancement on the existing meter-regsitry. I think it will be better if the publisher and the registry are decoupled. However, it is indeed enough in most scenarios. Thanks for your prompt and quick reply 😄.

**Comment by uraurora** [comment]
> Have you taken a look at [CompositeMeterRegistry](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/composite/CompositeMeterRegistry.java)? :)

I have taken a look at the details of CompositeMeterRegistry. It is more like component composition and enhancement on the existing meter-regsitry. I think it will be better if the publisher and the registry are decoupled. However, it is indeed enough in most scenarios. Thanks for your prompt and quick reply 😄.

**Comment by uraurora** [comment]
I have taken a look at the details of CompositeMeterRegistry. It is more like component composition and enhancement on the existing meter-regsitry. I think it will be better if the publisher and the registry are decoupled. However, it is indeed enough in most scenarios. Thanks for your prompt and quick reply 😄.
