### ISSUE TITLE
Datadog: LongTaskTimer/Active Interpreted as a Time rather than Occurrence

### ISSUE THREAD

**Issue by darylrobbins** [micrometer-metrics/micrometer#3511]
**Describe the bug**
The Active statistic for the LongTaskTimer does not override the default units for the metric so it's reported as a time rather than an occurence.

**Environment**
 - Micrometer version 1.9.5
 - Micrometer registry Datadog
 - OS: Windows
 - Java version: VM information: OpenJDK Runtime Environment 1.8.0_322-b06 Amazon.com Inc. OpenJDK 64-Bit Server VM 25.322-b06

**To Reproduce**
How to reproduce the bug:
Send a LongTaskTimer metric to Datadog and observe the statistic:active values in Datadog.

**Expected behavior**
The values should be reported as occurrences.

**Additional context**
Add any other context about the problem here, e.g. related issues.

**Comment by marcingrzejszczak** [comment]
Thank you for filing this issue! Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file. Thank you for your understanding.
