### ISSUE TITLE
Upgrade context-propagation to 1.0.0

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#3524]
Update `dependencies.gradle`
And update the lock files:
```bash
./gradlew resolveAndLockAll --no-build-cache --update-locks 'io.micrometer:context-propagation'
```

**Comment by shakuzen** [comment]
I've also made sure to remove the snapshot and milestone repository declarations we had for resolving context-propagation from them, now that it is available in central.
