### ISSUE TITLE
ClassNotFound: io.micrometer.common.util.StringUtils on 1.10.x

### ISSUE THREAD

**Issue by bourgeoisor** [micrometer-metrics/micrometer#3530]
**Describe the bug**
After bumping `micrometer-registry-stackdriver` from `1.9.5` to `1.10.0`, my unit tests started failing with the following errors:

```
[ERROR] addTransactionFailWhenWhenAmountLargerThanBalance{TestInfo}  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: io/micrometer/common/util/StringUtils
        at anthos.samples.bankofanthos.ledgerwriter.LedgerWriterControllerTest.setUp(LedgerWriterControllerTest.java:85)
Caused by: java.lang.ClassNotFoundException: io.micrometer.common.util.StringUtils
        at anthos.samples.bankofanthos.ledgerwriter.LedgerWriterControllerTest.setUp(LedgerWriterControllerTest.java:85)
```

You can see the diff & complete `mvn test` log here: https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1078

I looked through https://github.com/micrometer-metrics/micrometer/wiki/1.10-Migration-Guide but didn't see any breaking changes relevant to me from 1.9 to 1.10.

I also attempted to go around it by explicitly importing `io.micrometer.common.util.StringUtils` but got an error stating that path did not exist. A quick search around seem to suggest that it has been moved to `io.micrometer.core.instrument.util.StringUtils`?

**Environment**
 - Micrometer version [1.10.0]
 - Micrometer registry [maven: micrometer-registry-stackdriver]
 - OS: [Linux]
 - Java version: [openjdk 19]

**To Reproduce**
Run the following function:
```
StackdriverMeterRegistry meterRegistry = new StackdriverMeterRegistry(new StackdriverConfig(){...}, clock)
```
Full context: https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/src/ledgerwriter/src/test/java/anthos/samples/bankofanthos/ledgerwriter/LedgerWriterControllerTest.java#L83

**Expected behavior**
I expected the bump from 1.9.x to 1.10.x to not affect my unit tests (no breaking changes).

**Additional context**
This is the artifact used: https://mvnrepository.com/artifact/io.micrometer/micrometer-registry-stackdriver/1.10.0

Noting that the following directory seem to not have been modified since 1.9.x: https://github.com/micrometer-metrics/micrometer/tree/1.10.x/implementations/micrometer-registry-stackdriver

**Comment by ttddyy** [comment]
In your PR https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1078 
I see it is using micrometer `1.9.5` from Spring Boot, not `1.10.0`. That's the incompatibility.

```
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.7.5:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.7.5:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:2.7.5:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.9.5:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] +- io.micrometer:micrometer-registry-stackdriver:jar:1.10.0:compile
[INFO] |  +- com.google.cloud:google-cloud-monitoring:jar:3.6.0:compile
```

**Comment by jonatan-ivanov** [comment]
[`io.micrometer.common.util.StringUtils`](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/util/StringUtils.java) is deprecated but should be available in 1.10.0.

**Comment by shakuzen** [comment]
To add onto what others have said already, the key is that you need to use consistent versions of Micrometer. We provide the micrometer-bom for this purpose, which Spring Boot's dependency management uses. You should be able to override the version of Micrometer dependencies that Spring Boot is managing, e.g. with a Maven property `micrometer.version` if you are using the Spring Boot parent rather than overriding the version of one dependency.

**Comment by bourgeoisor** [comment]
The BOM seem to have done the trick, that's my bad... Thank you for the guidance!
