### ISSUE TITLE
Consider providing runtime memory metrics when `MemoryPoolMXBean` is not available

### ISSUE THREAD

**Issue by sdeleuze** [micrometer-metrics/micrometer#3531]
As described in oracle/graal#4510 `MemoryPoolMXBean` is not available on native, and after discussing with the GraalVM team, there is not yet an ETA for this so it will likely be available long term but not short/middle term, and the lack of memory metrics on native is really annoying (CPU metrics are available BTW).

Could you consider adding memory metrics returned by `Runtime.getRuntime()` like `freeMemory`, `maxMemory` and `totalMemory` since they are available on native as a fallback when `MemoryPoolMXBean` is not available?

**Comment by shakuzen** [comment]
Sorry we didn't get to this, but in the meantime https://github.com/oracle/graal/issues/4510 has been resolved and will be in the upcoming GraalVM 23.0.0 release in April. I think we can consider this issue superseded by that. Let us know if you disagree and there's still a reason for us to do something in Micrometer.
