### ISSUE TITLE
Consider to add Observation.observe(Function<C extends Observation.Context, T> function)

### ISSUE THREAD

**Issue by artembilan** [micrometer-metrics/micrometer#3537]
I have a use-case where I need to do `ResponseContext.setResponse()` after performing request-reply and withing an `Observation` scope.
So, to achieve that I have to do something like this:
```
		RequestReplyReceiverContext context = new MyCtx();

		return ObservationDoc.PROCESS.observation(this.observationConvention,
						DefaultConvention.INSTANCE,
						() -> context, this.observationRegistry)
				.observe(() -> {
					Message<?> reply = requestReply();
					context.setResponse(reply);
					return reply;
				});
```

This way I have to be sure about an `ObservationRegistry.NOOP` before calling this code.
With an `Observation.observe(Function<C extends Observation.Context, T> function)` API it would look like this:
```
		return ObservationDoc.PROCESS.observation(this.observationConvention,
						DefaultConvention.INSTANCE,
						() -> new MyCtx(), this.observationRegistry)
				.observe((context) -> {
					Message<?> reply = requestReply();
					context.setResponse(reply);
					return reply;
				});
```
and no any extra `if...else` around!

**Comment by ttddyy** [comment]
I experimented a little bit.

```java
default <C extends Context, T> T observe(Function<C, T> function) {
    start();
    try (Scope scope = openScope()) {
        return function.apply((C)getContext());
    }
    catch (Exception exception) {
        error(exception);
        throw exception;
    }
    finally {
        stop();
    }
}
```

One limitation of using this method is that the passed function's context object cannot infer the original Context class.

For example, 
```java
CustomContext context = new CustomContext();
AtomicReference<Context> contextHolder = new AtomicReference<>();
new SimpleObservation("service", registry, context).observe((ctx) -> {
  CustomContext customContext = (CustomContext) ctx;  // explicit cast needed
  return "foo";
});
```

In the lambda, explicit cast to `CustomContext` is required on the `ctx` variable.

On the other hand, you can pass a typed function variable
```java
Function<CustomContext, String> function = customContext -> {
    customContext.hello();
    return "bar";
};

new SimpleObservation("service", registry, context).observe(function);
```

or a method reference:
```java
new SimpleObservation("service", registry, context).observe(this::convert);


public String convert(CustomContext customContext) { ... }
```

If it is not a problem, I'll create a PR.

**Comment by artembilan** [comment]
Yeah... I see.
This is probably not possible with a generic argument on an `Observation` by itself to propagate the type down, like we have with Java `Stream` or Reactor `Flux`.

There is another workaround though: `.<CustomContext, String>observe((ctx) ->`.

Not sure if team is going to be OK with this anyway.

Thank you for looking into this!

**Comment by jonatan-ivanov** [comment]
I was thinking about this, and I think as of today, you can resolve this issue by holding a reference to the `Observation` not to the `Context`:

```java
Observation observation = Observation.createNotStarted("test", Observation.Context::new, observationRegistry);
        observation.observe(() -> System.out.println(observation.getContext()));
```

This way, even if a noop Observation is created, you don't need to do additional checks to prevent creating a context on your own. There is one drawback though: you need to cast since `getContext` returns `Context`.

**Comment by artembilan** [comment]
Yeah... Sure! Let's forget it then!
There are many other way to get access to what we need without burden for extra API support which in the end cannot so the problem for a fluent type inference.

**Comment by jonatan-ivanov** [comment]
I think @ttddyy's PR still makes sense (if nothing else, it lets you use the API fluently which is nice), I just wanted to see if this workaround could work for you.

**Comment by artembilan** [comment]
Well, my current workaround is like this:
```
			if (!ObservationRegistry.NOOP.equals(this.observationRegistry)) {
				replyMessage = sendAndReceiveWithObservation(channel, object, requestMessage);
			}
```
So, no worries from your side!
