### ISSUE TITLE
Why does @Timed publish avg, max, sum metrics? Why not just one value?

### ISSUE THREAD

**Issue by aaravmer** [micrometer-metrics/micrometer#3545]
Question:

I have already gone through [this](https://github.com/micrometer-metrics/micrometer/issues/1838) but couldn't get the answer. 

Let's say I want to plot avg, max, p99, p95, p90 of function time taken values on grafana.

To achieve this I have to do: 
`@Timed(value = "Client", percentiles = {0.90, 0.95, 0.99})`

But why do I need to send all these metrics? All I need is just one value which is time taken by that function (which is not being sent). Then I can apply avg, max, p99, p95, p90 on grafana.

Is there a way to send just only one value?

**Comment by jonatan-ivanov** [comment]
Metrics are aggregated values in time, not raw data. Metrics backends are usually not accepting raw data but aggregated values.

It is possible to implement your own meter registry with a Timer that publishes every "value" (recorded raw data) but it is likely that you metrics backend will not be able to anything with it. If you want to publish non-aggregated data, you might want to use logging or distributed tracing.
