### ISSUE TITLE
PortUnreachableException when application is shutting down

### ISSUE THREAD

**Issue by slingala-scout24** [micrometer-metrics/micrometer#3554]
**Describe the bug**
We use micrometer to log metrics in our spring boot application. When our application shuts down, our logs get polluted with the below warning logs, and exception. This happens only during application shutdown, and not during startup or during the usual application runtime.

> An exception has been observed post termination
> 
> java.net.PortUnreachableException: recvAddress(..) failed: Connection refused
> 	at io.micrometer.shaded.io.netty.channel.epoll.EpollDatagramChannel.translateForConnected(EpollDatagramChannel.java:605)
> 	at io.micrometer.shaded.io.netty.channel.epoll.EpollDatagramChannel.access$600(EpollDatagramChannel.java:55)
> 	at io.micrometer.shaded.io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:533)
> 	at io.micrometer.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
> 	at io.micrometer.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
> 	at io.micrometer.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
> 	at io.micrometer.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.micrometer.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: io.micrometer.shaded.io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection refused

**Environment**
 - Spring Boot v2.7.3
 - Micrometer version 1.10.2
 - OS: Linux
 - Java version: 11

**To Reproduce**
How to reproduce the bug:
Unfortunately, we cannot recreate this with a minimal sample. This issue happens only in our application, and I cannot extract a running demo out of it

**Expected behavior**
No warning logs are printed out during shutdown

**Comment by shakuzen** [comment]
How is your statsd daemon deployed? Is it possible that is shutting down before the application shuts down?

**Comment by shakuzen** [comment]
Closing due to lack of response. We can reopen if we get the requested info.
