### ISSUE TITLE
Add the possibility to give an order for ObservedAspect

### ISSUE THREAD

**Issue by julien92** [micrometer-metrics/micrometer#3575]
When I used the `@Observed` annotation with another one like `@MyCustomAspect,` I observed that the ObservedAspect is always lastely excuted :

See AspectJAwareAdvisorAutoProxyCreator#sortAdvisors()

Could we have an abastract class for Extends ObservedAspect and put my own orders.
with Spring annotation `@Order`

**Comment by marcingrzejszczak** [comment]
This class has nothing to do with Spring. Why should it implement a Spring interface?

**Comment by julien92** [comment]
No need to implements a Spring interface but if we have an abstract class then we can extends the class and we Can add a custom order. Actually the aspect Can t be ordered with another aspect using Spring aop

**Comment by julien92** [comment]
` @Observed(name = task, lowCardinalityKeyValues = {name,
      "task1"})
  @MyCustomAnnotation
  public void runTask() {
          .........
  }`
  
  `@MyCustomAnnotation` is used by a CustomAspect, i would like to have the possibility to run my aspect before `ObservedAspect`,
  
  If there is an AbstractObservedAspect i could implements my own aspect and specfic the order for execute `@ObservedAspect` before `@MyCustomAspect`
  
  I know it's a limitation from Spring-AOP but i thought you were spring friendly :)

**Comment by julien92** [comment]
I found a solution, i create a proxy class and its this one i put on the spring context

`@Aspect
@Component
@Slf4j
@Order(Ordered.HIGHEST_PRECEDENCE)
public class OrderedObservedAspect {

  private final ObservedAspect observedAspect;

  @Autowired
  public OrderedObservedAspect(ObservationRegistry registry) {
    this.observedAspect = new ObservedAspect(registry);
  }

  @Around("@within(io.micrometer.observation.annotation.Observed)")
  @Nullable
  public Object observeClass(ProceedingJoinPoint pjp) throws Throwable {
    return observedAspect.observeClass(pjp);
  }

  @Around("execution (@io.micrometer.observation.annotation.Observed * *.*(..))")
  @Nullable
  public Object observeMethod(ProceedingJoinPoint pjp) throws Throwable {
    return observedAspect.observeMethod(pjp);
  }
}
`

**Comment by jonatan-ivanov** [comment]
You can extend `ObservedAspect` without it being declared as an abstract class.
Also, that class should be non-abstract since users needs instances of it (w/o extending it).

**Comment by julien92** [comment]
If you extend `ObsverdedAspect` you cannot use it in Spring aop because Spring didnt allow it

**Comment by julien92** [comment]
Observation API is very powerful,
Unfortunately when we used `@ObservedAspect` and one `CustomAspect` aspect for add logging mechanism for a method, Aspect order execution is very important because i want to have my logs with tracing context (spanId and traceId).

**Comment by julien92** [comment]
@izeye yes that's is exactly my point.

@Observed aspect need to have the highest the precedence and need to be executed first,
because i use micrometer-tracing lib, and i want to have traceId and spanId with my logs added by my `@LogCustomAspect`

**Comment by marcingrzejszczak** [comment]
So maybe you can file an issue in Spring Framework about this with a general question on how to work with ordering of aspects?

**Comment by shakuzen** [comment]
I'm not sure what, if anything, we should do in Micrometer. We could make the abstract base class, but we haven't done that with any of our other aspects. I understand the special circumstance here is wanting the tracing context to be available. I see you found a workaround by wrapping the aspect and delegating. Another option to consider is converting your logging aspect to an `ObservationHandler` that runs after any tracing-related handlers, if that would work for your use case.

**Comment by julien92** [comment]
@shakuzen I thought of this solution but I prefer to keep observation to only make observation and not introduce transverse behaviors like locking or logging to an ObservationHandler.

**Comment by izeye** [comment]
This seems to be superseded by https://github.com/spring-projects/spring-framework/issues/29830.
