### ISSUE TITLE
expected equal, got \"INVALID\" error message with springboot MeterRegistryCustomizer in lambda function

### ISSUE THREAD

**Issue by senocak** [micrometer-metrics/micrometer#3597]
**Describe the bug**
I am customizing the metrics with prefix, I am getting following error log in prometheus ui with lambda function;
"expected equal, got \"INVALID\""

lambda function;
```
@Bean
    MeterRegistryCustomizer<MeterRegistry> configurer() {
        return (registry) -> registry.config().namingConvention(
            (NamingConvention) (name, type, baseUnit) -> "lorem_" + Arrays.stream(name.split("\\."))
                .filter(Objects::nonNull)
                .collect(Collectors.joining("_")));
    }
```

But when i refactor the bean with following one, it works ok;
```
@Bean
    MeterRegistryCustomizer<MeterRegistry> configurer() {
        NamingConvention convention = new NamingConvention() {
            @Override
            public String name(String name, Meter.Type type, @Nullable String baseUnit) {
                return toConvert(name);
            }

            @Override
            public String tagKey(String name) {
                return toConvert(name);
            }

            private String toConvert(String name) {
                return "lorem_" + Arrays.stream(name.split("\\.")).filter(Objects::nonNull)
                        .collect(Collectors.joining("_"));
            }
        };
        return (registry) -> registry.config().namingConvention(convention);
    }
```
**Environment**

 - Micrometer version [e.g. 1.7.1]: 1.9.5
 - Micrometer registry [e.g. prometheus] prometheus: version 2.41.0
 - OS: [e.g. macOS]: macOS monterey: v12.5.1
 - Java version: [e.g. output of `java -version`] jdk1.8.0_202
 - SpringBoot: 2.7.5

**To Reproduce**
How to reproduce the bug:

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g. related issues.

**Comment by shakuzen** [comment]
I don't know why you are getting that exception. I did not get that exception when I tried providing that same customizer in a sample application. I do not know what is the difference between your sample application and mine. In general, though, if your goal is to prefix all meter names with something, you would be better off using a `MeterFilter` like the following. Overriding the naming convention entirely for any MeterRegistry type may cause unexpected issues. The `PrometheusNamingConvention` does more than just convert dots to underscores like your replacement naming convention does.

```java
@Bean
MeterFilter prefixMeterFilter() {
    return new MeterFilter() {
        @Override
        public Meter.Id map(Meter.Id id) {
            return id.withName("lorem." + id.getName());
        }
    };
}
```

Hopefully that answer allows you to resolve your issue. Let us know if not and we can reopen if there is a bug in Micrometer.

**Comment by senocak** [comment]
Hi @shakuzen,
the block you shared is working but the one i shared it is in our production code, so before using your suggestion, i need to know why it is not working in the first place.
Thanks you

**Comment by shakuzen** [comment]
I can't reproduce the error you've described. In order for us to investigate it further, please provide a minimal sample project and instructions that reproduces the error.

**Comment by senocak** [comment]
@shakuzen Okay i just made a sample springboot project with minimal dependencies and i am getting the same problem, I put prometheus.yml and docker-compose.yml so you can reproduce it right away.
[sampleSpringBoot.zip](https://github.com/micrometer-metrics/micrometer/files/10477915/loremCopy.zip)
Thank you.

**Comment by senocak** [comment]
@shakuzen any update for me please?

**Comment by shakuzen** [comment]
The reason ultimately comes down to what I explained before:
> Overriding the naming convention entirely for any `MeterRegistry` type may cause unexpected issues. The `PrometheusNamingConvention` does more than just convert dots to underscores like your replacement naming convention does.

In the case of using the lambda, you are only overriding the `name` method of `NamingConvention`, deferring to the default `tagKey` and `tagValue` implementations. Hence you end up with a Prometheus output with the following line:
```
lorem_application_started_time{main.application.class="com.AppStarter",} 1.001
```
This is not valid Prometheus scrape format. The tag key (label name) does not get converted properly. It should be
```
lorem_application_started_time_seconds{main_application_class="com.AppStarter",} 1.022
```

Again, for the use case you have described (adding a prefix), there is no good reason to make a custom `NamingConvention`. You should use a `MeterFilter` instead. If you insist on continuing to make a custom `NamingConvetion`, you should look at the implementation of `PrometheusNamingConvention` to see what we are doing to produce valid and idiomatic Prometheus scrape format.

**Comment by senocak** [comment]
@shakuzen that is nice, i will use your way to add prefix but it is ok when i downgrade the springboot version: 2.3.3.RELEASE

```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.3.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```

**Comment by shakuzen** [comment]
In case you weren't aware, Spring Boot 2.3.x is an end of life, unsupported line now. I would advise upgrading to a supported version. See https://spring.io/projects/spring-boot#support

**Comment by senocak** [comment]
@shakuzen yes, thats the main reason why we upgrade the spring boot version, After upgrade, we got that problem. What i am trying to understand is that there is no problem with 2.3.x version but why we are having problem with the newer versions. (I got the same problem with 2.6.2 i guess)
