### ISSUE TITLE
TestObservationRegistry does not have any parent/child propagation

### ISSUE THREAD

**Issue by braunsonm** [micrometer-metrics/micrometer#3602]
**Describe the bug**
In unit tests I would like to make sure that a parent observation is set in the child. Typically I'm used to micrometer having a handler that does this automatically for me when, probably using the TreadContext. In test cases you can't expect the same behaviour. Is there a handle that should be registered manually when testing propagation in test cases?

**To Reproduce**
```java
@Test
void parentObservation() {
  var observationRegistry = TestObservationRegistry.create();
  Observation.createNotStarted("parent", observationRegistry).start();
  Observation.createNotStarted("child", observationRegistry).observe(() -> System.out.println("Testing"));
  TestObservationRegistryAssert.assertThat(observationRegistry)
    .doesNotHaveAnyRemainingCurrentObservation()
    .hasObservationWithNameEqualTo("child")
    .that()
    // This fails the assertion
    .hasParentObservation();
}
```

**Expected behavior**
Parent observations propagate to the child automatically.

**Additional context**
It's entirely possible I'm missing something here, I'm pretty new to the Observation API. I am aware that I can manually set the parent on the child, but in this case I'm calling code that creates the child which I cannot modify.

**Comment by shakuzen** [comment]
> Is there a handle that should be registered manually when testing propagation in test cases?

It depends on what the test is doing. You would need to register a handler if you want to test the behavior that depends on that handler.



> I am aware that I can manually set the parent on the child, but in this case I'm calling code that creates the child which I cannot modify.

If you want the parent to be set automatically, you should use the `Scope` API. If I modify your test to the following, the assertion passes. This should work for the case where third-party code is run.

```java
@Test
void parentObservation() {
    var observationRegistry = TestObservationRegistry.create();
    Observation parent = Observation.createNotStarted("parent", observationRegistry).start();
    try (Observation.Scope scope = parent.openScope()) {
        Observation.createNotStarted("child", observationRegistry).observe(() -> System.out.println("Testing"));
    }
    TestObservationRegistryAssert.assertThat(observationRegistry)
        .doesNotHaveAnyRemainingCurrentObservation()
        .hasObservationWithNameEqualTo("child")
        .that()
        .hasParentObservation();
}
```

I think this answers your question. Let us know if anything is still unclear or you think there's still an issue.
