### ISSUE TITLE
micrometer-registry-elastic + Spring Webflux (reactor/reactive application): Blocking http request to send metrics to Elastic

### ISSUE THREAD

**Issue by patpatpat123** [micrometer-metrics/micrometer#3606]
**Describe the bug**
micrometer-registry-elastic is sending metrics to Elastic in a blocking way. If the web application is a reactive application (Spring Webflux, having ```management.metrics.export.elastic.enabled=true``` brings performance degradation.

**Environment**
Java 17 + SpringBoot 3 + micrometer registry 1.10.2 (which comes with SpringBoot)

**To Reproduce**
```
package sk.balaz.springbootlogging;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.ArrayList;
import java.util.List;

@RestController
@SpringBootApplication
public class SpringBootLoggingApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringBootLoggingApplication.class, args);
    }

    private static final Logger logger = LoggerFactory.getLogger(SpringBootLoggingApplication.class);

    private static final List<Employee> DB = new ArrayList<>();
    static {
        DB.add(new Employee("1", "Frodo", "ring bearer"));
        DB.add(new Employee("2", "Bilbo", "burglar"));
    }

    @GetMapping("/api/employees")
    Flux<Employee> all() {
        logger.info("Look, there is a trace ID here with spring-boot-starter-web, but not with spring-boot-starter-webflux. Micrometer is not able to propagate traces");
        return Flux.fromIterable(DB);
    }

    @GetMapping("/api/employees/{id}")
    Mono<Employee> one(@PathVariable String id) {
        logger.info("Look, there is a trace ID here with spring-boot-starter-web, but not with spring-boot-starter-webflux" + id);
        return Mono.just(DB.stream().filter(employee -> employee.id().equals(id)).findFirst().orElseThrow(() -> new RuntimeException("Couldn't find " + id)));
    }

    public record Employee(String id, String aaa, String bbb) {
    }

}
```

```
spring.application.name=Baeldung SleuthBug Tutorial
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
debug=true
server.port=9090
management.endpoints.web.exposure.include=*
management.metrics.export.elastic.host=https://127.0.0.1:8086
management.metrics.export.elastic.enabled=true
```

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>sk.balaz</groupId>
    <artifactId>spring-boot-logging</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>spring-boot-logging</name>
    <description>spring-boot-logging</description>
    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-elastic</artifactId>
        </dependency>
        <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-tracing-bridge-brave</artifactId>
    </dependency>
    <dependency>
        <groupId>io.zipkin.reporter2</groupId>
        <artifactId>zipkin-reporter-brave</artifactId>
    </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

```

**Expected behavior**
The micrometer registry, when running inside a reactive application, should not perform any blocking operation, as it will degrade the main event loop of Reactor.

**Actual behavior**
When the registry is removed, the web application is performing without any issue. With the registry active, every one minute (default time of the registry to send to Elastic, there is a performance drop

**Additional context**
This is even more observable when the machine has fewer CPU. For instance, running in a single CPU or 2 CPU host, while the reactive application has no registry, the event loop can fully leverage the reactor core.

But with the registry, and fewer reactor core, the performance degradation is very noticeable.

Can you please help provide a Spring Webflux WebClient instead of your http client, or a reactive version of the registry please?
Also, your httpclient does not support TLS/SSL. Most of the registries destination, even just used for metrics, are usually secured

Thank you

**Comment by shakuzen** [comment]
> The micrometer registry, when running inside a reactive application, should not perform any blocking operation, as it will degrade the main event loop of Reactor.

Reactor threads should not be blocked in a Reactor application, but metrics publishing is done on a separate thread pool that has no direct effect on the Reactor threads. Instrumentation should not block. If the application is running in a resource constrained environment, then there can be an indirect effect because ultimately they are sharing the same CPU resources.

We can try to look into this, but from what you've shared, I don't see why there would be a problem with publishing on a separate thread pool in such an application.

> Also, your httpclient does not support TLS/SSL.

Please open a separate issue with a minimal sample to reproduce the issue.

**Comment by patpatpat123** [comment]
Hello @shakuzen ,

This is a very clear explanation. I am going to use some profilers in order to gather some more metrics and data and revert back if I can find more concrete evidence.
