### ISSUE TITLE
Support for @Timed in any Spring-managed bean

### ISSUE THREAD

**Issue by szpak** [micrometer-metrics/micrometer#361]
[As of v1.0.0-rc.7](https://github.com/micrometer-metrics/micrometer/issues/24#issuecomment-304378205) `@Timed` put on a method of an arbitrary Spring-managed bean is silently ignored. It would be useful to be able to generate metrics for any kind of beans (e.g. `Service`s with non-`RestTemplate` remote system calls) without writing a custom AOP logic.

**Comment by elenigen** [comment]
Is this feature is planned to be part of Milestone 1.0.0?

**Comment by jkschneider** [comment]
@elenigen I think it won't be autoconfigured in Boot 2. The Boot team is getting pretty firm on no new features. So maybe autoconfigured in Boot 2.1?

There is an open PR with an AspectJ aspect (#395). We could maybe include such an aspect in `micrometer-core` and leave the config to you, but it seems that a `BeanPostProcessor` could proxy any class with `@Timed` and not require AOP. There is some precedent for this  (`org.springframework.cache.annotation.Cacheable`).

**Comment by elenigen** [comment]
I just feel, the annotation is much less intrusive, since the metrics are not really part of the method logic itself, it's something external to monitor the method, so I was hoping if we could avoid AOP and still get this feature working, it would be the ideal solution, especially since you are saying it's feasible (`Cacheable`).

**Comment by davidkarlsen** [comment]
I can have a stab at it. It's just a lot more code without Aspectj

**Comment by jkschneider** [comment]
The `TimedAspect` aspect now exists in `micrometer-core`, but will _not_ be autoconfigured in Spring Boot 2 or `micrometer-spring-legacy`. We can revisit application of `@Timed` via AOP or a BPP in Boot 2.1, depending on how the community reacts to the feature.

To configure manually:

```
@Bean
TimedAspect timedAspect(MeterRegistry registry) {
   return new TimedAspect(registry);
}
```

**Comment by NadirJ** [comment]
Hi @jkschneider , I know TimedAspect is new, but I can't get it work in my spring boot app. I'm using the @Timed annotation on  public method in a Spring "@Service" class and the aspect isn't hit. Note I copied configuration class above.

**Comment by ben-manes** [comment]
Is there a reason why AspectJ was used instead of AOP Alliance? Both are supported by Spring, but only AOP Alliance is by Guice. Spring Transactions uses AOP Alliance (`TransactionInterceptor`), making it easy to leverage in Guice w/o Spring IoC.
