### ISSUE TITLE
mongodb.driver.pool.waitqueuesize is a negative number

### ISSUE THREAD

**Issue by buqq2015** [micrometer-metrics/micrometer#3618]
There is  a problem with the field “waitQueueSizes” of MongoMetricsConnectionPoolListener
The method "connectionCheckedOut" And "connectionCheckOutFailed" use waitQueueSize.decrementAndGet()
not judge with 0

**Comment by shakuzen** [comment]
Do you know in what situation this is happening? It seems like logically it should not happen, or we're missing some case in how we've implemented the listener.

**Comment by buqq2015** [comment]
In DefaultConnectionPool.java class
set the connectionPoolListener is ConnectionPoolListenerMulticaster(has two item JMXConnectionPoolListener and MongoMetricsConnectionPoolListener)
when invoke the method get(final long timeout, final TimeUnit timeUnit),
you will find  connectionPoolListener.connectionCheckOutStarted can not set waitQueueSizes, but connectionCheckOutFailed can set waitQueueSizes. It will make waitqueuesize to a negative number.

**Comment by buqq2015** [comment]
e ,mongodb fix this problem in https://jira.mongodb.org/browse/JAVA-4015

**Comment by shakuzen** [comment]
Thank you for the explanation and linking to the issue in the Mongodb driver. Would you be interested in contributing a pull request to fix it to the `1.9.x` branch?

**Comment by aditya-32** [comment]
Hi @shakuzen  i would like to contribute can you explain a bit more about the issue

**Comment by shakuzen** [comment]
Looking at the past comments and linked issue again, it seems I have probably misunderstood. It doesn't seem like there is anything to fix in Micrometer as the fix has been done on the Mongo driver side. I'll close for now and we can reopen if there is still something to fix in Micrometer.
Thank you anyway for the offer to help @aditya-32.
