### ISSUE TITLE
Getting Weird response in Spring boot java application when using @Timed

### ISSUE THREAD

**Issue by pvillikal** [micrometer-metrics/micrometer#3621]
When using @timed annotation in the controller for our application, we are getting 200ok for all the API hits. Even for the failure scenarios, we are getting 200 OK with empty Response and this function will call external calls ( using the rest template). We are using spring-boot version 2.7.0 and micrometer version 1.10.3. Tried upgrading the spring-boot version to 2.7.7, but getting the same issue. Also tried using a different lower version of micrometer, which also didn't solve the issue. We have also tried creating an interface like abcTimed and using it instead of @Timed. which also didn't solve the issue.
Removing @Timed annotation will fix this issue. But we need this annotation for creating the latency metrics in datadog. Can anyone please help with this issue. 
<img width="1255" alt="Screenshot 2023-02-07 at 12 40 39 PM" src="https://user-images.githubusercontent.com/124661314/217182936-9a14cbfe-4425-4ec3-be5d-270267d1c4c9.png">

**Comment by shakuzen** [comment]
You should typically let the version of micrometer dependencies be managed by Spring Boot's [dependency management](https://docs.spring.io/spring-boot/docs/2.7.x/reference/htmlsingle/#using.build-systems.dependency-management), to ensure compatibility with Spring Boot. Can you reproduce the issue in a minimal sample app that uses the latest patch version of a [supported Spring Boot version](https://spring.io/projects/spring-boot#support) (e.g. 2.7.8 or 3.0.2)? If so, please share such a project.

> But we need this annotation for creating the latency metrics in datadog.

Would you please elaborate on this? Controller endpoints [are timed](https://docs.spring.io/spring-boot/docs/2.7.x/reference/htmlsingle/#actuator.metrics.supported.spring-mvc) with a Micrometer `Timer` in Spring Boot apps when Micrometer auto-configuration is enabled, even if you don't use an `@Timed` annotation on the Controller method.

**Comment by pvillikal** [comment]
> You should typically let the version of micrometer dependencies be managed by Spring Boot's [dependency management](https://docs.spring.io/spring-boot/docs/2.7.x/reference/htmlsingle/#using.build-systems.dependency-management), to ensure compatibility with Spring Boot.

Does this mean not to give any version while giving the dependency of micrometer. I didn't get that can you please tell me about that

**Comment by pvillikal** [comment]
> Can you reproduce the issue in a minimal sample app that uses the latest patch version of a [supported Spring Boot version](https://spring.io/projects/spring-boot#support) (e.g. 2.7.8 or 3.0.2)? If so, please share such a project.


Actually I am not sure how to reproduce the issue. I have implemented the same micrometer dependency and the @Timed annotation in 4 applications. Where I am only facing issue with one of the application. So even if we create a sample project, not sure how to reproduce the issue.


> Would you please elaborate on this? Controller endpoints [are timed](https://docs.spring.io/spring-boot/docs/2.7.x/reference/htmlsingle/#actuator.metrics.supported.spring-mvc) with a Micrometer `Timer` in Spring Boot apps when Micrometer auto-configuration is enabled, even if you don't use an `@Timed` annotation on the Controller method.

Yes we are using an interface, for eg ABCTimed and using that interface as an annotation in controller(@ABCTimed(name = "first")). So that we can get the average latency time of each api in datadog using the name given in @ABCTimed in the controller.
Giving few sample code here, so that it might help you to understand more on the issue
ABCTimed.java
`@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface ABCTimed {
    String name() default "";
    String partnerName() default "";

}`

example controller class
`@RequestMapping(value = "/abc", method = RequestMethod.GET)
@ABCTimed(name = "first")
public ResponseEntity<Object> getAbc(@RequestHeader Map<String, String> requestHeaders){
   return abc
}`

MetricsTimerAspect.java
`@Aspect
@Component
public class MetricsTimerAspect {
    @Autowired
    private MeterRegistry meterRegistry;

    /**
     * Aop around advice ,record the method invoke time.
     *
     * @param jp The offer id
     * @param aBCTimed The token which was generated from the previous call.
     * @throws Throwable exception.
     * @return The translated offers response.
     */
    @Around(value = "@annotation(aBCTimed)")
    public Object around(ProceedingJoinPoint jp, ABCTimed aBCTimed) {
        io.micrometer.core.instrument.Timer timer;
        Instant start;
        timer = io.micrometer.core.instrument.Timer.builder(
                DataDogUtils.buildMetricName(aBCTimed.name())).
                tags(DataDogUtils.buildDataDogTags(aBCTimed.partnerName())).
                publishPercentiles(0.95, 0.999).
                register(meterRegistry);

        start = Instant.now();
        try {
            try {
                return jp.proceed();
            } catch (Throwable throwable) {
                throwable.printStackTrace();
            }
        } finally {
            timer.record(Duration.between(start, Instant.now()).toMillis(), TimeUnit.MILLISECONDS);
        }
        return null;
    }
}`

**Comment by jonatan-ivanov** [comment]
>Does this mean not to give any version while giving the dependency of micrometer. I didn't get that can you please tell me about that

Yes, please do not set the version number for your dependencies and let the Spring Boot BOM control them.

In your `@Aspect` you are swallowing the exception, please check `@Timed` how to do it properly. Based on this, let me close the issue, please let us know if I misunderstood it and you want us to reopen.

**Comment by shakuzen** [comment]
> Does this mean not to give any version while giving the dependency of micrometer. I didn't get that can you please tell me about that

Please read through the documentation that I linked. There are links there for Gradle and Maven that will explain how to use Spring Boot's dependency management so that you do not need to specify dependency versions that it manages.

> Giving few sample code here, so that it might help you to understand more on the issue

Looking at what you are doing there, you probably do not need to register an aspect at all. Spring Boot's [built-in support for `@Timed`](https://docs.spring.io/spring-boot/docs/2.7.x/reference/htmlsingle/#actuator.metrics.supported.timed-annotation) allows you to customize the Timer name without an aspect. If you are registering an Aspect, it is possible that both Spring Boot's native support for timing controller endpoints AND the aspect-based instrumentation are being applied. In general, you do not want the same thing to be instrumented twice. Using an aspect should be reserved for cases where you cannot achieve the customization you want with the features Spring Boot offers - please read the documentation to understand what you can customize.

It hasn't been clear what exactly you want to customize from the out-of-the-box instrumentation provided by Spring Boot. Perhaps we could help you achieve that in the best way possible rather than trying to diagnose the symptoms of the implementation you've done that maybe you didn't need to do.

**Comment by pvillikal** [comment]
> In your `@Aspect` you are swallowing the exception so the call will never fail, please check `TimedAspect` how to do it properly. Based on this, let me close the issue, please let us know if I misunderstood it and you want us to reopen.

Yes, this was the issue. We have changed the code for MetricsTimerAspect.java to this(removed the catch block and added throws to the method) and the issue got fixed.
`@Aspect
@Component
public class MetricsTimerAspect {
    @Autowired
    private MeterRegistry meterRegistry;
    /**
     * Aop around advice ,record the method invoke time.
     *
     * @param jp The offer id
     * @param aBCTimed The token which was generated from the previous call.
     * @throws Throwable exception.
     * @return The translated offers response.
     */
    @Around(value = "@annotation(aBCTimed)")
    public Object around(ProceedingJoinPoint jp, ABCTimed aBCTimed) throws Throwable{
        io.micrometer.core.instrument.Timer timer;
        Instant start;
        timer = io.micrometer.core.instrument.Timer.builder(
                DataDogUtils.buildMetricName(aBCTimed.name())).
                tags(DataDogUtils.buildDataDogTags(aBCTimed.partnerName())).
                publishPercentiles(0.95, 0.999).
                register(meterRegistry);

        start = Instant.now();
       try {
            return jp.proceed();
        } finally {
            timer.record(Duration.between(start, Instant.now()).toMillis(), TimeUnit.MILLISECONDS);
        }
        return null;
    }
}`

Thank you for providing a quick reply and helping.
