### ISSUE TITLE
Can we convert prometheus metrics to micrometer instance like counter, gauge?

### ISSUE THREAD

**Issue by Lunaticf** [micrometer-metrics/micrometer#3628]
Is there any method that can convert this text to micrometer object? Thanks
```
# HELP nv_gpu_power_limit GPU power management limit in watts
# TYPE nv_gpu_power_limit gauge
nv_gpu_power_limit{gpu_uuid="GPU-8de0ce2b-e1ef-0322-4ed3-1eb9c9bc2851"} 70.000000
# HELP nv_energy_consumption GPU energy consumption in joules since the Triton Server started
# TYPE nv_energy_consumption counter
nv_energy_consumption{gpu_uuid="GPU-8de0ce2b-e1ef-0322-4ed3-1eb9c9bc2851"} 197648.840000
```

**Comment by jonatan-ivanov** [comment]
Please do not cross-post, I answered your question on Slack:

>Please don’t do this. Neither Micrometer nor any metrics library is good for this.
>There are tools to convert metrics from one format to another:
> - [Telegraf](https://docs.influxdata.com/telegraf/v1.25/plugins/)
> - [OTel Collector](https://opentelemetry.io/docs/collector/)
>
>Though I would challenge why that service must use Prometheus and can’t publish metrics in other formats?
