### ISSUE TITLE
"jvm.threads.states" reports stale data

### ISSUE THREAD

**Issue by lenin-jaganathan** [micrometer-metrics/micrometer#3658]
**Describe the bug**
This [PR](https://github.com/micrometer-metrics/micrometer/pull/3651) aims at optimizing the calls to ThreadMxBean. But it ultimately makes the "jvm.threads.states" metric stale I,e this metric will always report the thread count when the class was initialized.

**Environment**
NA

**To Reproduce**
Start any application with the latest micrometer-core. Place the below piece of code which just creates threads that does nothing,
```
Executors.newSingleThreadScheduledExecutor().scheduleAtFixedRate(() -> {
            new Thread(() -> {
                while (true) {
                    System.out.println("Printing");
                    try {
                        Thread.sleep(5000);
                    } catch (InterruptedException e) {
                        throw new RuntimeException(e);
                    }
                }
            }).start();
        }, 5, 5, TimeUnit.SECONDS);
new JvmThreadMetrics().bindTo(registry);
```

Export the metrics to any back-end and we will see that jvm.threads.states metric will never report any change. We can also clearly see that "jvm.threads.live" increasing which proves that there are additional threads.

**Expected behavior**
jvm.threads.states - should report the thread states at any particular point in time.

**Additional context**
This is because the logic to query the thread states was moved from Gague's Supplier to JvmThreadMetrics initialization phase. This takes the snapshot during app start time and puts it in a map that never gets updated. 

if we really see performance issues with querying the ThreadMxBean.getAllThreadIds() probably, we can query it once and use something like a countdown latch to minimize the function call and re-computation every time.
```
private volatile CountDownLatch countDownLatch = new CountDownLatch(0);
private final Map<Thread.State, Integer> threadStateCountMap = new EnumMap<>(Thread.State.class);

long getCountForThreadState(ThreadMXBean threadBean, Thread.State state) {
        this.collectThreadStateCountIfNecessary(threadBean);
        countDownLatch.countDown();
        return threadStateCountMap.get(state);
    }

private synchronized void collectThreadStateCountIfNecessary(ThreadMXBean threadMXBean) {
        if (countDownLatch.getCount() == 0) {
            Arrays.stream(Thread.State.values()).forEach(state -> threadStateCountMap.put(state, 0));

            long[] allThreadIds = threadMXBean.getAllThreadIds();
            Arrays.stream(threadMXBean.getThreadInfo(allThreadIds))
                    .forEach(threadInfo -> threadStateCountMap.merge(threadInfo.getThreadState(), 1, Integer::sum));
            countDownLatch = new CountDownLatch(Thread.State.values().length);
        }
}
```

**Comment by asasas234** [comment]
Thank you very much, my bug, what you said is indeed correct, but I do not want to go through countDownLatch and synchronized way, let me think if there is a better way

**Comment by asasas234** [comment]
@lenin-jaganathan I have an idea, wait a moment, I will modify the self-test, and then re-introduce a PR, then please review with you again

**Comment by shakuzen** [comment]
Thank you both. We'll wait for the pull request and then decide what to do.

**Comment by izeye** [comment]
This doesn't seem to be a regression yet for users as 1.11.0-M2 which includes https://github.com/micrometer-metrics/micrometer/pull/3651 hasn't been shipped yet.

**Comment by jonatan-ivanov** [comment]
Thank you both: for reporting and for the PR!

@lenin-jaganathan I guess your `CountDownLatch` can be a simple `AtomicInteger` since you are not using `await`. Btw (unrelated), there is `CyclicBarrier` that is resettable and somewhat similar to `CountDownLatch`.
There is a bigger issue with this solution though (first, I was thinking about counting the number of queries too): if I write a `MeterFilter` that filters out one (or more) of the thread states, you will have less queries than states.

**Comment by shakuzen** [comment]
So that we don't release this as a bug in 1.11.0-M2, I'm going to revert #3651 for now. We will follow-up on an alternative implementation to optimize it.

Thank you @lenin-jaganathan for catching this before the release.
