### ISSUE TITLE
Property-based MeterFilters restructuring

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#366]
The property format should be restructured in a way that allows for property autocompletion/validation from the IDE.

**Comment by jkschneider** [comment]
There are bugs in both IntelliJ and Eclipse for `Map`-based `@ConfigurationProperties` fields whose values are of certain types. For our purpose, the following types of fields fail validation:

* `Map<String, Long[]>` in IntelliJ
* `Map<String, Duration>` in both IntelliJ and Eclipse
* `Map<String, Double[]>` in IntelliJ (almost certainly the same flaw as `Long[]` values

Here are the way those bugs present themselves:

![image](https://user-images.githubusercontent.com/1697736/35369916-44a86446-0150-11e8-9c5b-fcd41c591114.png)
(IntelliJ)

![image](https://user-images.githubusercontent.com/1697736/35369924-50ed554a-0150-11e8-9bdd-4e8152064dba.png)
(Eclipse)

**Comment by checketts** [comment]
Is the Duration validation problem due to the non-default duration format?

**Comment by jkschneider** [comment]
I think so? This may be fixed when we port it to 2.0 because they have built duration format parsing directly into the core. Not sure.
