### ISSUE TITLE
Logback events filtered at Appender still counted in LogbackMetrics

### ISSUE THREAD

**Issue by reneschroeder0000** [micrometer-metrics/micrometer#3667]
**Describe the bug**
I have a custom filter configured to filter some log events based by content. They are not shown in the output, but Micrometer is still counting them which makes Monitoring different from the actual output. 

**Environment**
 - Micrometer version: 1.9.7, 1.10.4
 - Micrometer registry prometheus
 - OS: macOS, Linux (Docker: eclipse-temurin:17-jdk-alpine)
 - Java version: 17

**To Reproduce**
Demo project: https://github.com/reneschroeder0000/logging-metrics-bug
1. Create custom filter
2. Log messages
3. Measure Logback Events counter

**Expected behavior**
Will only count output events

**Actual behavior**
Counts filtered events, too

**Additional context**
[Add any other context about the problem here, e.g. related issues.](https://stackoverflow.com/questions/75088934/spring-boot-actuator-logback-metric-with-custom-filter)

**Comment by izeye** [comment]
Loggers can have multiple appenders, and it's a filter for an appender, so I'm not sure how it can be considered unless the meters are per-appender.

**Comment by shakuzen** [comment]
That's a good point @izeye. It sounds like we should not consider this a bug and instead update the counter description and add JavaDocs to explain better what the metrics mean. We are instrumenting at the LoggerContext level, not at the appender level. Even if a log event if filtered for one appender, it may not be for another appender.
Any thoughts @reneschroeder0000?

**Comment by shakuzen** [comment]
I don't understand why the logs being from an external component matters. Could your filter be written as a `TurboFilter` instead of a `Filter`? If so, I think you could register it ahead of the `MetricsTurboFilter` that `LogbackMetrics` registers and get the result you want. That is, if you want the log events to be filtered from all appenders and not only a specific one.

**Comment by reneschroeder0000** [comment]
> I don't understand why the logs being from an external component matters. Could your filter be written as a `TurboFilter` instead of a `Filter`? If so, I think you could register it ahead of the `MetricsTurboFilter` that `LogbackMetrics` registers and get the result you want. That is, if you want the log events to be filtered from all appenders and not only a specific one.

Thanks, the `TurboFilter` solved my issue and also gave me more control.
