### ISSUE TITLE
Provide a simple way to make decisions based on the parent in ObservationPredicate

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#3678]
This issue was originally discussed in https://github.com/spring-projects/spring-boot/issues/34400
The scenario is the following: if Spring Security is used and users want to ignore `/actuator` endpoints, there is no easy way to do it today because Spring Security does not add details about the request. One potential solution would be checking the parent (root) Observation but it is not available through the context when the predicate is tested.

There is a [reproducer](https://github.com/spring-projects/spring-boot/issues/34400#issuecomment-1459658488) in the issue mentioned above.

Also see: https://github.com/spring-projects/spring-security/issues/12854

**Comment by braunsonm** [comment]
Thanks for opening this @jonatan-ivanov 
Can you clarify if the intention of this issue is to also have the parent set if the parent was ignored in a previous predicate?

ie:

```java
@Configuration
public class TestConfiguration {
    @Bean
    ObservationPredicate ignoreActuator() {
        return (s, context) -> ignoreActuatorRecursive(context);
    };

    public boolean ignoreActuatorRecursive(Observation.ContextView context) {
        if (context instanceof ServerRequestObservationContext serverRequestObservationContext) {
            HttpServletRequest carrier = serverRequestObservationContext.getCarrier();
            return !carrier.getServletPath().startsWith("/actuator"); // <----- Line (*)
        }

        if (context.getParentObservation() != null) {  // <-- Will the parent still be set if it was ignored in line (*)?
            return ignoreActuatorRecursive(context.getParentObservation().getContextView());
        }

        return true;
    }
}
```

It would be great for the parent to remain set even if the parent observation was ignored in a previous predicate. The reason being so that you can properly ignore any subsequent observations deriving from a root span that was ignored.

**Comment by jonatan-ivanov** [comment]
No, and there the parent can't be really set i these cases. If an Observation is ignored we will create a noop one that is hopefully eliminated by JIT.

**Comment by quaff** [comment]
@braunsonm `context.getParentObservation()` will always be null in `ObservationPredicate`, I'm trying to fix it by  https://github.com/micrometer-metrics/micrometer/pull/3867.
