### ISSUE TITLE
Prometheus histograms are not reported properly for numbers <1.0

### ISSUE THREAD

**Issue by yonatang** [micrometer-metrics/micrometer#3680]
**Describe the bug**

When creating a prometheus registry with histogram and SLOs <1.0, reported values are not counted properly. Full code is provided below in a gist link, but that's the meter definition:
```java
DistributionSummary.builder("latency")
  .serviceLevelObjectives(0.08, 0.09)
  .register(registry)
```

**Environment**

 - Micrometer version: 1.10.4
 - Micrometer registry: prometheus
 - OS: macOS
 - Java version: 11.0.6 Zulu11.37+17-NV (build 11.0.6+10-LTS)

**To Reproduce**
Please run the code here: https://gist.github.com/yonatang/377144253dbb5cba4f8dcbb134a31d2f

**Expected behavior**
Should output:
```
# HELP latency
# TYPE r histogram
latency_bucket{le="0.08",} 0.0
latency_bucket{le="0.09",} 1.0
latency_bucket{le="+Inf",} 1.0
latency_count 1.0
latency_sum 0.85
# HELP latency_max  
# TYPE latency_max gauge
latency_max 0.85
```

but instead the output is:
```
# HELP latency
# TYPE latency histogram
latency_bucket{le="0.08",} 0.0
latency_bucket{le="0.09",} 0.0
latency_bucket{le="+Inf",} 1.0
latency_count 1.0
latency_sum 0.85
# HELP latency_max  
# TYPE latency_max gauge
latency_max 0.85
```
(the `latency_bucket{le="0.09",}` dimension is 0.0 and not 1.0)

**Additional context**
If percentiles are reported, they are reported correctly. Additionally it works as expected with `SimpleMeterRegistry`.

**Comment by jonatan-ivanov** [comment]
But isn't `0.85 > 0.09`?
You should either record `0.085` or set your bucket to `0.9`.

Please let me kow if I'm missing something and you want me to reopen this issue.

**Comment by yonatang** [comment]
Hi @jonatan-ivanov, obviously you are right, 0.85>0.09, but it was a typo in the report and the gist (I originally tested the issue in Kotlin, and had a mistake when transformed it to Java - it was kinda late, sorry about that). 

We get the same result even when invoking `record(0.085)`, which is not expected. I revised the ticket and the gist accordingly.

**Comment by jonatan-ivanov** [comment]
I copied your updated code and I was able to reproduce the "issue".
So the "issue" is (I did not even notice this first) that 
>Micrometer’s preselected percentile histogram buckets are all integers from 1 to Long.MAX_VALUE

So if you want to use values < 1, you need to scale them up, see the docs: https://micrometer.io/docs/concepts#_scaling_and_histograms

```java
DistributionSummary summary = DistributionSummary.builder("not.latency")
    .serviceLevelObjectives(80, 90)
    .scale(1000)
    .register(registry);
summary.record(0.085);
```
You should get this:
```
# HELP not_latency  
# TYPE not_latency histogram
not_latency_bucket{le="80.0",} 0.0
not_latency_bucket{le="90.0",} 1.0
not_latency_bucket{le="+Inf",} 1.0
not_latency_count 1.0
not_latency_sum 85.0
# HELP not_latency_max  
# TYPE not_latency_max gauge
not_latency_max 85.0
```
Another "issue": please do not use `DistributionSummary` for measuring latency, Micrometer has a [`Timer`](https://micrometer.io/docs/concepts#_timers) component for this purpose:

With your example:
```java
public static void main(String[] args) {
    PrometheusMeterRegistry registry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);

    Timer timer = Timer.builder("latency")
        .serviceLevelObjectives(Duration.ofMillis(80), Duration.ofMillis(90))
        .register(registry);
    timer.record(Duration.ofMillis(85));

    System.out.println(registry.scrape());
}
```
You should get this:
```
# HELP latency_seconds_max  
# TYPE latency_seconds_max gauge
latency_seconds_max 0.085
# HELP latency_seconds  
# TYPE latency_seconds histogram
latency_seconds_bucket{le="0.08",} 0.0
latency_seconds_bucket{le="0.09",} 1.0
latency_seconds_bucket{le="+Inf",} 1.0
latency_seconds_count 1.0
latency_seconds_sum 0.085
```

or even better, you can record duration like this:
```java
Timer.Sample sample = Timer.start(registry);
// doSomething()
sample.stop(timer);
```
