### ISSUE TITLE
Upgrade Spring Cloud Sleuth to 3.1.7

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#3691]
Only samples are affected

**Comment by izeye** [comment]
Considering [its release notes](https://github.com/micrometer-metrics/micrometer/releases/tag/v1.9.9), it seems better to be labelled as `type: task` for internal dependency upgrades as it won't affect its release for users.

**Comment by jonatan-ivanov** [comment]
Thanks, I fixed it, I'm also removing it from the release notes.
