### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by BigBrokkokliMan** [micrometer-metrics/micrometer#3707]
Hello micrometer developers,

I think the Grafana-Dashboard for Micrometer ist out-of-date (https://grafana.com/grafana/dashboards/4701-jvm-micrometer/). The last update is from 2019-11-03. Not all metrics are visible in Grafana. Is it possible to provide an updated Grafana-Dashboard?

Some metrics-names changed. I discovered the following changes:

**Grafana Panel: Classloading -> Classes loaded**
- jvm_classes_loaded -> jvm_classes_loaded_classes

**Grafana Panel: Classloading -> Class load/unload rate (5m)**
- jvm_classes_unloaded_total -> jvm_classes_unloaded_classes_total

**Grafana Panel: JVM-Misc -> Threads**
- jvm_threads_live -> jvm_threads_live_threads
- jvm_threads_daemon -> jvm_threads_daemon_threads
- jvm_threads_peak -> jvm_threads_peak_threads
- process_threads -> ??? 

**Grafana Panel: JVM-Misc -> File Descriptors**
- process_open_fds -> ???
- process_max_fds -> ???
- process_files_open -> process_files_open_files
- process_files_max -> process_files_max_files

In the documentation (https://micrometer.io/docs/registry/prometheus) there is a broken link to this Grafana-Micrometer-Dashboard.
- Broken Link in Doku: https://grafana.com/dashboards/4701
- Correct Link: https://grafana.com/grafana/dashboards/4701-jvm-micrometer/

Many thanks in advance

**Comment by mweirauch** [comment]
That board was created by me. It's not officially affiliated with Micrometer.

Regarding missing metrics visualizations or technically broken queries: I tried to keep fallbacks in place, but haven't checked for a while. We are using this board in our company for a lot of services, and it works ok.

 Can you please give a hint which Micrometer version you are using?

**Comment by BigBrokkokliMan** [comment]
Hi mweirauch,

thank you for your response. We are using Micrometer 1.10.4 and 1.9.5.

Most of the dashboard is working correctly. So we can use the dashboard in our company too. But some metrics names (see above) have changed? 

I'm wondering, that there is no maintained grafana-dashboard. 

Many thanks in advance

**Comment by mweirauch** [comment]
Thanks for the reply. I will take care of the board which is long overdue anyway.

As there is no official support area for the board, but this project here is also not the correct place, I am fine if the Micrometer maintainers close this ticket as a non-issue/question. (I'd like to ask the allowance to give a little ping here when I updated the board, if that is ok.)

**Comment by BigBrokkokliMan** [comment]
That would be great. Thank you.
I am closing the ticket now.

**Comment by izeye** [comment]
> In the documentation (https://micrometer.io/docs/registry/prometheus) there is a broken link to this Grafana-Micrometer-Dashboard.
> 
> * Broken Link in Doku: https://grafana.com/dashboards/4701
> * Correct Link: https://grafana.com/grafana/dashboards/4701-jvm-micrometer/

@BigBrokkokliMan Thanks! I created https://github.com/micrometer-metrics/micrometer-docs/pull/293 to update it.

**Comment by shakuzen** [comment]
Thanks everyone for the responses so far. The Micrometer team would love to offer an official dashboard based on the metrics we provide as a starting point that users could customize to their needs. The problem is the maintenance burden of doing this for all of the different backends that we support and differences across versions. Each backend has its own query language and its own naming convention. Also, unless people would use the dashboard as-is without any customization, I'm not sure how they would be able to apply any updates made to an official dashboard to their own dashboard. I think this is a generally hard problem in the dashboard space.

**Comment by tomaaron** [comment]
@mweirauch thanks for the dashboard. Do you have a repository anywhere where we could collaborate and build on your effort? Currently the latest dashboard is using soon-to-be-deprecated graph viz.

**Comment by mweirauch** [comment]
@tomaaron Please file an issue or open a discussion over at <https://github.com/mweirauch/grafana-dashboards>.
