### ISSUE TITLE
Any plan for exposing property  for the OtelTracer to configure a custom receiver endpoint

### ISSUE THREAD

**Issue by sowndarya123** [micrometer-metrics/micrometer#3709]
Hi Team,

Iam using opentelemetry-exporter-otlp dependency  in my Spring boot 3.0 app to export my traces in OTLP format but found no property .
Please let me know if you already have a way where traces can be exported or if you have a development plan to do the same

**Comment by shakuzen** [comment]
This is not the right repository for this issue. It looks like there is already an open issue in Spring Boot for auto-configuration of that exporter - see https://github.com/spring-projects/spring-boot/issues/34390. There is an open pull request for this that also adds configuration properties support - see https://github.com/spring-projects/spring-boot/pull/34508.
