### ISSUE TITLE
Improve utility of Tags with additional methods

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#371]
cc / @philwebb

**Comment by philwebb** [comment]
Sketched code is [here](https://github.com/philwebb/micrometer/commit/ec527f007c8f1e5a26148ff72511c5fa44c2361e).

It would be very useful in code like [this](https://github.com/spring-projects/spring-boot/blob/62d9d0fd29a0519fddccb63d7c94d3fd5f83e7ca/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/cache/CacheMetricsRegistrar.java#L71) where we could change `bindCacheToRegistry` to call `getMeterBinder(cache, Tags.of(tags))` and `getMeterBinder` to use `tags.and(getAdditionalTags(cache))`.
