### ISSUE TITLE
PushMeterRegistry scheduled publish can collide with publish on close

### ISSUE THREAD

**Issue by lenin-jaganathan** [micrometer-metrics/micrometer#3711]
**Describe the bug**
[gh-3681](https://github.com/micrometer-metrics/micrometer/pull/3681) address the issue for Step Registries where data for the last incomplete step is incorrect. This fix should work fine for most of the cases yet it can suffer from some corner cases where `registry.close()` can be invoked while there was already a publish operation running from the ScheduleExecutor. This **might** result in inconsistent data being reported for both steps. 

So, there might be scenarios where data for a couple of steps might be inaccurate/ data loss.

**Environment**
 - Micrometer version - 1.11.0-M2
 - Micrometer registry - StepMeterRegistry

**To Reproduce**
How to reproduce the bug:
Scenario:
Assume that the step is 10 seconds and the application's graceful shutdown is initiated exactly or around 10th seconds. So, the scheduler would have already initiated the pushiSafely() and there are chances that close() is called around the same time. For a step meter, I believe there might be a scenario where manualRollover() will call sumThenReset() of StepValue and the pubishSafely initiated by Scheduler might call the rollCount(). This will again trigger a sumThenReset() which will make the data disappear or rest to zero.

**Expected behavior**
Duplicate publish should not be triggered and data reported for any step should not miss data points.

**Comment by lenin-jaganathan** [comment]
Haven't put much thought into this, but have some ideas that might prevent 2 publishes from being executed simultaneously.

See this code sample - https://github.com/micrometer-metrics/micrometer/compare/main...lenin-jaganathan:duplicate_publish?expand=1

**Comment by shakuzen** [comment]
I've got a test locally I can add for this (though there's an outstanding visibility issue with calling `publishSafely` in the test outside of the same package). Feel free to open your suggested code as a pull request.

**Comment by shakuzen** [comment]
The fix for this guards against publish being called on close if a scheduled publish is already happening. It does not consider if a manual call to `publish` is being called, however.
