### ISSUE TITLE
StepMeter's _manualRollover() causes data loss when called close to Step Boundary

### ISSUE THREAD

**Issue by lenin-jaganathan** [micrometer-metrics/micrometer#3720]
**Describe the bug**
[gh-3681](https://github.com/micrometer-metrics/micrometer/pull/3681) address the issue for Step Registries where data for the last incomplete step is incorrect. This fix should work fine for most of the cases yet it can suffer from some corner cases where manualRollover() is called close to step end and the during the course of the next publishing the meters roll over to the next step and report inaccurate data.

Especially, let's say the application shuts down closer to the end of the step which means, the next call to publish will call poll() and if the step has crossed we will roll over the data. Probably, we should have a signal like "stop Everything" sent to meters so that after manualRollover() (probably stopMeterRollover() is a better name?) no more rollover will happen based on clock time.

**Environment**
 - Micrometer version - 1.11.0-M2
 - Micrometer registry - StepMeterRegistry

**To Reproduce**
How to reproduce the bug:
[Here is the link to a gist](https://gist.github.com/lenin-jaganathan/c74bc01791c49fde6223a38155928c23) which captures the issue in a test for StepValue.

**Expected behavior**
After manulaRollover() is called, the meter should not reset values after a poll.

**Additional context**
- This issue was initially discussed in [gh-3714]( https://github.com/micrometer-metrics/micrometer/pull/3714)
- This bug was a side-effect of the fix for this issue - https://github.com/micrometer-metrics/micrometer/issues/1882

**Comment by shakuzen** [comment]
Thanks for all the feedback on this so quickly. It's great we can tackle these things before GA and end up with a better solution before it's perhaps more painful to change it. Thanks for the test case to reproduce the issue. I agree the naming of the method should change due to the behavior we want.
