### ISSUE TITLE
JMS coralationId autoconfigure 

### ISSUE THREAD

**Issue by fr3sh** [micrometer-metrics/micrometer#3728]
**Please describe the feature request.**

Due the migration of sluth to micrometer, where can I find a parameter to automatically set the 
traceId and spanId to the JMS message. 
Previously, this was the configuration metter:

spring.sleuth.messaging.jms.enabled

Do I need to configure of exectutors for that? Can you give me a hint? 

**Rationale**

**Additional context**

**Comment by shakuzen** [comment]
Duplicate of https://github.com/micrometer-metrics/tracing/issues/219
