### ISSUE TITLE
Consistently add `outcome` tag to HTTP client instrumentation

### ISSUE THREAD

**Issue by kubamarchwicki** [micrometer-metrics/micrometer#3729]
To enhance metrics filtering, a grouping `outcome` tag would be helpful in `http_client_requests`, similar to the `outcome` tag in the `http_server_requests`.

For less matured metrics systems (like CloudWatch) it's impossible to filter by patterns, and having a similar grouping in HTTP client and server metrics would be very helpful. 

PS. I couldn't find any issue related to this one, so I created a new one. Please let me know if I've overlooked something
PS2. If such a tag makes sense, I'm happy to raise a PR and work on that.

**Comment by shakuzen** [comment]
Thanks for opening the issue. Which HTTP client instrumentation are you using? We already have an outcome tag on some of them.

**Comment by kubamarchwicki** [comment]
Thank you for the swift answer. I was instrumenting JDK11 `HttpClient`
I can see the `Outcome::forStatus` is used a couple of times, but primarily for server-side requests (and for JettyClient). 

I'll happily raise a couple of PRs for different clients to align it

**Comment by shakuzen** [comment]
Thank you for the offer to help. We'd be happy to review pull requests for this.
