### ISSUE TITLE
`-SNAPSHOT` Dependency in POM Causes Build Issues

### ISSUE THREAD

**Issue by aplgithub** [micrometer-metrics/micrometer#3738]
**Describe the bug**
The `pom.xml` for `io.micrometer:micrometer-core:1.10.5` has a `SNAPSHOT` depdendency in it which is causing problems for projects using the `go-offine` function in Maven because the `SNAPSHOT` version is not publicly available.  Please see [here](https://repo1.maven.org/maven2/io/micrometer/micrometer-core/1.10.5/micrometer-core-1.10.5.pom);

```
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>io.micrometer</groupId>
<artifactId>micrometer-core</artifactId>
<version>1.10.5</version>
<name>micrometer-core</name>
...
<dependency>
<groupId>io.micrometer</groupId>
<artifactId>context-propagation</artifactId>
<version>1.0.3-SNAPSHOT</version>
<scope>compile</scope>
<optional>true</optional>
</dependency>
...
```

Please update the project so that there are no `SNAPSHOT` dependencies in the release.

**Environment**
This is being encountered with a SpringBoot 3 application [here](https://github.com/haiku/haikudepotserver) and is occuring when the immutable Docker container image is built from the [Dockerfile](https://github.com/haiku/haikudepotserver/blob/master/Dockerfile).  See the line;

```
RUN ./mvnw clean org.apache.maven.plugins:maven-dependency-plugin:3.3.0:go-offline
```

**To Reproduce**
Clone the [project](https://github.com/haiku/haikudepotserver) and with a Java 17 `JAVA_HOME` run...

```
./mvnw clean org.apache.maven.plugins:maven-dependency-plugin:3.3.0:go-offline
```

Finally you will see;

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.3.0:go-offline (default-cli) on project haikudepotserver-core: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: io.micrometer:context-propagation:jar:1.0.3-SNAPSHOT (absent): Could not find artifact io.micrometer:context-propagation:jar:1.0.3-SNAPSHOT -> [Help 1]
```

**Expected behavior**
The Maven execution will run to completion.

**Additional context**
---

**Comment by shakuzen** [comment]
That was definitely not intended. Sorry we missed that in the release, and thank you for bringing it to our attention. I'm surprised validation somewhere along the release process didn't catch this either. We'll have to make some changes so it doesn't happen again. In the meantime, I've fixed it for the upcoming 1.10.6 release scheduled for next week.
