### ISSUE TITLE
Is it possible to create a customized registry to always return delta aggregations for each scrape?

### ISSUE THREAD

**Issue by yiyiyongfu** [micrometer-metrics/micrometer#3739]
**Please describe the feature request.**
I have a use case that I want to measure some data in an application and always return a delta aggregation over whatever meter types(timer, gauge or counter) when scraping or pushing the data. I know some of the pre-existing registries do this, like Atlas registry and a bunch. But I'd like to know if I can create a lightweight customized registry and have that behavior. I don't think SimpleMeterRegistry does that though.

**Rationale**
My use case  for this registry is not fully flushed out yet and I'm not pushing the metrics to a separate monitoring backend. I'm likely consuming the data locally in my application. And to retrieve delta-aggregation result will largely simplify the process for me and I don't need to do post-processing in the pipeline anymore. So I'd like to know if this is something doable.

**Comment by shakuzen** [comment]
`SimpleMeterRegistry` has in its config (`SimpleConfig`) a `mode()` which can be changed from the default `CUMULATIVE` to `STEP`, which should give the behavior you're looking for. For more advanced use cases, perhaps you will want to make your own registry that extends the `StepMeterRegistry`.
