### ISSUE TITLE
Consider moving static methods to the bottom of the class

### ISSUE THREAD

**Issue by philwebb** [micrometer-metrics/micrometer#374]
Totally a personal style, but I personally prefer static methods to be at the bottom of the class. For example, rather than:

```java
public interface Tag {
    static Tag of(String key, String value) {
        return new ImmutableTag(key, value);
    }

    String getKey();

    String getValue();
}
```

I think the following is easier to parse because I can immediately see what are the important interface methods:

```java
public interface Tag {
    String getKey();

    String getValue();

    static Tag of(String key, String value) {
        return new ImmutableTag(key, value);
    }
}
```

I consider the `of` method to be less important that the `getKey()` and `getValue()` methods.

**Comment by jkschneider** [comment]
Left methods where one or more statics represent the primary user interaction with the class. Others have been moved as suggested.
