### ISSUE TITLE
KafkaClientMetrics - support metricsSupplier in constructor

### ISSUE THREAD

**Issue by handcarbon** [micrometer-metrics/micrometer#3743]
Would it be feasible to accept `Supplier<Map<MetricName, ? extends Metric>> metricsSupplier` directly in `KafkaClientMetrics` constructor?

Eg:
```
    public KafkaClientMetrics(Supplier<Map<MetricName, ? extends Metric>> metricsSupplier) {
        super(metricsSupplier);
    }
```

Currently the only option is to expose Kafka Consumer (from my own Kafka Library) and pass it as a constructor argument for `KafkaClientMetrics`.
```
    public KafkaClientMetrics(Consumer<?, ?> kafkaConsumer) {
        super(kafkaConsumer::metrics);
    }
```

Unfortunately I cannot also extend `KafkaMetrics` as it's not public class.

**Comment by jonatan-ivanov** [comment]
What would be the use-case of this?
Could you please add some code how would that look like and why does it have to look like that way. Micrometer only supports the Apache Kafka client which as far as I know implements `Consumer` I guess your own Kafka Library does not implement it.

As a workaround you can create an "adapter" that implements the `metrics` method of `Consumer`.

**Comment by handcarbon** [comment]
If there was such constructor
```
package io.micrometer.core.instrument.binder.kafka;

import org.apache.kafka.common.Metric;
import org.apache.kafka.common.MetricName;
....

public class KafkaClientMetrics extends KafkaMetrics {
  ...
   public KafkaClientMetrics(Supplier<Map<MetricName, ? extends Metric>> metricsSupplier) {
      super(metricsSupplier);
   }
```

I could do this:

```
  var myConsumer = new KafkaConsumer();
  var metrics = new KafkaClientMetrics(myConsumer::metrics);
```

But today I need to do this
```
  var myConsumer = new KafkaConsumer()....
  var metrics = new KafkaClientMetrics(myConsumer);
```

This requires me to expose KafkaConsumer from my internal library to pass this as an argument to KafkaClientMetrics.
But if I could be able to pass only `Supplier<Map<MetricName, ? extends Metric>> metricsSupplier` to KafkaClientMetrics, then I wouldn't need to expose KafkaConsumer. I could expose only metricsSupplier.

**Comment by jonatan-ivanov** [comment]
I think we can do this. Are you open creating a PR?
Also, have you considered these options?

```java
class MyKafkaClientThatWantsToKeepTheKafKaConsumerSecret implements MeterBinder {
    private Consumer<?, ?> kafkaConsumer;

    @Override
    public void bindTo(MeterRegistry registry) {
        new KafkaClientMetrics(this.kafkaConsumer).bindTo(registry);
    }
}
```
So that you can:
```java
client.bindTo(registry);
```
Or if you don't want to implement `MeterBinder`:
```java
class MyKafkaClientThatWantsToKeepTheKafKaConsumerSecret {
    private Consumer<?, ?> kafkaConsumer;

    public MeterBinder meterBinder() {
        return new KafkaClientMetrics(this.kafkaConsumer);
    }
}
```
So that you can:
```java
client.meterBinder().bindTo(registry);
```
Or you can make the `Consumer<?, ?> getKafkaConsumer()` method package private and create a public `MeterBinder` in the same package:
```java
class MyKafkaClientThatWantsToKeepTheKafKaConsumerSecret {
    private Consumer<?, ?> kafkaConsumer;

    // only accessible from the same package
    Consumer<?, ?> getKafkaConsumer() {
        return this.kafkaConsumer;
    }
}

class CustomKafkaClientMeterBinder implements MeterBinder {
    private MyKafkaClientThatWantsToKeepTheKafKaConsumerSecret client;

    @Override
    public void bindTo(MeterRegistry registry) {
        new KafkaClientMetrics(client.kafkaConsumer).bindTo(registry);
    }
}
```
so that you can:
```java
MyKafkaClientThatWantsToKeepTheKafKaConsumerSecret client = ...;
new CustomKafkaClientMeterBinder(client).bindTo(registry);
```

**Comment by marcingrzejszczak** [comment]
There was no feedback since april. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
