### ISSUE TITLE
Publish metrics to Elastic TimeSeries DataStream TSDS

### ISSUE THREAD

**Issue by patpatpat123** [micrometer-metrics/micrometer#3763]
**Please describe the feature request.**
What I would like to do with Micrometer:
Send the existing metrics (which are great by the way) to ElasticSearch, but to a DataStream, more precisely, a Time Series Data Stream, not just a regular index:
https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html
https://www.elastic.co/guide/en/elasticsearch//reference/master/tsds.html

(Copy paste from ElasticSearch official doc:)
A data stream lets you store append-only **time series data** across multiple indices while giving you a single named resource for requests. Data streams are well-suited for logs, events, **metrics**, and other continuously generated data.

(see screenshot for datastream)
![Screenshot 2023-04-11 163729](https://user-images.githubusercontent.com/43899031/231105060-e0320141-89f8-4e1f-aebb-481bffd31fbb.png)

But could not with this current version, because 
```
management.elastic.metrics.export.auto-create-index=false
management.elastic.metrics.export.enabled=true
management.elastic.metrics.export.host=some-elastichost
management.elastic.metrics.export.index=indexname
management.elastic.metrics.export.indexDateFormat=yyyy-MM
```

will create a plain index (please see screenshot)

![Screenshot 2023-04-11 163814](https://user-images.githubusercontent.com/43899031/231105099-24296496-ef60-4d7a-849f-b1ebe8fc1e3a.png)

**Rationale**
The reason behind this request is that by definition, metrics published by micrometer elastic are very well suited for ElasticSearch TimeSeries DataStream, because they are time series data stream in the first place.

However, as of now, one needs to manually convert the metric index into DataStream from the regular Index on the ElasticSearch backend in order to benefit from the synergy between micrometer elastic metrics and elasticsearch data stream.

Would be a great feature if micrometer elastic can directly push the metrics as it is doing today, directly to a time series data stream instead.

Thank you

**Comment by patpatpat123** [comment]
Thank you for your answer @shakuzen .
clarification
I have reached out to the original author of the PR for clarifications.

With that said, I think the _time series data stream index template_ can be create by an http request from micrometer directly.

**Comment by shakuzen** [comment]
If there is an equivalent template for time series data streams that we could be creating, I think it makes sense to default to creating that if something (e.g. an index template) doesn't already exist and the elasticsearch instance we're connecting to supports time series data streams. We would consider accepting a contribution that does that, if you're interested in making a pull request. I don't know if we would lose any features that users may be relying upon with the index approach.
