### ISSUE TITLE
Support primitive types for Observation tags

### ISSUE THREAD

**Issue by nikoncode** [micrometer-metrics/micrometer#3781]
Modern tracing backends support boolean, double and long values in attribute, it might be used for future filtering. For example: http.retry_count > 3.

I added support of these types in tracing library https://github.com/micrometer-metrics/tracing/issues/234, but I want to make this work starting from Observation (Convention) layer. It requires modification of KeyValue class.

**Comment by maciejwalkowiak** [comment]
Did you mean @marcingrzejszczak?

**Comment by nikoncode** [comment]
Yes, I am sorry.

**Comment by maciejwalkowiak** [comment]
No worries it happens systematically 😊

**Comment by marcingrzejszczak** [comment]
@nikoncode we are looking into this. Please be patient

**Comment by marcingrzejszczak** [comment]
We will postpone the decision  to merge this until the next minor release. We need to think this through

**Comment by nikoncode** [comment]
If you want my opinion:
* we probably should even start exposing types from KeyName level, because it's used to declare attribute.
* since types "kind of" exporter specific, we can try to make all places which operates with types abstract (for example setTags), to be able to support various types for different backends or use conversion to string as fallback.
* we can get inspiration from opentelemetry https://github.com/open-telemetry/opentelemetry-java/blob/9f600741edbc0094ca9828b8873cf854a02f1917/api/all/src/main/java/io/opentelemetry/api/common/AttributeKey.java#L22, they Key is parameterized and use types as enum for future processing.
* I think it's not an option to prevent creation of non-string attributes, because:
  * tracing specifications and modern backends support DSL which might be based on attribute type (Jaeger, Tempo, etc.). <> for numbers, and things like IN for array.
  * I like micrometer-tracing concept and want to stick to the spring boot 3 defaults to instrument in-house transport clients with variant of opentelemetry spec.
* I can try to assist with implementation, because I feel direct pain with it. But it's not possible without strategic decision from your side. And thanks for letting me implement this at least on span level, I will use it to avoid call of specific opentelemetry methods.

**Comment by marcingrzejszczak** [comment]
> I can try to assist with implementation, because I feel direct pain with it. But it's not possible without strategic decision from your side. And thanks for letting me implement this at least on span level, I will use it to avoid call of specific opentelemetry methods.

No problem. Can you elaborate more about the direct pain of not having this? Backends should allow you to do comparison operations like `>` or `<` even on string values :thinking:

**Comment by marcingrzejszczak** [comment]
@nikoncode any feedback on this?

**Comment by izeye** [comment]
https://github.com/micrometer-metrics/micrometer/pull/3782 seems to have been opened for this, so you might also want to close it.

**Comment by viacheslav-dobrynin** [comment]
@jonatan-ivanov, @marcingrzejszczak, hello! 

We are faced with the problem of the absence of types in micrometer. 
More specifically, langfuse expects an integer type for the tag, and when it receives a string, it does not work as expected.

See https://github.com/orgs/langfuse/discussions/10097#discussioncomment-15059893 for details.
