### ISSUE TITLE
Add solace-binder Instrumentation 

### ISSUE THREAD

**Issue by desertTown** [micrometer-metrics/micrometer#3789]
solace binder did not do instrumentation in SpringBoot 3.0.x, please help to support this feature, Thanks!

**Comment by Mrc0113** [comment]
Hi @desertTown, 
Solace is currently working on the Boot v3 release. If you have specific things you want to make sure are included can you let us know over in the [Solace Community](https://solace.community) or open an issue on our [Spring Boot](https://github.com/SolaceProducts/solace-spring-boot) or [Cloud Stream binder](https://github.com/SolaceProducts/solace-spring-cloud) repos? 

thanks!

**Comment by marcingrzejszczak** [comment]
There was no feedback since April 2023. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
