### ISSUE TITLE
Influx Metric Registry Publish Can Fail Silently

### ISSUE THREAD

**Issue by michaelmcfadyen** [micrometer-metrics/micrometer#379]
I had a bug in my logic to create timer metrics which passed in 'null' as one of the values of a tag. The next execution of the publish method would then throw a NullPointerException when invoking writeTimer. The exception wasn't handled in the publish method, bubbled back to the Executor which then failed silently and as result all no more metrics were ever sent.

Currently, the publish method implementation inside InfluxMetricRegistry only catches MalformedURLException and IOException ie.
```
        } catch (MalformedURLException e) {
            throw new IllegalArgumentException("Malformed InfluxDB publishing endpoint, see '" + config.prefix() + ".uri'", e);
        } catch (IOException e) {
            logger.warn("failed to send metrics", e);
        }
```

I am unsure of the best solution for this however I believe that the NullPointerException should be handled and the appropriate log message should be displayed.

**Comment by jkschneider** [comment]
The null tag value problem is not possible anymore because we have a `requireNonNull` check on the `ImmutableTag` constructor. We should, however, trap all Throwables in publishing threads so as not to break publishing in an irrevocable way.

**Comment by michaelmcfadyen** [comment]
thanks, yet again for getting out a change so quickly.

**Comment by alebar** [comment]
One addition for the InfluxMeterRegistry: exceptions from the `createDatabaseIfNecessary()` should also be catched. Please check out the PR: https://github.com/micrometer-metrics/micrometer/pull/460
