### ISSUE TITLE
MicrometerHttpClientInterceptor has no outcome Tag

### ISSUE THREAD

**Issue by cachescrubber** [micrometer-metrics/micrometer#3790]
****Describe** the bug**

MicrometerHttpClientInterceptor does not support the **outcome** tag. `io.micrometer.core.instrument.binder.httpcomponents.hc5.MicrometerHttpClientInterceptor` publishes to the same meter as `io.micrometer.core.instrument.binder.httpcomponents.hc5.MicrometerHttpRequestExecutor` - **httpcomponents.httpclient.request** - using a different set of tags. When prometheus is used as registry, one of the mentioned measurements are silently dropped.

**Environment**
 - Micrometer version **1.11.0-RC1**
 - Micrometer registry **prometheus**
 - Java version: **17**

**To Reproduce**
How to reproduce the bug:

Instrument a `HttpAsyncClient` using the `MicrometerHttpClientInterceptor` and an `HttpClient` using `MicrometerHttpRequestExecutor` in the same application. Export the measurements to prometheus.

**Expected behavior**
The **outcome** Tag is supported when instrumenting `HttpAsyncClient` using the `MicrometerHttpClientInterceptor`. Both instrumentations support an identical set of Tags.

**Additional context**
#877 will be triggered by the absence of the outcome Tag.

**Comment by shakuzen** [comment]
Thank you for the report. It looks like we missed that instrumentation in #3732. Would you be interested in contributing a fix to add the `outcome` tag to `MicrometerHttpClientInterceptor`?

**Comment by cachescrubber** [comment]
> Thank you for the report. It looks like we missed that instrumentation in #3732. Would you be interested in contributing a fix to add the `outcome` tag to `MicrometerHttpClientInterceptor`?

Thanks for your quick response. I filed a fix in #3791.
