### ISSUE TITLE
Enhance Apache HttpComponents instrumentation to support the `exception` tag.

### ISSUE THREAD

**Issue by cachescrubber** [micrometer-metrics/micrometer#3812]
**Please describe the feature request.**
Enhance Apache HttpComponents instrumentation to support the `exception` tag.

**Rationale**
Most if not all the other http client / server based instrumentations support an `exception` Tag. For the sake of consistency, enable to HttpComponents instrumentation to support the `exception` tag.
 
**Additional context**
I'm happy to contribute. A PR would be blocked by #3800 since the HttpAsyncClient currently does not meter errors / IOExceptions. 

Relates to #3729

**Comment by izeye** [comment]
This seems to have been covered through #3800 already.

**Comment by cachescrubber** [comment]
Yes, closed with #3800 for http client 5.
