### ISSUE TITLE
influxdb not reading spring.metrics.influx properties

### ISSUE THREAD

**Issue by cskinfill** [micrometer-metrics/micrometer#382]
I have a spring boot 1.5.8 app that i'm trying out micrometer with.  Version 1.0.0-RC5 worked fine with the configuration properties

spring.metrics.influx.db = testme
spring.metrics.influx.uri = http://localhost:8186

but if i use RC6, RC7, or RC8 I get a failure that the connection is refused.  Looking closer I also see `14:53:39.220 WARN InfluxMeterRegistry:83: unable to create database 'mydb'` which makes me think its not reading the properties at all (since `mydb` is the default db name in the code)

**Comment by jkschneider** [comment]
@cskinfill The properties prefixes changed to `management.metrics.export.influx.uri=http://localhost:8186`, etc.

Sorry, still updating the docs!

**Comment by jkschneider** [comment]
(Published a new docs site with updates to these references)

**Comment by cskinfill** [comment]
thanks, that worked
