### ISSUE TITLE
Gauge does not update value in Gauge.builder

### ISSUE THREAD

**Issue by Salmanassar** [micrometer-metrics/micrometer#3826]
values are not updated in Gauge.builder

method.updateApplication() pull data from db

here code example:

  ```
public void registerApplicationSomeData() {
        String gaugeName =  "application-date";
        method.updateApplication().forEach(bucket -> {
            Tags tags = Tags.of("tags.some-tag", bucket.Type());
            Optional.ofNullable(register.find(gaugeName).tags(tags).gauge())
                    .ifPresent(gauge -> {
                        if (gauge.value() != bucket.count()) {
                            register.removeByPreFilterId(gauge.getId());
                        }
                    });
            Gauge.builder(gaugeName, bucket::count)
                    .description("Some description")
                    .tags(tags)
                    .register(register);
        });
    }

```

I expect that the data will be update but after initialization  the gauge does not update the value and that is why i have to add optional remove (it is works) which is not good solution for performance. I use  Gauge.builder(gaugeName, bucket,  bk-> bucket.count()) and a lot of suggestions here and Stackoverflow  and so on but in my case  it does not work. And I know about Multi-gauge (work for db) but it does not appropriate in my case
if i use for example  Gauge.builder(gaugeName, bucket,  bk->new Random().getInt()) the value is update

**Comment by jonatan-ivanov** [comment]
This is not how you should use a gauge, please check the docs: https://micrometer.io/docs/concepts#_manually_incrementing_or_decrementing_a_gauge

```java
public class GaugeSample {
    private static final SimpleMeterRegistry registry = new SimpleMeterRegistry();
    private static final Map<String, Number> bucketValues = new ConcurrentHashMap<>();

    public static void main(String[] args) throws InterruptedException {
        for (int i = 0; i < 10; i++) {
            System.out.println("---");
            registerGaugeAndUpdateData(i);
            System.out.println(registry.getMetersAsString());
        }
    }

    private static void registerGaugeAndUpdateData(int seed) {
        for (String bucket : Arrays.asList("x", "y", "z")) {
            Tags tags = Tags.of("bucket", bucket);
            bucketValues.put(bucket, Math.random() * 100 + seed * 100);
            if (registry.find("buckets").tags(tags).gauge() == null) {
                Gauge.builder("buckets", () -> bucketValues.get(bucket))
                    .tags(tags)
                    .register(registry);
            }
        }
    }
}
```

You might also want to take a look at `MultiGauge`: https://micrometer.io/docs/concepts#_multi_gauge

```java
public class GaugeSample {
    private static final SimpleMeterRegistry registry = new SimpleMeterRegistry();
    private static final MultiGauge buckets = MultiGauge.builder("buckets").register(registry);

    public static void main(String[] args) throws InterruptedException {
        for (int i = 0; i < 10; i++) {
            System.out.println("---");
            registerGaugeAndUpdateData(i);
            System.out.println(registry.getMetersAsString());
        }
    }

    private static void registerGaugeAndUpdateData(int seed) {
        buckets.register(
            Stream.of("x", "y", "z")
                .map(bucket -> Row.of(Tags.of("bucket", bucket), Math.random() * 100 + seed * 100))
                .collect(toList()),
            true
        );
    }
}
```

If I understand you correctly, these should resolve your issue, please let us know if these don't work and we can reopen it.

**Comment by Salmanassar** [comment]
Than you for reply but your first example is not correct just for loop which only creates 3 Gauge and update nothing (you can check) 
Next one is not appropriate it creates a lot of different tags, I suspect it will be problem with elasticsearch and displaying  and by the way internally use the same method register.removeByPreFilterId(id))) I use only 4 different tags and they count sometimes is changed.

**Comment by jonatan-ivanov** [comment]
>your first example is not correct just for loop which only creates 3 Gauge and update nothing (you can check)

I did check when I wrote it, it does creates 3 gauges (as intended) and it updates all 3 gauges in every iteration. :)
Did you look into the output? The value is random every single time (also it falls into 0-100, 100-200 and so on intervals o it's easier to understand):

```
buckets(GAUGE)[bucket='z']; value=28.29468284496769
buckets(GAUGE)[bucket='x']; value=49.33464938383756
buckets(GAUGE)[bucket='y']; value=92.23177703694941
---
buckets(GAUGE)[bucket='z']; value=170.1218633356928
buckets(GAUGE)[bucket='x']; value=186.01553626838157
buckets(GAUGE)[bucket='y']; value=175.02843259921013
...
```

>Next one is not appropriate it creates a lot of different tags, I suspect it will be problem with elasticsearch and displaying and by the way internally use the same method register.removeByPreFilterId(id))) I use only 4 different tags and they count sometimes (timer for 10 min)

I have hard time to understand this, the second sample produces the exact same output (3 tags, random values as intended). I'm not sure how ElasticSearch could have any issues with it or how is that related at all but it will not have any problems displaying gauges like this.

Could you please provide us a simple, minimalistic test that reproduces the issue?
To me the two samples I provided should solve your issue but I might misunderstood something.

**Comment by Salmanassar** [comment]
You are absolutely right. Thank you very much for helping. I have resolved my problem based on your code. Instead of using the bucketValues map in the method like local variable, it should be declared as a private static final map in a field. The corrected declaration should be private static final Map<String, Number> bucketValues = new ConcurrentHashMap<>();. Here's how it should look like in my code (just for example)


```
@Component
@Slf4j
public class GaugeSample {
    private static final MeterRegistry registry;
    private static final Map<String, Number> bucketValues = new ConcurrentHashMap<>();

    @Autowired
    public GaugeSample(MeterRegistry registry) {
        this.registry = registry;
    }

@EventListener(ApplicationReadyEvent.class)
public void init(){
registerApplicationSomeData()
}
    public void registerApplicationSomeData() {
        String gaugeName = "application-date";
        method.updateApplication().forEach(bucket -> {
            Tags tags = Tags.of("tags.some-tag", bucket.Type());
            bucketValues.put(bucket.Type(), bucket.count);
            Gauge.builder(gaugeName, () -> bucketValues.get(bucke.Type))
                    .description("Some description")
                    .tags(tags)
                    .register(register);
        });
    }

}

```
Thanks a lot!!

**Comment by jonatan-ivanov** [comment]
>it should be declared as a private static final map in a field

The same `Map` must be visible to everyone but it does not have to be `static`, I only made it `static` so that it is easy to use everything from `public static void main(String[] args)` (to simplify the example). If it can be non-static in your app, I would recommend doing that.

Also, it does not even need to be a `Map<String, Number>`, it can be any collection that you can update and query to get the value. I have a feeling that using a `Map` is still the best choice for you but just keep in mind that the `Gauge` does not care about the state, it only needs a state and a way to get the value from that state, if you can keep these two "rules", it should be ok.

**Comment by Ilya-Ivanov-SL** [comment]
Despite there is a warning in the documentation
```
WARNING | Attempting to construct a gauge with a primitive number or one of its java.lang object forms is always incorrect. These numbers are immutable. Thus, the gauge cannot ever be changed. Attempting to “re-register” the gauge with a different number does not work, as the registry maintains only one meter for each unique combination of name and tags.
```
it would be nice to forbid this incorrect usage of the Gauge. May be by throwing IllegalArgumentException when attempting to construct Gauge with primitive immutable Number?
I have spent several hours digging into this cause the call with primitive or Integer looks ok for the first sight and similar to the usage of Counter or Timer. I can see other people fall into this pit as well

May be even forbid `register.gauge("existing.gauge", ...)` cause it seems this call does not make sense when the other gauge with same name already exists

**Comment by jonatan-ivanov** [comment]
I don't think this is the right issue to discuss it but I'm not sure people would be happy if we would break their flow throwing an IllegalArgumentException. Logging on a `WARN` level might be better. Do you want to open a PR for this?

**Comment by Ilya-Ivanov-SL** [comment]
> I don't think this is the right issue to discuss it but I'm not sure people would be happy if we would break their flow throwing an IllegalArgumentException. Logging on a `WARN` level might be better. Do you want to open a PR for this?

Yeah, I think you are right. Despite that call leads to non-working Gauge, it might be a minor issue for client code, while exception would break it completely. I'll try WARN and open a PR a bit later
