### ISSUE TITLE
Generic Observation API

### ISSUE THREAD

**Issue by brunobat** [micrometer-metrics/micrometer#3829]
**Please describe the feature request.**

There is wide interest for an Observation API that can be able to instrument in one place and be used by multiple instrumenters coming from a wide range of libraries. 
This issue proposes to evolve the Observation API to be as generic as possible allowing non Spring projects to use it.

**Rationale**

There are a few improvements that are needed in the Observation API, in order to expand its usage to other frameworks:

1. Looking at the current Observation API I can see that it depends on Micrometer common and, more problematically on AspectJ. The later makes it unsuitable to use in a project based on any other framework. Thinking on CDI or Vert.x.
2. It's fine to have `@Observed` but not an implementation with `ObservedAspect`
3. If we decide to instrument with pure OpenTelemetry, we shouldn't need to transitively depend on `micrometer-common`.
4. Context propagation is an issue to solve. Each framework has their own mechanisms and it doesn't seem the current implementation will be widely compatible. This needs discussion.

There are some other implications:
- This could be a source and a receiver of JFR events. A facade for JFR based observability.

At the philosophical level we should evaluate if this API shouldn't be moved to an independent party like the OpenTelemetry Java project (just a suggestion!). This is certainly something that would be very useful there as well.

**Additional context**

This issue started from the discussions in: https://github.com/vert-x3/vertx-micrometer-metrics/issues/162
There is additional interest for an API like this here: [Observability abstraction layer.#29911](https://github.com/quarkusio/quarkus/issues/29911)

**Comment by ebullient** [comment]
The ObservedAspect is not a problem. If you don't use AspectJ, it does nothing (it is an optional/build time dependency). Micrometer Core also has aspects defined:
https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-core/src/main/java/io/micrometer/core/aop. The CDI interceptor implementation I created for Quarkus (to carry on that example), was specific to Quarkus. There is nothing preventing Vert.x or Quarkus or any other CDI-based (or OSGi-based, for that matter) runtime from emulating what the Aspects do. We could also contribute those back. 

Micrometer Commons is tiny. If you want to chase this direction, you're back into OTel API and/or MP Metrics territory... defining another API for the sake of defining another API. Have you looked at what is actually in that jar? 

I think we should move forward with the Observability API as it is. Explore what we need to do to make CDI or Vert.x equivalents for AspectJ, and contribute more concrete suggestions back for things that really are problems. </end early morning grumbles>

**Comment by marcingrzejszczak** [comment]
Hey, thanks for the issue!

> Looking at the current Observation API I can see that it depends on Micrometer common and...

Why is it a problem that it depends on Micrometer Common?

> more problematically on AspectJ. The later makes it unsuitable to use in a project based on any other framework. Thinking on CDI or Vert.x.

The dependency to AspectJ is optional (https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-observation/build.gradle#L24) - is that a problem?

>  This issue proposes to evolve the Observation API to be as generic as possible allowing non Spring projects to use it.

Micrometer has nothing to do with Spring, it has no dependency to Spring (other than tests) so that shouldn't be a problem really

> It's fine to have @Observed but not an implementation with ObservedAspect

As mentioned before you don't have to use it - it's in Optional scope

> If we decide to instrument with pure OpenTelemetry, we shouldn't need to transitively depend on micrometer-common.

Why? What's the problem with this dependency?

> Context propagation is an issue to solve. Each framework has their own mechanisms and it doesn't seem the current implementation will be widely compatible. This needs discussion.

Micrometer's Context Propagation implementation (https://github.com/micrometer-metrics/context-propagation) is an optional dependency in micrometer (https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-observation/build.gradle#LL18C52-L18C52)

> This could be a source and a receiver of JFR events. A facade for JFR based observability.
> At the philosophical level we should evaluate if this API shouldn't be moved to an independent party like the OpenTelemetry Java project (just a suggestion!). This is certainly something that would be very useful there as well.

I guess we can talk about this later once we agree on the rest :)

**Comment by brunobat** [comment]
The only real problem here is the context propagation. We will create a couple of PoCs on Quarkus to understand the implications and if we need to add/modify code.

**Comment by jonatan-ivanov** [comment]
Hey, were there any proceedings on the topic?
Do we still need this issue?

**Comment by brunobat** [comment]
Hey @jonatan-ivanov. It's still under consideration but parked due to bandwidth issues.
