### ISSUE TITLE
Tracer.currentSpan() is always null in Spring WebFlux

### ISSUE THREAD

**Issue by Krithika-Madhavan** [micrometer-metrics/micrometer#3835]
Hi Team, 

I'm trying to Integrate Spring AOP with Micrometer Along with Spring Webflux. 

I'm trying to use Tracer object in the Configuration class, I tried 2 methods

1. Direct Implementation
2.   
<img width="536" alt="image" src="https://github.com/micrometer-metrics/micrometer/assets/49759661/41fbf51e-444f-472e-8072-5fa557662139">

3. By searching in Net I understood that spring Webflux needs to have context , So i tried in below method 

<img width="819" alt="image" src="https://github.com/micrometer-metrics/micrometer/assets/49759661/f850f88e-9b2e-4efd-8137-9d0a19f2ff9a">

Below are the dependencies i used

<img width="628" alt="image" src="https://github.com/micrometer-metrics/micrometer/assets/49759661/1d94c1c1-3da8-4105-a6a2-d62cb894b951">

Can you please suggest me how can i get the current span in AOP layer , so that i can do customizations

**Comment by jonatan-ivanov** [comment]
I'm not sure I understand why would you do this, WebFlux is instrumented so you don't need to do it. Also, I don't think what you are trying to do with the aspect should work. Thirdly, there is `ObservedAspect` but I would not use it with Reactor.

Let me close this issue, please let me know if my understanding is not correct.

**Comment by Krithika-Madhavan** [comment]
Hi @jonatan-ivanov , 

So In a real time, I need to edit the Span's to add new tag's , also customize the Span for each method. That's why i'm trying to use AOP with this, also this was working fine Until Sleuth was there. 

Please let me know If we have some way to cutsomize the span , and add tags in Micrometer (Zipkin Trace)

**Comment by jonatan-ivanov** [comment]
You can use an `ObservationFilter` or an `ObservationConvention` or a `SpanFilter` for that.
