### ISSUE TITLE
springboot3.x integrates elastic and does not automatically create indexes

### ISSUE THREAD

**Issue by ymwfish** [micrometer-metrics/micrometer#3838]
The system determines whether the template index is automatically created during creation, and there is no problem. But the execution of the publish () method, code: for (the List is springboot integration only need to configure the "management.elastic.metrics.export", also need to write Java code alone?

**Comment by shakuzen** [comment]
Are you saying the index is not automatically being created in a Spring Boot 3 app with the Elasticsearch registry? Is there any information in the logs about any errors? It's hard to help with the information given.

**Comment by bclozel** [comment]
@ymwfish I still don't understand this requirement. If the index is properly created and metrics exported to the collectors, I guess this is not an issue for Micrometer itself but an enhancement request for Elasticsearch or Zipkin?

**Comment by ymwfish** [comment]
> @ymwfish I still don't understand this requirement. If the index is properly created and metrics exported to the collectors, I guess this is not an issue for Micrometer itself but an enhancement request for Elasticsearch or Zipkin?

You're quite right. I just don't want to send link data directly to zipkin. Instead, I want to send link call data to elastic and zipkin gets it from elastic. Is there an appropriate example?

**Comment by bclozel** [comment]
I'm not aware of any example showing this. I think this is really a question for the Zipkin team as Micrometer here did its part. I'm closing this issue as a result.
