### ISSUE TITLE
Autoconfigured CompositeMeterRegistry has null clock

### ISSUE THREAD

**Issue by michael-barker** [micrometer-metrics/micrometer#384]
I've updated to rc8 micrometer-spring-legacy.  I'm now registering multiple `MeterRegistry` beans directly instead of through `MeterExporter`.  The `CompositeMeterRegistry` that holds all of my individual `MeterRegistry`s is created with a null clock which results in an NPE.

**Comment by jkschneider** [comment]
Thanks @michael-barker

**Comment by jkschneider** [comment]
My fix was not perfect, as this causes early bean intitialization. A better fix is here: https://github.com/spring-projects/spring-boot/commit/09181d6b16eac4e06c1abff120818ddf93cb11d1
