### ISSUE TITLE
Current step data is not published on shutdown when publishing is in progress

### ISSUE THREAD

**Issue by lenin-jaganathan** [micrometer-metrics/micrometer#3846]
**Describe the bug**
https://github.com/micrometer-metrics/micrometer/issues/1882 was fixed by introducing the StepMeter Contract and doing a closing rollover. This fixed the original issue but https://github.com/micrometer-metrics/micrometer/pull/3750 introduced a polling thread that rolls the step meters at the start of the step. These 2 fixes combined produce a grey area where publishing is happening at the middle of the step and the registry closes. In this scenario, the data accumulated for the current step will be lost and will be never reported.

**Environment**
 - Micrometer version - 1.11.0
 - Micrometer registry - StepMeterRegistry

**To Reproduce**
How to reproduce the bug:
Use any Step registry for testing,
- start the registry and create an increment counter every second.
- close the registry exactly during publishing.

If the step is 60 seconds and the counter is incremented every second, it will report a value of 60 for every step. If the registry publishes at the 30th second and closes also happens at the 30th second, then publishing will be skipped as there is already publishing that is in progress. Also, the closingRollOver will be skipped as the data is already getting published. The publish will report a value of 60 (the value for the last step) and the data for the current step will never be published.

**Expected behavior**
Data for the current step should be published on close and publish happening simultaneously.

**Comment by jonatan-ivanov** [comment]
Is this the same thing we are discussing here: https://github.com/micrometer-metrics/micrometer/issues/3832?

**Comment by lenin-jaganathan** [comment]
I believe they are related.
