### ISSUE TITLE
Support ExponentialHistogram in OTLP

### ISSUE THREAD

**Issue by lenin-jaganathan** [micrometer-metrics/micrometer#3861]
**Please describe the feature request.**
[ExponentialHistogram](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exponentialhistogram) was proposed in this [OTEP](https://github.com/open-telemetry/oteps/blob/main/text/0149-exponential-histogram.md) (OpenTelemetry Enhancement Proposal) and was made stable by https://github.com/open-telemetry/opentelemetry-specification/pull/3041. Exponential Histograms advantages are documented in the OpenTelemetry documents to list a few -  configuration free, can record highly dynamic values, fully mergeable (the merging is lossy but **errorless**).
Micrometer should support exporting `ExponentialHistogram` when the export happens through OTLPMeterRegistry. The expectation is that for the use-case where service level objectives are defined, we will continue to use ExplicitBucketHistograms (It completely makes sense for a use-case where the objective is to track/observe the signals based on a set of pre-defined SLAs rather than the auto-generated one and also very cheaper when there are less SLO's involved), but when `percentilesHistogram()` is enabled the flavor of the histogram can either be `ExplicitBucketHistogram` or `ExponentialHistogram` based on the config supplied during Registry creation time (there is also an environmental variable available for this).

**Rationale**
This allows the export of ExponentialHistogram for which some of the benefits are mentioned above.

References:
- https://github.com/open-telemetry/opentelemetry-specification/pull/3041
- https://github.com/open-telemetry/opentelemetry-specification/issues/2832
- https://github.com/open-telemetry/opentelemetry-specification/issues/2987

**Comment by lenin-jaganathan** [comment]
This might need a spring-boot actuator change as well.

**Comment by shakuzen** [comment]
Do you mean for the new OtlpConfig methods to be supported as Spring Boot configuration properties? We'll make sure the Boot team is aware. We can hopefully get that added in time for the upcoming Spring Boot milestone.

**Comment by snicoll** [comment]
See https://github.com/spring-projects/spring-boot/issues/41837

**Comment by shakuzen** [comment]
We would love to hear any feedback from users that have tried this new feature out in milestones.
