### ISSUE TITLE
micrometer-osgi-test fails to resolve on JDK 21

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#3869]
```
> Task :micrometer-osgi-test:resolve FAILED
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=micrometer-osgi-test-tests)
          ⇒ [micrometer-osgi-test-tests version=1.11.1.SNAPSHOT]
              ⇒ osgi.ee: (&(osgi.ee=JavaSE)(version=21))
```

A sample build scan: https://ge.micrometer.io/s/mewa4mm2cfoxg

I don't exactly understand the issue. Perhaps the BND Gradle plugin doesn't support JDK 21 yet?

**Comment by shakuzen** [comment]
@driessamyn would you be able to provide any assistance on this? We were trying to do some local testing with early access builds of JDK 21 and came across this on the 1.11.x branch.

**Comment by chrisr3** [comment]
Those kind of errors suggest an incorrect `-runee` value in the `test.bndrun` file. Perhaps test by setting it explicitly?
```
-runee: JavaSE-21
-runtrace: true
```

**Comment by shakuzen** [comment]
Thank you for the help @chrisr3. Indeed the wrong version of Java was being passed to `runee`. I've updated the build script to pass the version of the Java configured for the toolchain, which is what will be used to compile/run tests. I was able to get a successful run of the osgi-test module with the change and JDK 21 EA (https://ge.micrometer.io/s/sorhfnvatjl2i).
