### ISSUE TITLE
Configurable base time unit for OTLP registry

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#3870]
We avoid making the base time unit configurable because it can lead to nasty issues if different applications are producing metrics data for the same meters in different units. However, it doesn't look hopeful https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18903 is going to be resolved, and it's also not great that data from the OTLP registry through the Collector to Prometheus is going to have a different unit than everything else Prometheus scrapes (presumably, since Prometheus asks producers to use seconds for time).

We'll have to discuss this and what, if anything, it makes sense for us to do in Micrometer.

**Comment by zeitlinger** [comment]
I also ran into this issue today - and created a [PR](https://github.com/micrometer-metrics/micrometer/pull/3875) - based on the assumption that this is meeting the [spec](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8355)

**Comment by jonatan-ivanov** [comment]
For future reference, let me collect a couple of connected issues/prs:
- https://github.com/open-telemetry/opentelemetry-specification/issues/2977
- https://github.com/open-telemetry/opentelemetry-specification/pull/3388
- https://github.com/open-telemetry/opentelemetry-specification/pull/3294
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18903
