### ISSUE TITLE
Clarify difference between Meter.type() and Meter.getId().getType()

### ISSUE THREAD

**Issue by philwebb** [micrometer-metrics/micrometer#388]
Are both methods needed and when would they return different values? Is it worth updating the Javadoc?

**Comment by jkschneider** [comment]
Fair point. `Meter#type` is unnecessary. It may initially seem strange to leave the type on `Meter.Id` instead, if only one needs to be present, but at times decisions are made on the basis of Id's alone, without access to the entire `Meter` (e.g. naming conventions, `MeterFilter`s that may use the type to prevent the creation of a `Meter` in the first place with a deny rule).
