### ISSUE TITLE
Add ObservedRunnable and ObservedCallable

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#3881]
Similarly to [`TraceRunnable`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceRunnable.java) in Sleuth, I think we could make the lives of those users who wants to switch threads during Observations simpler in some scenarios by providing `ObservedRunnable` and `ObservedCallable` components that will propagate the context and create a new Observation for tasks running on different threads. Additionally maybe we can create components that are not starting new Observations but just propagating the context (open `Scope`). The use-case is something like this:

https://github.com/micrometer-metrics/micrometer/blob/09b81f4adc4e8944bb8ed843756850721cc17fa2/micrometer-observation/src/test/java/io/micrometer/observation/CurrentObservationTest.java#L57-L70

**Comment by vasantteja** [comment]
Can I please work on this?

**Comment by jonatan-ivanov** [comment]
I assigned it to you. Please let us know if you have questions here or https://slack.micrometer.io/

**Comment by vasantteja** [comment]
Hi I am working on this and I am making decent progress. I will get back with details as soon as possible. Just want to drop a message. Thanks for the patience.

**Comment by shakuzen** [comment]
> Additionally maybe we can create components that are not starting new Observations but just propagating the context (open `Scope`).

This is already effectively provided by `ContextExecutorService` from [context-propagation](https://github.com/micrometer-metrics/context-propagation). See [this section](https://micrometer.io/docs/observation#instrumentation_of_thread_switching_components) of the documentation.

**Comment by vasantteja** [comment]
> > Additionally maybe we can create components that are not starting new Observations but just propagating the context (open `Scope`).
> 
> This is already effectively provided by `ContextExecutorService` from [context-propagation](https://github.com/micrometer-metrics/context-propagation). See [this section](https://micrometer.io/docs/observation#instrumentation_of_thread_switching_components) of the documentation.

I believe we are currently using `ContextExecutorService` for having observations around async methods. I am currently stuck over the fact of whether if I can we expose a Executor wrapper which is similar to `LazyTraceExecutor` around these ObservedRunnable and ObservedCallable or should I tweak `ContextExecutorService` some thing like this:

`
@Override
    public void execute(ObservedRunnable command) {
        this.executorService.execute(capture().wrap(command));
    }
`

Please let me know if I am going in the right direction or not.

CC: @jonatan-ivanov @shakuzen

**Comment by marcingrzejszczak** [comment]
Let's close this in favour of what we have in Context Propagation. I'm not a fan of us creating an observation around runnables and callables. If a user wants that then one should create an observation themselves.
