### ISSUE TITLE
Making KafkaMetrics class public

### ISSUE THREAD

**Issue by sauljabin** [micrometer-metrics/micrometer#3882]
**Please describe the feature request.**
I'm trying to filter the Kafka Stream Metrics map (KafkaStreams::metrics()), I want to customize a Supplier and then pass it to [KafkaMetrics](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java).

I do not want to create an io.micrometer.core.instrument.binder.kafka package in my project.

**Rationale**
Given the KafkaMetrics user the freedom to customize its own supplier and then pass it to the KafkaMetrics class

**Additional context**
This comes from the need to filter the metrics before binding then

**Comment by jonatan-ivanov** [comment]
Thanks for opening this issue. We might have an https://xyproblem.info/ here, could you please explain what exactly are you are trying to do maybe with an example?
I have a feeling that you can filter metrics out using a [`MeterFilter`](https://micrometer.io/docs/concepts#_deny_or_accept_meters).

**Comment by sauljabin** [comment]
Thanks! you are right
