### ISSUE TITLE
SleuthWebProperties 

### ISSUE THREAD

**Issue by ShimonMimoun** [micrometer-metrics/micrometer#3884]
Hello,

 I  using import : **org.springframework.cloud.sleuth.autoconfig.instrument.web.SleuthWebProperties;**

 to access **_SleuthWebProperties.TRACING_FILTER_ORDER._**

However, since migrating to Micrometer, i encountered difficulties in accessing that property. Is there a solution available?

**Comment by ShimonMimoun** [comment]
Hello

I searched in your micrometer packages and I can’t find these properties..

Could you tell me exactly where it is?

Thank you in advance

**Comment by shakuzen** [comment]
As @jonatan-ivanov mentioned, the filter is not in Micrometer. It is in Spring Framework; see [the documentation](https://docs.spring.io/spring-framework/reference/integration/observability.html). And the auto-configuration for it is in Spring Boot; see [the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.supported.spring-mvc). It doesn't look like the order of the bean is publicly accessible, but I'm sure the Boot team would want to understand your use case when considering an issue about this. /cc @bclozel

**Comment by bclozel** [comment]
I don't think the order is made available through properties, but [it's published in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.reactive.webflux.web-filters). In Spring Boot, defining your own `ServerHttpObservationFilter` bean instance and ordering it is enough to override the auto-configured one and enforce your own order.

In general, observability filters should be really early as they're meant to measure as much as possible on the server side and start the trace as early as possible.
