### ISSUE TITLE
Unnecessary ThreadLocal overhead in LogbackMetrics for disabled log levels

### ISSUE THREAD

**Issue by onukristo** [micrometer-metrics/micrometer#3891]
**Describe the bug**

An application is using Logback and `io.micrometer.core.instrument.binder.logging.LogbackMetrics` is enabled, via Logback turbo filters system. Notice that this is the case of almost every Spring Boot service out there.

Now, let's say an application is using `log.debug("Foo")` somewhere, and logging level for that logger is set to INFO.
The expectation of developers here is that this call will be super cheap.

However the `log.debug` call ends up in `io.micrometer.core.instrument.binder.logging.MetricsTurboFilter#decide`, which now does one ThreadLocals get, one put and one removal.

And, accessing thread local is actually relatively heavy operation.

If the application has written that logging statement as following:

```java
if (log.isDebugEnabled()){
  log.debug("Foo");
}
```

Then the issue does not happen, because following block in LogbackMetrics eliminates the thread local accesses.

```java
        // When filter is asked for decision for an isDebugEnabled call or similar test,
        // there is no message (ie format)
        // and no intention to log anything with this call. We will not increment counters
        // and can return immediately and
        // avoid the relatively expensive ThreadLocal access below. See also logbacks
        // Logger.callTurboFilters().
        if (format == null) {
            return FilterReply.NEUTRAL;
        }
```

But `if (log.isDebugEnabled())` clause is rarely used in java world.

Profiler example as well to illustrate the issue: 
![image](https://github.com/micrometer-metrics/micrometer/assets/5344757/41e3d0cb-fa4d-46f7-be93-6756b151a85c)

The profiling was the thing, that made me wonder - how come we have so many log.debug stacks visible in our flame graphs?

**Environment**
- Micrometer version 1.10.7
- Spring Boot 3.0.7
- logback-core, logback-classic: 1.4.7

**To Reproduce**
1. Create a default Spring Boot Application or enable LogbackMetrics in a simple java app with Logback as logging system.
2. Set logging level to INFO.
3. Add log.debug("Foo") statement.
4. Step into it.

**Expected behavior**
`log.debug("Foo")` is expected to be lightning fast in java ecosystem.

I think the fix is just about replacing 
```java
if (format == null) {
  return FilterReply.NEUTRAL;
}
```

with

```java
if (!level.isGreaterOrEqual(logger.getEffectiveLevel())){
   return FilterReply.NEUTRAL;
}
```

**Additional context**
We have the same case in all Spring Boot 2 services as well (2.7 mainly).
Meaning I think this bug has been around for quite a while.

And thanks for the great library.

**Comment by shakuzen** [comment]
Sounds reasonable. Though we still need the `format == null` check so we aren't counting `isXEnabled` calls (when they are enabled). Are you interested in making a pull request to the `1.9.x` branch with the change?

> Meaning I think this bug has been around for quite a while.

It has been around since 1.9.8. See https://github.com/micrometer-metrics/micrometer/pull/3627 which introduced the ThreadLocal check.

**Comment by jonatan-ivanov** [comment]
fyi: if I run the benchmarks on a log level that is not enabled (`logger.trace`), I get this result:
(`false` is without `LogbackMetrics`, `true` is with it)

```
Benchmark                                                  (registerLogbackMetrics)    Mode     Cnt    Score   Error  Units
LogbackMetricsBenchmark.logSomething                                          false  sample  486714    0.068 ± 0.004  us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.00                       false  sample            0.002          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.50                       false  sample            0.036          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.90                       false  sample            0.041          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.95                       false  sample            0.042          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.99                       false  sample            0.095          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.999                      false  sample           15.653          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.9999                     false  sample           32.725          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p1.00                       false  sample          107.904          us/op
LogbackMetricsBenchmark.logSomething                                           true  sample  661363    0.107 ± 0.003  us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.00                        true  sample            0.047          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.50                        true  sample            0.081          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.90                        true  sample            0.090          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.95                        true  sample            0.095          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.99                        true  sample            0.142          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.999                       true  sample           14.272          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p0.9999                      true  sample           29.655          us/op
LogbackMetricsBenchmark.logSomething:logSomething·p1.00                        true  sample          100.864          us/op
```

I think we should do the check earlier regardless.

**Comment by shakuzen** [comment]
I've committed a fix for this which will be in the upcoming maintenance releases scheduled for next week. You can also try out the latest snapshots if you would like to test it prior to the releases. Thank you again for the report and analysis on this.
