### ISSUE TITLE
Instrument Redisson

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#390]
Seems like the best option might be to add Micrometer support directly to Redisson, similarly to its Dropwizard integration. Some of the metrics that Redisson is recording to Dropwizard are more fine-grained than the JCache implementation surfaces. See [detail here](https://github.com/redisson/redisson/wiki/14.-Integration%20with%20frameworks#147-jmx-and-dropwizard-metrics).

**Comment by marcingrzejszczak** [comment]
Already done in Redisson https://github.com/redisson/redisson/wiki/16.-Observability
