### ISSUE TITLE
Add missing `@since` tags across the code base where appropriate

### ISSUE THREAD

**Issue by sbrannen** [micrometer-metrics/micrometer#3907]
## Overview

I unfortunately don't have time to determine all locations where `@since` tags are missing within the code base, but I have noticed that features have recently been added without `@since` tags.

For example, the new `getObservationRegistry()` and `setObservationRegistry(...)` methods were added in 1.10.8, but the class-level Javadoc for `ObservationThreadLocalAccessor` makes it appear that these methods have existed since 1.10.0, which is not true.

## Related Issues

- https://github.com/spring-projects/spring-framework/pull/30658

**Comment by sbrannen** [comment]
At a glance, it appears that several constructors and methods in `ObservationThreadLocalAccessor` were introduced in 1.10.8 without `@since` tags.

**Comment by marcingrzejszczak** [comment]
Yup, will fix that ASAP
