### ISSUE TITLE
Guard against ClassNotFoundException in JvmGcMetrics

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#391]
See https://github.com/spring-projects/spring-boot/issues/11879

**Comment by vpavic** [comment]
Hey @jkschneider, I've tried the latest snapshot however this doesn't appear to have fixed the problem. Did you manage to verify that the changes from 85d01ec work on WildFly?

I've also managed to get a workaround at WildFly configuration level, see this [SO question](https://stackoverflow.com/questions/42066835/garbagecollectionnotificationinfo-using-wildfly-8-causes-noclassdeffounderror).

Having said that, I still believe `JvmGcMetrics` should be defensive and try to detect this kind of problem but it should also notify the user, perhaps by logging a warning that `GarbageCollectionNotificationInfo` isn't accessible?

**Comment by jkschneider** [comment]
@vpavic

**Comment by jkschneider** [comment]
@vpavic I didn't test it specifically on WildFly. If you could improve the guard and test it on WildFly, that would be super helpful!

**Comment by vpavic** [comment]
Thanks for the feedback. I'll give it a try over the next day or two.
