### ISSUE TITLE
Missing http_server_requests metric in springBoot V3.0.7

### ISSUE THREAD

**Issue by guanyingjie** [micrometer-metrics/micrometer#3913]
**Describe the bug**
can not find http_server_requests metric when I call /actuator/prometheus, but others default metric is exist

**Environment**
SpringBoot v3.0.7
micrometer-registry-prometheus:1.9.3'
Micrometer registry prometheus
OS: Linux
Java version: 17

**Expected behavior**

**Additional context**
https://github.com/micrometer-metrics/micrometer/issues/3726 but my project don't conatin @EnableReactiveMethodSecurity

**Comment by bclozel** [comment]
Could you provide a sample application showing the issue? Thanks!

**Comment by jonatan-ivanov** [comment]
I think this happens because you are using Micrometer 1.9.x with Boot 3.0x.
Please do not define versions on your own but let the Boot BOM manage versions for you.
Boot 3.0.x needs Micrometer 1.10.x.
