### ISSUE TITLE
Potential tracing memory leak in Spring Boot WebFlux service

### ISSUE THREAD

**Issue by zoobert** [micrometer-metrics/micrometer#3916]
**Describe the bug**
When I instrument a very simple WebFlux Spring Boot app that simply front's a postgres database, I see a large amount of memory retained by io.micrometer.observation.SimpleObservation to the point where with large amounts of requests we start to receive OOM exceptions

**Environment**

 - Micrometer version 1.11.0
 - Compiler: Amazon Corretto JDK 19.0.2+7-FR
 - OS: MacOS Ventura 13.4

**To Reproduce**
The following is a repo containing a slimmed-down version of the problem: https://github.com/zoobert/otel-memory. This repo contains both the server with the problem and a client which makes many calls to the server to insert records.

**Expected behavior**
To receive open telemetry trace spans without encountering OOM exceptions

**Additional context**
The problem seems to be related to r2dbc pooling, Reactor content propagation, and/or spring security. If I disable any of these the problem goes away or is diminished. I've already tried posting the issue to Open Telemetry: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8749

**Comment by bclozel** [comment]
Thanks for the sample. While far from minimal, I was able to reproduce the issue. This is a case of "scope leaks" we have been working on recently. This means that the tracking of current observations and scopes has problems in certain conditions (especially with reactive pipelines) and that this cause scopes to pile up (a  memory leak).

This has been addressed in Micrometer with #3831 (and in Reactor, Context Propagation with other issues).

Upgrading your sample to Spring Boot 3.1.1-SNAPSHOT (3.1.1 is to be released this Thursday) and applying a temporary workaround fixes the problem: I'm not seeing memory leaks anymore with a profiler.

I've just submitted https://github.com/zoobert/otel-memory/pull/1 and I'll link here to the relevant Spring Boot issue when I find it.

**Comment by bclozel** [comment]
Spring Boot issue: https://github.com/spring-projects/spring-boot/issues/34736

**Comment by bclozel** [comment]
@zoobert if you can reproduce with a minimal app (just security and MVC/webflux), you should submit it as an issue to Spring Security first. Thanks!

**Comment by zoobert** [comment]
@bclozel I have a minimal reproducible case related to `Hooks.enableAutomaticContextPropogation()`, which is necessary for correlating logs with trace spans in some providers. It might be related to (https://github.com/reactor/reactor-core/issues/3499), so I will initially post it there. This issue requires jwt authentication of an endpoint using a resource server and both of the following dependencies:

```
    implementation("io.micrometer:context-propagation:1.0.3")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp:1.25.0")
```

Just letting you know here for your enlightenment.
