### ISSUE TITLE
Update to jakarta.* specification

### ISSUE THREAD

**Issue by jaraujo-sinch** [micrometer-metrics/micrometer#3919]
Hi!

There are classes that still use javax.* specification, instead of the jakarta.* ones.
Can you guys update it?

Here are some examples:
io/micrometer/core/instrument/binder/http/DefaultHttpServletRequestTagsProvider.java
io/micrometer/core/instrument/binder/http/HttpRequestTags.java
io/micrometer/core/instrument/binder/http/HttpServletRequestTagsProvider.java
io/micrometer/core/instrument/binder/jersey/server/MetricsRequestEventListener.java
io/micrometer/core/instrument/binder/jersey/server/ObservationRequestEventListener.java
io/micrometer/core/instrument/binder/jetty/OnCompletionAsyncListener.java
io/micrometer/core/instrument/binder/jetty/TimedHandler.java
io/micrometer/core/instrument/binder/jpa/HibernateMetrics.java
io/micrometer/core/lang/NonNull.java
io/micrometer/core/lang/NonNullApi.java
io/micrometer/core/lang/NonNullFields.java
io/micrometer/core/lang/Nullable.java
io/micrometer/common/lang/NonNull.java
io/micrometer/common/lang/NonNullApi.java
io/micrometer/common/lang/NonNullFields.java
io/micrometer/common/lang/Nullable.java
io/micrometer/shaded/reactor/util/annotation/NonNull.java
io/micrometer/shaded/reactor/util/annotation/NonNullApi.java
io/micrometer/shaded/reactor/util/annotation/Nullable.java

Thanks!

**Comment by bclozel** [comment]
Micrometer requires a JDK8 baseline and needs to support a wide range of applications.

For Servlet we need to support both Javax and Jakarta variants (see #3804 for a related improvement).

As for the nullability annotations I don't believe they are covered by the Jakarta specifications but rather will be by https://jspecify.dev

I'm closing this issue as a result. Thanks!

**Comment by jaraujo-sinch** [comment]
There is jakarta.annotation.Nonnull, at jakarta.annotation:jakarta.annotation-api:2.1.1

**Comment by bclozel** [comment]
Nice thanks I wasn't aware of that. Is this causing a compatibility or runtime issue in your application?

**Comment by jaraujo-sinch** [comment]
No issues so far.
We're trying to make our application fully up-to-date with Jakarta specification, without updating external dependencies on our own.

**Comment by bclozel** [comment]
Ok. Micrometer is already being used in Spring Boot 3 apps which rely on Jakarta dependencies only - so let's keep the issue closed until we find an actual problem.

**Comment by denAbramoff** [comment]
but newest micrometer-core also uses javax, for example in next classes 
-  TimedHandler
- OnCompletionAsyncListener
- HttpRequestTags
- DefaultHttpServletRequestTagsProvider

**Comment by bclozel** [comment]
@denAbramoff See #3804
