### ISSUE TITLE
Create Reactive @Observed annotation for Reactor Core for Spring Boot

### ISSUE THREAD

**Issue by tkmax83** [micrometer-metrics/micrometer#3940]
**Please describe the feature request.**
There is currently an @Observed annotation that works for MVC applications but nothing is available for the same in Reactor Core applications. There should be something available that is able to handle the Publisher wrapper of Mono and Flux and understand once those have completed to be able to observe a specific span in the context of a trace.

**Rationale**
Currently only MVC exists and applications using Reactor Core do not have a comparable annotation that can be used to monitor specific spans

**Comment by jonatan-ivanov** [comment]
There is, check the new `.tap` operator in Reactor: https://projectreactor.io/docs/core/release/reference/#_observation
Does it work for you?

**Comment by 62mkv** [comment]
Hi @jonatan-ivanov could you confirm my guess, based on this issue and this https://micrometer.io/docs/observation#instrumentation_of_reactive_libraries documentation section, it looks like `@Observed` annotation *should NOT* be used to observe reactive methods? 

Unfortunately the documentation overall is a bit moot on this.

**Comment by jonatan-ivanov** [comment]
`@Observed` can work in certain scenarios (e.g.: where Reactor can't switch threads in the middle of an `Observation`) but yes, `@Observed` annotation _should NOT_ be used to with reactive pipelines, there there is another on-liner that you can use, see Reactor's docs about `.tap`: https://projectreactor.io/docs/core/release/reference/#_observation

**Comment by 62mkv** [comment]
thanks, @jonatan-ivanov . I am currently trying to adapt a sample project from https://github.com/marcingrzejszczak/observability-boot-blog-post to Reactive "world". How would you suggest to refactor this `@Observed` annotation to use `.tap`? 

```
	@Observed(name = "user.name",
			contextualName = "getting-user-name",
			lowCardinalityKeyValues = {"userType", "userType2"})
```

Is it even possible with `.tap`?

**Comment by evanmalmud** [comment]
Wanted to follow up here because im currently trying to implement this. Having an annotation seems much better than having to reference mono with the .tap function, and it would align with the current MVC implementation. Is this something thats being worked towards?

**Comment by jonatan-ivanov** [comment]
Please notice that Micrometer does not depend on Spring, it does not contain any instrumentation for MVC as well as it does not depend on Reactor. The support is the other way: Reactor and Spring instrument themselves by using (depending on) Micrometer.

I'm not sure doing this from an annotation is a good idea since I guess modifying the pipeline from an aspect can cause conflicts. I'm not aware of any annotation that is doing anything similar and I would recommend using `.tap` instead. @chemicL might be able to give more insights.

We are not working on anything like that and not really planning to (Micrometer Core should not depend on Reactor).

**Comment by chemicL** [comment]
Hey! I think I agree with @jonatan-ivanov here. I'm not a user of the `@Observed` annotation myself so I might be wrong here, but it feels like it can be used to measure some execution of a synchronous method. Here are the traits in this scenario:
* it has a clear start time (method invocation)
* it has a clear, singular outcome (return on exception)
* it has one concern

With methods that provide a reactive return value, none of these are true. The reactive type that gets returned will have a runtime behaviour that depends on the caller. Here we have some quick thoughts that come to my mind:
* invocation of method (**start_1**)
* returning the value (**start_2** and **end_1**)
* signalling demand (**start_3**)
* `0..N onNext` calls (should they be measured individually?)
* `onComplete`/`onError` call (**end_2**)
* cancellation - (**end_3**)

With these in mind (3 start types, 3 end types, and ambiguous definition of "unit of work"), I believe the knowledge that the method author has is necessary to devise a good strategy for custom observability.
