### ISSUE TITLE
Issue with @Timed despite TimedAspect

### ISSUE THREAD

**Issue by patpatpat123** [micrometer-metrics/micrometer#3960]
**Describe the bug**
I have the Timed annotation and a TimedAspect Bean, however, metric not showing 

**Environment**
 - Micrometer version [e.g. 1.7.1] Latest SpringBoot 3.1.1
 - Micrometer registry [e.g. prometheus]
 - OS: [e.g. macOS] reproducible in macOS / Windows / Linux
 - Java version: [e.g. output of `java -version`] GraalVM 17

**To Reproduce**
How to reproduce the bug:
https://github.com/patpatpat123/timedissue

**Expected behavior**
To see the metric "findme"

**Additional context**
I have in my project spring-aspects + spring-boot-starter-actuator + micrometer-registry-prometheus + micrometer-tracing-bridge-otel + opentelemetry-exporter-otlp + a TimedAspect + a @Timed annotation.

However, the metric is absent

**Comment by shakuzen** [comment]
This reason it does not work is not related to Micrometer. This is an issue of how proxying objects works. See [this section](https://docs.spring.io/spring-framework/reference/core/aop/proxying.html#aop-understanding-aop-proxies) of the Spring Framework documentation for more explanation. You are calling the annotated method via a method reference `this::transform`, which will not go through the proxy and so the aspect will not be called. https://github.com/patpatpat123/timedissue/blob/bf185b3186af16d76b71d7903c9ca956e7a435c9/src/main/java/org/example/MyTransformService.java#L15
