### ISSUE TITLE
OtlpMeterRegistry does not report unsuccessful publication due to HTTP status

### ISSUE THREAD

**Issue by stevekradel-okta** [micrometer-metrics/micrometer#3961]
**Describe the bug**
OtlpMeterRegistry#publish silently ignores the result of `httpRequest.send()` which may be a non-exceptional `io.micrometer.core.ipc.http.HttpSender.Response` bearing a non-2xx HTTP status.

**Environment**
Micrometer 1.11.1
 - Micrometer version 1.11.1
 - Micrometer registry OtlpMeterRegistry
 - OS: MacOS
 - Java version: [e.g. output of `java -version`]

**To Reproduce**
Configure an OtlpMeterRegistry URL endpoint that accepts HTTP and returns HTTP 400, 404, 503, etc.; observe that nothing will be logged.

**Expected behavior**
A warning should be logged when the HTTP status code is outside range [200, 299]

**Additional context**
None

**Comment by lenin-jaganathan** [comment]
Possible retries on certain error cases can also be looked upon with this.

**Comment by marcingrzejszczak** [comment]
With 1.10.x we [already support this](https://github.com/micrometer-metrics/micrometer/blob/v1.10.13/implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMeterRegistry.java#L113). Is this still a problem?

**Comment by stevekradel-okta** [comment]
> With 1.10.x we [already support this](https://github.com/micrometer-metrics/micrometer/blob/v1.10.13/implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMeterRegistry.java#L113). Is this still a problem?

Looks good to me 👍
