### ISSUE TITLE
DatadogMetricMetadata should escape metric description string

### ISSUE THREAD

**Issue by GreyTeardrop** [micrometer-metrics/micrometer#397]
`DatadogMetricMetadata` might generate invalid JSON if meter description contains characters that should be JSON-scaped, e.g, `"` or `\`.

As an example, `system.cpu.usage` and `process.cpu.usage` created by `ProcessorMetrics` have `"` as part of their description.

Looks like [JSON string scaping](https://tools.ietf.org/html/rfc7159#section-7) should be applied to meter description values.

**Comment by maciejwalkowiak** [comment]
Hey @GreyTeardrop I've submitted today PR for this issue: https://github.com/micrometer-metrics/micrometer/pull/396

**Comment by GreyTeardrop** [comment]
@maciejwalkowiak awesome, thank you. I've missed it for some reason.
