### ISSUE TITLE
Support Hazelcast 3.9.1

### ISSUE THREAD

**Issue by jdubois** [micrometer-metrics/micrometer#399]
When starting a Spring Boot 2.0.0.RC1 application using Hazelcast 3.9.1 I get the following stacktrace:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: io.micrometer.core.instrument.binder.cache.HazelcastCacheMetrics.<init>(Lcom/hazelcast/core/IMap;Ljava/lang/String;Ljava/lang/Iterable;)V
```

Looking at the Micrometer Gradle configuration, it is currently tested with Hazelcast 3.8, so I guess the API has changed between versions...

**Comment by jkschneider** [comment]
@jdubois Looks like you are on Spring Boot's 2.0.0-SNAPSHOT instead of RC1, because the signature you are referring to changed in Micrometer's master branch yesterday and was fixed in Boot 2 [here](https://github.com/spring-projects/spring-boot/pull/11918#event-1459961128).

**Comment by jdubois** [comment]
Oh sorry you are right... I'm using the Spring Platform BOM, which forces the SNAPSHOT on the transitive dependencies!!!
Thanks a lot.
BTW I'm doing this for https://github.com/jhipster/generator-jhipster so we should be able to give you a lot of feedback, as we are heavy users of this kind of thing.

**Comment by jkschneider** [comment]
@jdubois Glad that answers it. Let me know if you need any other help!
