### ISSUE TITLE
Remove metrics when shutting down InstrumentedQueuedThreadPool

### ISSUE THREAD

**Issue by wakingrufus** [micrometer-metrics/micrometer#4000]
remove metrics from MeterRegistry when shutting down InstrumentedQueuedThreadPool
Something like:

```java
    @Override
    protected void doStop() throws Exception {
       Set<Tag> tagSet = new HashSet<>();
        tags.forEach(tagSet::add);
        Stream.of("jetty.threads.config.min",
                        "jetty.threads.config.max",
                        "jetty.threads.busy",
                        "jetty.threads.jobs",
                        "jetty.threads.current",
                        "jetty.threads.idle")
                .flatMap(name -> meterRegistry.find(name).meters().stream())
                .map(Meter::getId)
                .filter(id -> new HashSet<>(id.getTags()).containsAll(tagSet))
                .forEach(meterRegistry::remove);
        super.doStop();
    }
```

**Rationale**
Clean up resources when not needed anymore

**Additional context**
The dropwizard metrics  jetty InstrumentedQueuedThreadPool does something [similar](https://github.com/dropwizard/metrics/blob/release/4.2.x/metrics-jetty11/src/main/java/io/dropwizard/metrics/jetty11/InstrumentedQueuedThreadPool.java#L103), and it seems like a good idea to do here as well.

I am happy to open a PR for this with tests if it is agreed that this should exist.

Thanks

**Comment by shakuzen** [comment]
It sounds like it may make sense, but I'd like to understand more. In most cases, I would expect stopping the threadpool to happen on shutdown of the `Server` which would also correspond to shutting down the JVM. In that case, I don't think it matters much if we remove the meters. Is this proposal for cases where Jetty Servers will be started and stopped multiple times while the JVM is running?

**Comment by wakingrufus** [comment]
Yes. Another place where it may be nice is with running multiple integration tests, spinning up and shutting down Jetty multiple times for different tests, but all using the same globalRegistry. This would provide better isolation for such tests.

**Comment by shakuzen** [comment]
We offer a `clear` method for cleaning up the registered meters on a global registry. Though we generally advise against using a global registry as much as possible to avoid having the issue in the first place. Nonetheless, it wouldn't be a bad idea for us to clean up as you suggest. Please do send us a pull request.

**Comment by wakingrufus** [comment]
Ok I have opened a PR for this. please take a look and let me know if there is anything I can improve.

Thanks again!
