### ISSUE TITLE
Some counters not being incremented when called when run on certain environments

### ISSUE THREAD

**Issue by LockeBirdsey** [micrometer-metrics/micrometer#4004]
**Describe the bug**
Counters not being recorded when triggered in some K8S environments. In a SpringBoot3 app, we have a bunch of counters that trigger when things happen. However, in our production environments, only some of the counters don't get triggered at all, despite the counter incrementer being called (validated via additional logging). As far as I can tell, all the 'default' JVM meters still work, while 4 of our meters work as intended. 

As it only appears on our production environments, I am somewhat likely to believe that there's an issue with our infrastructure and that this might be an impossible edge case

**Environment**

 - Micrometer version: 1.11.2
 - Micrometer registry: prometheus
 - OS: Alpine Linux
 - Java version: 17
 - SpringBoot: 3.1.2
 - Kubernetes: 1.27.2

**To Reproduce**
How to reproduce the bug: 
As far as I've tried (once each with local with gradle, docker, and docker k8s), it cannot be reproduced outside of running in a pod in k8s.

**Expected behavior**
Certain events should trigger all their associated counters as those events happen. Only some of the counters are being triggered correctly and are as such missing from the `actuator/prometheus` endpoint.

**Additional context**
I have validated that the appropriate counter increments are in fact being called through additional logging, so it's not user error :). This has worked fine previously and I do not know when the problems began.

**Comment by jonatan-ivanov** [comment]
This is super weird, could you please answer a few questions?
1. What was the latest version of Boot/Micrometer when this worked?
2. Do you happen to use any kind of Java agents?
3. Do you use an OpenJDK (HotSpot) JVM? And not GraalVM native-image?
4. Could you please show us how you register and increment a counter?
5. Is it only `Counter`s that won't be refreshed or `_count` on `Timer`s neither?
6. Where do you see that the value is not incremented, do you check the Prometheus UI or upir dashboards or do you call the Prometheus endpoint directly?
7. Could you please check the Prometheus endpoint directly?
8. Since the counter is present I assume it was incremented at least once. What is the counter value when it stops being incremented? When does it happen (right after startup or minutes/hours/days later)?
9. Does Spring Boot http metrics work (e.g.: `http_server_requests`)?
10. Can you repro it in a local cluster (e.g.: minikube, kind, etc.)?
11. Could you please check if you do this:

```java
private final ObservationRegistry observationRegistry = ObservationRegistry.create();

Observation.start("test", observationRegistry)
        .event(Event.of("event"))
        .stop();
```
Do you see this `Counter` incremented on the Prometheus endpoint?
```
test_event_total 1.0
```

**Comment by LockeBirdsey** [comment]
> What was the latest version of Boot/Micrometer when this worked?
	
Unsure, these metrics have been somewhat neglected since they were added about a year ago

> Do you happen to use any kind of Java agents?

No

> Do you use an OpenJDK (HotSpot) JVM? And not GraalVM native-image?

```
OpenJDK Runtime Environment Zulu17.44+15-CA (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.44+15-CA (build 17.0.8+7-LTS, mixed mode, sharing)
```


> Could you please show us how you register and increment a counter?

All the counters in this app follow the same pattern:

```kotlin
@Service
class MetricService(val meterRegistry: MeterRegistry) {
    
    fun someEventMetric(endpoint: String, requestType: String){
        Counter
            .builder("metric_name")
            .description("metric_description")
            .tags(listOf<Tag>(Tag.of("ENDPOINT", endpoint), Tag.of("REQUEST_TYPE", requestType)))
            .register(meterRegistry).increment()
    }
```


> Is it only Counters that won't be refreshed or _count on Timers neither?

This app only has Counters. I will check with some of our other apps to see if their Timers are behaving correctly

>  Where do you see that the value is not incremented, do you check the Prometheus UI or upir dashboards or do you call the Prometheus endpoint directly?
>  Could you please check the Prometheus endpoint directly?

Tests were straight from the endpoint already

> Since the counter is present I assume it was incremented at least once. What is the counter value when it stops being incremented? When does it happen (right after startup or minutes/hours/days later)?

The offending counters never show up. But the other counters that do incrememnt correctly

> Does Spring Boot http metrics work (e.g.: http_server_requests)?

Yep, those all appear to be working

> Can you repro it in a local cluster (e.g.: minikube, kind, etc.)?

I have already, that's what I meant when I said 'docker k8s'

> Could you please check if you do this...

This doesn't show up 🤔

**Comment by jonatan-ivanov** [comment]
>The offending counters never show up. But the other counters that do incrememnt correctly

This means that the part of that code was never executed. I know you wrote you validated it with logging but I still think it is the case. It is either the code is never executed or you have multiple `MeterRegistry` instances and Prometheus scrape uses a different one than you when you are registering your counter. Could you please verify this with a debugger?

Also, if you create an `ObservationTextPublisher` `@Bean` you will see log statements when `Observations` are created. You can use that too to verify if the code I posted above is executed or not.

**Comment by LockeBirdsey** [comment]
> you have multiple MeterRegistry instances

Turns out it was this. Thanks for the suggestion!
