### ISSUE TITLE
Upgrade to context-propagation 1.0.5

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#4027]

**Comment by shakuzen** [comment]
There are no new features or changes in the context-propagation 1.1 milestones that are not in 1.0.x patches. Therefore, we should stick with the GA patch versions until there is a reason to upgrade to the 1.1 line. We [previously upgraded](https://github.com/micrometer-metrics/micrometer/issues/3975) to the 1.1 line. Let's switch back to the 1.0.x line.
