### ISSUE TITLE
Memory bloat with metric tagging

### ISSUE THREAD

**Issue by datavisortedyu** [micrometer-metrics/micrometer#4035]
**Describe the bug**

**Environment**
 - Micrometer version 1.6.13
 - Micrometer registry: prometheus
 - OS: Linux
 - Java version: 1.8

**To Reproduce**
How to reproduce the bug:
Inside a compute task class, we tag metric in this way:
```
            List<Tag> tags = new ArrayList<>();
            tags.add(new Tag() {
                @Override
                public String getKey() {
                    return "ds.name";
                }

                @Override
                public String getValue() {
                    return dataSource.getName();
                }
            });
```
The class has several fields: `dataSource` represents the data source. Another field is context which can grow quite large.
At runtime, we observed the Context field inside the compute task class which had large memory footprint was referenced by micrometer.
Hence it becomes infeasible to use tagging for this class.
I am aware of `maximumAllowableTags` but it wouldn't help since one single tag may bring in large context object.

**Expected behavior**
The memory footprint of tags shouldn't be tied with enclosing class.

**Additional context**

**Comment by jonatan-ivanov** [comment]
>At runtime, we observed the Context field inside the compute task class which had large memory footprint was referenced by micrometer.

It's not clear to me from your code snippets how could Micrometer know about your `Context`.
Also, a few other issues:
- You are using a very old version of Micrometer, it is not supported anymore, please upgrade
- Instead of reimplementing `Tag` (anonymous class) you can do this:
```java
Tags tags = Tags.of("ds.name", dataSource.getName());
```

Also, please check if you don't a have high-cardinality issue (lot of datasources with different names): https://develotters.com/posts/high-cardinality/

**Comment by datavisortedyu** [comment]
Do you have recommendation on whether I should upgrade to 1.10 or 1.11 ?

https://mvnrepository.com/artifact/io.micrometer/micrometer-core

```
Tags tags = Tags.of("ds.name", dataSource.getName());
```
I assume the above is syntactic sugar (compared with anonymous class).

`how could Micrometer know about your Context`
That's the mystery I want to solve.

**Comment by jonatan-ivanov** [comment]
>Do you have recommendation on whether I should upgrade to 1.10 or 1.11 ?

Always use the higher version (`1.11` in this case), you will get more features, longer support timeline and easier migration path when you go to the next version (`1.12` in this case).

>I assume the above is syntactic sugar (compared with anonymous class).

I'm not sure, other than it is much more readable and maintainable (sugar), it also does not create a new sub-class of the `Tag` every time you have a different `dataSource` instance.

>That's the mystery I want to solve.

Without any code or reproducer I'm afraid we can't really help much. Please notice that the snippet you provided does not contain the `Context` you have problems with.

Could you please provide a minimal sample java project to reproduce your issue so we can more easily investigate? In the meantime let me close the issue, please let us know if you have a minimal reproducer or more details and we can reopen it.

**Comment by datavisortedyu** [comment]
```
            Tags tags = Tags.of("dataviews", dvs.toString());
            tags = tags.and(Tags.of("features", fsStr));
```
For multiple `Tag`s, I assume I can use the above calls.

**Comment by datavisortedyu** [comment]
After upgrading to 1.11.3 and using `Tags.of()` notation, the metrics previous tagged come up without tag.

Still investigating.
