### ISSUE TITLE
Micrometer support to push metrics from SpringBoot 3.0 application to CW using Micrometer-registry-cloudwatch2 dependency

### ISSUE THREAD

**Issue by HimajaS94** [micrometer-metrics/micrometer#4039]
I have been trying to get metrics out of my Spring Boot 3.0 application to Cloudwatch using the below dependencies.
```xml
<dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-cloudwatch2</artifactId>
 </dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-aws-actuator</artifactId>
</dependency>
```
and added management.export.cloudwatch.enabled=true and also the namespace property.

But unfortunately, I am not able to see any of my app metrics in Cloudwatch with all the permissions in place.
However, it worked for Spring Boot 2.7.x versions.
Can someone please guide me in understanding if the above dependencies work for Spring Boot 3.0 applications?
Or do I need to add any extra configuration?
If the above dependencies doesn't work, then does micrometer has any story in their roadmap to support the same feature for Spring Boot 3.0 + versions.

Thanks in advance.

**Comment by yeradis** [comment]
@HimajaS94 this I what I have and works without issue

For AWS CloudWatch specifically add bellow dependencies:

```
	implementation("org.springframework.boot:spring-boot-starter-actuator")
	
	implementation(platform("io.awspring.cloud:spring-cloud-aws-dependencies:3.1.0"))
	implementation("io.awspring.cloud:spring-cloud-aws-autoconfigure")
	implementation("io.awspring.cloud:spring-cloud-aws-starter-metrics")

	implementation("io.micrometer:micrometer-registry-cloudwatch2")
```

Read more about AWS integration here https://docs.awspring.io/spring-cloud-aws/docs/3.1.0/reference/html/index.html#using-amazon-web-services

**Comment by shakuzen** [comment]
Thanks for the help @yeradis.
@HimajaS94 The Spring Cloud AWS documentation should help on how to get metrics configured with [Spring Cloud AWS and CloudWatch](https://docs.awspring.io/spring-cloud-aws/docs/3.1.0/reference/html/index.html#cloudwatch-metrics). If you're still having trouble, you should be able to get help from the Spring Cloud AWS support channels. It's not clear there's a Micrometer issue here. Hopefully the comment from @yeradis or the documentation gets things working for you. Let us know if there's something to fix in Micrometer and we can reopen the issue.
