### ISSUE TITLE
Adding Flexibility to NamingConvention for DropwizardMeter Registry

### ISSUE THREAD

**Issue by vk-98** [micrometer-metrics/micrometer#4043]
**Please describe the feature request.**
In DropwizardMeterRegistry, I found that it is hardcoding the naming convention of the metrics to camel case only, without having the flexibility for the users to modify it in some simple way. 

**Rationale**
I started using micrometer metrics, and we so far follow the `dot` separate metric name convention, we want to have metrics in the same shape using a micrometer as well. So I wanted to have this naming convention Configurable as per the requirements of any user adopting it.

**Additional context**
None

**Comment by vk-98** [comment]
I want to contribute to micrometer-metrics in order to fix this issue. Let me know, if more clarification is needed for the issue.

**Comment by marcingrzejszczak** [comment]
You can do sth like this, that would override the default naming convention, can't you ?

```java
DropwizardMeterRegistry reg = new DropwizardMeterRegistry(...);

reg.config().namingConvention(yourNewNamingConvention)
```
