### ISSUE TITLE
Asserting Observation keys and value should offer suggestions from the other cardinality bucket.

### ISSUE THREAD

**Issue by osi** [micrometer-metrics/micrometer#4046]
**Please describe the feature request.**

When using `#hasLowCardinalityKeyValue` or `#hasHighCardinalityKeyValue`, if the key is not found, in addition to listing all the possible keys with the same cardinality, it should print the keys with the differing cardinality.

**Rationale**

There are two types of mistakes possible in writing an assertion:
 - Correct cardinality, wrong key name
 - Wrong cardinality, correct key name

The current error message only helps with the first case.

**Comment by marcingrzejszczak** [comment]
Great idea! Are you willing to file a PR?

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer/pull/4768 to try to resolve this.
