### ISSUE TITLE
Allow setting an (optional) display name for metrics

### ISSUE THREAD

**Issue by pirgeo** [micrometer-metrics/micrometer#4051]
Currently, Micrometer has support for registering a `baseUnit` as well as a `description` for each `Meter`. This sets up metadata about the recorded metrics. Consumers use this metadata to display information about this metric more concisely (e.g., representing a value that was recorded in `bytes` as `megabytes` in a chart if the values are sufficiently high). The `description` can give consumers of the data a hint about what the metric is about.

In a similar fashion, setting a pretty/display name for a metric would allow users to give a name to a metric that is easy to read and understand. An example: `jvm.threads.live` could have a display name of "Live threads", with the description going into even more detail ("The current number of live threads including both daemon and non-daemon threads").

Is there any opposition/prior discussion to adding an (optional) display name for metrics?

**Rationale**
Extending metadata on the metrics exported by Micrometer improves the readability and usability for consumers of ingested metrics.

**Additional context**
I would expect the display name to be **non-identifying** (similar to how unit and description are working today). It can be optional and omitted by default, leaving the current behavior unchanged.

**Comment by shakuzen** [comment]
> Is there any opposition/prior discussion to adding an (optional) display name for metrics?

Not that I can remember. Do any metrics backends support such a thing?

**Comment by lenin-jaganathan** [comment]
@pirgeo Aren't the Metric names meant to be self-explanatory? Also, I am worried about misinterpretation when there is a name and display name saying different things.

What will be the use case for the Display name? Is it like how the metric labelled when used in a dashboard?

**Comment by pirgeo** [comment]
> Do any metrics backends support such a thing?

* AppOptics has the concept of a [Metric Label](https://documentation.solarwinds.com/en/success_center/appoptics/content/kb/charts_dashboards/metrics.htm#metrics) (see the first screenshot there / the section at the bottom)
* Dynatrace allows you to set it as the [displayName](https://www.dynatrace.com/support/help/extend-dynatrace/extend-metrics/reference/custom-metric-metadata).
* DataDog has the concept of a Meter `short_name` which is defined as "A more human-readable and abbreviated version of the metric name.".
* Many vendors that let you build dashboards also allow you to set the metric name or the title of the tile displaying the data (e.g. Grafana)

> Aren't the Metric names meant to be self-explanatory?

They are. However, there are metrics with metric names that have 100+ characters. Having a concise, human-readable name is worth a lot in a case like this.

> What will be the use case for the Display name? Is it like how the metric labelled when used in a dashboard?

That could be one use, yes. Could be the name of a tile on your dashboard that displays a certain metric. Could be the name that shows up in the tooltip when you hover over the metric. Could also be an alternative way to search for a certain metric in your backend. I am sure there are other things that I did not think of just now 😄 

I am thinking about this as an optional additional piece of metadata that you can use to make it easier for your users to understand the data. I get your point that metric names should be self-explanatory, yet not every person looking at metrics in a dashboard is a developer who has no difficulty reading dot-cased or snake-cased metric names. Additionally, metric names might be long and hard to read. I think of the display name as a more human-readable alternative to the metric name.

**Comment by pirgeo** [comment]
Seems like there isn't a lot of appetite for this one. I'll close it for now.
