### ISSUE TITLE
OTLPMeterRegistry should adhere to OpenTelemetry data model for producing metrics

### ISSUE THREAD

**Issue by lenin-jaganathan** [micrometer-metrics/micrometer#4053]
The current implementation of OTLPMeterRegistry seems to violate some of the principles of [Metric Datamodel specified by OpenTelemetry.
](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md)

see below for the data model copied over from OTEL proto,

```
  Metric
------------+
name        |
description |
unit        |     +------------------------------------+
data        |---> |Gauge, Sum, Histogram, Summary, ... |
------------+     +------------------------------------+

 Data [One of Gauge, Sum, Histogram, Summary, ...]
-----------+
...        |  // Metadata about the Data.
points     |--+
-----------+  |
              |      +---------------------------+
              |      |DataPoint 1                |
              v      |+------+------+   +------+ |
           +-----+   ||label |label |...|label | |
           |  1  |-->||value1|value2|...|valueN| |
           +-----+   |+------+------+   +------+ |
           |  .  |   |+-----+                    |
           |  .  |   ||value|                    |
           |  .  |   |+-----+                    |
           |  .  |   +---------------------------+
           |  .  |                   .
           |  .  |                   .
           |  .  |                   .
           |  .  |   +---------------------------+
           |  .  |   |DataPoint M                |
           +-----+   |+------+------+   +------+ |
           |  M  |-->||label |label |...|label | |
           +-----+   ||value1|value2|...|valueN| |
                     |+------+------+   +------+ |
                     |+-----+                    |
                     ||value|                    |
                     |+-----+                    |
                     +---------------------------+
```

But the micrometer's producer creates N number of metrics with the same. We basically create one metric object per meter and add exactly one data point to it. This violates the specification mentioned [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#opentelemetry-protocol-data-model).
The specification goes on to mention how conflicts can be resolved in cases where description/unit mismatches. Micrometer OTLPMeterRegistry should honor these conventions for the following reasons,

* The OpenTelemetry consumer recommendation says that "Consumers MAY reject OpenTelemetry Metrics data containing semantic errors (i.e., more than one Metric identity for a given name, Resource, and Scope).". This can be problematic for micrometer users if they run into consumers who reject these data points.
* Optimal use of resources - This will reduce the memory allocated during the export processes since this involves less number of meters created. Also, one would expect this to provide wire and downstream processing efficiency (I don't have any conclusive evidence about this).

**Comment by shakuzen** [comment]
> This can be problematic for micrometer users if they run into consumers who reject these data points.

Are you aware of such a collector, or is this a theoretical concern? As far as I remember, the official OTel Collector itself does not have issue with the way we currently produce metrics. That said, of course it would be best to adhere to the specification.

Pull requests welcome to coerce the output to the specification. I think it's not going to be as easy as it perhaps sounds.

**Comment by lenin-jaganathan** [comment]
> Are you aware of such a collector, or is this a theoretical concern?

As of now only theoretical. But definitely bytes on the wire will be opitimized if we can change the protocol a bit and also the garbage created while publishing can be reduced.


> Pull requests welcome to coerce the output to the specification. I think it's not going to be as easy as it perhaps sounds.

Let me see if I can pull something off over this weekend.

**Comment by lenin-jaganathan** [comment]
@shakuzen On another note, OTLPMeterRegistry seem to not use `NamingConvention` for tags and I don't see a reason for that. Do you have any reason for it?

**Comment by shakuzen** [comment]
> OTLPMeterRegistry seem to not use `NamingConvention` for tags and I don't see a reason for that. Do you have any reason for it?

Probably just an oversight. Though at least by default, the `NamingConvention` is set to `NamingConvention.dot` which is the same as `NamingConvention.identity` which does not do any conversion/coercing of naming anyway. We should still use the configured naming convention. Feel free to open a separate issue for that.

**Comment by marcingrzejszczak** [comment]
@lenin-jaganathan have you managed to confirm that there is a collector to which we are unable to send observation data?

**Comment by lenin-jaganathan** [comment]
@marcingrzejszczak Irrespective of such a collector, this will provide a lot of network gains. Currently, the default otel collector accepts this data and I have tried 3-4 different exporters (log, signalfx, datadog, new relic) and all of them seem to work without issues.

But I would like this to be worked upon sometime soon to get network benefits.

**Comment by marcingrzejszczak** [comment]
I see. Are you willing to file a PR for this?

**Comment by lenin-jaganathan** [comment]
I had a draft work made sometime back. Let me see if I can get back to it soon.

**Comment by lenin-jaganathan** [comment]
@marcingrzejszczak Have a look at https://github.com/micrometer-metrics/micrometer/pull/4564. It might not solve this issue entirely. But 99% of what is asked will be solved by https://github.com/micrometer-metrics/micrometer/pull/4564.

**Comment by marcingrzejszczak** [comment]
Sorry for the comment above, the requested information got provided

**Comment by lenin-jaganathan** [comment]
@marcingrzejszczak Can this be targetted for the next release?

I am willing to validate this with some of our internal applications and provide feedback if this gets into the next milestone/rc release.

**Comment by shakuzen** [comment]
@lenin-jaganathan I'll take a look.

**Comment by shakuzen** [comment]
Is it just the two points mentioned in the description of https://github.com/micrometer-metrics/micrometer/pull/4564 that are remaining? If so, I think that's more a matter of updating our instrumentation to make sure those cases don't happen and this issue can be considered closed by https://github.com/micrometer-metrics/micrometer/pull/4564. If there is something else to do beside that, let us know.
