### ISSUE TITLE
Dynatrace V2 API - invalid metric key system.load.average.1m

### ISSUE THREAD

**Issue by DerKanzler** [micrometer-metrics/micrometer#4058]
**Describe the bug**
We use Spring Boot 3.1.2 with micrometer-registry-dynatrace 1.11.2.
Our Dynatrace SaaS instance should ingest the metrics created by micrometer using Dynatrace API V2. But it doesn't since Dynatrace still doesn't allow a numeric value after a dot in the name of the metric key.
Instead we get 400 error back.
```
{linesOk=0, linesInvalid=1, error={code=400, message=1 invalid lines, invalidLines=[
            {
                "line": 1,
                "error": "invalid metric key"
            }
        ]
    }, warnings=null
}
```

**Environment**
 - Micrometer version **1.11.2**
 - Micrometer registry **dynatrace**
 - OS: **Linux & macOS**
 - Java version: **JDK 17**

**To Reproduce**
How to reproduce the bug:
See attached example. [dynatrace-api-v2-metricsname.zip](https://github.com/micrometer-metrics/micrometer/files/12516706/dynatrace-api-v2-metricsname.zip)
And the log of it. [dynatrace-api-v2-metricsname.log](https://github.com/micrometer-metrics/micrometer/files/12516686/dynatrace-api-v2-metricsname.log)
Of course you'd have set management.dynatrace.metrics.export.api-token and management.dynatrace.metrics.export.uri with a valid value in application.properties.

Or send the one faulty line manually to a Dynatrace V2 API endpoint.
```
curl --location 'REDACTED' \
--header 'Authorization: Api-Token REDACTED' \
--header 'Content-Type: text/plain' \
--data 'system.load.average.1m,dt.metrics.source=micrometer gauge,2.85302734375 1693860702761'
```

**Expected behavior**
Micrometer renames the key system.load.average.1m to system.load.average.oneminute before sending it to Dynatrace V2.

**Additional context**
This was fixed once with https://github.com/micrometer-metrics/micrometer/issues/1648 in https://github.com/micrometer-metrics/micrometer/commit/712411a60ab93c5592363f5965d0e2971bbd5a50.
But after these changes it seems the code is only used and executed for V1.
https://github.com/micrometer-metrics/micrometer/pull/2607
https://github.com/micrometer-metrics/micrometer/issues/2295

Please do the renaming of the metric key also for Dynatrace API V2.

Thank you!

Kind regards,
Peter

**Comment by shakuzen** [comment]
Thank you for the report.

@pirgeo do you know if removal of the mentioned sanitization logic from the v2 implementation was intentional or an oversight? It looks like the v2 implementation doesn't use a `NamingConvention` at all.

**Comment by pirgeo** [comment]
Hi, thanks for bringing this up and for the thorough investigation!

For API v2, we do the sanitization on the backend side, so the renaming on the client side is no longer required. The metric should show up as `system.load.average.1m` in your data explorer.

I tried it out with the curl command you posted above and the same line (I just omitted the timestamp. The server timestamp will be used instead):
```
curl --location 'https://<your-dynatrace-api>/api/v2/metrics/ingest' \
--header 'Authorization: Api-Token REDACTED' \
--header 'Content-Type: text/plain' \
--data 'system.load.average.1m,dt.metrics.source=micrometer gauge,2.85302734375'
```
and I get: 
```
{"linesOk":1,"linesInvalid":0,"error":null,"warnings":null}
```
I also tried out the other metrics keys that you have shown in the log, and your sample app, and I got all lines accepted.
Might there be some other metric key that you are trying to send that is invalid?

If this problem persists, please reach out to Dynatrace support. It seems to me as if this is unrelated to the Micrometer integration and is coming from somewhere else in the ingest flow.

**Comment by DerKanzler** [comment]
Hello,

thank you for your swift analysis and responses.

The error occurred exactly with this one line system.load.average.1m. Changing it to system.load.average.oneminute manually in the curl command worked perfectly fine.

But I suppose the issue lies with our Dynatrace instances then.

I created https://one.dynatrace.com/hc/en-us/requests/219082.
Maybe it's of interest to @pirgeo. I guess/hope he is allowed to access it.

I am closing this issue in the meantime. I hope I can give an update later on.
Thank you again for your help!
