### ISSUE TITLE
Improve MeterTag to allow extracting multiple keys/value tags

### ISSUE THREAD

**Issue by gwelican** [micrometer-metrics/micrometer#4081]
**Please describe the feature request.**
The '@MeterTag' feature lets you add dynamic tags, taking a value from a parameter. Currently, you can only extract one key/value pair because annotation can't be repeated and I did not see a way to define a list of key/value pairs. 
It would be helpful to allow for extracting multiple key-value pairs.

**Rationale**
For APIs with numerous fields, it would be beneficial to create multiple tags for improved filtering.

**Additional context**

**Comment by marcingrzejszczak** [comment]
Maybe I'm missing sth, can you provide an example of what doesn't work currently?

**Comment by gwelican** [comment]
hey @marcingrzejszczak, thanks for taking a look. Suppose we have the following code:

```java
public ChargeResponse chargeInstrument(ChargeInstrumentRequest chargeInstrumentRequest) {
      }

public class ChargeInstrumentRequest {
 String currency; // EUR, USD etc
 String instrumentType; // CARD, PAYPAL etc
}
```

I can use @MeterTag to extract 1 field:

```java
      @MeterTag(key = "instrument_type", expression = "instrumentType")
```

If I also want to use the currency as a tag, I don't see a way to do it with @MeterTag, I cannot repeat @MeterTag and @MeterTag does not accept a list of keyvaluepairs, I could implement my custom extractor, but would be nice to use spel with @MeterTag.

I am still on spring boot 2.x, planning to upgrade soon, my apologies if this was solved in 3.x, but from the micrometer documentation, it seemed like this is still going to be a problem in 3.x

**Comment by marcingrzejszczak** [comment]
Do I understand correctly that you would like to use a single method parameter as 2 tags? In other words annotate the currency parameter twice with different values?

**Comment by gwelican** [comment]
Correct, I'd like to do 

```java
public ChargeResponse chargeInstrument(@MeterTag(key = "instrument_type", expression = "instrumentType") @MeterTag(key = "currency", expression = "currency") ChargeInstrumentRequest chargeInstrumentRequest) {
}
```
Or if the annotation cannot be repeated, a way to provide a key value pair, where key is the metric key and the value is the spel that resolves the value from the input parameter.

**Comment by smaxx** [comment]
it seems that the only missing thing is the declaration of `@Repeatable(MeterTags.class)` where MeterTags is just:
```
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.PARAMETER})
@Documented
public @interface MeterTags {
    MeterTag[] value();
}
```

**Comment by marcingrzejszczak** [comment]
Care for a PR?

**Comment by smaxx** [comment]
Sure https://github.com/micrometer-metrics/micrometer/pull/5055

**Comment by shakuzen** [comment]
Unfortunately, I had to revert this change as it broke the build and we need to get 1.14.0-M1 released. See https://github.com/micrometer-metrics/micrometer/pull/5055#issuecomment-2216847415

**Comment by smaxx** [comment]
> Unfortunately, I had to revert this change as it broke the build and we need to get 1.14.0-M1 released. See [#5055 (comment)](https://github.com/micrometer-metrics/micrometer/pull/5055#issuecomment-2216847415)

Please see the new one: https://github.com/micrometer-metrics/micrometer/pull/5292
Some additional comments:
Merging of the parameter annotations works now in a bit different way, earlier it was based on parameter index, now we support all of the annotations taken from target class and base interface methods, and the actual deduplication happens not based on a parameter index, but on a metertag key instead. So you can now have multiple annotations on different layers, they will be intelligently deduped, more specific keys will take precedence in case if we have same key in multiple declarations(class, interface)
