### ISSUE TITLE
Tests are flaky

### ISSUE THREAD

**Issue by brice-laurencin** [micrometer-metrics/micrometer#4082]
**Describe the bug**
I do not get stable/reproducible results from tests.

**Environment**

 - Micrometer version: 1.11.0
 - prometheus / Simple
 - OS: Ubuntu 23.04
 - Java version: openjdk version "17.0.7" 2023-04-18

**To Reproduce**
How to reproduce the bug:

I use metrics in the business logic declared as 
```kotlin
Counter.builder(GENERATED)
            .description("Counts things generated successfully.")
            .baseUnit(MY_UNIT)
            .register(registry)
```
Others directly from the `@Counted` or `@Timed` annotations.

I try to test them by both `metricRegistry.get` and counter instance injection.

I do have a reset pre-test step with `metricRegistry.clear()`.

**Expected behavior**
Always the same results.

**Additional context**
The web framework we are using is Quarkus, version `3.1.1.FINAL`.
More often than not the counter is not even known to the registry and I get a `null`.
Removing the `clear` call before the test sometimes helps, but then I have to take the previous tests into account when checking the counter values, and then it's still flaky.

Is there a way to somehow flush the registry (I did not find any)?

**Comment by jonatan-ivanov** [comment]
We are talking about tests that you wrote not tests in Micrometer, right?
With this little amount of details, I'm not sure what is the problem with your tests. Could you please provide a minimal sample project to reproduce this issue so we can more easily investigate and ensure any fix is working properly for your use case?

Also, I would highly recommend not using the global registry and always inject a new MeterRegistry to your components so every tests can have a fresh registry and you will not end up having a split brain problem where one test uses one registry and another test uses a different registry. `metricRegistry.clear()` should remove the meters from the registry but it does not do anything with other parameters (config). You can verify this by calling `scrape`/`getMetersAsString` on Prometheus/Simple meter registries.

Let me close the issue with this, please let us know if you have a reproducer and you want us to reopen it.

**Comment by brice-laurencin** [comment]
Thanks Jonatan.

Trying to write a minimal project to expose the issue I had, I came across a solution.

So, when asserting the metrics are increased by the expected value, we need to first have `get` the metric value, and then compare the value after the call to the method under test. `clear` is too powerful and removes all previously declared counters, trying to increment them result in NoOp.

Hope that will help someone someday.

**Comment by jonatan-ivanov** [comment]
There is also a `remove` method on the registry. I'm not sure if that helps in your case but I would try to write tests in a way so that every test case can start with a new registry if possible.
