### ISSUE TITLE
ObservationRegistry.NOOP is null

### ISSUE THREAD

**Issue by tomaerden-everesst** [micrometer-metrics/micrometer#4096]
In some scenarios, ObservationRegistry.NOOP is null.

We're running micrometer in a spring boot application. When enabling datasource-micrometer the application fails to start, with the following exception:
```
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "io.micrometer.observation.ObservationRegistry.NOOP" is null at spring.integration.core@6.0.7/org.springframework.integration.channel.AbstractMessageChannel.isObserved(AbstractMessageChannel.java:249)
```

We could narrow the problem down to a class initialization problem of `ObservationRegistry` and `NoopObservationRegistry`. Since these classes refer to each other in static fields, correct initialization is dependent on which class is loaded first.

versions:
micrometer 1.10.10
spring boot 3.0.10
datasource-micrometer 1.0.2

failing unit test:
```
   // in NoopObservationRegistryTests
    @Test
    void should_initialize_correctly() {
        then(NoopObservationRegistry.INSTANCE).isNotNull();
        then(ObservationRegistry.NOOP).isNotNull();
    }

```

minimal standalone example mimicking the behaviour:
```
package foo;

public class Main {

    public static void main(String[] args) {
        System.out.println(NoopObservationRegistry.INSTANCE);
        System.out.println(ObservationRegistry.NOOP);

        ObservationRegistry.NOOP.equals(ObservationRegistry.NOOP);
    }

    interface ObservationRegistry {

        ObservationRegistry NOOP = NoopObservationRegistry.INSTANCE;

        default boolean isNoop() {
            return this == NOOP;
        }

    }

    static final class NoopObservationRegistry implements ObservationRegistry {
        static final NoopObservationRegistry INSTANCE = new NoopObservationRegistry();
    }
}
```

**Comment by tomaerden-everesst** [comment]
datasource-micrometer calls `observation.openScope()` where observation happens to be a `NoopObservation`

https://github.com/jdbc-observations/datasource-micrometer/blob/main/datasource-micrometer/src/main/java/net/ttddyy/observation/tracing/DataSourceObservationListener.java#L241
https://github.com/jdbc-observations/datasource-micrometer/blob/main/datasource-micrometer/src/main/java/net/ttddyy/observation/tracing/DataSourceObservationListener.java#L134

**Comment by jonatan-ivanov** [comment]
Right, it's because `NoopObservation` does this:

https://github.com/micrometer-metrics/micrometer/blob/80c20e14608103c1dcfd65175d56b067445d1bd3/micrometer-observation/src/main/java/io/micrometer/observation/NoopObservation.java#L93-L96

**Comment by jonatan-ivanov** [comment]
@tomaerden-everesst Could you please check if the latest snapshot eliminates the issue for you? I checked it using `NoopObservationRegistry.FOR_SCOPES` it seemed ok in my test-setup.

**Comment by tomaerden-everesst** [comment]
verified successfully, our application is able to start with this fix. We'll keep an eye on when it becomes available on the maven central. Thank you, @jonatan-ivanov !

**Comment by jonatan-ivanov** [comment]
Great to hear, it should be released on 9th October.
