### ISSUE TITLE
Deprecate Jersey server instrumentation in favour of the jersey-micrometer module in Jersey

### ISSUE THREAD

**Issue by marcingrzejszczak** [micrometer-metrics/micrometer#4100]
https://github.com/eclipse-ee4j/jersey/pull/5391

**Comment by senivam** [comment]
question - why Micrometer does not support ``@Counted`` annotation for Jersey? As far as I see, there is only ``@Timed`` annotation processing for ``MetricsRequestEventListener``.

**Comment by shakuzen** [comment]
@senivam I think it was just missed to add that support to the Jersey instrumentation. Since we are deprecating the code here in favor of the code in the Jersey repo, please open an issue there and we can see about adding support for that.

**Comment by shakuzen** [comment]
Note that only Jersey server instrumentation was added to the jersey-micrometer module. We need to add the Jersey client instrumentation there before deprecating that.
