### ISSUE TITLE
Use specific exceptions for configuration problems

### ISSUE THREAD

**Issue by wilkinsona** [micrometer-metrics/micrometer#417]
#409 made the various registries fail fast when a configuration problem is detected. If a custom exception was used (rather than `IllegalStateException`), we could take this a step further in Spring Boot and provide a `FailureAnalyzer` ([introduced in 1.4](https://spring.io/blog/2016/07/28/spring-boot-1-4-released#startup-failure-message)) that provides some user-friendly guidance on how to fix the problem and avoid showing the user a stacktrace that isn't particularly useful.

A quick look at the code suggests there's room for two exceptions:

- One for some missing configuration
- One for some configuration that's invalid

There may well be room for more, but the more specific the exception the easier it'll be for Boot the failure analysis without having to resort to exception message parsing.

**Comment by jkschneider** [comment]
* One for some missing configuration - `MissingRequiredConfigurationException`
* One for some configuration that's invalid - `InvalidConfigurationException`

**Comment by wilkinsona** [comment]
Thanks!
