### ISSUE TITLE
Please make sure @Configuration classes are flagged accordingly

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#420]
I've seen this pattern in a few places involving Micrometer so I thought I'd report it. Please make sure that all configuration classes (i.e. a `class` that has at least an `@Bean` annotated method) is flagged with `@Configuration`.

Here is [an example](https://github.com/micrometer-metrics/micrometer/blob/fadd1ee0b758f983841bbef3235d10f3ada86fb4/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/web/tomcat/TomcatMetricsConfiguration.java#L33). Note  that  this applies to inner classes as well.

**Comment by jkschneider** [comment]
Combing through the project, I only found it missing on `TomcatMetricsConfiguration`. You say you've seen it in a few places... If I'm missing something, please let me know.

**Comment by snicoll** [comment]
> You say you've seen it in a few places

I've seen that several times In the PR you submitted. Sorry that wasn't clear.
