### ISSUE TITLE
ObservationGrpcServerInterceptor does not store observation in a context

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [micrometer-metrics/micrometer#4218]
**Please describe the feature request.**
Let's say that we have a gRPC server written in kotlin with coroutines support enabled:

```kotlin
class ExampleServer(private val registry: ObservationRegistry) :ServiceGrpcKt.CoroutineImplBase() {
    override suspend fun exampleMethod(request: Request): Response {
        // logic
    }
```

And let's assume that `ObservationGrpcServerInterceptor` was added as an interceptor.

When we try to get the current observation from the registry, it always return null, which is expected as suspended function are ran in a different thread:

```kotlin
override suspend fun exampleMethod(request: Request): Response {
    this.registry.currentObservation // returns null
}
```

I wonder how we can fix this, so that we can get the current observation the same as we do for blocking API.

It would be nice if the existing function could be used to retrieve the current observation created by the interceptor:
```kotlin
class ExampleServer(private val registry: ObservationRegistry) :ServiceGrpcKt.CoroutineImplBase() {
    override suspend fun exampleMethod(request: Request): Response {
        coroutineContext.currentObservation()
    }
```

**Rationale**
It is currently not possible to create a child observation based on the parent one that was created in the gRPC Server Interceptor. 

**Additional context**
https://github.com/micrometer-metrics/micrometer/pull/3256

**Comment by jonatan-ivanov** [comment]
So it seems there is a missing instrumentation and not the existing one having some bugs, right?

**Comment by AleksanderBrzozowski** [comment]
@jonatan-ivanov
Yeah, exactly, you can see my PR to find how this might be added 🙂 

I don't think that the discussion you have mentioned is related, though. It seems to be about context propagation to the REST calls, and in my case it is gRPC call 🙂 

I will be happy if you can take a look at the PR that I provided 🙂

**Comment by marcingrzejszczak** [comment]
Thank you @AleksanderBrzozowski for your PR. We will look into that ASAP (we haven't forgotten about your PR :) )

**Comment by AleksanderBrzozowski** [comment]
@marcingrzejszczak Thanks! 🙂 I haven't forgotten either! 😄

**Comment by AleksanderBrzozowski** [comment]
@marcingrzejszczak Hello! :) How is it going? Were you able to take a look at the PR? :)

**Comment by marcingrzejszczak** [comment]
Not yet, the PR however needs some conflict resolution.

**Comment by AleksanderBrzozowski** [comment]
Yup, I will try to fix conflicts today 🙂

**Comment by AleksanderBrzozowski** [comment]
Conflicts fixed, @marcingrzejszczak you can proceed with review 😃
