### ISSUE TITLE
Java 9 build

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#422]
From #414:

> It might be a good idea to consider introducing something like https://github.com/policeman-tools/forbidden-apis and/or switching the build to run with JDK9 and use the compiler flag release to target 1.8, which is what JUnit 5 does.

> sdkman might have a simple Java 9 option: http://sdkman.io

> I'll try to give it a go with different Runtimes. I was about to propose https://adoptopenjdk.net/ but there is no build of a JDK with openJ9 on OSX yet. Likely due this.

**Comment by shakuzen** [comment]
Master is currently building with JDK 11 and using the `--release` flag for compatibility with Java 8. 1.1.x builds with both JDK 8 and JDK 10. Therefore, this issue can be closed as already resolved via other changes made.
