### ISSUE TITLE
Propage headers with micrometer, feign, spring boot 3 and asynchronous call

### ISSUE THREAD

**Issue by DobreMihai-echo** [micrometer-metrics/micrometer#4222]
Hello. I have the following Request Interceptor, which sets my custom header on the requests. This works without problems when accessed from the Thread Local.
```
@Configuration 
public class ConfigClass {

 @Bean 
 public RequestInterceptor requestInterceptor() {
return requestTemplate -> {
ServletRequestAttributes = (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
if(requestAttributes == null) return;

HttpServletRequest request = requestAttributes.getRequest();
String header = request.getHeader("CUSTOM_HEADER");
if(header !=null) requestTemplate.header("CUSTOM_HEADER", header)
```

This works perfectly fine when accessing mergods that are on the thread local. But when I access those merhods asynchronously, the header is null.

I also read that with SpringBoot 3.x onwards, we need to setup a configuration in order to propagate the local thread context to the async one. And I did the following from this github:

https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide

But it still is null. Can you please tell me if you know why this happens?

Thank you in advance!

**Comment by jonatan-ivanov** [comment]
Hi, there is no need to cross post this to the Boot issue tracker, slack and here.

Also, I'm not sure I understand this, I don't see you would use Micrometer anywhere in your code. If you want to propagate custom fields, please try to setup baggage fields, as you can see in the Micrometer Tracing and/or Spring Boot docs.

**Comment by DobreMihai-echo** [comment]
Yes, I did use baggage fields before. They just never propagate to upstream services from an Async call. But they work perfectly in synchronous calls.
