### ISSUE TITLE
Pin io.micrometer:context-propagation to 1.0.6

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#4242]
See: https://github.com/micrometer-metrics/micrometer/commit/6a0f2a730385a3ef6a0c039d2cd31d617896c8b4

**Comment by shakuzen** [comment]
There are no changes except in test dependencies since context-propagation 1.0.6. Therefore, we will drop back to context-propagation 1.0.6 instead of bumping to 1.0.7.
