### ISSUE TITLE
Bump io.micrometer:context-propagation to 1.1.0

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#4244]
See: https://github.com/micrometer-metrics/micrometer/commit/bae5e10023f4e2b437fdaa0b9571ae2e3f4354ce, https://github.com/micrometer-metrics/micrometer/commit/3513df3780ab2fe1119ec2f9a6099ddcff7e7544

**Comment by izeye** [comment]
I'm curious if there's any policy change as since https://github.com/micrometer-metrics/micrometer/issues/4027, [`context-propagation`](https://github.com/micrometer-metrics/context-propagation/commits/main) doesn't seem to have made any functional changes, either.

**Comment by jonatan-ivanov** [comment]
That's a great question. The short answer is: no policy change, this will be an exception though since we were asked by the Reactor team to release 1.1.

The longer answer: Reactor has a policy to support every patch version in a minor they depend on. E.g.: they depend on the latest context-propagation `1.0.x` so they want to support it all the way back to `1.0.0`. Unfortunately, certain bug fixes in context-propagation `1.0.x` were public API changes (adding new methods). Reactor uses these new methods but since they are not available in earlier versions (like `1.0.0`), Reactor needs to do some checks (/"hacks") to prevent `NoSuchMethodException`. They asked us to release `1.1.0` which has these methods so in their new minor release they can upgrade to `1.1.x` and remove these checks. If we would not release `1.1.0`, their next minor version would still use `1.0.x` so they ned to support all the way back to `1.0.0` and keep the checks.
