### ISSUE TITLE
Remove native-image.properties from micrometer-core

### ISSUE THREAD

**Issue by zakkak** [micrometer-metrics/micrometer#4245]
**Please describe the feature request.**

Remove `-H:ReflectionConfigurationResources=${.}/reflect-config.json` from native-image.properties file.
The option should not be necessary for native-image to pick up the reflect-config.json file, while with this option included native builds using GraalVM for JDK 21 print the following warning:

```
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
```

The option is passed in https://github.com/micrometer-metrics/micrometer/blob/3513df3780ab2fe1119ec2f9a6099ddcff7e7544/micrometer-core/src/main/resources/META-INF/native-image/io.micrometer/micrometer-core/native-image.properties#L17C8-L17C68

**Rationale**
As noted in the warning the use of '-H:ReflectionConfigurationResources=` is experimental and should thus be avoided.

**Additional context**

Reproducer:
```
wget https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.0/graalvm-community-jdk-21.0.0_linux-x64_bin.tar.gz
wget https://repo1.maven.org/maven2/io/micrometer/micrometer-core/1.11.5/micrometer-core-1.11.5.jar
tar xf graalvm-community-jdk-21.0.0_linux-x64_bin.tar.gz
cat > Main.java <<EOF                                                                                                                                                                     
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
EOF
./graalvm-community-openjdk-21+35.1/bin/javac Main.java
./graalvm-community-openjdk-21+35.1/bin/native-image -cp ./micrometer-core-1.11.5.jar:./ Main
```

**Comment by shakuzen** [comment]
Thank you for bringing this to our attention.

I believe this is warning is something new since GraalVM 23 perhaps. It did not used to give such a warning. I checked with the latest patch of 22 (22.3.3) and it does not give a warning.

It does indeed seem `native-image` can find the `reflect-config.json` file now (I assume it did not before) without the `native-image.properties`. I was trying to find some documentation on this so we can know what minimum version of GraalVM we would be requiring by removing the explicit reference to the `reflect-config.json` from the `native-image.properties`. It seems to be documented [here](https://www.graalvm.org/latest/reference-manual/native-image/metadata/#specifying-metadata-with-json), but I'm not sure from what version that became the case. Do you happen to know?

**Comment by shakuzen** [comment]
I did a little more digging in the documentation, and it looks like GraalVM 22.2 [also mentions](https://www.graalvm.org/22.2/reference-manual/native-image/metadata/#specifying-metadata-with-json) including the config, but it mentions `reflection-config.json` rather than `reflect-config.json`.

**Comment by zakkak** [comment]
> I did a little more digging in the documentation, and it looks like GraalVM 22.2 [also mentions](https://www.graalvm.org/22.2/reference-manual/native-image/metadata/#specifying-metadata-with-json) including the config, but it mentions `reflection-config.json` rather than `reflect-config.json`.

Well it also mentions `reflect-config.json` in https://www.graalvm.org/22.2/reference-manual/native-image/metadata/#specifying-reflection-metadata-in-json

Digging through the code instead of the documentation I was able to track its presence all the way back to [GraalVM 19.1](https://github.com/oracle/graal/blob/b03199134754bf35fef43ec9b96e8f5afca6d0a1/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/configure/ConfigurationFiles.java#L52).

Probably GraalVM always detected `reflect-config.json` but not `reflection-config.json` (which probably by mistake was mentioned in the docs in the past), thus why there was the need for passing it explicitly through the command line options.

**Comment by shakuzen** [comment]
Thank you for the investigation and reference. It sounds like we should be okay to remove our `native-image.properties` in our next minor release, then.
