### ISSUE TITLE
Consider renaming file descriptor metrics

### ISSUE THREAD

**Issue by wilkinsona** [micrometer-metrics/micrometer#425]
The metric names are currently the following:

- `process.open.fds`
- `process.max.fds`

To match other metrics like `jvm.classes.loaded` and `jam.classes.unloaded` should they not be the following:

- `process.fds.open`
- `process.fds.max`

I also find `fds` a bit ambiguous. Would `files` be better?

- `process.files.open`
- `process.files.max`

**Comment by shakuzen** [comment]
See #412 for this change already proposed and some links to previous discussion.

**Comment by wilkinsona** [comment]
Oops. I should have found this one. Thanks for the pointer. I'll close this and make a comment about a possible `fds` -> `files` change on #412.
