### ISSUE TITLE
Code not getting the correct uri

### ISSUE THREAD

**Issue by houzhao666** [micrometer-metrics/micrometer#4256]
Writing to the return front-end using the following, the uri is fetched correctly, and you get the root
```java
response.setStatus(HttpStatus.BAD_REQUEST.value());
response.setHeader("content-type", "application/json;charset=UTF-8");
OutputStream outputStream = response.getOutputStream();
outputStream.write(JSON.toJSONString(RestResponse.fail(e.toString())).getBytes(StandardCharsets.UTF_8));
```
![image](https://github.com/micrometer-metrics/micrometer/assets/45731570/7277f3b0-b322-464b-8def-048d9d7920fa)

How can I set the uri of the current request?

**Comment by jonatan-ivanov** [comment]
You did not provide a lot of details and I'm not sure I understand this.
It seems you are using Spring (`HttpStatus` and Prometheus output) but if so why would you use and `OutputStream` and  `JSON.toJSONString`. Or is this something else?

Also, if the `uri` is correct:
>the uri is fetched correctly,

Why do you want to modify it?

So let me assume a bunch of things here. If you are asking how to set the `uri` on an Observation so that the `uri` of the time series will be different, you can do this:

```java
ServerHttpObservationFilter.findObservationContext(request).ifPresent(context -> context.lowCardinalityKeyValue(uri));
```
or
```java
observationRegistry.currentObservation().lowCardinalityKeyValue(uri);
```

**Comment by houzhao666** [comment]
![image](https://github.com/micrometer-metrics/micrometer/assets/45731570/8a7c8eb8-90b1-402d-a5a3-8be1424bee81)
I don't know if it has anything to do with this interceptor, but anyway, the exception is thrown inside the catch, and the http_server_requests_seconds_count uri is also the root

**Comment by jonatan-ivanov** [comment]
Spring Security has JWT support so you should not do this I think.
Your filter might interfere with Spring MVC's instrumentation.

I would try two things:
1. Does anything change if you have your own error handler ([example](https://github.com/jonatan-ivanov/teahouse/blob/68a46c2b2ac342057962b0eefe2e063344c4c54b/core/src/main/java/org/example/teahouse/core/error/CommonExceptionHandler.java))
2. If you can reproduce it without Spring Security, open a new issue for Spring Framework. If not open a new issue for Spring Security. They might need a better description, less screenshots and a minimal java sample that reproduces the issue.
