### ISSUE TITLE
Rename HistogramConfig to DistributionStatisticConfig

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#426]
`HistogramConfig` has grown beyond its original scope. It is now used to configure a rolling, decaying max as well.

Spring Boot 2 has named corresponding property-based `MeterFilter` options `management.metrics.distribution.*`.

Changing the name of the interface now before 1.0 as a nod to its increased responsibility.

**Comment by checketts** [comment]
Just a double check on the name `DistributionStatisticConfig`, does `Statistic` help describe anything?

**Comment by jkschneider** [comment]
From the Javadoc:

"Configures the distribution statistics that emanate from meters like Timer and DistributionSummary. These statistics include max, percentiles, percentile histograms, and SLA violations."

**Comment by jkschneider** [comment]
Fixed in e689461c.
