### ISSUE TITLE
Micrometer Tracing: automatic tracing instrumentation for Spring Data Repositories

### ISSUE THREAD

**Issue by 62mkv** [micrometer-metrics/micrometer#4263]
Hi, .. this question might seem a bit odd, as I am really confused with so many variables here ..

So, in a SB 2.x, we've been using Spring Cloud Sleuth for Distributed Tracing, which is going to be deprecated with SB 3.x

Also, we've been using javaagent by https://github.com/open-telemetry/opentelemetry-java-instrumentation/ which provides quite a bunch of things out of the box. 

I've managed to replicate almost all of what we might need for tracing, under this fork of https://github.com/marcingrzejszczak/observability-boot-blog-post: https://github.com/62mkv/observability-boot-blog-post/

But, I could not find anything for Spring Data repositories. And a more generic question would be: is there a way to "bridge" OTel auto-instrumentation(s) into Micrometer Tracing? Or otherwise re-use those?

**Comment by jonatan-ivanov** [comment]
You might want to look into this: https://github.com/jdbc-observations/datasource-micrometer
I think the Spring Data JPA repo should mention it as well as the Spring Boot docs.

Here is a full demo with multiple apps: https://github.com/jonatan-ivanov/teahouse/
And a talk where you can see what it can provide: https://www.youtube.com/watch?v=HQHuFnKvk_U

With this, let me close the issue, let me know if the above does not help and you want us to reopen it. If you need some Spring Data-specific instrumentation on top of JDBC, please open an issue there and explain what you need.

**Comment by 62mkv** [comment]
Hi, thanks, cool stuff! 
I was looking for Spring Data R2DBC instrumentation in particular. Is it planned? 
Also, this datasource-proxy is instrumenting SQL statements directly, not Spring Data repository methods, correct? This is useful but being able to automatically observe repository methods would be used too...
Thanks again! 
--
Sent from Mail.ru app for Android Tuesday, 24 October 2023, 02:57am +03:00 from Jonatan Ivanov  ***@***.*** :

**Comment by jonatan-ivanov** [comment]
R2DBC has a similar instrumentation using r2dbc-prroxy (/cc @ttddyy).
Please check the Boot docs: https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.observability

>Observability for JDBC and R2DBC can be configured using separate projects. For JDBC, the [Datasource Micrometer project](https://github.com/jdbc-observations/datasource-micrometer) provides a Spring Boot starter which automatically creates observations when JDBC operations are invoked. Read more about it [in the reference documentation](https://jdbc-observations.github.io/datasource-micrometer/docs/current/docs/html/). For R2DBC, the [Spring Boot Auto Configuration for R2DBC Observation](https://github.com/spring-projects-experimental/r2dbc-micrometer-spring-boot) creates observations for R2DBC query invocations.

>Also, this datasource-proxy is instrumenting SQL statements directly, not Spring Data repository methods, correct?

Yes.

>This is useful but being able to automatically observe repository methods would be used too...

Please check the project above if you find something is missing, please tell us i forms of issues to the right project(s). If you think you need a separate Observation for Spring Data repositories, please open a new issue in Spring Data and explain what you need.
