### ISSUE TITLE
@Observed does not create a counter

### ISSUE THREAD

**Issue by olada** [micrometer-metrics/micrometer#4272]
Hello everyone,
… and please bear with me if this is by design or if I am simply not using it correctly. If so, then I will transform this issue into an enhancement request.

**Describe the bug**
I am trying to leverage the Observation API through spring-aop which is working to some extent. The timer as well as long task timer are correctly handled, however the counter is missing.

This is because a counter is created for each scope, but a scope is never (?) created automatically.

**Environment**
Latest version - currently at v1.11.5

**To Reproduce**
How to reproduce the bug:
Just use the @Observed annotation according to docs.

**Expected behavior**
I would expect that an initial scope is started when using the @Observed annotation - including an event.
This would be comparable to the manual observe() method which also creates a scope.

**Additional context**
Is the expectation to always create a scope manually inside of an existing @Observed context? Or overwrite / replace the DefaultMeterObservationHandler?
Or are there additional annotations which I have not yet found to create an event?

**Comment by jonatan-ivanov** [comment]
>The timer as well as long task timer are correctly handled, however the counter is missing.

`Timer` and `LongTaskTimer` are always include a counter.

>This is because a counter is created for each scope, but a scope is never (?) created automatically.

Scoping is for a completely different thing (context propagation), we are not creating a `Counter` is you open a scope (btw `@Observed` always opens a scope).

>Just use the @observed annotation according to docs.

Many people did, we also has tests for this, and count is produced.

>I would expect that an initial scope is started when using the @observed annotation - including an event.

What makes you think that `@Observed` does not open a scope and what does this have to do with events? Have you tried it? Could you please check it with a debugger?
Also, what event would `@Observed` create?

>This would be comparable to the manual observe() method which also creates a scope.

It is the same thing, check out the code:

https://github.com/micrometer-metrics/micrometer/blob/ef04486e613c2c3acb5d2e0b5befcf7a7eeae2b1/micrometer-observation/src/main/java/io/micrometer/observation/aop/ObservedAspect.java#L134-L151
