### ISSUE TITLE
Support to change `METRIC_PREFIX` of MongoMetricsConnectionPoolListener

### ISSUE THREAD

**Issue by lntuition** [micrometer-metrics/micrometer#4288]
**Please describe the feature request.**
Support to change `METRIC_PREFIX` of MongoMetricsConnectionPoolListener

**Rationale**
I'm now using two(primary, secondary) mongo connection with one spring server. but with current `MongoMetricsConnectionPoolListener` all metric is collected with constant `METRIC_PREFIX` variable (which is now `mongodb.driver.pool.`) 

So how about add new constructor with new string parameter that can change `METRIC_PREFIX`? Or is there a better way than this suggestion? if you agree with this suggestion, can i try to resolve this issue own?

thank you for answering issue :)

**Comment by marcingrzejszczak** [comment]
You can always create a `MeterFilter` to modify these metrics, can't you?

**Comment by lntuition** [comment]
> You can always create a MeterFilter to modify these metrics, can't you?

You're right! I missed that solution! thank you for answering. i'll close this issue!

**Comment by shakuzen** [comment]
I don't see how a `MeterFilter` will help in this situation. But `MongoMetricsConnectionPoolListener` has a constructor that takes a `MongoConnectionPoolTagsProvider` and we provide a default implementation. You could pass your own tags provider (you can extend from our default implementation) that includes a tag to differentiate primary vs secondary. Would that work for your use case?

**Comment by lntuition** [comment]
@shakuzen Yes you're right. i confused last answer. Like your suggestion, i use `MongoConnectionPoolTagsProvider` to differentiate primary vs secondary (applied before last answer 😓)

Thank you very much for your response 👍 

```
fun defaultMongoConnectionPoolTagsProvider(
    clientName: String,
): MongoConnectionPoolTagsProvider =
    MongoConnectionPoolTagsProvider { event ->
        Tags.of(
            io.micrometer.core.instrument.Tag.of(
                "client.name",
                clientName
            ),
        )
    }
 ```
