### ISSUE TITLE
Slack invite link doesn't work

### ISSUE THREAD

**Issue by mkubele** [micrometer-metrics/micrometer#4305]
The link to join Slack workspace provided in the [SUPPORT](https://github.com/micrometer-metrics/micrometer/blob/main/SUPPORT.adoc) file (https://slack.micrometer.io/) does not work anymore.

**Comment by jonatan-ivanov** [comment]
Thank you so much for reporting it!
That url redirects you to a (non-expiring) invite which is getting removed by Slack every once in a while. :(
We updated the record, it worked for me, could you please check again?
