### ISSUE TITLE
Prepend http_server_requests with SOAP urlMappings

### ISSUE THREAD

**Issue by robachmann** [micrometer-metrics/micrometer#431]
Scraping metrics from an application with micrometer RC 9 returns: 

```
http_server_requests_seconds_count{exception="None",method="GET",status="200",uri="/rest/accounts/{id}",} 654.0
http_server_requests_seconds_count{exception="None",method="POST",status="200",uri="/accounts",} 946.0
```
The first metric is from a REST endpoint (`@RestController`) whereas the second one is from a SOAP endpoint (`@Endpoint`) where the method is annotated as follows:

```
@PayloadRoot(namespace = TARGET_NAMESPACE, localPart = "getAccount")
@ResponsePayload
@Override
@Timed(percentiles = {0.5, 0.95})
public GetAccountResponse getAccount(@RequestPayload GetAccount request) {}
```
Requests are being forwarded to this endpoint as configured in an extension of a `WsConfigurerAdapter`:
```
@Bean
public ServletRegistrationBean messageDispatcherServlet(ApplicationContext applicationContext) {
    MessageDispatcherServlet servlet = new MessageDispatcherServlet();
    servlet.setApplicationContext(applicationContext);
    servlet.setTransformWsdlLocations(true);
    return new ServletRegistrationBean(servlet, "/soap/*");
}
```

Does micrometer has any possibility to access the *complete* URI of a request including the defined `urlMapping="/soap/*"`? I would like to have the metrics' uri starting with either /soap or /rest:
```
http_server_requests_seconds_count{exception="None",method="GET",status="200",uri="/rest/accounts/{id}",} 654.0
http_server_requests_seconds_count{exception="None",method="POST",status="200",uri="/soap/accounts",} 946.0
```

That would be very helpful, thank you :-)

PS: The `@Timed(percentiles = {0.5, 0.95})` doesn't seem to have any effect on `@Endpoint`. 
//edit:
Instead of `@Timed(percentiles = {0.5, 0.95})`, I set the property that works for all endpoints. 
```
management.metrics.summaries.percentiles:
  all: 0.5, 0.95
```

**Comment by shark300** [comment]
As a workaround you can use CXF as a SOAP handler because I've opened a PR for CXF starter yet:
apache/cxf#642

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

As for the workaround, we've instrumented Apache Cxf https://github.com/apache/cxf/pull/1346
