### ISSUE TITLE
@Observed creates a new trace

### ISSUE THREAD

**Issue by richbolen** [micrometer-metrics/micrometer#4314]
I'm using the @Observed annotation on a service method in a spring boot app.  It is creating a new trace instead of continuing the existing trace. Is there a way to have it continue the existing trace?  i.e. inherit the traceId and and set the parent span id.  

I'm using the default setup provided by spring boot and OpenTelemetry as the tracing implementation with propagation type B3 reporting to Zipkin.

Micrometer version 1.11.5
Java 17
Mac OS
Spring Boot 3.1.5 using WebFlux

The parent trace has all subsequent spans chained together properly, including propagating them across other services that are called by my service.  Just the methods marked with @Observed end up in separate traces.

**Comment by jonatan-ivanov** [comment]
The method that has `@Observed` on (or if you create an `Observation` on your own) must be in the scope of another `Observation`. I.e.: I'm not sure where the original `Observation` ( or `Span`) is coming from but if you create a controller, call another method from there that is annotated with `@Observed`, it will produce the same traceId, please see and try one of our samples: https://github.com/micrometer-metrics/micrometer-samples/tree/main/micrometer-samples-boot3-web

**Comment by richbolen** [comment]
The Hooks thing fixed it.  Many thanks!
