### ISSUE TITLE
com.sun. management package should not be used in latest JVM's

### ISSUE THREAD

**Issue by alebastrov** [micrometer-metrics/micrometer#4317]
in logs (Java 18 temurin) I see
~~~
2023-11-06 11:24:26 2023-11-06T09:24:26.568Z  WARN 1 --- [           main] i.m.c.i.binder.jvm.JvmGcMetrics          : GC notifications will not be available because com.sun.management.GarbageCollectionNotificationInfo is not present
~~~

**Environment**
 - Micrometer version [1.11.1]
 - Micrometer registry [prometheus]
 - OS: [macOS]
 - Java version: openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)

**Comment by shakuzen** [comment]
I tried with a sample Spring Boot application using Micrometer 1.11.5 and the latest temurin 21.0.1 (as well as 18.0.2.1) and did not see any warn logs and the gc metrics were available. There must be something different about how you are running your application, and we will need more details to be able to investigate. Are you running your application in an application server?

**Comment by orionll** [comment]
This warning is shown when `jdk.management` module is not included in a running JDK.

**Comment by shakuzen** [comment]
Thanks for the additional context @orionll. The warning log seems reasonable in that case. Or do you think there's still some issue to be addressed?

**Comment by orionll** [comment]
I don't think so. The warning looks good enough to me.
