### ISSUE TITLE
GangliaConfig#ttl should use duration

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#432]
Other TTL config uses `Duration` but [this one doesn't](https://github.com/micrometer-metrics/micrometer/blob/553f20679b163d7d6da3603a1d1e6a4486e06bcd/implementations/micrometer-registry-ganglia/src/main/java/io/micrometer/ganglia/GangliaConfig.java#L81).

**Comment by jkschneider** [comment]
UDP TTL is not dimensioned as a unit of time.

> An IP TTL is set initially by the system sending the packet. It can be set to any value between 1 and 255; different operating systems set different defaults. Each router that receives the packet subtracts at least 1 from the count; if the count remains greater than 0, the router forwards the packet, otherwise it discards it and sends an Internet Control Message Protocol (ICMP) message back to the originating host, which may trigger a resend.

> The point of the TTL/hop limit is to keep streams of undeliverable packets stuck in routing loops (perhaps due to incorrect routing tables) from circulating forever and clogging up the networks in question.

Anybody still using Ganglia will be familiar with its configuration recommendation:

> Set the multi-cast Time-To-Live (TTL) to be one greater than the number of hops (routers) between the hosts.

The default is generally conservative at 1.
