### ISSUE TITLE
Should not ignore GraphiteConfig.prefix while building basic GraphiteMeterRegistry

### ISSUE THREAD

**Issue by askindaras** [micrometer-metrics/micrometer#434]
Hi,
if _GraphiteMeterRegistry(GraphiteConfig, Clock)_  is called, it will ignore _GraphiteConfig.prefix_.

Looks like _GraphiteMeterRegistry#defaultGraphiteReporter_ could pass _GraphiteConfig.prefix_ value to _GraphiteReporter.Builder_.

**Comment by jkschneider** [comment]
`prefix` here means something totally different. It represents a property prefix if you care to bind `System.properties` or some other property source to the `GraphiteConfig` interface.

On the question of a property prefix to the graphite reporter, look to `tagsAsPrefix` that allows you to represent certain tags as a prefix in the hierarchical mapping of a Micrometer meter id. If this behavior isn't exactly what you want, you are free to provide your own `GraphiteReporter` with specific customizations applied:

`GraphiteMeterRegistry(GraphiteConfig config, Clock clock, HierarchicalNameMapper nameMapper,
                                 MetricRegistry metricRegistry, GraphiteReporter reporter)`
