### ISSUE TITLE
Base time unit string duplicated for each timer

### ISSUE THREAD

**Issue by DanielThomas** [micrometer-metrics/micrometer#4352]
`getBaseTimeUnitStr` returns a new instance of `String` for every call, so for services with high tag cardinality, duplicate time units in timers can add up:

https://github.com/micrometer-metrics/micrometer/blob/d6fc0b8fdcb10bd90707855b67c8d27adf83bee4/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L290

<img width="956" alt="Screenshot 2023-11-13 at 10 07 35 am" src="https://github.com/micrometer-metrics/micrometer/assets/1479220/3f009fdb-736b-4d4b-843c-45b4fb2d6172">

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer/pull/4487 to try to resolve this.
