### ISSUE TITLE
Identifying performance issues through  flame graph:Arrays.sort(this.tags)

### ISSUE THREAD

**Issue by jiangxinlingdu** [micrometer-metrics/micrometer#4354]
jdk17，Identifying performance issues through  flame graph:Arrays.sort(this.tags)

<img width="1911" alt="企业微信截图_90060984-8490-4cb2-8de2-59df65430c1f" src="https://github.com/micrometer-metrics/micrometer/assets/6373972/28f7960e-d9a9-4b1b-bc8d-6fadedf18eb3">

i use like this：
Counter.builder(metricName).tags(tags).register(Metrics.globalRegistry).increment();

**Comment by jonatan-ivanov** [comment]
Could you please also tell us what is your question or issue?

**Comment by shakuzen** [comment]
I think this may effectively be a duplicate of #4052.

**Comment by jiangxinlingdu** [comment]
> I think this may effectively be a duplicate of #4052.

I think the same question

**Comment by shakuzen** [comment]
Thanks for confirmation. We'll close this as a duplicate of #4052, then.

**Comment by shakuzen** [comment]
Duplicate of #4052
