### ISSUE TITLE
Mimic one time event behaviour in Micrometer Counter publishing

### ISSUE THREAD

**Issue by juanegaragorri** [micrometer-metrics/micrometer#4355]
Hello everyone, I'm using Micrometer to publish metrics into NewRelic, my main problem is that I want to publish single time events (error events) with the data associated to those events, but I don't want Micrometer to keep publishing on every step this data over and over again with the throughput 0. I want micrometer to publish the data once (when the throughput is 1) and then don't publish it again. Is there any way to implement that behaviour? Some kind of filter of throughput 0?
Code example:
<img width="705" alt="Screenshot 2023-11-14 at 17 00 01" src="https://github.com/micrometer-metrics/micrometer/assets/14323376/2ad7f681-afe5-4bbc-8845-b52834f7872e">

Output: 
<img width="946" alt="Screenshot 2023-11-14 at 17 03 14" src="https://github.com/micrometer-metrics/micrometer/assets/14323376/876268f9-57d6-48d5-aaab-5a20fdac74b3">

As you can see, Its displaying the error data over and over again and I don't want garbage data in my NR (interpret this as I don't want Micrometer to keep publishing when the throughput is 0)

**Comment by jonatan-ivanov** [comment]
If I understand correctly, you can use the `Observation` API for this. You can record errors or arbitrary events that you can handle using your own `ObservationHandler` and send these events to NewRelic, please see the docs: https://micrometer.io/docs/observation#_signaling_errors_and_arbitrary_events

Please also check the `ObservationTextPublisher` to see an example about how to handle them (it writes them to logs but you can send them to NewRelic in your own handler): https://github.com/micrometer-metrics/micrometer/blob/8d5aac964bf0f5c44d1c51cd343eaaa77ff7459c/micrometer-observation/src/main/java/io/micrometer/observation/ObservationTextPublisher.java#L86-L94
