### ISSUE TITLE
TimeWindowLatencyHistogram never shuts down SimplePauseDetector

### ISSUE THREAD

**Issue by ArloL** [micrometer-metrics/micrometer#438]
[TimeWindowLatencyHistogram creates a new SimplePauseDetector](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/TimeWindowLatencyHistogram.java#L56) that is never [shut down](https://github.com/LatencyUtils/LatencyUtils/blob/master/src/main/java/org/LatencyUtils/SimplePauseDetector.java#L83) thus the SimplePauseDetectorThread instances are never stopped. This is problematic when the application is deployed in an application server e.g. Tomcat.

A workaround is to customize the MeterRegistry as follows

~~~~
@Bean
public MeterRegistryCustomizer<MeterRegistry> metricsCommonTags() {
	return registry -> registry.config()
	    .pauseDetector(new NoPauseDetector());
}
~~~~

**Comment by jkschneider** [comment]
Thanks @ArloL. We can make `MeterRegistry`/`Meter` implement `AutoCloseable` and shut down timers' pause detectors there.

**Comment by jkschneider** [comment]
Boot 2 change: we can remove custom destroy methods on all implementation autoconfigs.

**Comment by ArloL** [comment]
Thanks, @jkschneider for the quick response and the fix 👍 . I will test the snapshot first thing tomorrow.
