### ISSUE TITLE
Fix unrelated description changes

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#439]
Please review [this commit](https://github.com/micrometer-metrics/micrometer/commit/8cc63a3025cfc311927d97522bde78ad8a570858). It looks like a bunch of descriptions were changed by some refactoring and shouldn't have.

The most obvious example I could find is [the description of counting mode](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/simple/SimpleProperties.java#L45)

**Comment by jkschneider** [comment]
Good catch, thanks.
