### ISSUE TITLE
Support Azure Application Insights

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#441]
See https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#trackmetric

**Comment by jkschneider** [comment]
A client that can be wrapped: http://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Capplicationinsights-core%7C2.0.0-BETA%7Cjar

Note that the 2.0.0-BETA version contains first order dependencies on guava and httpclient.

**Comment by adriancole** [comment]
cc @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
There is a raw API for this as well: http://apmtips.com/blog/2017/10/27/send-metric-to-application-insights/ But implementing it via wrapper would be better.

@jkschneider are those dependencies problematic in this repo?

**Comment by spencergibb** [comment]
@SergeyKanzhelev in general they are, since an application might depend on an incompatible version of the same library. Shading is appropriate for those kinds of libraries.

**Comment by SergeyKanzhelev** [comment]
I believe there is a plan to shade them. @grlima @dhaval24 can you comment when those will be shaded?

**Comment by jkschneider** [comment]
@SergeyKanzhelev I actually had a chat with @dhaval24 about this yesterday. He indicated that they are relocated inside the package, so just need to strike the dependencies from the POM probably.

**Comment by dhaval24** [comment]
@jkschneider yes that is true. They are relocated inside core and web jars. As we talked yesterday I have some ideas around this. Let's touch base again soon and understand how we can get this done.

**Comment by dhaval24** [comment]
@jkschneider few things to point out: 
1. Application Insights Java SDK is composed of 3 parts - core, web and Agent. 
2. Core is the bare bone track() API which is responsible for ultimately transmitting the telemetry data to Application Insights backend service. It does all the processing, including batching of telemetry items. Web is used to auto collect requests by intercepting it using Servlet Filters and Agent is used to auto-collect Dependencies using byte code instrumentation.

For creating an exporter to send metrics to Application Insights, we would only need to wrap ApplicationInsights-core library. The main Data Structure which holds the Metric Telemetry is `MetricTelemetry.java`. This class is composed of `MetricData` and `DataPoint`. `MetricData` holds the list of `DataPoints` and `DataPoints` consist of metric related properties like avg, standard deviation etc. 

`TelemetryConfiguration.java` is the configuration class for ApplicationInsights and stores the ikey to publish data to Azure and `TelemetryClient.java` has all the definition of track() methods including
`void trackMetric(String name, double value, int sampleCount, double min, double max, Map<String, String> properties)` , `void trackMetric(String name, double value) and `void trackMetric(MetricTelemetry telemetry)`. All the Spring Metrics would go as custom metrics to AI.

I believe this would be the required pieces for this exporter. We would need to do some transformations to achieve this according to the backend schema. Let me know how would you think is the best way to proceed.

**Comment by jkschneider** [comment]
@dhaval24 A stub for Azure exists at https://github.com/micrometer-metrics/micrometer/blob/azure/implementations/micrometer-registry-azure/src/main/java/io/micrometer/azure/AzureMeterRegistry.java.

**Comment by jkschneider** [comment]
When you're ready to test, navigate to [SampleConfig](https://github.com/micrometer-metrics/micrometer/blob/master/samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/utils/SampleConfig.java#L20) and change it to `SampleRegistries.azure(..)` rather than `SampleRegistries.jmx()`. Then you can test each metric type one at a time (e.g. `GaugeSample`, `CounterSample`, `TimerSample`).

**Comment by jkschneider** [comment]
https://github.com/Microsoft/ApplicationInsights-Java/pull/518

**Comment by dhaval24** [comment]
@jkschneider thank you very much for sending all this out. I would take a look at this.

**Comment by dhaval24** [comment]
@spencergibb and @jkschneider the POM for application insights is now fixed and it does not reference any of the dependencies like Guava / HttpClient. They are shaded and excluded from the POM now.
