### ISSUE TITLE
 Micrometer Slack channel not active? 

### ISSUE THREAD

**Issue by patpatpat123** [micrometer-metrics/micrometer#4411]
Hello,

The readme has:

"Join the [Micrometer Slack](https://slack.micrometer.io/) to share your questions, concerns, and feature requests."

But the link seems to be broken.
A colleague of fine also facing this issue.

Thank you

**Comment by jonatan-ivanov** [comment]
It seems the [workspace](https://micrometer-metrics.slack.com/) got suspended, we are contacting Slack Support to resolve it.

**Comment by jonatan-ivanov** [comment]
It's back, sorry for the inconvenience.

**Comment by dancer1325** [comment]
@jonatan-ivanov , how to request access? https://slack.micrometer.io/ nor

**Comment by jonatan-ivanov** [comment]
https://slack.micrometer.io should be the way but after a certain number of people who signed up with that invite, Slack expires it (even if the invite is non-expiring). :(
The easiest way to fix this is reporting it to us (thanks for doing that), I fixed the link, could you please try again?
