### ISSUE TITLE
Prometheus PrometheusTimer java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by DmiyDing** [micrometer-metrics/micrometer#4454]
Spring Boot 2.0.x
micrometer: 1.5.6

<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-registry-prometheus</artifactId>
</dependency>

Error:
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by shakuzen** [comment]
Do you have unbounded, high cardinality tags? It's hard to help more without more information. Ideally a minimal sample application that reproduces the issue. Also, please ensure that the issue reproduces on a supported version. Spring Boot 2.0.x and Micrometer 1.5.6 are end of life versions.

**Comment by DmiyDing** [comment]
> Do you have unbounded, high cardinality tags? It's hard to help more without more information. Ideally a minimal sample application that reproduces the issue. Also, please ensure that the issue reproduces on a supported version. Spring Boot 2.0.x and Micrometer 1.5.6 are end of life versions.

Good. I am using Spring Boot version 2.3.6.RELEASE and Micrometer Registry Prometheus version 1.5.6. By analyzing with MAT, I have discovered the existence of multiple PrometheusTimer objects that fail to undergo automated garbage collection. Kindly advise when the CollectorMap inside the PrometheusMeterRegistry class is purged, and whether manual cleanup is required. Below is my code snippet - thank you!

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>simpleclient</artifactId>
                    <groupId>io.prometheus</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>HdrHistogram</artifactId>
                    <groupId>org.hdrhistogram</groupId>
                </exclusion>
            </exclusions>
        </dependency>

`    @Bean
    public MeterRegistryCustomizer<MeterRegistry> metricsCommonTags() {
        return registry -> registry.config()
                .commonTags("application", appName)
                .meterFilter(
                        new MeterFilter() {
                            @Override
                            public DistributionStatisticConfig configure(Meter.Id id, DistributionStatisticConfig config) {
                                if (id.getType() == Meter.Type.TIMER & id.getName().matches(HTTP_METER_ID_NAME)) {
                                    return DistributionStatisticConfig.builder()
                                            .percentilesHistogram(true)
                                            .percentiles(0.5, 0.90, 0.95, 0.99)
                                            .serviceLevelObjectives(Duration.ofMillis(50).toNanos(),
                                                    Duration.ofMillis(100).toNanos(),
                                                    Duration.ofMillis(200).toNanos(),
                                                    Duration.ofSeconds(1).toNanos(),
                                                    Duration.ofSeconds(5).toNanos())
                                            .minimumExpectedValue(Duration.ofMillis(1).toNanos())
                                            .maximumExpectedValue(Duration.ofSeconds(5).toNanos())
                                            .build()
                                            .merge(config);
                                } else {
                                    return config;
                                }
                            }
                        }
                );
    }`

**Comment by DmiyDing** [comment]
See [https://github.com/spring-projects/spring-boot/issues/11338](https://github.com/spring-projects/spring-boot/issues/11338)

**Comment by shakuzen** [comment]
The versions you mentioned are both end of life and unsupported (see Spring Boot's support timeline [here](https://spring.io/projects/spring-boot#support)). The issue you linked is almost 6 years old and that particular issue was fixed. Without understanding more about your usage, we can't really say where the issue might be.

In general, though, if you are creating meters with unbounded cardinality, your memory usage will increase with each new meter created. Meters will not be garbage collected because it is expected they will continue to be used and reported when publishing (in the case of Prometheus, scraping) happens every step (scrape) interval. It is advised to avoid high cardinality tags to avoid this issue. See, for example, our warning in the documentation in [this section](https://micrometer.io/docs/concepts#_tag_values):

>Beware of the potential for tag values coming from user-supplied sources to blow up the cardinality of a metric. You should always carefully normalize and add bounds to user-supplied input. Sometimes, the cause is sneaky. Consider the URI tag for recording HTTP requests on service endpoints. If we do not constrain 404’s to a value like NOT_FOUND, the dimensionality of the metric would grow with each resource that cannot be found.
