### ISSUE TITLE
Expose `VM.maxDirectMemory()` value

### ISSUE THREAD

**Issue by be-hase** [micrometer-metrics/micrometer#4456]
**Please describe the feature request.**

I would like to expose the maximum value that can be allocated by direct buffer.
In other words, the value that can be obtained with `VM.maxDirectMemory()`.
https://github.com/openjdk/jdk17/blob/master/src/java.base/share/classes/jdk/internal/misc/VM.java#L131-L137

By the way, the amount currently used and pooled in direct buffer is currently exposed.
https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmMemoryMetrics.java#L65-L75

**Rationale**

I would like to set an alert based on utilization. To do so, I would like to know the value of `VM.maxDirectMemory()`.

```
# alert when it exceeds 80%
(jvm_buffer_memory_used_bytes / VM.maxDirectMemory()) > 0.8
```

**Additional context**

Unfortunately, VM.java is in the `jdk.internal.misc` package. Therefore, it cannot be accessed.

```
Symbol is declared in module 'java.base' which does not export package 'jdk.internal.misc'
```

We need to write `--add-exports`, ...which is subtle.

`VM.maxDirectMemory()` is calculated as follows, which may be implemented in micrometer-side code. However, it may give out wrong information if the JDK behavior is changed.
https://github.com/openjdk/jdk17/blob/master/src/java.base/share/classes/jdk/internal/misc/VM.java#L243-L257

**Comment by marcingrzejszczak** [comment]
I don't think it's a good idea to copy that code to micrometer. That way we would have to ensure that the compatibility is met. Are you currently able to create that metric by yourself?

**Comment by be-hase** [comment]
Agreed. Yes, we have no choice but to get the metrics in our own code now.
We will also consider to feedback to the JDK side.

**Comment by marcingrzejszczak** [comment]
Great! I'm closing this then.
