### ISSUE TITLE
Build-in support for Sumo Logic

### ISSUE THREAD

**Issue by dmolenda-sumo** [micrometer-metrics/micrometer#4488]
I am requesting to include built-in support for Sumo Logic, which will enable sending data directly to it. It would be great to expand the built-in support by adding another analytic platform. If it is feasible, I would like to add this support myself. Please let me know if this is something that can be considered.

**Comment by marcingrzejszczak** [comment]
I'm not an expert with Sumo Logic but since Sumo Logic already has an OTel collector you can use the OTLP registry to send metrics there.

Also, do you think that creating the Sumo Logic Meter Registry inside Sumo Logic's Github would be possible?
