### ISSUE TITLE
Unreliable Kafka Metrics with Reactor Kafka

### ISSUE THREAD

**Issue by kschlesselmann** [micrometer-metrics/micrometer#4491]
We're using Reactor Kafka with the Spring Cloud Stream Kafka Reactive binder here and noticed that the Kafka Client Metrics are really unreliable. Sometime metrics like `kafka.producer.topic.record.send.total.count` are missing for _hours_ and suddenly re-appear. Sometime if we scale our services up and down some other metrics pop up and things that have been there suddenly vanish. If we monitor custom metrics or the Kafka Cluster everything is working fine though. Any suggestions what's going on here?

**Environment**
 - Spring Boot 3.2.0, Spring Cloud 2023.0.0
 - Micrometer version 1.12.0
 - Micrometer registry cloudwatch2
 - OS: AWS ECS Fargate with a container built by the Spring Boot buildpack (builder/jammy is the default)
 - Java version: JRE 21

**To Reproduce**
Run a Spring Cloud Stream Kafka Reactive service with multiple functions.

**Expected behavior**
All Kafka Consumer/Producer metrics are constantly reported.

**Additional context**
![image](https://github.com/micrometer-metrics/micrometer/assets/3634869/dd4896ea-3c05-4402-b298-5a0ede751f2d)

Our configuration looks like
```kotlin
@Configuration(proxyBeanMethods = false)
class ReactorKafkaConfiguration {

    @Bean
    fun receiverOptionsCustomizer(meterRegistry: MeterRegistry): ReceiverOptionsCustomizer<Any, Any> =
        ReceiverOptionsCustomizer { _, receiverOptions ->
            receiverOptions.consumerListener(MicrometerConsumerListener(meterRegistry))
        }

    @Bean
    fun senderOptionsCustomizer(meterRegistry: MeterRegistry): SenderOptionsCustomizer<Any, Any> =
        SenderOptionsCustomizer { _, senderOptions ->
            senderOptions.producerListener(MicrometerProducerListener(meterRegistry))
        }

    @Bean
    fun binderCustomizer(
        receiverOptionsCustomizers: ObjectProvider<ReceiverOptionsCustomizer<*, *>>,
        senderOptionsCustomizers: ObjectProvider<SenderOptionsCustomizer<*, *>>,
    ): BinderCustomizer = BinderCustomizer { binder, _ ->
        if (binder is ReactorKafkaBinder) {
            binder.apply {
                receiverOptionsCustomizers(receiverOptionsCustomizers)
                senderOptionsCustomizers(senderOptionsCustomizers)
            }
        }
    }

    @Bean
    fun kafkaMetricsMeterFilter(): MeterFilter = object : MeterFilter {

        private val tagsToRemove = setOf(
            "client.id",
            "reactor-kafka.id",
            "kafka.version",
            "node.id",
        )

        override fun map(id: Meter.Id): Meter.Id = if (id.name.startsWith("kafka.")) {
            id.tags
                .filter { it.key !in tagsToRemove }
                .let { id.replaceTags(it) }
        } else {
            id
        }
    }
}
```

**Comment by marcingrzejszczak** [comment]
I wonder if the metrics are not there for hours or for some reason they are being reported to the backend after hours? Is there a way for you to check it?

This is using the new kafka-reactor instrumentation I guess, so I will page @artembilan just in case something catches his attention here

**Comment by kschlesselmann** [comment]
@marcingrzejszczak Yeah, we're using the new reactor-kafka instrumentation. As for metrics being reported: We're using micrometer + AWS CloudWatch metrics for years now and all metrics but the the reactor-kafka metrics are very reliable and without issues so far.

**Comment by kschlesselmann** [comment]
@marcingrzejszczak Do you need further information?

**Comment by artembilan** [comment]
I see you have that `MeterFilter` which probably does something magical for your metrics.
It is hard to say what is going on without very simple project to reproduce.
Let's start from just Reactor Kafka, without any Spring Cloud and that AWS CloudWatch!

**Comment by kschlesselmann** [comment]
@artembilan OK, this would require quite some effort on our side. I'd have to check that with my team. The `MeterFilter` is just to save us money since you pay per dimension on AWS CloudWatch.

**Comment by artembilan** [comment]
Thanks for confirmation. 
I don't know what is `Cloudwatch`, but probably that's where we are struggle when those metrics suppose to be emitted.
And as you said it happens only when several clients does that in parallel. So, probably there is some singleton context which is overridden by those different threads.

Maybe there is the way to reproduce this even without Spring Boot and that CloudWatch?
