### ISSUE TITLE
Add Meter for process CPU time

### ISSUE THREAD

**Issue by simonzn** [micrometer-metrics/micrometer#4498]
**Please describe the feature request.**
I would like to have a meter for the accumulated CPU time used by a JVM process.

**Rationale**
We use the accumulated CPU time in derived metrics; e.g., we derive the percentage of time spent with garbage collection from the accumulated CPU time and the GC times.

**Additional context**
We currently add the meter in our applications, but we think it would be generally useful.

**Comment by shakuzen** [comment]
> e.g., we derive the percentage of time spent with garbage collection from the accumulated CPU time and the GC times.

FYI, this is something we try to offer with the `JvmHeapPressureMetrics` binder
