### ISSUE TITLE
access to timer percentiles

### ISSUE THREAD

**Issue by randysecrist** [micrometer-metrics/micrometer#450]
I am writing a simple metric endpoint using micrometer to dump timer metrics to JSON and/or to a log.  From the docs, it looks like timers automatically get histogram information published ... but just in case I used the builder to set up the buckets when the measurement is recorded.

Timers are being created as such:

```java
        Timer.builder("blah")
                .description("Record the time of a thing ...")
                .publishPercentiles(0.5, 0.95, 0.99)
                .publishPercentileHistogram()
                .register(registry).record(time);
```

I can fetch meters and measurements simple enough from a registry using this code:

```java
        this.registry.getMeters().stream().forEach((Meter meter) -> {
            log.info("Name: " + meter.getId().getName());
            meter.measure().forEach(measurement -> {
                log.info(measurement.toString());
            });
        });
```

However; I am not seeing (for timer types) any percentile information show up in logs.  I only observer COUNT, TOTAL_TIME and MAX measurements.  (Using jconsole I can clearly see percentile stats under attributes).

I have been trying to figure out how the recorded histogram data can be accessed from the registry; or other published source.  I can't find this in the docs; any guidance on API usage?

**Comment by jkschneider** [comment]
Understandable. Since percentile data is structured very differently from system to system, it doesn't show up in the default set "measurements". Once you have access to a `Timer`, you can access its percentiles like so:

```
ValueAtPercentile[] preconfiguredPercentiles = timer.takeSnapshot(false).percentileValues();
```

You can also just snag a percentile from a timer at any time, regardless of whether or not it was preconfigured to publish it:

```
timer.percentile(0.9, TimeUnit.MILLISECONDS); // for 90th percentile
```

**Comment by randysecrist** [comment]
Awesome; thanks for clarification!
