### ISSUE TITLE
Whether the granularity of the lock is too broad？Can the meter granularity be locked to ensure that simultaneous changes to tens of thousands of metrics are not overly blocked?

### ISSUE THREAD

**Issue by Tian90coder** [micrometer-metrics/micrometer#4504]
https://github.com/micrometer-metrics/micrometer/blob/225234755f1ad70cd67eea167862c1cedddc0cd2/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L621C41-L621C41

**Comment by marcingrzejszczak** [comment]
I'm sorry but I don't understand the question. Can you show a reproducer to the problem? Have you actually encountered a problem? Which versions of micrometer are you using?

**Comment by Tian90coder** [comment]
In my case.I registered a bunch of meters, include counter, timer, gauge.

Different tag combinations will produce unique meter, it results in a meter being generated for each interface and source IP in the RPC scenario. Therefore, my application contains tens of thousands of meters.

When I change the tag combination, I will delete all old meters. At the same time, new requests will generate new meters.

However, due to the lock in the map dimension, the generation process is excessively blocked.

I think lock in the key dimension(like meter id) will alleviate this problem.

So, the key of this question is the granularity of the lock.

**Comment by marcingrzejszczak** [comment]
Would it be possible for you to create a reproducer of this problem? I don't see anyone else complaining about the performance of the current solution...
