### ISSUE TITLE
Deprecate jooQ support

### ISSUE THREAD

**Issue by marcingrzejszczak** [micrometer-metrics/micrometer#4508]
more context here https://github.com/micrometer-metrics/micrometer/issues/2686

**Comment by marcingrzejszczak** [comment]
We could consider leveraging the multirelease jar to support this? (check this [issue](https://github.com/micrometer-metrics/micrometer/issues/3828))

**Comment by shakuzen** [comment]
I commented on that proposal over in https://github.com/micrometer-metrics/micrometer/issues/2686 but I've proposed another way we could perhaps salvage jOOQ instrumentation there. Let's put deprecation on hold to see if we can get some feedback from our jOOQ users on that.

**Comment by shakuzen** [comment]
#4727 is a path to supporting the latest versions of jOOQ so deprecation should no longer be needed.
