### ISSUE TITLE
actions/stale doesn't seem to work intentionally

### ISSUE THREAD

**Issue by izeye** [micrometer-metrics/micrometer#4518]
For example, https://github.com/micrometer-metrics/micrometer/issues/3962#issuecomment-1864821676 should have been closed already.

The default value (30) for `operations-per-run` doesn't seem to be enough to run it properly at the moment as follows:

```
Warning: No more operations left! Exiting...
Warning: If you think that not enough issues were processed you could try to increase the quantity related to the  operations-per-run (​[https://github.com/actions/stale#operations-per-run​)](https://github.com/actions/stale#operations-per-run%E2%80%8B))  option which is currently set to  30
```

See https://github.com/micrometer-metrics/micrometer/actions/runs/7374098871/job/20064104274

**Comment by marcingrzejszczak** [comment]
Temporarily increased the value to [300](https://github.com/micrometer-metrics/micrometer/commit/f766d261076cd1e04f7dd87fdc7192560b3432b1)
