### ISSUE TITLE
urlTemplate not marked as nullable for RestTemplateExchangeTagsProvider

### ISSUE THREAD

**Issue by michael-barker** [micrometer-metrics/micrometer#453]
When upgrading to 1.0.0 we ran into an issue where urlTemplate was not marked nullable for `RestTemplateExchangeTagsProvider::getTags`.  As of 1.0.0 nulls are now passed for urlTemplate when `RestTemplate` is used with a `URI`.  This resulted in a NPE as runtime in our `RestTemplateExchangeTagsProvider` implementation.

**Comment by michael-barker** [comment]
I'll have a PR shortly.

**Comment by jkschneider** [comment]
Marking `@Nullable` is a correctness issue that helps build better custom `RestTemplateExchangeTagsProvider`. There isn't anything to fix in the `DefaultRestTemplateExchangeTagsProvider`. No change to Boot 2 required.
