### ISSUE TITLE
Make global static composite on `Metrics` settable per thread

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#456]
Adding `ThreadLocal` indirection to the global static composite would make overriding it for tests possible.

**Comment by aconst-null** [comment]
+1 for this.

Related would be guidance / steering in the docs around injection and use of a registry vs using `Metrics.xxx` static methods to create. The latter is far more convenient - but potentially has issues with parallel test runners (presumably this issue would go some way to resolve that!). The former is more 'pure' - but seems higher-barrier if you want to use metrics ubiquitously without AOP

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2018. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it. Also usage of the global static instances is discouraged.
