### ISSUE TITLE
URI tag of http.server.requests meter contains templated URI

### ISSUE THREAD

**Issue by edeandrea** [micrometer-metrics/micrometer#458]
Seems that when looking at the `http.server.requests` metric of a Spring Boot/Spring MVC application the URI tag has the value of a templated URI and not the actual expanded URI.

For example, my controller is annotated with `@RequestMapping("/things")` and my action method has `@GetMapping(path = "/{id}")`, when looking at the output of the meter I see

```
Meter: name = http.server.requests, description = null, type = TIMER, tags = [ImmutableTag{key='exception', value='None'}, ImmutableTag{key='method', value='GET'}, ImmutableTag{key='status', value='200'}, ImmutableTag{key='uri', value='/things/{id}'}], measurements = [Measurement{statistic='COUNT', value=3.0}, Measurement{statistic='TOTAL_TIME', value=939.321339}, Measurement{statistic='MAX', value=923.181765}]
```

I was expecting to see

```
Meter: name = http.server.requests, description = null, type = TIMER, tags = [ImmutableTag{key='exception', value='None'}, ImmutableTag{key='method', value='GET'}, ImmutableTag{key='status', value='200'}, ImmutableTag{key='uri', value='/things/1'}], measurements = [Measurement{statistic='COUNT', value=3.0}, Measurement{statistic='TOTAL_TIME', value=939.321339}, Measurement{statistic='MAX', value=923.181765}]
```

Is this by design? I see it similarly on the `RestTemplate` customization with the `http.client.requests` metric where if I make an outbound REST call to `/somewhereElse/{id}` the URI is also template-ized there.

**Comment by jkschneider** [comment]
Absolutely intentional. This way you can plot latency against that endpoint and not the endpoint _given_ some particular parameters. 

Shipping a resolved URI would explode the total number of tags at the monitoring system and can overwhelm the backend.

**Comment by paulosuzart** [comment]
Is there any plan to add the path parameters as part of the tags? This could be disabled by default and enabled if needed. This would avoid creating Timers by hand based on path parameter. 

Of course it would be of developer responsibility to provide mechanisms to avoid an explosion of tag values on metrics system. But yet something in our scenario relevante to have.

**Comment by mweirauch** [comment]
@paulosuzart Ship your own `WebMvcTagsProvider` in this case. You can reuse stuff from the `DefaultWebMvcTagsProvider` and `WebMvcTags`.

**Comment by dennisvang** [comment]
> [@paulosuzart](https://github.com/paulosuzart) Ship your own `WebMvcTagsProvider` in this case. You can reuse stuff from the `DefaultWebMvcTagsProvider` and `WebMvcTags`.

With the "new" observation api, the following solution appears to work, replacing the uri path pattern by the full path:

```java
package org.example.package.filter;

import io.micrometer.common.KeyValue;
import io.micrometer.observation.Observation;
import io.micrometer.observation.ObservationFilter;
import org.springframework.http.server.observation.ServerRequestObservationContext;
import org.springframework.stereotype.Component;

import java.util.Optional;

@Component
public class RequestObservationFilter implements ObservationFilter {

    @Override
    public Observation.Context map(Observation.Context context) {
        if (context instanceof ServerRequestObservationContext serverContext) {
            Optional<String> requestURI = Optional.ofNullable(serverContext.getCarrier().getRequestURI());
            // replace existing uri path pattern by full uri path (actually high cardinality...)
            context.addLowCardinalityKeyValue(KeyValue.of("uri", requestURI.orElse("")));
        }
        return context;
    }
}
```

This is based on some examples from the [spring observability docs].

@mweirauch Would this be a reasonable approach, or is there a better way?

I'm adding the full uri as *low* cardinality, even though theoretically it is [high cardinality] (also see [here]), just to make sure it shows up in the metrics without having to write a custom handler.

(sorry for bumping an ancient thread)

[spring observability docs]: https://docs.spring.io/spring-framework/reference/integration/observability.html#observability.config.conventions
[high cardinality]: https://docs.micrometer.io/micrometer/reference/concepts/high-cardinality-tags-detector.html#_understand_high_cardinality
[here]: https://github.com/spring-projects/spring-framework/blob/fb10455d3cc34b02f05894d131fc3b6ebc39f6cb/spring-web/src/main/java/org/springframework/http/server/observation/DefaultServerRequestObservationConvention.java#L181

**Comment by shakuzen** [comment]
@dennisvang indeed an old closed issue is not the best place to ask this. As the documentation you linked points out, you can provide your own `ServerRequestObservationConvention` implementation and extend from the `DefaultServerRequestObservationConvention` to only customize the parts you need. If you are using Spring Boot and register your custom `ServerRequestObservationConvention` as a Bean, it will be used by auto-configuration. That would allow you to, for example, do something like the following:

```java
@Bean
DefaultServerRequestObservationConvention customServerRequestObservationConvention() {
    return new DefaultServerRequestObservationConvention() {
        @Override
        protected KeyValue uri(ServerRequestObservationContext context) {
            // TODO replace with custom logic to get URI KeyValue
            return super.uri(context);
        }
    };
}
```

**Comment by dennisvang** [comment]
Thanks @shakuzen for your kind response.

Looks like we could reuse [DefaultServerRequestObservationConvention.httpUrl()] to match the result from my [example], as in:

```java
            @Override
            protected KeyValue uri(ServerRequestObservationContext context) {
                return super.httpUrl(context);
            }
```

[DefaultServerRequestObservationConvention.httpUrl()]: https://github.com/spring-projects/spring-framework/blob/fb10455d3cc34b02f05894d131fc3b6ebc39f6cb/spring-web/src/main/java/org/springframework/http/server/observation/DefaultServerRequestObservationConvention.java#L179

[example]: https://github.com/micrometer-metrics/micrometer/issues/458#issuecomment-3812488064

**Comment by dennisvang** [comment]
Another alternative I had in mind subclasses `OncePerRequestFilter` and creates a custom counter using the `MeterRegistry`, as in the (simplified) example below.

```java
@Component
public class CustomMetricFilter extends OncePerRequestFilter {

    private MeterRegistry meterRegistry;

    public CustomMetricFilter(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;
    }

    @Override
    public void doFilterInternal(
            final HttpServletRequest request, final HttpServletResponse response, final FilterChain filterChain
    ) throws IOException, ServletException {
        meterRegistry.counter("my.custom.metric","uri", request.getRequestURI()).increment();
        filterChain.doFilter(request, response);
    }
}
```

@shakuzen Are there any obvious drawbacks to such an approach (other than the use of [counters vs timers]), compared with the `ObservationConvention`-based approach?


[counters vs timers]: https://docs.micrometer.io/micrometer/reference/concepts/counters.html

**Comment by jonatan-ivanov** [comment]
One drawback might be having redundant counters (the doc what you linked) but if you really want to do the above (separate counters for high cardinality data), there might be a better way than using a filter.

Since Spring Framework is already instrumented, adding a custom filter that creates a counter is basically re-instrumenting it. If you look at the Observation API, it has a component called `ObservationHandler`. This component is there to produce outputs based on existing Observations.
You can create your own `ObservationHandler` that creates a counter every time Spring Framework creates an HTTP observation so you don't need to re-instrument Spring, you just need to tell what to do with the data from the existing instrumentation. See [`DefaultMeterObservationHandler#onStop`](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/observation/DefaultMeterObservationHandler.java#L87-L97), in the `onStop` method, you can increment a counter and in `supportsContext`, you can decide which `Observations` you want to handle.
