### ISSUE TITLE
Creating a `TimedThreadPoolTaskExecutor` suppresses auto-configuration of default Spring metrics

### ISSUE THREAD

**Issue by dheld-expedia** [micrometer-metrics/micrometer#459]
To support Spring's `@Async` functionality, an application can provide a custom `AsyncTaskExecutor` which defines the thread pool on which `@Async` tasks run.  This can be instrumented via a `TimedThreadPoolTaskExecutor`, but if one is created, then the default Spring metrics like `JvmGcMetrics`, `JvmMemoryMetrics`, etc. no longer appear.

**Comment by jkschneider** [comment]
@dheld-expedia Trying to recreate. Can you examine the test in 078a2cf and see what I'm doing differently?
