### ISSUE TITLE
Heap Memory not decreasing for low cardinality metrics even when requests are not coming to Application

### ISSUE THREAD

**Issue by santpandey** [micrometer-metrics/micrometer#4590]
Hi. We have a setup where we are using SpringBoot and using Micrometer to push metrics data to Prometheus. The metrics which we are pushing has low cardinality. We followed this [doc](https://develotters.com/posts/high-cardinality/).
System:
4GB Ram, Heap Size : 2GB
Micrometer version : 1.10.7

Issue:
When there's huge rate of incoming requests, the heap size increases (Expected). However if there's no request in the next few minutes, the increased memory doesn't revert or reduce back. When the requests come again, the heap size again increases from the last increased level. But it never decreases. We also invoked `actuator/prometheus` endpoint to determine if any new metrics are getting created(because its visible if new ones are getting created). However number of metrics are same throughout.

Help:
Need assistance/suggestions or best practices on how can we reduce the heap memory when the application is not receiving request at all.

**Comment by marcingrzejszczak** [comment]
Do you have the same observation when micrometer is not on the classpath? Are you sure that this is related to metrics?

**Comment by santpandey** [comment]
Let me check this and update here with my findings.

**Comment by jonatan-ivanov** [comment]
I think what is happening here that your GC (as most GCs) does not want to run a collection unless it is necessary (GC is work, the JVM will not burn CPU cycles on it if it does not need to).

Try to trigger GC or keep traffic flowing, you should see change in the heap size eventually.
I have a project that you can use to simulate this: https://github.com/jonatan-ivanov/resourceater. It can create and release resources that occupy as much heap as much you want.
