### ISSUE TITLE
Document Prometheus registry onMeterRegistrationFailed callback

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#4622]
This is exactly what happened. I'm an app using micrometer + some custom registry to micrometer + prometheus.
I spent a few hours trying to figure out why some metrics don't appear after adding prometheus.
I think it would be better to make this behaviour configurable.

_Originally posted by @angry-cellophane in https://github.com/micrometer-metrics/micrometer/issues/2400#issuecomment-859792366_

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer/pull/4878 to try to resolve this.

**Comment by shakuzen** [comment]
Thanks so much, @izeye.
Closed by #4878
