### ISSUE TITLE
Custom micrometer observation context is not propagating to child observations (http server to grpc client)

### ISSUE THREAD

**Issue by KostadinAlmishev** [micrometer-metrics/micrometer#4635]
**Describe the bug**
I have:

- HTTP server which calls a GRPC client
- spring HTTP filter which sets an object in an observation context
  - GRPC ClientInterceptor which gets this object from the observation context.

http request -> service -> spring http filter -> grpc ClientInterceptor

The problem is that when I try to get the object from the observation context in the GRPC client interceptor, it is null. However, in a parentObservation context I get it successfully. I don't have this problem with HTTP clients (for example feign interceptors).

As workaround I am using currently:
```java
ObservationRegistry registry...
// ...
Optional.ofNullable(registry.getCurrentObservation())
                .map(Observation::getContext)
                .map(Observation.Context::getParentObservation)
                .map(ObservationView::getContextView)
                .map(contextView -> contextView.get(key));
```
... but I think It is not a good idea to search in the parent observations.

Expecting the object to be present in the current observation:
```java
Optional.ofNullable(registry.getCurrentObservation())
                .map(Observation::getContext)
                .map(context -> context.get(key));
```

**Environment**

 - Micrometer version [e.g. 1.8.6]
 - OS: macOS, Linux
 - Java version: 17

**To Reproduce**

- Register grpc observation interceptors:
```
    @GrpcGlobalClientInterceptor
    @Order(HIGHEST_PRECEDENCE)
    public ClientInterceptor globalObservationClientInterceptor(ObservationRegistry observationRegistry) {
        return new ObservationGrpcClientInterceptor(observationRegistry);
    }
    
    @GrpcGlobalServerInterceptor
    @Order(HIGHEST_PRECEDENCE)
    public ServerInterceptor globalObservationServerInterceptor(ObservationRegistry observationRegistry) {
        return new ObservationInterceptorPropagatingGrpcServerInterceptor(observationRegistry);
    }
```
- Register one GRCP client interceptor, which reads object from observation context
- Set the object in the observation context during http observation
- Make http call

**Expected behavior**
Object should be present in the current observation context in grpc client interceptors.

**Comment by jonatan-ivanov** [comment]
>The problem is that when I try to get the object from the observation context in the GRPC client interceptor, it is null.

What object are you expecting there and where do you set it?

>Micrometer version [e.g. 1.8.6]

Providing the Micrometer version could help.

**Comment by KostadinAlmishev** [comment]
> What object are you expecting there and where do you set it?

I am setting just a string in OncePerRequestFilter with this code:
```java
static <T> void putToContext(ObservationRegistry registry, Object key, T object, String logErr) {
        Optional.ofNullable(registry.getCurrentObservation())
                .ifPresentOrElse(observation -> observation.getContext().put(key, object),
                        () -> log.error(logErr));

    }
```

I am expecting the string to be present in my GrpcClientInterceptor in currentObservation context. But it is null. It is present in parent observation context view. With feign interceptors I don't have this problem.

> Providing the Micrometer version could help.

1.12.1

**Comment by ttddyy** [comment]
Hi,

I haven't fully grasped your setup, but it appears that you're placing an object in the observation context created by HTTP. If your gRPC interceptor is invoked after Micrometer's ObservationGrpcClientInterceptor opens a new observation scope, your current observation is essentially the one created by gRPC, with its parent being the one created by HTTP. Consequently, adding a key-value pair to the parent results in it being stored in the parent context.

It's important to consider the order in which gRPC interceptors are called. So, arrange the interceptor registration order based on your specific use case.


If that doesn't solve the problem, I recommend creating a [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example) and sharing it in this ticket.

**Comment by jonatan-ivanov** [comment]
`Observation.Context` is not propagated between `Observation`s and we are not planning to do this in the future. `Observation.Context` is a data holder for a single `Observation`, it contains the name of the observation, high/low cardinality key values and extra custom object that you add. Propagating it would mean that the name/key values/custom objects you set in an http observations would creep into the grpc observations and you will end up things like having an http method name tag in your grpc observation. :)

What you should do instead is with having the grpc observation, move up on the chain of parents till you find the one you need (http) and get the data from there.
