### ISSUE TITLE
Dependency BOM

### ISSUE THREAD

**Issue by flozano** [micrometer-metrics/micrometer#469]
It would be really useful to have a dependency BOM that avoids dependency-managing all dependencies one by one.

**Comment by wilkinsona** [comment]
I was just about to raise an issue for this. I'd really like to see Micrometer provide a bom. Right now Spring Boot manages each Micrometer module individually. As a result, we sometimes [miss one](
https://github.com/spring-projects/spring-boot/pull/16178). A bom would be of great benefit to Boot and also, IMO, to those using Micrometer without Boot.
