### ISSUE TITLE
access rate info on counters and timers ...

### ISSUE THREAD

**Issue by randysecrist** [micrometer-metrics/micrometer#470]
I have another followup question ...

JMX stats show for distribution summaries and timers rates based on(1, 5, and 15) minute intervals.  There is also a mean rate.

So I can see it is being recorded and stored in memory somehow ... how is that accessible from the `io.micrometer.core.instrument.Meter` api?

Is it possible to set arbitrary intervals for rate collection (say 60 minutes) during counter creation?

**Comment by jkschneider** [comment]
@randysecrist For JMX, Micrometer is applying a `HierarchicalNameMapper` to the dimensional meter id and then delegating to Dropwizard metrics to decide what structure to use for exposing the data to JMX.

I don't see any way on the Dropwizard interface to configure the intervals, they are hard coded.

**Comment by randysecrist** [comment]
The more I think about it; the more this specific use case may not be a fit for micrometer.  (Other use cases still are).  This can probably be closed.

**Comment by jkschneider** [comment]
OK. I guess I'm trying to say that accessing rate over an interval _is_ possible in almost every dimensional monitoring system we support. It looks a little different depending on what the system is, but that functionality is always present. Just interact with a regular Micrometer `Counter` and the rate will be derivable.
