### ISSUE TITLE
Add Support for @MeterTag to @Counted

### ISSUE THREAD

**Issue by ColdFireIce** [micrometer-metrics/micrometer#4725]
Hi there,

I would like to count method calls with an enum in the parameters and use these as tags for the counter. Something analogue to to the @Timed annotation.
It would be super to have the option to add an `MeterAnnotationHandler` to the `CountedAspect`, as you can for the `TimedAspect`.

I'm not sure if this needs more explanation or an example?

Best regards

**Comment by shakuzen** [comment]
Thanks for the enhancement request. I think it makes sense to bring CountedAspect support up to the level of TimedAspect with respect to `@MeterTag`. Is this something you'd be willing to submit a pull request for?

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer/pull/4958 to try to resolve this.
