### ISSUE TITLE
Observation API bird's eye view

### ISSUE THREAD

**Issue by brunobat** [micrometer-metrics/micrometer#4726]
**Request.**
It would be great to have a high level overview on the documentation on how the Observation API works. 
This could be done by enumerating and defining the different functional modules and explain their motivation and relationship with other modules. I see some big blocks like:
* Observation and ObservationView
* Context (the different ones)
* Handlers and Composition
* Conventions
* How it can be used for metrics and tracing and how it cannot be used for metrics.

**Rationale**
This is important for anyone wanting to integrate the Observation API on their own framework or for someone that just wants to instrument a library.

**Comment by brunobat** [comment]
CC @jonatan-ivanov @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
I understand that we should expand what we have [here](https://docs.micrometer.io/micrometer/reference/observation/handler.html) with additional information?
