### ISSUE TITLE
Support StackDriver

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#474]

**Comment by triberraar** [comment]
Hej,
I am looking into stackdriver and google cloud for my boot app and would love metrics through micrometer. I was wondering if you guys are on coarse to release it?

**Comment by jkschneider** [comment]
We are. For unrelated work, I believe this is a must have for 1.1.0

**Comment by triberraar** [comment]
Cool, looking forward to using it.

**Comment by michael-barker** [comment]
@triberraar If you're using GKE another option is to use [Prometheus with Stackdriver Kubernetes Monitoring](https://cloud.google.com/monitoring/kubernetes-engine/prometheus).  It's currently in beta.

**Comment by jkschneider** [comment]
@michael-barker Interesting. Are metrics forwarded from this prometheus instance to stackdriver subject to the same 500 metric limit?

**Comment by shakuzen** [comment]
According to that page, seems it is a 1000 metric limit:

> Note: There is presently a limit of 1,000 Prometheus-exported metric descriptions per GCP project.
