### ISSUE TITLE
GC Pause time metric includes concurrent cycle time for Generational ZGC

### ISSUE THREAD

**Issue by rreimann** [micrometer-metrics/micrometer#4764]
**Describe the bug**
For Generational ZGC in Java 21 the `jvm.gc.pause` metric doesn't only measure actual pause times but also concurrent GC cycle times. 

The `gcName(s)` provided by `GarbageCollectorMXBean` / `GarbageCollectionNotificationInfo` for Generational ZGC are different from the `gcName(s)` for single-generation ZGC...

gcNames for ZGC: 
- ZGC Pauses
- ZGC Cycles

gcNames for GenZGC: 
- ZGC Minor Pauses
- ZGC Major Pauses 
- ZGC Minor Cycles
- ZGC Major Cycles

The condition `"ZGC Cycles".equals(name)` to detect concurrent phases for ZGC in [JvmMemory#isConcurrentPhase](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmMemory.java#L39-L42) doesn't work for the above mentioned gcNames for GenZGC. Replacing aforementioned condition with something like `(name.startsWith("ZGC") && !name.endsWith("Pauses"))` should IMHO work for both variants of ZGC.

**Environment**

 - Micrometer version: 1.12.2
 - Micrometer registry: prometheus
 - OS: macOS
 - Java version: openjdk version "21.0.2" 2024-01-16 LTS

**To Reproduce**
Run the following code with the JVM options `-XX:+UseZGC -XX:+ZGenerational` ...
```
import java.lang.management.ManagementFactory;

public class ExampleGarbageCollectorMXBean {
    public static void main(String[] args) {
        // Run 100 GCs
        for (int i = 0; i < 100; i++) {
            System.gc();
        }

        // Print basic information from available beans
        for (final var bean : ManagementFactory.getGarbageCollectorMXBeans()) {
            System.out.println(bean.getName());
            System.out.println("   Count: " + bean.getCollectionCount());
            System.out.println("   Total Time: " + bean.getCollectionTime() + "ms");
            System.out.println("   Average Time: " + (bean.getCollectionTime() / (double)bean.getCollectionCount()) + "ms");
        }
    }
}
```

... which should result in an output like this:
```
ZGC Minor Cycles
   Count: 0
   Total Time: 0ms
   Average Time: NaNms
ZGC Minor Pauses
   Count: 0
   Total Time: 0ms
   Average Time: NaNms
ZGC Major Cycles
   Count: 101
   Total Time: 2292ms
   Average Time: 22.693069306930692ms
ZGC Major Pauses
   Count: 805
   Total Time: 3ms
   Average Time: 0.0037267080745341614ms
```

**Expected behavior**
For Generational ZGC ...
- the time measured by `jvm.gc.pause`  should be the same as ZGC Minor Pauses + ZGC Major Pauses from the output
- the time measured by `jvm.gc.concurrent.phase.time`  should be the same as ZGC Minor Cycles + ZGC Major Cycles from the output

**Comment by shakuzen** [comment]
Thanks for reporting the issue with all the details. I missed this when working on #4258, and although we have a test that, if working, should have caught this, it's disabled because GC can happen before JvmGcMetrics is registered and begins tracking GC metrics:

https://github.com/micrometer-metrics/micrometer/blob/2807c0bcd1a58ae2069e117e45a06c437140a5f0/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetricsTest.java#L106-L131

I'll improve that test so it can run at least with some collectors and make sure this doesn't regress.
