### ISSUE TITLE
Provide abstract spectator implementation for push backends taking step counts

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#48]
Much of the implementation for Datadog, Influx, and Clickhouse is the same. The only real difference is the exposition format.

**Comment by jkschneider** [comment]
@Camelion For Clickhouse support, look at `DatadogRegistry` and `DatadogConfig`. All you should have to do now is extend `AbstractStepRegistry` and provide an implementation of `pushMetrics()` which performs the table creation and insertion. You can also create a `ClickhouseConfig` with any permissions or whatever else is necessary to make the connection.

Once you've got the `ClickhouseRegistry` implementation, you can use it by:

`MeterRegistry registry = new SpectatorMeterRegistry(new ClickhouseRegistry());`

The idea here is that Spectator already collects the correct measurements and performs step interval aggregation correctly, so there is no need for you to implement custom `Meter` types. Really we can use Spectator as our backing instrumentation library and just provide a different exposition format through `pushMetrics()`.

Just thought I'd give you the plan in case you beat me to it ;)

**Comment by Camelion** [comment]
Cool! New clickhouse exporter contains only two classes, but currently quantities measurements not working in `SpectatorMeterRegistry`:(

**Comment by jkschneider** [comment]
I think adding [one more class](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/datadog/DatadogMeterRegistry.java) to hide the fact the registry is Spectator-backed makes it easier to use.

Did your last PR resolve the quantities measurements problem?

**Comment by Camelion** [comment]
no, PR don't fix quantilies problem. Think Micrometer need some changes in Timers and DitributionSummaries, similarly that [i previously do](https://github.com/Camelion/spring-clickhouse-metrics/commit/4ed1c6e2773c0b926667dda280f974b52655245e#diff-1996e15a0eb690831d713b16e8fba45bR54) for ClickhouseTimer/DistributionSummary
