### ISSUE TITLE
OSGi import of javax.annotation and javax.annotation.meta is incorrect

### ISSUE THREAD

**Issue by ponziani** [micrometer-metrics/micrometer#4824]
**Describe the bug**
The manifest file of micrometer-core and micrometer-commons contains the Import-Package "javax.annotation;version=
 "[3.0,4)",javax.annotation.meta;version="[3.0,4)". However, these are not the correct version ranges, as explained in https://github.com/jhy/jsoup/issues/1616#issuecomment-958684482

This results in our Apache Karaf application no longer starting after upgrading to Micrometer 1.11

`Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve micrometer-commons/1.11.9: missing requirement [micrometer-commons/1.11.9] osgi.wiring.package; filter:="(&(osgi.wiring.package=javax.annotation)(version>=3.0.0)(!(version>=4.0.0)))"
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 17 more
`

**Environment**
 - Micrometer version 1.11.9
 - Java version: 17

**Additional context**
As suggested in the jsoup-link, the import could be made optional.

**Comment by shakuzen** [comment]
Resolved by #4825
