### ISSUE TITLE
Failed to bind as java.util.concurrent.ThreadPerTaskExecutor is unsupported.

### ISSUE THREAD

**Issue by loicmathieu** [micrometer-metrics/micrometer#4826]
**Describe the bug**
Micrometer ExecutorServiceMetrics class logs a warning `Failed to bind as java.util.concurrent.ThreadPerTaskExecutor is unsupported.` when runs in Java 21.

**Environment**
 - Micrometer version: 1.12.2
 - Micrometer registry: prometheus
 - OS: Ubuntu 23.10
 - Java version: 21

**Expected behavior**
No warning logs should be visible in the console.

**Comment by dozsa** [comment]
Ran into the same issue. Seems that the Java 21 `ThreadPerTaskExecutor `class is not supported by `ExecutorServiceMetrics`. You can see that in its `bindTo` method. So this will be an enhancement.

**Comment by shakuzen** [comment]
Which executor metrics specifically are you interested in with a `ThreadPerTaskExecutor`?

**Comment by loicmathieu** [comment]
@shakuzen no idea, I just want this warning to disappear and Micrometer to work as usual.

**Comment by shakuzen** [comment]
What do you mean by work as usual? The log message is making you aware something is trying to monitor an ExecutorService that is not supported. There will be no corresponding metrics but nothing is broken, per se. If you don't want the warning log, don't call `ExecutorServiceMetrics.monitor` with something not supported. If we didn't log anything in the case of trying to bind to a `ThreadPerTaskExecutor`, users might be confused why there are no metrics.

Are you configuring this yourself or is some library/framework trying to do this? If the latter, probably that library/framework should be updated to not do this with `ThreadPerTaskExecutor` until/unless it is supported.

**Comment by dozsa** [comment]
By reading the source for both `ExecutorServiceMetrics` and `ThreadPerTaskExecutor` I think the only metric it could capture is `ThreadPerTaskExecutor.threadCount()` which would map to `executor.active`.

**Comment by vad3x** [comment]
It seems it's been fixed here: https://github.com/micronaut-projects/micronaut-micrometer/issues/679

**Comment by loicmathieu** [comment]
OK, let's close it.
Thanks @vad3x

**Comment by angulito** [comment]
For the error
```
Failed to bind as java.util.concurrent.Executors$AutoShutdownDelegatedExecutorService is unsupported.
```
I found a PR which is already created:
https://github.com/micrometer-metrics/micrometer/pull/4315

@shakuzen is that something we could try to move on? I'm using micrometer with java 21 and got:
```
Failed to bind as java.util.concurrent.Executors$AutoShutdownDelegatedExecutorService is unsupported.
``` 
as well. Thank you!

**Comment by shakuzen** [comment]
@angulito that's not really related to this issue. It would have been better to comment on that pull request. I've left a review on it now.
