### ISSUE TITLE
Can't inherit @Timed annotation in custom annotation

### ISSUE THREAD

**Issue by tiagodj** [micrometer-metrics/micrometer#4832]
**Describe the bug**
I have created this custom annotation:

```java
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Timed(percentiles = {0.99, 0.95, 0.90, 0.75, 0.50, 0.25, 0.10, 0.05, 0.01})
public @interface CustomTimed {
  @AliasFor(annotation = Timed.class, attribute = "value")
  String value();
  @AliasFor(annotation = Timed.class, attribute = "description")
  String description();
}
```

Because I want to reuse the same percentiles across all usages of this annotation.

But when I annotate my class with it, no metrics are generated.

This doesn't work:
```java
@CustomTimed(value = "azure.client", description = "Time taken to call Azure APIs")
public class AzureClient {
// ...
}
```
No metrics are created when the methods are called.

But this works fine:
```java
@Timed(value = "azure.client", description = "Time taken to call Azure APIs")
public class AzureClient {
// ...
}
```
The problem is that the 2nd case is not taking into consideration the `percentiles` defined above.

Is this supported at all?

**Environment**
 - Micrometer version [e.g. 1.12.0]
 - Micrometer registry: prometheus
 - OS: macOS
 - Java version: 17

**To Reproduce**
How to reproduce the bug:
Simply run the example code above.

**Expected behavior**
I'd expect the custom annotation to also trigger the timers, so that I can reuse default values defined in it across the application.

**Comment by jonatan-ivanov** [comment]
Check `TimedAspect`, it processes `@Timed`.
If you don't process `@CustomTimed`, nothing will happen as you are experiencing.
