### ISSUE TITLE
Manage context-propagation version in micrometer-bom

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#4847]
Projects that have instrumentation based on Micrometer Observation may also need to use context-propagation to ensure propagation in that project is handled correctly. Currently, as context-propagation is an optional dependency, there is no version management provided in this case. If the project depends on Micrometer Tracing, that will pull in a transitive dependency on context-propagation (eliminating the need to choose the version), but not every project will have a dependency on tracing.

We can add context-propagation to the micrometer-bom with the version that we compile against for our optional integration with context-propagation in micrometer-core.

**Comment by spencergibb** [comment]
So part of [boot 3.3](https://github.com/spring-projects/spring-boot/blob/6c56810d6ef23a9340574e5b399ec573508b69de/spring-boot-project/spring-boot-dependencies/build.gradle#L1235)? So cloud will be able to use it with a boot 3.4 baseline in 2024.0

**Comment by shakuzen** [comment]
> So part of [boot 3.3](https://github.com/spring-projects/spring-boot/blob/6c56810d6ef23a9340574e5b399ec573508b69de/spring-boot-project/spring-boot-dependencies/build.gradle#L1235)?

Yes
