### ISSUE TITLE
Allow custom SLO configuration when using a DistributionSummary.

### ISSUE THREAD

**Issue by nielsm5** [micrometer-metrics/micrometer#4854]
Right now it's impossible to configure a PrometheusDistributionSummary with custom service level objects.

https://github.com/micrometer-metrics/micrometer/blame/b81c63bf9b87f6e1dd149d503133e7f1a008b2e8/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheusmetrics/PrometheusDistributionSummary.java#L63
The `DistributionStatisticConfig.builder()` takes preferences over it's own empty-array `.serviceLevelObjectives()` and thus does not allow the summary to be created in a normal fasion.

I found a [6 year old issue](https://github.com/micrometer-metrics/micrometer/issues/530) with a very similar problem, but the solution was to simply turn off the histogram.

I'm curious as to why this has been made in this way, and if this has been done by accident, or if there actually is a purpose. (And if so, I'd expect some explanation in the javadoc.)
It's strange that Prometheus disables SLO but does **NOT** set the percentilesHistogram to false by default.

**Comment by jonatan-ivanov** [comment]
Could you please send us a test (reproducer) that shows the issue?

```java
DistributionSummary ds = DistributionSummary.builder("ds")
    .serviceLevelObjectives(100, 200, 300)
    .register(registry);

ds.record(10);
```

>It's strange that Prometheus disables SLO but does NOT set the percentilesHistogram to false by default.

You can imagine this as adding extra buckets to a histogram.

**Comment by nielsm5** [comment]
Hi,

When adding a new DistributionSummary the way you described, the PrometheusDistributionSummary 'messes' with the `distributionStatisticConfig` in particularly the serviceLevelObjectives(). It calls the method but does not provide any arguments.

This causes the `merge` method (`DistributionStatisticConfig.merge(DistributionStatisticConfig)`) to favor it's own (Prometheus SLO, over the parent (provided when creating the summary).

The problem; if you define your own SLO, it will ignore the provided value, and use SLO without any value creating it's own random range from 0 to inf.

**Comment by jonatan-ivanov** [comment]
Could you please send us a test (reproducer) that shows the issue?
As far as I remember what you are trying to do should work.
