### ISSUE TITLE
Adding 'mean', 'min' or 'percentiles' to Spring Boot 2 metrics?

### ISSUE THREAD

**Issue by gotson** [micrometer-metrics/micrometer#488]
Also posted on [StackOverflow](https://stackoverflow.com/questions/49166271/adding-mean-or-min-to-spring-boot-2-metrics_) and on [Spring Boot github](https://github.com/spring-projects/spring-boot/issues/12433)

I am using the new **MicroMeter** metrics in **Spring Boot 2** version `2.0.0-RELEASE`.

When publishing metrics over the `/actuator/metrics/{metric.name}` endpoint, i get the following:

  For a `DistributionSummary` :

    "name": "sources.ingestion.rate",
        "measurements": [
            {
               "statistic": "COUNT",
                "value": 5
            },
            {
                "statistic": "TOTAL",
                "value": 72169.44162067816
            },
            {
                "statistic": "MAX",
                "value": 17870.68010661754
            }
        ],
        "availableTags": []
    }

  For a `Timer` :

    {
        "name": "sources.ingestion",
        "measurements": [
            {
                "statistic": "COUNT",
                "value": 5
            },
            {
                "statistic": "TOTAL_TIME",
                "value": 65.700878648
            },
            {
                "statistic": "MAX",
                "value": 22.661545322
            }
        ],
        "availableTags": []
    }

Is it possible to enrich the measurements to **add measures** like *mean*, *min*, or *percentiles* ?

For percentiles i tried using `.publishPercentiles(0.5, 0.95)`, but that doesn't reflect on the actuator endpoint.

Spring Boot team is [saying](https://github.com/spring-projects/spring-boot/issues/12433#issuecomment-372310893) that they only expose the content of the MeterRegister, hence the question should be asked here.

**Comment by jkschneider** [comment]
Sure, we can do that.

Just out of curiosity: what are you using the actuator endpoint for specifically?

**Comment by jkschneider** [comment]
@gotson Those percentiles are shipped to your monitoring system of choice. The actuator endpoint is at best a toy, a diagnostic tool. It's a blunt instrument, where only the things that show up in the [default measure](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/DistributionSummary.java#L95) implementation for each type show up. The solution is simple though: just add more details from the `HistogramSnapshot` to the default measure implementation.

**Comment by gotson** [comment]
Thanks a lot for the explanations !
