### ISSUE TITLE
Failed to send metrics to Atlas

### ISSUE THREAD

**Issue by Emin77** [micrometer-metrics/micrometer#489]
Hi,
i'am using spring boot  2 RELEASE, and when send request from postman for any metric 
get an exception. What did i do wrong?

 c.netflix.spectator.atlas.AtlasRegistry  : failed to send metrics

java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_144]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_144]

**Comment by jkschneider** [comment]
@Emin77 Seems like Atlas is not available at the URI you have configured to ship metrics to. Because we can make no assumptions about your deployed environment, the default URI is `http://localhost:7101/api/v1/publish`.

You can change this by setting the `management.metrics.export.atlas.uri` property, or programmatically providing a `@Bean AtlasConfig` where you override the `uri()` function.

**Comment by checketts** [comment]
Do we log out the url it failed to send metrics to? Perhaps that would help the user.

**Comment by jkschneider** [comment]
In this case, we don't control the `AtlasRegistry` class, it comes from spectator-atlas.

**Comment by Emin77** [comment]
Excuse me, i don't write process step by step
my app.properties 
server.port=8099

management.endpoint.health.enabled=true
management.endpoint.shutdown.enabled=true
management.endpoint.info.enabled=true
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*

Then i send request like this 

localhost:8099/actuator/health

and i get valid response 

{
    "status": "UP",
    "details": {
        "diskSpace": {
            "status": "UP",
            "details": {
                "total": 249678528512,
                "free": 166633775104,
                "threshold": 10485760
            }
        },
        "db": {
            "status": "UP",
            "details": {
                "database": "Oracle",
                "hello": 1
            }
        }
    }
}

But in log after some 20 seconds i see exception message

c.netflix.spectator.atlas.AtlasRegistry : failed to send metrics

java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_144]

**Comment by brharrington** [comment]
> Do we log out the url it failed to send metrics to? Perhaps that would help the user.

If you enable debug level for `com.netflix.spectator`, then you'll get an access log for the client that will show the uri, headers, status or exception, etc. 

> In this case, we don't control the AtlasRegistry class, it comes from spectator-atlas.

If you find improvements we can make on the Spectator side, then please file an issue or send a PR.

**Comment by Emin77** [comment]
> If you enable debug level for com.netflix.spectator, then you'll get an access log for the client that will show the uri, headers, status or exception, etc.

i did it. This is log

2018-03-15 11:05:21.927 DEBUG 33166 --- [tor-reg-atlas-0] c.n.spectator.sandbox.HttpLogEntry       : spectator-reg-atlas	2018-03-15T11:05:21	4	4	start:1521093921920;complete:1521093921924;	POST	null	http://localhost:7101/api/v1/publish	null	-1	-1	null	java.net.ConnectException	Connection refused (Connection refused)	0	8651	0	-1			0	1	-1
2018-03-15 11:05:21.931  WARN 33166 --- [tor-reg-atlas-0] c.netflix.spectator.atlas.AtlasRegistry  : failed to send metrics

**Comment by checketts** [comment]
@Emin77 Where do you have Atlas running? That error appears to indicate Atlas isn't running on your `localhost:7101`.

**Comment by jkschneider** [comment]
Thanks @brharrington. I think the error message is clear enough as it is.

**Comment by ripjal** [comment]
you need to start server with memory-conf to get up your atlas server running
`java -jar atlas-1.6.5-standalone.jar memory.conf`
Please refer Atlas [wiki](https://github.com/Netflix/atlas/wiki/Getting-Started) more details
