### ISSUE TITLE
Support OpenTSDB

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#490]
Look to HTTP ingestion here: http://opentsdb.net/docs/build/html/user_guide/writing/index.html

Grafana supports OpenTSDB as an data source.

Test against https://hub.docker.com/r/petergrace/opentsdb-docker/

**Comment by jkschneider** [comment]
For now, it is sufficient to direct folks to https://github.com/influxdata/telegraf/tree/master/plugins/outputs/opentsdb. 

If you have a need for direct publishing to OpenTSDB, please comment and we can reopen this.

**Comment by wingyiu** [comment]
reopen it plz

**Comment by jkschneider** [comment]
@wingyiu have you tried the telegraf plugin?

**Comment by newffy** [comment]
@jkschneider 
telegraf is one more point of failure if use it just for metrics conversion.
Meanwhile, influx/kairos have similar to opentsdb protocols.
