### ISSUE TITLE
Support Graphite 1.1.x tags

### ISSUE THREAD

**Issue by ITman1** [micrometer-metrics/micrometer#491]
Hi,
is there a plan to support exporting metrics into Graphite using tags http://graphite.readthedocs.io/en/latest/tags.html?
Thank you.

**Comment by jkschneider** [comment]
There is now ;). Thanks for bringing it to our attention.

**Comment by ibhi** [comment]
Hi, any recent updates on this issue?

**Comment by shakuzen** [comment]
No update so far. If someone were to send a pull request that added this support, it would help move things along. To that end, I've labeled the issue with the `help wanted` tag.

**Comment by fitzoh** [comment]
I'm suddenly interested in this...

Any thoughts on what the implementation looks like?
A switch in the graphite registry config that changes the namer?
