### ISSUE TITLE
Support Square's Cube

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#492]
http://square.github.io/cube/

**Comment by mweirauch** [comment]
No offense, but who is using a monitoring system which is unmaintained for nearly 4 years? (Judging from the github commits.)

**Comment by jkschneider** [comment]
Maybe nobody, in which case I will close this. I'm still scrounging for options for a hystrix dash replacement and a reactor dash.

**Comment by checketts** [comment]
What is 'hystrix dash'? Is that the same as Turbine?

**Comment by jkschneider** [comment]
[This](https://github.com/Netflix-Skunkworks/hystrix-dashboard). Turbine aggregates data being fed to the dashboard. So with the right pick, Turbine is obsolete in the stack as well.

**Comment by checketts** [comment]
I see. We have some Prometheus/Grafana dashboards that display that information, but not nearly as densely.

**Comment by jkschneider** [comment]
Yep, so the million dollar question is what do we replace it with? We could embed Atlas easily enough into a Boot app and provide a custom viz. Or is a StatsD solution better because we need to use the dash in places where we have more reliable access to messaging middleware than discovery? Remains to be seen.

**Comment by warrell** [comment]
I still use Cube but I am old but I'm happy (to paraphrase Cat Stevens). I am writing an adaptor using the Simple Json data source and the Node Streams modules. Looking a bit clunky... There must be a better way?

**Comment by shakuzen** [comment]
Closing due to the following note in the [now archived GitHub repository](https://github.com/square/cube):
> Cube is not under active development, maintenance or support by Square (or by its original author Mike Bostock). It has been deprecated internally for over a year. We keep it running for historical interest because it powers some interesting visualizations, but new production systems have replaced it for analytics purposes.
