### ISSUE TITLE
Micrometer Prometheus scrape format example does not compile

### ISSUE THREAD

**Issue by tsegismont** [micrometer-metrics/micrometer#4953]
The example shown in the [Scrape Format](https://docs.micrometer.io/micrometer/reference/1.13-SNAPSHOT/implementations/prometheus.html#_scrape_format) section of the Micrometer Prometheus doc does not compile:

```java
String openMetricsScrape = registry.scrape(TextFormat.CONTENT_TYPE_OPENMETRICS_100);
```

This applies to the 1.13 snapshot doc only.

The reason is the `io.micrometer.prometheusmetrics.PrometheusMeterRegistry.Format` enum is private.

Even if it was public, the example should be modified to:

```java
String openMetricsScrape = registry.scrape(TextFormat.CONTENT_TYPE_OPENMETRICS_100).getContentType();
```

The documentation should be updated, or users should be able to use the enum to specify the desired format.

I would prefer the second solution afaic. I can provide a PR in any case.

**Comment by jonatan-ivanov** [comment]
This is a known issue(?), we moved to the Prometheus 1.x client (`micrometer-registry-prometheus`) in our snapshot release but haven't updated the docs, the docs are still for the old Prometheus 0.x client (`micrometer-registry-prometheus-simpleclient`). The former is missing, the latter is still needed in case users want to use the old client.

**Comment by jonatan-ivanov** [comment]
I created this: https://github.com/micrometer-metrics/micrometer/issues/4957
