### ISSUE TITLE
Improve memory usage of StepBucketHistogram

### ISSUE THREAD

**Issue by lenin-jaganathan** [micrometer-metrics/micrometer#4954]
While configuring Histograms the expectation is that 16 bytes would be used per bucket (8 bytes - for bucket bound, 8 bytes - for a count of values at a bound). But it seems using StepBucketHistogram (also TimeWindowFixedBoundaryHistogram) uses 8 additional bytes in addition to the required bytes. This is because these implementations seem to hold a local copy of buckets which costs for additional memory footprint.

Expected Behaviour:
Histogram only uses (2 * 8) bytes per bucket.

**Comment by shakuzen** [comment]
Following up on https://github.com/micrometer-metrics/micrometer/pull/4955#issuecomment-2395707968, @lenin-jaganathan is there anything left to do for this issue, or is it taken care of by #4955?

**Comment by lenin-jaganathan** [comment]
I missed the comment. Will have a look and update.

**Comment by lenin-jaganathan** [comment]
We are good. Resolved by https://github.com/micrometer-metrics/micrometer/pull/4955
