### ISSUE TITLE
@Timed support for rx.Single and rx.Observables

### ISSUE THREAD

**Issue by ravindra9966** [micrometer-metrics/micrometer#496]
Hi,

I am developing micro services with rx Java ,@Timed and @Metered annotations are not producing valid matrixs, is there any way to resolve produce valid matrxi?

Kindly help me resolving this issue.

**Comment by jkschneider** [comment]
Currently `@Timed` is a general purpose annotation that frameworks can apply to specific things like web endpoints. There is also an incubating `TimedAspect` that applies it more generally with AOP.

Not sure what you have in mind for RxJava. Can you provide a code snippet that describes how you _want_ it to work?

**Comment by ravindra9966** [comment]
`    @RequestMapping(value = "/{msisdn}/{period}", produces = MediaType.APPLICATION_JSON_VALUE, method = RequestMethod.GET)
    @ExceptionMetered
    @Timed
    public Single<ResponseEntity<Result<UsageDetail>>> getDDUReportSummary(Principal principal, @ApiParam(value = "msisdn", type = "String", example = "0828718620", required = true) @ValidMsisdn(message = "Please enter a valid cellphone number") @PathVariable("msisdn") String msisdn,
                                                                           @ApiParam(value = "period", type = "String", example = "today", required = true) @PathVariable("period") Period period)
            throws VodMsTechnicalException, VodMsServiceException, VodMsBusinessException {
`

I am returning Single object directly from rest controller , What I mean to ask you is will I be getting correct Timed and Exception metered Matrix? Since TimedAspect just calculating method execution?

**Comment by checketts** [comment]
What annotations are you improting? These look like Dropwizard, not Micrometer.

**Comment by ravindra9966** [comment]
Sorry, my bad.

**Comment by AaronLiang** [comment]
I dont think this would work for Reactive Java or any non-blocking code.

**Comment by jkschneider** [comment]
@AaronLiang We'll add timing to Reactor anyway via `Operators.lift`, not annotations. Not sure what we could do for RxJava specifically at this point.

**Comment by AaronLiang** [comment]
@jkschneider   thanks for your response, do you have any sample code for rxjava or Reactor?

**Comment by AaronLiang** [comment]
Also please check this:
https://github.com/resilience4j/resilience4j/tree/master/resilience4j-micrometer

**Comment by jkschneider** [comment]
We had [started Reactor](https://github.com/micrometer-metrics/micrometer/tree/v1.0.0-rc.9/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/reactor) support, but dropped it before 1.0. A little more work needed to happen in reactor-core I think before it was finalized. My memory of this is a little hazy.

**Comment by jkschneider** [comment]
@AaronLiang Great start on the resilience4j support!

1. I think [these](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/RetryMetrics.java#L63-L70) and [these](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/CircuitBreakerMetrics.java#L62-L67) would be better as `FunctionCounter` so you could reason about rates over an interval.
2. Could we add desciption text to the metrics?

**Comment by AaronLiang** [comment]
@jkschneider   i didnt try resilience4j solution yet. Its very hard to record async non-blocking status. Maybe we should go to the original solution, set a timer and then record the metrics
