### ISSUE TITLE
How to add mongodb instrumentation

### ISSUE THREAD

**Issue by jeusdi** [micrometer-metrics/micrometer#4974]
How can I configure Spring Boot 3 with Micrometer tracing to send traces to X-Ray instead of Jaeger, and also enable instrumentation to generate traces for communication with MongoDB, which I currently don't see visualized?

Here my current related dependencies I'm using:

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
		<groupId>io.micrometer</groupId>
		<artifactId>micrometer-tracing</artifactId>
</dependency>
<!-- Adds the Tracer Implementation -->
<dependency>
		<groupId>io.micrometer</groupId>
		<artifactId>micrometer-tracing-bridge-otel</artifactId>
</dependency>
<!-- Adds an exporter to store the traces -->
<dependency>
	<groupId>io.opentelemetry</groupId>
	<artifactId>opentelemetry-exporter-otlp</artifactId>
</dependency>
```

It's not clear to my how to manually instrumenting my project in order to generate mongodb traces.

Any ideas?

**Comment by shakuzen** [comment]
Are you using Spring Data MongoDB or the MongoDB client directly? If you're using Spring Data MongoDB, see their [documentation on observability](https://docs.spring.io/spring-data/mongodb/reference/observability/observability.html).

**Comment by jeusdi** [comment]
Thanks a lot @shakuzen.

I'm using Spring Data Mongodb.
I solved issue applying chnages suggested on mongodb documentation.
