### ISSUE TITLE
X-Ray traces destination

### ISSUE THREAD

**Issue by jeusdi** [micrometer-metrics/micrometer#4975]
It's not clear to how to send my traces to x-ray.

I mean, currently I'm sending my traces to a jaeger. It works fine. Here my related configuration:

I mean, currently, here's my related configuration:

```
# See https://docs.spring.io/spring-data/mongodb/reference/observability/observability.html
# Disable Spring Boot's autoconfigured tracing
management.metrics.mongo.command.enabled=false
# Enable it manually
management.tracing.enabled=true

management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
spring.application.name=espaidoc-frontoffice
```

It's not clear to me how to change OTLP destination.

My current dependencies:

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
	<groupId>io.micrometer</groupId>
	<artifactId>micrometer-tracing</artifactId>
</dependency>
<dependency>
	<groupId>io.micrometer</groupId>
	<artifactId>micrometer-tracing-bridge-otel</artifactId>
</dependency>
<dependency>
	<groupId>io.opentelemetry</groupId>
	<artifactId>opentelemetry-exporter-otlp</artifactId>
</dependency>
```

Could you provide any suggestions?

**Comment by jonatan-ivanov** [comment]
As far as I know X-Ray does not have an OTLP endpoint but you can do two things:
1. Use the OTel collector: it can accept OTLP and emit X-Ray but it's another component in your infrastructure and it is not stable yet.
2. OTel might have an x-ray exporter (same thing you did with `opentelemetry-exporter-otlp`), please check the OTel docs for it.
