### ISSUE TITLE
ElasticMeterRegistry reports fields with same name in different formats

### ISSUE THREAD

**Issue by tkp1n** [micrometer-metrics/micrometer#498]
Elasticsearch [dynamic mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#_dynamic_mapping) currently fails because certain fields (e.g. sum) get reported as floatingpoint and integral values (see image below).

![sample](https://user-images.githubusercontent.com/9985284/37511169-2347b4de-28fe-11e8-8518-59936ba315a3.PNG)

Possible solutions:
- Use [explicit mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#_explicit_mappings) for fields known to differ in type
- Make sure all values of a field get reported in the same format

The use of `DoubleFormat.decimalOrWhole` might generally be dangerous in the context of Elasticsearch, as it produces results as `12` and `14.9` which will confuse Elasticsearch Mapping.

Unitl now I only had issues with `sum` but there might be others.

Error as reported by Elasticsearch:

```json
"index": {
    "_index": "metrics-2018.03.15",
    "_type": "doc",
    "_id": "AWIqq3txcLB5uE05seua",
    "status": 400,
    "error": {
        "type": "illegal_argument_exception",
        "reason": "mapper [sum] cannot be changed from type [float] to [long]"
    }
}
```

_Please also consider to log as a warning instead of an error if the bulk post to elasticsearch succeeds with errors. I would suggest to treat a 200 with errors as a warning and only log as error if the repsonse code is != 2xx._

/cc @jkschneider

**Comment by jkschneider** [comment]
Changed 200 response with errors to log at warn level in 7cfa7c78f3e7d751499dadfaf74ace041a19fea9

**Comment by criminosis** [comment]
@jkschneider I'm bumping into this problem with the count field. It looks like timer returns a long whereas counter returns a double. If a timer metric is emitted first then Elasticsearch's dynamic mapping interprets the count field as being a long type and then fails to write counters' count because they have decimal characters.

`mapper [count] cannot be changed from type [long] to [float]`

**Comment by jkschneider** [comment]
Thanks @criminosis. Opened #1071 to track this.
