### ISSUE TITLE
Dynatrace rejecting metrics ingestion with errror "Inconsistent Gauge Fields"

### ISSUE THREAD

**Issue by rohithkk** [micrometer-metrics/micrometer#5037]
We are using the `micrometer-registry-dynatrace` library to publish metrics to Dynatrace endpoint. In certain instances, the metrics submitted by micrometer are being rejected by Dynatrace.

> Error: Failed metric ingestion: Error Code=400, Response Body={\"linesOk\":115,\"linesInvalid\":1,\"error\":{\"code\":400,\"message\":\"1 invalid lines\",\"invalidLines\":[{\"line\":19,\"error\":\"inconsistent gauge fields: min <= avg <= max doesn't hold: min: 35.689672, max: 35.689672, sum: 35.669104, count: 1, avg: 35.669104, tolerance: 0.000001\"}]},\"warnings\":{\"message\":\"First 22 warnings reported\",\"warningLines\":[{\"line\":8,\"warning\":\"metric key 'executor.completed' changed to 'executor.completed.count'\"},{\"line\":22,\"warning\":\"metric key 'logback.events' changed to 'logback.events.count'\"},{\"line\":24,\"warning\":\"metric key 'logback.events' changed to 'logback.events.count'\"},{\"line\":26,\"warning\":\"metric key 'executor.completed' changed to 'executor.completed.count'\"},{\"line\":27,\"warning\":\"metric key 'executor.completed' changed to 'executor.completed.count'\"},{\"line\":28,\"warning\":\"metric key 'jvm.buffer.count' changed to 'jvm.buffer.count.gauge'\"},{\"line\":37,\"warning\":\"metric key 'system.cpu.count' changed to 'system.cpu.count.gauge'\"},{\"line\":52,\"war (truncated)

Here is the offending line in the metrics.

`http.server.requests.active,exception=none,method=GET,dt.entity.host_group=HOST_GROUP-723F20685945FBAA,dt.metrics.source=micrometer,dt.entity.process_group_instance=PROCESS_GROUP_INSTANCE-64B4F127EA54D4C1,dt.host_group.id=test-r,uri=UNKNOWN,outcome=SUCCESS,status=200,dt.entity.host=HOST-241BAE1BC8844344 gauge,min=35.689672,max=35.689672,sum=35.669104,count=1 1714653042290
`

I'm wondering if this issue is due to double datatype losing precision when calculating SUM and AVG. Is there a way to fix this issue? 

We are using micrometer version `1.11.0`.

**Comment by pirgeo** [comment]
Should be fixed as of 1.11.10 (https://github.com/micrometer-metrics/micrometer/commit/aa8403b153c3cdbfb8744f67734fdac3bf6a7382). The problem was that the max and sum values could not be retrieved from the Micrometer instrument in an atomic operation, leading to inconsistent data as the elapsed time continued to elapse while max and sum were retrieved sequentially.

**Comment by rohithkk** [comment]
Yes, updating to latest version did fix the issue. Thank you!
