### ISSUE TITLE
Add Server-Timing header for HTTP responses

### ISSUE THREAD

**Issue by osi** [micrometer-metrics/micrometer#504]
There's a W3C draft for servers adding a `Server-Timing` header to HTTP responses. https://w3c.github.io/server-timing/

It would be handy to have this be a feature of Micrometer

**Comment by shakuzen** [comment]
This seems more in the tracing realm than metrics, to me. Interesting for sure, though.
/cc @adriancole

**Comment by osi** [comment]
fair enough, I wasn't sure which project an implementation would be the best fit for.
