### ISSUE TITLE
ElasticSample causes "Duplicate field 'name'" error in elasticsearch

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#506]
cc / @jvalkeal

**Comment by prafsoni** [comment]
Hi, when in 1.1 release is scheduled? We are waiting on this... feature. So we can remove intermediate storage in atlas and move metrics directly to Elasticsearch.

**Comment by jkschneider** [comment]
@prafsoni Latest possible delivery date is September 1, but we could release a 1.1 earlier if there is a need and follow on with 1.2 for Spring Boot 2.1 later. Until this issue is resolved, Elastic support is broken.

**Comment by tkp1n** [comment]
@jkschneider Do you know which metric causes the issue? Or any other info to get a PR started? Would love to see this finally working without errors...

**Comment by jkschneider** [comment]
@tkp1n Yep, we are now renaming reserved words in Elastic as part of the default naming convention for the elastic implementation.
