### ISSUE TITLE
Metric grpc_server_processing_duration_seconds_max is always 0

### ISSUE THREAD

**Issue by rick-alp** [micrometer-metrics/micrometer#5062]
The bug:

grpc_server_processing_duration_seconds_max is always 0 no matter what the call,
grpc_server_processing_duration_seconds_sum and grpc_server_processing_duration_seconds_count are okay.

Steps to Reproduce

Enable metrics, make a grpc call grpc_server_processing_duration_seconds_max should not be 0

Which versions do you use?

Spring (boot): 3.2.3
grpc-spring-boot-starter: 3.0.0.RELEASE
java: version + architecture (64bit?) 21, 64bit
Additional context

Did it ever work before? Yes

**Comment by shakuzen** [comment]
If the sum and count have values, the max should also have a value around when recordings happen. However, note that max is time windowed. So if there are no new measurements recorded, after some time max will become 0. See the first note in the [Timers documentation](https://docs.micrometer.io/micrometer/reference/concepts/timers.html). We have a [GrpcMetricsSample](https://github.com/micrometer-metrics/micrometer/blob/294a5cdb46d3f2881c82398e73bf4095183ed5f1/samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/GrpcMetricsSample.java) that you can run. As is, it won't log the max value, but you can modify it to use the LoggingMeterRegistry and close the registry at the end so it logs out all the metrics, and you will see something like the following:

```
INFO: grpc.server.processing.duration{method=Check,methodType=UNARY,service=grpc.health.v1.Health,statusCode=OK} throughput=0.1/s mean=0.006688125s max=0.006688125s
```

There shouldn't be any scenario in which the max is 0 if there was a positive measurement recorded and the time window has not elapsed. Please check if any of that applies to your scenario, and if not, please provide a minimal sample we can use to reproduce the issue.

**Comment by rick-alp** [comment]
@shakuzen Thanks for the explanation.
