### ISSUE TITLE
1.12.5 java.lang.NoClassDefFoundError: org/HdrHistogram/DoubleRecorder

### ISSUE THREAD

**Issue by LukasPrediger** [micrometer-metrics/micrometer#5134]
**Describe the bug**
When using a spring boot application with client-side histograms, upgrading to version 1.12.5 causes a NoClassDefFoundError when registering the metric in the test context.

**Environment**
 - Micrometer version: 1.12.5
 - Micrometer registry: Prometheus

**To Reproduce**
Create a spring-boot application (version 3.2.5) and create a metric with client-side histograms

**Additional context**
The metric is defined in a library that is used by the actual application. Both the library and the application have a dependency to spring-boot 3.2.5.

The application uses gradle as its build system while the library is build with maven. 

Observations:
- the dependency HdrHistogram is part of the runtimeClasspath but not the testRuntimeClasspath
- downgrading to 1.12.4 makes the dependency appear on both runtime and testRuntimeClasspath in gradle
- We have not included or excluded the dependency in any way
- The documentation mentions the HdrHistogram dependency but recommends to exclude it if client-side histograms are not used

**Comment by shakuzen** [comment]
Would it be possible to put together a minimal sample repository that reproduces the issue? Then it would be easiest for us to confirm the issue and test any fixes.

**Comment by LukasPrediger** [comment]
Thanks for the quick reply @shakuzen. 

We investigated the issue further and figured out that this seems to be an issue with the gradle setup. We were unable to replicate the error in a minimal repository or any other application for that matter. It is unknown yet what exactly caused the issue but since i don't expect this to be a micrometer issue, i will close this ticket
