### ISSUE TITLE
Publish recent documentation under a fixed version number

### ISSUE THREAD

**Issue by philwebb** [micrometer-metrics/micrometer#5152]
**Please describe the feature request.**
Currently micrometer publishes the most recent documentation under https://docs.micrometer.io/micrometer/reference but does not offer a version that includes the version number. This makes it impossible to link to a specific release.

For example, at the time of raising this issue to link to v1.12 you can use https://docs.micrometer.io/micrometer/reference/1.12/index.html but trying to link to v1.13 using https://docs.micrometer.io/micrometer/reference/1.13/index.html results in a 404.

Links to https://docs.micrometer.io/micrometer/reference/ will currently return v1.13, but only whist v1.14 is not out.

**Rationale**
I want to link to the correct version of the docs

**Additional context**
https://github.com/spring-projects/spring-boot/issues/40916
https://github.com/micrometer-metrics/tracing/issues/731

**Comment by jonatan-ivanov** [comment]
I think this is happening because Micrometer's docs site is hosted on GH Pages and Antora is not able to generate html files for redirection right now.

**Comment by philwebb** [comment]
I wonder if https://docs.antora.org/antora/latest/playbook/urls-redirect-facility/#static might work?

**Comment by shakuzen** [comment]
@philwebb thanks for the pointer. That sounded like it would do what we need, and I [tried it](https://github.com/micrometer-metrics/micrometer/commit/8af61251c1bcdc44fb98d71a543c64fa726845c5) but unfortunately, it [did not do](https://github.com/micrometer-metrics/docs-pages/commit/9bba679a57e0d17725a290138fef4c0c54c654fc) what we want. I think it only creates static redirects for explicitly defined page aliases. [This open Antora issue](https://gitlab.com/antora/antora/-/issues/848) looks to be the feature request for the behavior we want. Unfortunately, I think that leaves us needing to write an Antora extension to get the behavior we want.

**Comment by jonatan-ivanov** [comment]
Based on recommendations of @trevormarshall, I set up a redirect rule for Micrometer docs in CloudFlare (I will do the rest if it works fine).

@philwebb Could you please check some of the links you want to use against 1.13?
All these should work:
- https://docs.micrometer.io/micrometer/reference/1.13/index.html
- https://docs.micrometer.io/micrometer/reference/1.13/implementations/prometheus.html
- https://docs.micrometer.io/micrometer/reference/1.13/implementations/prometheus.html#_exemplars
- https://docs.micrometer.io/micrometer/reference/1.13/
- https://docs.micrometer.io/micrometer/reference/1.13
