### ISSUE TITLE
Typo in Datadog properties for Spring Boot 1.5

### ISSUE THREAD

**Issue by wimdeblauwe** [micrometer-metrics/micrometer#517]
On https://micrometer.io/docs/ref/spring/1.5#_datadog there is:

    # You will probably want disable Atlas publishing in a local development profile.
    management.metrics.export.datadog.enabled=true # default is true

That should change to:

    # You will probably want disable Datadog publishing in a local development profile.
    management.metrics.export.datadog.enabled=true # default is true

**Comment by jkschneider** [comment]
Good catch! Fixed in https://github.com/micrometer-metrics/micrometer-docs/commit/edec236fd2da4f6eb652b149c866f5814f6c33ec
