### ISSUE TITLE
HibernateMetrics should not assume Hibernate is used

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#518]
`HibernateMetrics` [expects to be able](https://github.com/micrometer-metrics/micrometer/blob/c8912948b36ab6935fd74d5bdfdfac55b6eda95a/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jpa/HibernateMetrics.java#L180) to unwrap `EntityManagerFactory` to `SessionFactory`.

I don't think that's wise and that code should gracefully ignore when that's not the case the same way it does if stats aren't enabled.

Alternatively the constructor could be changed to indicate that a `SessionFactory` is expected.

**Comment by jkschneider** [comment]
@snicoll It appears to me that there is a guard in this code already. If the unwrapping is unsuccessful, the javadocs indicate that `EntityManagerFactory` would return a `PersistenceException`, which is handled gracefully here. 

The net result is that no metrics are bound.

Is there another edge case to handle?

**Comment by snicoll** [comment]
@jkschneider you are right and I've realized that after the fact. `EntityManagerFactory#unwrap` could return `null` but that breaks the API contract so you shouldn't have to care.

Sorry for the noise.
