### ISSUE TITLE
Timer prometheus metric _max is not according to Prometheus spec

### ISSUE THREAD

**Issue by AFriemann** [micrometer-metrics/micrometer#519]
The current [prometheus implementation](https://github.com/micrometer-metrics/micrometer/blob/e30323829185dcd016ad9291316a1f54cb2615a9/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L215) for the Timer metric is not according to the Prometheus specification for a summary metric.

This results in issues with the official prometheus client libraries and should be moved to a seperate gauge metric:

https://github.com/prometheus/client_python/pull/264

Is that a known problem, or rather, is there any interest for a fix? We might be able to offer a PR in the coming days.

**Comment by checketts** [comment]
Yes, a fix would be welcome

**Comment by mweirauch** [comment]
So we'd need to ship another MetricFamily which just includes the `_max`, right?

The thing which puzzles me is that neither Prometheus1 nor Prometheus2 server - as the system having to deal with the metrics - has ever complained about the `_max` being ingested. So it has a laxer validation then client libraries?

**Comment by AFriemann** [comment]
@mweirauch 

that is exactly what's happening. Prometheus does not need a HELP/TYPE for it's metrics, however it is required for some features. 

Since the metrics are all under the respective summary HELP/TYPE it is perfectly fine with having some strays in there, it will just collect them as a seperate untyped metric automatically (as far as I understand it). The client libraries will do the same though, so if you're trying to forward metrics from another source (which is what we're doing right now) Prometheus will not be able to parse the result anymore (since HELP/TYPE get mixed up).

It should be a seperate gauge for the _max value.

A colleague of mine is working on a fix right now as far as I know.

**Comment by marcoschulte** [comment]
Sorry for the first PR, didn't notice right away it duplicated the HELP and TYPE comments in the Prometheus output. New PR should be fine.

**Comment by jkschneider** [comment]
I'm relieved that the metric name doesn't need to change. Thanks for the PR!
