### ISSUE TITLE
Unable to instrument dataSource

### ISSUE THREAD

**Issue by Eloo** [micrometer-metrics/micrometer#52]
Hi,
i'm currently trying to instrument my DataSource in my SpringBoot 1.5.4 application but it seems that it isn't working properly.

Instrumentation is done according to the documentation (doc seems a bit outdated?)
```    @PostConstruct
    private void instrumentDataSource() {
        SpringMeters.monitor(
                registry,
                dataSource,
                metadataProviders,
                "data_source",
                Tag.of("stack", env.acceptsProfiles("cloud") ? "cloud" : "local")
        );
    }
````
But i'm only receiving NaN values :/
```data_source_active_connections{stack="local",} NaN```

Has someone successfully instrumented his dataSource? Any tips?

Thanks in advance

**Comment by jkschneider** [comment]
Thanks for the report @Eloo. The root cause was the `DataSourcePoolMetadata` being garbage collected out from underneath the gauges that were reporting on it.

**Comment by Eloo** [comment]
okay thanks for fixing this ;)
