### ISSUE TITLE
Add Timer instrumentation to Spring Data Interfaces

### ISSUE THREAD

**Issue by twicksell** [micrometer-metrics/micrometer#526]
It would be valuable to have timer instrumentation on all children of the Spring Data `Repository` interface. Metric name along the lines of of `spring.data.repository` with tags for method name (save, findOne, exists, etc.) and success/failure.

**Comment by jkschneider** [comment]
Discussed this with Adrian and Marcin. Zipkin's Brave provides p6spy tracing. To the extent you are willing to add a p6spy layer between your app and driver, we could take advantage of this.

**Comment by twicksell** [comment]
That'd be excellent for tracing, but I think not very good for readable metric names. It seems to be tracking things at the query level, whereas the interface methods put a much more accessible name on top of those (likely verbose) queries. 
`PersonController.getById` vs `select * from person where id=%id`. 
Also, this looks limited to jdbc whereas I'd want to cover the full suite of Spring Data techs, (redis, cassandra, etc.) 

Feels like that might be better in a spring-cloud-sleuth-extensions project for the tracing benefits.

**Comment by gavlyukovskiy** [comment]
We created similar to #500 interceptor especially for spring data use case, probably you can at least copy it to your project.

**Comment by futurechan** [comment]
I'm interested in something similar for use with Retrofit2.

**Comment by pscosta** [comment]
It would be very useful that some interceptor mechanism around the queries executions is provided. My goal is to simply collect Query execution time metrics and expose them as prometheus histograms.

**Comment by izeye** [comment]
This seems to be resolved via https://github.com/spring-projects/spring-boot/issues/22217.

**Comment by jonatan-ivanov** [comment]
Closing this since it suppose to go out with Spring Boot 2.5.0-RC1 (2.5.0).
