### ISSUE TITLE
Unable to send Micrometer data via statsd to graphite from my Akka actor within Spring Boot 2.0 app

### ISSUE THREAD

**Issue by itay-keller** [micrometer-metrics/micrometer#528]
I have a Spring Boot 2.0 application and I like to send Micrometer info to a graphite via statsd.

In the application.properties file I added:

management.metrics.export.statsd.enabled=true
management.metrics.export.statsd.host=192.168.1.1  // not the real IP
management.metrics.export.statsd.port=8126
management.metrics.export.statsd.step=10s

In one of the Akka actors classes I added a Counter and in the relevant function I increment it:

public class ThePrincessBride extends AbstractActor { 
     private final Counter Inigo = 
            Metrics.counter("my.name.is",  "Inigo", "Montoya");
    ///
    ...
    ///
    private void doX(){
       //do X
       Inigo.increment();
    }

The problem is that I don't  see any relevant UDP network packets leaving my computer when checking the network packets with Wireshark.

Of course I also see no data in graphite.

Am I missing something in the code / configuration?

**Comment by jkschneider** [comment]
Do you have `micrometer-registry-statsd` on the runtime classpath?

**Comment by itay-keller** [comment]
No, I don't have such parameter.
Do I need to simply add it to the path of the computer, (under the environment variables)?
Where should I point it to? Do I need to install something first on the computer?

**Comment by jkschneider** [comment]
@itay-keller I mean you need `micrometer-registry-statsd` as a binary dependency on your classpath. Add it to your Maven POM or Gradle dependencies block, as indicated here:

http://micrometer.io/docs/registry/statsD#_installing

If this doesn't solve your issue, please reopen!
