### ISSUE TITLE
Make measured event duration accessible from outside of DefaultMeterObservationHandler

### ISSUE THREAD

**Issue by kk-mats** [micrometer-metrics/micrometer#5289]
**Please describe the feature request.**
Currently, event duration is measured by `DefaultMeterObservationHandler` and the value is directly registered to `MeterRegistry`.

Thus, other handlers cannot get and reuse the duration in the stable way (even if we extend `DefaultMeterObservationHandler`).

To expose such information `DefaultMeterObservationHandler`, my request is to add a new method `void onTimeMeasured(Context context, long durationNs)` to `MeterObservationHandler` so that we can handle addition logic using measured event duration upon `DefaultMeterObservationHandler`.

**Rationale**
I was writing an `ObservationHandler` to log values from `ObservationContext` and the logs also need to contain event duration, for instance, response time.

However, I noticed that such duration information is not accessible with stable APIs from outside of `DefaultMeterObservationHandler`.

**Comment by jonatan-ivanov** [comment]
I'm not sure how `onTimeMeasured` would work or could be used, a usage example could help.
Handlers are measuring their own time (e.g.: tracing handler) would you mind sharing what exactly you are trying to do?

Also, if you register your handler _after_ `DefaultMeterObservationHandler`, you should be able to get the duration like this:
```
@Override
public void onStop(Observation.Context context) {
    LongTaskTimer.Sample sample = context.getRequired(LongTaskTimer.Sample.class);
    sample.duration(TimeUnit.NANOSECONDS); // or whatever unit you want
}
```
