### ISSUE TITLE
Gauge API like counter / timer

### ISSUE THREAD

**Issue by anuragagarwal561994** [micrometer-metrics/micrometer#5298]
**Please describe the feature request.**
Gauge should have a default implementation over AtomicInteger for making it easier to use for the end user like Prometheus library. 

**Rationale**
We are in process to shift from using prometheus library to micrometer, the one major caveat we feel is the way gauge has been implemented in Micrometer that it is not searchable and you have to define a function it is supposed to track.

In case someone is designing a library it makes much more sense to have this kind of integration because the library developer would mostly design their own metrics / stats framework and then integrate micrometer over like most of the implementations I have seen have done.

But when we are tracking end user application metrics who just wants a simpler integrations faces issues defining these complicated data models.

Currently if we want to have dynamic labels on Gauge we would need to ourselves have to create an AtomicInteger and store it in a heirarchical map based on the metric names and the tags and then while incrementing we would lookup from our own map and increment / decrement the AtomicIntegers that we have created.

For one or two cases it is okay, but everytime I will have to use a gauge if I have do this hassel of making another and trying to find my meter is not solving any purpose where micrometer says that Gauge is designed in a way where we don't have to lookup and it is self sufficient, point is if micrometer is not doing someone else mostly the end user is doing this job which is a pain from a well established library perspective.

I just wanted to simply do on my per function / parameter basis what is the number of concurrent request going on and I have to do a lot in order to achieve this. I further checked some of the binder imlementations for example https://github.com/micrometer-metrics/micrometer/blob/ea51e72207ee6d42879329252ab45352b23c2429/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsConnectionPoolListener.java#L51

where similar thing is happening, in case we have an API much like counter / timer even this code can be simplified and a lot of people have written articles over it stating thier is no current solution for this problem.

**Comment by jonatan-ivanov** [comment]
>Gauge should have a default implementation over AtomicInteger for making it easier to use for the end user like Prometheus library.

I don't really get why and what does this has to do with Prometheus. You can back your `Gauge` by and `AtomicInteger` like this:
```
AtomicInteger myGauge = registry.gauge("myGauge", new AtomicInteger(0));
```
See the docs: https://docs.micrometer.io/micrometer/reference/concepts/gauges.html#_manually_incrementing_or_decrementing_a_gauge

>the way gauge has been implemented in Micrometer that it is not searchable and you have to define a function it is supposed to track.

That's the point, please check how `Gauge`s work in the docs: https://docs.micrometer.io/micrometer/reference/concepts/gauges.html, they supposed to be async but you can use any backing "state object", you need to use the "state object" not the `Gauge` to change the value.

>Currently if we want to have dynamic labels on Gauge we would need to ourselves have to create an AtomicInteger and store it in a heirarchical map based on the metric names and the tags and then while incrementing we would lookup from our own map and increment / decrement the AtomicIntegers that we have created.

You might want to take a look at `MultiGauge`, see docs: https://docs.micrometer.io/micrometer/reference/concepts/gauges.html#_multi_gauge

**Comment by jonatan-ivanov** [comment]
Oh I forgot to link our `MultiGauge` sample, hope this helps: [`MultiGaugeSample`](https://github.com/micrometer-metrics/micrometer/blob/ea51e72207ee6d42879329252ab45352b23c2429/samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/MultiGaugeSample.java)

**Comment by anuragagarwal561994** [comment]
I am not sure if this works for me, see the example that you have given is still having both the labels and the values fixed.

What some of us want is an Up / Down Gauge where we can increment / decrement the gauge like prometheus provides. The issue is I understand the micrometer API doesn't want to build that for some reason.

But at the end, end users are building it and putting it in a Map by themselves which makes less sense when the meters are already cached by micrometer, we should just be able to provide labels and record things, if we have to store the dynamically created gauges in a map itself that what is the point.

**Comment by shakuzen** [comment]
> I just wanted to simply do on my per function / parameter basis what is the number of concurrent request going on and I have to do a lot in order to achieve this.

It sounds like you want a [LongTaskTimer](https://docs.micrometer.io/micrometer/reference/concepts/long-task-timers.html) instead of a Gauge, unless you really don't want info about the time spent on in-progress requests.

**Comment by jonatan-ivanov** [comment]
Based on the quote in Tommy's comment it seems pretty likely to me as well that you need a `LongTaskTimer`. If not, please read the rest of this comment.

>I am not sure if this works for me, see the example that you have given is still having both the labels and the values fixed.

The tag (label) names ~"must be" fixed since a different set of tag means it's a different metric so the name of the metric as well as the meter instance should be different (even if you write a `SyncronousGauge`).

The tag values as well as the value of the `Gauge` are totally dynamic in the sample, they come from method calls:
```java
.map(record -> Row.of(Tags.of("room", record.getRoom().name()), record.getTemperature()))
```
This will create as many `Gauge`s as many room names you have dynamically, also you can add as many tags as you want.

If this still not what you can use, could you please give us simple Java example that we can play with and shows what you need to do to workaround the async nature of the Gauge (something like the room temperature example I linked above)?
