### ISSUE TITLE
Use Duration for @Timed SLOs instead of double

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#5299]
SLOs were introduced for `@Timed` in https://github.com/micrometer-metrics/micrometer/pull/5145. The original "contract" in that PR looks like this:
https://github.com/micrometer-metrics/micrometer/blob/ea51e72207ee6d42879329252ab45352b23c2429/micrometer-core/src/main/java/io/micrometer/core/annotation/Timed.java#L84

The SLOs contract of the `Timer` (Builder) on the other hand looks like this:
https://github.com/micrometer-metrics/micrometer/blob/ea51e72207ee6d42879329252ab45352b23c2429/micrometer-core/src/main/java/io/micrometer/core/instrument/Timer.java#L401

As you can see the annotation uses an array of `double` while `Timer` uses and array of `Duration`. I was wondering if we should make the contract the same (i.e.: using `Duration` for `@Timed` too).

This would eliminate any confusion about the time unit in the annotation and some complexity by not converting the double values to nanos, cast back to long and create a Duration anyways: https://github.com/micrometer-metrics/micrometer/blob/ea51e72207ee6d42879329252ab45352b23c2429/micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java#L261-L264

I think the original contract in the PR above can be shorter:
```java
@Timed(value = "test", serviceLevelObjectives = { 0.1, 0.5 })
```
but using `Duration` instead can be more expressive and consistent to the `Timer` contract:
```java
@Timed(value = "test", serviceLevelObjectives = { Duration.ofMillis(100), Duration.ofMillis(500) })
```

@lcavadas What do you think?

**Comment by lcavadas** [comment]
@jonatan-ivanov Because this is an annotation, you won't be able to use `Duration` directly. See https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.1

You would have to create a new annotation to hold the value and the ChronoUnit. For example something like:

```
@Retention(RUNTIME)
@Target({METHOD})
@Introspected
public @interface Objective {
  long value();
  ChronoUnit unit() default ChronoUnit.MILLIS;
}
```

```
@Timed(
  value = "test", 
  serviceLevelObjectives = { 
    @Objective(value=100, unit=ChronoUnit.MILLIS), 
    @Objective(value=500, unit=ChronoUnit.MILLIS) 
  }
)
```

which would then be converted like:
```
 .serviceLevelObjectives( 
         timed.serviceLevelObjectives().length > 0 ? Arrays.stream(timed.serviceLevelObjectives()) 
             .map(s -> Duration.of(s.value(), s.unit())) 
             .toArray(Duration[]::new) : null); 
```

I'm not opposed to this at all but it might not be as clean as you were originally intending.

**Comment by jonatan-ivanov** [comment]
I forget about this restriction time to time. :|

I guess another (bad) alternative can be using `String[]` which can contain the value and the unit as well but since writing a parser does not seem like a good idea. Also, the smallest unit for `Duration.parse()` is seconds and that needs to be presented in the ISO-8601 duration format with the period and time indicators (`PnDTnHnMn.nS`)  e.g.: `"PT0.1S"`, I think it might make things worse (and probably less performant).

Let me close this issue, if anyone has any idea for improvement, please leave a comment here.
