### ISSUE TITLE
Apache HTTP client instrumentation

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#533]
It looks like there is already [OkHttp instrumentation](https://github.com/micrometer-metrics/micrometer/blob/d30ca20c13e0682e6e78fa4c4c32dc75c5f9c1ac/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java) (which isn't documented as far as I can tell). It would be nice if there were also instrumentation for the [Apache HTTP client](https://hc.apache.org/). This would help achieve HTTP client instrumentation in cases where people are using the HTTP client directly (instead of through `RestTemplate` in a Spring application) or for things like the [Elasticsearch Java Low Level REST](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.2/java-rest-low-usage-initialization.html).

**Comment by ravin-singh** [comment]
@benhubert How it's going with the testing of pool monitoring? I would like to use for one of our app in case it can be made available.

**Comment by benhubert** [comment]
@ravin-singh Sorry. We are working on some other big changes at the moment, which are causing delays for this particular task. But it looks like we are able to continue with this next week, so I should be able to prepare the pull request soon.

**Comment by ravin-singh** [comment]
Thanks @benhubert. For mean time I have created a workaround solution that exposed pool stats to micrometer. 
https://gist.github.com/ravin-singh/8654b654163c508cdb227a621fe078f0

**Comment by shakuzen** [comment]
With the merged pull requests, I'm considering this enhancement request complete. There is now `MicrometerHttpRequestExecutor` which can be used to time requests made from an Apache `HttpClient`, and there is `PoolingHttpClientConnectionManagerMetricsBinder` which provides metrics on the connection pool for a `PoolingHttpClientConnectionManager`.

I've opened up follow-up issues to track other ideas for metrics for Apache HttpClient. See #1616 and #1617.

**Comment by j-gurda** [comment]
Thank you for your contribution!

I just wonder how I may use `PoolingHttpClientConnectionManagerMetricsBinder` with HTTP Client constructed with `HttpClientBuilder`. The problem is that  `HttpClientBuilder` internally instantiates `PoolingHttpClientConnectionManager` baseing on a bunch of configuration properties (see `HttpClientBuilder::build`. Maybe I miss something but I believe it's impossible to access such `PoolingHttpClientConnectionManager` in a "civilized way" and I need to use reflection:

```java
try {
    Class<?> internalHttpClient = Class.forName("org.apache.http.impl.client.InternalHttpClient"); // HttpClientBuilder returns InternalHttpClient which is an internal implementation of CloseableHttpClient
    Field connManagerField = internalHttpClient.getDeclaredField("connManager");
    connManagerField.setAccessible(true);
    PoolingHttpClientConnectionManager connManager = (PoolingHttpClientConnectionManager) connManagerField.get(client);
    new PoolingHttpClientConnectionManagerMetricsBinder(connManager, "proxyHttpClient").bindTo(meterRegistry);
} catch (ClassNotFoundException | NoSuchFieldException | IllegalAccessException e) {
     // some error handling here
}
```

**Comment by GguptaBlackBuck** [comment]
@j-gurda I am facing the exact same problem. Have you been able to find any workaround?

**Comment by shakuzen** [comment]
@j-gurda usage questions like this can easily be lost on closed issues (especially old, closed issues). StackOverflow or our Slack channel are a better place for such questions. You can make your own `PoolingHttpClientConnectionManager` and pass it to both the builder and the meter binder like:

```java
PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager();
HttpClient httpClient = HttpClientBuilder.create().setConnectionManager(connectionManager).build();
new PoolingHttpClientConnectionManagerMetricsBinder(connectionManager, "my-pool").bindTo(registry);
```
