### ISSUE TITLE
Metrics not collected after ExecutorService recreation

### ISSUE THREAD

**Issue by ajax-surovskyi-y** [micrometer-metrics/micrometer#5366]
**Describe the bug**
When using Micrometer to collect metrics from an `ExecutorService`, I wrap it with `ExecutorServiceMetrics.monitor`. In the framework logic that I use, the original ExecutorService shuts down if it is not used for some time, and then it is recreated as needed. After it is recreated, metrics are not collected from it because it is created with the exact same name, and all methods like `ThreadPoolExecutor::getCorePoolSize` are called on the `ThreadPoolExecutor` that has already been shut down. I have created a [PR](https://github.com/micrometer-metrics/micrometer/pull/5367) with a test for this problem and a potential fix.
**Environment**

 - Micrometer version 1.13.1
 - Micrometer registry statsd
 - OS: Linux
 - Java version: 21.0.1

**To Reproduce**
How to reproduce the bug:

1. Wrap an `ExecutorService` with `ExecutorServiceMetrics.monitor.`
2. Allow the shutdown.
3. Recreate the ExecutorService.
4. Observe that metrics are not being collected.

**Expected behavior**
Metrics should continue to be collected from the recreated ExecutorService.

**Additional context**

**Comment by slovdahl** [comment]
Nice that this was fixed 👍

I think the `TimedScheduledExecutorService` variant still has the same problem? I could maybe look into it following a similar pattern if no one else feels like it.

**Comment by jonatan-ivanov** [comment]
@slovdahl I think it has, please feel free to open a PR to fix it.

**Comment by slovdahl** [comment]
https://github.com/micrometer-metrics/micrometer/pull/6920
