### ISSUE TITLE
ObservationValidator fails with NullObservation

### ISSUE THREAD

**Issue by chemicL** [micrometer-metrics/micrometer#5388]
**Describe the bug**

When empty scopes are present thanks to `NullObservation`, the validation with `ObservationValidator` fails.

**To Reproduce**

https://github.com/micrometer-metrics/tracing/pull/810

**Expected behavior**

`NullObservation` doesn't cause `ObservationValidator` to fail.

**Additional context**

The issue is that `NullObservation` doesn't launch handlers for most events (e.g. start) but it launches handlers for scope opening and closing events. Combined with `ObservationValidator` being implemented as a handler this always causes `NullObservation` to trigger a failure.

**Ideas, notes**

It is crucial that `NullObservation` doesn't do unnecessary work as it is often on the hot path in reactive chains.

Therefore, perhaps it's worth considering an alternative implementation only created at **test** runtime which fires up all handlers. That code would need to interact with `ObservationThreadLocalAccessor`.

Another idea would be to skip validation on `NullObservation`, e.g. by providing

    context -> !"null".equals(context.getName())

as `supportsContextPredicate` argument to `ObservationValidator`.

**Comment by shakuzen** [comment]
A new `NullContext` was introduced to make the conditional less brittle for ignoring `NullObservation` in the `ObservationValidator`.
