### ISSUE TITLE
Springboot App startup failed in integration tests

### ISSUE THREAD

**Issue by Eloo** [micrometer-metrics/micrometer#54]
Hi,
i'm facing an issue when running multiple integration tests one after another. 
It seems that some collectors are tried to be registers twice.
`Collector already registered that provides name: jvm_buffer_count`
Any idea how to get this fixed?

Thanks

**Comment by checketts** [comment]
I suspect we need to enable swapping out the default registry that is a static variable. This is using the prometheus registry?

**Comment by Eloo** [comment]
yep i'm using prometheus registry and the prometheus springbootmetriccollector if this is helpful

**Comment by jkschneider** [comment]
Good call @checketts. Should never have used the default collector in the first place. With the change to `PrometheusMetricsConfiguration`, we'll instantiate a new collector registry every time (and of course you could override it with a `@Primary @Bean`.

**Comment by Eloo** [comment]
are there any plans to schedule the next release?
or can you provide a workaround to get my app running? ;)

**Comment by Eloo** [comment]
okay got it by adding the following:

```
    @Bean
    @ConditionalOnMissingBean
    CollectorRegistry collectorRegistry() {
        return new CollectorRegistry();
    }

    @Bean
    @Primary
    PrometheusMeterRegistry meterRegistry() {
        return new PrometheusMeterRegistry(collectorRegistry());
    }
```

**Comment by Eloo** [comment]
with my previous version above the springboot metrics where gone.
so i need to do the following to get this working with the springboot metrics

```
    @Bean
    @ConditionalOnMissingBean
    CollectorRegistry collectorRegistry() {
        CollectorRegistry collectorRegistry = new CollectorRegistry();
        collectorRegistry.register(springBootMetricsCollector(null));
        return collectorRegistry;
    }

    @Bean
    @Primary
    PrometheusMeterRegistry meterRegistry() {
        return new PrometheusMeterRegistry(collectorRegistry());
    }

    @Bean
    @Primary
    public SpringBootMetricsCollector springBootMetricsCollector(Collection<PublicMetrics> publicMetrics) {
        SpringBootMetricsCollector springBootMetricsCollector = new SpringBootMetricsCollector(publicMetrics);
        springBootMetricsCollector.register();
        return springBootMetricsCollector;
    }
```

**Comment by olavholten** [comment]
If you have EG. several Counters, they need to have a unique name when you define them in your Bean / PrometheusConfig.

@Bean(name = "transactionCounter")
  @Scope(value = ConfigurableBeanFactory.SCOPE_SINGLETON)
  Counter transactionCounter() {
    return Counter.build()
        .name("transactionCounter")
        .help("Total number of successful transactions.")
        .register(registry);
  }

And the class that uses that Counter bean needs to specify this name.

@Qualifier("transactionCounter") Counter transactionCounter

Hope that helps.
