### ISSUE TITLE
small breaking change in micrometer-core 1.0.3

### ISSUE THREAD

**Issue by pjfanning** [micrometer-metrics/micrometer#541]
The constructor on AbstractTimer was changed and this required me to modify some of my code when uptaking v1.0.3 (cf https://github.com/pjfanning/micrometer-kamon/commit/96f321361f69a423fb1ffe5633d8b9363ba0f040).

The micrometer change was in https://github.com/micrometer-metrics/micrometer/commit/ef2dad5bd5542c6f88c02f11c6df93ebabe02e7c

It's not a big deal but for backward compatibility reasons, it might be a good idea to put back the old AbstractTimer contructor (keeping the new one too) and deprecate the old one.

**Comment by jkschneider** [comment]
Thanks for pointing this out @pjfanning. It will be restored for 1.0.4.
