### ISSUE TITLE
TimedAspect for Webflux

### ISSUE THREAD

**Issue by vecnick** [micrometer-metrics/micrometer#5410]
**Please describe the feature request.**
TimedAspect catches errors by try/catch that doesn't work in webFlux, can you add a support for reactive spring apps, with Mono/Flux.

**Rationale**
It needs for many cases in metrics observation. 
(its difficult understand how to override histogram In GraphQl.)

Thanks for a spending time and answer!

**Comment by jonatan-ivanov** [comment]
Project reactor has Micrometer support, please check the .tap operator for reactor publishers, it does the same.
