### ISSUE TITLE
Add marker `TagsProvider` interface to Spring Boot

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#542]
Just a marker superinterface of both `RestTemplateExchangeTagsProvider`, `WebMvcTagsProvider`, and `WebFluxTagsProvider`. Functionally this does nothing, but eases the discovery of tags providers on the classpath.

cc / @twicksell

**Comment by izeye** [comment]
@jkschneider I created #909 to resolve this.
