### ISSUE TITLE
MeterFilter could benefit greatly from some static Builder options

### ISSUE THREAD

**Issue by twicksell** [micrometer-metrics/micrometer#545]
`MeterFilter.renameTag(...)` is pretty useful, but each one returning an instance of MeterFilter requiring its own bean definition can become a bit verbose. It may be useful to have something along the lines of:

```
@Bean
public MeterFilter metricRenamer() {
     return MeterFilter
                  .renameTag("someMetric1", "someBadTag1", "someGoodTag1")
                  .renameTag("someMetric2", "someBadTag2", "someGoodTag2")
                  .deny(...)
                  .ignoreTags(...);
}
```

All of the methods on MeterFilter seem very useful, but they could be easier to string together.

**Comment by jkschneider** [comment]
Hopefully this is sufficiently succinct:

```java
@Bean
public MeterRegistryCustomizer<MeterRegistry> metricRenamer() {
     return r -> r.config()
        .meterFilter(renameTag("someMetric1", "someBadTag1", "someGoodTag1"))
        .meterFilter(renameTag("someMetric2", "someBadTag2", "someGoodTag2"))
        .meterFilter(deny(...))
        .meterFilter(ignoreTags(...));
}
```

**Comment by marcingrzejszczak** [comment]
Can we assume that Jon's answer is the correct one?

**Comment by shakuzen** [comment]
It's an alternative to what Taylor was asking for that doesn't require code changes in Micrometer. Though `MeterRegistryCustomizer` is a Spring Boot class. I think until we hear from more users about this, we can close for now.
