### ISSUE TITLE
Global metrics get updated multiple times if there are multiple MeterRegistry beans

### ISSUE THREAD

**Issue by crmky** [micrometer-metrics/micrometer#546]
My application uses micrometer-core 1.03 with micrometer-spring-legacy. When it starts, there are three `MeterRegistry` beans get created:
- `PrometheusMeterRegistry` bean comes with `micrometer-registry-prometheus`.
- a customized implementation based on `DropwizardMeterRegistry`.
- `CompositeMeterRegistry` bean created by `micrometer-spring-legacy`. And it contains the previous two registries.

The problem is all of those beans are added into `globalRegistry` in `Metrics` class by `MeterRegistryPostProcessor`. The hierarchy becomes:
- Global Registry
  - PrometheusMeterRegistry
  - DropwizardMeterRegistry
  - CompositeMeterRegistry
     - PrometheusMeterRegistry
     - DropwizardMeterRegistry

 If I defined a counter in global registry, the counter value in `PrometheusMeterRegistry` and `DropwizardMeterRegistry` will be updated twice.

**Comment by jkschneider** [comment]
Fixed by 79047359

**Comment by rafal-dudek** [comment]
The problem still exists.

In our application we have 2 registries: PrometheusMeterRegistry and JmxMeterRegistry.
There is created automatically CompositeMeterRegistry.

Some metrics are doubled e.g. "logback_events_total" (io.micrometer.core.instrument.binder.logging.LogbackMetrics).

We are using spring-boot-actuator-autoconfigure:2.1.3.RELEASE, micrometer-registry-prometheus:1.1.3 and micrometer-registry-jmx:1.1.3.
