### ISSUE TITLE
Add disk space binder

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#549]
Available in Spring Boot Actuator health endpoint:

```
{
  "status": "UP",
  "details": {
    "total": 1056858112,
    "free": 816021504,
    "threshold": 10485760
  }
}
```

**Comment by jkschneider** [comment]
Sorry, no threshold. Just a regular set of gauges. Only mention actuator health because we can go peek at that implementation and lift the bits that calculate the sizes.

**Comment by shakuzen** [comment]
Here is the implementation: https://github.com/spring-projects/spring-boot/blob/b5c4ce230df815273bcc7d3c05de438d9d6da846/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/system/DiskSpaceHealthIndicator.java

**Comment by izeye** [comment]
This looks resolved mainly via #674 and hopefully can be closed when #702 and #703 are merged.

**Comment by soad666p** [comment]
there any update on this ?

**Comment by marcingrzejszczak** [comment]
It's been out there for a long time already https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/DiskSpaceMetrics.java
