### ISSUE TITLE
Better API and SPI separation

### ISSUE THREAD

**Issue by marschall** [micrometer-metrics/micrometer#5494]
**Please describe the feature request.**

Introduce a clear separation between the [API](https://en.wikipedia.org/wiki/API) for client code and the [SPI](https://en.wikipedia.org/wiki/Service_provider_interface) for metric registry implementations.

**Rationale**

The `Meter` hierarchy currently acts both as an API for client code using Micrometer and as an SPI for metric registry implementations. Client code will never call meter registry implementations directly, rather it will always to through the `CompositeMeter` hierarchy implementations. This makes it unclear what a metric registry actually needs to implement. For example a metric registry may override `io.micrometer.core.instrument.LongTaskTimer#record(BooleanSupplier)` to avoid the `Sample` allocation. However because calls always to through `CompositeLongTaskTimer` that method is never actually called.

I feel this would help custom meter registry implementations as documentation regarding implementing a custom registry is [spare](https://micrometer.io/docs/guide/customMeterRegistry) and it's not always easy to tell at first hand what does and doesn't need to be implemented. This experience is based on implementing [my own meter registry](https://github.com/marschall/micrometer-jfr).

This could also help to simplify SPI implementations. For example it's not clear to me why every SPI implementation needs to implement `LongTaskTimer#activeTasks()` when that could be simply done in `CompositeLongTaskTimer`. In general everything that delegates to `AbstractCompositeMeter#firstChild()` is probably something that may be moved from an SPI implementation to `AbstractCompositeMeter`.

**Additional context**

The first example that comes to mind is [JCE](https://docs.oracle.com/en/java/javase/21/security/java-cryptography-architecture-jca-reference-guide.htm) that separates the API and SPI interfaces.

**Comment by shakuzen** [comment]
Thank you for opening this and sharing the difficulties in making a custom MeterRegistry implementation. The documentation could definitely be better. What needs to be done or doesn't need to be done largely depends on the nature of the metrics backend the implementation is for, which makes it difficult to determine how much should be written in the documentation on the topic. It is probably more useful for many people to look at the existing registry implementations we have [here](https://github.com/micrometer-metrics/micrometer/tree/main/implementations). We're also usually happy to review and give feedback on implementations to the extent we have time and enough domain knowledge to do so. 

There seems to be some confusion about the Composite types. MeterRegistry implementations can be used without a CompositeMeterRegistry (and consequently CompositeMeter types) involved. So there is no expectation that calls will necessarily go through composite types. Maybe the confusion comes from the static methods available on `Metrics`. Those are provided as a convenience in situations where it is not possible to pass a MeterRegistry instance. In environments where global statics do not need to be use, we recommend they are not. Typically, it is expected the API on MeterRegistry will be used to register and interact with meters, which if there is only one (non-global) MeterRegistry in an application, it would be reasonable for it to not be a composite registry and used directly.

We're not opposed to some kind of more clear separation that makes responsibility and implementation more apparent. The challenge would be to introduce such changes in a non-breaking way. Suggestions are welcome.

**Comment by marschall** [comment]
Thanks for the quick reply. I indeed seem to have been confused regarding the Composite types. I'll check if indeed the static methods on `Metrics` are ghte issue.

Yes, the included registry implementations are indeed helpful. However as you mentioned the nature of the metrics backend the implementation may differ quite dramatically it so may not be easy to find the implementation most appropriate to look at.

**Comment by shakuzen** [comment]
Let us know if we can clear anything else up or if you have ideas on how to make the documentation better or any suggestions on code changes. We appreciate the feedback and discussion.
