### ISSUE TITLE
Add ability for Prometheus default registry to be able to report

### ISSUE THREAD

**Issue by checketts** [micrometer-metrics/micrometer#55]
Micrometer instantiates its own instance of `CollectorRegistry`. This means that metrics that are wired in using the static/default one will not be reported via the micrometer wired endpoint.

**Comment by jkschneider** [comment]
Is the only difference the value of `autoDescribe` in the constructor?

**Comment by checketts** [comment]
The main difference is that the default one is a static global. And if users create a metric using the default/recommended client directly: `Counter.build("my_metric).help("help").register()`, that `register` call will register the metric with the default registry.

Since that registry is disconnected from the Micrometer one, the counter won't get reported.

**Comment by jkschneider** [comment]
I see. Would you like to do something automatically or just advise Prometheus users to create

`@Bean CollectorRegistry prometheusCollector() { return Collector.defaultRegistry; }`

in the event that they are going to be doing mixed-instrumentation with Micrometer and the Prometheus simpleclient?

**Comment by checketts** [comment]
Something automatically is probably needed since creating a bean using the default registry gets them back into the problem with integrations tests failing from metrics being registered twice.

**Comment by jkschneider** [comment]
Integration tests would only fail if somehow the metrics registered in two different tests had different tag keys right? Is this scenario plausible?

**Comment by checketts** [comment]
The failure would have to be a perfect storm of:
- Using Prometheus directly instead of micrometer
- Wiring up the metric in the constructor, instead of as a static variable.

So app users won't likely hit this problem, since in their code they would use micrometer directly, or follow the Prometheus pattern of the static variable. 

If they have a bean that is wiring up other collectors: like https://github.com/prometheus/client_java/blob/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/GarbageCollectorExports.java#L18 they could have a problem. But that is a very corner case (and solve-able in itself)

**Comment by jkschneider** [comment]
Since the solution to this would be quite circuitous I think, is it close-worthy?
