### ISSUE TITLE
Add configuration property to disable MetricsRestTemplateCustomizer

### ISSUE THREAD

**Issue by mkrichevsky** [micrometer-metrics/micrometer#554]
I think it would be more convenient way of disabling

**Comment by jkschneider** [comment]
I think the Spring Boot team is going to point out that you can do this with an exclude:

```java
@SpringBootApplication(exclude = RestTemplateMetricsAutoConfiguration.class)
```

It's unlikely that they'll add another property additionally.

**Comment by mkrichevsky** [comment]
Can micrometer has its own property in `RestTemplateMetricsConfiguration`?
I think it's a little bit inconsistent that some meters can be disabled by properties and the others by exclusion in annotations.
Maybe I'm missing something here?

**Comment by jkschneider** [comment]
There is only one metric coming out of rest template metrics: `http.client.requests`. So disabling it just requires:

```
management.metrics.enable[http.client]=false
```

The binders, OTOH create several metrics, which is why I suppose they added a single disablement property. But even that was probably unnecessary as all OOTB binders use a consistent name prefix internally.

```
management.metrics.enable[hystrix]=false
management.metrics.enable[jvm.gc]=false
management.metrics.enable[jvm.memory]=false // notice you could collapse this with just [jvm]
```

**Comment by mkrichevsky** [comment]
I can tell about `logback` meter, as I debugged the behavior with different configurations:
With `management.metrics.enable[logback]=false` I indeed don't have any metrics about logs, but [decide method](https://github.com/micrometer-metrics/micrometer/blob/09f3ea7963da6135cd253f6e26de8a910273c8fa/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/LogbackMetrics.java#L126) is still invoked on every log.
However, with `management.metrics.binders.logback.enabled=false` property the [bean](https://github.com/micrometer-metrics/micrometer/blob/09f3ea7963da6135cd253f6e26de8a910273c8fa/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/MeterBindersConfiguration.java#L73) is not created at all, thus the `decide` method is never called.
I don't know why the behavior is different. If you want, tomorrow I can debug other binders. Or maybe you know why this happens?

**Comment by mkrichevsky** [comment]
Tbh, I would prefer the ability to configure through properties. (I like how `endpoints` configuration is done, where I can disable all of them and enable only those that I want/need).
But I'm not sure how easy it would be to implement the same here and if it would make sense to do such thing at all.
Any other thoughts?

**Comment by checketts** [comment]
You can exclude autoconfiguration via properties.

**Comment by mkrichevsky** [comment]
Yes, you're right.
Well, if I'll be able to include only those configurations that I need, then it should be good enough.
May I ask why don't you want to introduce separate properties for this?

**Comment by jkschneider** [comment]
@mkrichevsky The Spring Boot team is generally unhappy with adding multiple properties to achieve the same thing.
