### ISSUE TITLE
add config for Rate aggregation

### ISSUE THREAD

**Issue by inventoryz** [micrometer-metrics/micrometer#555]
Our counter exported to Prometheus endpoint get auto converted to counts/second

Is there an config to turn off rate aggregation?

**Comment by checketts** [comment]
Can you post the the metrics you are seeing on the Prometheus endpoint and what you would expect them to look like?

By default Micrometer counters don't create any sort of counts/second that I can think of. Is your counter created using Micrometer directly?

**Comment by jkschneider** [comment]
Micrometer does not pre-aggregate counters, like @checketts suggests. Closing this for now. Feel free to reach out to us if you still have trouble here.
