### ISSUE TITLE
MicrometerHttpRequestExecutor fails to instrument with Apache HC 5.4

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#5575]
Our implementation overrode one of the two `execute` methods from `HttpRequestExecutor`. From Apache HC 5.4, it seems the other is the one that gets called, while the default implementation of the one we override delegates to the other. We can make our implementation more robust by overriding both and delegating one to the other similarly. This was discovered in failed tests for the pull request to upgrade to Apache HC 5.4 https://github.com/micrometer-metrics/micrometer/pull/5525

**Comment by flozano** [comment]
I am not sure this is fully fixed for the async version. After upgrading to 1.13.6, I get again the request metrics, but something has changed.

Before Http client 5.4 I got:

```
httpcomponents_httpclient_request_seconds_sum{httpclient="hc5async",method="GET",outcome="CLIENT_ERROR",status="401",target_host="0.0.0.0",target_port="50964",target_scheme="http",uri="/"}
```

now I am getting:
```
httpcomponents_httpclient_request_seconds_sum{httpclient="hc5async",method="GET",outcome="CLIENT_ERROR",status="401",target_host="UNKNOWN",target_port="UNKNOWN",target_scheme="UNKNOWN",uri="/"}
```

is this expected?
