### ISSUE TITLE
micrometer-observation-test support for assertions on events

### ISSUE THREAD

**Issue by wabrit** [micrometer-metrics/micrometer#5576]
**Please describe the feature request.**
The `micrometer-observation-test` dependency does not appear to offer a simple way of asserting on observation events in tests

**Rationale**
The `TestObservationRegistryAssert` class handles assertions on what observations have been made, the key values associated with an observation, etc. But it does not appear to provide support for asserting that particular calls to `Observation#event(...)` have been made.

This is necessary to provide test coverage for observations which raise events.

**Additional context**
This is based  on using version `1.13.2` of `io.micrometer:micrometer-observation-test`

**Comment by shakuzen** [comment]
@wabrit thanks for opening the issue. It sounds like a useful enhancement. Would you be interested in contributing a pull request for this?

**Comment by wabrit** [comment]
Hi @shakuzen - I'd be happy to try, and I do have my own "workaround", but perhaps it would be a good idea to submit some kind of API design proposal first before a PR? Is here the right place to do that?

**Comment by shakuzen** [comment]
Sure, here is fine. Leave a comment with what you have in mind.

**Comment by wabrit** [comment]
What I envisaged would be to extend the `TestObservationRegistryAssert` class (and supporting classes) to support this:

```java
TestObservationRegistryAssert.assertThat(observationRegistry)
        .hasObservationWithNameEqualTo("foo")
        .that()
        .hasEvent("event1") /* at least one event with name event1 in observation */
        .hasEvent("event2", 3) /* exactly 3 events with name event2 in observation */
        .doesNotHaveEvent("event3") /* no events with name event3 in observation */
        ....
```

**Comment by wabrit** [comment]
Hi all - does the above proposal sound ok before I embark on a PR, and (not having committed to this project before) is there a guide to that process? (I assume I need to fork the repo and create a branch on the fork to submit the PR against)

**Comment by shakuzen** [comment]
Your proposal looks reasonable to me. As for contributing, check the [contributing guide](https://github.com/micrometer-metrics/micrometer/blob/main/CONTRIBUTING.md). Yes, forking the repo and committing the changes to a branch in that fork and submitting a pull request would be the right process.

**Comment by wabrit** [comment]
Apologies - not an everyday user of gradle; I forked the repo, created a branch and cloned it to my local IDE. But running `./gradlew` from the root directory gave me the following error:

```
Build file 'C:\Dev\git_repos\micrometer\micrometer\build.gradle' line: 51

A problem occurred evaluating root project 'micrometer'.
> Could not get unknown property 'release' for root project 'micrometer' of type org.gradle.api.Project.
```

**Comment by wabrit** [comment]
PR raised: https://github.com/micrometer-metrics/micrometer/pull/5605
