### ISSUE TITLE
[OTLP Registry] Documentation not showing the batch size configuration

### ISSUE THREAD

**Issue by joaopgrassi** [micrometer-metrics/micrometer#5578]
**Please describe the feature request.**
The current docs only mention the `step` config which is the equivalent to the export interval in OTel SDKs. But I saw that there's also a "batch size" which would also be nice to have in the docs. 

**Rationale**
Usually these two properties go together so I think it's a good idea to demonstrate to users that those options are available.

**Additional context**
It is common for metric back-ends to have limits on the size or/and the amount of metrics in a single export request. With both the interval and batch size, users can tweak things to make sure their metric requests stay under the limits.

**Comment by shakuzen** [comment]
Thanks for bringing it to our attention. A pull request would be welcome. As a side note, we have been thinking about ways to keep the docs about configuration options in sync with the code but we haven't implemented anything so far, so these things happen from time to time.
