### ISSUE TITLE
Aspects' tagsBasedOnJoinPoint may throw uncaught exception

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#5584]
We should catch the exception to avoid the aspect handling from causing an exception when calling user code. Originally found in https://github.com/micrometer-metrics/micrometer/pull/2462#discussion_r1796500121 courtesy of @kinddevil.

**Comment by jonatan-ivanov** [comment]
Closed by https://github.com/micrometer-metrics/micrometer/pull/5585
