### ISSUE TITLE
How to count exceptions with controlleradvice?

### ISSUE THREAD

**Issue by Eloo** [micrometer-metrics/micrometer#56]
Hi,

i would like to keep track of thrown exception in a request but it seems that this is not possible if the request is catched by a controller advice. 
Any idea how i can track thrown exception with controller advices?

Thanks

**Comment by jkschneider** [comment]
Exceptions are already tracked as a dimension on `@Timed` controllers. See [WebmvcTagConfigurer](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/web/WebmvcTagConfigurer.java#L91). So you should be able to just do a little dimensional drill down in your Prometheus query to group your graph by exception.

If you'd like to add a separate counter for whatever reason, note that you can write a `HandlerInterceptorAdapter`. The `afterCompletion` method contains a reference to thrown exceptions.

**Comment by Eloo** [comment]
okay but the problem seems to be that the controller advice catches the exception and so @timed at the restcontroller will not see the exception

**Comment by checketts** [comment]
@Eloo Why not count within the Controller advice itself?

I'm currently counting exceptions in a filter, actually just counting response status code. In the past I would check for exceptions via a `Request.getAttribute` call.

**Comment by jkschneider** [comment]
@checketts @Eloo I understand the use case. If we can register a higher priority `@ControllerAdvice` that stuffs the exception in a request attribute like you say, then the exception will be captured by default by `WebMvcTagConfigurer`, and there is no need for additional manual counting.

**Comment by checketts** [comment]
@jkschneider Unfortunately `@ControllerAdvice` don't act like filters though. If the higher priority `@ControllerAdvice` handles the exception it won't bubble up, and you can't rethrow in a `@ControllerAdvice` without consequences.

**Comment by jkschneider** [comment]
Sounds like you know that dark corner of Spring better than I. Worst case, this may be a Boot 2 feature only. Maybe a custom `HandlerExceptionResolver` for Boot 1? Not sure.

**Comment by checketts** [comment]
> you can't rethrow in a @ControllerAdvice without consequences

Sorry if that sounded too mystical. I haven't actually tried rethrowing for another `ControllerAdvice` to handle. I do have code the routinely rethrows from the ControllerAdvice and it just causes Spring internals to log stuff about controller advice failing to be run.

**Comment by Eloo** [comment]
@checketts if i count the exception in the controller advice i'm not able to 100% map the exception to an request in the metrics without some extra work.

in dropwizards metrics i'm able to annotate my endpoint with @ExceptionMetered and will receive proper metrics for this endpoint and exception thrown during this request.

**Comment by jkschneider** [comment]
Related problem in sleuth: https://github.com/spring-cloud/spring-cloud-sleuth/issues/585

**Comment by jkschneider** [comment]
I think this may be the best we are able to do:

```java
@ControllerAdvice
static class CustomExceptionHandler {
    @Autowired
    ControllerMetrics metrics;

    @ExceptionHandler
    ResponseEntity<String> handleDefaultError(HttpServletRequest request,
                                                        HttpServletResponse response,
                                                        Throwable ex) {
        metrics.record(request, response, ex);
        return new ResponseEntity<>("this is a custom exception body", HttpStatus.INTERNAL_SERVER_ERROR);
    }
}
```

I tested out a bunch of combinations, and it turns out that @checketts is right. `@ControllerAdvice` does not function like a filter -- once an exception is handled by one `@ControllerAdvice`, it's over, even if the exception is rethrown.

**Comment by Eloo** [comment]
@jkschneider that looks promising 
thanks

**Comment by Eloo** [comment]
@jkschneider 
just tested this code and it seems that the response code for the exception is mapped for the normal response code (200) and not the set status code from the ControllerAdvice.
So i guess you example will set statuscode to 200 in the metric but returns a 500 or not?
This is how it looks in my test
```
http_server_requests_count{method="POST",uri="/test",exception="IllegalArgumentException",status="200",exporter="micrometer",} 1.0
http_server_requests_count{method="POST",uri="/test",exception="None",status="500",exporter="micrometer",} 1.0
```

**Comment by jkschneider** [comment]
@Eloo Thanks for the excellent testing again. `ControllerMetrics` has changed now to just preserve the exception, like so:

```java
@ControllerAdvice
static class CustomExceptionHandler {
    @Autowired
    ControllerMetrics metrics;

    @ExceptionHandler
    ResponseEntity<String> handleError(HttpServletRequest request, Exception1 ex) throws Throwable {
        metrics.tagWithException(ex); // (1)
        return new ResponseEntity<>("this is a custom exception body", HttpStatus.INTERNAL_SERVER_ERROR);
    }

    @ExceptionHandler
    ResponseEntity<String> rethrowError(HttpServletRequest request, Exception2 ex) throws Throwable {
        throw ex; // (2) 
    }
}
```

It seems that regardless of whether you rethrow the exception or generate a different response entirely that the `MetricsHandlerInterceptor` still is triggered. So in the case that you are returning a different response, we'll just preserve the original exception like in **(1)**. If you rethrow the exception, `MetricsHandlerInterceptor` still receives it, like in **(2)**.

I've fixed up the spring release plugin, so if you run `./gradlew pTML` you should get a snapshot in your maven local repository that you could test with. You mind trying that, and if everything looks good, I'll cut an 0.9.1 with this fix.

Thanks again!

**Comment by Eloo** [comment]
@jkschneider
thanks for fixing this.. will test this in the new week

**Comment by Eloo** [comment]
So i've tested the new release and it seems to work like a charm ;) 
Thanks @jkschneider
