### ISSUE TITLE
Extend annotation io.micrometer.core.annotation.Timed

### ISSUE THREAD

**Issue by eugene-kuntsevich** [micrometer-metrics/micrometer#5657]
I'm using `@Timed` in my Spring Boot application to collect metrics from methods, and it’s working fine:

`@Timed(percentiles = {0.95, 0.99}, histogram = true, extraTags = {"slice", "client"})`

Since I use this annotation in multiple places, I decided to create a custom annotation, `@TimedExtended`:

```
import io.micrometer.core.annotation.Timed;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Timed(percentiles = {0.95, 0.99}, histogram = true, extraTags = {"slice", "client"})
public @interface TimedExtended {
}
```

However, this new annotation isn't working as expected, and metrics aren’t being sent to Influx. Do you have any suggestions for how to fix this?

**Comment by eugene-kuntsevich** [comment]
If you’re using a custom annotation that wraps `@Timed` (a meta-annotation), such as `@TimedExtended`, the pointcut from `io.micrometer.core.aop.TimedAspect` **_"execution (@io.micrometer.core.annotation.Timed * .(..))"_** won't match it directly. This is because the execution expression looks only for methods explicitly annotated with `@Timed`, and it won’t recognise methods annotated with `@TimedExtended`.

For solving this problem I created my own Aspect, took as a base `io.micrometer.core.aop.TimedAspect`:

```
@Aspect
public class TimedExtendedAspect {
...
  @Around("execution (@com.test.metrics.TimedExtended * *.*(..))")
  @Nullable
  public Object timedMethod(ProceedingJoinPoint pjp) throws Throwable {
    if (shouldSkip.test(pjp)) {
      return pjp.proceed();
    }

    Method method = ((MethodSignature) pjp.getSignature()).getMethod();
    TimedExtended timed = method.getAnnotation(TimedExtended.class);
    if (timed == null) {
      method = pjp.getTarget().getClass().getMethod(method.getName(), method.getParameterTypes());
      timed = method.getAnnotation(TimedExtended.class);
    }

    return perform(pjp, timed, method);
  }
...
}
```
Also I modified my annotation in the next way:

```
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface TimedExtended {

  String value() default "";

  boolean longTask() default false;

  String description() default "";

  String[] extraTags() default {"slice", "client"};

  boolean histogram() default true;

  double[] percentiles() default {0.95, 0.99};
}
```
Last step - create bean for new Aspect:

```
    @Bean
    TimedExtendedAspect timedExtendedAspect(InfluxMeterRegistry influxMeterRegistry) {
        return new TimedExtendedAspect(influxMeterRegistry);
    }
```

**Comment by jonatan-ivanov** [comment]
Fyi: if you produce histograms, you can calculate any percentiles on the backend from it, you don't need to publish percentiles too.
