### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by pjanuario** [micrometer-metrics/micrometer#5661]
**Describe the bug**
While running Grafana dashboard [4701 revision 10](https://grafana.com/grafana/dashboards/4701-jvm-micrometer/) on Grafana `grafana/grafana-oss:11.3.0` the rows for JVM Memory Pools Heap/Non heap and Buffer pools doesn't render panels in same row, but it will render one panel per row.

**Environment**

-  Grafana dashboard [4701 revision 10](https://grafana.com/grafana/dashboards/4701-jvm-micrometer/) 
- grafana/grafana-oss:11.3.0`

**To Reproduce**
How to reproduce the bug:
Launch the dashboard and see  the following

![JVM-Micrometer-Dashboards-Grafana-11-14-2024_10_27_AM](https://github.com/user-attachments/assets/5cfe8a25-e9be-415c-a567-687ca522795c)

**Expected behavior**
Render panels in the same row

**Comment by mweirauch** [comment]
The board is created by me and not officially affiliated with the Micromter team. Please head on over to <https://github.com/mweirauch/grafana-dashboards> and create the issue there.

I need to take care of updating it anyway soon'ish.

**Comment by pjanuario** [comment]
As it's referenced on the micrometer documentation, maybe it's a good idea to add note to the documentation.

**Comment by pjanuario** [comment]
Opened the ticket in the source repository: https://github.com/mweirauch/grafana-dashboards/issues/2
