### ISSUE TITLE
Migration from 1.9.x to 1.13.x

### ISSUE THREAD

**Issue by a-dudko** [micrometer-metrics/micrometer#5689]
Hi! We are migrating our project using `io.micrometer:micrometer-registry-prometheus` from 1.9.16 to 1.13.4

Unfortunately there is a scenario which is not covered in the migration guide.

Here is our scrapping controller
```
@WebEndpoint(id = "customPrometheus")
public class CustomPrometheusScrapeEndpoint {
    private final CollectorRegistry collectorRegistry;

    public BusinessPrometheusScrapeEndpoint(CollectorRegistry collectorRegistry) {
        this.collectorRegistry = collectorRegistry;
    }

    @ReadOperation(produces = {"text/plain; version=0.0.4; charset=utf-8"})
    public String scrape() throws IOException {
        Writer writer = new StringWriter();
        TextFormat.write004(writer, this.collectorRegistry.metricFamilySamples());
        return writer.toString();
    }
}
```
I see that both TextFormat and CollectorRegistry are already removed and there is no indication what the code above should be replaced with. Could you please give a hint here?

**Comment by jonatan-ivanov** [comment]
Thank you for the issue!
It seems the code above does not contain any Micrometer components, this is pure Prometheus Client. You can find the migration guide of the Prometheus Java Client here: https://prometheus.github.io/client_java/migration/simpleclient/

Also, if you want to use Micrometer, you can replace the code above with:
```java
return registry.scrape();
```

Please let us know if I misunderstood your request and/or you have an ide to improve docs/code/etc. and we can reopen this issue.
