### ISSUE TITLE
Add 'clear' method to SimpleMeterRegistry to support testing

### ISSUE THREAD

**Issue by mkopylec** [micrometer-metrics/micrometer#569]
There is no implementation of `MeterRegistry` suitable for intergration/e2e tests.
The `SimpleMeterRegistry` is almost OK, but it lacks of one major functionality.
Its `Meter`s cannot be reset and again filled with metrics.
The `close()` method makes the `SimpleMeterRegistry` useless when invoked.
Because the `SimpleMeterRegistry` is not reusable I need to start Spring Boot application every test method which is a simple waste of time.

**Comment by checketts** [comment]
Can you add a little more details about what you need the `SimpleMeterRegistry` to do in an integration test? Are you trying to use it to time your tests?

Also what behavior do you see when calling `close()` that makes it unusable?

**Comment by mkopylec** [comment]
In each test method I need to check that the `Timer` and `Counter` metrics were correctly recorded in the `MeterRegistry` by their name. Every test case collects identically named metrics but different number of times. When `Meter`s in the `MeterRegistry` are not cleared each test method than the `MeterRegistry.count()` method will return increased number each test method and the assertions will fail. There is no implemention of `MeterRegistry` that provides clearing metrics feature. I thought that maybe the `MeterRegistry.close()` clears metrics but after invoking the method the `MeterRegistry` is no longer accepting new metrics.

**Comment by checketts** [comment]
It appears that a `clear()` method would be useful. We've discussed this and the problems for why other registries like the PrometheusMeterRegistry can't support it (yet), but I don't think that should block `SimpleRegistry` from supporting it.

**Comment by jkschneider** [comment]
I think this is well covered by #479? Will close this in favor of the more general solution targeted for 1.1.0

**Comment by checketts** [comment]
I'm fine merging the 2 tickets. #479 seems to be targeted at unregistering individual meters. It would be nice to have an `un-register all` so the user doesn't have to iterate over all meters, they just want a fresh set of measures.

**Comment by jkschneider** [comment]
Agreed. Once we have the ability to "unregister individual" meters, clearing is trivial.

**Comment by kurtharriger** [comment]
This is closed, but I don't yet see a clear() method on SimpleMeterRegistry am I missing something? Thanks

**Comment by checketts** [comment]
@kurtharriger You are correct that `clear()` doesn't yet exist. The referenced tickets like #479 solved removing a single meter, clear would just be a convenience method around fetching all meters and removing each one.

**Comment by izeye** [comment]
@kurtharriger @checketts I created #1069 for this.
