### ISSUE TITLE
Adding machine name to the Statsd line text

### ISSUE THREAD

**Issue by itay-keller** [micrometer-metrics/micrometer#576]
We like to configure the line format of the Statsd packets sent, by adding the machine name to each packet. 
Change something like that :
`httpServerRequests.exception.None.method.POST.status.200.uri./doX:254.959825|ms`
to
`machineXYZ.httpServerRequests.exception.None.method.POST.status.200.uri./doX:254.959825|ms`

We found this [link](https://micrometer.io/docs/registry/statsD#_customizing_the_line_format), but when trying to add it to our code, the IDE complains that it doesn't recognize _MeterId_

Currently, in the pom.xml file, we have this dependency:

> 		<dependency>
>			<groupId>io.micrometer</groupId>
>			<artifactId>micrometer-registry-statsd</artifactId>
>			<version>1.0.3</version>
>		</dependency>

So we have few questions:

1. What is this _MeterId_ class, and how do we get/generate it? Is there a code sample that we can see example in?
2.  Is there a configuration way to tell micrometer to append something to the text being sent?

**Comment by itay-keller** [comment]
Hi, any update on this issue?

**Comment by jkschneider** [comment]
Hi @itay-keller. Sorry about the delay in answering. The documentation should read `Meter.Id`, not `MeterId`. The docs have been updated!

**Comment by jkschneider** [comment]
It looks like you are using the Etsy Statsd format. You can alernatively supply a custom `HierarchicalNameMapper` to the `StatsdMeterRegistry` constructor.

**Comment by jkschneider** [comment]
@itay-keller I think one of your colleagues has been asking the same question on Slack. Here is a full gist: https://gist.github.com/jkschneider/a7af362d51da99b21dd9c84484213a44
