### ISSUE TITLE
[Feature Request] Add Postgres Meter Binder

### ISSUE THREAD

**Issue by kristofdepypere** [micrometer-metrics/micrometer#577]
Postgres collects out of the box very relevant statistics to monitor the performance of the database. It is a matter of doing the correct queries and exposing these statistics the correct way in order to support postgres statistics through micrometer. 

I think the following article is a very nice summary of the postgres metrics that are very important and I think we should use it as a guideline to collect the correct metrics: https://www.datadoghq.com/blog/postgresql-monitoring/

**Comment by izeye** [comment]
This looks resolved via #578 .

**Comment by shakuzen** [comment]
Thanks @izeye. Duplicates #578
