### ISSUE TITLE
SimplePauseDetector never shuts down with micrometer-registry-prometheus

### ISSUE THREAD

**Issue by jensritter** [micrometer-metrics/micrometer#579]
Stopping a spring-boot(2.0.1) webapp with micrometer-registry-prometheus(1.0.3) deployed in a Tomcat8-Container won't stop SimplePauseDetectedThread_0.

To workaround the problem i'm currently disabling the PauseDetector, which was  mentiond in #438 : 

```
@Bean
public MeterRegistryCustomizer<MeterRegistry> metricsCommonTags() {
	return registry -> registry.config()
	    .pauseDetector(new NoPauseDetector());
}

```

**Comment by jensritter** [comment]
Nice. Thx for the fast reaction.

**Comment by jkschneider** [comment]
I had a bit of trouble reproducing, since `SimplePauseDetectorThread` is always a daemon. But we are now explicitly calling its `shutdown` method. Let me know if that works for you!
