### ISSUE TITLE
Improve performance when there are a lots of registered meters

### ISSUE THREAD

**Issue by vpugar** [micrometer-metrics/micrometer#585]
In case a very big number of meters to register, it takes relatively long to register all of them. 
I think the main problem is that for each registration, it is done a copy of HashMap of all registered meters. In the code on current master MeterRegistry.register:

   ```
    private void register(Id id, Meter meter) {
        HashMap<Id, Meter> newMeterMap = new HashMap<>(meterMap);
        newMeterMap.put(id, meter);

        meterMap = Collections.unmodifiableMap(newMeterMap);
    }
```

For example for registration of 20000 counters on a plain laptop registration takes around 33556ms. Here is an example of test: [MeterRegistryPerfTest](https://github.com/vpugar/micrometer/blob/pcollection/micrometer-core/src/test/java/io/micrometer/core/instrument/MeterRegistryPerfTest.java)

**Comment by vpugar** [comment]
Possible solution would be to use pcollections API ([pcollections](https://pcollections.org/)), specifically HashPMaps backed by IntTreePMaps implementation from there. 
Implementation of new MeterRegistry in that case is here: [MeterRegistry](https://github.com/vpugar/micrometer/blob/pcollection/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java)
The solution has better performance, for example on same laptop registration of 20000 meters takes around 506ms.

**Comment by jkschneider** [comment]
Thanks for all the work on this @vpugar. Really big improvement!
