### ISSUE TITLE
Negative cache miss metric

### ISSUE THREAD

**Issue by nickcodefresh** [micrometer-metrics/micrometer#586]
Hi,

I'm registering sme Hazelcast cache metrics using

```
HazelcastCacheMetrics.monitor(meterRegistry, hazelcastInstance.getMap(Constants.METADATA_DEFINITION_CACHE));
```
And then using then like this:
```
    @CachePut(value = Constants.METADATA_DEFINITION_CACHE, key = "#metadataDefinitionId", unless = "#result == null")
    public MetadataDefinition putMetadataDefinition(long metadataDefinitionId) {
        return getMetadataDefinitionMetadataInternal(metadataDefinitionId);
    }

    @Cacheable(value = Constants.METADATA_DEFINITION_CACHE, key = "#metadataDefinitionId", unless = "#result == null")
    public MetadataDefinition getMetadataDefinition(long metadataDefinitionId) {
        return getMetadataDefinitionMetadataInternal(metadataDefinitionId);
    }

    @CacheEvict(value = Constants.METADATA_DEFINITION_CACHE, key = "#metadataDefinitionId")
    public void removeFromCache(long metadataDefinitionId) {
    }
```
but somehow I'm getting negative miss values.
```
# HELP cache_gets_total the number of times cache lookup methods have returned an uncached (newly loaded) value, or null
# TYPE cache_gets_total counter
cache_gets_total{cache="metadataDefinitionCache",result="miss",} -156909.0
cache_gets_total{cache="metadataDefinitionCache",result="hit",} 314086.0
```
Any ideas why?

Thanks

Nick

**Comment by nickcodefresh** [comment]
So it appears as though these metrics are coming from Spring Boot Actuator class `org.springframework.boot.actuate.cache.DefaultCacheStatistics`. 

When I looked in to it I can't get the hit/miss ratio from `io.micrometer.core.instrument.binder.cache.HazelcastCacheMetrics#nearCacheMetrics` because `cache.getLocalMapStats().getNearCacheStats()` is always null. Any idea how to set that field so it can report statistics?

**Comment by nickcodefresh** [comment]
Digging in to this it appears as though these metrics are coming from Spring Boot Actuator
```
org.springframework.boot.actuate.cache.DefaultCacheStatistics
```
How come HazelcastCacheMetrics doesn't export hits/misses (apart from the near cache)?

**Comment by nickcodefresh** [comment]
Ok so this is a weird one. I've discovered that the `cache_gets_total` metrics are coming from `io.micrometer.core.instrument.binder.cache.CacheMeterBinder#bindTo` (micrometer-code 1.0.3). When we graph this metrics from 2 instances of our service we see the misses as:

![screen shot 2018-05-08 at 15 49 59](https://user-images.githubusercontent.com/5837418/39764434-8348755a-52d7-11e8-9dd0-14fde6116cb3.png)

If I change this to hits we see 

![screen shot 2018-05-08 at 15 52 39](https://user-images.githubusercontent.com/5837418/39764595-db8e3b5a-52d7-11e8-9f07-d41f7e049ec7.png)

So we can see that the node2 instance is getting all the hits, but it doesn't explain why the node2 miss count is negative.

**Comment by jkschneider** [comment]
So I suppose this arithmetic in HazelcastCacheMetrics is incorrect:

![image](https://user-images.githubusercontent.com/1697736/39765184-d28704fa-52a6-11e8-9050-52979e6e34f1.png)

**Comment by mweirauch** [comment]
Just as a hint, when somebody touches the file, the class Javadoc mentions "EhCache". Likely a C&P leftover.

**Comment by jkschneider** [comment]
@nickcodefresh Without your screenshots, this would have been very hard to track down. In the end, I concluded that it is impossible to calculate miss count against Hazelcast caches :(

I've removed the metric from the Hazelcast implementation, and added another FunctionCounter, `cache.partition.gets`.
