### ISSUE TITLE
Dropwizard Metrics 4.x

### ISSUE THREAD

**Issue by slovdahl** [micrometer-metrics/micrometer#587]
Are there any plans for updating the Dropwizard Metrics dependency to 4.x in the near future?

We're currently using Metrics (version 4.x) for exposing metrics over JMX. While I was evaluating gradually migrating from Dropwizard Metrics to Micrometer, I noticed that Micrometer depends on Dropwizard Metrics 3.2.x. With regard to JMX reporting, version 3.2 is incompatible with 4.x. JMX support has been moved to a separate artifact, `metrics-jmx`, and the `com.codahale.metrics.JmxReporter` class has been moved to `com.codahale.metrics.jmx.JmxReporter`, which is the main cause of incompatibility here.

**Comment by jkschneider** [comment]
@slovdahl In fact, we were considering eliminating the Dropwizard dependency specifically for JMX. We've heard some feedback that folks want a really lightweight dependency graph for the JMX case.

Is there a difference in the way metrics are exposed in JMX in 4.x vs. 3.x that you like? Or is it strictly a dependency conflict that would be solved for you by us _not_ using DW as a passthrough?

**Comment by jkschneider** [comment]
Outside of JMX, I think it is reasonable for us to upgrade to 4.x in the Micrometer 1.1 line.

**Comment by slovdahl** [comment]
And FWIW, in the meantime it's trivial to have a copy of `JmxMeterRegistry` in my own code that uses Dropwizard Metrics 4.x instead.

**Comment by jkschneider** [comment]
See also https://github.com/spring-projects/spring-boot/issues/14183
