### ISSUE TITLE
Failed to send metrics: Payload is not in the expected format

### ISSUE THREAD

**Issue by KJoyner** [micrometer-metrics/micrometer#589]
> DatadogMeterRegistry         : failed to send metrics: Payload is not in the expected format: invalid character '{' after array element

After my services are running for awhile, I start to see this message in the logs. Once it appears, it doesn't seem to go away and metrics are no longer being received in Datadog.

I am using Spring Boot 1.5.10 and the Micrometers 1.0.3 release. I have this running on a few of our microservices and the error only seems to be happening on one of them. It is strange because a few instances of the microservice never had the error but others once it started never stopped. These were all running the same version of the same microservice.

**Comment by jkschneider** [comment]
Thanks @KJoyner. I'll take a look before the 1.0.4 release that's coming up shortly. Sounds like we just need to add some more characters to Datadog's naming convention blacklist.

**Comment by jkschneider** [comment]
Having trouble reproducing the exact scenario, but I'm pretty sure it has something to do with us not properly escaping `"` and `\` in the naming convention. Probably one or more of these occur in one of your tag values, which would be somewhat unusual, and why we probably haven't heard about this yet.
