### ISSUE TITLE
Migrate to CircleCI 2.0

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#592]
[CircleCI 1.0 is scheduled to be EOL](https://circleci.com/sunset1-0/) in August. If we are going to continue using CircleCI as our CI tool, we should migrate to 2.0. I don't have experience with CircleCI, but they have a [migration guide](https://circleci.com/docs/2.0/migrating-from-1-2/). If someone else has experience and expertise with CircleCI 2.0, feel free to take up this issue. If no one speaks up, I will give a try doing it eventually, since I wanted to add a JDK 10 and possibly 11 EA build to our setup, but I don't want to bother trying to do this in the 1.0 config if we are going to migrate soon.

**Comment by izeye** [comment]
This looks resolved via #663 and [the latest builds with CircleCI 2.0 look okay](https://circleci.com/gh/micrometer-metrics/micrometer).
