### ISSUE TITLE
Allow Graphite tags to be presented in the hierarchical name in the order in which they were defined

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#595]
See #561 for more context.

> Tested your change and this helped - thanks. It takes care of the tagsAsPrefix explicit ordering with common tags. There is one part that remains - the tags that are specified when registering a metric also sort the order. We need explicit control there. I believe that would affect Metric.Id constructor - I didn't see a graphite abstraction available for that inner class. I don't see an easy way for me to work around this other than by manipulating tag names to sort in the order I want.

> Understandable @jspofford. Sorting tags on Meter.Id is important for performant equality comparisons, but we may be able to preserve the original ordering for Graphite.

**Comment by shakuzen** [comment]
I looked into this and I'm not seeing a sensible way to achieve this for Graphite without affecting all repositories right now. I'm thinking something like #620 may be a better general approach to the problem-space.

**Comment by jspofford** [comment]
I ended up implementing my own HierarchicalNameMapper to provide a consistent prefix order and to pull out certain meter tags and put them into a specific order.  The remaining tags get sorted.

But this is definitely less than ideal.  Sorting the graphite hierarchy makes a mess of the hierarchy and the hierarchy is inconsistent across Meters.  What would be better is if during Meter creation, if the tag list order was preserved.  Instead the tags are put into a map and all order is lost.  You are stuck trying to make up for it with your own name mapper with hard coded, non-reusable rules that may or may not apply to every Meter.  Instead, if the order was preserved in the Meter, the hierarchy name mapper could use that order.  With that, my need for a custom hierarchical name mapper goes away.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2019. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it. Also according to @shakuzen [this](https://github.com/micrometer-metrics/micrometer/issues/620) might be a better general approach
