### ISSUE TITLE
micrometer-registry-prometheus v1.0.4 dependency on simpleclient_common is 0.2.0

### ISSUE THREAD

**Issue by pjfanning** [micrometer-metrics/micrometer#601]
https://mvnrepository.com/artifact/io.micrometer/micrometer-registry-prometheus/1.0.4

The build.gradle has a lock on simpleclient_common 0.3.0 so the 2 versions are not consistent.
https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-prometheus/build.gradle

**Comment by jkschneider** [comment]
Thanks @pjfanning.

**Comment by jkschneider** [comment]
Definitely not intended. Did this cause a breakage?

**Comment by pjfanning** [comment]
@jkschneider not causing me any issues - just wanted to bring it to your attention

**Comment by raoofm** [comment]
@jkschneider 0.4.0 was released a month ago. Can be used?

**Comment by jkschneider** [comment]
@raoofm It's so hard for me to reason about these Prometheus dependencies given their pre-1.0 nature. I'll check out 0.4.0 for breaking changes (I don't expect any) and include it in Micrometer 1.0.5 this week if possible.

**Comment by jkschneider** [comment]
Upgraded to Prometheus 0.4.0 for the upcoming Micrometer 1.0.5 release.
