### ISSUE TITLE
TimedAspect support of LongTaskTimer

### ISSUE THREAD

**Issue by weistom** [micrometer-metrics/micrometer#604]
As of now [TimedAspect](https://github.com/micrometer-metrics/micrometer/blob/0061a4aeba8c59ba018307cfa03435739c973827/micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java) doesn't care about longTask value set to [@Timed](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/annotation/Timed.java).
Do you have any plan to switch to long task timers in case longTask value is set to true ? 

```
    @Around("execution (@io.micrometer.core.annotation.Timed * *.*(..))")
    public Object timedMethod(ProceedingJoinPoint pjp) throws Throwable {
        Method method = ((MethodSignature) pjp.getSignature()).getMethod();
        Timed timed = method.getAnnotation(Timed.class);
        final String metricName = timed.value().isEmpty() ? DEFAULT_METRIC_NAME : timed.value();

        Timer.Sample sample = Timer.start(registry);
        try {
            return pjp.proceed();
        } finally {
            sample.stop(Timer.builder(metricName)
                    .description(timed.description().isEmpty() ? null : timed.description())
                    .tags(timed.extraTags())
                    .tags(tagsBasedOnJoinpoint.apply(pjp))
                    .publishPercentileHistogram(timed.histogram())
                    .publishPercentiles(timed.percentiles().length == 0 ? null : timed.percentiles())
                    .register(registry));
        }
    }
```

**Comment by jkschneider** [comment]
If it isn't done in #604, we should revise that PR.

**Comment by weis-tom** [comment]
That is very helpful for me if you revise it.
Can you fix it ?

**Comment by nejckorasa** [comment]
Possible solution in #1407? It starts `LongTaskTimer` in case `longTask` is set.

**Comment by weistom** [comment]
Yes ! I checked #1407.
Thank you for revising.
