### ISSUE TITLE
Add a `LoggingMeterRegistry` that summarizes metrics to a logger

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#605]
For those cases where we get questions about what metrics are being exported (especially when they don't appear to be showing up in a typical monitoring system).

**Comment by jkschneider** [comment]
See https://stackoverflow.com/questions/50193287/exporting-metrics-to-files-when-using-spring-boot-2-0

**Comment by mweirauch** [comment]
Some random thoughts:
* a log entry per metric or a all in one? (the latter might overwhelm producer and consumer)
* structured (json?) vs plain text? (think structured log analysis and the presentation of more complex metrics like timers/distributionsummaries)

**Comment by jkschneider** [comment]
All good questions :)

- Unless there is a reason not to, I think a log per metric makes sense?
- I can imagine that declarative dimensional pre-aggregation that is needed for CloudWatch and JMX is equally useful here along with a whitelist to pare the list down to just a set of things you care about.
- No idea on format. JSON isn't great for readability, but I suppose benefits structured log analysis?

**Comment by mweirauch** [comment]
> No idea on format. JSON isn't great for readability, but I suppose benefits structured log analysis? Suggests a configurable format?

Was just an example. In the golang world most structured loggers seem to go for the `key1=value key2=value key3="some whitespace text"` style which I tend to find quite readable.

**Comment by checketts** [comment]
I think a summarized option would be most useful. It could output:

```
Total Metrics being recorded: 123
``` 

or perhaps:

```
Counters: 50 Timers: 60 LongTaskTimers: 13 Total metrics: 123
```

**Comment by joeo73** [comment]
For reference.  Here is a dropwizard metric logged output.  It's quite readible 

``
2018-07-06 17:00:28,884 [metrics-logger-reporter-thread-1] [INFO] (com.codahale.metrics.Slf4jReporter) type=METER, name=io.dropwizard.jetty.MutableServletContextHandler.async-timeouts, count=0, mean_rate=0.0, m1=0.0, m5=0.0, m15=0.0, rate_unit=events/second
2018-07-06 17:00:28,884 [metrics-logger-reporter-thread-1] [INFO] (com.codahale.metrics.Slf4jReporter) type=TIMER, name=com.impinj.itemsense.agent.TaskRepositoryDao.rawGetNextTaskForReader, count=209, min=145.511, max=7976.1320000000005, mean=858.4775167464114, stddev=1347.4190261974575, median=394.425, p75=594.4985, p95=4190.705, p98=7013.792999999979, p99=7880.0349000000015, 
``

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/47597809-6df62f00-d958-11e8-9012-3899f4ca0bea.png)

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/47597832-ba416f00-d958-11e8-95bd-302aa6c1c931.png)

**Comment by JamazRuan** [comment]
hi @jkschneider , when I use LoggingMetricsExportAutoConfiguration, webMvcMetricsFilter would throw an exception, the detail is
https://github.com/micrometer-metrics/micrometer/issues/1431
