### ISSUE TITLE
Make LatencyUtils and HdrHistogram shaded just like pcollections

### ISSUE THREAD

**Issue by quaff** [micrometer-metrics/micrometer#614]
I wish my project only depends on micrometer-*.jar and some popular lib like slf4j.

**Comment by checketts** [comment]
Isn't the benefit of shading to avoid dependency clashes between versions? Do you have a need to use other versions of Latency Utils or HDR Histogram?

The goal shouldn't be to reduce the number of jars or dependency tree.

**Comment by quaff** [comment]
Both of them are not common used lib, many projects manage dependence manually, like to keep dependence simple and clear, I think is reasonable since pcollections get shaded.

**Comment by jkschneider** [comment]
Shading pcollections was done only because it was introduced in a patch release. It will be unshaded in 1.1.0. I agree with @checketts, shading should be kept to a minimum for known version incompatibility issues.
