### ISSUE TITLE
[Cloudwatch] problems registering custom metrics

### ISSUE THREAD

**Issue by Dreando** [micrometer-metrics/micrometer#618]
I'm having issues registering custom metrics to MeterRegistery.

What it looks like is that Spring manages register all its metrics (70 something) and then when the control comes back to me, I'm trying to register my own too:

```
public MetricsAwareActiveTasksRepository(ActiveTasksRepository activeTasksRepository, MeterRegistry meterRegistry) {
    this.activeTasksRepository = activeTasksRepository;

    this.createdTaskIdsCounter = meterRegistry.counter(CustomBusinessMetrics.CREATED_TASK_IDS_COUNTER);
    this.autoStoppedTasksCounter = meterRegistry.counter(CustomBusinessMetrics.AUTO_STOPPED_TASKS_COUNTER);
}
```
Unfortunately at the point where my first metric is being registered, process hangs here in micrometer:
```
    private Meter getOrCreateMeter(@Nullable DistributionStatisticConfig config,
                               BiFunction<Id, /*Nullable Generic*/ DistributionStatisticConfig, Meter> builder,
                               Id originalId, Id mappedId, Function<Meter.Id, ? extends Meter> noopBuilder) {
    Meter m = meterMap.get(mappedId);

    if (m == null) {
        if (isClosed()) {
            return noopBuilder.apply(mappedId);
        }

        synchronized (meterMapLock) {
            m = meterMap.get(mappedId);

            if (m == null) {
                if (!accept(originalId)) {
                    //noinspection unchecked
                    return noopBuilder.apply(mappedId);
                }

                if (config != null) {
                    for (MeterFilter filter : filters) {
                        DistributionStatisticConfig filteredConfig = filter.configure(mappedId, config);
                        if (filteredConfig != null) {
                            config = filteredConfig;
                        }
                    }
                }

                m = builder.apply(mappedId, config);
                meterMap = meterMap.plus(mappedId, m);
                for (Consumer<Meter> onAdd : meterAddedListeners) {
                    onAdd.accept(m);
                }
            }
        }
    }

    return m;
}
```
The last line that can be tracked from debugger is where synchronized block starts. From debugger I see that the main thread becomes ZOMBIE, and nothing more happens. Lock is not being released.

Did anyone have this kind of problems? Am I doing something wrong here?

BTW Here's config also:

```
@Bean
CloudWatchMeterRegistry cloudWatchMeterRegistry(CloudWatchConfigProperties config, AmazonCloudWatchAsync amazonCloudWatch) {
    CloudWatchMeterRegistry meterRegistry = new CloudWatchMeterRegistry(config, Clock.SYSTEM, amazonCloudWatch);
    meterRegistry.config().commonTags(commonTags());
    return meterRegistry;
}
```

I tried to deliver custom metrics to configuration before meterRegistry is being returned, so that my metrics would be registered first and then control returned to Spring, however this does not solve the issue, and also I don't thing it would be a good way to go.

We did some examples with configuration, like initial delay, enabling, disabling. It turns out that it only hangs if pushing to cloudwatch is enabled.

Also after enabling DEBUG logger, the micrometer library says nothing, the last logs before actually hanging forever are the logs from spring bean lifecycle methods, like autowiring this particular constructor that registers new metrics.

Versions are: spring-boot: 2.0.2, micrometer 1.0.4

Thanks in advance for any ideas.

**Comment by jkschneider** [comment]
@Dreando Makes me wonder if there is a sync problem somewhere in `AmazonCloudWatchAsync`.

**Comment by Dreando** [comment]
@PyvesB, @jkschneider I have indeed recently had an opportunity to check if again on newest versions, and it seems that problem disappeared :) Thanks.

**Comment by izeye** [comment]
Based on the @PyvesB 's comment and the original reporter, @Dreando 's the latest comment, this looks no longer to be an issue. Closing.
