### ISSUE TITLE
If using custom HierarchicalNameMapper, GraphiteConfig.tagsAsPrefix is not honored

### ISSUE THREAD

**Issue by asarkar** [micrometer-metrics/micrometer#637]
I found that if using custom `HierarchicalNameMapper`, `GraphiteConfig.tagsAsPrefix` is not honored because it's the mapper that creates and prepends the prefix. This should be documented, because we can't expect the user to look into source code to discover this behavior.

**Comment by jkschneider** [comment]
Closing here and created an issue in `micrometer-docs`
