### ISSUE TITLE
GraphiteMetricsExportAutoConfiguration is lacking

### ISSUE THREAD

**Issue by asarkar** [micrometer-metrics/micrometer#638]
`GraphiteMetricsExportAutoConfiguration` could call `GraphiteMeterRegistry(GraphiteConfig config, Clock clock, HierarchicalNameMapper nameMapper, MetricRegistry metricRegistry, GraphiteReporter reporter)` after looking up the beans in the context, in case user had provided alternate ones. Currently, because there is no way to inject my own `HierarchicalNameMapper`, I'm forced to create my own auto-config, which shouldn't be necessary.

**Comment by jkschneider** [comment]
I think we had it written this way at one point and then concluded that when you have multiple hierarchical monitoring systems that expect different name mappings that the injection was harmful. Seems now that it would have been fine since the escape hatch is to just define your own `XXXMeterRegistry` beans for each hierarchical backend that doesn't share the injectable `HierarchicalNameMapper`.

**Comment by jkschneider** [comment]
I'm marking this as a 1.1.0 task rather than 1.0.5, because there is a workaround and it would represent an API change in Spring Boot. Unless there's a compelling reason, it is preferable that `micrometer-spring-legacy` doesn't diverge from `spring-boot-actuator`.

**Comment by asarkar** [comment]
@jkschneider It seems this change isn't present in the spring-boot-actuator-autoconfigure-2.1.1.RELEASE.

**Comment by izeye** [comment]
@asarkar Thanks! I created https://github.com/spring-projects/spring-boot/pull/15464.

**Comment by izeye** [comment]
@asarkar Thanks for the suggestion! I agree it’s easy to be out of sync with Spring Boot 2.x but it’s not easy to be automated with the current situation as the codes for both are not identical and changes are happening in both ways. At least we need some process to track changes in both repos to be in sync.

**Comment by asarkar** [comment]
How about this, every time a PR is created in this repo, the description must contain a link to a PR in the Boot repo?

**Comment by izeye** [comment]
> changes are happening in both ways

@asarkar It seems the part of my comment wasn't clear. "both way" means that changes are happening in both the Micrometer repo and the Spring Boot repo, so syncing changes could be heading to both repos. Even if changes were happening in one way, someone still should keep track of them manually.

I'm not sure but the "boot2-change" label might exist for this purpose.

This discussion seems to be useful but it's off-topic, so it'd be better to create another issue for it if you want to discuss this more.

**Comment by izeye** [comment]
@asarkar FYI https://github.com/spring-projects/spring-boot/pull/15464 has been declined. For details, see the discussion in the PR.
