### ISSUE TITLE
Any plans for Spring Cloud messaging support?

### ISSUE THREAD

**Issue by Eloo** [micrometer-metrics/micrometer#64]
Hi there,

i would like to monitor my messaging channels as well as my http endpoints.
Currently we bridge the springboot actuator metrics to your prometheus metrics which works but isn't really the solution we want.
So are there plans to add support for spring cloud metrics like channel count or else?

Thanks for your work so far, really great library!

**Comment by jkschneider** [comment]
Thanks, this is a gap. Will add an equivalent `MeterBinder` for this in micrometer-spring-legacy.

**Comment by Eloo** [comment]
nice.. looking forward to the next release ;)
