### ISSUE TITLE
Sanitise tag values on export

### ISSUE THREAD

**Issue by nhmarujo** [micrometer-metrics/micrometer#644]
I'm using **Spring Boot 2.0.1** and exporting my metrics to telegraf using **micrometer-registry-statsd**.

The pool name that I had configured for Hikari was a bit odd, being something like **poolname=abc::hikari** (some kind of weird hack to make it work as a tag on older metrics, that were exported by scollector).

Having special characters inside the tag value (like "=" or ":") makes the telegraf parser raise some errors. Looking at telegraf logs I was able to see errors like, for instance:
> E! Error: splitting '|', Unable to parse metric: hikaricp_connections_acquire,pool=poolName=abc::hikari:0.468846|ms

Removing the special characters solved the issue, however, I think it should be enforced that the tag values (and perhaps keys?) are sanitised before exported to telegraf (or whatever the flavor you are using).

**Comment by jkschneider** [comment]
Documentation on special characters is here: https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_reference/#special-characters
