### ISSUE TITLE
InfluxNamingConvention formats tag values incorrectly

### ISSUE THREAD

**Issue by iabudiab** [micrometer-metrics/micrometer#645]
The tag values are treated the same way as keys in `InfluxNamingConvention` which results in values like `org.example.service` to be converted to `org_example_service`

Take a look at: [InfluxNamingConvention.java#L63](https://github.com/micrometer-metrics/micrometer/blob/d0f4a2f194951389b6e96b3775a9e0accefc05cb/implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxNamingConvention.java#L63)

**Comment by jkschneider** [comment]
Good catch. Thanks @iabudiab. We'll fix this for the upcoming 1.0.5 release.

**Comment by quaff** [comment]
This change breaks name formatting, "test.call" remains "test.call" instead of "test_call", I prefer this, Please make sure it keeps "test.call" in future versions.

**Comment by jkschneider** [comment]
@quaff The intended behavior is to leave tag values unchanged. If you'd like to apply naming conventions to tag values as well, you may override the naming convention by extending `InfluxNamingConvention` and applying it to your registry with:

```
registry.config().namingConvention(new MyCustomInfluxNamingConvention())
```

**Comment by bckfnn** [comment]
@jkschneider I think quaff says that it changes the metrics **names** so they are no longer snakecased at all, so the example from section "5. Naming meters" in the manual
```
registry.timer("http.server.requests");
```
now in 1.0.5 is written as "http.server.requests" to influx and not "http_server_requests" as it was in 1.0.4.

I doubt this is intentionally; if it is, the manual should be updated to reflect the new behaviour.
