### ISSUE TITLE
Support management.metrics.tags.*

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#646]
This support was added in Spring Boot 2.0.2 but wasn't backported to Micrometer 1.0.4?

**Comment by izeye** [comment]
See https://github.com/spring-projects/spring-boot/issues/12933

/cc @snicoll

**Comment by shakuzen** [comment]
@jkschneider just wanted to note that was added to Spring Boot 2.1 (milestone 2.1.0.M1)

**Comment by manivkm** [comment]
Is this feature added in Spring Boot 2.1?

**Comment by jkschneider** [comment]
@manivkm Yes, which is in snapshots until the first milestone on July 19.

**Comment by manivkm** [comment]
Is it possible, somehow to consume the fixed version? For example, 2.0.3.SNAPSHOT or 2.0.3.RELEASE

**Comment by snicoll** [comment]
I am afraid not, that question was already asked on the linked issue, see there for more details.

**Comment by jkschneider** [comment]
@ghost You should be able to consume the fixed version with 2.1.0.SNAPSHOT, unless I misunderstand the question.

**Comment by amitarora15** [comment]
What is way to define these common tag in YML file?

**Comment by shakuzen** [comment]
@amitarora15 the feature was added in Spring Boot 2.1, so you will first need to upgrade to that to use it. As for the format, the second looks right to me. See also the Spring Boot documentation: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-common-tags

**Comment by amitarora15** [comment]
Thanks @shakuzen. Spring Boot 2.0 supports it through MeterRegistryCustomizer. And as you pointed out Boot 2.1 supports it through application configuration by yml.

**Comment by shakuzen** [comment]
I'm not sure what yaml changes you mean - the documentation for 2.0 won't mention changes made in a future release. I think it is going to be easier to get to the bottom of this via chatting on the Micrometer Slack or the Spring Boot Gitter channel.

**Comment by amitarora15** [comment]
@shakuzen No problem. I understand what you were saying is that supporting of common tags through yaml or properties is present in 2.1 version and mentioned in the documentation. 

Spring Boot 2.0 supports it through MeterRegisteryCustomizer
