### ISSUE TITLE
Zabbix support

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#65]
https://www.zabbix.com/

Is this something we want?

**Comment by hadjiski** [comment]
for sure, I would be happy to have this :+1:

**Comment by stepio** [comment]
Hello guys, is this feature still on track?

**Comment by jkschneider** [comment]
Yes, still targeted for inclusion in 1.1.0. Of course, we'd love a PR ;)

**Comment by mschirmacher** [comment]
looks like it didn't make it into 1.1.0. did it? Is there any update on this one?

**Comment by kedaly** [comment]
If you can point me to the correct place I'd be more than happy to build the Zabbix integration

**Comment by kedaly** [comment]
@jkschneider Looks like you're the guy to talk to about that.

**Comment by shakuzen** [comment]
Hi @kedaly thank you for your interest in contributing the Zabbix integration. You can reference the other backend implementations for examples: https://github.com/micrometer-metrics/micrometer/tree/master/implementations
I took a quick look around the Zabbix website but I wasn't sure how applications would send metrics to Zabbix via Micrometer. If possible, Micrometer can send metrics to a Zabbix server. Alternatively, the Zabbix agent could perhaps convert Micrometer metrics to its own representation.
Feel free to [reach out to us on Slack](http://slack.micrometer.io/) to chat more.

**Comment by querplis** [comment]
@jkschneider , @shakuzen zabbix way of doing this is called zabbix sender:
https://www.zabbix.com/documentation/4.2/manual/concepts/sender
This was first hit on google "zabbix sender java" https://github.com/hengyunabc/zabbix-sender
but  there might be other/better implementations.

**Comment by querplis** [comment]
@jkschneider , @shakuzen  that is if we want to push data into zabbix

**Comment by scoopex** [comment]
> @jkschneider , @shakuzen zabbix way of doing this is called zabbix sender:
> https://www.zabbix.com/documentation/4.2/manual/concepts/sender
> This was first hit on google "zabbix sender java" https://github.com/hengyunabc/zabbix-sender
> but there might be other/better implementations.

Yes, it would be better not to rely on "zabbix_sender" or its configurations files, because:

- invoking commands from a java runtime is often considered to be a "dirty hack" from software engineering perspective 
- invoking commands from a java runtime often creates complications in debugging, portability,  transparency and configuration
- zabbix_sender is often deployed as a separate package
- zabbix_sender is typically not part of docker containers

I think it's a good idea to use a implementation of the relatively simple [zabbix trapper (zabbix_sender) protocol.](https://www.zabbix.com/documentation/4.4/manual/appendix/items/trapper).

It would be a good idea to use a [library](https://github.com/hengyunabc/zabbix-sender) which already implements the zabbix sender protocol, because this might help to inherit current and future implementations like [agent protocol encryption](https://www.zabbix.com/documentation/4.4/manual/encryption).

**Comment by yurtesen** [comment]
Will the pull request be merged or is there anything blocking it?

**Comment by scoopex** [comment]
It would be really nice to see this merged!

**Comment by jbx1** [comment]
Any chance of getting this in?

**Comment by workless** [comment]
I'm also waiting for this PR, how can i help?

**Comment by scoopex** [comment]
We use the implementation in https://github.com/micrometer-metrics/micrometer/pull/1773 for several months here.
Is there any reason not not merge it?

**Comment by garretwilson** [comment]
I just learned about Micrometer via Spring while researching metrics and alarms for a large company I am working with. They are using Zabbix extensively. I saw Micrometer and thought, wow, maybe this could improve their metrics publishing. I thought surely Zabbix would be something supported, but I was disappointed. It's encouraging that someone already created this ticket, though, so I don't have to. Any idea when it will go forward? Thanks.

**Comment by EmhyrVarEmreis** [comment]
Implementation in https://github.com/micrometer-metrics/micrometer/pull/1773 is working properly. Why it is taking so long to merge this?

**Comment by shakuzen** [comment]
While we recognize there is a sizable amount of interest from the community in Zabbix support, the Micrometer team has significant concerns about maintaining Zabbix support. We lack expertise in Zabbix and we have concerns about the difference in the model for publishing metrics compared to other metrics backends. In the proposed implementation so far, there is a significant amount of code to maintain and a dependency on projects that have not been updated in a long time (e.g. [hengyunabc/zabbix-sender](https://github.com/hengyunabc/zabbix-sender)). For these reasons we are not willing to take on the maintenance of supporting a Zabbix integration at this time.

If someone is willing to take on the maintenance, we would suggest publishing an implementation (such as #1773) as a standalone third-party project maintained by the community. Those with Zabbix expertise can better maintain it and provide support for it that way.
I apologize for the long delay on taking action on this and don't want to leave it in limbo longer. If someone does make a third-party Micrometer integration for Zabbix, feel free to link it here so those interested can find it from here.
Closing as we do not plan on adding Zabbix support here for now.

**Comment by scoopex** [comment]
The reason for the low activity of https://github.com/hengyunabc/zabbix-sender is, that the zabbix procol is very simplea nd the implementation works with out problems for years. U haven't experienced any problems with that dependency for years.

**Comment by mabrarov** [comment]
FYI, I successfully tried in the past [jitlogic/zorka](https://github.com/jitlogic/zorka), but it's more targeted to instrumentation, tracing and profiling (though these features can be turned off keeping just monitoring). I'm not sure if it can replace Micrometer (which seems to be much more popular) Zabbix integration.

**Comment by kotoant** [comment]
I’ve just published the solution based on code from @matzepan: https://central.sonatype.com/artifact/io.github.kotoant.micrometer/micrometer-registry-zabbix
