### ISSUE TITLE
Shade pcollections into `micrometer-registry-statsd`

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#655]
Workaround for 1.0.5:

```
compile("io.micrometer:micrometer-registry-statsd:1.0.5")
compile("org.pcollections:pcollections:3.0.1")
```

**Comment by ctoestreich** [comment]
Make sure to coordinate with platform.io as currently this is breaking Cairo-SR2 and Boot 2.0.3.RELEASE 

https://github.com/spring-projects/spring-boot/blob/4a883d00a5a6842e53086207c259fd053be1ce43/spring-boot-project/spring-boot-dependencies/pom.xml#L125

I have logged an issue here https://github.com/spring-projects/spring-boot/issues/13528
