### ISSUE TITLE
Add support for gRPC monitoring

### ISSUE THREAD

**Issue by jacobk** [micrometer-metrics/micrometer#656]
It would be great with auto configured monitoring for:
* gRPC client requests using generated Java code
* gRPC server handlers based on e.g. https://github.com/LogNet/grpc-spring-boot-starter

**Comment by ST-DDT** [comment]
There is also an interceptor based implementation available in https://github.com/yidongnan/grpc-spring-boot-starter:

* [shared](https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/metric)
* [client](https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metric)
* [server](https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric)

Feel free to move this upstream. I can create a PR with the required classes, just tell me where to add them to.

**Comment by racevedoo** [comment]
Any work here guys? @ST-DDT did you start doing something? I was thinking of creating a PR

**Comment by ST-DDT** [comment]
No, IMO configuring support for monitoring netty's ELGs is way more complicated then I originally anticipated, so I dropped it for now. (Especially how to restore the grpc's default settings while still retaining maintainability and configurability).
One of the biggest issues there (if you dive for netty metrics), is that grpc shades netty.

Feel free to reuse the metric collection code linked above. Just ping me if you create the PR.

**Comment by racevedoo** [comment]
@ST-DDT I guess we could start with the basic metrics and then improve to include netty metrics later. The reason for this is that, for some use cases, basic metrics are good enough.

WDYT?

**Comment by ST-DDT** [comment]
Finally I had time to create a PR to add the metric collection code grpc to this library. See #2323
