### ISSUE TITLE
Add AWS CloudWatch metrics support

### ISSUE THREAD

**Issue by mrcasablr** [micrometer-metrics/micrometer#66]
AWS CloudWatch can take custom metrics and is supported by their Java SDK - http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-cloudwatch-publish-custom-metrics.html

**Comment by jkschneider** [comment]
https://github.com/spring-cloud/spring-cloud-aws/blob/2.0.x/spring-cloud-aws-actuator/src/main/java/org/springframework/cloud/aws/actuate/metrics/CloudWatchMetricWriter.java

**Comment by dkublik** [comment]
Created PR: https://github.com/micrometer-metrics/micrometer/pull/250

**Comment by jkschneider** [comment]
Added Boot binding in 3af71a2d2ba033baa8147e98d6ae400d4724d141.
