### ISSUE TITLE
HdrHistogram: upstream DoubleHistogram.reset() issue

### ISSUE THREAD

**Issue by mweirauch** [micrometer-metrics/micrometer#672]
There's been an upstream fix regarding the `reset()`. I can't judge the impact of this on the core components of micrometer. I can see it being used...
@jkschneider perhaps you can give a small roundup of what effects it has, if at all.

https://github.com/HdrHistogram/HdrHistogram/issues/143

We should track upstream releases.

**Comment by jkschneider** [comment]
We maintain our own max (and later min) that isn't subject to the same limitations. So this feature of HdrHistogram isn't used in Micrometer.
