### ISSUE TITLE
Make prometheus actuator endpoint (scrape) configurable

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#68]
See the [SO question](https://stackoverflow.com/questions/45418398/change-prometheus-endpoint-using-micrometer-io).

**Comment by mweirauch** [comment]
Perhaps I am missing something, but what about ...
```
endpoints:
  prometheus:
    id: micrometheus
```
Works for me on Spring Boot 1.5.6.RELEASE.
As we are at it, is it feasible to integrate the `spring-boot-configuration-processor` so that any `@ConfigurationProperties` are autocompletable in `application.yml` where there is IDE support?

**Comment by checketts** [comment]
@mweirauch Thanks for validating! I had hoped that would work, but hadn't gotten around to validating.

I don't see a reason not to add the autocomplete processor support, but I don't have much experience with that aspect.

**Comment by jkschneider** [comment]
Updated docs on configuring the scrape endpoint with an application property.
