### ISSUE TITLE
Anonymous Exception leads to empty exception tag

### ISSUE THREAD

**Issue by hgnoyke** [micrometer-metrics/micrometer#680]
In case an anoynymous exception is thrown and reported in "http.server.requests" the resulting exception tag will be empty and the metric can not be sent to InfluxDB (in our case; not sure whether this holds true for other metric DBs).

Following the error message (abbreviated for convenience):
failed to send metrics: {"error":"partial write: unable to parse 'http_server_requests_percentile,exception=,status=400,uri=/api/,[...]'

I can not tell whether this should be fixed in micrometer or in spring boot acutator or both. Exception tag is created in https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/servlet/WebMvcTags.java
It would be great if micrometer would either ignore empty tags before sending or provide sensible default values (if possible).
If that is clarified I will be happy to help with a pull request.

Thanks for looking into this!

**Comment by jkschneider** [comment]
Interesting, thanks!
