### ISSUE TITLE
Add counter for Hystrix circuit breaker

### ISSUE THREAD

**Issue by benhubert** [micrometer-metrics/micrometer#683]
Additionally to the existing `Gauge` metric returning the current state of Hystrix circuit breakers it would be great to have this information also as `Counter`.

Since Prometheus scrapes this information just periodically (e.g. all 15 seconds), with only a Gauge value we might miss some incidents, where the circuit breaker is open for just some seconds. With an additional Counter we could monitor if some circuit breaker events occured.

Regarding to hystrix documentation, this count should already be there as `countShortCircuited`:
https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring#cumulative-and-rolling-event-counts

So I think it should be easy to integrate it in Micrometer+Prometheus.

**Comment by jkschneider** [comment]
Is this already captured by the `hystrix.errors` counter?

**Comment by benhubert** [comment]
No. I don't think so. `hystrix.errors` is incremented within a `HystrixCommandCompletion` when a command failed. As far as I understand, it's incremented only if a command failed with `FAILURE`, `TIMEOUT`, `THREAD_POOL_REJECTED` or `SEMAPHORE_REJECTED`. But it does not count the times that a circuit has been opened, right?

Furthermore it does not contain a tag for the error type, so I'm not able to differentiate between different error types:
```
hystrix_errors_total{exported_group="Foo",key="Foo"}
```

**Comment by benhubert** [comment]
Ok. You're right. `hystrix.errors{event="short_circuited"}` already shows this value because it's not the value I expected. Both
 * Micrometer `hystrix.errors{event="short_circuited"}` and
 * Hystrix `metrics.getCumulativeCount(HystrixEventType.SHORT_CIRCUITED)`
count the _number of command executions_ that fail caused by a open circuit breaker.

But what I want is the count, how often the circuit breaker changed its state from _closed_ to _open_. I'm not sure at the moment, if there's a way to retrieve this information from Hystrix.

If someone has a hint for me, that would be great.

**Comment by benhubert** [comment]
Ok. I close this ticket. Even if we expected other numbers, all the existing metrics already enable us to monitor hystrix as we want. E.g. we can put alerts on `hystrix_execution_total{event="short_circuited"}` to find out if a hystrix circuit breaker opened.
