### ISSUE TITLE
Plan for Spring Boot 1.5 EOL

### ISSUE THREAD

**Issue by izeye** [micrometer-metrics/micrometer#684]
I'd like to know whether Micrometer support for Spring Boot 1.5 will be EOLed at the same time or live longer regardless when Spring Boot 1.5 EOLed.

See https://github.com/spring-projects/spring-boot/issues/13575

**Comment by jkschneider** [comment]
Several possibilities:

1. We carry on in spite of the Spring Boot EOL for some time later.
2. We continue publishing `micrometer-spring-legacy`, ensuring it at least isn't broken by `micrometer-core`, but not backporting any more features from Boot 2.
3. We move `micrometer-spring-legacy` to a separate repo and allow it to soldier on its own release cadence only for badly needed changes.

We owe some measure of support on the 1.x line of Micrometer for 3 years at a minimum from its Spring 2018 initial release.

**Comment by izeye** [comment]
@jkschneider Thanks for the quick feedback! I just wanted to know what you have in mind for the event.

Feel free to either close this and create another later when necessary or use this for further discussion if necessary.

**Comment by jkschneider** [comment]
Thanks again for raising this. I think we'll close for now, and when Spring Boot 1.5 is officially EOL, we'll take some action.
