### ISSUE TITLE
[InfluxDB] Add a sslVerify boolean options

### ISSUE THREAD

**Issue by esarbanis** [micrometer-metrics/micrometer#687]
When sending metrics to influxdb over https it should be possible to omit verification.

By adding an `sslVerify` boolean to switch on/off certificate chain and hostname verification. This comes in handy for all those that need to send metrics over https to a known and trusted host, without having to setup keystores and truststores.

**Comment by esarbanis** [comment]
@jkschneider I have began working on it, if that's ok :slightly_smiling_face:

**Comment by jkschneider** [comment]
Sounds great!

**Comment by royshahaf** [comment]
Curious that last week I made a PR to add this ability for the competition (dropwizard-metrics-influxdb by izettle).
Findsecbugs was not pleased, though.
The flag should be documented clearly since turning off ssl verification makes MITM attacks fairly easy.

**Comment by jkschneider** [comment]
@royshahaf Thanks for your comment. It contributed to reaching the conclusion that we should allow users to inject an HTTP client into push-based registries. In this way, we don't make findsecbugs unhappy, but users are still free to do whatever they'd want in the HTTP client that they inject into their registries. See #842.
