### ISSUE TITLE
Add static holder for injecting MeterRegistry

### ISSUE THREAD

**Issue by checketts** [micrometer-metrics/micrometer#69]
Similar to how libraries can code against slf4j by using the LoggerFactory to get a logger, we need a similar way for libraries to get the MeterRegistry.

Instead of using classpath introspection, we can leverage the constructor usage. I'll send a PR shortly.

**Comment by jkschneider** [comment]
```java
final Counter thingCounter = MeterFactory.counter("thing", "region", "test");
```

This could generate a no-op shim (or uses a global SimpleRegistry). 

In a Spring context, a `@BeanPostProcessor` could be used to replace the shim with a counter generated from the registry/registries wired in your `ApplicationContext`.

Frameworks that don't have an equivalent to `@BeanPostProcessor` could affect static state of the factory to change how the "shim" is generated?

**Comment by jkschneider** [comment]
If we implement something like this, #37 probably goes away. You can do more in code than you can in an annotation for sure.

**Comment by checketts** [comment]
Yes, that is exactly how I think it can work. I really like the `@BeanPostProcessor` idea too, that means we wouldn't recommend `static` fields and instead toward normal field variables.

I actually prefer that anyways since the static nature has caused me trouble in the past, and not due to shared state, but rather just the fact that I want a gauge to reference an instance field.

**Comment by danveloper** [comment]
I can't speak for _all_ frameworks that do not have the `@BeanPostProcessor` equivalent, but in Ratpack, the `Execution` (which can-be/is a DI-backed registry) can be got at in a static context, provided the code path is executing on a Ratpack-managed thread.

**Comment by brharrington** [comment]
In spectator we do this using [Spectator.globalRegistry](http://netflix.github.io/spectator/en/latest/javadoc/spectator-api/com/netflix/spectator/api/Spectator.html#globalRegistry--). It returns a composite registry type so the DI provided registry would just get added to that composite if it is desirable to pick up meters from the global registry. This has worked fairly well for us though in rare cases there have been concerns about missing some activity before the DI initialization is complete and the registry is added to the global composite.

Not sure if it is a concern here, but in spectator we also make sure to avoid any use of logging in the composite registry so it is safe to use `Spectator.globalRegistry()` in log appender implementations assuming the logging configuration is setup prior to and independent of DI, e.g., using standard log4j properties configuration.
