### ISSUE TITLE
Support for scheduled metrics reporting

### ISSUE THREAD

**Issue by edudar** [micrometer-metrics/micrometer#691]
This came up during Spring Boot 1.5 to 2.0 and dropwizard + metrics-coursera to micrometer migration. The former couple uses `ScheduledReporter` so metrics, even though they are sent immediately by `java-dogstatsd-client`, are not reported immediately but rather by a schedule like every 5 or 10 seconds. This creates a room to breathe for the agent. Micrometer floods the agent with immediate reporting as my service generates about 10-15K metrics per second as a part of request tracking. Right now there's a 20% toll when metrics are collected in such scenario consumed by datadog agent.

There seem to be a few options:
1. Adopt scheduled reporting as a configurable option
2. datadog-agent v6 [supports batch reporting](https://github.com/DataDog/dd-agent/issues/1862)

**Comment by edudar** [comment]
As a workaround, I created a sink that does buffer and sends metrics to dogstatsd on its own:

```
    @Component
    class Metrics {
        final BlockingQueue<String> queue = new LinkedBlockingQueue<>();
        final StatsdConfig statsdConfig;
        final int interval;
        final ScheduledExecutorService scheduledExecutorService;

        Metrics(StatsdConfig statsdConfig, @Value("${management.metrics.export.interval:10}") int interval) {
            this.statsdConfig = statsdConfig;
            this.interval = interval;
            this.scheduledExecutorService = Executors.newScheduledThreadPool(1);
        }

        @PostConstruct
        void postConstruct() {
            UdpClient udpClient = UdpClient.create(statsdConfig.host(), statsdConfig.port());
            this.scheduledExecutorService.scheduleAtFixedRate(() -> {
                List<String> buffer = new ArrayList<>(queue.size());
                queue.drainTo(buffer);
                udpClient
                        .newHandler((in, out) -> out
                                .options(NettyPipeline.SendOptions::flushOnBoundary)
                                .sendString(Flux.fromIterable(buffer))
                        )
                        .subscribe();
            }, this.interval, this.interval, TimeUnit.SECONDS);
        }

        @PreDestroy
        void preDestroy() {
            this.scheduledExecutorService.shutdown();
        }

        void add(String metric) {
            this.queue.add(metric);
        }
    }
```

**Comment by michael-barker** [comment]
When migrating from Dropwizard Metrics I was able to switch from `ScheduledReporter` to Micrometer's `StepMeterRegistry`.  That might be what you're looking for.  There are several existing meter registries that extend `StepMeterRegistry`.

**Comment by edudar** [comment]
`statsd` one is not a step registry though. It might have to become one, which would be an option 3

**Comment by breun** [comment]
I'm new to working on Micrometer and specifically looking to add buffering/batching support for the Etsy statsd backend. Today I've looked at making `StatsdMeterRegistry` implement `StepMeterRegistry`, but it looks like this is not really a good match, because `StatsdMeterRegistry` currently uses reactive streams with Netty `UdpClient`, while `StepMeterRegistry` uses a scheduled `ExecutorService` approach.

Looking at `StatsdMeterRegistry#start` I see that the `UdpClient` immediately sends every `String` from the `publisher` to statsd:

```
UdpClient.create(statsdConfig.host(), statsdConfig.port())
        .newHandler((in, out) -> out
                .options(NettyPipeline.SendOptions::flushOnEach)
                .sendString(publisher)
                .neverComplete()
        )
```

I'm thinking I'll probably need to modify the `publisher` (which is actually a `Processor`) to buffer (and maybe aggregate counters) and gather multiple lines into a single message. However, I'll also need to enforce a maximum message length (in bytes) for the messages sent to statsd. It's not yet clear to me how I can modify the code to do these things.

**Comment by breun** [comment]
I've talked to Reactor committers and am working on an implementation of [Nagle's algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm), at least for the StatsD registry, which is actually not trivial using the currently available Reactor operators. I don't think there is a generic way to implement this for all meter registries by the way.

**Comment by jkschneider** [comment]
The statsd registry now buffers statsd lines together using @breun's implementation based on Nagle's algorithm. This happens by default without any configuration.

The same approach is not relevant to other registry types. Only statsd requires emission on a per timing basis.
