### ISSUE TITLE
Add LongTaskTimer samples to registries as they are included in a composite

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#699]
... if the sample was initiated against the composite.

```java
    @Test
    void timerSampleStoppedAfterRegistryAdded() {
        LongTaskTimer.Sample startTime = LongTaskTimer.builder("start.time").register(composite).start();
        Timer.Sample startTimeShort = Timer.start(clock);

        clock.addSeconds(1);
        composite.add(simple);

        // by the time the Boot app is finished booting, the registry should be added to the composite
        startTimeShort.stop(composite.timer("start.time.short"));
        assertThat(simple.get("start.time.short").timer().totalTime(TimeUnit.SECONDS)).isEqualTo(1);

        // this should be fixed though.
        LongTaskTimer ltt = simple.get("start.time").longTaskTimer();
        assertThat(ltt.activeTasks()).isEqualTo(1);
        assertThat(ltt.duration(TimeUnit.SECONDS)).isEqualTo(1);
    }
```

**Comment by shakuzen** [comment]
To solve this, I think we'll need new API to pass the active task timings (<id, startTime> map) of each `LongTaskTimer` from composite to new child when registering a new child. However, this isn't API we generally want to expose, hence why it isn't in the API now.

**Comment by shakuzen** [comment]
This is also complicated because the task IDs do not necessarily match between the composite and any children. While not a problem demonstrated in the given test, if a `LongTaskTimer` is started on a composite, there's no way for the user to know what task ID to use to stop it on a child.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2019. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
