### ISSUE TITLE
Possible to reset all currently held metrics?

### ISSUE THREAD

**Issue by david-mccarthy** [micrometer-metrics/micrometer#709]
I'm wondering if it is possible to reset the metrics held, and essentially start over without having to restart the running application?

For example if we are running our application for a number of months then spikes in performance may be more difficult to notice in the gathered statistics..

**Comment by jkschneider** [comment]
Why do you believe it would be harder to notice spikes in performance when running an app for a long time? This is the main reason to always alert based on rates and not cumulative figures. See some of the elaboration on this [here](http://micrometer.io/docs/concepts#_counters).

**Comment by david-mccarthy** [comment]
Hi, thanks for your response. Apologies I haven't come back sooner.

I'm not sure I understand the example in the documentation you linked.  The example uses a counter, so if I check that metric, I am just seeing a number returned. 
If I am using a timer I see a count, a total time and a max, and this is where I am wondering if some information may be hidden over time. As the time span increases this information becomes less useful, as it is showing an average time over a long period.

I also see the max statistic in the timer, but am not sure what this is, as it does not seem to keep track of the maximum time encountered, it appears to be change to lower values from time to time.

**Comment by david-mccarthy** [comment]
> The number that is returned though is either already a rate for monitoring systems that prefer a rate, or a cumulative count for monitoring systems (like Prometheus) that expect you to use the rate query function at retrieval time. 

OK, so do I need to use a specific implementation of MicroMeter to get this functionality? At the moment I just use the MeterRegistry in micrometer-core and use the default timers (such as http.server.requests).

I assume then from your comment that it is the responsibility of the monitoring application to interpret the information, and it is just provided by micrometer as is.

> Max decays with a configurable ring buffer, for precisely the same reasons you cited about average.

How can I configure this ring buffer? The decaying max value is very useful, even better that it is configurable.

**Comment by jkschneider** [comment]
> OK, so do I need to use a specific implementation of MicroMeter to get this functionality? At the moment I just use the MeterRegistry in micrometer-core

Every implementation of `MeterRegistry` defines semantics appropriate to the monitoring system it is designed to serve. It is not then the responsibility of the monitoring system to interpret a single representation from Micrometer, but Micrometer's responsibility to expose the data to the monitoring system in the way it expects.

What doesn't change is the developer's API interaction. For example, `counter.increment(..)` is the same interface that you interact with regardless of what the target monitoring system expects. 

> How can I configure this ring buffer? The decaying max value is very useful, even better that it is configurable.

There are a few ways. You can define it at the time the timer/summary is created if you use the [builder pattern](https://github.com/micrometer-metrics/micrometer/blob/master/samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/TimerSample.java#L38-L39).

You can also define it after the fact using a `MeterFilter` by configuring the `DistributionStatisticConfig`. Look to the example provided [here](http://micrometer.io/docs/concepts#_configuring_distribution_statistics). The example configures percentiles after the fact, but there are similar `distributionStatisticExpiry`/`distributionStatisticBufferLength` options on that same type.

**Comment by jkschneider** [comment]
Since there is nothing to do, I'll close this issue. Feel free to continue commenting on it if there are any further questions, though. Or hit us up on slack.micrometer.io.

**Comment by szczebel** [comment]
I have another case where I'd like to reset timers programatically at runtime.

I'm using timers in very basic performance tests, executed during build time - to have a general idea if certain functionalities degrated significantly (e.g. order of magnitude).

There is a pair of tests that look at each particular timer: serial (1 thread, 500 hits) and concurrent (10 threads, 50 hits each). After each of such tests I inspect timer like [here](https://gitlab.com/class-treasurer/app/blob/ver.2.0.0/core/src/test/java/treasurer/core/perf/PerfMetricsCollector.java)

I'd like to reset the timer between those two tests, so that I don't have to reload the app and regenerate the data for testing.

I'd be happy to see Timer.reset() api. Or a more general MeterRegistry.resetAll() would be fine as well.

Would that be a reasonable argument to reopen this issue?

Or would you suggest any other options?

**Comment by shakuzen** [comment]
@szczebel it sounds like you just need meters in-memory. You could use the `SimpleMeterRegistry` and replace the MeterRegistry used with a new instance to reset, or you could use the `MeterRegistry#remove` method to remove a specific meter, which will cause it to be a fresh instance next time it is used.

**Comment by szczebel** [comment]
@shakuzen these hints solve my usecase, thanks!
