### ISSUE TITLE
Unable to disable RestTemplateMetricsConfiguration

### ISSUE THREAD

**Issue by mohsinkerai** [micrometer-metrics/micrometer#722]
It seems like there is no property or way to disable metrics collection of RestTemplate.

As per documentation, `management.metrics.enable` works with `Whether to deny meters from emitting any metrics.`. 

It only disables emission process, it does not effect collection process.

Collector Configuration is defined in `RestTemplateMetricsConfiguration` via MetricsRestTempateCustomizer and there exist no way to disable it.

Following changes can be done to library in order to disable it
1. Add a property configuration to disable it.
2. Add Such configuration as AutoConfiguration, so one can exclude them.

**Comment by izeye** [comment]
@mohsinkerai It looks you're right for Spring Boot 1.5.x support but for Spring Boot 2.x there is `RestTemplateMetricsAutoConfiguration`.

I created #723 to align with Spring Boot 2.x.
