### ISSUE TITLE
io.micrometer.core.instrument.Meters should not depend on the guava cache class

### ISSUE THREAD

**Issue by tokuhirom** [micrometer-metrics/micrometer#73]
When I want to use the Meters class, I need to import google guava. I don't want to use the Google guava at some time because it doesn't care the backward compatibility well.
Other targets for the Meters class are JDK's core classes. I suggest splitting the guava support and other parts like ExecutorService and Execturor.

(Note: I heard Spring 5 will support the caffeine library as a primary cache library instead of guava cache)

**Comment by checketts** [comment]
Guava is not intended to be a required dependency. Can you please include details on why it is being required or what error you see when it is not being required?

**Comment by jkschneider** [comment]
Hopefully 6527f3a shows how the absence of optional dependencies like guava on the classpath does not preclude the use of other methods on `Meters`. Please let us know if you run into a specific issue that we haven't covered.

Also, thanks for the note on caffeine. Tracking micrometer support for caffeine in #76.

**Comment by tokuhirom** [comment]
@checketts @jkschneider 

Please lok https://github.com/tokuhirom/micrometer-issue-73/tree/master .

I got this error with ↑ repo.

```
micrometer-issue-73/src/main/java/com/example/demo/MicrometerIssue73Application.java:26: error: cannot access Cache
            return Meters.monitor(registry,
                         ^
  class file for com.google.common.cache.Cache not found
1 error
```

Because `Meters.monitor()` method uses method overloading. A method uses method loading loads all classes required by every methods' arguments.

**Comment by jkschneider** [comment]
Compilation failure -- that's what I didn't expect. Thanks for the detail @tokuhirom.
