### ISSUE TITLE
Measuring Logback's Appenders 

### ISSUE THREAD

**Issue by cemo** [micrometer-metrics/micrometer#736]
This part is from `ch.qos.logback.core.OutputStreamAppender#writeBytes` which is the base class of many appenders such as Console or File. 

```

    private void writeBytes(byte[] byteArray) throws IOException {
        if(byteArray == null || byteArray.length == 0)
            return;
        
        lock.lock();
        try {
            this.outputStream.write(byteArray);
            if (immediateFlush) {
                this.outputStream.flush();
            }
        } finally {
            lock.unlock();
        }
    }
```

We observed some problems in our tests and wanted to reduce contention at there. But in order to detect such contentions it would be great to detect them as early as possible.

**Comment by jkschneider** [comment]
I'm not exactly sure what you are asking for. Looking for a `DistributionSummary` to measure payload size moving through appenders? How do you propose to do that?

**Comment by cemo** [comment]
Our threads are waiting on `lock.lock()`. I would like to see that `outputStream` is not consuming fast enough. This can be a ConsoleAppender or FileAppender. I think Meter or Gauge fits for this purpose.
