### ISSUE TITLE
DataSourcePoolMetricsAutoConfiguration doesn't check whether DataSource bean is available properly

### ISSUE THREAD

**Issue by crmky** [micrometer-metrics/micrometer#753]
This is an issue introduced by https://github.com/micrometer-metrics/micrometer/pull/725 in version1.0.6.

The use of `@ConditionalOnBean` is incorrect. If we specify multiple types for that annotation, if **any** of those beans exist, it returns true. In my example, the `MeterRegistry` bean is available, but no `DataSource` bean is available, this auto-configuration will be activate but throws the following exception:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method bindDataSourcesToRegistry in io.micrometer.spring.jdbc.DataSourcePoolMetricsAutoConfiguration$DataSourcePoolMetadataMetricsConfiguration required a bean of type 'javax.sql.DataSource' that could not be found.
	- Bean method 'dataSource' not loaded because @ConditionalOnClass did not find required class 'org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType'
	- Bean method 'dataSource' not loaded because @ConditionalOnClass did not find required classes 'javax.transaction.TransactionManager', 'org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType'


Action:

Consider revisiting the conditions above or defining a bean of type 'javax.sql.DataSource' in your configuration.
```

Here is the Javadoc of `@ConditionalOnBean`:

```
/**
 * The class type of bean that should be checked. The condition matches when any of
 * the classes specified is contained in the {@link ApplicationContext}.
 * @return the class types of beans to check
 */
```

**Comment by crmky** [comment]
This should not be a big problem. Just found that our application created `DataSourcePoolMetadataProvider` instance even spring-jdbc is not on the classpath.

For normal user, the `DataSourcePoolMetadataProvider` instance will only be created by Spring Boot when spring-jdbc is available on the classpath.

**Comment by izeye** [comment]
@crmky Ah, sorry. You're right. I just synced them from Spring Boot 2.x support and forgot the change from https://github.com/spring-projects/spring-boot/commit/457d0414ea419dbe9044343d9aa69009743a0548. I'll create a PR to fix it shortly.
