### ISSUE TITLE
Metrics getting cleared after export to InfluxDB

### ISSUE THREAD

**Issue by PedroBorgesBJSS** [micrometer-metrics/micrometer#755]
I'm using micrometer-registry-influx to export metrics to influxDB on a Spring Boot application and what I am seeing is that the metrics get cleared after each export. For instance, a counter that had a value of 2 gets reset to 0. Counters and time measurements from @Timed annotations are also getting reset.

I'm adding this dependency to the pom:
`
<dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-influx</artifactId>
</dependency>
`

and then i simply add on my .yml:

`
metrics:
    export:
      influx:
        uri: influxdbLocation:port
        db: nameofApp
`

I'm also setting a new tag for all metrics like this:
`
@Bean
    MeterRegistryCustomizer<MeterRegistry> metricsCommonTags() {
        return registry -> registry.config().commonTags("env", this.env);
    }
`
where env is read from the yml.

**Comment by jkschneider** [comment]
Micrometer rate-aggregates counters and timers shipped to influx because of a lack of built-in rate functionality in the query language. See http://micrometer.io/docs/concepts#_client_side.

**Comment by shartte** [comment]
Isn't this the point of https://docs.influxdata.com/influxdb/v1.8/query_language/functions/#non_negative_derivative?
I find it extremely awkward to work with the current implementation since I essentially need to know the reporting step when I set up my dashboard to convert it to rate per second :-|
