### ISSUE TITLE
Counter in InfluxMeterRegistry (StepRegistry/Counter) is reset also if sending to InfluxDB fails

### ISSUE THREAD

**Issue by hgnoyke** [micrometer-metrics/micrometer#759]
I have created a counter in an InfluxMeterRegistry. When it is incremented and on the next "step" sending the update to InfluxDB fails, the counter will still be reset to 0, i.e. data is missing from that metric.
I would like to see the data in InfluxDB after the next successful report.

In short:
Current data in InfluxDB:
0
0 (Sending fails bc InfluxDB N/A)
0

Expected data in InfluxDB:
0
0 (Sending fails bc InfluxDB N/A)
1 (Value comes after the next "step time")

 Is that possible?
Thanks!

**Comment by jkschneider** [comment]
@hgnoyke It seems like this could be harmful if you set a max alert threshold on a counter. Effectively the failed data would be rolled together with data from the most recent interval, making increments apparently higher than they really were in that interval.

**Comment by hgnoyke** [comment]
Yes, indeed. We need to take care of that. In our scenario the missing data is worse as we use these type of counters for tracking business metrics (e.g. cash flowing in). In our distributed system we track whether all services work correctly if sth happens. Then it is ok if the data comes in the next period.

Anyway: We are now working with an InfluxMeterRegistry using the Cumulative* implementations. In Grafana we are using "fill(previous)" in case of missing data in one period (still experimenting with it).

This specific registry is setup like this (businessInfluxConfig is a config pointing to a different database):
~~~~
MeterRegistry businessMeterRegistry = new InfluxMeterRegistry(businessInfluxConfig, Clock.SYSTEM) {
            @Override
            protected Counter newCounter(Meter.Id id) {
                return new CumulativeCounter(id);
            }

            @Override
            protected io.micrometer.core.instrument.Timer newTimer(Meter.Id id, DistributionStatisticConfig distributionStatisticConfig, PauseDetector pauseDetector) {
                io.micrometer.core.instrument.Timer timer = new CumulativeTimer(id, clock, distributionStatisticConfig, pauseDetector, getBaseTimeUnit(), false);
                HistogramGauges.registerWithCommonFormat(timer, this);
                return timer;
            }

            @Override
            protected DistributionSummary newDistributionSummary(Meter.Id id, DistributionStatisticConfig distributionStatisticConfig, double scale) {
                DistributionSummary summary = new CumulativeDistributionSummary(id, clock, distributionStatisticConfig, scale, false);
                HistogramGauges.registerWithCommonFormat(summary, this);
                return summary;
            }

            @Override
            protected <T> FunctionTimer newFunctionTimer(Meter.Id id, T obj, ToLongFunction<T> countFunction, ToDoubleFunction<T> totalTimeFunction, TimeUnit totalTimeFunctionUnits) {
                return new CumulativeFunctionTimer<>(id, obj, countFunction, totalTimeFunction, totalTimeFunctionUnits, getBaseTimeUnit());
            }

            @Override
            protected <T> FunctionCounter newFunctionCounter(Meter.Id id, T obj, ToDoubleFunction<T> countFunction) {
                return new CumulativeFunctionCounter<>(id, obj, countFunction);
            }
        };
~~~~

It would be great if you could configure the type of counters a meter registry should use. Would that be possible?

Not sure whether I got the concepts from http://micrometer.io/docs/concepts#rate-aggregation right. By making InfluxMeterRegistry tied to Step-Meters it seems InfluxDB expects client side aggregations. With my humble knowledge I would not make InfluxDB a clear candidate for this but could also work with server side aggregation. What are your thoughts on this?

**Comment by brett-miller** [comment]
@hgnoyke I think a good pattern in this case would be to use a local Telegraf agent with an influx http input (from java app) and influx output.  Telegraf will provide some durability by buffering the metrics until they can be sent to Influx.

**Comment by jkschneider** [comment]
That's also a reasonable suggestion @brett-miller, although using StatsD as an intermediary does have a performance impact on the app (generates more garbage than pre-aggregated payloads).

I'm going to close this issue for now, unless some new information comes to light.
