### ISSUE TITLE
Add instrumentation for Caffeine caches.

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#76]
https://github.com/ben-manes/caffeine

**Comment by ben-manes** [comment]
See [stats](https://github.com/ben-manes/caffeine/wiki/Statistics) for Dropwizard and Prometheus code examples. The metrics can be pull or push based, based on your preference. I tend to think push is cleaner API wise, but it limits to the core metrics so pull is nice if you have additional ones to capture.

**Comment by jkschneider** [comment]
Thanks @ben-manes!

**Comment by checketts** [comment]
Sorry @jkschneider I had actually written the Prometheus Caffeine implementation I was going to get back to it in micrometer once the other changes had settled down. It mirrors the guava implementation with a few additional metrics.
