### ISSUE TITLE
Hawkular support

### ISSUE THREAD

**Issue by prafsoni** [micrometer-metrics/micrometer#760]
Hawkular is built-in metrics store for Openshift. Having Hawkular support will enable us to reuse it without any additional efforts.

**Comment by shakuzen** [comment]
In looking at the [Hawkular org](https://github.com/hawkular) on GitHub, I'm not seeing any releases in the past couple years. Am I looking at the right place? The lack of activity doesn't entirely rule out supporting it, but we haven't seen much interest in support in the few years this issue has been open. If someone wanted to try making a `MeterRegistry` implementation that shipped to Hawkular, I'd be willing to take a look at it and give some review. We would probably want to start with it being published as a third-party module outside of the official repository. If that got usage and was vetted by multiple parties, we could consider making it an official module.

**Comment by shakuzen** [comment]
Closing for now for the reasons mentioned in my previous comment. If the situation changes or there is new information, we can reconsider.
