### ISSUE TITLE
KairosDB support

### ISSUE THREAD

**Issue by ilinchik** [micrometer-metrics/micrometer#761]
It would be great to have a support for KairosDB.
https://kairosdb.github.io/

**Comment by jkschneider** [comment]
Is Kairos supported through Telegraf's OpenTSDB support since Kairos was a fork of OpenTSDB?

**Comment by ilinchik** [comment]
No Kairos is not a fork of OpenTSDB. As I know It was inspired by the OpenTSDB design but then took a different path. KairosDB based on Cassandra. It supports HTTP REST and Telnet API. There is a plugin for Graphite protocol but it is unstable and does not work with the last version.

**Comment by DanoOM** [comment]
Any chance this will be getting pulled into mainline in the near future?

**Comment by jkschneider** [comment]
@DanoOM it's seeming that way. You are now the third person to ask for it in as many weeks.

**Comment by snicoll** [comment]
@jkschneider it would be nice if you could review https://github.com/spring-projects/spring-boot/commit/89349c6eb974478e186e31efe2418e497624ca6f and harmonize the implementation in the legacy module accordingly. Let me know on the Spring Boot issue if there is something wrong in what I've polished.
