### ISSUE TITLE
OkHttpMetricsEventListener default uriMapper

### ISSUE THREAD

**Issue by danieljamesscott** [micrometer-metrics/micrometer#771]
The default uriMapper in OkHttpMetricsEventListener:

https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.java#L142

Looks a little strange, it is looking for a header named 'URI_PATTERN'.

In the tests:

https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListenerTest.java#L37

This default is being overridden to extract the path from the request object.

This seems inconsistent, is there a reason why it was done like that?

To make it consistent, either the default should be to extract the path from the request object (my preference), or the test should add a header to the request so that users can use the tests to discover how to add path information to the metrics.

**Comment by jkschneider** [comment]
Thanks @danieljamesscott. Don't know the reason it was created the way it was, but your suggestions are perfectly reasonable.

**Comment by danieljamesscott** [comment]
Do you have a preference for the default? I can do a PR to change it, maybe with a simple static method to restore the old functionality?

**Comment by jkschneider** [comment]
I know this has been a while, but can you shed any light on the reason things are the way they are @bjartek?

**Comment by bjartek** [comment]
The reason it does not fetch the path from the request object is that this path has the url pattern with resolved placeholders.

The test should add a header here to be consistent.

**Comment by jkschneider** [comment]
So it's maybe a little unfortunate for general use, but OkHttp doesn't provide a native way of retrieving the parameterized URI. Anything short of trying to retrieve a custom header would be bad for tag cardinality.

**Comment by kppullin** [comment]
In case someone runs across this like I did, if you're using retrofit on top of OkHttp, here's a bit of code that'll set the URI to the path set the retrofit annotated method (uses a bit of guava and apache commons, but easy to adjust as needed):

```
   private static final ImmutableSet retrofitHttpMethodAnnotationName;

    static {
        retrofitHttpMethodAnnotationName = ImmutableSet.of(
                GET.class.getName(),
                POST.class.getName(),
                PUT.class.getName(),
                DELETE.class.getName(),
                PATCH.class.getName(),
                HEAD.class.getName(),
                OPTIONS.class.getName()
        );
    }

...

              OkHttpMetricsEventListener
                    .builder(meterRegistry, "http_client_requests")
                    .uriMapper(request -> {
                        // Extract the URI path `value` from the GET/POST/PUT/etc annotation so that
                        // we can see which URI is called in the metrics. This mirrors the default behavior of the
                        // Spring RestTemplate metrics.

                        Invocation invocation = request.tag(Invocation.class);

                        if (invocation != null) {
                            for (Annotation declaredAnnotation : invocation.method().getDeclaredAnnotations()) {
                                String name = declaredAnnotation.annotationType().getName();
                                if (retrofitHttpMethodAnnotationName.contains(name)) {
                                    try {
                                        return MethodUtils.invokeMethod(declaredAnnotation, true, "value").toString();
                                    } catch (Exception ignored) { }
                                    break;
                                }
                            }
                        }
                        return "none";
                    })
                    .build();
```

**Comment by stepbeekio** [comment]
Thanks @kppullin! Your answer helped a lot. If anyone if doing something similar in kotlin, I've ended up with this function:

```kotlin
    fun extractPathTemplateFromRequest(request: Request): String {
        val annotations = request.tag(Invocation::class.java)?.method()?.declaredAnnotations

        return annotations?.mapNotNull { declaredAnnotation ->
                    when (declaredAnnotation) {
                        is GET -> declaredAnnotation.value
                        is PUT -> declaredAnnotation.value
                        is POST -> declaredAnnotation.value
                        is PATCH -> declaredAnnotation.value
                        is DELETE -> declaredAnnotation.value
                        is HEAD -> declaredAnnotation.value
                        is OPTIONS -> declaredAnnotation.value
                        else -> null
                    }
                }?.firstOrNull() ?: "none"
    }
```

I'm intending to alarm on the presence of `none` as the uri in our metrics as a rough way to catch any edge cases.

**Comment by Bennett-Lynch** [comment]
And in case someone stumbles upon this using OpenAPI Generator with Kotlin and OkHttp (which has nothing similar to the above `Invocation` tag), the following will use reflection to find a given class in the current request's stack trace:

```
inline fun <reified T> uriMapper(): Function<Request, String> {
    return Function {
        val stackTrace = Thread.currentThread().stackTrace
        val element = stackTrace.last { it.className == T::class.qualifiedName }
        element?.methodName ?: "UNKNOWN"
    }
}
```
