### ISSUE TITLE
Metrics for Spring WebFlux WebClient

### ISSUE THREAD

**Issue by PyvesB** [micrometer-metrics/micrometer#772]
Hello there,

According to the documentation, Micrometer supports `http.client.requests` for "any _RestTemplate_ created using the auto-configured _RestTemplateBuilder_".

Nevertheless, even though there is support for `http.sever.requests` metrics handled by WebFlux controllers and functional handlers, there doesn't seem to be any equivalent client metrics for _WebClient_, which is a reactive version of _RestTemplate_.

Am I missing something here? Are there any plans to add such support?

Thanks in advance!

Kind regards,

Pyves

**Comment by shakuzen** [comment]
Support for WebClient metrics have been added in Spring Boot. See https://github.com/spring-projects/spring-boot/issues/12228. Support would not go here because the micrometer-spring-legacy is for Spring Boot 1.5.x, which uses Spring 4.x, before WebClient was introduced in Spring 5.
