### ISSUE TITLE
Prometheus quantile is flat lined

### ISSUE THREAD

**Issue by pratickchokhani** [micrometer-metrics/micrometer#774]
I tried the following config in but it seems to not working properly:

Version:

- Spring Boot: 2.0.1.RELEASE

- micrometer and micrometer-registry-prometheus : 1.0.3 (I'm using Prometheus)

- Server Config:
`management.endpoints.web.exposure.include=health,configprops,env,info,loggers,heapdump,threaddump,prometheus,httptrace`
`management.metrics.distribution.percentiles.http.server.requests=0.5, 0.75, 0.95, 0.99, 0.995`

- Grafana Config:
`Quantile: max(http_server_requests_seconds{node=~'$mult_node', method='POST', status='200', uri=~"/signup"}) by (quantile)`
`Mean: sum(irate(http_server_requests_seconds_sum{node=~'$mult_node', method='POST', status='200', uri=~"/signup"}[2m])) /sum(irate(http_server_requests_seconds_count{node=~'$mult_node', method='POST', status='200', uri=~"/signup"}[2m]))`

Issue:
These Config does not seem to work as the quantiles are coming flatlined and do not change until there is a big difference as shown in the attached image.

<img width="1417" alt="screen shot 2018-08-04 at 9 51 55 am" src="https://user-images.githubusercontent.com/6915712/43672465-16a36f74-97cc-11e8-886e-e796344c8503.png">

**Comment by checketts** [comment]
What do your quantiles look like without a `max`? I wonder if you have several instances, and the outlier sets a high water mark so it appears flatlined overall.

Max is the right way to graph it since you can't average the client side percentiles (that is what the histograms are for).

**Comment by pratickchokhani** [comment]
We do have many instances but even without max, it is flatlined for every node.

**Comment by jkschneider** [comment]
@pratickchokhani As noted in the [release notes](https://github.com/micrometer-metrics/micrometer/releases/tag/v1.0.4), 1.0.4 contained a fix to correctly decay percentiles for Prometheus (this was a regression in 1.0.3).

Please upgrade to Micrometer 1.0.6.

**Comment by pratickchokhani** [comment]
Thanks @jkschneider
