### ISSUE TITLE
InfluxDB database name no longer quoted during creation

### ISSUE THREAD

**Issue by johanmagnusson** [micrometer-metrics/micrometer#776]
It is no longer possible to for `micrometer-registry-influx` to create databases with non-ASCII letters/numbers/underscore, in my case a database name with a dash (ex `my-service`).

I *think* I have identified the problem; since 1.0.6 (brought in by Spring Boot 2.0.4) the identifiers passed to `CREATE DATABASE` are [no longer quoted](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/CreateDatabaseQueryBuilder.java#L33), which they were in [1.0.5](https://github.com/micrometer-metrics/micrometer/blob/v1.0.5/implementations/micrometer-registry-influx/src/main/java/io/micrometer/influx/InfluxMeterRegistry.java#L68).

**Comment by izeye** [comment]
@johanmagnusson Thanks. It looks the double quotes have been dropped accidentally in 5d5db2e63b180c2e1bb89f3d1785894e400753b3. I created #777 to restore it.

**Comment by izeye** [comment]
Resolved via #777
