### ISSUE TITLE
Base units are not sent to Timer/Summary percentiles

### ISSUE THREAD

**Issue by jonmcewen** [micrometer-metrics/micrometer#789]
Graphs of timer.avg, timer.max in Datadog are annotated with the correct time units, but associated percentile metrics don't appear to have base units.

**Comment by krishnaexplore** [comment]
@jkschneider  any tentative date for release of 1.0.7 ? seems this is required feature

**Comment by jkschneider** [comment]
@krishnaexplore No later than September 11

**Comment by jkschneider** [comment]
Fixed with 597f763a
