### ISSUE TITLE
Logback metrics not working for lombok slf4j

### ISSUE THREAD

**Issue by eloo** [micrometer-metrics/micrometer#79]
Hi,
it seems that logs created with lombok ```@Slf4j``` are not collected to the logback metrics.

Is this a bug? Or did i miss something in the configuration?

Thanks

**Comment by Eloo** [comment]
after some testing i've figured out that the turbofilter list seems to be reset during the applicationstart which disables the logbackmetrics.

**Comment by jkschneider** [comment]
Thanks for the diagnosis. Will try to find out where that list gets reset precisely and add our filter again after that :)

**Comment by jkschneider** [comment]
Hmm... I tested this with `bootRun`, and it seems the metric is shipped. It is non-zero whenever the `/api/people` endpoint is exercised. Could you see what might be different about your project (and perhaps we fixed this accidentally along the way somewhere)?

[micrometer-slf4j-lombok.zip](https://github.com/micrometer-metrics/micrometer/files/1322856/micrometer-slf4j-lombok.zip)

**Comment by jkschneider** [comment]
Feel free to reopen if you are still experiencing this issue!

**Comment by lensener** [comment]
same problem with me. Have you solved it yet?
