### ISSUE TITLE
Add extra debugging to WavefrontMeterRegistry

### ISSUE THREAD

**Issue by scottmf** [micrometer-metrics/micrometer#790]
hi,
Right now it is very difficult to trace metrics from my service to wavefront.  It would be really nice if I could turn on debug and trace in order to inspect what is being sent

My ask is for two items:
1. add logger.trace() [here](https://github.com/micrometer-metrics/micrometer/blob/fbca7acb93917767dfc151e25d3df8a5d411c72a/implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java#L79) to show the metrics that are being transmitted to wavefront - proxy or direct
2. add a logger.debug() to show the number of metrics being sent to the wavefront proxy [here](https://github.com/micrometer-metrics/micrometer/blob/fbca7acb93917767dfc151e25d3df8a5d411c72a/implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java#L121)

**Comment by jkschneider** [comment]
@scottmf Out of curiosity, why do you need this? Are you not receiving metrics? Just don't trust it?

**Comment by scottmf** [comment]
@jkschneider, The problem stems from the scenario where I was sending metrics to wavefront but the metrics were being dropped.  I saw that while the directApi outputs some useful information the proxy does not.  Not sure why that is but it seems reasonable to sync that up.
In digging some more it turns out that wavefront drops the entire batch of metrics when the value is NaN.  I got confirmation from the wavefront team on this yesterday.  The only way I figured this was to spend LOTs of time digging which would have been unnecessary if I had this trace-level info.

There is another bug that I eluded above, which I will file now, that the WavefrontReporter should not send metrics with value NaN or else the entire batch is dropped.

Do you have any concerns about adding this to reporter?  It would be quite useful.  Additionally, I would change the logger.info("successfully sent {} metrics to Wavefront", batch.size()) to debug as it is too verbose.  I will have to turn off the logging all together when I use the directApi.

**Comment by jkschneider** [comment]
I appreciate the idea, and sorry it took you so long to debug. I'm not sure I like the idea of adding trace information in all registries, and don't think we should do something special for Wavefront in particular.

Your comment about default debug logging has been captured and will be fixed with #801.
