### ISSUE TITLE
Unix Domain Socket support (DataDog/StatsD)

### ISSUE THREAD

**Issue by kgoralski** [micrometer-metrics/micrometer#792]
java-dogstatsd-client is going to support Unix Domain Socket (see https://github.com/DataDog/java-dogstatsd-client/pull/42)

is Micrometer is going to support it too? 

https://docs-staging.datadoghq.com/xvello/dsd_uds/developers/dogstatsd/unix_socket/
https://github.com/DataDog/datadog-agent/wiki/Unix-Domain-Sockets-support
https://github.com/DataDog/java-dogstatsd-client#unix-domain-socket-support

**Comment by jonnywray** [comment]
This would be really useful in a Kubernetes environment for adding various deployment details, container, and k8s tags to the metrics.

We've experimented with different approaches for the DD reporter for Dropwizard metrics and UDS was the easiest to get up and running. Support here (and so for Spring Boot 2.x) would be great.

**Comment by jonnywray** [comment]
For sure. In k8s the application knows nothing about the deployment environment, but of course it's useful for custom metrics coming from an app to have those, e.g. k8s namespace, host name, container details, etc. Using the DD API is out as that means the app needs the values.

There are two recommended ways of dealing with it outlined in the DD docs (https://docs.datadoghq.com/agent/kubernetes/dogstatsd/) and we've found the unix domain socket approach much easier to get going. And I think is the recommended approach now. Once this is working the various docker and k8s tags are added automatically to your custom metrics.

I tried the other approach, using a k8s hostPort and DogStatsD instance, but could never get it to work. 

There is a work around using DD API. You can use the k8s downward api to add environment variable to your application deployment and use them as custom tags in a MeterRegistryCustomizer. But, you don't get all available tags this way (e.g. docker image details) and automated tagging would be great.

**Comment by jkschneider** [comment]
Cool, thanks! Sounds like a very useful feature.

**Comment by PandaXass** [comment]
This feature could potentially work around https://github.com/containernetworking/plugins/issues/123 for Datadog agent?

**Comment by Simwar** [comment]
@PandaXass I believe so, as the connection will be through the socket, not via the port mapped via hostPort.
@jkschneider is there any news about adding UDS support to micrometer?

**Comment by aantono** [comment]
Something like this would need to be added: https://github.com/Frankqsy/netty-sample/blob/master/netty-client/src/main/java/org/daisy/stevin/netty/sample/client/uds/UdsClient.java

**Comment by liu0013** [comment]
when we plan to implement it? it is very useful for k8s integrate with Datadog.

**Comment by aantono** [comment]
@jkschneider Any updates on the progress of this?

**Comment by shakuzen** [comment]
> Any updates on the progress of this?

Due to the apparent interest in this new feature, I'm tentatively scheduling this for the 1.5 release. It still has the `help wanted` label as a pull request implementing this could help get this integrated sooner.

**Comment by pboado** [comment]
Hi, isn't the implementation _really_ simple, just changing `StatsdMeterRegistry.prepareTcpClient` to have a slightly different connection for UDS? 

```  
private void prepareTcpClient(Publisher<String> publisher) {
    AtomicReference<TcpClient> tcpClientReference = new AtomicReference<>();
    TcpClient tcpClient =
        getTcpClient(statsdConfig)
            .handle((in, out) -> out.sendString(publisher).neverComplete())
            .doOnDisconnected(
                connection -> {
                  Boolean connectionDisposed =
                      connection.channel().attr(CONNECTION_DISPOSED).getAndSet(Boolean.TRUE);
                  if (connectionDisposed == null || !connectionDisposed) {
                    connectAndSubscribe(tcpClientReference.get());
                  }
                });
    tcpClientReference.set(tcpClient);
    connectAndSubscribe(tcpClient);
  }

  private TcpClient getTcpClient(StatsdConfig config) {
    if (config.host().startsWith("unix:")) {
      return TcpClient.create().remoteAddress(() -> new DomainSocketAddress(config.host()));
    } else {
      return TcpClient.create().host(config.host()).port(config.port());
    }
  }
```

**Comment by shakuzen** [comment]
@pboado yes, I suppose it is that simple. Though to be fair, that support was added to reactor-netty long after this issue was originally opened. We would need to upgrade reactor-netty for that to be available, which we had issues doing before and so the upgrade got backed out. We're planning to upgrade for the Micrometer 1.8 release, so I'll target this at the 1.8 release now that it is clear how we can easily support this with minimal maintenance on our side.

**Comment by pboado** [comment]
I'm pretty sure the shaded version of reactor-netty packed with micrometer already includes the functionality.

**Comment by shakuzen** [comment]
While the netty class may be available, support for UDS was not added to reactor-netty until 1.0.0. See https://github.com/reactor/reactor-netty/issues/403

**Comment by pboado** [comment]
Fair enough, thanks for looking into this.

**Comment by shakuzen** [comment]
Now that we have the upgrade to Reactor 2020.0 in main, I was trying to implement this using the netty/reactor-netty features. Unfortunate news is that dogstatsd is listening on a datagram type domain socket, and netty only supports stream domain sockets currently. There is https://github.com/netty/netty/issues/6737 open to add datagram support but no release targeted. This means we can't just use the features offered by netty/reactor-netty to get this, as we hoped. It might be easier to implement this ourselves with [JEP 380](https://openjdk.java.net/jeps/380) but that is only available from JDK 16.

**Comment by jhohertz** [comment]
Looks like the needed support in reactor just dropped in reactor-netty/issues#1714

**Comment by shakuzen** [comment]
It's been a long wait, but support for datagram Unix domain socket protocol has just now landed for the StatsdMeterRegistry. It is available for early testing in `1.8.0-SNAPSHOT` versions and should be in the upcoming `1.8.0-M2` milestone release. You can test it with snapshots by configuring the `protocol` to the newly added `UDS_DATAGRAM` and setting the path to the socket as the `host` config. Let us know if there are any issues or feedback on it. A huge thank you to @violetagg who contributed the underlying support that made this possible to the Netty project and subsequently added support on top of that in Reactor Netty.
I did some ad hoc testing with a Datadog agent running locally on my machine and running an app in a Kubernetes cluster with the datadog agent configured.

**Comment by sqlboy** [comment]
Is there any docs on how to set this up?

**Comment by jonatan-ivanov** [comment]
Only in javadocs, see:
https://github.com/micrometer-metrics/micrometer/blob/4f4cbe2b20cf94024bd5de1a479b98665a51c5f4/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdConfig.java#L76-L82
and
https://github.com/micrometer-metrics/micrometer/blob/4f4cbe2b20cf94024bd5de1a479b98665a51c5f4/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdProtocol.java#L27-L31

But most probably you use a framework which might have a property for this, e.g. if you use Spring Boot: https://docs.spring.io/spring-boot/reference/actuator/metrics.html#actuator.metrics.export.statsd

Please feel free to create an issue/PR to add a note to our docs about changing the protocol.

**Comment by sqlboy** [comment]
Is the path unix:///var/run/datadog/dsd.socket or just /var/run/datadog/dsd.socket ?

**Comment by shakuzen** [comment]
> or just /var/run/datadog/dsd.socket ?

This. We should document this. I've opened #5730 for adding documentation
