### ISSUE TITLE
Support Elastic APM

### ISSUE THREAD

**Issue by cah-andrew-fitzgerald** [micrometer-metrics/micrometer#793]
Elastic (Elasticsearch/Kibana) is working on a new APM solution.
It would be nice if it worked out of the box with micrometer.

see elastic/apm-agent-java#112

**Comment by felixbarny** [comment]
A spec of the API is here: https://github.com/elastic/apm-server/blob/master/docs/spec/metricsets/v2_metricset.json

Note that it currently only supports counters and gauges.

**Comment by jkschneider** [comment]
Thanks @felixbarny. Counters and gauges are good enough. Timers are just composed of a series of counters and gauges. We can make it work.

**Comment by felixbarny** [comment]
See also my very rough WIP for the agent-internal metric tracking here: https://github.com/elastic/apm-agent-java/pull/360

**Comment by sabareeshkkanan** [comment]
This will be a great future. When can we expect this

**Comment by surenraju** [comment]
This feature will be very useful.

**Comment by felixbarny** [comment]
We're also thinking about automatically adding a micrometer Collector via the Elastic APM Java agent which reports to the APM Server if the agent is attached - so that no code changes are necessary.

See also https://github.com/elastic/apm-agent-java/issues/893

**Comment by nikolaigotzmann** [comment]
Hello,
are there any news on this feature?

**Comment by xeraa** [comment]
The APM agent has a Micrometer integration in beta now: https://www.elastic.co/guide/en/apm/agent/java/current/metrics.html#metrics-micrometer

**Comment by shakuzen** [comment]
It sounds like deferring to the Micrometer support in the agent is a good resolution to this request. We can add some documentation to https://micrometer.io/docs/registry/elastic referring to the APM docs. I have made https://github.com/micrometer-metrics/micrometer-docs/issues/203 for that.
