### ISSUE TITLE
Plan for dropping Spring Boot 1.3 and 1.4 supports

### ISSUE THREAD

**Issue by izeye** [micrometer-metrics/micrometer#799]
Based on [this blog post](https://spring.io/blog/2018/03/16/micrometer-spring-boot-2-s-new-application-metrics-collector), Micrometer also supports Spring Boot 1.3 and 1.4 which have been already EOLed:

> Micrometer is the metrics collection facility included in Spring Boot 2’s Actuator. It has also been backported to Spring Boot 1.5, 1.4, and 1.3 with the addition of another dependency.

I'm not sure how much the Spring Boot legacy support will evolve but having support for the EOLed Spring Boot versions could be a burden. Is there any plan for dropping support for the already EOLed Spring Boot versions?

FTR I'm not sure that the current releases are compatible with the EOLed Spring Boot versions as I haven't seen any compatibility tests for them.

**Comment by jkschneider** [comment]
@izeye Perhaps we should make a statement about this somewhere in the doc, but we've been treating 1.3 and 1.4 as "best effort" support. There really isn't much to `micrometer-spring-legacy` that would work in one version and not the others. When we decide to EOL `micrometer-spring-legacy` or move it somewhere else on account of 1.5's EOL, then at that time we are essentially saying the same thing about 1.3-4.

**Comment by izeye** [comment]
FTR, [Spring Boot 1.x EOL will be on Aug 1st 2019](https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019).
