### ISSUE TITLE
Binders should register metric names that follow different conventions

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#80]
Example from Slack on Aug 8:

> It seems like Prometheus convention tells us to 1)  include unit in the name and 2) append '_total' for cumulative values while Atlas does not.

cc / @trustin

**Comment by trustin** [comment]
Thanks for creating an issue for this. I see different libraries have different conventions. To list a few:

- Dropwizard
  - Dot separator
  - Camel case
  - No unit suffix
  - No total suffix for cumulative value
  - No tags
  - No help
  - e.g. `caffeineCache.hits`
- Prometheus
  - Underscore separator
  - Snake case
  - Unit suffix
  - Total suffix for cumulative value
  - Tags
  - Help
  - e.g. `caffeine_cache_hits_total`
- Atlas
  - Dot separator
  - Camel case
  - No unit suffix
  - No total suffix for cumulative value
  - Tags
  - No help
  - e.g. `caffeineCache.hits`

Prometheus is interesting in that:

- It uses the same separator (underscore) for components and words, resulting in ambiguity. e.g. There's no way to tell the difference between `caffeineCache.hits` and `caffeine.cacheHits`.
- It requires to append unit suffix.
- It requires to append `_total` for cumulative meters
- It allows specifying 'help' string for a meter, which is a human-readable description of the meter.

**Comment by trustin** [comment]
One option to solve this is to let a user provide enough information so that micrometer can generate the names that meet the convention:

- Specify the unit (bytes/nanoseconds, ..), cumulativeness and help string of a meter.
- Define a universal naming convention which can be translated into the naming convention of provider. e.g. `"caffeineCache.hits"` rather than `"caffine_cache_hits"` ?

**Comment by trustin** [comment]
Here's my simple name generator:

https://github.com/trustin/armeria/blob/stats_micrometer/core/src/main/java/com/linecorp/armeria/common/metric/MeterRegistryUtil.java#L50

Example:

https://github.com/trustin/armeria/blob/stats_micrometer/core/src/main/java/com/linecorp/armeria/internal/metric/CaffeineMetricSupport.java#L76

and test case:

https://github.com/trustin/armeria/blob/stats_micrometer/core/src/test/java/com/linecorp/armeria/internal/metric/CaffeineMetricSupportTest.java#L46
