### ISSUE TITLE
Discuss: TLS/SSL support in core for reporter configurations

### ISSUE THREAD

**Issue by spinscale** [micrometer-metrics/micrometer#809]
I took a quick look at micrometer yesterday for the first time and noticed, there is no story around TLS/SSL - this means every reporting implementation will implement this themselves. It's no easy thing to properly implement TLS/SSL configurations, and java does not make this particular appealing by dealing with tons of system properties (ok, that was an understatement, it really sucks - big time).

Before features like [this one](https://github.com/micrometer-metrics/micrometer/issues/687) to fully disable the verification features of TLS get added, would it make sense to have a discussion how to properly support this?

I'd imagine a few helpers in micrometer core, that allows to add configuration options, that on the one hand properly parse certificate files that are linked to via configuration allowing to configure custom CAs and certs and on the other hand have helpers to create ssl socket factories based on the configurations.

**Comment by jkschneider** [comment]
@spinscale I agree we need to handle this more generally. I'm honestly out of my depth on the proper way to handle TLS/SSL. Any guidance you can provide?

**Comment by spinscale** [comment]
From my perspective (full blown subjective experience) the most important thing is to stay away from keystores for SSL/TLS certs. This is a java thing and alienates ops people and non-java developers alike. Using same files and formats than openssl/apache/nginx for TLS certs is what I would do.

This means you have configuration options to specify the path to those files allowing you to create SSLSocketFactories and other SSL classes based on those, which then can be used to inject into the HTTP clients used in the concrete implementation.

Another part (which I have not mentioned in the ticket on purpose) is secrets management. Do you want to put passwords in configuration files or do you have another vault-like mechanism (or a keystore might actually be a valid idea here). This is much more cumbersome to manage, but that's the price for security.

Hope this makes sense!

**Comment by jkschneider** [comment]
@spinscale I don't believe (though I haven't created a tutorial on it yet) that anything needs to happen for secrets management. It should be a simple matter of binding secrets from something like vault to the correct property.

**Comment by jkschneider** [comment]
> Using same files and formats than openssl/apache/nginx for TLS certs is what I would do.

> This means you have configuration options to specify the path to those files allowing you to create SSLSocketFactories and other SSL classes based on those, which then can be used to inject into the HTTP clients used in the concrete implementation.

Is this encapsulated somewhere that we can use a component off-the-shelf?

**Comment by spinscale** [comment]
netty has an [SslContextBuilder](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslContextBuilder.java) with a few helpers. Elasticsearch is doing something very similar, but even though the code is open, it is not open source, as security is part of the commercial code base (disclaimer: I work for Elastic) - so I might not be of much help here.

I do not know about other implementations (that do not make use of the keystore). Cassandra, Solr, Druid Hazelcast all seem to have picked the keystore route after a super quick check.

**Comment by jkschneider** [comment]
@spinscale We're talking about allowing folks to simply inject an HTTP client of their choice into push-based registries. In this way, you could use the evolved features already present in Netty, for example, if that is your client of choice. I hope this satisfies the need while not requiring Micrometer to recreate this logic. See #842.

**Comment by spinscale** [comment]
I'd personally prefer to keep dependencies small to prevent things like classpath hell and thus have proper support to create JDK-core based TLS helpers/classes via the above described approach, but I am not a maintainer nor do I have the time to contribute code myself at the moment.

Thanks for taking a look, much appreciated!

**Comment by jkschneider** [comment]
@spinscale To be clear, the approach we're considering does keep dependencies small (at least from the perspective of Micrometer). We'll still continue to use the `java.net.HttpURLConnection` approach we do today as the default client. If you want something more special in your app, you can choose whatever client you probably already have on your classpath. Hopefully makes sense?
