### ISSUE TITLE
Ability to export to more than one MeterRegistry

### ISSUE THREAD

**Issue by trustin** [micrometer-metrics/micrometer#81]
When migrating from one metric library to the other, it is necessary to export the stats to more than one `MeterRegistry` implementation. It would be useful to have a `MeterRegistry` implementation that broadcasts its calls to more than one delegate.

**Comment by jkschneider** [comment]
Thanks for creating this ticket -- I've had this in the back of my mind to support for a little while now. Even when you've consolidated on one monitoring system, I can imagine wanting to publish locally to JMX as well.

**Comment by jkschneider** [comment]
The default static global registry will be linked to an empty composite registry. Related to #69 .
