### ISSUE TITLE
Exception when using @Timed annotation on a @Scheduled method with PrometheusMeterRegistry and TimedAspect

### ISSUE THREAD

**Issue by devaprasadh** [micrometer-metrics/micrometer#813]
There is a `TimedAspect` bean defined:

```java
@Bean
public TimedAspect timedAspect(MeterRegistry registry) {
	return new TimedAspect(registry);
}
```

And the method being timed looks like:

```java
@Scheduled(cron = "0 0 0/1 * * *")
@Timed(value = "timer.doSomething", percentiles = { 0.5, 0.75, 0.95, 0,98, 0.99 })
public void doSomething() {
       // do something 
}
```

When the `doSomething` method finished execution, the exception is:

```
ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter containing tag keys [app]. The meter you are attempting to register has keys [app, class, method].
        at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$collectorByName$9(PrometheusMeterRegistry.java:361)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
        at io.micrometer.prometheus.PrometheusMeterRegistry.collectorByName(PrometheusMeterRegistry.java:348)
        at io.micrometer.prometheus.PrometheusMeterRegistry.newTimer(PrometheusMeterRegistry.java:160)
        at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:257)
        at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:566)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:528)
        at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:255)
        at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:447)
        at io.micrometer.core.aop.TimedAspect.timedMethod(TimedAspect.java:78)
```

`app` is the name of the default tag that is setup for all metrics. The exception seems to be because the `ScheduledMethodMetrics` aspect and `TimedAspect` are both trying to time the same method. ScheduledMethodMetrics creates timer `timer.doSomething` with only the app tag and then TimedAspect tries to create a timer with the same name but with additional `class` and `method` tags.

The timer created by ScheduledMethodMetrics was present in the `/prometheus` endpoint

```
timer_doSomething_seconds{app="sample-app",quantile="0.5",} 6.979321856
timer_doSomething_seconds{app="sample-app",quantile="0.75",} 6.979321856
timer_doSomething_seconds{app="sample-app",quantile="0.95",} 6.979321856
timer_doSomething_seconds{app="sample-app",quantile="0.98",} 6.979321856
timer_doSomething_seconds{app="sample-app",quantile="0.99",} 6.979321856
timer_doSomething_seconds_count{app="sample-app",} 2.0
timer_doSomething_seconds_sum{app="sample-app",} 15.689029194
```

Tested with versions `1.0.5` and `1.0.6` and spring boot version `1.5.15.RELEASE`

**Comment by dcoraboeuf** [comment]
I have the same error when registering a counter:

```
meterRegistry.counter("job_error_count", tags).increment()
```

Micrometer `1.0.3`
Spring Boot `1.5.12`

> java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter containing tag keys []. The meter you are attempting to register has keys [job_category, job_id, job_type].

**Comment by jkschneider** [comment]
@dcoraboeuf The error message says it all: Prometheus requires that all meters with the same name have the same set of tag keys. Anything we can do to clarify that?

**Comment by dcoraboeuf** [comment]
I understand the message but not how I can get it. The only location I use this meter, identified by this name, is in this very piece of code, with always the same set of tag keys (but different tag values of course). So I think I'm good in this regard.

So I actually wonder where the meter with the empty tag key set could come from.

**Comment by dcoraboeuf** [comment]
It so happens that I had two (distinct) counters:

* ontrack_job_error_count (the one causing the error)
* ontrack_job_error_count_total (a gauge)

If I change the counter name of something else (like ontrack_job_errors), the error disappears.

So it seems there is a kind of collision based on the prefix of the counter.

So not an issue for me.

**Comment by devaprasadh** [comment]
@jkschneider Is this issue resolved?

**Comment by jkschneider** [comment]
@devaprasadh I don't think there is an issue to resolve. The error message says it all: Prometheus will not accept two metrics with the same name and a differing set of tags.

If you can provide a reproducible test case that indicates that there is a framework level issue here, would be happy to take a look.

**Comment by jkschneider** [comment]
`TimedAspect` is incubating for a reason: it is difficult to have framework-level use of `@Timed` and also a AOP-oriented approach. I'd suggest turning off `TimedAspect`. It is bound to be rewritten with 1.1.0 one way or another, probably to a non-AOP approach.

**Comment by tooms4444** [comment]
Hello,
I'm having the same issue with Spring Boot 2.0.8, even when upgrading micrometer-registry-prometheus to version 1.1.1 but, needless to say as it has already been confirmed, no duplicate @Timed entries in code

**Comment by devatherock** [comment]
@tooms4444 Looks like the [PR](https://github.com/micrometer-metrics/micrometer/pull/500) is still open. But you shouldn't be facing this issue if you are in Spring Boot 2+ because the `ScheduledMethodMetrics` class which was creating the duplicate metric is in `micrometer-spring-legacy` which is meant for using micrometer with Spring Boot 1.x versions

**Comment by tooms4444** [comment]
@devatherock Hello, thx for feeding back. Let me confirm that this issue arises with Spring Boot 2.0.8 (not the parent, if that changes anything, but POM import).
The issue happens with normal (1.09) and upgraded dependencies to micrometer-core 1.1.1
Please see traces attached. 
[traces_micrometer-core_1.0.9.txt](https://github.com/micrometer-metrics/micrometer/files/2767829/traces_micrometer-core_1.0.9.txt)
[traces_micrometer-core_1.1.1.txt](https://github.com/micrometer-metrics/micrometer/files/2767830/traces_micrometer-core_1.1.1.txt)

**Comment by jkschneider** [comment]
@tooms4444 We can talk about this in more real time in [Slack](http://slack.micrometer.io) if you'd like, but I still think there is no problem in the Micrometer code itself. It appears that the method is being timed in two different ways with different sets of tags and Prometheus does not allow this. The second set of tags suggests that the method being timed is a rest endpoint (because status and uri are tags). This is instrumented by the framework. If you also add a @Timed annotation with different tags, Prometheus will fail.

**Comment by devatherock** [comment]
I was able to recreate the error when I used Timed annotation with name `http.server.requests` on a controller method. The code is below:

```java
@RestController
public class HelloController {
	@RequestMapping(path = "/hello", method = RequestMethod.GET)
	@Timed("http.server.requests")
	public String sayHello() {
		return "hello";
	}
}
```

`TimedAspect` first registers a timer named `http.server.requests` with tags class, exception and method. Then when WebMvcMetricsFilter tries to register the timer `http.server.requests` with tags exception, method, status and uri, the exception was thrown

**Comment by shakuzen** [comment]
@devatherock that would be expected in that case as @jkschneider explained in his previous comment.

**Comment by tooms4444** [comment]
Thank you @jkschneider and everyone : I didn't get that the issue was coming from intricated timers, as the message seemed to be related to a particular duplicate timer name
