### ISSUE TITLE
LongTaskTimer not increasing count in prometheus

### ISSUE THREAD

**Issue by ssozonoff** [micrometer-metrics/micrometer#816]
Maybe I understand LongTaskTimer poorly but when I read both the _sum and _count values in prometheus the _sum grows but the count remains at 1. Documentation indicates that the registry will return the same LongTaskTimer if the key and tag are the same. How than is the count supposed to get incremented or how am I supposed to use the time.

What am I missing?

**Comment by jkschneider** [comment]
@ssozonoff `_sum` grows until the task is complete. `_count` represents _active_ tasks, so is effectively a gauge. It is supposed to go up and down.
