### ISSUE TITLE
Way of constructing Gauge by providing only Supplier

### ISSUE THREAD

**Issue by gkresic** [micrometer-metrics/micrometer#818]
Currently, Gauges are constructed as observers on some objects. Furthermore, those objects must be always alive, because `DefaultGauge` holds only weak reference to it.

Considering that metrics sometimes may be provided by some static functions, Gauges that use `java.util.function.Supplier` as source of their values would be useful.

**Comment by jkschneider** [comment]
Interesting.

**Comment by jkschneider** [comment]
Related to #807
