### ISSUE TITLE
Atlas percentile timers/summaries missing return statement

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#819]
https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-atlas/src/main/java/io/micrometer/atlas/AtlasMeterRegistry.java#L139

**Comment by jkschneider** [comment]
This appears to be working correctly. `PercentileTimer` is additive, creating additional counters for percentile histogram data.

**Comment by twicksell** [comment]
@jkschneider Those additional counters are wrapped inside of PercentTimer and need to be incremented for this feature to work. It looks like this *should* be returned up to the user after all, or otherwise wrapped inside of the Timer that is returned to the user.

**Comment by jkschneider** [comment]
Fixed with e6fb9a24.
