### ISSUE TITLE
TomcatMetrics never removes NotificationListeners

### ISSUE THREAD

**Issue by ArloL** [micrometer-metrics/micrometer#827]
First of all thanks for this library. Everything I tested so far just works out of the box and it's great to have this information with very little configuration.

While investigating a ClassLoader leak issue I came across the `TomcatMetrics` class and noticed that it might add `NotificationListener`s but never removes them. This is a problem in application server deployments where this creates a MetaSpace leak. I propose keeping a List of all registered `NotificationListener`s and adding a `shutdown` (so Spring automatically calls it) method that removes them.

If this sounds reasonable I can create a PR for my proposed changes.

Thanks :+1:

**Comment by jkschneider** [comment]
Thanks for the report. I'd love to entertain any solution provided it isn't Spring specific.

**Comment by izeye** [comment]
@ArloL Are you still interested in creating a PR? Your original proposal looks Spring-specific. I’d propose removing itself at the end of the method body as its job’s already done there. If you can’t find time for it, I could take care of it.

**Comment by izeye** [comment]
I just created https://github.com/micrometer-metrics/micrometer/pull/850 to fix this as it's targeted for 1.0.7 which is due by September 14, 2018.

@ArloL Sorry if you were still interested in creating a PR for this.
