### ISSUE TITLE
HierarchicalNameMapper API design issues

### ISSUE THREAD

**Issue by trustin** [micrometer-metrics/micrometer#83]
I see a few design issues in `HierarchicalNameMapper`:

- It is currently possible to change the behavior of an `HierarchicalNameMapper` by calling its setters at any time, which can result in confusing situation. e.g. A user can change the behavior of `HierarchicalNameMapper.DEFAULT` completely.
- It tries to require more (separators and comparators) than what's essential.

I propose to make `HierarchicalNameMapper` a functional interface:

```java
public interface HierarchicalNameMapper {
    static HierarchicalNameMapper DEFAULT = ...;
    String toHierarchicalName(String name, Iterable<Tag> tags);
}
```

**Comment by jkschneider** [comment]
Agreed, I think your design is an improvement.

**Comment by jkschneider** [comment]
Cannot be a functional interface and have a static default, however.

**Comment by adriancole** [comment]
Cannot be a functional interface and have a static default, however

Are you refering to a default method or a constant named default?

**Comment by adriancole** [comment]
Nm looked at your commit. All good
