### ISSUE TITLE
Bring back PushGateway functionality / autoconfiguration for SB 2.x

### ISSUE THREAD

**Issue by davidkarlsen** [micrometer-metrics/micrometer#830]
It seems the work that was put into spring-legacy for autoconfiguration of Prometheus Pushgateway was not ported to the spring-boot 2.x code. It would be great to have it there too, as one sometimes need the push-gateway (e.g. for batch-jobs).

Also see https://stackoverflow.com/questions/49779684/how-to-export-metrics-to-prometheus-via-pushgateway-using-spring-boot-2-0 

Should it be added to the micrometer codebase or to spring-boot 2.x?

**Comment by jkschneider** [comment]
> Should it be added to the micrometer codebase or to spring-boot 2.x?

Good question that I don't know the answer to just yet.

**Comment by davidkarlsen** [comment]
@jkschneider I guess it belongs in SB along with the rest of the code that was ported, look at: https://github.com/spring-projects/spring-boot/pull/14353 - however it would maybe be nice to manage the pushgateway dependency in micrometer alongside the other prometheus libraries?

**Comment by jkschneider** [comment]
How do you propose Micrometer manage the pushgateway dependency? It would have to be optional to `micrometer-registry-prometheus` even if the logic were there. Micrometer doesn't produce a BOM. Thoughts?

**Comment by jkschneider** [comment]
Closing this as it seems to be done in https://github.com/spring-projects/spring-boot/pull/14353
