### ISSUE TITLE
Publish `micrometer-registry-elastic`

### ISSUE THREAD

**Issue by pete-woods** [micrometer-metrics/micrometer#833]
Would be great to be able to start to take advantage of this.

I can't seem to find it here yet: https://mvnrepository.com/artifact/io.micrometer

**Comment by izeye** [comment]
@pete-woods Elasticsearch support was added in #154 which targets for 1.1.0-rc.1 which hasn't been released yet.

**Comment by pete-woods** [comment]
Whoops. I just noticed this myself (it not being in 1.0.6).
