### ISSUE TITLE
Micrometer without Spring Boot Actuator

### ISSUE THREAD

**Issue by theigl** [micrometer-metrics/micrometer#834]
I just finished migrating from Dropwizard Metrics to micrometer. Most of the changes were straight forward. The only thing I'm missing is support for [Apache HTTP client](https://github.com/micrometer-metrics/micrometer/issues/533).

Our application is a Spring app that has been ported to Spring Boot for tooling and easy of deployment. We use hardly any auto-configution, because it tends to be quite unpredictable when enabled in large, existing applications.

That's no problem because we can easily create our own meter registry beans and inject them where needed.

However, when I tried to manually instrument `RestTemplate`, I noticed that I'm forced to add a dependency on Spring Boot Actuator where the `MetricsRestTemplateCustomizer` and related classes reside:

```
import org.springframework.boot.actuate.metrics.web.client.DefaultRestTemplateExchangeTagsProvider;
import org.springframework.boot.actuate.metrics.web.client.MetricsRestTemplateCustomizer;
import org.springframework.boot.actuate.metrics.web.client.RestTemplateExchangeTagsProvider;
```

You probably had good reasons for this, because the `micrometer-spring` module is marked as `legacy`. However, in my opinion, the old direction of dependencies makes much more sense for users who do not use Spring Boot with auto-configuration and do not want to pull the actuator dependencies into their lower level modules.

So my question is: Wouldn't it make sense to keep the `micrometer-spring` module and depend on it in the Spring Boot Actuator?

**Comment by izeye** [comment]
> Wouldn't it make sense to keep the micrometer-spring module and depend on it in the Spring Boot Actuator?

@theigl It sounds sensible to me but I don't think it's feasible as Micrometer supports both Spring Boot 1.x and 2.x at the same time.

**Comment by izeye** [comment]
It's possible if we have two `micrometer-spring` modules, one for Spring Boot 1.x and another for Spring Boot 2.x but I wonder the additional complexity would be worth the benefit from the `micrometer-spring` module.

**Comment by theigl** [comment]
For my specific use case, I'd be happy with plain `HttpClient` instrumentation as well. With Dropwizard Metrics I used [`InstrumentedHttpClients`](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-httpclient/src/main/java/com/codahale/metrics/httpclient/InstrumentedHttpClients.java).

**Comment by jkschneider** [comment]
For the `HttpClient` instrumentation, we have an open issue #533 targeted for 1.1.0.

**Comment by jkschneider** [comment]
It's tricky for us to instrument `RestTemplate` without `RestTemplateBuilder`, so not really sure what the path forward is.

The Spring Boot team views metrics as a "production ready feature" outside of core application logic, which is precisely the domain of Spring Boot Actuator. I don't think we'll convince them to move it to a lower level unfortunately.

**Comment by theigl** [comment]
Thanks for clearing that up @jkschneider. I do not necessarily agree and still think that simpler building blocks usable without Spring Boot would be preferable, but I'll close this in favor of #533 .
