### ISSUE TITLE
Tomcat metrics only works on embedded Spring Boot 2 Tomcat instance

### ISSUE THREAD

**Issue by jreijn** [micrometer-metrics/micrometer#835]
At my current project we've build a Spring Boot 2 application which we deploy remotely to a Tomcat 8.5.x instance. I expected the tomcat metrics to show up in our actuator metrics endpoint, but they do not. 
At first I thought it had to do something with the Spring Boot auto configuration, but after debugging I noticed that  io.micrometer.core.instrument.binder.tomcat.TomcatMetrics#registerMetricsEventually queries for object names starting with "Tomcat:". However if you run a Spring Boot application inside a plain Apache Tomcat 8.5.x (so not the Spring Boot embedded one) and connect with JConsole to see the mbeans the root MBean starts is "Catalina" instead of "Tomcat". I noticed that Spring Boot used tomcat-embedded, which as far as I can see explicitly names the embedded webserver "Tomcat", so therefor it works out of the box with Boot, but not with an 'external' instance .

**Comment by izeye** [comment]
@jreijn Thanks for the report! I think your analysis is correct. I created #836 to resolve this.

**Comment by jreijn** [comment]
@izeye great. If I can help in testing something do let me know!

**Comment by izeye** [comment]
@jreijn I confirmed the fix with [a sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/war) but if you could confirm the original issue is resolved with the fix, it would be appreciated.
