### ISSUE TITLE
Add design for resilience for when metrics export fails, so that metrics are not lost

### ISSUE THREAD

**Issue by Hoagiex** [micrometer-metrics/micrometer#837]
When a metrics export fails (e.g. in the ElasticMeterRegistry, when the connection with Elastic cannot be established), the batch of Metrics is lost and there is currently no way to recover it.

Suggestion:
Can a design be added, where a configurable retry mechanism is added directly into the MeterRegistries, so that the already created request payload is stored on export failure, and the export is retried at a later moment in time?

(or at least a lightweight solution, where a user supplied callback is called with the composed request body string of the failed request, so that a custom handling can be implemented?)

**Comment by jkschneider** [comment]
I'm thinking that this is another concern that is rolled into #842. I can imagine you injecting a HTTP client call that is wrapped in [Resilience4J Retry](http://resilience4j.github.io/resilience4j/#_retry) logic into your registry. Then you'd have full control over the retry logic with a library which is purpose-built for this and we won't be reinventing that in Micrometer.

**Comment by Hoagiex** [comment]
@jkschneider I'm not talking about a http client retry mechanism, but a local storage mechanism, that would allow the target system for the metrics export (e.g. Elastic) to be down for a longer period (e.g. 15 minutes), without the metrics with a lower step time to be lost.

A http retry solution, would only result into spamming the non-present target. If anything, you would use a back-off setp like hystrix in cases like this, so you need to have control over the metric export, to allow local buffering of the metrics data, that could not be exported.

Separating the actual export logic from the MeterRegistry, would allow for injection of a custom exporter, with a fallback to the default exporter* in the micrometer autoconfiguration.

NOTE: It's not entirely different than #842, but the cut-off for the abstraction would be at a slightly higher level than merely http handling, because it would also include the actual (complete-) flow of exporting the metrics, leaving only the request body construction to the specialized ElasticMeterRegistry class.

This change would be non-invasive and contained.

* containing the current connection logic in the MeterRegistry

**Comment by jkschneider** [comment]
Ah I see. I don't think the math works out for this @Hoagiex. Rate-normalized figures are dimensioned with `rate/sec*interval`. If `interval` is variable, time scale aggregation on the back side wouldn't work.

**Comment by Hoagiex** [comment]
@jkschneider I'm not talking about modifying anything in the metrics system, but purely enabling the ability, to add specific handling in the MeterRegistry for request bodies (the composed string) that fail to be transmitted.

**Comment by jkschneider** [comment]
@Hoagiex I'm sorry, it just doesn't work. We can't simply send request bodies that have amassed when we can successfully get through to the monitoring system. Most of them don't even have a timestamp on the body.

**Comment by Hoagiex** [comment]
@jkschneider Ah ok, thank you. Now I understand. I was speaking specifically from my experience (which is only with the ElasticMeterRegistry).
