### ISSUE TITLE
IdentityTagFormatter could be a singleton

### ISSUE THREAD

**Issue by trustin** [micrometer-metrics/micrometer#84]
According to the source code:
```java
public class IdentityTagFormatter implements TagFormatter {
}
```

.. which seems like a perfect fit for a singleton. How about:

- making `IdentityTagFormatter` a package-private class and
- adding `TagFormatter.identity()` which returns the singleton of `IdentityTagFormatter`?

**Comment by trustin** [comment]
Actually, I find all other `TagFormatter` implementations are stateless and can be singletons. What do you think about adding the singleton factory methods for each `TagFormatter` implementations? e.g. `TagFormatter.prometheus()` and `TagFormatter.influx()`

**Comment by jkschneider** [comment]
* We should keep `IdentityTagFormatter` public so users can implement custom registries that don't need any tag normalization.
* I'm neutral on the singleton factory methods and singletons for `TagFormatter`s in general. I would hope they are generally being wired in DI-capable environments that are effectively making singletons anyway, but there would be no harm in adding these shortcuts.

**Comment by jkschneider** [comment]
In the end, since they `TagFormatters` are super cheap to create and will generally be wired in a DI enviroment, I don't see a compelling reason to do this.
