### ISSUE TITLE
How to get newly created metric (MetricBinder) in actuator/metric endpoint? 

### ISSUE THREAD

**Issue by abhishekhbd** [micrometer-metrics/micrometer#852]
I want to get the kafka metric, so created a kafkaconsumermetric of type MetricBinder, now i want this in actuator/metric. I am using springboot less then 2.0.
I followed something looks like https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaConsumerMetrics.java

**Comment by jkschneider** [comment]
There is no relationship between the Spring Boot 1.x metrics system which provides the `/metrics` endpoint there, and Micrometer. `/actuator/metrics` in Spring Boot 2 is produced from Micrometer. We have no intention of adding an additional metric actuator endpoint for Boot 1.x, though you can write a simple one fairly easily by simply iterating over `registry.getMeters()`.

**Comment by izeye** [comment]
> I am using springboot less then 2.0.

@abhishekhbd Did you mean to say that you're using Spring Boot 1.5.x?

**Comment by izeye** [comment]
Ah, @jkschneider has already answered two minutes ago :sweat_smile:
