### ISSUE TITLE
More convenient getters for MeterRegistry

### ISSUE THREAD

**Issue by trustin** [micrometer-metrics/micrometer#87]
`MeterRegistry` currently provides a single getter method:

```java
    /**
     * @return The set of registered meters.
     */
    Collection<Meter> getMeters();
```

Finding a specific `Meter` and get its value(s) is pretty useful when you write a test case to verify if the related counters were increased, etc.

I can write a utility class that scans over the `Collection<Meter>` to find a matching `Meter` and get its `Measurement`s, but it wasn't very nice in terms of user experience. 

Have you thought about adding more ways to get the measurement values? For example, I wrote the following utility class to access the measurement values, but it would be way better if `MeterRegistry` provided this functionality out of the box:

https://github.com/trustin/armeria/blob/stats_micrometer/core/src/main/java/com/linecorp/armeria/common/metric/MeterRegistryUtil.java#L121

**Comment by checketts** [comment]
There is also `findMeter` already

**Comment by trustin** [comment]
Oh, didn't realize it was added to master. Thanks! However, I find it is still pretty hard to get the measurement values. e.g.

```java
// Create a counter whose type is not Counter.
registry.counter(name, tags, someSupplier, supplier -> supplier.get().getSomeProperty());

Meter m = register.findMeter(Type.COUNTER, name, tags).get();
// Getting the value is not very convenient; needs shortcut methods?
double value = m.measure().get(0).value();
```

It gets quite a bit more verbose if a user accesses a `Meter` that produces multiple measurements and he or she wants to access one of them (e.g. count or sum of DistributionSummary)

**Comment by jkschneider** [comment]
@checketts' creation of assert methods to check values on meters in #76 tells me you are right about this: we could use a little more convenience.

**Comment by checketts** [comment]
Yes, though I think leaving those specifically for tests is preferred, instead of adding directly to the `MeterRegistry` interface

**Comment by trustin** [comment]
> Yes, though I think leaving those specifically for tests is preferred, instead of adding directly to the MeterRegistry interface

Fine by me as well.

**Comment by jkschneider** [comment]
All of the `findXXX` methods that existing previously have been consolidated into a fluent finder on `MeterRegistry` that looks like:

```
Optional<Timer> found = registry.find("timer")
   .tags("region", "test")      // assert that this tag exists
   .value(Statistic.Count, 1.0) // assert that the timer count has a certain value
   .timer();                    // assert that the meter is a Timer
```

**Comment by trustin** [comment]
Beautiful. Thanks a lot!
