### ISSUE TITLE
Migrate to drop wizard

### ISSUE THREAD

**Issue by genx2010** [micrometer-metrics/micrometer#891]
We have bunch of customize dropwizard reporters built to report to various legacy monitoring tools. Since we used dropwizard, most of the API accepts MetricRegistry as input and it seamlesssly report to dorwnstream system. Can you please help me to make all these reportors (note that reporters are tied/mapped to existing legacy system) reusable if I migrate to micrometer?

**Comment by jkschneider** [comment]
Can you simply extend `DropwizardMeterRegistry`?
