### ISSUE TITLE
Different reporting frequency for different types of metrics in micrometer

### ISSUE THREAD

**Issue by andrsuh** [micrometer-metrics/micrometer#892]
There is no such ability to set different reporting frequency for different types of metrics in micrometer. For example I want send endpoints metrics with 10s step and the others with 5s step. It leads to necessity to make extra aggregations on server side...

**Comment by jkschneider** [comment]
> It leads to necessity to make extra aggregations on server side...

What do you mean by this?

**Comment by andrsuh** [comment]
For example I have 5s reporting frequency for all of the metrics. Micrometer pushes metrics to Elasticsearch. In Kibana I would like to have a chart that shows mean execution time for certain endpoint for each minute. But I can't calculate average execution time for minute as average of averages over all 5 second periods

**Comment by jkschneider** [comment]
But you could a 1-minute mean as the sum of totals divided by the sum of counts right? Arbitrary time aggregation on the server-side is why we ship those independently.

**Comment by andrsuh** [comment]
But seems like It would be easier just have an ability to set different steps to Meters on client side? Probably I'm wrong and don't understand. Could you explain?

**Comment by jkschneider** [comment]
I doubt you will find there to be much utility in the precomputed average anyway. After all, it is only an average for a particular combination of name and tags. If you want to get the average for an endpoint, for example, how would you aggregate averages of successful/non-successful statuses, methods, exceptions, etc.? You wind up running into the same problem you ran into with trying to aggregate across time: you can't average averages.

As an aside, and completely unrelated to your request, be sure to [read this](http://latencytipoftheday.blogspot.com/2014/06/latencytipoftheday-average-random.html) about averages.
