### ISSUE TITLE
2018-10-03 19:50:05 io.micrometer.elastic.ElasticMeterRegistry [ERROR] Error connecting to http://localhost:9200: java.net.MalformedURLException: For input string: "9200metrics-2018-10"

### ISSUE THREAD

**Issue by andrsuh** [micrometer-metrics/micrometer#896]
I think It is because of absence of leading slash before the index name in the class ElasticConfig?
Maybe it is worth to add.

**Comment by izeye** [comment]
@andrsuh Thanks for the report!

It seems to have been introduced in 5f198e394b629529824393239932c5013e6c8527. I created #897 to resolve it.

**Comment by jkschneider** [comment]
This has been resolved incidentally with dd62f0c8 for #842.
