### ISSUE TITLE
Provide autocompletable @ConfigurationProperties for registry configs

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#90]
From #68:

> As we are at it, is it feasible to integrate the spring-boot-configuration-processor so that any @ConfigurationProperties are autocompletable in application.yml where there is IDE support?

cc / @mweirauch

**Comment by mweirauch** [comment]
Since 'metrics-spring' has vaporized with 0c23dc8ace863ef0fea4e61d195c5c236c64c25f the only place to add would be for 'metrics-spring-legacy', right?
What is happening to Spring 5 and Spring Boot 2 support? Some place to read about the bigger plans?

**Comment by jkschneider** [comment]
A [PR is open](https://github.com/spring-projects/spring-boot/pull/9970) in Spring Boot 2 where we plan to incorporate Micrometer out-of-the-box.

I'm working on this issue and #96 right now, and will update the Boot 2 PR when complete.

We'll put out a blog post on the big picture on the Spring blog in about 2 weeks when Spring Boot M4 and the first 1.0 milestone of Micrometer land.
