### ISSUE TITLE
Align Jersey tags with Web MVC

### ISSUE THREAD

**Issue by wilkinsona** [micrometer-metrics/micrometer#900]
There are a couple of areas where it would be good to align Jersey tags with those for Web MVC:

1. Provide a `JerseyTags` class akin to `WebMvcTags` and change `DefaultJerseyTagsProvider` to be a thin wrapper around it.
2. Add an `outcome` tag as was added for Web MVC in https://github.com/micrometer-metrics/micrometer/pull/881.

**Comment by izeye** [comment]
@wilkinsona Thanks for the suggestion! I created #907 to resolve this.
