### ISSUE TITLE
Backport: MeterFilter and MeterRegistryCustomizer beans are not ordered

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#918]
Backport the fix from Spring Boot 2 to micrometer-spring-legacy for https://github.com/spring-projects/spring-boot/issues/14780

**Comment by izeye** [comment]
@shakuzen I created #919 to resolve this.

**Comment by shakuzen** [comment]
Done via #919. Thanks, Johnny!
