### ISSUE TITLE
Configuration property javadoc could not use Javadoc tags

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#932]
The field javadoc for configuration properties can't use javadoc tag as it's used as the source for the key's description.

There is [an example here](https://github.com/micrometer-metrics/micrometer/blob/fee5b350e6c810e85358f0aebac09f4c323293e3/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/appoptics/AppOpticsProperties.java#L35). It would be nice to review the others to see if that pattern isn't used anywhere else.

**Comment by snicoll** [comment]
Can we reopen this please? This commit adds even more javadoc tags. None of the `{@` thing is supported.

**Comment by izeye** [comment]
@snicoll If the commit you pointed is 3cd2dab131072ad3ecd9c723e5137dde7dfa5feb, it's for `AppOpticsConfig`, not for `AppOpticsProperties`. `AppOpticsProperties` has been fixed in 289977bcdc14fa85a5b25dd4efbb12e72bcbdb48.

I'll reopen this to check there are more cases across codebase.

**Comment by izeye** [comment]
And I'll also align Javadoc for configuration properties with Spring Boot 2.x's if possible.

**Comment by snicoll** [comment]
Thanks @izeye

**Comment by izeye** [comment]
@snicoll @jkschneider I didn't find any issue with Javadoc at least in configuration properties for meter registries. I created #938 to align configuration properties for meter registries with Spring Boot 2.x.
