### ISSUE TITLE
Inconsistent name for AppOpticsProperties#token

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#933]
Micrometer has the concept of `apiToken` that is used for several registries but the name for AppOptics is token.

We've decided to harmonize in Spring Boot so that it's called `apiToken`. An harmonization here would be most welcome. 

If this has to be named `token` we can adapt the other way in Spring Boot.

**Comment by izeye** [comment]
@snicoll Thanks for the suggestion! It seems reasonable to me, so I created #937 to resolve this.
