### ISSUE TITLE
AppOpticsConfig does not have a `DEFAULT` implementation

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#935]

**Comment by izeye** [comment]
@snicoll [`AppOpticsConfig` has a mandatory field](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-appoptics/src/main/java/io/micrometer/appoptics/AppOpticsConfig.java#L40-L48), so it's not possible to have a valid `DEFAULT`. There were some invalid `DEFAULT` constants and they were removed in https://github.com/micrometer-metrics/micrometer/pull/894.

**Comment by snicoll** [comment]
Makes sense, sorry for the noise.
