### ISSUE TITLE
Why does Counter.increment() produce a metric incremented by 0.1?

### ISSUE THREAD

**Issue by lukaszkrawiec** [micrometer-metrics/micrometer#940]
I apologize if this is obvious to someone familiar with metric systems - I'm a novice in this area.

**Environment: Spring Boot 2.0 / StatsD**

When I create a Counter metric and increment it by the default value of 1.0, the value of the metric being published is 0.1

For example, if the counter was incremented twice in some publish interval, this is what gets emitted to the StatsD port.

```metric.name:0.2|g```

Two questions:
- Why is this the case?
- If I want to create a chart with the absoulute number of this metric, is it a good idea to increment the counter by ```10```?

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/47094816-914f0a80-d1f1-11e8-91e4-084209422c8e.png)

Produces:

`my.counter:1|c|#statistic:count`

What am I missing?
