### ISSUE TITLE
MemoryLeak throught PauseDetectorThread

### ISSUE THREAD

**Issue by HansPeterIngo** [micrometer-metrics/micrometer#946]
We want to reduce the systems involved. Thus we want to use Micrometer not only for our metrics but for our monitoring too.

Per request we add a `SimpleMeterRegistry` which then records all meters associated to an `UUID`:
```
final UUID uuid = uuidProvider.getUUID();
SimpleMeterRegistry simpleMeterRegistry = new SimpleMeterRegistry();
simpleMeterRegistry.config().meterFilter(new MeterFilter() {
	@Override
	public MeterFilterReply accept(Meter.Id id) {
		return id.getTag("UUID").equals(uuid.toString()) ? MeterFilterReply.ACCEPT : MeterFilterReply.DENY;
	}
});

Metrics.addRegistry(simpleMeterRegistry);
Object result = joinPoint.proceed();
Metrics.removeRegistry(simpleMeterRegistry);

LOG.info(simpleMeterRegistry.find("rest_requests").timer().measure().toString());
return result;
```

Additionally we set some global configuration to ignore the UUID tags.
```
@Bean
public MeterRegistryCustomizer meterRegistryCustomizer() {
	return new MeterRegistryCustomizer() {
		@Override
		public void customize(MeterRegistry registry) {
			MeterRegistry.Config config = registry.config();
			config.meterFilter(MeterFilter.ignoreTags("UUID"));
		}
	};
}
```

Around the endpoints we create then timers for the requests

```
Timer timer = Metrics.timer("rest_requests",
		"resource", joinPoint.getTarget().getClass().getSimpleName(),
		"method", joinPoint.getSignature().getName(),
		"UUID", uuidProvider.getUUID().toString());
long start = System.currentTimeMillis();
try {
	return joinPoint.proceed();
} finally {
	long duration = System.currentTimeMillis() - start;
	timer.record(duration, TimeUnit.MILLISECONDS);
}
```

Besides the SimpleMeterRegistry, we use Prometheus to report the metrics. This solution seems to work, as it aggregates the meters per UUID for each request and reports them globally with prometheus. 

Nevertheless as we create more and more Timers and MeterIDs there is some problems with the `pauseDetectorCache` in `AbstractTimer` and some Lambda's created in `AbstractTimer`. The Timers don't get garbage collected.

Are we misusing micrometer or is this a valid application of the system. Can the `pauseDectectorThread` exclusivily use weak references for the timers so they could be gargabe collected?

**Comment by izeye** [comment]
@HansPeterIngo I'm not sure I'm understanding this but do you mean you're creating a `MeterRegistry` on every request? If so, why not just creating it once and using it?

**Comment by HansPeterIngo** [comment]
Yes, we create it on every request, because we want the meters aggregated for this particular requests. When there is only on meterregistry and there are parallel requests, the meters are not correct. I tried different solutions using threadlocal MeterRegistries and a MeterRegistry decorated with an advices which only let's calls through which are from the associated thread. Both of the latter solutions haven't worked. The one with the threadlocal Regestry had problems because the meter had only be created for the first thread. On any request later the meters haven't been recorded. With the advice we had the problem that some methods are called on package visibility. The advice haven't fired on those. Nevertheless using reflection on each meter creates some pressure on the application which is potentially a bad thing.

**Comment by jkschneider** [comment]
@HansPeterIngo Micrometer is intended to collect and record aggregate metrics. Creating a registry per request significantly deviates from that goal. If you'd like to see information about per request metrics, I'd suggest you look at a distributed tracing system like Sleuth/Zipkin.
