### ISSUE TITLE
InfluxDB returns "Unable to parse" after upgrading

### ISSUE THREAD

**Issue by lukas-krecan-lt** [micrometer-metrics/micrometer#948]
After upgrading from Spring Boot 2.1.0.M4 to RC1 (micrometer 1.1.0.m1 to 1.1.0.rc1) Influx metric registry started to return following error message:

`InfluxMeterRegistry [][] authUser= failed to send metrics to influx: {"error":"unable to parse '\u001f\ufffd\u0008\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd[\ufffds\ufffd8\u0014\ufffd\ufffd\ufffd\ufffdm/\u000eAB\u0002\ufffd\ufffd\ufffdN6\ufffd\ufffd\ufffd~Mӽe\u0026#\ufffdlӂ`\ufffdp\ufffd\ufffd\ufffd\ufffd}\u001f\ufffd\ufffd\ufffd': missing fields\nunable to parse '\u0010\ufffd\ufffd\ufffd\\\ufffd8\ufffd\ufffd{\ufffd?\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd': missing fields\nunable to parse '\ufffdxb#\ufffdXI\u000f\ufffd3Q\ufffd\ufffdRh\ufffd\ufffd\ufffdI\ufffd\ufffd\u001bY\ufffdٺ\ufffd\ufffd\ufffd\ufffdˈDK\ufffd8#\ufffd\ufffd\ufffd$\ufffdO\ufffd\\\u001a\ufffd\ufffd\ufffd桔\ufffd\ufffd\ufffdW\ufffdb#\ufffdZ\ufffd}\ufffd\ufffd\u0017\ufffd\u0006\ufffdEȏ\ufffd \ufffdo\u003enr/\ufffdy\ufffd\u001f\ufffd\\|9\u0010\u0026\ufffd\u0014\ufffd\ufffd\u0014\ufffdP\ufffdi2\ufffdI\ufffd\ufffd\ufffd\ufffd-E,;Q\u0010\ufffdI\ufffd\u0013\ufffdB\ufffd6\ufffd\ufffd*\ufffdAsO˿k\ufffdW\ufffd+/\ufffdĲ4i\ufffd\ufffd\ufffdT\\\ufffd\ufffd0\ufffd\"\ufffd\ufffdF\u0018y\ufffd\ufffd\ufffd\ufffd\u0016Z\u0017\ufffd\ufffd\ufffd?n?̊\ufffd\ufffd]\ufffd\ufffd\ufffd\ufffdw7\ufffd\ufffd\ufffdy\ufffd\ufffd\ufffd\ufffd\ufffd': invalid field format\nunable to parse '\ufffdVWs\ufffd\ufffdY\ufffd\ufffd\ufffd\ufffd\u0006]\ufffdnV]\ufffd\ufffd\ufffd\ufffd]\ufffdߕN\u0013\t\ufffd4/͟\ufffdP\ufffd\ufffd\u000eT_\ufffd\ufffd)VZ\ufffd\u0017U\ufffd\ufffd\ufffdY\\\ufffd\ufffd\ufffdk.\ufffd\ufffd\ufffd\ufffd,\ufffd\ufffdc\u001fy\u001c\u0007\u0011\ufffd\ufffdc\ufffd\u003c\u0016ƋE\ufffd\ufffd\ufffd\ufffdcYu\u0018exD\u003c\u0002\ufffdz\u001f\u0013-\u0001\ufffd\ufffd\ufffd`\ufffd\u0012a\ufffdW\ufffd\ufffdH\ufffd1\ufffd|\ufffdh\u0014\ufffd\ufffd\\-\u0016\ufffd\ufffd\ufffd{\ufffd\ufffd\ufffd\u0011\ufffdܗ\ufffd\"K\ufffd\ufffdLƈW\u0002\u003c\ufffd\ufffd\ufffd\u0011\ufffdW\ufffd\u0014\ufffd\ufffd\ufffd{\ufffd\ufffdSş\ufffd\"\ufffd޳\ufffd\ufffdX\ufffd\u000c\"\u003e\ufffd\ufffd\ufffd\u0004]\ufffd\ufffd\ufffdTiq\ufffd|\ufffd\u000fU\u0019`\u003c+\u0000ue\ufffd\ufffd\u0000\ufffdPG\u0016\ufffd\ufffd\"\ufffd\ufffd\ufffd%w\u0017?\ufffdŗj\ufffdl\ufffd\u000fݦ\ufffd\ufffd\ufffd\u0008w#\ufffd\ufffd\ufffdSc\ufffd\ufffd\ufffdM\u001aQ\ufffdV\ufffd(\ufffd\u0001': missing tag value\nunable to parse 'x\u001b \ufffd\u0006\ufffdI\ufffd5\ufffdA\ufffdJ\ufffd\ufffd+\ufffd\ufffdVJ@\ufffd\ufffd\ufffd\ufffd\ufffdå\ufffd\u0002\u0000\ufffd\ufffd\ufffdb\ufffda\u001b\ufffdm1\u0018\u0012\u001cG\ufffd\ufffd\ufffd֛tS\ufffd\ufffdZD\ufffd}\u0014\ufffd\u0013\ufffd\ufffd U\ufffderw\ufffdV\ufffd\ufffdf\u0015E\u000ca\ufffd\u001b\ufffdC!\u0011\u0000J\ufffd,\u0015\ufffd[\ufffd\ufffdե\ufffd\u0002^\ufffd\ufffd\u0014\u0004\u00183?8k](u\ufffdL\ufffd\ufffd\ufffd\u0003\ufffd\u0003\ufffd\u000c!FZ\u00006\ufffdj\ufffdQdY\u0011\ufffdO\u0008\ufffdq\u0018\ufffdVٮ*\ufffdg\ufffd\ufffdT\ufffd\ufffdէ\u0007\ufffd\u003c\u0018\ufffd\ufffdP\ufffdQ\ufffd\ufffd\ufffddW\ufffd\ufffd\ufffd\ufffd\u000b\ufffdLW/x\ufffd\ufffd.v\ufffd\u001f\ufffd\ufffd\u0001\ufffd\ufffd!\ufffd\ufffd\u0017J\u000e\ufffd\ufffdoo\ufffd\ufffd\ufffdۿ\ufffd\ufffdono\ufffd\u0004\u0011\ufffdl\t\ufffd\ufffdM-L\ufffd\ufffd\ufffd\ufffd\ufffdY\ufffdP@\u0016x$@$D;*\u0018n\ufffd ': invalid field format\nunable to parse '\u003c\ufffdSL\ufffd\u001d%$\ufffd#\u003e\ufffd\u0011\ufffdv+c?\ufffd_\u001f\ufffd\ufffd\u0018s\u0014\ufffd\ufffd\ufffd\ufffd\u001f\u0007\ufffd\ufffd\ufffd!\ufffd\ufffd}\u0004C\u000fi\ufffd\ufffd\u0000Գ\ufffd\ufffd\ufffd\ufffdB\ufffd\ufffd\r\ufffd\ufffdW\ufffd\u0026\ufffd\u0013)\ufffd_\ufffdTOK': missing fields\nunable to parse '\ufffdE\\\ufffdօ\u003e3kE\ufffdq\ufffdk8Nj\ufffdf\u0013\ufffdי\ufffd\ufffd\ufffd': missing fields\nunable to parse '8\ufffd̀Y7\ufffd\ufffd': missing fields\nunable to parse 'zr\ufffd\ufffd\ufffd\ufffdS\ufffdL\u0010\ufffd^\u001f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u001e\u0003\ufffd\ufffdw\u0017?C\ufffd\ufffd\u0003\ufffd\u0018k\u001d\ufffd\ufffd;\ufffdh\u000b\ufffd\ufffd|\u0018\ufffd\u0016\ufffdӎҎ\ufffd\ufffd\u0004': missing fields\nunable to parse 'K\ufffdX7FG\ufffd\ufffd\ufffd\ufffdi\ufffd\ufffd\u0002\ufffd\ufffdb\u0013\ufffd3|\u001fsk\ufffd\ufffdU|Q/\ufffdPJF\ufffdvA\ufffd\u0004\ufffdu\ufffdݽ\ufffd\ufffd\ufffd\u0013_R\ufffd\ufffd\u0017\ufffd'U|\u0006\ufffd\ufffd\ufffd\ufffdx\ufffd\ufffd\u0006\ufffd0@\ufffdc\u0001\ufffdK\ufffd\ufffd4\ufffd\ufffd\u003eBmn\ufffd\u001bb-\ufffd\ufffdM\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdP[\ufffd)8L': missing fields\nunable to parse '\u0001o\ufffd\ufffdԷۻ\ufffd\ufffd*ږ\ufffd\u000e\u00021\ufffd\ufffd\ufffdx\ufffdh\u0014\ufffd9Ţ\ufffdF9\ufffd\u0008Ba#p\u001d|\ufffd\u000c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffda\ufffd@\ufffd\ufffd;\u0008\ufffd\ufffdzB\u000f\ufffd\u0016\ufffd\ufffd3\ufffdVnr\ufffd\ufffd\u001c\ufffd\u0017\\\ufffdi\ufffd\u001by': missing fields\nunable to parse '\ufffd\u001cꌧ\ufffdx\ufffd\"H\u0026\u001c\u001d\u001c\ufffd\ufffdR\ufffd\u0013\u000b޷\ufffd\ufffd\ufffd%\ufffd\u001dqv\r9\ufffd\u0008\ufffd\u0018\ufffd\ufffd\ufffd[3\u001a\u0019[\ufffdG\ufffd\ufffdi\ufffd\ufffd6b\ufffdz\ufffd\u0001\ufffd}\ufffdt\ufffd}:f\u0011\rQ\u0014ve\ufffds\ufffdq\ufffd$\ufffdSP\ufffd\u0001k[\u0014\u0004ط\ufffd\u001f\ufffd\ufffdv\u0003\ufffdZ\u0016}\ufffd\ufffd\u000f=J\u0008\ufffd\ufffdZ\rD^D\ufffd ': invalid field format\nunable to parse 'w)Ʊ\u0017\ufffd\ufffd\u0010\ufffdbugGv\ufffd\ufffd\ufffd\ufffd\ufffdQ\u001b\ufffdjt\ufffd\ufffdđ\ufffdX\ufffd\u0012D\u00041L\ufffd\ufffd\ufffdT\ufffd\ufffd\ufffd\ufffd8\ufffd\u001c\ufffd\ufffd\u001c\ufffd\ufffd-\ufffd#\ufffd\ufffd\ufffd\ufffd\ufffdǲ\ufffd\ufffdYyE)\ufffd.\ufffd\ufffd\ufffd\ufffd53#\ufffd'\ufffd\ufffdyi\ufffdʵm\ufffdL\ufffdm\ufffd\ufffdB)\ufffd\ufffdJ\ufffd\ufffd\ufffd~\ufffdg\ufffd\u0004\ufffdm\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdt\ufffd\ufffdIy\u0004}\ufffd\u0015\ufffd\u0005\ufffdROn\ufffd\u001b\ufffd2z\u0006\ufffdf\ufffd\u0017-\ufffdO\ufffdЙ\ufffd\ufffdB\ufffd#\ufffdN2\ufffd:\ufffd\ufffd7\ufffdSk\ufffd\ufffd\ufffd \ufffd\\ԫo\ufffd\ufffdm\ufffd\ufffd\u003cqb\ufffd}\ufffd]V\ufffdq\u0014:Y\ufffd۲]\ufffdl\ufffd\ufffd\ufffd~[\ufffd\u001b\u00110\u0011m\u003cכ\ufffd\ufffd,\ufffd\ufffd\u0000sbI\u003e\ufffdmWӬ],\ufffd\ufffdv\ufffdO\ufffd\ufffd\ufffd\ufffd͐2\ufffdB\ufffd\ufffd\u0000ۍp\ufffd\ufffdÄ\ufffd\ufffd\ufffd\\G\ufffd#\ufffd\ufffd4\ufffdN_\ufffdŤ\u001cw\ufffd\ufffd\u0013\ufffd-\ufffd\ufffd\ufffd8\u001c\u0000\ufffd\u000b\ufffdO\ufffd\u0005\ufffd7\ufffd-*\\\ufffd:\u0016Y\u0011\u001a|\ufffdp+[\ufffd\ufffd\u0003\ufffdF/\u001e\ufffd\u003e}\ufffd\u003c\ufffdɷ\ufffd\ufffdv(\ufffdo\u0008\ufffdӓ\ufffdv}\ufffd9\ufffd\u000e\u000e\ufffd\ufffd\u001e\ufffd\u0018\ufffd\ufffd\ufffd\ufffdG1\u0014=d\ufffdܿ\ufffd\u0014\u001fϻ\ufffd\ufffd@o\ufffd\ufffdi\ufffd\u003ej\ufffdޑ\u001c\u0013$\ufffd=e\ufffd/\ufffd\ufffd\ufffd\u0005\ufffd\ufffdb\u001b\ufffd\ufffdy\u001a:\u0005\ufffd\ufffd`\ufffdlc=\ufffd\ufffdS6\ufffdc\ufffdt\ufffd\ufffd0h\ufffd\ufffd\ufffd\ufffd\u001f\ufffd\ufffd\ufffdK\ufffd\u001d\u00034O\ufffd\ufffd(d\u0016\ufffdց깗\ufffd\u0004\ufffd\ufffd\u0001L\ufffd\ufffdy\u00268\u0000\u0000': invalid boolean"}
`

**Comment by lukas-krecan-lt** [comment]
It's standard Spring Boot configuration without any custom metrics. The only difference against standard is that we are adding tags and using dot configuration

```java
    public static MeterFilter createCustomMetricTagsFilter(String appName, String environment) {
        List<Tag> tags = new ArrayList<>();
        tags.add(Tag.of("app",appName));
        tags.add(Tag.of("host", getHostname()));
        if (environment != null) {
            tags.add(Tag.of("env", environment));
        }

        return MeterFilter.commonTags(tags);
    }

    public static InfluxMeterRegistry createInfluxMeterRegistry(InfluxConfig config, Clock clock) {
        InfluxMeterRegistry registry = new InfluxMeterRegistry(config, clock);
        registry.config().namingConvention(new InfluxNamingConvention(NamingConvention.dot));
        return registry;
    }

```

**Comment by izeye** [comment]
I confirmed `Content-Encoding` header is missing, so I created #950 to fix this.

**Comment by izeye** [comment]
And this has been introduced with `HttpRequest` which has been added since 1.1.0-rc1. Changing this milestone to "1.1.0-rc.2".
