### ISSUE TITLE
DynatraceMeterRegistry not sending custom metric values

### ISSUE THREAD

**Issue by lautenb** [micrometer-metrics/micrometer#951]
`postCustomMetricValues()` is currently not invoked at any point. The condition in [DynatraceMeterRegistry.java#L107](https://github.com/micrometer-metrics/micrometer/blob/70ee77a71fdb916497d81790f9947e8dd5124bd8/implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceMeterRegistry.java#L107) can never be true. `!createdCustomMetrics.isEmpty()` is always false. The issue is that when creating custom metrics, they are not added to the `Set<String> createdCustomMetrics` [DynatraceMeterRegistry.java#L57](https://github.com/micrometer-metrics/micrometer/blob/70ee77a71fdb916497d81790f9947e8dd5124bd8/implementations/micrometer-registry-dynatrace/src/main/java/io/micrometer/dynatrace/DynatraceMeterRegistry.java#L57).

This [change](https://github.com/micrometer-metrics/micrometer/commit/dd62f0c8322031bc98c872965e420b132c68ed69#diff-e36ce589a0957331b0007085fc02b156L206) removed the line `createdCustomMetrics.add(customMetric.getMetricId());`. Was that by intention or an accident?

**Comment by izeye** [comment]
@lautenb Thanks for report! It seems removed accidentally. I created #952 to fix it.
