### ISSUE TITLE
PrometheusMeterRegistry should use CollectorRegistry.defaultRegistry instead of creating a new one?

### ISSUE THREAD

**Issue by dthong** [micrometer-metrics/micrometer#954]
In PrometheusMeterRegistry, the constructor was initialized with a new CollectorRegistry.
```
     public PrometheusMeterRegistry(PrometheusConfig config) {
        this(config, new CollectorRegistry(), Clock.SYSTEM);
    }
```
But from CollectorRegistry's document, it's recommended to use CollectorRegistry.defaultRegistry

>  * The majority of users should use the {@link #defaultRegistry}, rather than instantiating their own.
>  * <p>
>  * Creating a registry other than the default is primarily useful for unittests, or
>  * pushing a subset of metrics to the <a href="https://github.com/prometheus/pushgateway">Pushgateway</a>
>  * from batch jobs.

Is there any particular reason to create a new CollectorRegistry here? I'd like a have a single entry for all of my metrics, including custom metrics & micrometer's ones. Having different CollectorRegistry makes it harder to do so.

**Comment by jkschneider** [comment]
Feel free to inject your own `CollectorRegistry`, including the default one with [this constructor](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L61) if you'd like.

We will not use static references in Micrometer code except where necessary for the sake of test independence. The default collector registry, after all, is nothing more than a registry instantiated in the same way.
