### ISSUE TITLE
how can i get the throughput like the meter of Dropwizard. one_minute_rate,mean_rate etc.

### ISSUE THREAD

**Issue by zjw121461745** [micrometer-metrics/micrometer#955]
I am a freshman.I want to migrate the project from Dropwizard to Micrometer.io; But now i meet a problem, I am developing the msg client project, I should to record the throughput of the sended-message. I used meter in DropWizart.io, how can i do that using micrometer.io.

**Comment by jkschneider** [comment]
Micrometer timers always ship a count. How you get the rate depends on the backend. There is an example for Prometheus timer throughput [here](http://micrometer.io/docs/registry/prometheus#_timers), but again the query varies by monitoring system.

Please ask further questions like this on Stackoverflow or on slack.micrometer.io.
