### ISSUE TITLE
Data size metrics for Prometheus do not contain unit

### ISSUE THREAD

**Issue by breun** [micrometer-metrics/micrometer#97]
https://github.com/micrometer-metrics/micrometer/issues/80 added support for naming conventions, which when using Prometheus adds the unit (seconds) to the metric name when using `@Timed` on a REST controller, which is very nice!

However, it seems that metrics for data sizes don't contain units yet. I see the following for instance:

* jvm_buffer_memory_used
* jvm_buffer_total_capacity
* jvm_gc_live_data_size
* jvm_gc_max_data_size
* jvm_memory_committed
* jvm_memory_max
* jvm_memory_used

I guess those should all be postfixed with `_bytes`?

**Comment by jkschneider** [comment]
Good catch. I made a late commit in the 0.10.0.RELEASE to allow for specifying base units in distribution summaries and didn't go back and augment these gauges with base units
