### ISSUE TITLE
Sysdig statsD integration not working

### ISSUE THREAD

**Issue by brmakana** [micrometer-metrics/micrometer#970]
Hello,

I'm using micrometer version 1.1.0-rc.1 and trying to publish metrics with Spring Boot to Sysdig using their statsD detector. I'm able to see (via tcpdump) metrics sent via UDP as expected, but it appears the line format may not be correct as Sysdig's agents are ignoring my requests. 

According to here: https://sysdigdocs.atlassian.net/wiki/spaces/Monitor/pages/204832927/Integrate+StatsD+Metrics, the format should be:
METRIC_NAME#LABEL_NAME=LABEL_VALUE,LABEL_NAME...

and the allowed characters are: 
Allowed characters: a-z A-Z 0-9 _ .

However when I have a Spring Boot endpoint with URL path arguments (like /value/for/key/is/{key}), then those metrics are not being picked up; I believe it's because of the { and } characters. 

Is there any way to set which characters to allow, or strip out characters from metric names?

**Comment by brmakana** [comment]
My application.properties that apply:
```
management.metrics.export.statsd.host=127.0.0.1
management.metrics.export.statsd.port=8125
management.metrics.export.statsd.flavor=sysdig
```

**Comment by jkschneider** [comment]
@brmakana Sanitization for sysdig is done set [here](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/SysdigStatsdLineBuilder.java#L54). A pull request would be welcome.

**Comment by brmakana** [comment]
Thanks - will give it a try

**Comment by brmakana** [comment]
@jkschneider Gave it a shot: https://github.com/micrometer-metrics/micrometer/pull/973, let me know if you'd like any changes.
