### ISSUE TITLE
Meter registration memory and CPU performance improvements

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#971]

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/47545583-fcf44000-d8a1-11e8-9232-70a3b8e4d917.png)

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/47545886-80faf780-d8a3-11e8-8f04-522a5744aa8d.png)

**Comment by mweirauch** [comment]
@jkschneider I really tried to get ahold of the substantial change that improved the time spent on meter registration, but with this abysmal gradle lockfile stuff, I just gave up filtering the 223 files changed.
Could you describe in short what improved it?
Also, it looks like the `Counter.Builder` had a ride through the other Meter implementations. (Quite some occurrences of `@return The counter builder ...`.)

**Comment by jkschneider** [comment]
> Also, it looks like the Counter.Builder had a ride through the other Meter implementations. (Quite some occurrences of @return The counter builder ....)

Thanks @mweirauch. I'll fix this up!

**Comment by shakuzen** [comment]
@nyilmaz yes they are. The source is in the Micrometer `benchmarks` folder: https://github.com/micrometer-metrics/micrometer/blob/f1d21481e1214a0cca3d77fda2a52c12b06cb27b/benchmarks/benchmarks-core/src/main/java/io/micrometer/benchmark/compare/CompareCountersWithOtherLibraries.java
