### ISSUE TITLE
PostgreSQLDatabaseMetrics#runQuery does not advance JDBC cursor to next row

### ISSUE THREAD

**Issue by michaelbull** [micrometer-metrics/micrometer#979]
The [`runQuery`](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/db/PostgreSQLDatabaseMetrics.java#L282) method in `PostgreSQLDatabaseMetrics` does not call `resultSet.next()`.

The [`ResultSet`](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html) documentation states:

>Initially the cursor is positioned before the first row. The `next` method moves the cursor to the next row

As `next()` is not called, the `runQuery` method always fails with the following exception:

>ResultSet not positioned properly, perhaps you need to call next.

![](https://i.imgur.com/wCpVfP0.png)

As a result, none of the intended metrics are recorded.

**Comment by izeye** [comment]
Thanks for the report! It seems an oversight. I created #980 to fix this.
