### ISSUE TITLE
Improve resilience4j metrics

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#982]
Using gauges rather than `FunctionCounter`, etc.

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/CircuitBreakerMetrics.java

**Comment by izeye** [comment]
[Integration with Resilience4j lives in its own repo](https://github.com/resilience4j/resilience4j/tree/master/resilience4j-micrometer), the referenced class seems to be relocated in [TaggedCircuitBreakerMetrics](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/TaggedCircuitBreakerMetrics.java) and there's no usage on `FunctionCounter` on `master`. So this seems closable.
