### ISSUE TITLE
Statsd-registry pollutes sout with metrics output

### ISSUE THREAD

**Issue by fauscik** [micrometer-metrics/micrometer#984]
Since version 1.1 statsd-registry pollutes standard output with metrics. Probably it affects only telegraf flavour.

**Comment by fauscik** [comment]
And short PR for this:
https://github.com/micrometer-metrics/micrometer/pull/985

**Comment by izeye** [comment]
@fauscik Thanks for the report and the PR! It also affects [the 1.0.x line](https://github.com/micrometer-metrics/micrometer/blob/1.0.x/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/internal/TelegrafStatsdLineBuilder.java#L56).
