### ISSUE TITLE
Micrometer 1.0.7 incompatible with Spring Boot 2.0.6.RELEASE

### ISSUE THREAD

**Issue by ollio** [micrometer-metrics/micrometer#991]
The method `getTags` (v 1.0.6) from inner class Id of Meter was renamed to `getTagsAsIterable` (v 1.0.7). This breaks the API and the Spring boot dosen't start:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call the method io.micrometer.core.instrument.Meter$Id.getTagsAsIterable()Ljava/lang/Iterable; but it does not exist. Its class, io.micrometer.core.instrument.Meter$Id, is available from the following locations:

    jar:file:/opt/service/service.jar!/BOOT-INF/lib/micrometer-core-1.0.6.jar!/io/micrometer/core/instrument/Meter$Id.class

It was loaded from the following location:

    jar:file:/opt/service/service.jar!/BOOT-INF/lib/micrometer-core-1.0.6.jar!/


Action:

Correct the classpath of your application so that it contains a single, compatible version of io.micrometer.core.instrument.Meter$Id
```

**Comment by jkschneider** [comment]
@ollio `getTagsAsIterable()` wasn't introduced until 1.1.0. It was also additive. I'm guessing you have a mixture of Micrometer versions on your classpath.

**Comment by ollio** [comment]
I had used spring boot-cloud Finchley.SR1, Spring-Boot 2.0.5.RELEASE and micrometer-registry-prometheus:latest.release

Now I have upgraded to Finchley.SR2, Spring-Boot 2.0.6.RELEASE and explizite added io.micrometer:micrometer-core:latest.release 

This seems to work for me

**Comment by shakuzen** [comment]
If using Spring Boot, it is best to use its dependency management to avoid incompatible/mixed versions. I think the situation was as Jon suggested. `micrometer-registry-prometheus:latest.release` will pull in 1.1.0 right now, but Spring Boot 2.0.x manages micrometer dependencies to 1.0.x (like micrometer-core).

**Comment by longye0914** [comment]
> I had used spring boot-cloud Finchley.SR1, Spring-Boot 2.0.5.RELEASE and micrometer-registry-prometheus:latest.release
> 
> Now I have upgraded to Finchley.SR2, Spring-Boot 2.0.6.RELEASE and explizite added io.micrometer:micrometer-core:latest.release
> 
> This seems to work for me

This work for me, TKS
