### ISSUE TITLE
micrometer-spring-legacy does not respect actuator settings

### ISSUE THREAD

**Issue by frehov** [micrometer-metrics/micrometer#992]
The legacy bridge to spring boot 1.5 does not respect spring boot actuator disabled setting.
Even setting `endpoints.prometheus.enabled=false` does not stop the prometheus endpoint of being initialized.

We're explicitly setting the property `management.metrics.export.prometheus.enabled=true` to enable autoconfiguration, but expect that we should be able to disable or enable the prometheus endpoint at will using either `endpoints.enabled` or `endpoints.prometheus.enabled`

we have the following dependencies:
- spring-boot-starter-actuator
- micrometer-spring-legacy
- micrometer-registry-prometheus
- simpleclient_hotspot (prometheus)
- simpleclient_servlet (prometheus)
- simpleclient (prometheus)

Setting the property
- `endpoints.enabled=false`
- (`endpoints.prometheus.enabled=false`)
- `management.metrics.export.prometheus.enabled=true` 

### Expected result
all actuator endpoints to be disabled and a PrometheusMeterRegistry bean to be available

### Actual result
all actuator endpoints except `/prometheus` is disabled, and the PrometheusMeterRegistry bean is available.

All other spring boot actuators are not even registered whereas the prometheus one is registered with a message saying "this endpoint is disabled".

**Comment by izeye** [comment]
@frehov Thanks for the report! I created #1000 to resolve this.
