### ISSUE TITLE
How to specify interval/delay between CloudWatch metric push

### ISSUE THREAD

**Issue by Aleksandr-Filichkin** [micrometer-metrics/micrometer#999]
Hi,

Could you explain how often metrics are pushed to CloudWatch? We don't have any options, only bulk size.

**Comment by izeye** [comment]
@Aleksandr-Filichkin `CloudWatchConfig.step()` should work for it. Doesn't it work for you?

**Comment by Aleksandr-Filichkin** [comment]
@izeye, It works thanks
management.metrics.export.cloudwatch.step=30s
